### ISSUE TITLE
[v4] IRequiring module "node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/index.ts", which threw an exception: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by fukemy** [gorhom/react-native-scroll-bottom-sheet#1000]
HI, i got. this error with v4
![Screen Shot 2022-06-21 at 11 12 29](https://user-images.githubusercontent.com/8202437/174714685-dad2eef5-d5d9-4b0f-8859-39f6724f62c1.png)

step,
```
npm i @gorhom/bottom-sheet
npx pod-install
```

run app

**Comment by fukemy** [comment]
ok bye

**Comment by airowe** [comment]
I'm having the same issue. Did anyone find a solution here?
