### ISSUE TITLE
[v4] | [v2] Issue in resolving the test case for BottomSheetTextInput.

### ISSUE THREAD

**Issue by Ekaanth** [gorhom/react-native-scroll-bottom-sheet#1005]
While trying to provide the test cases for the application I have been having difficulty mocking the call for `BottomSheetTextInput`. I'm using the initial mock that was provided in the earlier version (Thanks a lot for that):

I try to mock for the `BottomSheetTextInput` something like this:

```
jest.mock('@gorhom/bottom-sheet', () => {
  const MockBottomSheet = require('@gorhom/bottom-sheet/mock');
  const originalModule = jest.requireActual('@gorhom/bottom-sheet');

  return {
    __esModule: true,
    BottomSheetTextInput: originalModule.BottomSheetTextInput,
    ...MockBottomSheet,
  };
});

```

still facing an issue of `thrown: "'useBottomSheetInternal' cannot be used out of the BottomSheet!"` Which I'm unable to resolve. It would be amazing if you can look into this issue by providing a mock implementation for this problem.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.3.1  |
| react-native                    | 0.67.3   |
| react-native        |  17.0.2 |
| react-native-gesture-handler    | ^2.4.2  |
## Steps To Reproduce

1. Implement the bottom sheets component and it contains bottomsheetinputtext.
2.
3. 

Describe what you expected to happen:

1. resolving the issue that I'm getting for bottom sheet test case.
2.

**Comment by banisetticn** [comment]
I am also facing same issue

**Comment by Ekaanth** [comment]
Any update on this issue?

**Comment by developius** [comment]
Following @pedrorestrepo's comment [here](https://github.com/gorhom/react-native-bottom-sheet/issues/932#issuecomment-1137645269), this is what I did to get the mock working:

```typescript
import mockBottomSheet from '@gorhom/bottom-sheet/mock';

jest.mock('@gorhom/bottom-sheet', () => ({
  ...mockBottomSheet,
  __esModule: true,
}));
```

**Comment by Ekaanth** [comment]
@developius  I do mock the same way right now, but I'm getting an error when I have the sheets that use `BottomSheetTextInput.` I t would be nice that `BottomSheetTextInput` is included in the mockup.

**Comment by vdr-mm-quan** [comment]
Hi guys, Hi @Ekaanth,
Ekaanth I'm still facing the same issue? any helps? Thank you guys so much. Really appreciated!

<img width="1139" alt="Screenshot 2023-09-26 at 17 28 23" src="https://github.com/gorhom/react-native-bottom-sheet/assets/133188379/263038ce-7736-4cbe-9ce7-2b9e385016d3">

<img width="616" alt="Screenshot 2023-09-26 at 17 29 44" src="https://github.com/gorhom/react-native-bottom-sheet/assets/133188379/a26a016e-d74c-4a46-b4f9-020fccfedb32">

**Comment by avencat** [comment]
Hi @vdr-mm-quan, if you're still looking for a solution, you can use this mock instead of the basic one:
```ts
jest.mock('@gorhom/bottom-sheet', () => {
  const { ScrollView, TextInput } = jest.requireActual('react-native')

  return ({
    ...require('@gorhom/bottom-sheet/mock'),
    __esModule: true,
    BottomSheetScrollView: ScrollView,
    BottomSheetTextInput: TextInput
  })
})
```
