### ISSUE TITLE
[v4] | [v2] Bottom Sheet does not open on top of React Native Modal

### ISSUE THREAD

**Issue by banisetticn** [gorhom/react-native-scroll-bottom-sheet#1006]
# Bug

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.2  |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.3.1  |
| react-native-gesture-handler    | 2.2.0   |

**Comment by jckyeh** [comment]
Did you end up figuring this out @banisetticn? Also facing the same issue.
