### ISSUE TITLE
Export createBottomSheetScrollableComponent

### ISSUE THREAD

**Issue by alexco2** [gorhom/react-native-scroll-bottom-sheet#1012]
# Feature Request

## Why it is needed

With the new `FlashList` from shopify, it would be great to be able to use it with `BottomSheet`. For that I propose to export `createBottomSheetScrollableComponent`, so a -`BottomSheetFlashList`- can be build

I have a really big `FlatList` inside a `BottomSheet`, that has infinitive scrolling. It would be great to get the performance boost from `FlashList`

## Possible implementation

I guess it would be straight forward to export `createBottomSheetScrollableComponent`. Perhaps it should be mentioned in the docs, that the component needs to be memoized as well.

### Code sample

```
const BottomSheetFlashListComponent = createBottomSheetScrollableComponent<
  BottomSheetFlatListMethods,
  BottomSheetFlatListProps<any>
>(SCROLLABLE_TYPE.FLATLIST, AnimatedFlashList);

const BottomSheetFlashList = memo(BottomSheetFlashListComponent);

```

**Comment by viet-dopamineapp** [comment]
i am looking forward to implementing this too

**Comment by RichardLindhout** [comment]
How did you solve this alexco2?

**Comment by RichardLindhout** [comment]
Because it's exported but still not working for me

**Comment by RichardLindhout** [comment]
This works for me
```tsx
import * as React from 'react';
import { FlashList, FlashListProps } from '@shopify/flash-list';

import Animated from 'react-native-reanimated';
import {
  BottomSheetFlatList as BSF,
  createBottomSheetScrollableComponent,
  SCROLLABLE_TYPE,
} from '@gorhom/bottom-sheet';

const F2 = React.forwardRef((props: any, ref) => {
  return (
    <FlashList
      {...props}
      overrideProps={{
        ref,
      }}
    />
  );
});

const AnimatedFlashList = Animated.createAnimatedComponent<FlashListProps<any>>(
  F2 as any,
);

const BottomSheetFlatListComponent = createBottomSheetScrollableComponent(
  SCROLLABLE_TYPE.FLATLIST,
  AnimatedFlashList,
);

const BottomSheetFlatList = React.memo(BottomSheetFlatListComponent);
BottomSheetFlatList.displayName = 'BottomSheetFlatList';

export default BottomSheetFlatList as typeof BSF;


```

**Comment by alexco2** [comment]
Yes, there is more to it than just wrapping `FlashList` in `createBottomSheetScrollableComponent` to make it work. Since it is now technically possible to make `FlashList` and `BottomSheet` compatible, I closed the issue.  I haven't worked on making `FlashList` compatible yet. 
If you Sponsor @gorhom though, you will gain access to his version of a compatible `FlashList`.

**Comment by BalogunofAfrica** [comment]
Pending when the implementation is available publicly, you can pass `BottomSheetScrollView` to `renderScrollComponent` in your `FlashList` rendered in a `BottomSheet`. This prop is the same as the `externalScrollView` of RecyclerListView.

```tsx
import { BottomSheetScrollView } from "@gorhom/bottom-sheet";
...
...
...
<BottomSheet>
    ....
    <FlashList
        ...
        renderScrollComponent={BottomSheetScrollView}
        ...
        />
    ...
</BottomSheet>
```

**Comment by jittuu** [comment]
> Pending when the implementation is available publicly, you can pass `BottomSheetScrollView` to `renderScrollComponent` in your `FlashList` rendered in a `BottomSheet`. This prop is the same as the `externalScrollView` of RecyclerListView.
> 
> ```tsx
> import { BottomSheetScrollView } from "@gorhom/bottom-sheet";
> ...
> ...
> ...
> <BottomSheet>
>     ....
>     <FlashList
>         ...
>         renderScrollComponent={BottomSheetScrollView}
>         ...
>         />
>     ...
> </BottomSheet>
> ```

It doesn't work for me. Got this error 😔

```
TypeError: property is not configurable
```

**Comment by oguzhnatly** [comment]
> ```tsx
> 
>         renderScrollComponent={BottomSheetScrollView}
> ```

Works like a charm, thanks a lot!

**Comment by oguzhnatly** [comment]
> This works for me
> 
> ```tsx
> import * as React from 'react';
> import { FlashList, FlashListProps } from '@shopify/flash-list';
> 
> import Animated from 'react-native-reanimated';
> import {
>   BottomSheetFlatList as BSF,
>   createBottomSheetScrollableComponent,
>   SCROLLABLE_TYPE,
> } from '@gorhom/bottom-sheet';
> 
> const F2 = React.forwardRef((props: any, ref) => {
>   return (
>     <FlashList
>       {...props}
>       overrideProps={{
>         ref,
>       }}
>     />
>   );
> });
> 
> const AnimatedFlashList = Animated.createAnimatedComponent<FlashListProps<any>>(
>   F2 as any,
> );
> 
> const BottomSheetFlatListComponent = createBottomSheetScrollableComponent(
>   SCROLLABLE_TYPE.FLATLIST,
>   AnimatedFlashList,
> );
> 
> const BottomSheetFlatList = React.memo(BottomSheetFlatListComponent);
> BottomSheetFlatList.displayName = 'BottomSheetFlatList';
> 
> export default BottomSheetFlatList as typeof BSF;
> ```

Works like a charm, thank you!
