### ISSUE TITLE
[v4] BottomSheet responds slowly to snap point changes

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-scroll-bottom-sheet#1017]
# Bug

There seem to be a bug with BottomSheet not responding in time for snap point changes. This issue does not appear to be affecting BottomSheetModal.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.64.3  |
| react-native-reanimated         | ~2.2.0   |
| react-native-gesture-handler    | ~1.10.2   |

## Steps To Reproduce

1. Click 300 : BS should open to snap point 300
2. Click 300 + 500 : BS will now have an additional snap point. Pull up to get to 500
3. Drag BS down to close
At some point BS will stop acting properly. 300 + 500 will automatically pull the BS up to the second snap point, and then after closing and clicking on "300", the BS will open to snap point 500 with white BG below.

## Reproducible sample code

Have a look at https://snack.expo.dev/@kickbk/bs-v4-snap-points-issue

**Comment by thanhdevapp** [comment]
when add code Backdrop, modal render too slow, remove code work good

      backdropComponent={(props) => (
        <BottomSheetBackdrop
          {...props}
          appearsOnIndex={0}
          disappearsOnIndex={-1}
        />
      )}
      
      
      remove backdropComponent => work fast

**Comment by Roka20012** [comment]
@thanhdevapp what if I need a backdrop?
