### ISSUE TITLE
Is there any plan integrate FlashList to this library  ?

### ISSUE THREAD

**Issue by chanphiromsok** [gorhom/react-native-scroll-bottom-sheet#1021]
# Feature Request

 Integrate FlashList
 link: https://github.com/Shopify/flash-list

## Why it is needed

The FlashList is maintained by Shopify and Fast & performant React Native list. No more blank cells

**Comment by Dani-Boy92** [comment]
Same question

**Comment by smfunder** [comment]
I ask the same here! FlashList is way more performance than FlatList specially in complex and large layouts, so it would be an amazing support.

**Comment by Acetyld** [comment]
Same here!
