### ISSUE TITLE
[v4] Android shadows are barely noticeable

### ISSUE THREAD

**Issue by ZRunner** [gorhom/react-native-scroll-bottom-sheet#1026]
# Bug

On Android, shadows applied to the BottomSheetModal are virtually invisible, even with a very high value of elevation.

To make sure no other library or config was interfering, I started a fresh project under React Native 0.68 with only the minimal libraries and files. I then copy-pasted the [usage example](https://gorhom.github.io/react-native-bottom-sheet/modal/usage/) provided in your documentation, and applied some shadow styles to the modal component. I made sure they were visible by putting high opacity and elevation values, as well as a low radius. I tried with and without `shadowColor`, as well as with and without `backgroundColor`. The used code can be found at the end of this report.

As you can see on this screenshot, the iOS shadow is correctly visible, but the Android one is not. If I use an even lower elevation value, the shadow will completely disappear and the modal will blend into the app background.

<img width="880" alt="Capture d’écran 2022-07-11 à 16 47 09" src="https://user-images.githubusercontent.com/30912430/178292772-7a1c8606-52ef-4630-844c-70b9a917b45d.png">

I also made sure this wasn't an Android or React Native bug by applying shadows to other objects (like buttons and views), which worked fine.

I found the ticket #734, and especially [this comment](https://github.com/gorhom/react-native-bottom-sheet/issues/734#issuecomment-1150977998) pretending to solve the issue, but as you can see in my MCVE it didn't work for me.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.2   |
| react-native                    | 0.68.2   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Fetch the [usage example](https://gorhom.github.io/react-native-bottom-sheet/modal/usage/) from the doc
2. Apply shadows styling to the `BottomSheetModal` style prop.
3. Run on Android and observe the (lack of) result

Describe what you expected to happen:

1. I was expecting the shadow to be more visible on Android

## Reproducible sample code

<details>
  <summary>Minimal sample code</summary>

  ```js

  import React, {useCallback, useMemo, useRef} from 'react';
  import {View, Text, StyleSheet, Button} from 'react-native';
  import {BottomSheetModal, BottomSheetModalProvider} from '@gorhom/bottom-sheet';
  import {GestureHandlerRootView} from 'react-native-gesture-handler';

  const App = () => {
    // ref
    const bottomSheetModalRef = useRef<BottomSheetModal>(null);
  
    // variables
    const snapPoints = useMemo(() => ['25%', '50%'], []);
  
    // callbacks
    const handlePresentModalPress = useCallback(() => {
      bottomSheetModalRef.current?.present();
    }, [bottomSheetModalRef]);
  
    // renders
    return (
      <GestureHandlerRootView style={{flex: 1}}>
        <BottomSheetModalProvider>
          <View style={styles.container}>
            <Button onPress={handlePresentModalPress} title="Present Modal" />
            <BottomSheetModal
              ref={bottomSheetModalRef}
              index={1}
              style={styles.sheet}
              snapPoints={snapPoints}>
              <View style={styles.contentContainer}>
                <Text>Awesome 🎉</Text>
              </View>
            </BottomSheetModal>
          </View>
        </BottomSheetModalProvider>
      </GestureHandlerRootView>
    );
  };
  
  const styles = StyleSheet.create({
    sheet: {
      backgroundColor: 'white',
      borderRadius: 15,
      shadowOpacity: 0.37,
      shadowRadius: 5,
      shadowColor: 'blue',
      elevation: 5,
    },
    container: {
      flex: 1,
      padding: 24,
      justifyContent: 'center',
      backgroundColor: 'white',
    },
    contentContainer: {
      flex: 1,
      alignItems: 'center',
    },
  });
  
  export default App;
   ```
</details>

**Comment by thame** [comment]
My solution was to use a separate shadow component. I chose [`react-native-shadow-2`](https://github.com/SrBrahma/react-native-shadow-2#%EF%B8%8F-faq) which depends on `react-native-svg` and works with Expo.

I placed the Shadow component at the top of my custom Handle component with the following properties and it's working great with identical appearance of shadow on iOS and Android:

```
    <>
      <Shadow
        sides={'top'}
        startColor={'rgba(0,0,0,0.1)'}
        finalColor={'rgba(0,0,0,0)'}
        distance={20}
        viewStyle={{alignSelf: 'stretch'}}
      >
        <View />
      </Shadow>
      <Animated.View style={handleStyle} />
    </>
```

**Comment by ZRunner** [comment]
I'd prefer to avoid installing a whole new lib just for one shadow, but I guess I don't really have the choice until this bug is fixed lol

Thanks for the suggestion

**Comment by afizboltz** [comment]
maybe you can add `borderWidth: 0 ` in style. mine showing the shadow for android emulator

![BottomSheetShadow](https://user-images.githubusercontent.com/32946333/180402670-79c77377-c8a3-4677-8766-ba64eb64916b.png)



<img width="375" alt="Screenshot 2022-07-22 at 4 53 00 PM" src="https://user-images.githubusercontent.com/32946333/180404045-6737f88a-9d16-4f86-b546-6444cca3d50f.png">

**Comment by ZRunner** [comment]
hello, thanks for the suggestion!
Unfortunately I cannot seem to get a shadow as visible as yours, even with the exact same styling. Here's what I get:
<img width="380" alt="Capture d’écran 2022-07-22 à 11 43 19" src="https://user-images.githubusercontent.com/30912430/180412603-bd76a9c5-a784-4db0-ab38-7f5f0318b3dc.png">

While testing this, I noticed a weird behavior with an elevation of 1... it looks like the shadow is correctly rendered but cropped right on top of the sheet?
<img width="380" alt="Capture d’écran 2022-07-22 à 11 44 54" src="https://user-images.githubusercontent.com/30912430/180412989-e7381ef0-cd2a-4a2b-9a48-bb4cfdcb06e2.png">

I read somewhere that Android sometimes behaves strangely with shadows, and occasionally doesn't let them draw over neighboring components... could this be the cause of my bug?

**Comment by ZRunner** [comment]
This is still an issue but it looks like the lib is more or less dead anyway?

**Comment by Softkeydel** [comment]
@ZRunner 

Try using
borderWidth: 0,
borderTopLeftRadius:15,
borderTopRightRadius: 15

**Comment by matthintosh** [comment]
Hi @Softkeydel , I try your code and unfortunately this is not working.

**Comment by carlos-cne** [comment]
still a bug for me also.
I've tried the solutions commented in here, but without success. Just appears a tiny line almost imperceptible.

**Comment by Softkeydel** [comment]
This worked for me on Android 

`
 <BottomSheet
        ref={bottomSheetRef}
style={{
borderWidth: 0,
borderTopLeftRadius:15,
borderTopRightRadius: 15
shadowColor: "#000",
shadowOffset: {
	width: 0,
	height: 2,
},
shadowOpacity: 0.25,
shadowRadius: 3.84,
elevation: 5,
}}

        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>


`

**Comment by jr00n** [comment]
I have same issues on Android. No black shadow possible, even with borderWidth:0  whatever I do...so I ended up with:
` shadowColor: Platform.OS === 'ios' ? color.palette.black : color.palette.white,`

Is this bug going to be fixed? I don't know where to look to fix this.

**Comment by gabriel-moresco** [comment]
some workaround?

**Comment by fernandolabsit** [comment]
> This worked for me on Android
> 
> ` <BottomSheet ref={bottomSheetRef} style={{ borderWidth: 0, borderTopLeftRadius:15, borderTopRightRadius: 15 shadowColor: "#000", shadowOffset: { width: 0, height: 2, }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5, }}
> 
> ```
>     index={1}
>     snapPoints={snapPoints}
>     onChange={handleSheetChanges}
>   >
>     <View style={styles.contentContainer}>
>       <Text>Awesome 🎉</Text>
>     </View>
>   </BottomSheet>
> ```
> 
> `

this solved for me too ! thanks bro!
