### ISSUE TITLE
[v4] | [v2] BottomSheetModal is not showing along with React Native Modal

### ISSUE THREAD

**Issue by ursnj** [gorhom/react-native-scroll-bottom-sheet#1028]
# Bug

BottomSheetModal is not showing along with ReactNativeModal.

I think Modal coming on top of Bottom Sheet, but not sure.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.2   |
| react-native                    | 0.67.1  |
| react-native-reanimated         | 2.3.1   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1.
2.
3. 

Describe what you expected to happen:

1.
2.

**Comment by ursnj** [comment]
Is this library is bot maintained anymore ???

**Comment by Waryen** [comment]
React Native Modal is a native view that [sit above your react native application](https://stackoverflow.com/questions/39766350/bring-view-on-top-of-modal-using-zindex-style-with-react-native) therefore the Native modal will hide everything pure JavaScript/TypeScript

Your bottom sheet must be used within a Modal to be shown

**Comment by 738** [comment]
+1

**Comment by arunabhverma** [comment]
+1

**Comment by arunabhverma** [comment]
It will work if you wrap all the content of the modal in `<BottomSheetModalProvider>`

**Comment by iraybi** [comment]
> 

Can you explain what you meant?

**Comment by iraybi** [comment]
> It will work if you wrap all the content of the modal in

@arunabhverma Can you explain what you meant?

**Comment by arunabhverma** [comment]
Let me provide you with some code.

**Comment by iraybi** [comment]
> Let me provide you with some code.

@arunabhverma It'll be a great help if you can do so. Thank you

**Comment by arunabhverma** [comment]
```
<Modal {...modalProps}>
  <BottomSheetModalProvider>
    <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
  </BottomSheetModalProvider>
</Modal>

```

Try this one

**Comment by iraybi** [comment]
@arunabhverma 

Working now. Thanks! So the solution is 

`
<Modal>
    <BottomSheetModalProvider>
        // Your child content goes here
    </BottomSheetModalProvider>
</Modal>
`

**Comment by arunabhverma** [comment]
Yes @iraybi

**Comment by iraybi** [comment]
@arunabhverma , but now the gesture or modal closing behavior is not working anymore. Once opened, the bottomsheet stucks

**Comment by arunabhverma** [comment]
Could you please provide me your code? I will look into it.

**Comment by sarthakmeta** [comment]
@arunabhverma, I am using the same concept but, close on swipe not working not able to close.

**Comment by arunabhverma** [comment]
@sarthakmeta It because of gesture conflicting between screen and bottom sheet.

**Comment by arunabhverma** [comment]
@sarthakmeta you can try this code, it should resolve your issue.

```
import { NativeViewGestureHandler } from 'react-native-gesture-handler';

<NativeViewGestureHandler disallowInterruption={true}>
   <AwesomeComponent />
</NativeViewGestureHandler>
```

**Comment by sarthakmeta** [comment]
@arunabhverma Working now. Thanks!🙏
