### ISSUE TITLE
v4 | Not working with Reanimate v3 | Cannot read property toString of undefined 

### ISSUE THREAD

**Issue by rado196** [gorhom/react-native-scroll-bottom-sheet#1030]
# Bug

I'm using React Native with Fabric, and for fabric, I need to install `react-native-reanimated ^3.0.0-rc.0` to get it to work, 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.2   |
| react-native                    | 0.69.1   |
| react-native-reanimated         | 3.0.0-rc.0  |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

It happened when the screen with `BottomSheet` is rendered. 

## Reproducible sample code
```jsx
import styles from './styles';
import React, { forwardRef, useCallback, useEffect, useRef } from 'react';
import { View } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const SwipeableModal = forwardRef(function (
  { children, points = ['25%', '50%'] },
  ref
) {
  const refModal = useRef();

  const onChange = useCallback((index) => {
    console.log('SwipeableModal.onChange: ', index);
  }, []);

  useEffect(() => {
    ref.current = {
      open: () => refModal.current?.snapToIndex(1),
      close: () => refModal.current?.close(),
    };
  }, []);

  return (
    <View style={styles.container}>
      <BottomSheet
        ref={refModal}
        enablePanDownToClose={true}
        snapPoints={points}
        index={1}
        onChange={onChange}
      >
        {children}
      </BottomSheet>
    </View>
  );
});

export default SwipeableModal;

```

![Simulator Screen Shot - iPhone 13 - 2022-07-15 at 18 49 44](https://user-images.githubusercontent.com/24914689/179250324-cacbdb28-3919-4e08-aa9a-22505e3931e5.png)

**Comment by hirvesh** [comment]
Observing same issue with Reanimated 2.8.0 (Expo) on web.

**Comment by gmiller1763** [comment]
I am also experiencing this issue when using Expo on the web. Any guidance would be much appreciated. Thanks!

**Comment by RobertSasak** [comment]
I think you need to somehow extend your webpack.config.js to also run _react-native-reaanimated/plugin_ on _@gorhom/bottom-sheet_ .
See my solution for bare project here https://github.com/software-mansion/react-native-reanimated/issues/2994#issuecomment-1211247103

**Comment by tanlucvo** [comment]
Observing same issue with Reanimated 2.8.0

**Comment by Albert-Gao** [comment]
does this lib even support for the web, i found nothing on the doc

**Comment by devalnor** [comment]
> does this lib even support for the web, i found nothing on the doc

It seems to be the case
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support/

**Comment by Albert-Gao** [comment]
@devalnor  thanks, got it now, so it depends on reanimated, if reanimated supports, than this lib supports :D

**Comment by numandev1** [comment]
`import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue. it seems metro issue

**Comment by scottmas** [comment]
I get this error too on web for Expo web using reanimated 2.10.0 and I have added the required snippet for web support.

```javascript
createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ["@gorhom"],
      },
    },
    argv,
  );
```

**Comment by anisurrahman072** [comment]
Hi @gorhom ,
![Simulator Screen Shot - iPhone 12 mini - 2023-03-06 at 15 40 56](https://user-images.githubusercontent.com/40535268/223074153-70b3cf7b-2e41-400b-8d02-3c0a2c0012d8.png)

Can't install reanimated v3 with Bottom Sheet v4

**Comment by kaiyes** [comment]
same issue as above 👆👆👆👆👆

**Comment by vdr-mm-quan** [comment]
> 
`Can't install reanimated v3 with Bottom Sheet v4`
Facing the same issue!

**Comment by Sofronijev** [comment]
> `import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue. it seems metro issue

This worked for me! Upgraded to expo SKD 49 and react reanimated 3.3.0 caused sheet not to open at all, now it works again
