### ISSUE TITLE
[v4] | Example of BottomSheetModal does not work in iOS with Expo SDK 46

### ISSUE THREAD

**Issue by arjendevos** [gorhom/react-native-scroll-bottom-sheet#1036]
# Bug

The modal does not open on iOS, it does open sometimes if we add a console.log in handleSheetChanges it opens sometimes the first time but without animation.

In our real app we saw shadow visible at the bottom of the bottom sheet so it seems like it does not go to the right snappoint or something. When do a ui action the modal suddenly shows up.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.0   |
| react-native                    | 0.69.1   |
| react-native-reanimated         | 2.9.1  |
| react-native-gesture-handler    | 2.5.0  |

## Steps To Reproduce
Use expo SDK 46

1. Run on iOS
2. Press open modal
3. Modal does not open, only when you press a second time

Describe what you expected to happen:

1. Press open modal
2. Modal opens

## Reproducible sample code
```tsx
import "react-native-gesture-handler";

import React, { useCallback, useMemo, useRef } from "react";
import { View, Text, StyleSheet, Button } from "react-native";
import { BottomSheetModal, BottomSheetModalProvider } from "@gorhom/bottom-sheet";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const App = () => {
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ["25%", "50%"], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    // console.log("handleSheetChanges", index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <Button onPress={handlePresentModalPress} title="Present Modal" color="black" />
      <BottomSheetModal ref={bottomSheetModalRef} index={1} snapPoints={snapPoints} onChange={handleSheetChanges}>
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheetModal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
    backgroundColor: "grey",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
  },
});

export default () => {
  return (
    <BottomSheetModalProvider>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <App />
      </GestureHandlerRootView>
    </BottomSheetModalProvider>
  );
};

```
I can not use the versions I want in the snack it works but i cant upgrade deps there
https://snack.expo.dev/@richardlindhout/bottom-sheet-v4-reproducible-issue-template

**Comment by arjendevos** [comment]
When we downgrade to
```
"react-native-reanimated": "2.8.0",
"react-native-gesture-handler": "2.2.1",
```
It's still not working..

Looks like it's a react native 0.69.0 issue or something

**Comment by arjendevos** [comment]
We can't create a snack because SDK 45/46 does not yet work on Snack with react-native-gesture-handler + react-native-reanimated

**Comment by arjendevos** [comment]
What is very strange is that if i import enableLogging and call it enableLogging() it works great.

**Comment by RichardLindhout** [comment]
On production app enableLogging does not always work so we need another solution

**Comment by Bieluu** [comment]
Problem and solution has already been described [here](https://github.com/gorhom/react-native-bottom-sheet/issues/925#issuecomment-1126584791). This issue occurs because of [reanimated bug](https://github.com/software-mansion/react-native-reanimated/issues/3296)

**Comment by RichardLindhout** [comment]
Thanks for the heads up @Bieluu, @arjendevos it works with this patch right?

**Comment by arjendevos** [comment]
@RichardLindhout Yeah works fine now!

**Comment by Saliheen** [comment]
Wrape it with   GestureHandlerRootView 
```
<GestureHandlerRootView style={ { height: '100%' } }>
                <BottomSheet
                    animateOnMount
                    ref={ bottomSheetRef }
                    index={ 1 }
                    snapPoints={ snapPoints }
                    onChange={ handleSheetChanges }
                >
                    <View style={ styles.contentContainer }>
                        <Text>Awesome 🎉</Text>
                    </View>
                </BottomSheet>
            </GestureHandlerRootView>
```

**Comment by samrith-s** [comment]
I am trying to use this and I am never able to see the modal. I have even tried applying the patch (https://github.com/gorhom/react-native-bottom-sheet/issues/925#issuecomment-1126584791) but to no avail.
