### ISSUE TITLE
[v4] | Duplicate class eightbitlab.com.blurview.BlurAlgorithm

### ISSUE THREAD

**Issue by bulkinav** [gorhom/react-native-scroll-bottom-sheet#1037]
# Bug

It's seems that current version doesn't compatible with the latest BlurView library: https://github.com/Dimezis/BlurView/releases/tag/version-2.0.2

I'm trying build my project and in Android Studio and get an error:

`Duplicate class eightbitlab.com.blurview.BlurAlgorithm found in modules jetified-BlurView-version-2.0.2-runtime (com.github.Dimezis:BlurView:version-2.0.2) and jetified-blurview-1.6.6-runtime (com.eightbitlab:blurview:1.6.6)`

This is due to the fact that you are applying such a patch with the old version of BlurView:

https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/patches/%40react-native-community%2Bblur%2B3.6.0.patch

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.1 |
| react-native                    | 0.67.4 |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 2.5.0   |

**Comment by bulkinav** [comment]
Don't close )

**Comment by freemanUA** [comment]
same here, is there any workaround?

**Comment by bulkinav** [comment]
@freemanUA I solved this problem by deleting the following line form gradle file:

```gradle
implementation('com.eightbitlab:blurview:1.6.6') {
        force = true
    }
```

As you can see, the old version of the library was indicated here. But in fact, this implementation is not necessary.

**Comment by freemanUA** [comment]
@bulkinav omg, found this in my project too - some developer has put it there. Thanks a lot!
