### ISSUE TITLE
ANR when using the bottomsheet together with react navigation

### ISSUE THREAD

**Issue by uzair-justdice** [gorhom/react-native-scroll-bottom-sheet#1041]
### ANR

We are facing this ANR when we try to load the bottom sheet instantly after navigation to a screen.  I think this happens due to the react native navigation and your bottom sheet both using the react native reanimated at same time.  

`com.swmansion.reanimated.NodesManager.performOperations (NodesManager.java:251)
com.swmansion.reanimated.NodesManager.onEventDispatch (NodesManager.java:492)
com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent (EventDispatcherImpl.java:116)
com.facebook.react.views.image.ReactImageView$1.onSubmit (ReactImageView.java:262)
com.facebook.drawee.controller.ForwardingControllerListener.onSubmit (ForwardingControllerListener.java:75)
com.facebook.drawee.controller.AbstractDraweeController.reportSubmit (AbstractDraweeController.java:802)
com.facebook.drawee.controller.AbstractDraweeController.submitRequest (AbstractDraweeController.java:555)
com.facebook.drawee.controller.AbstractDraweeController.onAttach (AbstractDraweeController.java:450)
com.facebook.drawee.view.DraweeHolder.attachController (DraweeHolder.java:248)
com.facebook.drawee.view.DraweeHolder.attachOrDetachController (DraweeHolder.java:265)
com.facebook.drawee.view.DraweeHolder.onVisibilityChange (DraweeHolder.java:134)
com.facebook.drawee.generic.RootDrawable.setVisible (RootDrawable.java:69)`

### Environment info

Library | Version
-- | --
@gorhom/bottom-sheet | 4.4.0
react-native | 0.69.2
react-native-reanimated | 2.9.1
react-native-gesture-handler | 2.4.0

### Steps To Reproduce

1. Open the bottomsheet as soon as you navigate to a screen.

**Comment by fukemy** [comment]
i got this problem in IOS

**Comment by pierroo** [comment]
By any chance, were you able to find a solution to this problem @uzair-justdice ?
facing the exact same one :/

**Comment by uzair-justdice** [comment]
@pierroo unfortunately no, therefor we had to make our own bottomsheet. I think it's better and error free. I followed this https://www.youtube.com/watch?v=KvRqsRwpwhY&ab_channel=Reactiive
also to open the bottomsheet like modal, I have used the Portal -> https://github.com/gorhom/react-native-portal
