### ISSUE TITLE
Add onLayout to get BottomSheet dynamic height

### ISSUE THREAD

**Issue by Rc85** [gorhom/react-native-scroll-bottom-sheet#1057]
# Feature Request

## Why it is needed

Bottom sheet is sometimes used with customized background, such as a map. When bottom sheet's height is dynamically defined, the maps height also needs to be adjusted just enough to fill the screen so that most of the map is in view.

## Possible implementation

![Screenshot_20220811-020656_Courier](https://user-images.githubusercontent.com/22307591/184100798-87e75832-0530-4e9a-a035-f34507ff6ee8.jpg)

Here, the bottom sheet's height dynamically defined and because I don't know the height, I don't know what to set for the map so that the other marker on the map is visible.

Using a fixed/guessed height may cause inconsistency between screen sizes.

### Code sample

```
<BottomSheet onLayout={(e) => console.log(e.nativeEvent.layout)}>
</BottomSheet>
```

No different than the `onLayout` provided by React components.

**Comment by Killyannoor** [comment]
@gorhom Would you think this is possible? I'm running into the same problem and I still haven't found a way to achieve the wanted result, that's about the same as @Rc85

**Comment by karimcambridge** [comment]
did anyone ever solve this?
