### ISSUE TITLE
[v4] BottomSheetFlatList initialScrollIndex does not work

### ISSUE THREAD

**Issue by Pika-Pool** [gorhom/react-native-scroll-bottom-sheet#1058]
# Bug

when setting the `initialScrollIndex` prop on the `BottomSheetFlatList`, the list doesn't scroll to the specified index.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.2  |
| react-native                    | 0.69.1   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Create the following component:
```
<BottomSheet
	index={0}
	snapPoints={[ '75%', '100%' ]}
	backdropComponent={BackdropGreeting}
	// handleComponent={() => <ChatSupportDetailsHandle chatSupportAssistDetails={chatSupportAssist} />}
>
	<View style={{flex: 1, paddingTop: 10}}>
		<BottomSheetFlatList
			keyboardShouldPersistTaps='always'
			data={ Array(30).fill({ chat: 'hello' }) }
			keyExtractor={(_, index) => index}
			ItemSeparatorComponent={() => <Box h={20} />}
			renderItem={({ item: chat }) => <Text>{chat}</Text>}
			initialScrollIndex={29}
		/>
	</View>
</BottomSheet>
```

Describe what you expected to happen:

1. Like the react-native `FlatList`, the list should initially scroll the to specified index

## Reproducible sample code

https://snack.expo.dev/@pikapool/bottom-sheet-v4-reproducible-issue-template

**Comment by alexandergyllensvard** [comment]
@Pika-Pool how was this closed? I am experiencing this in version 4.4.5, did you find a workaround?

**Comment by WanYingT** [comment]
@Pika-Pool same here, have you found out the problem?

**Comment by BliiTzZ** [comment]
Have you found a solution for defining an initialScroll or ScrollToIndex?
