### ISSUE TITLE
[v4] | [v2] Couldn't find navigation object with BottomSheetModal

### ISSUE THREAD

**Issue by sumi-svmx** [gorhom/react-native-scroll-bottom-sheet#1081]
# Bug
 On wrapping a component that internally uses react-navigation hooks (eg, `useFocusEffect`, `useNavigation`) with `BottomSheetModal`, throws error `"Couldn't find navigation object. Is your component in a screen inside navigator?"`. However, works on using with `BottomSheet` component.

<img src ="https://user-images.githubusercontent.com/71371219/187336666-a47a22e1-652f-4f5a-94bf-c262302778bd.png" width="350" />

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.3   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.6.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open bottom sheet modal that uses and component containing react navigation hooks

Describe what you expected to happen:

1. Work without crash

## Reproducible sample code

```
import {useFocusEffect, useNavigation} from '@react-navigation/native';
import React from 'react';
import {View} from 'react-native';

const DummyComponent = () => {
  const nav = useNavigation();
  useFocusEffect(() => {
    console.log('test');
  });

  return <View style={{backgroundColor: 'yellow', height: 20}} />;
};

export default DummyComponent;
```
--------
```
import React from 'react';
import {BottomSheetModal, BottomSheetBackdrop} from '@gorhom/bottom-sheet';

export function Component(props: Props) {
    <BottomSheetModal
      ref={bottomSheetModalRef}
      index={0}
      backdropComponent={prop => <BottomSheetBackdrop {...prop} />}
      snapPoints={snapPoints}>
      <DummyComponent />
    </BottomSheetModal>
}
```

**Comment by jhhayashi** [comment]
Is your [`<NavigationContainer />`](https://reactnavigation.org/docs/getting-started#wrapping-your-app-in-navigationcontainer) a parent of your `<BottomSheetModalProvider />`?

**Comment by sumi-svmx** [comment]
@jhhayashi 
> Is your [`<NavigationContainer />`](https://reactnavigation.org/docs/getting-started#wrapping-your-app-in-navigationcontainer) a parent of your `<BottomSheetModalProvider />`?

Yes, `BottomSheetModalProvider` is wrapped inside `NavigationContainer`

`App.tsx` render
```
  return (
    <NavigationContainer ref={navRef}>
      <BottomSheetModalProvider>
        <Root />
      </BottomSheetModalProvider>
    </NavigationContainer>
  );
```

**Comment by hridoy43** [comment]
@sumi-svmx

Have you solved the issue? I'm getting the same error also.

**Comment by moxorama** [comment]
I'm using workaround with NavigationService 
https://reactnavigation.org/docs/navigating-without-navigation-prop

**Comment by carlosriveroib** [comment]
> I'm using workaround with NavigationService https://reactnavigation.org/docs/navigating-without-navigation-prop 

Can you share your workaround?

**Comment by AronBe** [comment]
If you <BottomSheetModalProvider> is outside of NavigationContainer you might get this error, but you can always use     <BottomSheetModalProvider> to wrap your component/screen again to be inside of the NavigationContainer

**Comment by Hopefulee** [comment]
> @jhhayashi
> 
> > Is your [`<NavigationContainer />`](https://reactnavigation.org/docs/getting-started#wrapping-your-app-in-navigationcontainer) a parent of your `<BottomSheetModalProvider />`?
> 
> Yes, `BottomSheetModalProvider` is wrapped inside `NavigationContainer`
> 
> `App.tsx` render
> 
> ```
>   return (
>     <NavigationContainer ref={navRef}>
>       <BottomSheetModalProvider>
>         <Root />
>       </BottomSheetModalProvider>
>     </NavigationContainer>
>   );
> ```

Thanks
