### ISSUE TITLE
[v4] | [v2] It is recommended to no longer use Portal

### ISSUE THREAD

**Issue by wy2010344** [gorhom/react-native-scroll-bottom-sheet#1087]
# Bug

Nesting Portals in Portals will cause an infinite loop

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.3   |
| react-native                    | 0.69.4  |
| react-native-reanimated         | 2.9.1  |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Add a BottomSheetModal and in it add a button for a new BottomSheetModal

Describe what you expected to happen:

BottomSheetModal depends on Portal, and Portal depends on state. Setting the state will result in a second render, which will repeatedly add state to the render.

## Reproducible sample code

I tried the code under Portal
```tsx
function App() {
  return <>
    <PortalHost name="custom_host_1" />
    <Portal name="custom_host_1">
      <TestModel />
    </Portal>
  </>
}

function TestModel() {
  const [showModal, setShowModal] = useState(false);
  return <View style={{ flex: 1, backgroundColor: "green" }}>
    <Button onPress={() => setShowModal(true)} title="showSub" />
    {showModal && (
      <Portal name="custom_host_1">
        <TestModel />
      </Portal>
    )}
  </View>
}
```

I think Portal is an unscientific react feature. It is recommended to store jsx as a state store (you can't get updates in Portal), or honestly tile the view like a navigation.

```tsx
function App() {
  useEffect(()=>{
    portalHost.push('custom_host_1', <TestModel />)
  })
  return <>
    <PortalHost name="custom_host_1" />
  </>
}

function TestModel() {
  return <View style={{ flex: 1, backgroundColor: "green" }}>
    <Button onPress={() => {
      portalHost.push('custom_host_1', <TestModel />)
    }} title="showSub" />
  </View>
}
```

I really like BottomSheet, but it's very complicated and hard to reproduce, hope it can be better, thanks a lot.

**Comment by mahimaJ-vs** [comment]
Still facing this issue, is there any other way to use BottomSheet without using Portal?
