### ISSUE TITLE
[v4] | [v2] BottomSheetFooter with BottomSheetTextInput does not handle keyboard animation

### ISSUE THREAD

**Issue by jamesdunay** [gorhom/react-native-scroll-bottom-sheet#1092]
# Bug

When the keyboard is opened the BottomSheetFooter, which contains a BottomSheetTextInput, moves to the correct position, but  it does not animate to that position. Instead it instantly teleports there making the animation somewhat jarring. Does anyone know of a fix for this? I've tried a couple things, but not really had any successes. 

## Environment info
"@gorhom/bottom-sheet": "^4.4.3",
"react-native": "0.69.4",
"react-native-reanimated": "^2.4.1",
"react-native-gesture-handler": "^1.10.3",

## Steps To Reproduce
Pretty simple really. BottomSheet + footer + text input.  Focusing the text input should show the skipping animation.

**Comment by gabimoncha** [comment]
I confirm this is happening also on a Google Pixel 3XL and 4A device

**Comment by jamesdunay** [comment]
I'm not sure if I've come across the issue elsewhere with my dealings KeyboardAvoidingView + listening to the changes of Keyboard.listeners. 

What seems like is happening is that the new position is (obviously correct),  but it's being instantly applied as the new screen is rendered.

**Comment by iraybi** [comment]
Has anyone found any workaround?

**Comment by Wenceslauu** [comment]
Any news on this?

**Comment by dhaval97shah** [comment]
Guys, I am also facing the same issue, any solution?

**Comment by 77zv** [comment]
also facing this, has anyone found a fix?

**Comment by gottfriedaniel** [comment]
+1

**Comment by enisit** [comment]
+1

**Comment by sherikovic** [comment]
A fix [here](https://github.com/gorhom/react-native-bottom-sheet/issues/2031#issuecomment-2810949666) for this in case someone comes back for updates
