### ISSUE TITLE
Hide bottom sheet content in tests when it's not visible

### ISSUE THREAD

**Issue by pierrezimmermannbam** [gorhom/react-native-scroll-bottom-sheet#1113]
# Feature Request

Currently, when using the exported mock from the library, the BottomSheet as well as the BottomSheetModal are always rendering their children. The aim of this feature would be that the children are only displayed when the bottom sheet is visible on the screen. 

## Why it is needed

When writing tests with react-native-testing-library there is no easy way to determine wether a bottom sheet is opened or not. 
It would be ideal to be able to make queries on the elements rendered in the bottom sheet to know wether or not it's visible on the screen

## Possible implementation

The mocks of BottomSheet and BottomSheetModal could be modified so that they have a state isVisible. That state would be modified by the various methods and when it is false they would render nothing instead of rendering the children.

### Code sample

It would look a bit like this (this is very incomplete but the idea is there)

```typescript
class BottomSheetModal extends React.Component {
  state = {
    isVisible : false
  }
  snapToIndex() {}
  snapToPosition() {}
  expand() {}
  collapse() {}
  close() {}
  forceClose() {}
  present() { this.setState({isVisible: true}) }
  dismiss() {}

  render() {
    if (this.state.isVisible) {
      return this.props.children;
    }
    return null;
  }
}
```

Then in the tests you'd be able to do stuff like this : 

```typescript
// check bottomsheet is closed
expect(screen.queryByText('MyBottomSheetTtitle')).toBeFalsy();

fireEvent.press(buttonThatOpensBottomsheet);

// check bottomsheet is opened
expect(screen.getByText('MyBottomSheetTtitle')).toBeTruthy();
```

If this feature gets accepted I'd be happy to start working on a pr

**Comment by ANDREYDEN** [comment]
Although there has not been any activity here, I still think that an all-purpose mock to test modal visibility like the one described by @pierrezimmermannbam would be very useful. In our project we use the following mock (but I'm sure this does not cover all the usecases):
```ts
// __mocks__/@gorhom/bottom-sheet.tsx
import { forwardRef, useImperativeHandle, useState } from 'react';
import { View } from 'react-native';

const MockBottomSheetModal = forwardRef((props, ref) => {
  const [visible, setVisible] = useState(false);

  useImperativeHandle(ref, () => ({
    present: () => setVisible(true),
    dismiss: () => setVisible(false),
  }));

  if (!visible) return null;

  return <View {...props} />;
});
MockBottomSheetModal.displayName = 'MockBottomSheetModal';

module.exports = {
  BottomSheetModal: MockBottomSheetModal,
  BottomSheetScrollView: View,
  BottomSheetView: View,
  BottomSheetBackdrop: View,
};
```
