### ISSUE TITLE
[v4] | BottomSheetBackdrop not closing when pressed on simulator but works on physical device (Expo)

### ISSUE THREAD

**Issue by hellocaio** [gorhom/react-native-scroll-bottom-sheet#1114]
When I press the BottomSheetBackdrop component it is not closing the BottomSheet on the simulator (both on iOS and Android simulators) using Expo (custom dev client) but when I run it on the physical device it works as expected. Does anyone know why this would happen? Panning it down to close also has the same issue, works on the physical device but not on the simulators.

I tried removing my `node_modules` and reinstalling all the packages, I also tried to clear expo cache by running `expo start -c` but nothing works. 

My implementation is quite simple per documentation, I am new to this package so I am going with something as simple as possible right now, something along the lines of:

    // Bottom Sheet References
    const bottomSheetRef = useRef<BottomSheetComponent>(null)
    const snapPointsLimit = useMemo(() => [400], [])

    // Backdrop component
    const renderBackdrop = useCallback(
        (props: BottomSheetBackdropProps) => (
          <BottomSheetBackdrop
            {...props}
            disappearsOnIndex={-1}
            appearsOnIndex={0}
            opacity={0.5}
            pressBehavior="collapse"
          />
        ),
        [],
      )
      
     /**
     * Renders component
     */
    return (
      <BottomSheetComponent
        index={-1}
        ref={bottomSheetRef}
        snapPoints={snapPointsLimit}
        backdropComponent={renderBackdrop}
        handleIndicatorStyle={handleIndicatorStyle}
        keyboardBehavior="interactive"
        keyboardBlurBehavior="restore"
        android_keyboardInputMode="adjustPan"
        enablePanDownToClose
        enableHandlePanningGesture
      >
        {renderContent()}
      </BottomSheetComponent>
    )

I am using Expo SDK 46. Running it by `expo start` if that helps anything.

Thanks!!

**Comment by GarryLaly** [comment]
Solved with this comment https://github.com/gorhom/react-native-bottom-sheet/issues/1165#issuecomment-1305041315
