### ISSUE TITLE
Cannot scroll when using flashlist with BottomSheetModal

### ISSUE THREAD

**Issue by shop-fluencer** [gorhom/react-native-scroll-bottom-sheet#1120]
# Bug

Hello,

I can not scroll when using flashlist with BottomSheetModal

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.0  |
| expo                   | 46.0.0 |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Reproducible sample code

```
const ModalAll = forwardRef<BottomSheetModal, IModalAll>(({ shop_id }, ref) => {
  const snapPoints = useMemo(() => ['25%', 395], []);

  const renderItem: ListRenderItem<IAllData & { user: CurrentUser }> = ({ item }) => {
    return (
      <Pressable style={s.btn}>
        <Image 
          source={{uri: 'https://picsum.photos/55/55'}}
          resizeMode='contain'
          style={s.firstImage}
        />
      </Pressable>
    )
  }
  return (
    <BottomSheetModal
      ref={ref}         
      index={1}
      snapPoints={snapPoints}
      handleIndicatorStyle={s.handleStyle}
      backdropComponent={BottomSheetBackdrop}
    >
      <FlashList
        data={mockAll}
        keyExtractor={(item, i) => i.toString()}
        estimatedItemSize={175}
        // @ts-ignore
        renderItem={renderItem}
        ListHeaderComponent={<Header />}
      />
    </BottomSheetModal>
  )
});
```

**Comment by hirbod** [comment]
You can sponsor @gorhom to get access to the BottomSheetFlashList Component.

**Comment by r3nya** [comment]
Hey @shop-fluencer 

Just use `BottomSheetBackdrop` (https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop) and it will work.

**Comment by ser-emejia** [comment]
@r3nya Hi, Could you share an example? please.

Works good on iOS but not on Android

**Comment by max-kim** [comment]
the same things :( 
Can't scroll FlashList when using it with the BottomSheet

**Comment by crockalet** [comment]
Works with `enableContentPanningGesture` disabled, not ideal but seems to be the best solution for now

**Comment by manan-schmooze** [comment]
Any updates on this?

**Comment by Masoodt** [comment]
<FlashList
      
      data={memoData}
      keyExtractor={(item) => item._id}
      renderItem={renderItem}
      estimatedItemSize={320}
      //@ts-ignore
      renderScrollComponent={BottomSheetScrollView}
    />

**Comment by LovesWorking** [comment]
I had to wrap my flash list with           <GestureDetector gesture={panGesture}> and use the                renderScrollComponent={ScrollView} from import { Gesture, GestureDetector, ScrollView } from 'react-native-gesture-handler';
