### ISSUE TITLE
[v4] Dragging doesn't work on Android

### ISSUE THREAD

**Issue by puelocesar** [gorhom/react-native-scroll-bottom-sheet#1127]
# Bug

No matter which SnapPoints are configured, on Android you can never drag to change them. Everything works perfectly on iOS with the very same code.

## Environment info

Tested on Android 10

"dependencies": {
    "@gorhom/bottom-sheet": "^4.4.5",
    "react": "18.1.0",
    "react-native": "0.70.1",
    "react-native-gesture-handler": "^2.7.0",
    "react-native-reanimated": "^2.10.0"
  }

## Steps To Reproduce

Using the most basic BottomSheet sample found in the "Usage" page of the documentation:

1. run it on Android
2. try to drag the sheet
3. sheet doesn't move

Describe what you expected to happen:

1. sheet moves like on iOS

## Reproducible sample code

https://github.com/puelocesar/bottomSheetBugAndroid

**Comment by gorhom** [comment]
have you setup gesture handler correctly ?

https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js

**Comment by MunemHabib47** [comment]
@gorhom its working but not as smooth as ios on android.

**Comment by ateeq0104** [comment]
https://user-images.githubusercontent.com/112867668/212865922-2cff00ed-42e7-4684-8f03-990b4c594cad.mp4

@gorhom I am facing this issue in android
