### ISSUE TITLE
Cannot determine default value of object (TypeError)

### ISSUE THREAD

**Issue by only1chi** [gorhom/react-native-scroll-bottom-sheet#1129]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.1   |
| react-native-reanimated         | 3.0.0-rc.3   |
| react-native-gesture-handler    | 2.6.2   |

## Steps To Reproduce
Configure the template with the packages listed above. 
Try to render a button within BottomSheet View as follows

1. Configure the [template](https://snack.expo.dev/@gorhom/bottom-sheet-v4-reproducible-issue-template) with the packages listed above. 
2. Try to render a button within BottomSheetScrollView  as shown in the Reproducible sample code below

Describe what you expected to happen:

1. I expected buttons to be rendered when scrolling up from the bottom, instead the application crashes

## Reproducible sample code

```
  // render
  return (
    <BottomSheet style={styles.container}>
      <BottomSheetScrollView style={styles.indicator} />
      <BottomSheetTextInput
        style={styles.input}
        value={value}
        placeholder="Text Input"
        onChange={handleInputChange}
      />
    </BottomSheet>
  );
```

![image](https://user-images.githubusercontent.com/22350063/193933988-b9857d46-7075-4968-b1e3-23ac5c0cf029.png)

**Comment by shreyakupadhyay** [comment]
Hey @only1chi, did you resolve this error at your end? If yes, please explain what fix did you try to resolve the issue. Thanks

**Comment by Helmanso** [comment]
Hello, I'm facing the same error, any fix?
using Fabric by the way
