### ISSUE TITLE
Appium accessibility issue on IOS

### ISSUE THREAD

**Issue by vitalyiegorov** [gorhom/react-native-scroll-bottom-sheet#1140]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@gorhom/bottom-sheet@4.4.5` for the project I'm working on.

On IOS appium does not see the contents of the BottomPanel, adding `accessible={false}` to the root Animated.View fixes the issue both with e2e tests and Appium Inspector.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
index b166440..829c3c1 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
@@ -1596,6 +1596,7 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
               bottomInset={bottomInset}
               detached={detached}
               style={_providedContainerStyle}
+              accessibility={false}
             >
               <Animated.View style={containerStyle}>
                 <BottomSheetBackgroundContainer
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
index 35597ce..46be830 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
@@ -103,7 +103,7 @@ const BottomSheetBackdropComponent = ({
 
   //#region effects
   useAnimatedReaction(
-    () => animatedIndex.value <= disappearsOnIndex,
+    () => Math.floor(animatedIndex.value) <= disappearsOnIndex,
     (shouldDisableTouchability, previous) => {
       if (shouldDisableTouchability === previous) {
         return;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by kollonqv** [comment]
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🙂
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@gorhom/bottom-sheet@4.4.5` for the project I'm working on.
> 
> On IOS appium does not see the contents of the BottomPanel, adding `accessible={false}` to the root Animated.View fixes the issue both with e2e tests and Appium Inspector.
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> index b166440..829c3c1 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> @@ -1596,6 +1596,7 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
>                bottomInset={bottomInset}
>                detached={detached}
>                style={_providedContainerStyle}
> +              accessibility={false}
>              >
>                <Animated.View style={containerStyle}>
>                  <BottomSheetBackgroundContainer
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> index 35597ce..46be830 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> @@ -103,7 +103,7 @@ const BottomSheetBackdropComponent = ({
>  
>    //#region effects
>    useAnimatedReaction(
> -    () => animatedIndex.value <= disappearsOnIndex,
> +    () => Math.floor(animatedIndex.value) <= disappearsOnIndex,
>      (shouldDisableTouchability, previous) => {
>        if (shouldDisableTouchability === previous) {
>          return;
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

Thanks [vitalyiegorov](https://github.com/vitalyiegorov) for posting this, it solved my problem! 🙏
