### ISSUE TITLE
[v4] Appium accessibility issue on IOS

### ISSUE THREAD

**Issue by vitalyiegorov** [gorhom/react-native-scroll-bottom-sheet#1141]
# Bug

Hi! 👋

Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch @gorhom/bottom-sheet@4.4.5 for the project I'm working on.

On IOS appium does not see the contents of the BottomPanel, adding `accessible={false}` to the root `BottomSheetContainer` fixes the issue both with e2e tests and Appium Inspector.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
index 9d42ef1..752a0ea 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
@@ -80,6 +80,7 @@ function BottomSheetContainerComponent({
       onLayout={shouldCalculateHeight ? handleContainerLayout : undefined}
       style={containerStyle}
       children={children}
+      accessible={false}
     />
   );
   //#endregion
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.69.5   |
| react-native-reanimated         | 2.10.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Run application with the bottom panel via Appium Inspector
2. Try to locate bottom panel content elements
3. Appium does not see anything, taps in inspector pass through underneath the bottom panel.

Describe what you expected to happen:

1. Appium should be able to find elements inside the bottom panel

## Reproducible sample code

Can use a example from react-native-bottom-sheet to try

**Comment by yakupdurmus** [comment]
This solution didn't work for me. I noticed that GestureHandlerRootView was preventing the test IDs from appearing.

Here's a solution that worked for me.

```javascript
...
...

  render() {
    const WrappedGestureHandlerRootView =
      Platform.OS === 'ios' ? React.Fragment : GestureHandlerRootView;

    return (
      <Container>
          <WrappedGestureHandlerRootView style={styles.gestureContainer} >
            ... 
            ...
          </WrappedGestureHandlerRootView>
      </Container>
    );
  }
```

The documentation says that it does not work on web and iOS for gestureHandlerRootHOC, so I converted it to Fragment.

https://docs.swmansion.com/react-native-gesture-handler/docs/1.x/#usage-with-modals-on-android
