### ISSUE TITLE
[v4] BottomSheet covering bottom tabs

### ISSUE THREAD

**Issue by NewvilleMedia** [gorhom/react-native-scroll-bottom-sheet#1143]
I am having issues rendering the BottomSheet over the bottom tabs. Currently, the sheet appears above the tabs. I can't find any documentation online explaining how this is done which is odd because on every app with tabs the BottomSheet covers them.
I tried BottomSheetModal and nothing worked.

     <BottomSheet
          ref={sheetRef}
          snapPoints={snapPoints}
          enablePanDownToClose={true}
          onClose={() => setIsOpen(false)}
          index={-1}
          backgroundStyle={{ backgroundColor: '#1b1c1f' }}
          >
          <BottomSheetView>

![1](https://user-images.githubusercontent.com/105016736/194990357-58314101-7f94-4ad7-8712-e56b72d21acd.png)

![2](https://user-images.githubusercontent.com/105016736/194990391-2c93cb4e-feb2-4978-945c-535b7dea99cb.png)

**Comment by MohammadAzimi** [comment]
I'm having the same issue
