### ISSUE TITLE
onDrag, onDragBegin, onDragEnd callbacks to know when drawer is being dragged/pulled

### ISSUE THREAD

**Issue by jacenko** [gorhom/react-native-scroll-bottom-sheet#1147]
# Feature Request

(Going from #351 by @midasCE and adding some details)
We could have a callback for when the user starts/continues/finishes dragging the handler? (Example: onDrag, onDragBegin, onDragEnd which return start/end index)

## Why it is needed

Currently, bottomsheet has only two position-based callbacks - `onChange` and `onAnimate` - which are only triggered once the user releases their finger. If we could detect when a user is pressing and dragging the drawer (just like `onScroll`, `onScrollBegin`, `onScrollEnd` in scrollables), we'd be able to more closely replicate advanced bottom sheet behavior like other components reacting/animating to the drawer dragged height ([note the Google logo and search bar in this video](https://user-images.githubusercontent.com/9830975/195648282-a083d2d6-1fbe-4a23-af03-6235c3749bf4.MP4)).

## Possible implementation

Updates would live alongside `onAnimate` and `onClose` in:
- [src/components/bottomSheet/BottomSheet.tsx](https://github.com/gorhom/react-native-bottom-sheet/blob/29af238d9eed31f0d9cad39ade8a43cf37ca2e72/src/components/bottomSheet/BottomSheet.tsx)
- [src/components/bottomSheet/types.d.ts](https://github.com/gorhom/react-native-bottom-sheet/blob/5e1ed9da98913d47b27912f49cf7e12b2393176e/src/components/bottomSheet/types.d.ts)

### Code sample

```
const onDrag = (fromIndex: number, (maybe other params to determine position) => {
   ......
}
...
onDragHandler={onDrag}
```

**Comment by jacenko** [comment]
Not stale

**Comment by jeremyallison** [comment]
Very interested in this feature request 👍

**Comment by ehsanbigzad** [comment]
up

**Comment by margabit** [comment]
interested as well

**Comment by branaust** [comment]
please add this feature

**Comment by canertuzunar** [comment]
this feature really helps create fluid transition animation

**Comment by Marco-Veio** [comment]
this feature would be very useful

**Comment by atiq4112** [comment]
please add this feature.

**Comment by kneza23** [comment]
is there any progress on maybe adding this?

**Comment by kneza23** [comment]
Not stale

**Comment by slangdog** [comment]
Would love to see this feature. Mainly for a way to may the pull to refresh work in the lowest position

**Comment by kneza23** [comment]
> Would love to see this feature. Mainly for a way to may the pull to refresh work in the lowest position

It would be amazing if you could observe the onDrag values so you can animate some other outside components when you are dragging.

**Comment by slutske22** [comment]
Not stale, need this

**Comment by NicholasBoccuzzi** [comment]
Any reason this is closed?

**Comment by ArkaneKhan** [comment]
It would be a great addition.

**Comment by IordanisSap** [comment]
Also need this

**Comment by paulohenriqueav** [comment]
Very interested in this feature  request =)

**Comment by fukemy** [comment]
any update now? I want to interpolate the color of bottomsheet based on the dragY position

**Comment by kicaal** [comment]
any update?

**Comment by nduyvu1511** [comment]
really need this

**Comment by Orijinn-github** [comment]
need this so much

**Comment by EduardoArtioli** [comment]
updates?

**Comment by Evan-Fisher** [comment]
also need this!

**Comment by ahmedam55** [comment]
also need it please 🙏

**Comment by Aletagro** [comment]
also need this!

**Comment by alexeyvax** [comment]
If anyone wants to implement `onDrag` logic please see the comment
https://github.com/gorhom/react-native-bottom-sheet/issues/351#issuecomment-2561694142

**Comment by devtm1123** [comment]
Need this!!!!!!!!!!!!!!!!!!!

**Comment by AlixH** [comment]
Up
