### ISSUE TITLE
[v4] | Extra space at bottom issue when bottom sheet snap to highest point.

### ISSUE THREAD

**Issue by krushalikevadiya** [gorhom/react-native-scroll-bottom-sheet#1148]
**Bug**
Extra spacing at bottom appear when using bottom sheet with flatlist & tab view.I'm calculating snap point dynamically based on content height.

 **Environment info**
"@gorhom/bottom-sheet": "^4.4.5"
"react-native": "0.67.4",
 "react-native-reanimated": "^2.7.0",
  "react-native-gesture-handler": "^1.10.3",

**Steps To Reproduce**
1.Snap bottom sheet to highest point.
When sheet is at normal state : https://prnt.sc/e3911jMnfV6o
When sheet is dragged : https://prnt.sc/3f40yupiDRhR
2.If i change my snap point then content is not scrolling till the end.
For exa :  
<BottomSheet
          index={0}
          handleComponent={null}
          snapPoints={[
            containerHeight - headerHeight - 30,
            containerHeight - headerHeight + 70,
          ]}
          enableOverDrag={false}
          enablePanDownToClose={false}
          animateOnMount={false}>
          <BottomSheetView style={{flex: 1}}>{renderInner()}</BottomSheetView>
        </BottomSheet>

**Describe what you expected to happen:**

1.Need to remove extra space that is appearing at bottom when bottom sheet is dragged.It is working properly when bottom sheet is not dragged.
2.This issue is in both plateform.

**Reproducible sample code**
 Here I have attached sample code in text formate.
[BottomSheetissue.txt](https://github.com/gorhom/react-native-bottom-sheet/files/9785858/BottomSheetissue.txt)

**Comment by umarabdullah23** [comment]
Same issue

**Comment by mertcankose** [comment]
same

**Comment by kvasnikoff** [comment]
same
