### ISSUE TITLE
[v4] BottomSheetModal autoclose if BottomSheetFlatList has setstate on onPress functions

### ISSUE THREAD

**Issue by syahirdev** [gorhom/react-native-scroll-bottom-sheet#1151]
# Bug

On BottomSheetFlatList, when I declare any setState, the modal will automatically close when I clicked one of the lists.
However, if I try to only console.log on the onPress function, it does not auto close.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.68.1   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    |  2.1.0  |

## Steps To Reproduce
```
const onChooseMonth = async (item: number) => {
    console.log('item = ',item)
    setDate(item)
  }

const renderItem = ({ item }: ListRenderItemInfo<string>) => {
    return (
      <TouchableOpacity key={item} onPress={() => onChooseMonth(item)}>
        <View className={classNames({
          'items-center p-3': true,
          'bg-primary/10': item === teamActivity.chosenMonth
        })}>
          <Text className={classNames({
            'text-primary font-medium': item === teamActivity.chosenMonth,
            'text-neutral-800': item !== teamActivity.chosenMonth
          })}>
            {item}
          </Text>
        </View>
      </TouchableOpacity>
    );
  }

<BottomSheetModalProvider>
    <BottomSheetModal
          ref={calendarModalRef}
          snapPoints={['50%']}
          enableContentPanningGesture={false}
          backdropComponent={(props) => ( <BottomSheetBackdrop {...props} disappearsOnIndex={-1}/> )}
          onDismiss={fetchData}
        >
        <BottomSheetFlatList
            ref={calendarFlatListRef}
            data={monthArray}   // Jan, Feb, Mar, Apr, ...
            renderItem={renderItem}
        />
    </BottomSheetModal>
</BottomSheetModalProvider>
```
1. on BottomSheetFlatList, I render a lists of month using TouchableOpacity
2. when clicked one of the month, execute onChooseMonth function
3. onChooseMonth function will set a new state to setDate

Describe what you expected to happen:

1. when clicked one of the months on flatlist, state Date should change its state, and modal remaining open without autoclosing

Describe what is actually happen:

1. When clicking one of the months on the FlatList, the modal is autoclosed by itself.
2. P.S - when I comments setDate and only console.log, the modal and log is working fine. It happens when only setState or dispatching anything on the function

**Comment by rawatnaresh** [comment]
Did you try wrapping your `onChooseMonth` function inside `useCallback`? for some reason this package show some unexpected behaviour when there are multiple states changes in your app.

**Comment by syahirdev** [comment]
Problem solved.

The issue occured when I have more than one `BottomSheetModal` declared on different components and each of them are wrapped with `BottomModalProvider`.

To fix the issue, I wrapped `BottomModalProvider` on my `NavigationContainer` on `App.tsx` file, and didn't need to wrap the `BottomSheetModal` again on each components.
