### ISSUE TITLE
[v4] BottomSheet*List doesn't work if it's not a direct child of a BottomSheetModal

### ISSUE THREAD

**Issue by sebastian-nowak** [gorhom/react-native-scroll-bottom-sheet#1155]
# Bug

It looks like the scrollable views provided by BottomSheet work only if they're a direct child of a `BottomSheet` / `BottomSheetModal`.

Wrapping a `<BottomSheet*List/>` in another component, even if it's a simple `<View style={{flex: 1}}>...</View>`, is enough to break scrolling.

None of the examples provided at https://gorhom.github.io/react-native-bottom-sheet/v2/scrollables/ work if `<BottomSheet*List/>` component is wrapped in another component.

Maybe this is expected behavior, but it's not documented anywhere on the page I linked to above.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.69.6   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Open any of the example apps under https://gorhom.github.io/react-native-bottom-sheet/v2/scrollables/
2. Wrap the `<BottomSheet*List/>` in a `<View style={{flex: 1}}>...</View>`
3. Notice that the list is no longer scrollable :-(

**Comment by eduardfarkas** [comment]
This deserves to be in the docs, it was driving me crazy until i found this issue...
