### ISSUE TITLE
[v4] | [v2] Warning: Cannot record touch end without a touch start while using Scrollables

### ISSUE THREAD

**Issue by quicksilverr** [gorhom/react-native-scroll-bottom-sheet#1162]
# Bug

Warning: Cannot record touch end without a touch start.
Touch End: {"identifier":0,"pageX":0,"pageY":0,"timestamp":1667227430638}
Touch Bank: [null,{"touchActive":true,"startPageX":83.04408264160156,"startPageY":514.2589111328125,"startTimeStamp":1667227430532,"currentPageX":83.04408264160156,"currentPageY":482.553466796875,"currentTimeStamp":1667227430638,"previousPageX":83.04408264160156,"previousPageY":509.3035583496094}

I'm getting this console warn, when using BottomSheetFlatlist in Bottom Sheet Modal

I've used the dynamic snap-points hook, to adjust according to content height. 

## Environment info

"@gorhom/bottom-sheet": "^4",
 "react-native-gesture-handler": "^2.3.2",
"react-native-reanimated": "2.3.0",
"react-native": "0.66.2",

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | x.x.x   |
| react-native                    | x.x.x   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

## Steps To Reproduce

1. Added BottomModalSheet
2. Then add a bottomSheetFlatlist in the modal
3. 

Describe what you expected to happen:

1. The FlatList to Scroll inside the bottom sheet modal

**Comment by quicksilverr** [comment]
@gorhom @elan

**Comment by elan** [comment]
Yes?

**Comment by paulrostorp** [comment]
@quicksilverr I also ran into this issue the other day on the android emulator. Turns out it was a bug with the emulator itself... It was failing to handle drag touch events properly (even on the OS home screen etc,...).
Restarting the emulator fixed the issue

**Comment by quicksilverr** [comment]
@paulrostorp Turns out genius is simple. 

Thank you so much, it works now!

Closing the issue.

**Comment by pradeep8235** [comment]
> @paulrostorp Turns out genius is simple.
> 
> Thank you so much, it works now!
> 
> Closing the issue.

Can u Tell How To Solve this issue , In Detail??
