### ISSUE TITLE
[v4] BottomSheetBackdrop does not close BottomSheet onTouch

### ISSUE THREAD

**Issue by MetaCorp** [gorhom/react-native-scroll-bottom-sheet#1165]
# Bug

BottomSheetBackdrop does not close BottomSheet onTouch even with pressBehavior="close" props. I tried several methods but I can't get an onPress event working on the BottomSheetBackdrop component either.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | 0.69.6   |
| react-native-reanimated         | ~2.9.1   |
| react-native-gesture-handler    | ~2.5.0   |

## Steps To Reproduce

See code below.

Describe what you expected to happen:

1. Clicking on the Backdrop closes the BottomSheet

## Reproducible sample code

```javascript
const tailwind = useTailwind()

const bottomSheetRef = useRef<BottomSheet>(null);
const snapPoints = useMemo(() => ['15%', '30%'], []);

const handleSheetChanges = useCallback((index: number) => {
	console.log('handleSheetChanges', index);
}, []);

useEffect(() => {
	if (open) {
		bottomSheetRef.current?.expand();
	}
	else {
		bottomSheetRef.current?.close();
	}
}, [open])

const renderBackdrop = useCallback(
	props => (
		<BottomSheetBackdrop
			{...props}
			pressBehavior='close'
		/>
	),
	[]
);

console.log({ MyBottomSheet: { open } })
return (
	<BottomSheet
		ref={bottomSheetRef}
		index={-1}
		snapPoints={snapPoints}
		onChange={handleSheetChanges}
		enablePanDownToClose
		backdropComponent={renderBackdrop}
		backgroundComponent={({ style }) => <View style={[style, tailwind('bg-slate-800')]} />}
		enableOverDrag
		enableHandlePanningGesture
	>
		<View />
	</BottomSheet>
)
```

**Comment by GarryLaly** [comment]
Solved with update MainActivity.java with RNGestureHandlerEnabledRootView and wrapped JS code with view < GestureHandlerRootView>

```
package com.swmansion.gesturehandler.react.example;

import com.facebook.react.ReactActivity;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
public class MainActivity extends ReactActivity {

   @Override
   protected ReactActivityDelegate createReactActivityDelegate() {
     return new ReactActivityDelegate(this, getMainComponentName()) {
       @Override
       protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
       }
     };
   }
}
```

See reference https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot

**Comment by yaaamin** [comment]
Is there anyway we can overcome this issue for people using Expo Managed Workflow?

**Comment by TaiwoO** [comment]
I'm having the same issue. It seems to work if you give BottomSheetBackdrop an absurd height (like 10,000).

**Comment by TaiwoO** [comment]
This works for me:
```js
 const renderBackdrop = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        style={[props.style]}
        disappearsOnIndex={-1}
        appearsOnIndex={0}
        opacity={0.5}
        pressBehavior="close"
   
      />
    ),
    []
  );
```

**Comment by yaaamin** [comment]
For anyone who is still looking for fixes for this issue, just wrap your App.js component with the following 

`export default function App() {
  return <GestureHandlerRootView>{/* content */}</GestureHandlerRootView>;
}`

_extracted from https://docs.swmansion.com/react-native-gesture-handler/docs/1.10.3/_

**Comment by elitenas** [comment]
@yaaamin it still doesn't seem to work even with `GestureHandlerRootView` at the root in App.js

**Comment by lewiscasewell** [comment]
I am still getting this same issue. Currently works in iOS expo sim, but not in android studio. Anyone else facing this issue?

**Comment by lewiscasewell** [comment]
> @yaaamin it still doesn't seem to work even with `GestureHandlerRootView` at the root in App.js

Did you try <GestureHandlerRootView style={{ flex: 1 }}>{/* content */}</ GestureHandlerRootView> ?

**Comment by SimonAM** [comment]
There is still no fix for this on expo SDK 47 even though i am using the GestureHandlerRootView as specified.

**Comment by SimonAM** [comment]
I dont understand why, but the onPress-handler for `BottomSheetBackdrop` leads to changing snapPoint index to index nr 1 no matter what i set the `pressBehavior`to. 

Creating a custom backdrop as per the docs and passing in a onPress to a touchable opacity still works though.

**Comment by yaaamin** [comment]
@SimonAM Care to share snippet of your code about how you are passing the `renderBackdrop` element? 
As for `GesterHandlerRootView` should be at your App.js file wrapping your Navigation Container if you are using React Navigation
Hope this helps.

**Comment by ivanhoe-dev** [comment]
> > @yaaamin it still doesn't seem to work even with `GestureHandlerRootView` at the root in App.js
> 
> Did you try <GestureHandlerRootView style={{ flex: 1 }}>{/* content */}</ GestureHandlerRootView> ?

I was having the same issue and your solution works, thank you.

**Comment by samvoults** [comment]
> > @yaaamin it still doesn't seem to work even with `GestureHandlerRootView` at the root in App.js
> 
> Did you try <GestureHandlerRootView style={{ flex: 1 }}>{/* content */}</ GestureHandlerRootView> ?

This solution worked for me too but the horizontal flatlists I have in my bottom sheet now can't be scrolled anymore...

**Comment by sgalanb** [comment]
> This works for me:
> 
> ```js
>  const renderBackdrop = useCallback(
>     (props: BottomSheetBackdropProps) => (
>       <BottomSheetBackdrop
>         {...props}
>         style={[props.style]}
>         disappearsOnIndex={-1}
>         appearsOnIndex={0}
>         opacity={0.5}
>         pressBehavior="close"
>    
>       />
>     ),
>     []
>   );
> ```

These should be the default values. I imagine at least 90% of people adding a backdrop just want this native-like behaviour.

**Comment by Poojaauma** [comment]
Is it possible to keep opacity to 0 and keep this functionality working? Because I just don't want the transparent background to be rendered ?

**Comment by JL-D-coder** [comment]
> Is it possible to keep opacity to 0 and keep this functionality working? Because I just don't want the transparent background to be rendered ?

https://gorhom.dev/react-native-bottom-sheet/custom-backdrop

**Comment by Cherevatin** [comment]
> Is it possible to keep opacity to 0 and keep this functionality working? Because I just don't want the transparent background to be rendered ?

Just set the background color of the backdrop component to 'transparent' and don't care about opacity
