### ISSUE TITLE
[v4] Memory leak when disappearsOnIndex is set to -1

### ISSUE THREAD

**Issue by MehdiG44** [gorhom/react-native-scroll-bottom-sheet#1169]
# Bug

Memory leak right after BottomSheetBackdrop is unmounted.

### Logs when opening the modal
<img width="587" alt="image" src="https://user-images.githubusercontent.com/51918171/200247607-41e7bd0c-f566-4028-954a-3e109d9fadd5.png">

#### when there's no memory leak
<img width="443" alt="image" src="https://user-images.githubusercontent.com/51918171/200248070-0e2c20b4-e1a9-49ab-8e4f-724cccb4de29.png">

#### when we have it
<img width="843" alt="image" src="https://user-images.githubusercontent.com/51918171/200247947-b2e6c0f3-c4a5-4e15-b04f-c616eb88c64e.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.64.0   |
| react-native-reanimated         | 2.11.0   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

1. Implement `BottomSheet` with `BottomSheetModal` (not sure the modal is mandatory to reproduce)
2. Only one `initialSnapPoints` ==> `'CONTENT_HEIGHT'`
3. Set `BottomSheetBackdrop` `disappearsOnIndex` prop to `-1`
4. Dismiss the modal

Describe what you expected to happen:

No memory leak.
But I get a memory leak randomly.
My guess is that we have a race condition between the `BottomSheetBackdrop` unmounting and the re-rendering of it because `animatedIndex` changed for the new index.

## Reproducible sample code

```js

import React, {useMemo, useCallback, useEffect} from 'react';
import PropTypes from 'prop-types';
import {
  BottomSheetModal as LibraryBottomSheetModal,
  BottomSheetBackdrop,
  BottomSheetView,
  useBottomSheetDynamicSnapPoints,
} from '@gorhom/bottom-sheet';

const BottomSheetModal = ({
  children,
  setShow,
  bottomSheetModalRef,
}) => {
  const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], []);

  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints);

  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    [],
  );

  const onDismiss = () => {
    console.log('Dismiss');
    return setShow(false);
  };

  useEffect(() => {
    bottomSheetModalRef.current.present();
    console.log('modal ⬆️');

    return () => console.log('modal ⬇️');
  }, []);

  useEffect(() => {
    console.log('modal 🔄');
  });

  return (
    <LibraryBottomSheetModal
      onChange={props => {
        console.log('onChange: ', props);
      }}
      onAnimate={(from, to) => {
        console.log('onAnimate: ', from, to);
      }}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}
      backdropComponent={renderBackdrop}
      keyboardBlurBehavior="restore"
      android_keyboardInputMode="adjustResize"
      enablePanDownToClose
      ref={bottomSheetModalRef}
      onDismiss={onDismiss}>
      <BottomSheetView onLayout={handleContentLayout}>
        {children}
      </BottomSheetView>
    </LibraryBottomSheetModal>
  );
};

BottomSheetModal.propTypes = {
  children: PropTypes.element.isRequired,
  setShow: PropTypes.func.isRequired,
  bottomSheetModalRef: PropTypes.object.isRequired,
};

export default BottomSheetModal;

```

**Comment by hirbod** [comment]
There was an article about this from the React team, that this error message is to harsh and not really indicates a memory leak. It indicates that a a useState was called after the component was unmounted. Sometimes, it is just a tiny timing issue and more like an info than a real error you should worry off. It should be fixed though, no questions asked.

**Comment by hritiksingh73** [comment]
Hey @hirbod  ,
I think you are talking about [this](https://github.com/facebook/react/pull/22114)
We have this error in one of our production app, I have searched for(searching) the workaround for the same.Should we ignore this or is this can cause any future bugs ?
Also any suggestion, workaround will be highly appreciated

**Comment by hirbod** [comment]
That was exactly the issue I was walking about @hritiksingh73 - as long there is no event listener or something like that, that message is absolutely irrelevant. This warning should not appear on React v18, only v17 anyway. OPs RN version is on 0.64, pretty old and React v17.

**Comment by louisiscoding** [comment]
It is not stale ! Please re-open
