### ISSUE TITLE
[v4] Native virtualized list within a BottomSheetScrollView not working in Android

### ISSUE THREAD

**Issue by TNAJanssen** [gorhom/react-native-scroll-bottom-sheet#1172]
# Bug

In one of my form inputs, you have the possibility to scroll between times. This works perfectly on iOS but on Android you can't scroll in these. I use the VirtualizedList, if i change to the BottomSheetVirtualizedList is this then possible to nest it with BottomSheetScrollView>

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.69.6   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

https://user-images.githubusercontent.com/2812277/200555509-a2187531-6f63-4780-a2cb-6f55bc971bf3.mp4

https://user-images.githubusercontent.com/2812277/200555536-4dadde36-478f-48cc-b24e-75b1a83c7506.MP4

**Comment by naytun** [comment]
I found the solution:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
return (
  <GestureHandlerRootView>
   ... your component here
  </GestureHandlerRootView>
)
```
