### ISSUE TITLE
Cannot put scroll in v4

### ISSUE THREAD

**Issue by Bayramito** [gorhom/react-native-scroll-bottom-sheet#1179]
# Bug

I just put a custom recyclerlistview in the bottom sheet but it's simply doesn't work at all. It's not scrolling in the recyclerlistview. 
just toggling between snapPoints that I set when I try to scroll.

If I put the entire component in a BottomSheetScrollView then scrolls but this time onEndReached functionality doesnt work.

## Environment info

Android phone Xiaomi mi8
IOS simulator

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.0   |
| react-native                    | 0.70.5  |
| react-native-reanimated         | 2.11.0  |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

```
 <BottomSheet
          ref={sheetRef}
          index={0}
          snapPoints={snapPoints}
          // waitFor={rlvRef}
          // simultaneousHandlers={flashListRef}
          // onChange={handleSheetChanges}
          backgroundStyle={{backgroundColor: "transparent"}}
          containerStyle={{borderTopLeftRadius: 20, borderTopRightRadius: 20}}
          // handleIndicatorStyle={styles().grip}
          // bottomInset={20}
        >
  
          <RecyclerListView
           
            data={discover}

            ref={rlvRef}
            contentContainerStyle={{paddingTop: 10, alignContent: "center", backdropColor: "transparent"}}
            numColumns={3}
            renderItem={({item, index}) => <ProfileModalGalleryItem {...{item, index}} />}
            extraData={discover}
            // height={"90%"}
            // style={{flex: 1}}
            onEndReachedThreshold={0.3}
            showsVerticalScrollIndicator={false}
            onEndReached={() => alert("test")}
          />
        </BottomSheet>
```

Describe what you expected to happen:

1. should expand the bottom sheet
2.should continue scrolling inside my list view (RecyclerListView)
3.should catch onEndReachThreshold

**Comment by naytun** [comment]
Usually the solution is:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
return (
  <GestureHandlerRootView>
   ... your component here
  </GestureHandlerRootView>
)
```
