### ISSUE TITLE
[v4] | Component inside BottomSheet is re-rendered upon snapPoint changed 

### ISSUE THREAD

**Issue by n-ii-ma** [gorhom/react-native-scroll-bottom-sheet#1180]
I have a component inside the BottomSheet and have noticed that it gets rendered upon snapPoint changes.

Is this a normal behavior or a bug leading to memory leak?

**Comment by rishabhHubilo** [comment]
Facing the same issue. Any updates on this?

**Comment by Bayramito** [comment]
any fixes on this ?
