### ISSUE TITLE
[v4] BottomSheetBackdrop opacity not working

### ISSUE THREAD

**Issue by ahmetkuslular** [gorhom/react-native-scroll-bottom-sheet#1183]
# Bug

The opacity value passed to the Bottom Sheet Backdrop is not applied.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.12.0   |
| react-native-gesture-handler    | 2.1.0   |

## Steps To Reproduce

1. use BottomSheetModal
2. Pass opacity prop 0.1 to BottomSheetModal

## Reproducible sample code
```

const renderBackdrop = useCallback(
      props => (
        <BottomSheetBackdrop
          {...props}
          opacity={0.1}
          disappearsOnIndex={-1}
          appearsOnIndex={-1}
          pressBehavior="close"
        />
      ),
      [],
    );

 return (
      <BottomSheetModal
       ....
        backdropComponent={renderBackdrop}
        >
        {children}
      </BottomSheetModal>
    );

```

https://snack.expo.dev/@ahmetkuslular/bottom-sheet-v4-reproducible-issue-template?platform=ios

https://user-images.githubusercontent.com/17436691/201490401-00144b61-9cc2-4cf9-b68f-56c8cfd53e13.mp4

**Comment by AronBe** [comment]
`appearsOnIndex={-1}` should be 0 probably

**Comment by damithg-dev** [comment]
@ahmetkuslular add following  `index={0}`  to `BottomSheetModal`  prop and `disappearsOnIndex={-1}`  `appearsOnIndex={0} ` to `BottomSheetBackdrop`

**Comment by ahmetkuslular** [comment]
@damithg-dev thank you

**Comment by baseer869** [comment]
> @ahmetkuslular add following `index={0}` to `BottomSheetModal` prop and `disappearsOnIndex={-1}` `appearsOnIndex={0} ` to `BottomSheetBackdrop`

perfect, working
