### ISSUE TITLE
How to hide the indicator component in header of BottomSheetModal

### ISSUE THREAD

**Issue by cuongnv-dev** [gorhom/react-native-scroll-bottom-sheet#1186]
I want to make the indicator component in the BottomSheetModal header invisible, but I can't figure out how to do it. I'm hoping you guys can help. Thanks

**Comment by anurbe** [comment]
Hey @cuongnv-dev not sure if you found the solution but you can do it this way:
Pass the: 
<BottomSheetModal
`handleIndicatorStyle={styles.headerIndicator}`
/>
and in the styles just make the headerIndicator: { height: 0 } and it should work.

**Comment by hieungochoangit** [comment]
@anurbe thanks, it work for me.

**Comment by Sameer08052003** [comment]
@anurbe Thankyou

**Comment by pritamleocoders** [comment]
just add  iniside  BottomSheetModal backgroundStyle={{borderRadius:0}}

**Comment by RyanLinXiang** [comment]
Hi there. The solution works, but however, there is still a height existing where the notch was before even when it is now not visible and height set to 0. how can I remove the height completely?

**Comment by sricc** [comment]
@RyanLinXiang Not sure if this is the best way, but I removed it by adding `handleComponent={null}` to the `BottomSheetModal` like this:

```javascript
<BottomSheetModal
  name={name}
  snapPoints={snapPoints}
  ref={ref}
  backdropComponent={renderBackdrop}
  handleComponent={null}
>
```
