### ISSUE TITLE
How to make the indicator component in the BottomSheetModal header invisible

### ISSUE THREAD

**Issue by cuongnv-dev** [gorhom/react-native-scroll-bottom-sheet#1187]
# Feature Request

I want to make the indicator component in the BottomSheetModal header invisible, but I can't figure out how to do it. I'm hoping you guys can help. Thanks

**Comment by TaharS** [comment]
```
handleComponent={() => <></>}
```

**Comment by AronBe** [comment]
or shorter `handleComponent={null}`

**Comment by cuongnv-dev** [comment]
@TaharS @AronBe  thanks a lot guys, It was my fault for not carefully reading the document
