### ISSUE TITLE
Glassmorphism with this modal?

### ISSUE THREAD

**Issue by GeorgeHop** [gorhom/react-native-scroll-bottom-sheet#1192]
# Feature Request

Hi guys! Thank you for this very very very good lib.) It really helpfull! 

The issue is I trying to add glassmorphism to your modal... Make it blur and transparent using expo-blur... But the issue is when I trying to do it by docs https://gorhom.github.io/react-native-bottom-sheet/custom-background it won't work properly. 

I trying to acieve something like that
![image](https://user-images.githubusercontent.com/47904385/202821655-a9ae7f40-391c-4f12-a85e-3ec41e681f19.png)

## Why it is needed

Because glassmorphism is very simple and popular design pattern this days)

## Issue

Yes probably backgroundComponent has some issues with displaying specific background like BlurView and so on... At first render view blured and then it's not. Probably it somehow depend on component animation or rendering system?!

## Possible implementation

Make some complex samples of customizing background? Or improve backgroundComponent prop to create specific backgrounds?

### Code sample
Sample of custom background 
```JS
import React from 'react';
import ComponentsStyles from "../../constants/ComponentsStyles";
import {BlurView} from "expo-blur";

export default function PanelBackground({style}) {
    return (
        <BlurView
            style={{
                ...style,
                overflow: 'hidden',
                ...ComponentsStyles.borderRadius.topRadius,
                // backgroundColor: `rgba(255,255,255,0)`
                // backgroundColor: theme.rgbaWhiteComponents,
            }}
            intensity={30}
        />
    )
}
```

Sample of how I use it

```JS 

           <BottomSheet
                animateOnMount={false}
                style={{
                    marginHorizontal: 5,
                    ...shadowGenerator(1),
                    ...ComponentsStyles.borderRadius.topRadius
                }}
                backgroundComponent={PanelBackground}
                enableOverDrag={false}

```

**Comment by ansh** [comment]
This would be cool. What isn't working?

**Comment by GeorgeHop** [comment]
You can check the issue description more detailed) I described the problem.

**Comment by GeorgeHop** [comment]
Almost month ago I created this thread and no response from maintainers. For some reasons you can make workaround with backdropComponent and it will work okay... Why? Why with backgroundComponent it's working sometimes and sometimes no? How I said before it is something about the render -_-

**Comment by ansh** [comment]
It is possible to do. Just set the Bottom Sheet's `style={{backgroundColor: "transparent"}}` then put a BlurView inside with flex: 1

I just tried it and it works perfectly. @GeorgeHop

**Comment by GeorgeHop** [comment]
And what should I do with FlatList inside? I this case you cant just wrap everything inside BottomSheet in BlurView with flex 1. And probably this is not best practice if authors added external prop like backgroundComponent.

![image](https://user-images.githubusercontent.com/47904385/207009293-486af11a-04d5-4e6d-b094-6ce02a05c61c.png)

**Comment by GeorgeHop** [comment]
Any comments from author @gorhom ?

**Comment by 2Senn** [comment]
I would love to see this being added as a prop too !

**Comment by GeorgeHop** [comment]
Guys more than month ago I created this issue! Maybe you will answer something?

**Comment by RGarrido03** [comment]
I'm trying to use a BlurView-powered bottom sheet modal. However, when I try @ansh's solution, the BlurView is only visible below the handle position, so the handle is completely transparent:

![IMG_2571](https://github.com/gorhom/react-native-bottom-sheet/assets/57329376/553afce9-6739-4b3c-8b2f-4bc48b43b80c)

I created a custom handle (based on [this one](https://gorhom.github.io/react-native-bottom-sheet/custom-handle)) that features a BlurView, but since there are two different blur surfaces (the main one and the one on the handle), the blur is not smooth between these two elements.
 
![IMG_2573](https://github.com/gorhom/react-native-bottom-sheet/assets/57329376/77f3a2ec-b244-4e2b-b5cd-198b5298fc65)

The dark green color background is there for showing purposes, it's planned to put a map there.

Any suggestions?

**Comment by GeorgeHop** [comment]
Hah, I added this issue like a half year ago... And no response from the author so far. I was not able to add blueview + flatlist inside this modal. Most of workarounds I found was pretty bad and low quality.

**Comment by aurelkpr** [comment]
Same issue here, BlurView is not displayed :(

**Comment by IordanisSap** [comment]
Also having the same issue

**Comment by eloisp** [comment]
Same issue, but found a workaround.
On first render, BlurView is not displayed, on second it's displayed.
So I forced a rerender by changing the tint

```
const bottomSheetRef = useRef(null)
const [blurTint, setBlurTint] = useState('light')

const onButtonBottomSheetPressed = () => {
        setBlurTint('dark')
        bottomSheetFlashRef.current?.expand()
}

useEffect(() => {
        bottomSheetRef.current?.present();
}, [bottomSheetRef]);


return (
<BottomSheetModal
     ref={bottomSheetRef}
     index={-1} 
     snapPoints={snapPoints} 
     enablePanDownToClose={true} 
     backgroundStyle={{backgroundColor: 'transparent'}} 
     enableDismissOnClose={false}
     handleComponent={null}
>
     <BlurView intensity={50} tint={blurTint} style={{flex:1}}>
                 ....
     </BlurView>
</BottomSheetModal>
)
```

**Comment by GeorgeHop** [comment]
Nice, but we need a cleaner solution...
Or at least author description why we can't use external components to style container.

**Comment by eloisp** [comment]
Did you try with StyleSheet.absoluteFill with self-closing tag ? Seems to work with me 

```
<BottomSheetModal
                ref={bottomSheetRef} 
                index={0} 
                snapPoints={snapPoints} 
                enablePanDownToClose={true} 
                backgroundStyle={{backgroundColor: 'transparent'}} 
                enableDismissOnClose={true}
                handleComponent={null}
            >
                <View style={styles.bottomSheetContainer}>
                    <BlurView intensity={50} tint={'light'} style={{...StyleSheet.absoluteFill, overflow: 'hidden', backgroundColor: 'transparent'}} />
                   {YOUR CONTENT}
                </View>
</BottomSheetModal>
```

**Comment by GeorgeHop** [comment]
This workaround is not working properly with FlatList from this lib. You can read topic one more time to see all corner cases ☺️

**Comment by mccraveiro** [comment]
I find this a better solution:

```js
<BottomSheet
  ...
  backgroundComponent={({ style }) => (
    <BlurView
      tint="light"
      intensity={50}
      style={[style, { borderRadius: 20, overflow: "hidden" }]}
    />
  )}
/>

**Comment by GeorgeHop** [comment]
Have you tried this solution with BottomSheetFlatList?

**Comment by GeorgeHop** [comment]
I wondering why is this issue closed?

**Comment by ParthNandaniya** [comment]
anyone found the solution ?

**Comment by mccraveiro** [comment]
@ParthNandaniya have you tried this solution?
https://github.com/gorhom/react-native-bottom-sheet/issues/1192#issuecomment-2002288444

**Comment by iamifechi** [comment]
This kinda worked for me

```
<BottomSheet
  ...
 backdropComponent={({ style }) => (
          <BlurView
            tint="light"
            intensity={100}
            style={[style, { overflow: "hidden" }]}
          />
  )}
/>
```

**Comment by Karthik-B-06** [comment]
Hey @iamifechi, 

```
      <BottomSheetModal
        ref={searchBookmarksSheetRef}
        handleComponent={null}
        backdropComponent={({ style }) => (
          <AnimatedBlurView
            entering={FadeIn.duration(200)}
            experimentalBlurMethod="dimezisBlurView"
            blurReductionFactor={6}
            intensity={70}
            tint="light"
            style={[style, tailwind.style('rounded-[40px] overflow-hidden bg-white/80')]}
          />
        )}
        backgroundComponent={({ style }) => (
          <Animated.View
            style={[style, tailwind.style('rounded-[40px] overflow-hidden bg-transparent')]}
          />
        )}
        snapPoints={['100%']}
        enableDynamicSizing={false}
        enableContentPanningGesture
        enablePanDownToClose
        enableOverDrag>
        <SearchSection />
      </BottomSheetModal>
```

I am trying to do something similar, but it flickers when the bottomsheet modal is opena and we try to switch apps>
