### ISSUE TITLE
[v4] BottomSheetScrollView doesn't play well with useBottomSheetDynamicSnapPoints

### ISSUE THREAD

**Issue by mefjuu** [gorhom/react-native-scroll-bottom-sheet#1193]
# Bug

I'm using `useBottomSheetDynamicSnapPoints` and `BottomSheetScrollView` as BottomSheet content container.

When:
- ScrollView content is higher than visible area
or
- keyboard is visible

BottomSheetScrollView's bottom content is clipped and cannot be reached. [Example](https://github.com/mefjuu/react-native-bottom-sheet/commit/0934bc50ab61c033160349c4c62867f37a90d004)

It seems to be an issue with calculating `animatedContentHeight` by  `useBottomSheetDynamicSnapPoints()` hook.

https://user-images.githubusercontent.com/2331923/203018001-97ff0214-6b08-45dc-9924-6f7a297942cf.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.70.1   |
| react-native-reanimated         | 2.11.0   |
| react-native-gesture-handler    | 2.6.1   |

## Steps To Reproduce

Place `<BottomSheetScrollView />` with some content exceeding available viewport's height within BottomSheet that utilizes `useBottomSheetDynamicSnapPoints(['CONTENT_HEIGHT'])`.

## Reproducible sample code

I've prepared a repo's fork with modified official "Dynamic snap point" example:  https://github.com/mefjuu/react-native-bottom-sheet/commit/0934bc50ab61c033160349c4c62867f37a90d004

**Comment by thebiltheory** [comment]
This issue is still going on.
@gorhom is there something we can do to help you work on this?

**Comment by AChevallier** [comment]
I've got the bug as well

**Comment by slutske22** [comment]
I'm also seeing this, cannot scroll all the way to the bottom of the scroll view within the bottomsheet if it exceeds the bottomsheet height

**Comment by susonthapa** [comment]
I'm also running into this issue. For the time being I'm using fixed height for ScrollView to fix the issue.

**Comment by iyansr** [comment]
i got the same
