### ISSUE TITLE
[v4] | [v2] Unable to scroll a FlatList in a bottom-sheet on Android

### ISSUE THREAD

**Issue by tyrauber** [gorhom/react-native-scroll-bottom-sheet#1194]
# Bug

In Expo SDK 47, a v4 BottomSheet with a FlatList:

- on iOS, allows for adjusting bottom sheet height *and* scrolling the FlatList content
- on Android, allows for one or the other

This is true for a FlatList, or @shopify/flash-list.

On Android, if the component is wrapped in GestureHandlerRootView, you can adjust the bottom-sheet position, but not scroll the FlatList. If the component is wrapped in NativeViewGestureHandler, you can scroll the FlatList,  but not adjust the bottom-sheet position.

On iOS, both GestureHandlerRootView and NativeViewGestureHandler work as expected.

Please see [the linked snack](https://snack.expo.dev/@tyrauber/bottom-sheet-flashlist) demonstrating the issue.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.1   |
| react-native                    | 0.70.4   |
| react-native-reanimated         | ~2.12.0   |
| react-native-gesture-handler    | ~2.8.0  |
| @shopify/flash-list|                      | 1.3.1 |

## Steps To Reproduce

Please see [the linked snack](https://snack.expo.dev/@tyrauber/bottom-sheet-flashlist) demonstrating the issue.

Describe what you expected to happen:

1. should be able to adjust the height of a bottom sheet
2. should be able scroll a FlatList within a bottom sheet

On both iOS and Android.

## Reproducible sample code

Please see [the linked snack](https://snack.expo.dev/@tyrauber/bottom-sheet-flashlist).  Testing on an Android and iOS will demonstrate the issue. Code below:

```
import './polyfills'
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';
import { GestureHandlerRootView, NativeViewGestureHandler } from 'react-native-gesture-handler'

import List from './components/List';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%', '90%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);
  console.log('ref', bottomSheetRef)

  // renders
  return (
    <NativeViewGestureHandler style={{ flex: 1 }}>
      <View style={styles.container}>
        <BottomSheet
          // ref={bottomSheetRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
        >
          <View>
            <View style={styles.contentContainer}>
              <Text>Awesome 🎉</Text>
            </View>
            <List/>
          </View>
        </BottomSheet>
      </View>
    </NativeViewGestureHandler>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey'
  },
  contentContainer: {
    alignItems: 'center'
  },
});

export default App;
```
```
import React, { useRef, useState } from "react";
import {
  View,
  Text,
  Pressable,
  LayoutAnimation,
  StyleSheet,
  FlatList
} from "react-native";
import { FlashList } from "@shopify/flash-list";

const generateArray = (size: number) => {
  const arr = new Array(size);
  for (let i = 0; i < size; i++) {
    arr[i] = i;
  }
  return arr;
};

const List = () => {
  const [refreshing, setRefreshing] = useState(false);
  const [data, setData] = useState(generateArray(100));
  const [height, setHeight] = useState(0);
  const [width, setWidth] = useState(0);

  const list = useRef<FlashList<number> | null>(null);

  const removeItem = (item: number) => {
    setData(
      data.filter((dataItem) => {
        return dataItem !== item;
      })
    );
    list.current?.prepareForLayoutAnimationRender();
    // after removing the item, we start animation
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
  };

  const renderItem = ({ item }: { item: number }) => {
    const backgroundColor = item % 2 === 0 ? "#00a1f1" : "#ffbb00";
    return (
      <Pressable
        onPress={() => {
          removeItem(item);
        }}
      >
        <View
          style={{
            ...styles.container,
            backgroundColor,
            height: item % 2 === 0 ? 100 : 200,
          }}
        >
          <Text>Cell Id: {item}</Text>
        </View>
      </Pressable>
    );
  };

  return (
    <View 
      style={{
        height: '100%'
       }}>
        <FlatList
          ref={list}
          refreshing={refreshing}
          onRefresh={() => {
            setRefreshing(true);
            setTimeout(() => {
              setRefreshing(false);
            }, 2000);
          }}
          keyExtractor={(item: number) => {
            return item.toString();
          }}
          renderItem={renderItem}
          estimatedItemSize={100}
          data={data}
        />
    </View>
  );
};

export default List;

const styles = StyleSheet.create({
  container: {
    justifyContent: "space-around",
    alignItems: "center",
    alignSelf: 'stretch',
    backgroundColor: "#000000",
  }
})
```

**Comment by tyrauber** [comment]
Of course. As soon as I post this, I notice the issue. I need to import FlatList from react-native-gesture-handler. Then both scrolling the FlatList and adjusting the bottom-sheet height work on Android.

Is there an equivalent for  @shopify/flash-list?

**Comment by tyrauber** [comment]
Yes, there is! Build your own! 

Wrap `FlashList` in `PanGestureHandler` with a shared ref.  Pass the ref to FlashList with the attribute overrideProps, and pass `ScrollView` from `react-native-gesture-handler` to  FlashList as renderScrollComponent.

Found here, [@shopify/FlashList does not integrate with createNativeWrapper](https://github.com/software-mansion/react-native-gesture-handler/issues/2175#top)

```
return (
    <View 
      style={{
        height: '100%'
       }}>
        <PanGestureHandler
          ref={panRef}
        >
          <FlashList
            ref={list}
            refreshing={refreshing}
            onRefresh={() => {
              setRefreshing(true);
              setTimeout(() => {
                setRefreshing(false);
              }, 2000);
            }}
            keyExtractor={(item: number) => {
              return item.toString();
            }}
            renderItem={renderItem}
            estimatedItemSize={100}
            data={data}
            renderScrollComponent={ScrollView}
          />
      </PanGestureHandler>
    </View>
  );
};
```

FlashList Scroll and BottomSheet height adjustment works on iOS and Android!

[Snack updated](https://snack.expo.dev/@tyrauber/bottom-sheet-flashlist).  Issue closed.

**Comment by ansh** [comment]
@tyrauber The docs still say to use BottomSheetFlatList but the only one that works is the FlatList from react-native-gesture-handler.

**Comment by victoriomolina** [comment]
@tyrauber Not sure if FlashList can be a direct descendant of `PanGestureHandler`.

```
<PanGestureHandler>
  <Animated.View style={globalStyles.flexContainer}>
    <Masonry
      data={searchedGIFs.length ? searchedGIFs : trendingGIFs}
      keyExtractor={keyExtractor}
      estimatedItemSize={ESTIMATED_GIF_ITEM_SIZE}
      renderItem={renderItem}
      itemMargin={1.5}
      numColumns={GIF_PICKER_NUM_COLUMNS}
      isLoading={isLoading}
      contentContainerStyle={styles.masonryContentContainer}
    />
  </Animated.View>
</PanGestureHandler>
```

**Comment by JJSLIoT** [comment]
For me just doing `renderScrollComponent={ScrollView}` for FlashList worked.

**Comment by sidtechno-haris** [comment]
just use Flatlist from react-native-gesture-handler and this error is resolve

**Comment by matteosprintdigital** [comment]
On BottomSheetModal set enableContentPanningGesture={false}
That solved it for me

**Comment by mattegalli** [comment]
On BottomSheetModal set enableContentPanningGesture={false}
That solved it for me

**Comment by tokyoshare** [comment]
> On BottomSheetModal set enableContentPanningGesture={false} That solved it for me

@mattegalli It resolved my problem. Thank you very much.

**Comment by shedworth** [comment]
In my case I had a `BottomSheetView` further up the component tree that was interfering with the pan gesture on Android only. Changing this to a standard RN `View` fixed the issue.

**Comment by AguSandoval** [comment]
> On BottomSheetModal set enableContentPanningGesture={false} That solved it for me

this definitely worked on my end. I'm using a `Animated.Flatlist` (Reanimated), and to solve the issue I just added this prop to the BottomSheet. Thanks @mattegalli !

**Comment by LovesWorking** [comment]
> Yes, there is! Build your own!
> 
> Wrap `FlashList` in `PanGestureHandler` with a shared ref. Pass the ref to FlashList with the attribute overrideProps, and pass `ScrollView` from `react-native-gesture-handler` to FlashList as renderScrollComponent.
> 
> Found here, [@shopify/FlashList does not integrate with createNativeWrapper](https://github.com/software-mansion/react-native-gesture-handler/issues/2175#top)
> 
> ```
> return (
>     <View 
>       style={{
>         height: '100%'
>        }}>
>         <PanGestureHandler
>           ref={panRef}
>         >
>           <FlashList
>             ref={list}
>             refreshing={refreshing}
>             onRefresh={() => {
>               setRefreshing(true);
>               setTimeout(() => {
>                 setRefreshing(false);
>               }, 2000);
>             }}
>             keyExtractor={(item: number) => {
>               return item.toString();
>             }}
>             renderItem={renderItem}
>             estimatedItemSize={100}
>             data={data}
>             renderScrollComponent={ScrollView}
>           />
>       </PanGestureHandler>
>     </View>
>   );
> };
> ```
> 
> FlashList Scroll and BottomSheet height adjustment works on iOS and Android!
> 
> [Snack updated](https://snack.expo.dev/@tyrauber/bottom-sheet-flashlist). Issue closed.

TY
