### ISSUE TITLE
[v4] Android Keyboard "doubling" in height and blocking content

### ISSUE THREAD

**Issue by calebpanza** [gorhom/react-native-scroll-bottom-sheet#1195]
# Bug

When using a Text Input on Android, the Keyboard seems to be "avoiding" twice and cuts off nearly half of my Sheet.

The example provided below is a screenshot from a dummy app that I put together in order to more easily display the disconnect. The "blue" is the parent container view which sits inside of the `BottomSheetModal` and the salmon is the `TextInput`.

When the Text Input is focused, the keyboard is brought up and you can see a white are which is pushing all of the content up, appearing to "double avoid" the keyboard.

<img width="50%" src="https://user-images.githubusercontent.com/45076058/203458707-dd2798de-8355-44b1-9556-732e6e84f5b5.png" />

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.6 (also seeing this issue in 0.67.5 on another project)   |
| react-native-reanimated         | ^2.13.0   |
| react-native-gesture-handler    | ^2.8.0 |

## Steps To Reproduce

1. Set up the `BottomSheetModal` per the [setup documentation](https://gorhom.github.io/react-native-bottom-sheet/modal/usage)
2. Include a `TextInput` in your `BottomSheetModal`
3. Run the application on a physical device
4. Open up the bottom sheet
5. Focus the TextInput

Describe what you expected to happen:

1. The content should fill the entire space provided by the bottom sheet modal down to the edge of the keyboard when the TextInput is focused

## Reproducible sample code

```js
import React, {useCallback, useMemo, useRef} from 'react';
import {View, Text, Pressable, StyleSheet} from 'react-native';
import {
  BottomSheetModalProvider,
  BottomSheetModal,
  BottomSheetTextInput,
  BottomSheetView,
} from '@gorhom/bottom-sheet';
import 'react-native-gesture-handler';

const App = () => {
  // ref
  const bottomSheetRef = useRef(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%', '98%'], []);

  // callbacks
  const handleSheetChanges = useCallback(index => {
    console.log('handleSheetChanges', index);
  }, []);

  const open = useCallback(() => {
    bottomSheetRef.current.present();
  }, [bottomSheetRef]);

  // renders
  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <View style={styles.contentContainer}>
          {/* Button on the Main Container that opens the Bottom Sheet */}
          <Pressable onPress={open}>
            <Text>Open the Sheet</Text>
          </Pressable>
        </View>

        {/* Bottom Sheet */}
        <BottomSheetModal
          multiline
          android_keyboardInputMode="adjustResize"
          topInset={50}
          ref={bottomSheetRef}
          index={0}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
          animateOnMount
          keyboardBehavior={'extend'}
          enablePanDownToClose={true}>
          {/* Flexed Content Container */}
          <BottomSheetView style={[styles.contentContainer, styles.base]}>
            {/* Multiline Text Input */}
            <BottomSheetTextInput
              multiline
              placeholder="Press Me"
              placeholderTextColor="gray"
              style={styles.textInput}
              returnKeyType="none"
            />
          </BottomSheetView>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    padding: 20,
  },
  base: {
    backgroundColor: 'blue',
  },
  textInput: {
    fontSize: 20,
    color: 'black',
    backgroundColor: 'salmon',
    textAlignVertical: 'top',
  },
});

export default App;
```

**Comment by calebpanza** [comment]
@gorhom not sure if there's a way for me to do it, but I've updated the comment to follow the template exactly. Could we get this issue re-opened??

**Comment by hotaryuzaki** [comment]
> @gorhom not sure if there's a way for me to do it, but I've updated the comment to follow the template exactly. Could we get this issue re-opened??

is it your manifest ```(android:windowSoftInputMode="adjustResize")```??
try change to adjustPan.
i solve with that, but it occur other issue after that.
i have absolute view as bottom sheet footer and it will sinking to the back of the keyboard when keyboard show
im stuck now

![Screenshot_2022-11-29-20-35-52-213_com brambang apps](https://user-images.githubusercontent.com/17826213/204543144-4225385b-18c1-4a22-b556-d1add32556f0.jpg)

**Comment by mak-022** [comment]
I had the same problem due to wrapping the bottom sheet content inside `KeyboardAvoidingView` while using `BottomSheetTextInput`, Removing the `KeyboardAvoidingView` container resolved it for me

**Comment by hotaryuzaki** [comment]
i find a solution here
https://github.com/gorhom/react-native-bottom-sheet/issues/618#issuecomment-1333324256

**Comment by jaiten-made** [comment]
+1

**Comment by calebpanza** [comment]
@mak-022 so you should wrap the entire bottom sheet in a keyboard avoiding view or nest it _inside_ of the bottom sheet?

**Comment by DD-hd** [comment]
> # 漏洞
> 在 Android 上使用文本输入时，键盘似乎“避开”了两次，并切断了我的 Sheet 的近一半。
> 
> 下面提供的示例是来自一个虚拟应用的屏幕截图，我将其组合在一起是为了更轻松地显示断开连接。“蓝色”是位于 内的父容器视图，`BottomSheetModal`而鲑鱼色是`TextInput`。
> 
> 当文本输入获得焦点时，键盘就会弹出，您可以看到一个白色区域将所有内容向上推，似乎在“双重避开”键盘。
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/45076058/203458707-dd2798de-8355-44b1-9556-732e6e84f5b5.png">
> 
> ## 环境信息
> 图书馆	版本
> @gorhom/底部表	4.4.5
> react-native	0.70.6（另一个项目的 0.67.5 中也看到了这个问题）
> react-native-重新激活	^2.13.0
> react-native-手势处理程序	^2.8.0
> ## 重现步骤
> 1. `BottomSheetModal`按照[安装文档](https://gorhom.github.io/react-native-bottom-sheet/modal/usage)进行设置[](https://gorhom.github.io/react-native-bottom-sheet/modal/usage)
> 2. 在`TextInput`您的`BottomSheetModal`
> 3. 在物理设备上运行应用程序
> 4. 打开底部表单
> 5. 聚焦 TextInput
> 
> 描述您期望发生的情况：
> 
> 1. 当 TextInput 获得焦点时，内容应该填满底部表单模式提供的整个空间，直到键盘边缘
> 
> ## 可复现的示例代码
> ```js
> import React, {useCallback, useMemo, useRef} from 'react';
> import {View, Text, Pressable, StyleSheet} from 'react-native';
> import {
>   BottomSheetModalProvider,
>   BottomSheetModal,
>   BottomSheetTextInput,
>   BottomSheetView,
> } from '@gorhom/bottom-sheet';
> import 'react-native-gesture-handler';
> 
> const App = () => {
>   // ref
>   const bottomSheetRef = useRef(null);
> 
>   // variables
>   const snapPoints = useMemo(() => ['25%', '50%', '98%'], []);
> 
>   // callbacks
>   const handleSheetChanges = useCallback(index => {
>     console.log('handleSheetChanges', index);
>   }, []);
> 
>   const open = useCallback(() => {
>     bottomSheetRef.current.present();
>   }, [bottomSheetRef]);
> 
>   // renders
>   return (
>     <BottomSheetModalProvider>
>       <View style={styles.container}>
>         <View style={styles.contentContainer}>
>           {/* Button on the Main Container that opens the Bottom Sheet */}
>           <Pressable onPress={open}>
>             <Text>Open the Sheet</Text>
>           </Pressable>
>         </View>
> 
>         {/* Bottom Sheet */}
>         <BottomSheetModal
>           multiline
>           android_keyboardInputMode="adjustResize"
>           topInset={50}
>           ref={bottomSheetRef}
>           index={0}
>           snapPoints={snapPoints}
>           onChange={handleSheetChanges}
>           animateOnMount
>           keyboardBehavior={'extend'}
>           enablePanDownToClose={true}>
>           {/* Flexed Content Container */}
>           <BottomSheetView style={[styles.contentContainer, styles.base]}>
>             {/* Multiline Text Input */}
>             <BottomSheetTextInput
>               multiline
>               placeholder="Press Me"
>               placeholderTextColor="gray"
>               style={styles.textInput}
>               returnKeyType="none"
>             />
>           </BottomSheetView>
>         </BottomSheetModal>
>       </View>
>     </BottomSheetModalProvider>
>   );
> };
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     padding: 24,
>     backgroundColor: 'grey',
>   },
>   contentContainer: {
>     flex: 1,
>     padding: 20,
>   },
>   base: {
>     backgroundColor: 'blue',
>   },
>   textInput: {
>     fontSize: 20,
>     color: 'black',
>     backgroundColor: 'salmon',
>     textAlignVertical: 'top',
>   },
> });
> 
> export default App;
> ```

  android:windowSoftInputMode="adjustNothing" , just simple

**Comment by DD-hd** [comment]
android:windowSoftInputMode="adjustNothing" 
  just simple to solve it

**Comment by Brune04** [comment]
> android:windowSoftInputMode="adjustNothing" just simple to solve it

Thanks, this worked for me, but now all of my other normal inputs don't adjust on android anymore. Do I just need to calculate the height of the keyboard and add that to all other keyboard avoiding views?
