### ISSUE TITLE
[v4] [IOS] Keyboard does not dismiss when the BottomSheetModal cointaining BottomSheetScrollView is collapsed

### ISSUE THREAD

**Issue by jc578271** [gorhom/react-native-scroll-bottom-sheet#1196]
# Bug

When `BottomTextInput` is focused and there is `BottomSheetScrollView` in `BottomSheetModal`, 
The keyboard does not dismiss if I swipe down through the keyboard.

https://user-images.githubusercontent.com/57795010/203501751-5c6e8d7d-3a39-4f05-b738-b22e51ec4181.mov

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.5  |
| react-native-reanimated         | next   |
| react-native-gesture-handler    | 2.7.0   |

## Steps To Reproduce

1. The keyboard dismiss if there is `BottomSheetScrollView` and the `BottomSheetModal` is collapsed

## Reproducible sample code

```typescript
import React, {useRef} from 'react';
import {
  BottomSheetModal,
  BottomSheetScrollView,
  BottomSheetTextInput,
} from '@gorhom/bottom-sheet';
import {Text, TouchableOpacity, View} from 'react-native';

export default () => {
  const bottomSheetRef = useRef<BottomSheetModal>(null);

  return (
    <View style={{flex: 1, paddingTop: 100}}>
      <TouchableOpacity onPress={() => bottomSheetRef.current?.present()}>
        <Text>Open</Text>
      </TouchableOpacity>

      <BottomSheetModal
        keyboardBlurBehavior={'restore'}
        ref={bottomSheetRef}
        keyboardBehavior={'interactive'}
        snapPoints={[150]}>
        <BottomSheetTextInput />
        <BottomSheetScrollView>
          <Text>Hello</Text>
        </BottomSheetScrollView>
      </BottomSheetModal>
    </View>
  );
};

```

**Comment by farhanhaider1** [comment]
having this issue!

**Comment by devDoubleH** [comment]
@jc578271  @farhanhaider1 
There is a **[Keyboard](https://reactnative.dev/docs/keyboard#dismiss)** module in the react native library.
And you can simply put the `dismiss()` method in the bottomsheet's `onClose` method.

Here is the code:
```
        onClose={() => {
          Keyboard.dismiss();
        }}
```
