### ISSUE TITLE
[v4] Excessive ANR's caused by bug in Reanimated

### ISSUE THREAD

**Issue by Dakuan** [gorhom/react-native-scroll-bottom-sheet#1199]
# Bug

Lots of ANR in Android play store. [Caused by bug in Reanimated](https://github.com/software-mansion/react-native-reanimated/issues/2812). Could be related [to this](https://github.com/gorhom/react-native-bottom-sheet/issues/1041)

**Comment by pierroo** [comment]
By any chance, were you able to find a solution to this problem @Dakuan ?
facing the exact same one :/
