### ISSUE TITLE
[v4] BottomSheetModalProvider not working? error: "Couldn't register the navigator..."

### ISSUE THREAD

**Issue by igorulian** [gorhom/react-native-scroll-bottom-sheet#1210]
# Bug

The documentation says to wrap my app with BottomSheetModalProvider, but when i do that it doesn't work and gives an error.
I also tried to wrap only the BottomSheet component, it worked, in some cases, but when there is a navigation component "near" the BottomSheet it also stops working.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.5   |
| react-native                    | 0.70.5   |
| react-native-reanimated         | ^2.12.0   |
| react-native-gesture-handler    | ^2.8.0   |

## Steps To Reproduce

1. Wrapping the whole app with BottomSheetModalProvider
```js
export default function App() {
   return (
        ....
        <GestureHandlerRootView style={{ flex: 1 }}>
          <GlobalContext>
            <BottomSheetModalProvider>
              <Routes />
            </BottomSheetModalProvider>
          </GlobalContext>
        </GestureHandlerRootView>
 )}

```
The BottomSheet been used inside the app:
```js
const MyScreen = () => {
return (
  <>
    <SafeAreaView>
          ....
          <Tab.Navigator screenOptions={tabBarOptions}>
            <Tab.Screen options={{ title: 'Tab1' }} name="Tab1" component={Component1}>
            <Tab.Screen options={{ title: 'Tab2' }} name="Tab2" component={Component2}>
          </Tab.Navigator>
    </SafeAreaView>

    <BottomSheetModal
      footerComponent={footerComponent}
      ref={bottomSheetRef}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      style={styles.container}
      backdropComponent={(props) => (
        <CustomBackdrop {...props} index={index} onPress={closeSheet} />
      )}
    >
        <SheetContent/>
     </BottomSheetModal>
  </>
```
Gives the error:
![image](https://user-images.githubusercontent.com/48739190/205298989-62a8470c-47af-4b15-92db-15cf31d74cd6.png)

Describe what you expected to happen:

1. I expected to use the BottomSheetModalProvider once, in my app root, and then be able to use the BottomSheetModal component anywhere in my app.

## Reproducible sample code
I'm not using expo for the project.. so i wont be able to provide a snack example with the error :|

**Comment by Skipperlla** [comment]
@igorulian Did you solve the problem, or would you like me to make a snack that works for you and throw it at you?
