### ISSUE TITLE
[v4] | Keyboard being shown cuts BottomSheetFlatList content on Android

### ISSUE THREAD

**Issue by dancamdev** [gorhom/react-native-scroll-bottom-sheet#1211]
# Bug

I have a simple bottom sheet that contains an `BottomSheetTextInput` and a `BottomSheetFlatList`.

I set the bottom sheet `keyboardBehaviour` to `extend` as I want it to automatically expand when the keyboard gets shown.

The bug seems to be related to the the whole screen being moved up as the keyboard opens - while BottomSheet still moves the content up by the keyboard height, causing a white space above the keyboard.

It can be better shown through images, so here they are, first one with the keyboard closed, second one with the keyboard open.

![photo_2022-12-02_16-50-57](https://user-images.githubusercontent.com/43640732/205332292-33333c33-ab18-4b0f-83a8-f886003da1fa.jpg)

![photo_2022-12-02_16-51-02](https://user-images.githubusercontent.com/43640732/205332335-64ce2bd9-da8c-45c1-8a30-ba03e0970e98.jpg)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.5  |
| react-native-reanimated         | 2.12.0   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

I've created a small snippet below that should reproduce the issue. Mind the issue only happens on android due to how the OS handles the keyboard.

## Reproducible sample code

[Reproducible Sample](https://snack.expo.dev/@appandup/bottom-sheet-v4-reproducible-issue-template)

**Comment by hotaryuzaki** [comment]
i find a solution here
https://github.com/gorhom/react-native-bottom-sheet/issues/618#issuecomment-1333324256

**Comment by misfits91** [comment]
@dancamdev did you find a solution for this? I'm facing the same problema.
