### ISSUE TITLE
Unable to call and lalunch BottomSheet from another component

### ISSUE THREAD

**Issue by designsheikh** [gorhom/react-native-scroll-bottom-sheet#1213]
Hi,

I'm trying to setup the bottom sheet so that it can be launched on button click from another component.

For example:

HomeScreen (Has button called 'LaunchBottomSheet')

ComponentX (Holds BottomSheet, BottomSheetView and data)

Awaiting your response

Thank you

**Comment by anis-18** [comment]
> Hi,
> 
> I'm trying to setup the bottom sheet so that it can be launched on button click from another component.
> 
> For example:
> 
> HomeScreen (Has button called 'LaunchBottomSheet')
> 
> ComponentX (Holds BottomSheet, BottomSheetView and data)
> 
> Awaiting your response
> 
> Thank you

did you find any solution
