### ISSUE TITLE
[v4] | Calling BottomSheetModal from another component is undefined

### ISSUE THREAD

**Issue by designsheikh** [gorhom/react-native-scroll-bottom-sheet#1215]
# Bug

My aim is to open the BottomSheetModal from a different component. I have 2 components 

1. BottomSheetComponent
2. LocationComponent 

BottomSheetComponent has the code as it is found on the 'Usage' section on the website instructions. In LocationComponent,  i have a TouchableOpacity which calls a ref that is sent to BottomSheetComponent as a Forward Ref. However, when doing a console log, upon clicking the TouchableOpacity, it is returned as undefined.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | "^4"  |
| react-native                    | 0.70.5   |
| react-native-reanimated         | "~2.12.0" |
| react-native-gesture-handler    | "~2.8.0"  |

## Steps To Reproduce

**BottomSheetModalComponent**
```
export default function BottomSheetModalComponent({ref}) {

// ref
const bottomSheetModalRef = useRef<BottomSheetModal>(null);

// variables
const snapPoints = useMemo(() => ['25%', '50%'], []);

// callbacks
const handlePresentModalPress = useCallback(() => {
  ref.current?.present();
}, []);
const handleSheetChanges = useCallback((index: number) => {
  console.log('handleSheetChanges', index);
}, []);

// renders
return (
  <BottomSheetModalProvider>
    <View>
      <BottomSheetModal
        ref={ref}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheetModal>
    </View>
  </BottomSheetModalProvider>
);
};
```

**Location Bar Component**

```
export default function LocationBar() {
   // Create Ref
  const userBottomSheetRef = useRef<BottomSheetModal>(null);

  // Pass ref into the bottom sheet component
  <LocationBottomSheet ref={userBottomSheetRef} snapPoints={["30%"]}/>

  return (
    <>
      <View style={{ flexDirection: "row" }}>
        <View style={styles.locationBar}>
          <Octicons style={styles.locationIcon} name="location" size={18} />
          <TouchableOpacity onPress={() => {

            // LINE BELOW RETURNS AS UNDEFINED
            userBottomSheetRef.current?.present()

          }}>
            <Text style={{fontSize: 17, fontWeight: '600'}}>{userLocation}</Text>
          </TouchableOpacity>
          <Ionicons style={styles.chevronIcon} name="chevron-down" size={12} />
        </View>
      </View>
    </>
  );
}
```

Describe what you expected to happen:

1. Touchable Opacity is clicked in LocationComponent 
2. BottomSheetModal is launched

**Comment by hardik-javascript** [comment]
@designsheikh Are you able to fix this issue?
