### ISSUE TITLE
[v4] keyboard not pushing bottomsheet

### ISSUE THREAD

**Issue by thedev204** [gorhom/react-native-scroll-bottom-sheet#1216]
# Bug

### The Issue

https://user-images.githubusercontent.com/116882323/206188924-cd466a47-3bf1-4f5a-a104-369e549d4185.mp4

### This is my Code

    const snapPoints = useMemo(() => ['25%', '25%', '60%'], []);
    const {animatedHandleHeight, animatedContentHeight} =
     useBottomSheetDynamicSnapPoints(snapPoints);

     <BottomSheetModal
    ref={bottomSheetModalRef}
    index={1}
    snapPoints={snapPoints}
    enableOverDrag={true}
    keyboardBehavior='extend'
    android_keyboardInputMode='adjustResize'
    handleHeight={animatedHandleHeight}
    contentHeight={animatedContentHeight}>
    <View style={[styles.contentContainer]}>
      
        <BottomSheetTextInput
          style={styles.input}
          onChangeText={val => setValue(val)}
          keyboardType="phone-pad"
        />
      ...
    </View>
  </BottomSheetModal>

### My Menifest

     android:windowSoftInputMode="adjustPan|adjustResize"

**Comment by ser-emejia** [comment]
Try to change `keyboardBehavior='extend'` to `keyboardBehavior='interactive'`
