### ISSUE TITLE
BottomSheetModalProvider when navigate to screen when modal is active the modal is always open

### ISSUE THREAD

**Issue by shop-fluencer** [gorhom/react-native-scroll-bottom-sheet#1217]
https://user-images.githubusercontent.com/101994056/206203757-5736e4e0-19b6-40bb-940a-587774bcb672.mp4

# Bug

Hello,

I use BottomSheetModal and when I open my modal and I have a button to navigate to a screen then if I press the button and I navigate to a screen the modal is always showing. How can I make that the modal is only inside the current screen showing ?

Look at the video

## Environment info

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.19044
Binaries:
Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 2020.3.0.0 AI-203.7717.56.2031.7583922
npmPackages:
expo: ^47.0.0 => 47.0.8
react: 18.1.0 => 18.1.0
react-dom: 18.1.0 => 18.1.0
react-native: 0.70.5 => 0.70.5
react-native-web: ~0.18.7 => 0.18.8
Expo Workflow: managed

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.0  |
| expo                   | 47   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

## Reproducible sample code

App.tsx
```
     <SafeAreaProvider>
      <SafeAreaView style={s.rootView}>
        <GestureHandlerRootView style={s.rootView}>
          <NavigationContainer onReady={onLayoutRootView}>
            <BottomSheetModalProvider>
                <NativeStackWrapper />
            </BottomSheetModalProvider>
            <Toast position='bottom' config={ToastConfig} />
          </NavigationContainer>
          </GestureHandlerRootView>
        </SafeAreaView>
      </SafeAreaProvider>
```

CreateData

```
        <ModalUploadImageAndSetTextForContest
          ref={modalUploadProductRef}
          onPress={handleAddProduct}
        />
```

PS: if I remove the BottomSheetModalProvider from App.tsx and added it in CreateData.tsx then it works but then the keybaord mode is broken and the header is not transluctent and input on modal is wired... has anyone a soulution ?

**Comment by bryanprimus** [comment]
any update?
