### ISSUE TITLE
[v4] Text is cropped for buttons inside bottomsheet on IOS only 

### ISSUE THREAD

**Issue by jeannei** [gorhom/react-native-scroll-bottom-sheet#1218]
# Bug

Buttons appearing inside a bottom sheet (on IOS) get cropped off. This behavior is random and does not occur every time, the best way to reproduce is to constantly refresh the app. This happens in the simulator and on my ios device.

<img width="324" alt="Screen Shot 2022-12-07 at 9 08 23 AM" src="https://user-images.githubusercontent.com/15200569/206202498-ef77ebb0-bf18-458a-a9df-f79a692c4bc9.png">

Another example:

<img width="286" alt="Screen Shot 2022-12-07 at 9 20 26 AM" src="https://user-images.githubusercontent.com/15200569/206203365-373eb840-ea40-45b0-9f7a-1edea9909768.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.1   |
| react-native                    | 0.69.0  |
| react-native-reanimated         | 2.9.1  |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Create a simple bottomsheet from https://gorhom.github.io/react-native-bottom-sheet/usage
2. Add a button
3. Add the following style to the content container:
```
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  }
```
4. Continue refreshing the app until the text gets cropped off. E.g.
<img width="245" alt="Screen Shot 2022-12-07 at 9 18 07 AM" src="https://user-images.githubusercontent.com/15200569/206202742-cd276b53-7e3e-43e7-b785-aa692c88bb39.png">

Expected behavior:

Text does not get cut off:

<img width="299" alt="Screen Shot 2022-12-07 at 9 21 38 AM" src="https://user-images.githubusercontent.com/15200569/206203582-bfd5b172-59ad-4081-8a39-371800bf34c0.png">

## Reproducible sample code

1. Open https://snack.expo.dev/@jeannei91/bottom-sheet-cropped-button
2. Switch to the ios view
3. Reload the app until the button is cropped

Note this was also reported [last year ](https://github.com/gorhom/react-native-bottom-sheet/issues/645)but the issue was closed

**Comment by jeannei** [comment]
It appears setting an explicit height on the button resolves this issue, see example (note using react native paper button in this example):

<img width="272" alt="Screen Shot 2022-12-08 at 10 26 12 PM" src="https://user-images.githubusercontent.com/15200569/206617476-8def196e-2c48-4a63-be08-e7a3f6931942.png">

**Comment by rchvalbo** [comment]
This issue is not stale... This is still happening.

**Comment by sahilsian** [comment]
Issue is still happening.

**Comment by sangameshsomawar** [comment]
The issue is still happening, as a workaround, I am adding min-height to every text in the button.

**Comment by itsramiel** [comment]
Experiencing this with latest v5 alpha 3

**Comment by balloman** [comment]
Can this issue be reopened?
