### ISSUE TITLE
Allow testID for BottomSheetBackdrop

### ISSUE THREAD

**Issue by RohovDmytro** [gorhom/react-native-scroll-bottom-sheet#1219]
# Feature Request

Would be cool to pass a testID to `BottomSheetBackdrop` component.

## Why it is needed

The prop can be utilized during end-to-end testing.

### Code sample

```
const renderBackdrop = useCallback(
    (props: React.ComponentProps<typeof BottomSheetBackdrop>) => (
      <BottomSheetBackdrop testID={"Wow"} {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
    ),
    []
  );
````

P.S. Thank you @gorhom for such an awesome and maintained library. You're a hero.

**Comment by AliakseiPaseishviliGetquin** [comment]
The same thing about BottomSheetTextInput. Actually it blocked by {TextInput} from 'react-native-gesture-handler'. But I haven't found out how to solve it.

**Comment by joebigboi** [comment]
I have the same request for an e2e that will allow to tap on a backdrop via testID
