### ISSUE TITLE
IOS Modal Presentation Style.

### ISSUE THREAD

**Issue by arunabhverma** [gorhom/react-native-scroll-bottom-sheet#1226]
# Feature Request
If it is possible with the current version of this library then please guide me on how to can I implement it.

## Why it is needed
Because this is a native ios style to show a full-screen modal. And this library provides us with all things like the bottom sheet and modal if there is a way to implement ios modal presentation it will be the cherry on the cake. 

## Possible implementation
I'll prefer to use reanimated for this type of animation.

## Code sample
```
<View style={styles.container}>
  <BottomSheet
    ref={bottomSheetRef}
    index={1}
    presentation={'modal'}
    snapPoints={snapPoints}
    onChange={handleSheetChanges}>
    <View style={styles.contentContainer}>
      <Text>Awesome 🎉</Text>
    </View>
  </BottomSheet>
</View>
```

## Expected look.
![AbdIl](https://user-images.githubusercontent.com/59590144/206978337-26c76e8c-e9a3-4a10-a7ca-65609943909d.png)

**Comment by nrwinner** [comment]
Why not just use a regular Modal from React Native here? https://reactnative.dev/docs/modal you can set the `presentationStyle` prop to "pageSheet" to get the look you're after.

**Comment by arunabhverma** [comment]
> Why not just use a regular Modal from React Native here? https://reactnative.dev/docs/modal you can set the `presentationStyle` prop to "pageSheet" to get the look you're after.

This is a good idea but if we go for this we are not able to use the swipe down to close in android.

We have to build another component for this.

**Comment by nrwinner** [comment]
Hmm, in that case I'd recommend checking out the native modals in [React Navigation](https://reactnavigation.org/docs/native-stack-navigator/#presentation) or [React Native Navigation](https://github.com/wix/react-native-navigation). This repo is specifically for bottom sheets and most likely will not implement iOS modals directly.
