### ISSUE TITLE
[v4] Android Crash on Resizing Screen - BottomSheetContainer

### ISSUE THREAD

**Issue by getterhiss** [gorhom/react-native-scroll-bottom-sheet#1228]
# Bug

The app crashes when re-opened from the background with the message: `Cannot add new property 'value'`

![Android Crash](https://user-images.githubusercontent.com/40630623/207411070-a493414f-604b-4bde-b1f2-668d356db54c.png)

This happens exclusively on **Android** devices. Through our monitoring systems we have been able to identify that this happens on phones with a resizable screen (foldable devices) or devices that allow adjusting the display size through settings.

Per our error monitoring, this happens _the most_ on OnePlus BE2025 devices that have turned on (automatic?) display size adjustments.

We have implemented the `bottom-sheet` library through the provider, by adding the `<BottomSheetModalProvider />` in the root of our application. Specifically between `<GestureHandlerRootView />` and `<SafeAreaProvider />`.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.67.5   |
| react-native-reanimated         | 2.13.0   |
| react-native-gesture-handler    | 2.8.0   |

### Setup

1. Follow setup for bottom-sheet, reanimated and gesture-handler libraries as provided in the instructions.
2. Setup `@gorhom/bottom-sheet` through `<BottomSheetModalProvider />` in the root of the project
3. Setup a Resizable Android emulator in Android Studio (I am using API 33).

### Triggering the crash
4. Run the project on the emulator and open the application
5. Change the emulator dimensions by switching to a foldable device mode
6. Observe the crash

_or_

5. Open device settings -> Display -> Display size and text -> adjust "Display size" to larger
6. Go back to the application and observe the crash

## Reproducible sample code

**Comment by witPranav** [comment]
This could be fixed by a patch as mentioned [here](https://github.com/gorhom/react-native-bottom-sheet/issues/1292)
We also applied it to BottomSheetContainer.tsx so it became like this

[@gorhom+bottom-sheet+4.4.5.patch](https://github.com/gorhom/react-native-bottom-sheet/files/11450921/%40gorhom%2Bbottom-sheet%2B4.4.5.patch)
