### ISSUE TITLE
Have the bottom sheet opened by default

### ISSUE THREAD

**Issue by pierroo** [gorhom/react-native-scroll-bottom-sheet#1231]
# Feature Request

Perhaps I missed it in the doc, but is there a way to have the BottomSheet automatically opened when entering a specific screen?
Ideally through a props (modalize uses "alwaysOpen")
Of course I can programmatically open it from UseEffect, but it requires a timeout that seems quite random.
(triggering the opening in useeffect right away doesnt work, a timeout of 1000ms at least seems to work, but feels like a hack)

**Comment by mhsfh** [comment]
I have the same need is there any way to achieve this?
