### ISSUE TITLE
How to detect if bottomsheet is closed and how to fade or add opacity to the hole screen but not bottomsheet

### ISSUE THREAD

**Issue by anis-18** [gorhom/react-native-scroll-bottom-sheet#1234]
# Feature Request

How to detect if bottomsheet is closed and how to fade or add opacity to the hole screen but not bottomsheet

## Why it is needed

It's needed to fade the background of the hole component when bottomsheet is opened

## Possible implementation

return boolean isOpened when translateY = 0

### Code sample
```js
if translateY === 0 return true
else rturn false
```

**Comment by dchhetri** [comment]
@anisamirouche I have something like this which adds opacity to the background
```
  const BackdropElement = useCallback(
    (backdropProps: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...backdropProps}
        opacity={0.7}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    []
  )

  <BottomSheet
      // ... other props
      backdropComponent={BackdropElement}
    >
```
That adds opacity to the background behind, which basically dims it.

**Comment by anis-18** [comment]
> backdropComponent={BackdropElement}

Thanks it's working perfectly

**Comment by ilyadynin** [comment]
@dchhetri You are my hero, you saved my nerves with your code. If you want, I can Paypal you $5 bro, you solved an issue that I have been sitting on for like 2,5 hours by now.

**Comment by dchhetri** [comment]
> @dchhetri You are my hero, you saved my nerves with your code. If you want, I can Paypal you $5 bro, you solved an issue that I have been sitting on for like 2,5 hours by now.

Glad it helped. Nah it’s cool. I appreciate the offer man.

**Comment by guillainbisimwa** [comment]
```
  const BackdropElement = useCallback(
    (backdropProps) => (
      <BottomSheetBackdrop
        {...backdropProps}
        opacity={0.7}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    []
  )

```
Thank so much for you solution!

**Comment by jkrmarmol** [comment]
this is my way to check bottomsheet open/closed
```js
  <BottomSheetModal
    onChange={(e) => {
      if (e === -1) {
        // -1 closed
      }
        // 0 open
    }}
  >
```
