### ISSUE TITLE
[v4] | [v2] Bottom Sheet Modal Closes Before Keyboard

### ISSUE THREAD

**Issue by logs123** [gorhom/react-native-scroll-bottom-sheet#1235]
# Bug

When attempting to close the Bottom Sheet Modal, the modal closes before the Keyboard does. This is an expo project.

[Here is a video of the bug](https://vimeo.com/784080170)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.5   |
| react-native-reanimated         |~ 2.12.0   |
| react-native-gesture-handler    | ~2.8.0   |

## Steps To Reproduce

1. After both text inputs are filled, click the post button.

Describe what you expected to happen:

1. When clicking the post button, I want the Keyboard to close first or simultaneously to the modal closing.

## Reproducible sample code

`
import React, { useCallback, useMemo, useState } from "react";
import { Button, Text, TouchableOpacity, View } from "react-native";
import { useDispatch } from "react-redux";
import { createAnnouncement, getUserAnnouncements } from "../../../redux/actions";
import { BottomSheetModal, BottomSheetTextInput } from "@gorhom/bottom-sheet";

import styles from "./styles";

export default function ComposeModal({ modalRef, isModalOpen, setIsModalOpen, currentUserObj, uid }) {

    const dispatch = useDispatch();
    const [title, setTitle] = useState("");
    const [body, setBody] = useState("");

    const snapPoints = useMemo(() => ["40%"], []);

    const handlePost = (title, body, creator) => {
        modalRef.current?.close();
        dispatch(createAnnouncement(title, body, creator, uid));
        setIsModalOpen(!isModalOpen);
        dispatch(getUserAnnouncements(currentUserObj.org, currentUserObj.chapter));
    }

    const handleClosePress = () => {
        modalRef.current?.close();
    }

    return(
        <BottomSheetModal
            ref={modalRef}
            index={0}
            snapPoints={snapPoints}
            onDismiss={() => {setIsModalOpen(false); setTitle(""); setBody("")}}
            style={{borderWidth: .5, borderRadius: 15, backgroundColor: "#E5FAFF"}}
            keyboardBehavior="interactive"
            keyboardBlurBehavior="restore">
            <View style={styles.topModalContainer}>
                <Text style={styles.userModalInfo}>{currentUserObj.firstName} {currentUserObj.lastName}</Text>
                <Button
                    title="Cancel"
                    onPress={handleClosePress}/>
            </View>
            <View style={styles.bottomModalContainer}>
                <BottomSheetTextInput
                    style={styles.titleInput}
                    placeholder="Title..."
                    placeholderTextColor={"#808080"}
                    onChangeText={(text) => setTitle(text)}/>
                <BottomSheetTextInput
                    style={styles.messageInput}
                    placeholder="Begin your announcement here..."
                    placeholderTextColor={"#808080"}
                    multiline
                    numberOfLines={10}
                    onChangeText={(text) => setBody(text)}
                    onContentSizeChange={(event) => {event.nativeEvent.contentSize}}/>
            </View>
            <View style={{position: "absolute", bottom: 0, marginBottom: 10, right: 30}}>
                <TouchableOpacity
                    disabled={title == "" || body == ""}
                    style={[styles.postButton,{backgroundColor: (title == "" || body == "") ? "#FFFFFF" : "#72AEBC"}]}
                    onPress={() => {handlePost(title, body, currentUserObj)}}>
                    <Text style={styles.postButtonText}>Post</Text>
                </TouchableOpacity>
            </View>
        </BottomSheetModal>
    );
}`

**Comment by ser-emejia** [comment]
Which is your expo version?

Did you try with `modalRef.current?.dismiss();` instead of `modalRef.current?.close();`

**Comment by logs123** [comment]
> Which is your expo version?
> 
> Did you try with `modalRef.current?.dismiss();` instead of `modalRef.current?.close();`

Expo version ~47.0.8

Using dismiss() produces the same result as close().

**Comment by OwenMelbz** [comment]
We had the same issue, I ended up adding an `onPress` to the backdrop component doing a `Keyboard.dismiss()` which puts it more in sync

**Comment by ser-emejia** [comment]
I had to do something like @OwenMelbz , but in my case only works in `iOS`, in `Android` had issues, so, I had to validate that:

```
const handleBackdropPress = () => {
    if (Platform.OS !== 'ios') return;

    Keyboard.dismiss();
};
```

```
const renderBackdropComponent = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={1}
        pressBehavior="close"
        disappearsOnIndex={-1}
        onPress={handleBackdropPress}
      />
    ),
    []
);
```

```
<BottomSheetModal
    ...
    backdropComponent={renderBackdropComponent}>
```
Hope it helps!

**Comment by pfcodes** [comment]
Is there a no-hack fix in the work for this?

**Comment by RichardLindhout** [comment]
This is still happening on latest alpha and reanimated 3

**Comment by gorhom** [comment]
@RichardLindhout could you share an expo snack with a simple code to reproduce the issue.

**Comment by tamighi** [comment]
I have this that works sometimes, but the "to" value is set to -1 if animated by the keyboard after opened a first time, so I set autofocus and do not restore position on Keyboard close.

The only thing that could make it bug if the user snap it back to position without keyboard after removing the keyboard, then try again to focus an input (which should not really happen, but still I don't know why the to value is set to -1 in these cases)

```
  const onAnimate = (_: number, to: number) => {
    if (to === -1) {
      Keyboard.dismiss();
      setTimeout(() => {
        bottomSheetRef.current?.close();
      }, 50);
    }
  };
  
  <BottomSheetModalProvider>
      <BottomSheetModal
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        keyboardBehavior="interactive"
        android_keyboardInputMode="adjustResize"
        onDismiss={onClose}
        onAnimate={onAnimate}
        backdropComponent={renderBackdrop}
        onChange={handleSheetPositionChange}
        handleStyle={{ backgroundColor: colors.mainBackground }}
        backgroundStyle={{ backgroundColor: colors.mainBackground }}
      >
        {children}
      </BottomSheetModal>
    </BottomSheetModalProvider>
```
