### ISSUE TITLE
Question: Is there a way to provide my own FlatList and have it's scrolling interact with BottomSheet as done with BottomSheetFlatList?

### ISSUE THREAD

**Issue by dchhetri** [gorhom/react-native-scroll-bottom-sheet#1238]
# Feature Request

Basically I have another FlatList which I would like to have it's scrolling respect that of BottomSheet. I'm wondering if there is a way to provide that functionality to my custom FlatList or if I have to use BottomSheetFlatList? 

## Why it is needed
I'm using a separate library which provides additional functionality on top of FlatList. I what that to respect the proper scrolling behavior as done with BottomSheetFlatList.

**Comment by allenhartwig** [comment]
I'm interested in this for all wrapped components. For example, I'd like to use the [UI Kitten Input](https://akveo.github.io/react-native-ui-kitten/docs/components/input/overview#input) instead of the vanilla React Native `Input` for the `BottomSheetTextInput` render component.

**Comment by JJSLIoT** [comment]
Can we re-open this issue? I also have the same feature request. I want to use Shopify `FlashList` instead of `BottomSheetFlatList` because of its immense performance benefit to render large list for my use case.
