### ISSUE TITLE
[v4] | [v2] backgroundColor does not work

### ISSUE THREAD

**Issue by laurencebedford** [gorhom/react-native-scroll-bottom-sheet#1242]
# Bug

  Hi, I am passing backgroundColor in a style tag to my BottomSheetModal like so:
```
<BottomSheetModal
          ref={bottomSheetModalRef}
          index={0}
          snapPoints={snapPoints}
          style={{ backgroundColor: "red" }}
        >
        </BottomSheetModal>
```

However it does not work as expected it only changes the colour external to the rounded corners:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/69059597/210008873-88575cdd-c749-4501-821f-12271a61ffde.png">

I have also tried including a view within my BottomSheetModal where I change the background colour aswell:
```
<BottomSheetModal
          ref={bottomSheetModalRef}
          index={0}
          snapPoints={snapPoints}
          style={{ backgroundColor: "red" }}
        >
          <View
            style={{
              flex: 1,
              justifyContent: "center",
              backgroundColor: "red",
            }}
          ></View>
        </BottomSheetModal>
```
 As you can see there is still that rectangle at the top of the modal that's white still:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/69059597/210009101-ee680e61-b74d-4487-bcea-5e30db6076fe.png">

How can I change the colour of the whole modal to something like so:
![image](https://user-images.githubusercontent.com/69059597/210009155-d9d9a133-7eed-4442-844b-eef47f1f24bc.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | Latest |
| react-native                    | Latest  |
| react-native-reanimated         | Latest   |
| react-native-gesture-handler    | Latest  |

## Steps To Reproduce

1. use my code above in your own project as a modal with the styling examples

Describe what you expected to happen:

1. I expect the whole modal to change colour not just parts

**Comment by LoremIpsum667** [comment]
Hello, I have the same problem on my Android device: 

"@gorhom/bottom-sheet": "^3",
"react-native": "0.70.5",
"react-native-reanimated": "~2.12.0",
"react-native-gesture-handler": "~2.8.0",

![Capture d’écran 2023-01-03 111515](https://user-images.githubusercontent.com/94966007/210338149-2bf22565-285c-4a07-840b-0f179893492f.png)
![photo_2023-01-03_11-16-30](https://user-images.githubusercontent.com/94966007/210338162-492e3afc-b1b6-4d03-9ab1-bf38839438ac.jpg)

**Comment by annalukash** [comment]
> Hello, I have the same problem on my Android device:
> 
> "@gorhom/bottom-sheet": "^3", "react-native": "0.70.5", "react-native-reanimated": "~2.12.0", "react-native-gesture-handler": "~2.8.0",
> 
> ![Capture d’écran 2023-01-03 111515](https://user-images.githubusercontent.com/94966007/210338149-2bf22565-285c-4a07-840b-0f179893492f.png) ![photo_2023-01-03_11-16-30](https://user-images.githubusercontent.com/94966007/210338162-492e3afc-b1b6-4d03-9ab1-bf38839438ac.jpg)

Have you tried to use backgroundStyle props?

**Comment by LoremIpsum667** [comment]
I solved the problem. 

In your BottomSheetModal add => backgroundComponent={CustomBackground}

And at the top of your code: 

```
const CustomBackground = ({ style, animatedIndex }) => {
  //#region styles
  const containerAnimatedStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(
      animatedIndex.value,
      [0, 1],
      ["#2C2C2C", "#1E1E1E"]
    ),
    borderRadius: interpolate(animatedIndex.value, [0, 1], [0, 15]),
  }));
  
  const containerStyle = useMemo(
    () => [style, containerAnimatedStyle],
    [style, containerAnimatedStyle]
  );
  //#endregion
  // render
  return <Animated.View pointerEvents="none" style={containerStyle} />;
};
```

**Comment by quentininou** [comment]
You must use the backgroundStyle props and add an object with the property backgroundColor :
<BottomSheetModal
                        **backgroundStyle={{
                            backgroundColor: 'red'
                          }}**
                        handleIndicatorStyle={listPaymentComponentStyle.handleIndicatorStyle}
                        // backgroundStyle={listPaymentComponentStyle.bottomSheetBackground}
                        enablePanDownToClose={true}
                        ref={bottomSheetModalRef}
                        snapPoints={snapPoints}>
{children}
</BottomSheetModal>
