### ISSUE TITLE
[v4] | [v2] How to control bottom sheet not automatically pop up? #1243

### ISSUE THREAD

**Issue by jojowhoooo** [gorhom/react-native-scroll-bottom-sheet#1244]
# Bug
bottom sheet automatically pop up

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.5   |
| react-native                    | 0.70.5   |
| react-native-reanimated         | ~2.12.0   |
| react-native-gesture-handler    | ~2.8.0   |

## Steps To Reproduce

1. I set a button to handle my bottom sheet in my current screen. 
2. But the button sheet pops up automatically at first time I come in my screen.
3. How to set bottom sheet close at first time I come in my screen?

Describe what you expected to happen:

1. bottom sheet not automatically pop up

**Comment by NoelJFreitas** [comment]
I have the same problem, any solution?
