### ISSUE TITLE
[v4] Invariant Violation: new NativeEventEmitter() requires a non-null argument

### ISSUE THREAD

**Issue by airowe** [gorhom/react-native-scroll-bottom-sheet#1258]
# Bug

After installation, iOS fails to build and gets hung on `'new NativeEventEmitter()' requires a non-null argument`

![simulator_screenshot_4512B8BF-DC73-44F6-8B15-A60A62BE5A3A](https://user-images.githubusercontent.com/52685/211064743-10d3e8b7-9570-4a70-a8b2-cd9a69544a9c.png)

I have tried uninstalling, reinstalling, clearing Derived Data and Build Folder, clearing Pods and reinstalling, etc. Android is building fine, for what it's worth.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.67.2   |
| react-native-reanimated         | 2.13.0   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

1. Use `npm install @gorhom/bottom-sheet`
2. Imported BottomSheet, attempted to use it
3. See the error

Describe what you expected to happen:

1. Able to import and use BottomSheet
2.

## Reproducible sample code

`export const Dialog: React.VFC = () => {
const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

return (<BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        bottomInset={46}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome</Text>
        </View>
      </BottomSheet>);},`

**Comment by tonystrawberry** [comment]
I got exactly the same problem using Expo... I would be grateful if someone could lead us to a solution 🙏

**Comment by makustova** [comment]
Had a similar issue (my app was set up with bare React native CLI), somehow solved by building my app in XCode instead of terminal ¯\_(ツ)_/¯

**Comment by mtzfactory** [comment]
I'm experiencing the same bug... 

```
ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
    at BottomSheet (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:190596:74)
    at PortalHostComponent (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:193375:20)
    at PortalProviderComponent (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:193459:33)
    at BottomSheetModalProviderWrapper (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:193674:24)
    at BottomSheetView (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:187634:22)
    at PreventRemoveProvider (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:183612:25)
    at NavigationContent (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:184512:22)
    at anonymous (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:184523:27)
    at BottomSheetNavigator (http://localhost:8081/src/main.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.Mobile:187430:18)
    at MainNavigator
```

My env:

```
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/rmartinez/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: 10.2.2 => 10.2.2
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

dependencies:

```
{
  "@gorhom/bottom-sheet": "^4.4.6",
  "@react-navigation/bottom-tabs": "^6.5.7",
  "@react-navigation/native": "^6.1.6",
  "@react-navigation/native-stack": "^6.9.12",
  "@th3rdwave/react-navigation-bottom-sheet": "^0.2.4",
  "axios": "^1.4.0",
  "change-case": "^4.1.2",
  "expo": "^48.0.17",
  "expo-auth-session": "^4.0.3",
  "expo-barcode-scanner": "^12.3.2",
  "expo-localization": "^14.1.1",
  "expo-random": "^13.1.1",
  "expo-web-browser": "^12.1.1",
  "i18next": "^22.5.0",
  "intl-pluralrules": "^2.0.0",
  "mobx": "^6.9.0",
  "mobx-react-lite": "^3.4.3",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "react-i18next": "^12.3.1",
  "react-native": "0.71.8",
  "react-native-config": "^1.5.1",
  "react-native-gesture-handler": "^2.10.1",
  "react-native-mmkv": "^2.8.0",
  "react-native-reanimated": "^3.1.0",
  "react-native-screens": "^3.20.0",
  "react-native-svg": "13.9.0",
  "react-native-vector-icons": "^9.2.0"
}
```

**Comment by chasepoirier** [comment]
If anyone still has this issue, you can follow these steps:

- Make sure your `react-native-renanimated` library is on version 2 (could use version 2.13.0)
- Rerun `pod install`
- Update your `babel.config.json` to include the reanimated plugin like so:
```json
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": ["react-native-reanimated/plugin"]
}
```
- Reset cache when starting application, `yarn start --reset-cache` 

This resolved the issue for me.

**Comment by mikescott** [comment]
Came here from Google experiencing the same issue with Expo. I was using a custom development client and creating a new build solved this problem for me with the following environment:

Library | Version
-- | --
expo | 48.0.19
@gorhom/bottom-sheet | 4.4.7
react-native | 0.71.8
react-native-reanimated | 2.14.4
react-native-gesture-handler | 2.9.0

**Comment by VictorPulzz** [comment]
@mikescott Problem with types in old version reanimated: 
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/23406402/d5e239e3-b6fa-483e-ad3d-293cd9f4b5c5)
