### ISSUE TITLE
[v4] Android Crash on New Arch with Pressable

### ISSUE THREAD

**Issue by cospin** [gorhom/react-native-scroll-bottom-sheet#1259]
# Bug

When a [Pressable](https://reactnative.dev/docs/pressable) inside the sheet is pressed, the app crash after the sheet is closed.
It works fine on iOS.

Note: this happens with other things, like inputs etc. not only with Pressable. I think it has to do with animations.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.6   |
| react-native-reanimated         | 3.0.0-rc.9   |
| react-native-gesture-handler    | 2.8.0   |

`newArchEnabled=true
`
## Steps To Reproduce

1. Add Pressable inside a sheet: `<Pressable><Text>Press Me</Text></Pressable>`
2. Open the sheet and press the Pressable
3. Close the sheet
4. Crash

Describe what you expected to happen:

1. Press a Pressable
2. Close the sheet
3. No crash

## Reproducible sample code

Repo: https://github.com/cospin/RNBS-NewArch (new project just for test this)
Specific file with the sheet: https://github.com/cospin/RNBS-NewArch/blob/main/src/ReactMain.tsx

Viedeo:

https://user-images.githubusercontent.com/2880114/211271055-2a3e5615-96e1-4b5b-9ebb-861d4e2fc8ce.mov

https://user-images.githubusercontent.com/2880114/211271116-ba754396-55b7-426d-ad6d-12e8dd49a0c0.mov

Crash Log:
```
/home/user/RN/MyApp/node_modules/react-native/ReactCommon/jsi/jsi/jsi-inl.h:185: std::shared_ptr<T> facebook::jsi::Object::getHostObject(facebook::jsi::Runtime &) const [T = facebook::react::ShadowNodeWrapper]: assertion "isHostObject<T>(runtime)" failed
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28571 (com.myapp), pid 28571 (com.myapp)
```

**Comment by hirbod** [comment]
That looks like an issue with Reanimated. Have you tried upgrading to Reanimated v3 ? (Currently a RC though)

**Comment by cospin** [comment]
@hirbod  yeah, this issue and the repro already has 3.0.0-rc.9, haven't tried anything lower, afaik 2.x doesn't work well on New Arch.

**Comment by hirbod** [comment]
Rea3 changed some internals around useSharedValue etc. I think some changes might be needed in this package, we should monitor, maybe worth a report at REA

**Comment by misaku** [comment]
same problem here, but with react-navigation and buttons of gesture handler =S
