### ISSUE TITLE
[v4] Keyboard opens and closes quickly when pressing Input in Custom Bottom Sheet navigator

### ISSUE THREAD

**Issue by alexandre-eliot** [gorhom/react-native-scroll-bottom-sheet#1260]
# Bug

This bug does not happen all the time.
The bottom sheet is open at ' 50%' of the view port's height, when I click on a Text input, the keyboard slides in, the bottom sheet adapts and moves up. Right away then, the keyboard slides out and the bottom sheet follows.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 45.0.0   |
| react-native                    | 0.65.2   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.2.1   |

## Steps To Reproduce

1. The BottomSheet's index is set to -1
2. Open the BottomSheet at its first snap point being 50% ( the second being 90% ) 
3. Click on a text input

Describe what you expected to happen:

1. The Keyboard and the BottomSheet slide up at once to allow the user to type a text

## Reproducible sample code

The architecture is as follow

```jsx
const BottomSheetContent = ({ style, children }) => {
  const { animatedFooterHeight, animatedContainerHeight, animatedPosition, animatedHandleHeight } =
    useBottomSheetInternal();

  const contentViewAnimatedStyle = useAnimatedStyle(() => {
    const height =
      animatedContainerHeight.value - animatedPosition.value - animatedHandleHeight.value - animatedFooterHeight.value;
    return {
      height: height || 0,
    };
  });

  const containerStyle = useMemo(() => [style, contentViewAnimatedStyle], [style, contentViewAnimatedStyle]);

  return <BottomSheetView style={containerStyle}>{children}</BottomSheetView>;
};
```

```jsx

<>
  <Component/>
  <BottomSheetModalProvider>
    <BottomSheetPanel>
      <BottomSheet>
        <BottomSheetContent>
          <NavigationContent>
            <BottomSheetScrollView>
              {state.routes.map(() => {
                return (
                  <Screen { ... } />
                );
              })}
            </BottomSheetScrollView>
          </NavigationContent>
        </BottomSheetContent>
      </BottomSheet>
    </BottomSheetPanel>
  </BottomSheetModalProvider>
</>

```

Sorry for the lack of details I do not possess the right to provide

**Comment by alexandre-eliot** [comment]
Of course, the architecture I provided is split amongst multiple components but I wrote it in a single tree for simplicity's sake

**Comment by jevkozlovs** [comment]
@alexandre-eliot Hi, were you able to solve this problem?

**Comment by alexandre-eliot** [comment]
I am not sure. Have you tried using a TextInput from another library ?
It's been ages so I don't remember if/how I solved that one, sorry
