### ISSUE TITLE
Not compatible with version reanimated@3.0.0-rc.10

### ISSUE THREAD

**Issue by ugurdalkiran** [gorhom/react-native-scroll-bottom-sheet#1264]
# Feature Request

Proper working with version 3.0.0 of the reanimated library.

## Why it is needed

In order to be up to date and work more efficiently.

## Possible implementation

The dependency file for this package says **"react-native-reanimated": ">=2.2.0"**. I am using the current version **reanimated@3.0.0-rc.10** in my project.

I could not install this package under normal conditions. I tried to force install with the **--force** tag, but I got an error like the one below.

![212874747-0a1cf82b-a01b-4838-8a0a-bd07de39bc79](https://user-images.githubusercontent.com/27302986/212886037-5a617236-6b04-4da0-a0e4-cad87df0a87b.png)

I think it's probably not compatible with the current reanimated version. Will there be any development on this?

### Code sample

npm i @gorhom/bottom-sheet --force

**Comment by siva-444** [comment]
+1
Facing Same problem

**Comment by Gnative** [comment]
reanimated@3.0.0-rc.10 is a release candidate.. not a stable release. 

Using this version you would be doing so knowing that there could be bugs and the code could change quite a bit. It might not even work with this package. To test this version of Reanimated with this package you can also use the "overrides" configuration in your packages.json file. 

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

```
  "overrides": {
    "react-native-reanimated": "^3.0.0-rc.10"
  },
```

For me I found no bugs currently with using react-native-bottom-sheet with reanimated@3.0.0-rc.10 , I don't have fabric enabled thou. I did find some problems with other uses of reanimated 3.0.0. in my app .. just so you are aware.

**Comment by sebastianMagnaldi** [comment]
experiencing this issue with reanimated 3.0.1 and gorhom/react-native-bottom-sheet 4.4.5

**Comment by mununki** [comment]
I can confirm facing the same issue with reanimated 3.0.2 and gorhom/react-native-bottom-sheet 4.4.5

**Comment by RichardLindhout** [comment]
See @gorhom twitter, 5.alpha is available it works with 3!

**Comment by pierroo** [comment]
@RichardLindhout but using that 5.alpha seems rather scary in production;
anyone else implemented 5.alpha in production with reanimated 3?

**Comment by vojto** [comment]
The alpha build works really well, is it going to become a stable release soon?
