### ISSUE TITLE
How to implement sticky section titles?

### ISSUE THREAD

**Issue by MatteoBuffo** [gorhom/react-native-scroll-bottom-sheet#1265]
# Bug

Hello. How do I implement the sticky section titles as seen [here](https://github.com/gorhom/react-native-bottom-sheet/blob/master/preview.gif) (i.e. France, Saint Pierre and Miquelon, French Southern Territories, etc.)? What component should I use and what props should I pass to it?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.68.2  |
| react-native-reanimated         |~2.8.0  |
| react-native-gesture-handler    | ~2.2.1   |

## Steps To Reproduce

1. Not applicable
2.
3. 

Describe what you expected to happen:

1. As reported before
2.

## Reproducible sample code

[Snack](https://snack.expo.dev/@gorhom/bottom-sheet-v4-reproducible-issue-template)

**Comment by wolfzer44** [comment]
You can use `<BottomSheetSectionList />` 
https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetsectionlist/

**Comment by MatteoBuffo** [comment]
@wolfzer44 I copy-pasted the code from your link but noticed that the section titles stick to the top of the BottomSheet only on iOS. Is that an expected behaviour or is there a way to have sticky section titles on Android as well?

**Comment by MatteoBuffo** [comment]
Just for clarification.

Android:

https://user-images.githubusercontent.com/56068232/220064817-16f92334-bd49-41ca-817a-4deae6f600e9.mp4


iOS:

https://user-images.githubusercontent.com/56068232/220064844-a98ef891-7d57-48ef-b38b-11dcc6a8e928.MOV

**Comment by wolfzer44** [comment]
@MatteoBuffo try to add `stickySectionHeadersEnabled` to your `<BottomSheetSectionList />`

**Comment by MatteoBuffo** [comment]
@wolfzer44 it works! I totally missed the part in the docs where that component inherits RN's SectionList props ([here](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetsectionlist#props)).

**Comment by wolfzer44** [comment]
@MatteoBuffo Sweet!
