### ISSUE TITLE
[v4] GestureHandlerRootView prevents swiping using react-native-swiper-flatlist

### ISSUE THREAD

**Issue by jaakola-aleksanteri** [gorhom/react-native-scroll-bottom-sheet#1267]
# Bug

GestureHandlerRootView prevents swiping using  `react-native-swiper-flatlist`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | 0.70.1   |
| react-native-reanimated         | 2.12.0   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

1. Install both libraries and use them the way I used them in the snippet below
2. Swiping doesn't work on Android
3. 

Describe what you expected to happen:

1. Swiping works on Android as it works on iOS
2.

## Reproducible sample code

```
   <GestureHandlerRootView style={{ flex: 1 }}>
      <BottomSheetModalProvider>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />

        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}>
          <View style={styles.container}>
            <SwiperFlatList
              showPagination
              data={colors}
              renderItem={({ item }) => (
                <View style={[styles.child, { backgroundColor: item }]}>
                  <Text style={styles.text}>{item}</Text>
                </View>
              )}
            />
          </View>
        </BottomSheetModal>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
```

**Comment by atiq4112** [comment]
@gorhom  I have also facing same issue I am using BottomSheetScrollView and I am facing this issue in android. In android get stuck other points instead of snap points during dragging

**Comment by R0LLeX** [comment]
still relevant
