### ISSUE TITLE
[v4] Animated.ScrollView is not working inside bottomsheet in Android 

### ISSUE THREAD

**Issue by sarulathadurai** [gorhom/react-native-scroll-bottom-sheet#1268]
# Bug

I need to use `Animated.ScrollView` inside Bottomsheet but it's working fine in ios but not on android

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.68.2   |
| react-native-reanimated         |2.13.0   |
| react-native-gesture-handler    |2.8.0  |

Describe what you expected to happen:

1. I want it to work in android

**Comment by anisurrahman072** [comment]
Did you find any solution of it?
