### ISSUE TITLE
Use fixed header inside BottomSheet with scrollable content

### ISSUE THREAD

**Issue by anis-18** [gorhom/react-native-scroll-bottom-sheet#1283]
# Feature Request

### Code sample

Can i use a fixed header not scrollable on the top with a scrollable view content inside bottom sheet ? 
I've tried this but it's not wotking :

```js
<BottomSheet>
    <BottomSheetView>
          {props.header}
    </BottomSheetView>
    <BottomSheetScrollView>
          {props.content}
     </BottomSheetScrollView>
</BottomSheet>
```

**Comment by ftanzarella-eviivo** [comment]
I've been trying to do the same thing this week.

**Comment by anis-18** [comment]
> I've been trying to do the same thing this week.

I was able to do it, i will post code tomorrow

**Comment by ftanzarella-eviivo** [comment]
@anisamirouche - Can you share your fix for this please? I managed to do it as well by wrapping the BottomSheetScrollView in a View with set height but I then lose the ability to scroll the bottomsheet first before the list start scrolling.

**Comment by theyanniss23002** [comment]
This question is relevant, I also needed a solution to this problem

**Comment by ftanzarella-eviivo** [comment]
I managed to get it mostly working with the following. 
It scrolls with a fixed header when scrolling starts on ScrollView but if user starts scroll on header, it will scroll the sheet. Also the sheet is set to a single snap point and I am using a stack navigator and ScrollView from RNGH. This solution is not ideal but works for me well enough.

```
    const { height: HEIGHT } = Dimensions.get('window');
    const scrollHeight = HEIGHT * 0.9;

    <BottomSheetView style={{ height: scrollHeight, paddingHorizontal: 16 }}>
      <NavigationContainer independent={true}>
        <Stack.Navigator>
          <Stack.Screen />
        </Stack.Navigator>
      </NavigationContainer>
    </BottomSheetView>

    <View>
        <View>
            <HeaderSearchInput onChange={setSearchQuery} value={searchQuery} />
        </View>
        <ScrollView>
            {...}
        </ScrollView>
    </View>

**Comment by Gruzchick** [comment]
What if we place the header inside the handleComponent ?

**Comment by Silon** [comment]
I used View instead of BottomSheetView and it works good

**Comment by yolpsoftware** [comment]
Anyone found a solution for this that also works with v5?

**Comment by csimpi** [comment]
@gorhom  It's impossible to properly setup BottomSheet or BottomSheetModal with a fixed header section.

Solution 1: Add fixed header outside of BottomSheetView
It ruins the calculation of the scrollable area, takes up the space. The bottom of the content will be hidden (impossible to scroll down) with the exact same size as the height of the header.

So if the header is 80 tall, 80 will be hidden below, even if you scroll

Solution 2: Add header template to the handler component
Solves the height issue, BUT if you want to place there a `BottomSheetTextInput` it will be bugged. If you type in one character the keyboard disappears because it loses the focus for some reason

So far I couldn't find the way to solve this.

**Comment by antoniogoulao** [comment]
The solution I got involves measuring the height of the header and pass it to the `contentContainerStyle`, in my case to set the `paddingBottom`. Code below:

```
export const HeaderBottomSheet = forwardRef(
  (
    { onClose, containerStyle }: { onClose: Dispatch<void>; containerStyle?: ViewStyle },
    ref: ForwardedRef<BottomSheetModalMethods>,
  ) => {
    ...
    const [headerHeight, setHeaderHeight] = useState(0);
    ...

    return (
      <BottomSheetModal
        ref={ref}
        ...
      >
        <View style={{ flex: 1 }}>
          {/* Fixed Header */}
          <View
            style={styles.header}
            onLayout={(event) => setHeaderHeight(event.nativeEvent.layout.height)}
          >
            <Text variant="titleMedium">{t('Header title')}</Text>
            <IconButton
              onPress={() => onClose()}
              icon={({ color }) => <Icons name="close" color={color} />}
            />
          </View>

          {/* Scrollable content, offset below header */}
          <BottomSheetScrollView
            style={styles.container}
            contentContainerStyle={[
              styles.contentContainer,
              { paddingBottom: headerHeight },
            ]}
          >
            <View style={styles.block}>
              <Text variant="bodyMedium">...</Text>
            </View>
            {/* Other blocks */}
          </BottomSheetScrollView>
        </View>
      </BottomSheetModal>
    );
  },
);
```

**Comment by petertoth-dev** [comment]
> The solution I got involves measuring the height of the header and pass it to the `contentContainerStyle`, in my case to set the `paddingBottom`. Code below:
> 

Yeah, but, please, don't do that :)

1) Padding bottom is an ugly workaround, not a solution, you already know something is wrong if you have do do these hacks
2)  continuously measuring calculating and updating and re-rendering based on display and content sizes called bad practices. When you do something like that, you already know you are doing something wrong :)

**Comment by agrinko** [comment]
### ✅ Solution

Use `BottomSheetScrollView` with [stickyHeaderIncices](https://reactnative.dev/docs/scrollview#stickyheaderindices) to define content elements that should be "sticky":

```
<BottomSheet ref={bottomSheetRef} enablePanDownToClose onClose={onClose}>
  <BottomSheetScrollView style={styles.container} stickyHeaderIndices={[0]}>
    <View>Your header</View>
    <View>Your content...</View>
  </BottomSheetScrollView>
</BottomSheet>
```

**Comment by akshg05** [comment]
What would be the solution if we have a large list where we need to use a Flat list with a header instead of ScrollView?

**Comment by petertoth-dev** [comment]
@akshg05 

https://gorhom.dev/react-native-bottom-sheet/components/bottomsheetflatlist what you are looking for, plus header with `stickyHeaderIndices={[0]}`

**Comment by akshg05** [comment]
Can you please elaborate on this with an example? I believe I can't use a BottomsheetFlatList inside ScrollView. Stickyheader is a prop of ScrollView. An example would help.
Thanks

**Comment by akshg05** [comment]
I was able to resolve it. I wasn't aware the BottomsheetFlatList had the prop of stickydices as my editor autocomplete didn't show. It's working.
