### ISSUE TITLE
How to detect when bottomsheet was closed with pandown gesture

### ISSUE THREAD

**Issue by anis-18** [gorhom/react-native-scroll-bottom-sheet#1286]
# Feature Request

### Code sample

Is there any possibility to detect when bottomsheet was closed or is there any method to detect when bottomsheet was closed so we can perfrom something or some function at that moment like clear state or something ?

**Comment by mariacheline** [comment]
any news on this?

**Comment by BorislavStefanov31** [comment]
Is there any update?
