### ISSUE TITLE
Flashlist Support

### ISSUE THREAD

**Issue by iway1** [gorhom/react-native-scroll-bottom-sheet#1290]
Feature Request
Would be awesome to support @shopify/flashlist. I tried to set it up using createBottomSheetScrollableComponent but it gets a native code error.

Why it is needed
Flashlist is much more performant than Flatlist. It's pretty much always better to use Flashlist nowadays

## Possible implementation

Could add flashlist as a peer dependency and export `BottomSheetFlatList`

Or could adapt `createBottomSheetScrollableComponent` to work with flashlist

### Code sample

```tsx
import { BottomSheetFlashList } from '@gorhom/bottom-sheet'
```

**Comment by XantreDev** [comment]
Btw flash list without gestures will work in bottom sheet with ScrollView from react-native-gesture-handler
```tsx
import { ScrollView } from 'react-native-gesture-handler';

<FlashList
        estimatedItemSize={64}
        renderScrollComponent={ScrollView}
        ItemSeparatorComponent={Separator}
        data={COUNTRY_CODES}
        keyExtractor={keyExtractor}
        renderItem={itemRenderer}
      />
```

**Comment by LCappell** [comment]
@XantreGodlike Would using a ScrollView within a FlashList get poorer performance and defeat the purpose of using a FlashLIst ?

**Comment by XantreDev** [comment]
> @XantreGodlike Would using a ScrollView within a FlashList get poorer performance and defeat the purpose of using a FlashLIst ? 

I has no performance issues with this case of usage of FlashList. And I think this still faster than FlatList. I my case, I had 200+ items in the list. So flatlist basically would render it with batches, and still will have poor performance. But FlashList handle this case

**Comment by luhahaha** [comment]
@XantreGodlike I tried this solution and it works, but my problem is that the FlashList is also inside a horizontal ScrollView, using your solution is not scrolling anymore horizontally, do you know a solution, or why this is happening?

> Btw flash list without gestures will work in bottom sheet with ScrollView from react-native-gesture-handler
> 
> ```tsx
> import { ScrollView } from 'react-native-gesture-handler';
> 
> <FlashList
>         estimatedItemSize={64}
>         renderScrollComponent={ScrollView}
>         ItemSeparatorComponent={Separator}
>         data={COUNTRY_CODES}
>         keyExtractor={keyExtractor}
>         renderItem={itemRenderer}
>       />
> ```

**Comment by XantreDev** [comment]
> @XantreGodlike I tried this solution and it works, but my problem is that the FlashList is also inside a horizontal ScrollView, using your solution is not scrolling anymore horizontally, do you know a solution, or why this is happening?
> 
> > Btw flash list without gestures will work in bottom sheet with ScrollView from react-native-gesture-handler
> > 
> > ```tsx
> > import { ScrollView } from 'react-native-gesture-handler';
> > 
> > <FlashList
> >         estimatedItemSize={64}
> >         renderScrollComponent={ScrollView}
> >         ItemSeparatorComponent={Separator}
> >         data={COUNTRY_CODES}
> >         keyExtractor={keyExtractor}
> >         renderItem={itemRenderer}
> >       />
> > ```
> 
> 

I don't know(

**Comment by younes0** [comment]
@gorhom what do you think about @XantreGodlike implementation ?

**Comment by XantreDev** [comment]
I think we can create separate entry for flash list
`@gorhom/react-native-bottom-sheet/flash-list`
And specify flash list as peer dependency.
But I think there should be better implementation

**Comment by gorhom** [comment]
Flash list is a third party library that I would not integrate in this package. I would recommend having your integration as an extension instead just like I did for sponsors.

**Comment by XantreDev** [comment]
Why we we cannot create separate entry for this goal? And use flash list as optional peer dependency?

**Comment by pheonix5** [comment]
> Btw flash list without gestures will work in bottom sheet with ScrollView from react-native-gesture-handler
> 
> import { ScrollView } from 'react-native-gesture-handler';
> 
> <FlashList
>         estimatedItemSize={64}
>         renderScrollComponent={ScrollView}
>         ItemSeparatorComponent={Separator}
>         data={COUNTRY_CODES}
>         keyExtractor={keyExtractor}
>         renderItem={itemRenderer}
>       />

Muito obrigado, eu estava passando pro esse problema há dias, ate que essa dica funcionou perfeitamente!
