### ISSUE TITLE
Close bottomsheet before leaving screen

### ISSUE THREAD

**Issue by anis-18** [gorhom/react-native-scroll-bottom-sheet#1295]
# Feature Request

Can we close bottomsheet before leaving screen, I mean close it with any animation when user is back to that screen he will find the bottom sheet closed, as we know in react native leaving screen and coming back doesn't reset the state of the screen. 
## Why it is needed
Sometimes user leaves the screen and when he is back he will find the bottom sheet open, it's more appropriate if he finds it closed. 

## Possible implementation
I tried to do it with useFocusEffect before leaving the screen but when user clicks on another tab first he sees the bottom sheet closing with animation and then he it changes screen, is there any solution to close the bottom sheet without any animation under the ground I mean and when user comes back he finds it closed, we can use blur option in tab navigator and force the whole screen to reset and reload when leaving but it will be more performant to close only the bottom sheet

**Comment by hirbod** [comment]
Are you using `enableFreeze` by RNS? Because what you try should be possible without freezing.

**Comment by anis-18** [comment]
> Are you using `enableFreeze` by RNS? Because what you try should be possible without freezing.

No I'm not using enableFreeze, can you post a record video to see the behavior , if it's working with you

**Comment by RohovDmytro** [comment]
My solution: listen to a change event from react-navigation to trigger bottom sheet close method.
