### ISSUE TITLE
[v4] Opening keyboard extends to max snap point

### ISSUE THREAD

**Issue by andrejguran** [gorhom/react-native-scroll-bottom-sheet#1299]
# Bug

Opening keyboard extends to max snap point
If this is an expected behaviour is there a workaround how to keep the current snap point when opening a keyboard?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.69.4   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

In Example App -> Advanced -> Keyboard handling
When bottomsheet is in minimal snap point (index: 0)
And I click on text input
Then bottomsheet snaps to maximum snap point (index: 1)
It snaps to max snap point regardless of the keyboard behaviours selected.

Describe what you expected to happen:

Bottomsheet keeps it's snap point

## Reproducible sample code

master branch at #[54abf0c](https://github.com/gorhom/react-native-bottom-sheet/commit/54abf0c0832d1451dfe11be212fc5f938ff5c5fd)
run in expo

**Comment by callaars** [comment]
There is currently no way of returning it back to the original state either unless the keyboard loses focus.

**Comment by MuriloCalegari** [comment]
Getting the same issue here... Did anyone find a solution?

**Comment by mia-lorraine** [comment]
Adding the prop `enablePanDownToClose` worked for me.

**Comment by JJSLIoT** [comment]
This issue needs to be re-opened, I am facing the same issue. The bottom sheet should not extend beyond the maximum snap-point or at least take into account the safe area.

Screenshot showing the bottomsheet goes beyond the maximum snap-point and under the iPhone notch:
![Simulator Screenshot - iPhone 14 Pro - 2023-06-15 at 18 08 17](https://github.com/gorhom/react-native-bottom-sheet/assets/53684569/f69475f3-ae27-4051-b7cf-3bca2869a7a4)

**Comment by vaibhav19121** [comment]
this is causing because of keyboard behaviour acting differently whenever the textinput is focused you can achieve your problems solution using this given prop ` keyboardBehavior="extend"` in bottomsheetModal Component.

thanks me later
