### ISSUE TITLE
[v4] Set index={-1} blocks entire view at certain devices, eg. Xiaomi, Samsung

### ISSUE THREAD

**Issue by CoSNaYe** [gorhom/react-native-scroll-bottom-sheet#1301]
# Bug

This issue is a reopen for https://github.com/gorhom/react-native-bottom-sheet/issues/807 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.67.4   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

The same of the original issue.
Just adding the prop `index={-1}` can reproduce the issue at certain devices.
Known affected devices: [OnePlus 5](https://www.oneplus.in/support/spec/oneplus-5), Samsung Galaxy S8+, Xiaomi S10

## Other information

A work-around is to set the first snap point to a very small number (e.g. 1) as mentioned [here](https://github.com/gorhom/react-native-bottom-sheet/issues/807#issuecomment-1427371098)

**Comment by RohovDmytro** [comment]
Sad it's closed. Any chance to revive it? @gorhom
