### ISSUE TITLE
[v4] Set index={-1} blocks entire view at certain devices, eg. Xiaomi, Samsung (re-open)

### ISSUE THREAD

**Issue by CoSNaYe** [gorhom/react-native-scroll-bottom-sheet#1302]
# Bug

This issue is a reopen for https://github.com/gorhom/react-native-bottom-sheet/issues/807 

A work-around is to set the first snap point to a very small number (e.g. 1) as mentioned [here](https://github.com/gorhom/react-native-bottom-sheet/issues/807#issuecomment-1427371098)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.67.4   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. The same of the [original issue](https://github.com/gorhom/react-native-bottom-sheet/issues/807).
2. Use a Xiaomi device
3. Set `index={-1}`, then the entire screen is blocked.

Describe what you expected to happen:

1. Do not block the entire screen. 

## Reproducible sample code

(copy from the original issue)

```
import React, { useCallback } from 'react';
import { StyleSheet, Keyboard } from 'react-native';
import PropTypes from 'prop-types';
import { bottomSheetHeaderHandler } from 'colors';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

const renderBackdrop = props => (
  <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
);

const BottomSheet = React.forwardRef((props, ref) => {
  const { children, onChange, ...restProps } = props;

  const handleChange = useCallback(index => {
    if (index === -1) {
      // When the BottomSheet is closed, dismiss any open Keyboard
      Keyboard.dismiss();
    }
    // Call the actual onChange handler passing in the index
    onChange?.(index);
  }, []);

  return (
    <BottomSheetGorhom
      index={-1}
      enablePanDownToClose
      backdropComponent={renderBackdrop}
      handleIndicatorStyle={styles.handleIndicatorStyle}
      ref={ref}
      onChange={handleChange}
      {...restProps}
    >
      {children}
    </BottomSheetGorhom>
  );
});

const styles = StyleSheet.create({
  handleIndicatorStyle: {
    width: wp('12.6%'),
    height: hp('0.65%'),
    borderRadius: 4,
    backgroundColor: bottomSheetHeaderHandler,
  },
});

BottomSheet.propTypes = {
  children: PropTypes.node,
  onChange: PropTypes.func,
};

export default BottomSheet;
```

**Comment by RohovDmytro** [comment]
Ohmy. This might explain a lot a bug I'm hunting for AGES. Some users tend to clear the device cache after visiting screens with bottom sheet. Could never debug that.

Thank you @CoSNaYe for re-opening and bringing light to the issue.
