### ISSUE TITLE
The current version of bottom sheet seems to work fine with the latest version of Reanimated (3), is there any reason not to upgrade to 3?

### ISSUE THREAD

**Issue by TowhidKashem** [gorhom/react-native-scroll-bottom-sheet#1315]
Should I stay at reanimated 2 or update to reanimated 3? I would like to take advantage of the new shared transitions feature in R3 but don't want to cause any issues with this library. I upgraded just to test and it seems to be working just fine but then I also saw a tweet by @gorhom who said that he's working on a new version of Bottom Sheet to support reanimated 3. So was wondering what the deal was there...

**Comment by meabed** [comment]
Yes - it crash on reanimated 3

**Comment by malikzype** [comment]
We are facing a similar issue with Backdrop on Android using reanimated v3.0.2. Any help? @TowhidKashem Can you confirm if backdrop component works well at your end on Android with reanimated v3?

**Comment by TowhidKashem** [comment]
> We are facing a similar issue with Backdrop on Android using reanimated v3.0.2. Any help? @TowhidKashem Can you confirm if backdrop component works well at your end on Android with reanimated v3? 
> 
> 

I only use iOS and form what I remember backdrop was working fine when I was on RN 3.

Closing the issue since the author has a alpha version out for working with RN 3.

**Comment by malikzype** [comment]
@TowhidKashem We tried working with the alpha version rolled out by the author. However it's still not working for us. When we comment the backdrop, everything works fine.
