### ISSUE TITLE
[v4] BottomSheetScrollView overflow: hiddent property not working on android on BottomSheet with no handle component

### ISSUE THREAD

**Issue by Miigaarino** [gorhom/react-native-scroll-bottom-sheet#1316]
# Bug

Not scrolled: 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/48021917/223367478-ea9e4cee-2063-47a4-9317-a223c9262248.png">

Started scrolling:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/48021917/223367584-2270bfc4-e60c-4b92-bb38-7fde6faf6c84.png">

BottomSheetScrollView styles: 
```
    overflow: 'hidden',
    borderTopLeftRadius: bottomSheetBorderRadius,
    borderTopRightRadius: bottomSheetBorderRadius,
```
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.71.3   |
| react-native-reanimated         | ^3.0.1   |
| react-native-gesture-handler    | ^2.9.0   |

## Steps To Reproduce

1. add ```handleComponent={null}``` prop to BottomSheetModal
2. add ```overflow: "hidden"``` style to BottomSheetScrollView component
3. Fill the BottomSheetScrollView with contents so that u can start scrolling
4. Start scrolling

**Comment by bryanprimus** [comment]
any update on this ?

**Comment by informsharique** [comment]
I'm also facing the same issue. Also, on some devices it just shows only backdrop and shows nothing from the UI
