### ISSUE TITLE
[v4] | BottomSheetScrollView only scrollable at highest snappoint

### ISSUE THREAD

**Issue by f1sh1918** [gorhom/react-native-scroll-bottom-sheet#1321]
# Bug

I'm using the bottom sheet with 3 snapPoints `[40, '35%', '100%']`
Initial the second snapPoint (35%) is opened and i can not scroll inside the scroll view. Instead i have to snap to the highest snapPoint which in my case is 100% to be able to scroll. I'm using `<BottomSheetScrollView>` inside my `<BottomActionSheet>`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.2   |
| react-native                    | 0.70.6   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. Drag Bottom sheet to second snappoint
2. try to scroll
3. bottom sheet is dragging to next snapPoint

Describe what you expected to happen:

1. Drag Bottom sheet to second snappoint
2. Try to scroll in the BottomSheetScrollView and works

## Reproducible sample code

```js
const snapPoints = [40, '35%', '100%']

 <BottomSheet
        snapPoints={snapPoints}
        animateOnMount
        >
        <BottomSheetScrollView ref={scrollRef}>
          {children}
        </BottomSheetScrollView>
      </BottomSheet>
```

**Comment by alan-la-chen-478** [comment]
I have the same question too.

```
<BottomSheetModal
  ref={ref}
  snapPoints={['20%', '80%']}
  backdropComponent={dropProps => <BottomSheetBackdrop {...dropProps} appearsOnIndex={0} disappearsOnIndex={-1} />}
>
  <BottomSheetScrollView>
    <Text>i'm at top</Text>
    <View style={{height: 800, backgroundColor: 'red'}} />
    <Text>i'm at bottom</Text>
  </BottomSheetScrollView>
</BottomSheetModal>
```

is this intentional to be not scroll-able unless fully expanded?

Is there a way to still make the first height scroll-able?

**Comment by lmeier** [comment]
I'm pretty sure this is expected behavior -- it makes for the clean "drag up until you can't any more, then scroll" behavior.

I bet using a regular scroll view instead of a bottomsheet scroll view would give you your desired behavior.

**Comment by f1sh1918** [comment]
> I'm pretty sure this is expected behavior -- it makes for the clean "drag up until you can't any more, then scroll" behavior.
> 
> I bet using a regular scroll view instead of a bottomsheet scroll view would give you your desired behavior.

If you use a simple `<ScrollView>` instead you can not scroll inside the `<BottomActionSheet>`
