### ISSUE TITLE
Not able to scroll inside BottomSheetModal using BottomSheetScrollView in Android

### ISSUE THREAD

**Issue by suman-kr** [gorhom/react-native-scroll-bottom-sheet#1323]
# Bug
 Not able to scroll inside `BottomSheetModal` using `BottomSheetScrollView` in Android. Tried the steps present in this link: https://gorhom.github.io/react-native-bottom-sheet/troubleshooting.  

Went through all the issues present inside the repo. Didn't find any solution

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4 |
| react-native                    |^0.71.1   |
| react-native-reanimated         | ^2.14.4   |
| react-native-gesture-handler    | ^2.8.0  |

## Steps To Reproduce

1. Try running the sample code in Android Emulator.
2. Set open prop to `true`
3. When Modal opens, try scrolling the content inside. Scroll does not work

Describe what you expected to happen:

1. Expected to scroll the content inside the Modal

## Reproducible sample code
```tsx
import React, { useCallback, useEffect, useMemo, useRef } from 'react';
import { Dimensions } from 'react-native';

import { BlurView } from '@react-native-community/blur';

import {
  type BottomSheetBackdropProps,
  BottomSheetModal,
  BottomSheetScrollView,
  useBottomSheetDynamicSnapPoints,
} from '@gorhom/bottom-sheet';

interface BottomSheetProps {
  open: boolean;
  onDismiss: () => void;
  children: JSX.Element | JSX.Element[];
}

const NINETY_PERCENT_SCREEN_HEIGHT = 0.9;

export const BottomSheet: React.FC<BottomSheetProps> = (
  props: BottomSheetProps,
) => {
  const { open: isOpen = false, onDismiss, children } = props;
  useEffect(() => {
    toggleModal();
  }, [isOpen]);
  const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], []);
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const toggleModal = useCallback(() => {
    if (isOpen) {
      bottomSheetModalRef.current?.present();
    } else {
      bottomSheetModalRef.current?.dismiss();
    }
  }, [isOpen]);
  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints);

  const renderBackDrop = useCallback(
    (props: BottomSheetBackdropProps) => {
      return <BlurView onTouchEnd={onDismiss} {...props} />;
    },
    [onDismiss],
  );

  const maxHeight = useMemo(
    () => ({
      maxHeight: Dimensions.get('window').height * NINETY_PERCENT_SCREEN_HEIGHT,
    }),
    [],
  );

  return (
    <>
      <BottomSheetModal
        ref={bottomSheetModalRef}
        onDismiss={onDismiss}
        keyboardBehavior='fillParent'
        snapPoints={animatedSnapPoints}
        handleHeight={animatedHandleHeight}
        contentHeight={animatedContentHeight}
        enablePanDownToClose={true}
        backdropComponent={renderBackDrop}
      >
        <BottomSheetScrollView onLayout={handleContentLayout} style={maxHeight}>
          {children}
        </BottomSheetScrollView>
      </BottomSheetModal>
    </>
  );
};
```

**Comment by fab-nikhil** [comment]
try setting `enableContentPanningGesture={false}` for bottom sheet modal

**Comment by naytun** [comment]
It's not fixed for me. The bug is still there

**Comment by naytun** [comment]
I found the solution:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
return (
  <GestureHandlerRootView>
   ... your component here
  </GestureHandlerRootView>
)
```

**Comment by Haider-Ali-7** [comment]
```
import {GestureHandlerRootView} from 'react-native-gesture-handler';
...
return (
     <GestureHandlerRootView style={{flex: 1}}>
       <BottomSheetModalProvider>
         <BottomSheetModal
           enableContentPanningGesture={false}>
           {children}
         </BottomSheetModal>
       </BottomSheetModalProvider>
     </GestureHandlerRootView>
)
```

**Comment by topurayhan007** [comment]
> ```
> import {GestureHandlerRootView} from 'react-native-gesture-handler';
> ...
> return (
>      <GestureHandlerRootView style={{flex: 1}}>
>        <BottomSheetModalProvider>
>          <BottomSheetModal
>            enableContentPanningGesture={false}>
>            {children}
>          </BottomSheetModal>
>        </BottomSheetModalProvider>
>      </GestureHandlerRootView>
> )
> ```

If I use this `enableContentPanningGesture={false}>` I can't use the dynamic snapPoints. Is there any solution for that? I need to use ScrollView inside the BottomSheetModal with dynamic snapPoints.

**Comment by topurayhan007** [comment]
What I did was used BottomSheetFlatList inside BottomSheet:
`App.js`
```
<GestureHandlerRootView style={{flex: 1}}>
       <BottomSheetModalProvider>
         . . .
       </BottomSheetModalProvider>
  </GestureHandlerRootView>
```

`BottomSheet.jsx`

```
import BottomSheet, { BottomSheetFlatList } from "@gorhom/bottom-sheet";

const bottomSheetModalRef = useRef(null);
const snapPoints = useMemo(() => ["35%", "80%"], []);

const handleSheetChange = useCallback((index) => {
    console.log("handleSheetChange", index);
}, []);

const handlePresentModalPress = useCallback((index, productId) => {
    const selectedProduct = products.find((prod) => prod._id === productId);
    bottomSheetModalRef.current?.snapToIndex(index);
    setProduct(selectedProduct);
  }, []);

  return (
    <View style={tw`flex-1 justify-center bg-[${COLORS.white}] relative`}>
      . . .
     <BottomSheet
          ref={bottomSheetModalRef}
          index={-1}
          snapPoints={snapPoints}
          enablePanDownToClose={true}
          onChange={handleSheetChange}
          backgroundStyle={tw`bg-[${COLORS.dark}]`}
          handleIndicatorStyle={{
            backgroundColor: COLORS.primary,
            width: "15%",
          }}
        >
          <View style={[tw`flex-1 h-full w-full`, {}]}>
               . . .
              <View style={[tw`flex-1 rounded-lg overflow-hidden`, {}]}>
                  <BottomSheetFlatList
                    data={product.reviews}
                    keyExtractor={(item, index) => index.toString()}
                    renderItem={({ item }) => <ReviewCard review={item} />}
                    showsVerticalScrollIndicator={false}
                    contentContainerStyle={[tw`py-2 rounded-lg`, {}]}
                  />
            </View>
      </View>
   </BottomSheet>  
</View>)
```

**Comment by youcefswoo** [comment]
any solution ? same case in android

**Comment by John-CFO** [comment]
> any solution ? same case in android

You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.

`import {
  ScrollView,
  FlatList
} from 'react-native-gesture-handler';`

**Comment by yktmd** [comment]
> > any solution ? same case in android
> 
> You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`

worked well for me. Thanks!!

**Comment by zjkuang** [comment]
> > any solution ? same case in android
> 
> You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`

Worked like a charm! This is worth a thousand hearts and thumb-ups! Thank you!

**Comment by AnhTP-Corize** [comment]
> > > any solution ? same case in android
> > 
> > 
> > You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.
> > `import { ScrollView, FlatList } from 'react-native-gesture-handler';`
> 
> worked well for me. Thanks!!

You save my time. Thanks

> > any solution ? same case in android
> 
> You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`

LGTM. Thanks a lot!

**Comment by sujan-york-ie** [comment]
For normal Flatlist or ScrollView we can import from react-native-gesture-handler, but for Animated.Flatlist won't work in bottom-sheet-modal.

**Comment by ravindraguptacapgemini** [comment]
If we import ScrollView from react-native-gesture-handler, then content panning do not work. So it's equivalent to import ScrollView from react-native and setting false for enableContentPanningGesture

**Comment by Ibeenoch** [comment]
> > any solution ? same case in android
> 
> You need to use ScrollView or Flatlist from React-Native-Gesture-Handler. React Native's ScrollView and Flatlist don't work in Gorhom-Bottom Sheet Modal when using Android Studio.
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`

thanks this solved it on expo
