### ISSUE TITLE
[v4] On Input focus Modal goes behind keyboard on iOS and Android

### ISSUE THREAD

**Issue by beqramo** [gorhom/react-native-scroll-bottom-sheet#1328]
# Bug

Hi,
I have a screen where by default modal is opened on screen open/focus I'm triggering Textinput Focus, and sometimes modal goes behind the keyboard like it is shown below. I tried time out on input focus, and it helped but not fully, sometimes it is still happening. From what we saw it is only happening on ios. 

<img src="https://user-images.githubusercontent.com/40486471/226919915-49d018f5-54b1-4dd2-af5b-3d191eee647a.gif" width="200" height="400" />

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.68   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.9.0  |

## Steps To Reproduce

1. add Input in the Modal
2. Trigger Input focus it on screen focus
3. Sometimes you may see that modal goes behind the keyboard.

Describe what you expected to happen:

1.
2.

## Reproducible sample code

I simplified the component for this example.

```tsx
const Modal = () =>{
 const ref = useRef(null);
  const sheetRef = useRef(null);

  useEffect(() => {
    setTimeout(() => {
      ref.current?.focus();
    }, 800);
  }, []);


 const renderBackdrop = useCallback(
    (props) => (
      <BottomSheetBackdrop
        {...props}
        disappearsOnIndex={-1}
        appearsOnIndex={1}
        pressBehavior={ 'none'}
        enableTouchThrough={false}
      />
    ),
    [],
  );
  
return  (
  <BottomSheet
      ref={sheetRef}
      snapPoints={[250]}
      enablePanDownToClose={false}
      backdropComponent={renderBackdrop}
      enableContentPanningGesture={false}
      backgroundStyle={{ flex: 1 }}
      style={{
        borderRadius: 24,
      }}
      keyboardBehavior={undefined} // I have tried all other options too but still not stable
      keyboardBlurBehavior="none"
      android_keyboardInputMode="adjustPan"
      handleComponent={null}
      handleHeight={0}
      bottomInset={0}
    >
      <View>
         <BottomSheetTextInput 
           placeholder={'Enter Amount'}
            keyboardType={'decimal-pad'}
            value={value}
            onFocus={onFocusLocal}
            onBlur={onBlurLocal}
            ref={ref}
         />
      </View>
    </BottomSheet>
   )
}
```

Thank you!

**Comment by huytdps13400** [comment]
Close Modal Keyboard not hide 
Thanks 

https://user-images.githubusercontent.com/68500260/229972297-1809cd5d-7805-4e98-8405-bb706ddfb20d.mp4

**Comment by isaacbatst** [comment]
Got same problem here! When I start to type, modal goes back to first position, behind keyboard. Only on IOS.

**Comment by huytdps13400** [comment]
> Got same problem here! When I start to type, modal goes back to first position, behind keyboard. Only on IOS.

If you have any solution, please help me Thanks

**Comment by beqramo** [comment]
Up.

**Comment by huytdps13400** [comment]
Thanks so much

**Comment by vishwasrvalke** [comment]
Help please

**Comment by AgnieszkaUzarek** [comment]
I have the same issue when validation of input fails

**Comment by beqramo** [comment]
Still facing this issue in prod

**Comment by beqramo** [comment]
I saw this same issue on android too:

https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/d407cd0f-8622-42aa-8612-57700a864ff3

**Comment by brentforder** [comment]
@gorhom 
#1420 hasn't fixed this issue for me. The iOS virtual keyboard is still covering up my inputs on focus in 5.0.0-alpha.11

**Comment by brentforder** [comment]
> @gorhom #1420 hasn't fixed this issue for me. The iOS virtual keyboard is still covering up my inputs on focus in 5.0.0-alpha.11

Update: False alarm., sorry. It's working now that I switched from React Native Paper's TextInput to BottomSheetTextInput. To take control of this virtual keyboard behavior seems to require BottomSheetTextInput.
