### ISSUE TITLE
[v4] Scroll does not work with dynamic snapPoints

### ISSUE THREAD

**Issue by g-todorov** [gorhom/react-native-scroll-bottom-sheet#1330]
# Bug
Hi, I'm not able to scroll when using the `useBottomSheetDynamicSnapPoints` hook.

![Simulator Screen Recording - iPhone 11 - 2023-03-24 at 17 45 01](https://user-images.githubusercontent.com/1577764/227575626-ec80c98c-e3c2-457e-9612-b91274c1dddc.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.71.4  |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. Added `BottomSheet` component.
2. Passed `BottomSheetScrollView` as a child.
3. Set `useBottomSheetDynamicSnapPoints` as described in the documentation.
4. When opened, the content is not scrollable.

Describe what you expected to happen:

1. The `BottomSheetScrollView` content should be scrollable.

## Reproducible sample code

```javascript
  const sheetRef = useRef<BottomSheet>(null);

  // variables
  const data = useMemo(
    () =>
      Array(50)
        .fill(0)
        .map((_, index) => `index-${index}`),
    [],
  );

  const snapPoints = useMemo(() => ["CONTENT_HEIGHT"], []);

  // callbacks
  const handleSheetChange = useCallback((index: any) => {
    console.log("handleSheetChange", index);
  }, []);
  const handleSnapPress = useCallback((index: any) => {
    sheetRef.current?.snapToIndex(index);
  }, []);
  const handleClosePress = useCallback(() => {
    sheetRef.current?.close();
  }, []);

  // render
  const renderItem = useCallback(
    (item: any) => (
      <View key={item} style={styles.itemContainer}>
        <Text>{item}</Text>
      </View>
    ),
    [],
  );

  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(snapPoints);

  return (
    <View style={{ flex: 1 }}>
      <Button onPress={() => handleSnapPress(0)}>Open</Button>
      <Button onPress={() => handleClosePress()}>Close</Button>
      <BottomSheet
        ref={sheetRef}
        index={-1}
        onChange={handleSheetChange}
        snapPoints={animatedSnapPoints}
        handleHeight={animatedHandleHeight}
        contentHeight={animatedContentHeight}>
        <BottomSheetScrollView onLayout={handleContentLayout}>
          {data.map(renderItem)}
        </BottomSheetScrollView>
      </BottomSheet>
    </View>
  );
```

**Comment by bryanprimus** [comment]
maybe related https://github.com/gorhom/react-native-bottom-sheet/issues/658

**Comment by g-todorov** [comment]
@bryanltobing Thanks, definitely related. Unfortunately, the proposed workarounds weren't satisfactory for my case.

**Comment by ororsatti** [comment]
https://github.com/gorhom/react-native-bottom-sheet/discussions/1363
Need your help to push this so we can add this to the lib.
