### ISSUE TITLE
[v4] Android handle and sheet not movable by gesture

### ISSUE THREAD

**Issue by michaek** [gorhom/react-native-scroll-bottom-sheet#1334]
# Bug

Bottom sheet does not respond to any user interaction to change size in Android.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.5   |
| react-native-reanimated         | 2.12.0   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

1. Create a bottom sheet with multiple snapPoints or enablePanDownToClose
2. Try to change the size of the bottom sheet by swiping the handle or the sheet content
3. Notice that it works in iOS, but gestures have no effect on Android (testing with 13)

Describe what you expected to happen:

1. Android should respond to the same gesture interaction as iOS

## Reproducible sample code

https://snack.expo.dev/@alpinemedia/basic-bottomsheet-example

(As a note, bottom-sheet-v4-reproducible-issue-template is broken on Snack. [This template](https://snack.expo.dev/@amanhimself/reanimated-bottom-sheet-polyfills-workaround) served as a working starting point to reproduce the issue.)

**Comment by brushton-ces** [comment]
This fixed it for me https://github.com/gorhom/react-native-bottom-sheet/issues/1297#issuecomment-1492863586

**Comment by michaek** [comment]
I can confirm that wrapping in a properly-styled GestureHandlerRootView addresses this issue, but I think it should be considered a workaround rather than a fix, since the library shouldn't require this kind of "mysterious" intervention in userland to function.

**Comment by lklima** [comment]
for anyone who is using `BottomSheetModal` instead of `BottomSheet` , you have to wrap `BottomSheetModalProvider` with `GestureHandlerRootView`

```javascript
<GestureHandlerRootView style={styles.container}>
  <BottomSheetModalProvider>
    <BottomSheetModal ref={modalRef} index={0} snapPoints={snapPoints}>
      <Text>Awesome 🎉</Text>
    </BottomSheetModal>
  </BottomSheetModalProvider>
</GestureHandlerRootView>
```
