### ISSUE TITLE
[v4] Android: Not passing gesture events down to child component

### ISSUE THREAD

**Issue by archcorsair** [gorhom/react-native-scroll-bottom-sheet#1337]
# Bug

I have a `<ScrollView>` component as a child of the `<BottomSheet>` component.

On android gestures do not appear to be passed down to the child scrollview

- Works flawlessly on iOS
- Does not work on android - some pointers events are coming through (like tap/press), but cannot scroll/swipe to interact with the scrollview on android
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.69.8  |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce
Embed a scrollview as a direct child of the bottom sheet.
Observe scrolling working on iOS
Observe scrolling not working on Android

Describe what you expected to happen:

1. Gestures should pass down to child component for both platforms

## Reproducible sample code
Template appears to be broken cannot provide a snack: https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by naytun** [comment]
I found the solution:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
return (
  <GestureHandlerRootView>
   ... your component here
  </GestureHandlerRootView>
)
```

**Comment by simonkarmy** [comment]
Hi @naytun I am stuck on the same issue, can you show me an example how you managed to use the `GestureHandlerRootView`

**Comment by naytun** [comment]
@simonkarmy Here's my actual code sample:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
export const ImagePreviewModal: FC<ImagePreviewProps> = () => {
   ...
   return (
      <Modal animationType='fade' transparent visible>
         <GestureHandlerRootView style={{ flex: 1 }}>
            <Gallery
               data={imageUrls?.map(image => image?.url)}
               initialIndex={index}
               renderItem={item => renderItem(item)}
            />

            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
               <Image
                  source={require('assets/images/delete-icon.png')}
                  style={{ width: 35, height: 35 }}
               />
            </TouchableOpacity>
         </GestureHandlerRootView>
      </Modal>
   )
}
```

And I use the component like this...
```
           <KeyboardAvoidingView>
               <TouchableWithoutFeedback>
                   <View>
                        ....
                        <ImagePreviewModal
                           imageUrls={attachedImages}
                           index={selectedIndex}
                           onClose={handleClose}
                        />
                  </View>
               </TouchableWithoutFeedback>
            </KeyboardAvoidingView>
```

**Comment by ravindraguptacapgemini** [comment]
GestureHandlerRootView does not help in fixing the issue
