### ISSUE TITLE
[v4] TextInput multiline on scroll input's content it closes bottomsheet

### ISSUE THREAD

**Issue by romancxx** [gorhom/react-native-scroll-bottom-sheet#1341]
# Bug

I am using the `BottomSheetTextInput` with `multiline`, On Android when the text is long enough to require scrolls, scrolling inside the input will also slide the bottom sheet.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.71.6  |
| react-native-reanimated         | ~2.14.4  |
| react-native-gesture-handler    | ~2.9.0   |

## Steps To Reproduce

1. Add a `BottomSheetTextInput` with multiline in a bottom sheet, add a max-height style of 100px
2. Write enough texts so that it can be scrolled
3. Start scrolling the input, the scroll will also be applied on the bottom sheet as if you were sliding it down or up. 

Describe what you expected to happen:

1. The bottom sheet should not move when scrolling inside the input

## Reproducible sample code
Create BottomSheet, use BottomSheetFooter with BottomSheetTextInput multiline
```
import React, { useCallback, useMemo, useRef ,useState} from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet, { BottomSheetFooter,BottomSheetTextInput } from '@gorhom/bottom-sheet';

const App = () => {

// State
const [text,setText] = useState("");

 // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  const renderFooter = useCallback(
    props => (
      <BottomSheetFooter {...props} bottomInset={24}>
        <BottomSheetTextInput multiline onChange={setText} value={text} style={{maxHeight:100, flex:1}} />
      </BottomSheetFooter>
    ),
    []
  );

return (
    <View style={{flex:1}}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        footerComponent={renderFooter}
      >
        <View style={{flex:1}}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
}
```

**Comment by JulienNoel** [comment]
having same issue here, did you find any solution ?

**Comment by Roshdy** [comment]
+1

**Comment by Aycom366** [comment]
++++++1
@gorhom

**Comment by ahmadadejumo** [comment]
> ++++++1 @gorhom

Lol i also came in here to complain @Aycom366 😂

**Comment by Aycom366** [comment]
adding  `enableContentPanningGesture={false}` should make the textinput scroll

**Comment by L-Weisz** [comment]
Hello, we also have this issue `enableContentPanningGesture={false}  ` does work however it prevents the modal to be closed with a scroll down. 
Is there any way to have both of those behaviours ?
