### ISSUE TITLE
[v4] | [v2] backdrop not working in BottomSheetModal 

### ISSUE THREAD

**Issue by hamza5746** [gorhom/react-native-scroll-bottom-sheet#1348]
# Bug
BottomSheetModal
BackdropComponent is not working in Bottomsheet Modal
 
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.67.3  |
| react-native-reanimated         | ^2.4.1   |
| react-native-gesture-handler    | 2.1.1   |

## Steps To Reproduce

1. Provide a BottomSheetBackdrop in the property "backdropComponent"
2. Just open a bottom sheet modal with bottomsheetRef.current.present() 
3.  Not working when we add any style to backdropComponent like background color set to red

Describe what you expected to happen:

1. When we add any style to backdropComponent like background color set to red it should apply.

## Reproducible sample code
`
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet, Button } from 'react-native';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop style={{backgroundColor: 'red'}} {...props} />
    ),
    []
  )
  
  // renders
  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
          backdropComponent={renderBackdrop}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;`

**Comment by hamza5746** [comment]
This isssue already has been made

**Comment by pencilcheck** [comment]
I'm on [Release 4.4.6] and I just can't see the backdrop in BottomSheetModal

Just tried [Release 5.0.0-alpha.1] still doesn't work. @hamza5746 do you mean it is still in branch but not in release yet?

Looks like the custom backdrop didn't work for me (the one provided in the website documentation but the code seen in this thread worked for me:
https://github.com/gorhom/react-native-bottom-sheet/issues/968

**Comment by Roka20012** [comment]
@pencilcheck I am on 4.4.7 and got the same issue when I wanted to change the `backgroundColor` of the `BottomSheetBackdrop` component provided by the library, it seems like the `BottomSheetBackdrop` component is still there but now it renders under the `BottomSheet` itself

Have you managed to fix that or is this issue already fixed somewhere?
