### ISSUE TITLE
[v5] Can't drag bottom sheet on web

### ISSUE THREAD

**Issue by mateoguzmana** [gorhom/react-native-scroll-bottom-sheet#1355]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.0   |
| react-native                    | 0.71.6   |
| react-native-reanimated         | 3.1.0   |
| react-native-gesture-handler    | 2.9.0  |

## Steps To Reproduce

1. Run the code snippet in web
2. Try to drag the bottom sheet

Describe what you expected to happen:

1. Bottom sheet position changes as in mobile

## Reproducible sample code

```tsx
import React, { useCallback, useMemo, useRef } from "react";
import { View, Text, StyleSheet } from "react-native";
import BottomSheet from "@gorhom/bottom-sheet";

export const App = () => {
  const bottomSheetRef = useRef<BottomSheet>(null);

  const snapPoints = useMemo(() => ["25%", "50%", "75%", "100%"], []);

  const handleSheetChanges = useCallback((index: number) => {
    console.log("handleSheetChanges", index);
  }, []);

  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: "grey",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
  },
});

```

https://user-images.githubusercontent.com/20783123/233867835-92b297eb-84f5-4816-8ab2-e722460b8079.mov

Just found this when testing v5.

**Comment by suyundukov** [comment]
Have you tried to drag it in Responsive Design Mode? If I'm not mistaken drag gestures are enabled only in mobile mode in Chrome. For more info check https://developer.chrome.com/docs/devtools/device-mode/.
