### ISSUE TITLE
[v4] | [v2] enableFooterMarginAdjustment prop not mentioned in docs

### ISSUE THREAD

**Issue by Rehubbard** [gorhom/react-native-scroll-bottom-sheet#1358]
# Bug

When using `<BottomSheetScrollView>` and `<BottomSheetTextInput>` with a footerComponent the input was scrolling on focus, but was hidden behind the footer sitting on top of the keyboard. I tried a few different ways just to try and hide the footer on keyboard shown, but nothing was working due to it being wrapped in FooterContainer.

I found `enableFooterMarginAdjustment` [here](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/types.d.ts#L24) and that seems to fix my issue. Is there a reason this hasn't been added to the documentation?

Thanks for the great library 👍

**Comment by Kakaranara** [comment]
Thanks for mentioning this, my issue also solved with this prop.
