### ISSUE TITLE
[v4] appearsOnIndex doesn't work with a single snap point

### ISSUE THREAD

**Issue by java-james** [gorhom/react-native-scroll-bottom-sheet#1362]
# Bug

Backdrop will not appear if you have a single element in the snapping and your back drop defines appear on index 0.
To achieve the desired behaviour at the moment you have to use disappearsOnIndex={-1}

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6  |
| react-native                    | 0.70.8  |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Define `BottomSheetModal` with `snapPoints={["50%"]}`
2. Add property `backdropComponent` defining a new `BottomSheetBackdrop` with property `appearsOnIndex={0}`

Describe what you expected to happen:

1. Backdrop is shown with sheet at first and only snap point

## Reproducible sample code

```
      <BottomSheetModal
        ref={bottomSheetModalRef}
        enablePanDownToClose={true}
        snapPoints={["50%"]}
        onDismiss={handleCloseModalPress}
        backdropComponent={backDropProps => (
          <BottomSheetBackdrop appearsOnIndex={0} {...backDropProps} opacity={0.5} pressBehavior={"close"} />
        )}
        handleComponent={() => (
          <View style={styles.handlerContainer}>
            <View style={styles.handler} />
          </View>
        )}
      >
..........
```

**Comment by bangerang** [comment]
Have the same issue. This workaround seems to do the trick.

```javascript
  const snapPoints = useMemo(() => ['1%', '50%'], []);
  const handleSheetChanges = useCallback((index: number) => {
    if (index === 0) {
      bottomSheetModalRef.current?.close();
    }
  }, []);
  ```

**Comment by maciejewiczow** [comment]
Having the same issue, workaround does the trick but is ugly.

**Comment by danieloi** [comment]
Same issue
