### ISSUE TITLE
[v4] BottomSheet cannot "bypass" snap point to close the sheet

### ISSUE THREAD

**Issue by QuangBinhDinh** [gorhom/react-native-scroll-bottom-sheet#1364]
# Bug
I have a `BottomSheet` which its snap points is `['45%', '90%']`. While sheet is at 90% height, I want the sheet snaps to bottom whenever user swipe down, but looks like it just snaps to 45% and cannot "bypass" it. How can I achieve this ? One more thing, seem like pan distance to make sheet starts snapping is a bit long (at 90% height , I have to swipe down like 1/4 screen height to make it move). Can we reduce this distance to make user easily close sheet by swiping a bit short ? 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4  |
| react-native                    | 0.66.4  |
| react-native-reanimated         | ^2.11.0  |
| react-native-gesture-handler    | ^2.9.0  |

## Steps To Reproduce

1. Open the sheet to 45% of the screen height
2. Swipe up to make the sheet reach 90% screen height
3.  Swipe down to close sheet, the sheet should be snap to the bottom 

Describe what you expected to happen:

1. Sheet only snap to 45% height

## Reproducible sample code
My snack : https://snack.expo.dev/@quangbinh1999/bottomsheet

Version in snack is a bit different from above (which I use on my project). I cannot reproduce in Expo cause unknown error but you can check my `<Example/>` component.

**Comment by Stenbaek** [comment]
Would it maybe be possible to change the snap points passed to the bottomsheet depending on what index it currently is snapped to?

So by default, you pass: ['45%', '90%']

and then when the user has snapped to index = 1, you just pass ['90%']
