### ISSUE TITLE
[v4] ReanimatedError: Tried to synchronously call a non-worklet function on the UI thread. 

### ISSUE THREAD

**Issue by beqramo** [gorhom/react-native-scroll-bottom-sheet#1366]
# Bug

Hi,
I swipe down the modal to close it and it throws this error.
I think call to the function is wrong

PR has been created: 
https://github.com/gorhom/react-native-bottom-sheet/pull/1367
<img width="439" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/5e9d6a67-5a7e-49b8-b581-f2f270e58815">

<img width="446" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/6b4175a2-da99-49a7-bfa0-936ff9422544">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.71   |
| react-native-reanimated         | ~3.1.0   |
| react-native-gesture-handler    | ~2.9.0   |

## Steps To Reproduce

1.create bottom-sheet input in the bottom-sheet modal
2. try to swipe down to close the modal
3. lib will crash on keyboard close

Describe what you expected to happen:

1. it shouldn't crash on close
2.

## Reproducible sample code

```tsx
const Modal = () =>{
 const ref = useRef(null);
  const sheetRef = useRef(null);



 const renderBackdrop = useCallback(
    (props) => (
      <BottomSheetBackdrop
        {...props}
        disappearsOnIndex={0}
        appearsOnIndex={1}
      />
    ),
    [],
  );
  
return  (
  <BottomSheet
      ref={sheetRef}
      snapPoints={[250]}
      backdropComponent={renderBackdrop}
    >
      <View>
         <BottomSheetTextInput 
           placeholder={'Enter Amount'}
            keyboardType={'decimal-pad'}
            value={value}
            ref={ref}
         />
      </View>
    </BottomSheet>
   )
}
```

**Comment by starnizar** [comment]
have same issue 
there is path of that hook in warning  `/node_modules/@garhom/bottom-sheet/src/hooks/useGestureEventHandlersDefault.tsx`
hope will be useful

[link](https://ibb.co/tMswC77) to image with error

**Comment by beqramo** [comment]
@starnizar you can use the pr  code changes above that I created.

**Comment by akanoce** [comment]
The same happens to me on `4.4.6` + reanimated `2.14.4`
Rolling back to `4.4.5` fixes the issue

**Comment by sawariz0r** [comment]
Also came across this on `4.4.6`, reverting to `4.4.5` instead gave me `Trying to access property "dismiss" of an object which cannot be sent to the UI runtime." 

Will post updates if I find the root of the cause

**Comment by Ricka7x** [comment]
Also ran into the same problem but it works as expected after upgrading to 4.4.7

**Comment by 90dy** [comment]
Thanks @Ricka7x
