### ISSUE TITLE
[v4] | Keyboard dismiss crashes - Tried to synchronously call a non-worklet function on the Ul thread.

### ISSUE THREAD

**Issue by tsdmrfth** [gorhom/react-native-scroll-bottom-sheet#1369]
# Bug

The app crashes when dismissing keyboard. I'm getting the error below
![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-05-12 at 10 01 36](https://github.com/gorhom/react-native-bottom-sheet/assets/27639087/30d3b4b1-0fbd-4ab1-926e-275aa10066c4)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.6   |
| react-native                    | 0.71.6   |
| react-native-reanimated         | 3.0.2  |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. Create a bottom sheet with BottomSheetTextInput
2. Swipe down the bottom sheet

Describe what you expected to happen:

1. Bottom sheet to dismiss keyboard with no crash...

## Reproducible sample code

https://snack.expo.dev/UXATlw3L7

Here is the diff that solved my problem:

```
diff --git a/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx b/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
index a0b759c..73eb034 100644
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
@@ -21,7 +21,9 @@ type GestureEventContextType = {
   isScrollablePositionLocked: boolean;
 };
 
-const dismissKeyboardOnJs = runOnJS(Keyboard.dismiss);
+const dismissKeyboard = () => {
+    Keyboard.dismiss()
+}
 
 export const useGestureEventsHandlersDefault: GestureEventsHandlersHookType =
   () => {
@@ -298,7 +300,7 @@ export const useGestureEventsHandlersDefault: GestureEventsHandlersHookType =
                 absoluteY > WINDOW_HEIGHT - animatedKeyboardHeight.value
               )
             ) {
-              dismissKeyboardOnJs();
+              runOnJS(dismissKeyboard)();
             }
           }
 ```

**Comment by eeston** [comment]
Seems to be related to these changes... https://github.com/gorhom/react-native-bottom-sheet/pull/1346

Rolling back to `4.4.5` fixes the issue for me

**Comment by andreiwow2** [comment]
I also get such an issue if I drag the sheet down when keyboard is visible
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/29161725/09c0f7fd-b257-4b4b-b324-9fbfddd79bad)

**Comment by callaars** [comment]
This is the patch that resolves this.

```
diff --git a/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx b/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
index b44bfa5..a017623 100644
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
@@ -15,6 +15,8 @@ import type {
 import { clamp } from '../utilities/clamp';
 import { snapPoint } from '../utilities/snapPoint';
 
+const dismissKeyboard = () => Keyboard.dismiss();
+
 type GestureEventContextType = {
   initialPosition: number;
   initialKeyboardState: KEYBOARD_STATE;
@@ -296,7 +298,7 @@ export const useGestureEventsHandlersDefault: GestureEventsHandlersHookType =
                 absoluteY > WINDOW_HEIGHT - animatedKeyboardHeight.value
               )
             ) {
-              runOnJS(Keyboard.dismiss)();
+              runOnJS(dismissKeyboard)();
             }
           }
 
```

**Comment by nicolascavallin** [comment]
Fixed in last version
https://github.com/gorhom/react-native-bottom-sheet/issues/1368
