### ISSUE TITLE
[v4] | [v2] Android Keyboard overlap BottomSheetTextInput when it's focused.

### ISSUE THREAD

**Issue by 7maucdn** [gorhom/react-native-scroll-bottom-sheet#1372]
# Bug

This is my code

 ```
const renderFooter = useCallback(
        props => (
            <BottomSheetFooter {...props} bottomInset={24}>
                <BottomSheetTextInput
                    ref={textBox}
                    maxLength={200}
                    placeholder="Viết bình luận..." />
            </BottomSheetFooter>
        ),
        []
    );

    return (
        <View style={tw`h-full`}>
            <BottomSheetModalProvider >
                <BottomSheetModal
                    ref={bottomSheetRef}
                    snapPoints={['70%']}
                    enablePanDownToClose={true}
                    keyboardBehavior={"extend"}
                    keyboardBlurBehavior='restore'
                    android_keyboardInputMode='adjustResize'
                    onDismiss={() => navigation.goBack()}
                    backdropComponent={renderBackdrop}
                    footerComponent={renderFooter}
                >
                    
                </BottomSheetModal>
            </BottomSheetModalProvider>
            <CommentItemAction commentActionBottomSheetRef={commentActionBottomSheetRef} />
        </View>
    );
}
```
On my Realme phone. When i press on BottomSheetTextInput, the keyboard show up, but it's overlap 1/2 the BottomSheetTextInput. This issue not happens on iOS.

See below attached video

https://github.com/gorhom/react-native-bottom-sheet/assets/19583618/372131f3-e160-411d-b9e4-017f5d41650a

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.71.3   |
| react-native-reanimated         | ~2.14.4   |
| react-native-gesture-handler    |~2.9.0   |

## Steps To Reproduce

1. Press BottomSheetTextInput inside BottomSheetModal
2. The keyboard is show up
3. Keyboard overlap 1/2 BottomSheetTextInput 

Describe what you expected to happen:

1. Press BottomSheetTextInput inside BottomSheetModal
2. The keyboard is show up
3. Keyboard not overlap 1/2 BottomSheetTextInput

**Comment by rohitjindal018** [comment]
Why is this issue closed. It is still happening in 4.4.7 version.  was anybody able to get this issue resolved?

**Comment by SriChandraSekharA** [comment]
Facing this issue in Android with edgeToEdgeEnabled: true with version: 4.6.4
