### ISSUE TITLE
[v4] PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized

### ISSUE THREAD

**Issue by soemarko** [gorhom/react-native-scroll-bottom-sheet#1373]
# Bug

Getting the error above by just installing and running the sample usage.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4     |
| react-native                    | 0.71.7   |
| react-native-reanimated         | ^3.1.0   |
| react-native-gesture-handler    | ^2.10.0   |

Tried downgrading to reanimated 2.17 but then my whole app breaks on launch.

## Steps To Reproduce

1. Follow the non-expo installation method from https://gorhom.github.io/react-native-bottom-sheet/
2. Copy and paste the code from https://gorhom.github.io/react-native-bottom-sheet/usage

Describe what you expected to happen:

1. The app runs without error

## Reproducible sample code

Exact code from https://gorhom.github.io/react-native-bottom-sheet/usage

**Comment by soemarko** [comment]
Same issue with using  v5 alpha1.

Is it because the screen I'm using it on is inside bottom tab navigation?

**Comment by T30-H0** [comment]
same issue here

**Comment by Crhis35** [comment]
I got the same error when I updated all the packages, I had to revert the changes. These are the versions that are working for me
<img width="363" alt="Captura de pantalla 2023-05-16 a la(s) 3 40 44 p m" src="https://github.com/gorhom/react-native-bottom-sheet/assets/49347705/d07a0ef4-6dc0-4f6c-8fc3-68eeb5f63371">

**Comment by quocluongha** [comment]
I fixed this by adding `GestureHandlerRootView` wrapper at the root of my project (E.g `App.tsx`). You can find the instruction here https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#js

**Comment by soemarko** [comment]
> I fixed this by adding `GestureHandlerRootView` wrapper

That's it, thank you! Just need to add that wrapper. Doesn't even need to be in the root. Just wrapped it around the `BottomSheet`. From the sample code, just replace `View` into `GestureHandlerRootView` like so;

```typescript
    <GestureHandlerRootView style={{ flex: 1 }}>
      <BottomSheet
        ref={bottomSheetRef}
        index={0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </GestureHandlerRootView>
```

**Comment by TobiramaSan** [comment]
I also fixed it by wrapping the root .js file with `GestureHandlerRootView`, but it came out weird, and I fixed that by adding style = {{flex: 1}} to `GestureHandlerRootView`

``` <GestureHandlerRootView style={{ flex: 1 }}>
      <View style={styles.container}>
        <CoinDetailsScreen />
        <StatusBar style="light" />
      </View>
    </GestureHandlerRootView>
  );
}```

**Comment by TobiramaSan** [comment]
I also fixed it by wrapping the root .js file with `GestureHandlerRootView`, but it came out weird, and I fixed that by adding style = {{flex: 1}} to `GestureHandlerRootView`.

```export default function App() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <View style={styles.container}>
        {/* <HomeScreen /> */}
        <CoinDetailsScreen />
        <StatusBar style="light" />
      </View>
    </GestureHandlerRootView>
  );
}
```
