### ISSUE TITLE
[v4] State update warning related to BottomSheetBackdrop on closing

### ISSUE THREAD

**Issue by nihilenz** [gorhom/react-native-scroll-bottom-sheet#1376]
# Bug

After upgrading to 4.4.6 from 4.3.2, we have  occasionally noticed this warning related to `BottomSheetBackdrop` when closing the bottom sheet:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in BottomSheetBackdrop
```

BottomSheetBackdrop usage:
```
backdropComponent={backdropProps => (
  <BottomSheetBackdrop {...backdropProps} disappearsOnIndex={-1} appearsOnIndex={0} pressBehavior="close" />
)}
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.67.5   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 2.4.2   |

## Steps To Reproduce

It happens occasionally both on Android and iOS. 
I think it only happens with the modal component.
The warning appears when the sheet is closed (tap on backdrop, drag gesture or programmatically)

**Comment by donatoaguirre24** [comment]
not stale

**Comment by AZ604** [comment]
Currently facing the same issue with 4.4.7, RNGH 2.8.0 and reanimated 2.4.1

**Comment by donatoaguirre24** [comment]
not stale

**Comment by AZ604** [comment]
I was able to remove the warning(error) by applying a patch from this old pr:
https://github.com/gorhom/react-native-bottom-sheet/pull/1167
But I get a different warning now:

> Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}

**Comment by nihilenz** [comment]
Please re-open, it's a very annoying issue

**Comment by louisiscoding** [comment]
Please re-open. Still occurs

**Comment by christophby** [comment]
Still occurs

**Comment by christophby** [comment]
I created a [PR](https://github.com/gorhom/react-native-bottom-sheet/pull/1657) which fixes the issue for me
