### ISSUE TITLE
[v4] | [v2] How I set zIndex to BottomSheet component?

### ISSUE THREAD

**Issue by AstrOOnauta** [gorhom/react-native-scroll-bottom-sheet#1378]
# Bug

I need to show the bottom sheet over of the modal, but I dont know set the zIndex to bottom sheet component!
Can anyone help me?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |  4.4.6   |
| react-native                    |  0.71.6  |
| react-native-reanimated         |  2.17.0   |
| react-native-gesture-handler    |  1.10.3   |

## Steps To Reproduce
JSX with my Bottom Sheet Component:

```
mport React, {useMemo, useRef, useContext, useCallback} from 'react';
import BottomSheet from '@gorhom/bottom-sheet';
import IsBottomSheetOpenContext from '../../core/contexts/bottomSheet';

export function BottomSheetComponent() {
  const {setIsBottomSheetOpen, childrenBottomSheet, maxSize} = useContext(
    IsBottomSheetOpenContext,
  );

  const bottomSheetRef = useRef(null);

  const snapPoints = useMemo(() => ['25%', maxSize ? maxSize : '50%'], []);

  const handleSheetChanges = useCallback(index => {
    if (index === -1) {
      setIsBottomSheetOpen(false);
    }
  }, []);

  return (
    <BottomSheet
      ref={bottomSheetRef}
      index={1}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      enablePanDownToClose>
      {childrenBottomSheet}
    </BottomSheet>
  );
}
``` 

## Reproducible sample code
What's happening (PRINT):

![image](https://github.com/gorhom/react-native-bottom-sheet/assets/81580470/0a83617f-1541-47b3-b05e-b0bbc64ef95f)

**Comment by Lewitje** [comment]
Try this, I use it to always show the bottom sheet ontop of other content:
https://github.com/jeremybarbet/react-native-portalize

**Comment by cam-shaw** [comment]
@AstrOOnauta if this is a native modal you're showing (i.e. if you've used Modal import from react native), there's a slim chance you'll get the bottom sheet to appear over the modal (I don't think it's possible, but happy to be wrong).

To achieve what you want, my suggestion would be to convert your modal to using Gorham's other package, [react-native-portal](https://github.com/gorhom/react-native-portal), and show your modal that way. Bottom sheet is based on that, and it will allow you to overlap "portals".

**Comment by amitchaudhary140** [comment]
Can anyone suggest how to have single instance of bottom sheet across the app? For e.g, clicking settings icon in the header should open the bottom sheet modal from the bottom of the screen and not from the bottom of the header.

**Comment by cam-shaw** [comment]
@amitchaudhary140 perhaps move that question over into Discussions https://github.com/gorhom/react-native-bottom-sheet/discussions

**Comment by Giasinit** [comment]
this is the solution:

```jsx
<BottomSheetModal
              ref={sheetRef}
              index={currentSheet.index}
              snapPoints={currentSheet.snapPoints}
              enablePanDownToClose
              onDismiss={() => setCurrentSheet(null)}
              containerStyle={{ zIndex: 1000 }} <--
            >
```
