### ISSUE TITLE
[v4] | [v2] Quickly swiping closed don't trigger onAnimate or onChange

### ISSUE THREAD

**Issue by MetaBenji** [gorhom/react-native-scroll-bottom-sheet#1381]
# Bug

When swiping to close the bottom sheet less than a second after opening it, the `onAnimate` and `onChange` callback functions aren't called.

I only have one snapPoint and it's set to `"50%"`.  Copy of my snapPoint code: `const snapPoints = useMemo(() => ["50%"], [])`

I need to call functions to change other on screen UI when the bottom sheet is closed, which therefore doesn't work in this case.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |  4.4.6   |
| react-native                    | 0.71.7  |
| react-native-reanimated         |  2.14.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open the bottom sheet 
2. Close it promptly within 1-2 seconds 
3. You'll see that the `onAnimate` and `onChange` functions don't get called

Describe what you expected to happen:

1. the `onAnimate` and `onChange` functions to be called

## Reproducible sample code

 
```
export const BottomSheetComponent = memo(function BottomSheetComponent() {
  const navigation = useNavigation<NativeStackNavigationProp<StackRouteParams>>()

  const setBottomSheetRef = useCallback(
    (ref: BottomSheet | null) => {
      // sets ref in a context so we can open the bottom sheet from other components easily
    },
    [actions]
  )

  const onAnimate = useCallback(
    (_: number, toIndex: number) => {

      if (toIndex === -1) {
// call other necessary functions
        navigation.reset({
          index: 0,
          routes: [{ name: BACKPACK_ROUTES.ROUTE_ONE }],
        })
      }
    },
    [navigation]
  )

  const onChange = useCallback((index: number) => {
    console.log("onChange", index)
  }, [])

  const snapPoints = useMemo(() => ["50%"], [])

  const animationConfigs = useBottomSheetSpringConfigs({
    damping: 80,
    overshootClamping: true,
    restDisplacementThreshold: 0.1,
    restSpeedThreshold: 0.1,
    stiffness: 70,
    mass: 0.1,
  })

  return (
    <BottomSheet
      ref={setBottomSheetRef}
      index={-1}
      enablePanDownToClose
      snapPoints={snapPoints}
      onAnimate={onAnimate}
      onChange={onChange}
      handleIndicatorStyle={styles.handle}
      backgroundStyle={styles.modalBackground}
      style={{ zIndex: 1000 }}
      animationConfigs={animationConfigs}
    >
      {/* Component rendering a native stack navigator with two screens */}
      <BackpackNavigator />
    </BottomSheet>
  )
})
```

**Comment by MetaBenji** [comment]
@gorhom I love your package but I'm running into this bug.  Any ideas?

**Comment by MetaBenji** [comment]
@gorhom I'd love to get your opinion on this bug

**Comment by jmysliv** [comment]
I have the same issue.

@gorhom can you take a look at it?

**Comment by baesumin** [comment]
+1
when I use animateOnMount={false}
it is the same issue.

**Comment by MichaelDanielTom** [comment]
For those who are looking to just see if the sheet is closed, there appears to be an `onClose` prop on `BottomSheet` that isn't documented but that does work for me where `onAnimate` or `onChange` do not work. Namely when quickly opening or closing the sheet.

**Comment by paulohenriqueav** [comment]
@gorhom I have the same issue!!

**Comment by mateuuszzzzz** [comment]
@gorhom I have the same issue. Could you take a look at this bug?

**Comment by PartypayNL** [comment]
@gorhom Same issue, doesn't seem to impact normal use alot but its just not very clean.

**Comment by ferrannp** [comment]
I think I found a solution here. Sometimes `onChange` or `onClose` will not be called if you do it very fast (open sheet and super fast press backdrop to close it) or do some weird gestures (two fingers for example).

I found when it happens, it hits here https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L1548.

My solution was to move the close part before it:

https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L1573-L1583

(using `patch-package`).

cc @gorhom

**Comment by kostas64** [comment]
Hi guys, dont know if you found a solution but i found something i could play around. I used prop "animatedIndex". You can pass a sharedValue there and its interpolated based on modal state. 

```
const snapPoints = [80, 500];
const sheetState = useSharedValue(1);

<BottomSheet
          index={1}
          ref={bottomSheetRef}
          snapPoints={snapPoints}
          animatedIndex={sheetState}
          backgroundStyle={styles.borderRad}
          handleIndicatorStyle={styles.sheetIndicator}>
 .......
 </BottomSheet>
 ```
 
 So i use  sheetState to interpolate content's opacity. 'opacity.value' is the sheetState.value
 
 ```
 const opacityStyle = useAnimatedStyle(() => ({
    opacity: interpolate(opacity.value, [0, 1], [0, 1], Extrapolation.CLAMP),
  }));
 ```

**Comment by hayata-suenaga** [comment]
I'm also experiencing the issue 🤔

**Comment by paulohenriqueav** [comment]
I'm also experiencing the issue 🤔

**Comment by BorislavStefanov31** [comment]
Is there any progress on this?

**Comment by LucasWilliams2622** [comment]
I’m also experiencing the same issue where onChange is not always triggered when the bottom sheet index changes via gesture (dragging).

As a temporary workaround, we can sync animatedIndex with onChange using useAnimatedReaction — this solved my problem:
```

diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
index 6748c93..4e4b7a9 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
@@ -1746,6 +1746,36 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
       [_providedAnimatedPosition, topInset]
     );
 
+    /**
+     * Synchronizes the animated index with the external onChange callback.
+     *
+     * This patch ensures that `onChange` is triggered correctly when the bottom sheet
+     * index changes via user gestures (e.g., dragging), especially in cases where
+     * the default implementation may miss updates.
+     *
+     * - Listens to changes of `animatedIndex`.
+     * - Skips invalid state when index is `-1` (closed state).
+     * - Rounds index to avoid floating point inconsistencies.
+     * - Invokes `onChange` on the JS thread using `runOnJS`.
+     *
+     * Note:
+     * This is a minimal and safe patch that does not affect the initial mount behavior.
+     */
+    useAnimatedReaction(
+      () => animatedIndex.value,
+      (current, previous) => {
+        'worklet';
+
+        if (current !== previous && Math.round(current) !== -1) {
+          const newIndex = Math.round(current);
+          if (props.onChange) {
+            runOnJS(props.onChange)(newIndex, animatedPosition.value, 0);
+          }
+        }
+      },
+      [props.onChange, animatedPosition]
+    );
+
     /**
      * sets provided animated index
      */

```
