### ISSUE TITLE
[v4] | [v2] Bottomsheet in the flatlist renderItem is not working

### ISSUE THREAD

**Issue by AMITHATHAMPY** [gorhom/react-native-scroll-bottom-sheet#1387]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.6   |
| react-native                    | 0.71.2   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

I have a horizontal flat list where in which each item in the list should considered as a bottom sheet..So that I can swipe up and  swipe down this individual item.
But this flatlist is not displaying when we are adding bottom sheet to its render item..without bottom sheet it is working fine

![image](https://github.com/gorhom/react-native-bottom-sheet/assets/63200139/410d837e-435f-485a-96a7-aabea8fd874b)

## Reproducible sample code

      <FlatList
                    data={data}
                    renderItem={renderitem}
                    keyExtractor={(item) => item?.id}
                    horizontal
                    nestedScrollEnabled={true}
                  />
renderitem:

    <BottomSheet
        ref={bottomSheetRef}
        index={ 0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View>
         <Text>test</Text>
       </View>
      </BottomSheet>

**Comment by AftabUfaq** [comment]
same issue. i ahve to open a bttomsheet i in a list to select form alist. but it not show just on the list not from the bottom of the sheet
