### ISSUE TITLE
App crashes without GestureHandlerRootView

### ISSUE THREAD

**Issue by mertafor** [gorhom/react-native-scroll-bottom-sheet#1389]
# Bug
I'm not sure when this started to happened exactly but my app crashes by throwing following errors : 

```
Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

This error is located at:
    in PanGestureHandler (created by BottomSheetDraggableViewComponent)
    in BottomSheetDraggableViewComponent (created by BottomSheet)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by BottomSheet)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by BottomSheet)
    in RCTView (created by View)
    in View (created by BottomSheetContainerComponent)
    in BottomSheetContainerComponent (created by BottomSheet)
    in BottomSheetGestureHandlersProvider (created by BottomSheet)
    in BottomSheet (created by BottomSheet)
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in AwesomeProject(RootComponent), js engine: hermes
 ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

This error is located at:
    in PanGestureHandler (created by BottomSheetHandleContainerComponent)
    in BottomSheetHandleContainerComponent (created by BottomSheet)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by BottomSheet)
    in RCTView (created by View)
    in View (created by BottomSheetContainerComponent)
    in BottomSheetContainerComponent (created by BottomSheet)
    in BottomSheetGestureHandlersProvider (created by BottomSheet)
    in BottomSheet (created by BottomSheet)
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in AwesomeProject(RootComponent), js engine: hermes
 ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

This error is located at:
    in PanGestureHandler (created by BottomSheetDraggableViewComponent)
    in BottomSheetDraggableViewComponent (created by BottomSheet)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by BottomSheet)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by BottomSheet)
    in RCTView (created by View)
    in View (created by BottomSheetContainerComponent)
    in BottomSheetContainerComponent (created by BottomSheet)
    in BottomSheetGestureHandlersProvider (created by BottomSheet)
    in BottomSheet (created by BottomSheet)
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in AwesomeProject(RootComponent), js engine: hermes
```

## Environment info

I know bottom sheet is only compatible with react reanimated v2 but I've been using the latest version of all libraries without any problem when I use bottom sheet modal. I also tried to downgrade react-reanimated to 2.x in case it's a compatibility issue yet the result is same. Furthermore I  tried to install react native from scratch and installed only bottom-sheet, reanimated and gesture handler other than react-native (with recommended versions). Again, it doesn't work

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 3.2.0   |
| react-native-gesture-handler    | 2.10.2   |

## Steps To Reproduce

1. Install a fresh react native app and bottom-sheet along with dependencies
2. Use the basic bottom sheet modal code that is provided in documentation
3. App is getting crashed if bottomsheetmodalprovider is not wrapped with `<GestureHandlerRootView style={{ flex: 1 }}>`

Describe what you expected to happen:

1. As in documentation, using only bottomsheetmodalprovider and bottom sheet modal inside of it without using extra wrappers.

## Reproducible sample code

Using the following sample code provided in documentation on a freshly installed react native app :
https://gorhom.github.io/react-native-bottom-sheet/modal/usage

The final question is, does wrapping the app with <GestureHandlerRootView style={{ flex: 1 }}> has any side effects?

**Comment by mertafor** [comment]
Sorry for this wrong bug report, please ignore. I noticed that it's recommended to use GestureHandlerRootView with gesture handler 2+. I'm just surprised how it was working before (I also use react navigation).

**Comment by MensurRasic** [comment]
Hey, got exactly the same issue here, the error appeared out of no where. How did you fixed it on your side? You wrapped the whole app with GestureHandlerRootView?

**Comment by mertafor** [comment]
@MensurRasic Yes, it's actually mentioned in Installation step of documentation (blue highlighted box), but honestly never needed before : 
https://gorhom.github.io/react-native-bottom-sheet/

This way it works just fine :
```js
import { BottomSheetModalProvider } from '@gorhom/bottom-sheet'
import { GestureHandlerRootView } from 'react-native-gesture-handler'

const App = () => {
  return (
        <GestureHandlerRootView style={{ flex: 1 }}>
            <BottomSheetModalProvider>
              <AppContent />
            </BottomSheetModalProvider>
        </GestureHandlerRootView>
  )
}
```

**Comment by Arch1tect** [comment]
Also got this issue after I upgrade reanimated to v3 and react-native-gesture-handler from 2.9 to 2.12, the above solution works.

**Comment by kirtikapadiya** [comment]
Follow this documents : https://docs.swmansion.com/react-native-gesture-handler/docs/installation/

**Comment by toemmanuel** [comment]
import {GestureHandlerRootView} from 'react-native-gesture-handler', then wrap your swipable component with GestureHandlerRootView.

**Comment by MaryamKhan05** [comment]
Expo Project---
I faced the same issue and attempted to solve it by wrapping everything inside app.js with GestureHandlerRootView. Additionally, I imported "react-native-gesture-handler" at the top of app.js. what more can I do? 
Any help would be appreciated

**Comment by MaryamKhan05** [comment]
> Expo Project--- I faced the same issue and attempted to solve it by wrapping everything inside app.js with GestureHandlerRootView. Additionally, I imported "react-native-gesture-handler" at the top of app.js. what more can I do? Any help would be appreciated

I tried various solutions, but nothing seemed to work. Eventually, I was able to successfully resolve the issue by downgrading my react-native-gesture-handler to version 2.9.0.

**Comment by numannaqvi** [comment]
i face the same issue 
 **Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.**

i resolved this issue my importing FlatList from react-native instead of gensture handeler

**Comment by iway1** [comment]
@MaryamKhan05 wrapping the whole app worked for me when upgrading an expo project - but had to make sure that the gesture handler root view was the parent of some other providers (`<PortalProvider/>` specifically)

**Comment by djmarcosban** [comment]
import {GestureHandlerRootView} from 'react-native-gesture-handler'

<GestureHandlerRootView style={{flex: 1}}>{YOUR APP}</GestureHandlerRootView>

**Comment by wish-me-luck** [comment]
After adding both  GestureHandlerRootView and BottomSheet, my surface stopped rendering, it just shows complete white background w/o crashing on iOS simulator. Removing BottomSheet alone would resolve the issue. 

<GestureHandlerRootView style={{flex: 1}}>
    <My Surface>
   <Bottom Sheet>
      <PopUpContent>
  </Bottom Sheet>
</GestureHandlerRootView>


```
 "@gorhom/bottom-sheet": "^4",
 "react-native-gesture-handler": "~2.12.0",
 "react-native-reanimated": "~3.3.0",

**Comment by edencalves** [comment]
I have a similar problem, the app works normally in expo go, but when it goes to the Apple fligth test it freezes and doesn't give any errors, I'm using Swipeable from react-native-gesture-handler if I remove it the app works

**Comment by Real-Musafir** [comment]
> @MensurRasic Yes, it's actually mentioned in Installation step of documentation (blue highlighted box), but honestly never needed before : https://gorhom.github.io/react-native-bottom-sheet/
> 
> This way it works just fine :
> 
> ```js
> import { BottomSheetModalProvider } from '@gorhom/bottom-sheet'
> import { GestureHandlerRootView } from 'react-native-gesture-handler'
> 
> const App = () => {
>   return (
>         <GestureHandlerRootView style={{ flex: 1 }}>
>             <BottomSheetModalProvider>
>               <AppContent />
>             </BottomSheetModalProvider>
>         </GestureHandlerRootView>
>   )
> }
> ```

After doing this I am facing new error in macos "TypeError: undefined is not an object (evaluating 'this.view.style['touchAction'] = 'none'')". Anyone have this solution?

**Comment by sedtapongn** [comment]
> @MaryamKhan05 wrapping the whole app worked for me when upgrading an expo project - but had to make sure that the gesture handler root view was the parent of some other providers (`<PortalProvider/>` specifically)

Got an idea from this. I try to put GestureHandlerRootView as parent of may app Portal or Provider. Both way are work fine.
This is my app structure.

```JavaScript
import { NavigationContainer } from '@react-navigation/native';
import { Host } from 'react-native-portalize';
import { Provider } from 'react-redux';
import { createStackNavigator } from '@react-navigation/stack';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

export default function App() {
const AppStackNavigator = createStackNavigator();

 return (
    <Provider>
        <NavigationContainer>
          <GestureHandlerRootView style={{flex:1}}>
          <Host>
            <AppStackNavigator.Navigator>
                ...
                ...
            </AppStackNavigator.Navigator>
          </Host>
          </GestureHandlerRootView>
        </NavigationContainer>
    </Provider>
  );
}
```

this one also work:

```JavaScript
return (
    <GestureHandlerRootView style={{flex:1}}>
    <Provider>
        <NavigationContainer>
          <Host>
            <AppStackNavigator.Navigator>
                ...
                ...
            </AppStackNavigator.Navigator>
          </Host>
        </NavigationContainer>
    </Provider>
    </GestureHandlerRootView>
  );
}
```

Hope this help.

**Comment by shreyasskasetty** [comment]
> Expo Project---
> I faced the same issue and attempted to solve it by wrapping everything inside app.js with GestureHandlerRootView. Additionally, I imported "react-native-gesture-handler" at the top of app.js. what more can I do?
> Any help would be appreciated



> # Bug
> I'm not sure when this started to happened exactly but my app crashes by throwing following errors :
> 
> ```
> Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> 
> This error is located at:
>     in PanGestureHandler (created by BottomSheetDraggableViewComponent)
>     in BottomSheetDraggableViewComponent (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by AnimatedComponent(View))
>     in AnimatedComponent(View)
>     in Unknown (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by AnimatedComponent(View))
>     in AnimatedComponent(View)
>     in Unknown (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by BottomSheetContainerComponent)
>     in BottomSheetContainerComponent (created by BottomSheet)
>     in BottomSheetGestureHandlersProvider (created by BottomSheet)
>     in BottomSheet (created by BottomSheet)
>     in PortalHostComponent (created by PortalProviderComponent)
>     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
>     in BottomSheetModalProviderWrapper (created by App)
>     in App
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in AppContainer
>     in AwesomeProject(RootComponent), js engine: hermes
>  ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> 
> This error is located at:
>     in PanGestureHandler (created by BottomSheetHandleContainerComponent)
>     in BottomSheetHandleContainerComponent (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by AnimatedComponent(View))
>     in AnimatedComponent(View)
>     in Unknown (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by BottomSheetContainerComponent)
>     in BottomSheetContainerComponent (created by BottomSheet)
>     in BottomSheetGestureHandlersProvider (created by BottomSheet)
>     in BottomSheet (created by BottomSheet)
>     in PortalHostComponent (created by PortalProviderComponent)
>     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
>     in BottomSheetModalProviderWrapper (created by App)
>     in App
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in AppContainer
>     in AwesomeProject(RootComponent), js engine: hermes
>  ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> 
> This error is located at:
>     in PanGestureHandler (created by BottomSheetDraggableViewComponent)
>     in BottomSheetDraggableViewComponent (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by AnimatedComponent(View))
>     in AnimatedComponent(View)
>     in Unknown (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by AnimatedComponent(View))
>     in AnimatedComponent(View)
>     in Unknown (created by BottomSheet)
>     in RCTView (created by View)
>     in View (created by BottomSheetContainerComponent)
>     in BottomSheetContainerComponent (created by BottomSheet)
>     in BottomSheetGestureHandlersProvider (created by BottomSheet)
>     in BottomSheet (created by BottomSheet)
>     in PortalHostComponent (created by PortalProviderComponent)
>     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
>     in BottomSheetModalProviderWrapper (created by App)
>     in App
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in AppContainer
>     in AwesomeProject(RootComponent), js engine: hermes
> ```
> 
> ## Environment info
> I know bottom sheet is only compatible with react reanimated v2 but I've been using the latest version of all libraries without any problem when I use bottom sheet modal. I also tried to downgrade react-reanimated to 2.x in case it's a compatibility issue yet the result is same. Furthermore I tried to install react native from scratch and installed only bottom-sheet, reanimated and gesture handler other than react-native (with recommended versions). Again, it doesn't work
> 
> Library	Version
> @gorhom/bottom-sheet	4.4.6
> react-native	0.71.8
> react-native-reanimated	3.2.0
> react-native-gesture-handler	2.10.2
> ## Steps To Reproduce
> 1. Install a fresh react native app and bottom-sheet along with dependencies
> 2. Use the basic bottom sheet modal code that is provided in documentation
> 3. App is getting crashed if bottomsheetmodalprovider is not wrapped with `<GestureHandlerRootView style={{ flex: 1 }}>`
> 
> Describe what you expected to happen:
> 
> 1. As in documentation, using only bottomsheetmodalprovider and bottom sheet modal inside of it without using extra wrappers.
> 
> ## Reproducible sample code
> Using the following sample code provided in documentation on a freshly installed react native app : https://gorhom.github.io/react-native-bottom-sheet/modal/usage
> 
> The final question is, does wrapping the app with <GestureHandlerRootView style={{ flex: 1 }}> has any side effects?

I'm currently using GestureHandlerRootView in order to avoid the error. However I see a side effect when used with BottomSheet. It is not allowing for simultaneous gesture handling of both React Native MapView and BottomSheet. Can anyone please help me on how to solve this issue?

```
    <GestureHandlerRootView style={{flex: 1}}>
      <SafeAreaView style={{ flex: 1}}>
        <Stack.Screen
          options={{
            headerTransparent: true,
            headerShadowVisible: false,
            headerTitle: "",
          }}
        />
         <Map mapRef={mapRef}/>
          {bottomSheetOpen && <TourRoutesSheet onFocusChange = {setBottomSheetOpen}/>}
      </SafeAreaView>
      </GestureHandlerRootView>
 ```     
 `<Map>` component contains the React Native `<MapView>`. `<TourRoutesSheet>` wraps the BottomSheetComponent. I'm not able to interact with the map when Bottom Sheet is present, even if its collapsed.

**Comment by rmacchi** [comment]
**Before with error:**

```
<View style={{ flex: 1, marginTop: 130 }}>
 <Stack.Screen
  options={{
   header: () => <ExploreHeader onCategoryChanged={onDataChanged} />,
  }}
 />
 {/* <Listings listings={items} category={category} /> */}
 <ListingsMap listings={listingsDataGeo} />
 <ListingsBottomSheet listings={items} category={category} />
</View>
```

**The solution:** 

**import { GestureHandlerRootView } from 'react-native-gesture-handler'**

```
<GestureHandlerRootView style={{ flex: 1 }}>
 <View style={{ flex: 1, marginTop: 130 }}>
   <Stack.Screen
     options={{
       header: () => <ExploreHeader onCategoryChanged={onDataChanged} />,
     }}
   />
   {/* <Listings listings={items} category={category} /> */}
   <ListingsMap listings={listingsDataGeo} />
   <ListingsBottomSheet listings={items} category={category} />
 </View>
</GestureHandlerRootView>
```

**Comment by ChuDinhHanh** [comment]
thx u sir

**Comment by richardd3ng** [comment]
> > Expo Project---
> > I faced the same issue and attempted to solve it by wrapping everything inside app.js with GestureHandlerRootView. Additionally, I imported "react-native-gesture-handler" at the top of app.js. what more can I do?
> > Any help would be appreciated
> 
> > # Bug
> > I'm not sure when this started to happened exactly but my app crashes by throwing following errors :
> > ```
> > Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> > 
> > This error is located at:
> >     in PanGestureHandler (created by BottomSheetDraggableViewComponent)
> >     in BottomSheetDraggableViewComponent (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by AnimatedComponent(View))
> >     in AnimatedComponent(View)
> >     in Unknown (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by AnimatedComponent(View))
> >     in AnimatedComponent(View)
> >     in Unknown (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by BottomSheetContainerComponent)
> >     in BottomSheetContainerComponent (created by BottomSheet)
> >     in BottomSheetGestureHandlersProvider (created by BottomSheet)
> >     in BottomSheet (created by BottomSheet)
> >     in PortalHostComponent (created by PortalProviderComponent)
> >     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
> >     in BottomSheetModalProviderWrapper (created by App)
> >     in App
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in AppContainer
> >     in AwesomeProject(RootComponent), js engine: hermes
> >  ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> > 
> > This error is located at:
> >     in PanGestureHandler (created by BottomSheetHandleContainerComponent)
> >     in BottomSheetHandleContainerComponent (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by AnimatedComponent(View))
> >     in AnimatedComponent(View)
> >     in Unknown (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by BottomSheetContainerComponent)
> >     in BottomSheetContainerComponent (created by BottomSheet)
> >     in BottomSheetGestureHandlersProvider (created by BottomSheet)
> >     in BottomSheet (created by BottomSheet)
> >     in PortalHostComponent (created by PortalProviderComponent)
> >     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
> >     in BottomSheetModalProviderWrapper (created by App)
> >     in App
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in AppContainer
> >     in AwesomeProject(RootComponent), js engine: hermes
> >  ERROR  Error: PanGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.
> > 
> > This error is located at:
> >     in PanGestureHandler (created by BottomSheetDraggableViewComponent)
> >     in BottomSheetDraggableViewComponent (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by AnimatedComponent(View))
> >     in AnimatedComponent(View)
> >     in Unknown (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by AnimatedComponent(View))
> >     in AnimatedComponent(View)
> >     in Unknown (created by BottomSheet)
> >     in RCTView (created by View)
> >     in View (created by BottomSheetContainerComponent)
> >     in BottomSheetContainerComponent (created by BottomSheet)
> >     in BottomSheetGestureHandlersProvider (created by BottomSheet)
> >     in BottomSheet (created by BottomSheet)
> >     in PortalHostComponent (created by PortalProviderComponent)
> >     in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
> >     in BottomSheetModalProviderWrapper (created by App)
> >     in App
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in RCTView (created by View)
> >     in View (created by AppContainer)
> >     in AppContainer
> >     in AwesomeProject(RootComponent), js engine: hermes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Environment info
> > I know bottom sheet is only compatible with react reanimated v2 but I've been using the latest version of all libraries without any problem when I use bottom sheet modal. I also tried to downgrade react-reanimated to 2.x in case it's a compatibility issue yet the result is same. Furthermore I tried to install react native from scratch and installed only bottom-sheet, reanimated and gesture handler other than react-native (with recommended versions). Again, it doesn't work
> > Library	Version
> > @gorhom/bottom-sheet	4.4.6
> > react-native	0.71.8
> > react-native-reanimated	3.2.0
> > react-native-gesture-handler	2.10.2
> > ## Steps To Reproduce
> > 
> > 1. Install a fresh react native app and bottom-sheet along with dependencies
> > 2. Use the basic bottom sheet modal code that is provided in documentation
> > 3. App is getting crashed if bottomsheetmodalprovider is not wrapped with `<GestureHandlerRootView style={{ flex: 1 }}>`
> > 
> > Describe what you expected to happen:
> > 
> > 1. As in documentation, using only bottomsheetmodalprovider and bottom sheet modal inside of it without using extra wrappers.
> > 
> > ## Reproducible sample code
> > Using the following sample code provided in documentation on a freshly installed react native app : https://gorhom.github.io/react-native-bottom-sheet/modal/usage
> > The final question is, does wrapping the app with <GestureHandlerRootView style={{ flex: 1 }}> has any side effects?
> 
> I'm currently using GestureHandlerRootView in order to avoid the error. However I see a side effect when used with BottomSheet. It is not allowing for simultaneous gesture handling of both React Native MapView and BottomSheet. Can anyone please help me on how to solve this issue?
> 
> ```
>     <GestureHandlerRootView style={{flex: 1}}>
>       <SafeAreaView style={{ flex: 1}}>
>         <Stack.Screen
>           options={{
>             headerTransparent: true,
>             headerShadowVisible: false,
>             headerTitle: "",
>           }}
>         />
>          <Map mapRef={mapRef}/>
>           {bottomSheetOpen && <TourRoutesSheet onFocusChange = {setBottomSheetOpen}/>}
>       </SafeAreaView>
>       </GestureHandlerRootView>
> ```
> 
> `<Map>` component contains the React Native `<MapView>`. `<TourRoutesSheet>` wraps the BottomSheetComponent. I'm not able to interact with the map when Bottom Sheet is present, even if its collapsed.

Were you able to find a solution? I am running into the same issue.

**Comment by ChuDinhHanh** [comment]
const App = () => {
  return (
    <GestureHandlerRootView>
      <MenuProvider>
        <Provider store={store}>
          <PaperProvider>
            <NavigationContainer>
              <ModalLike>
                <BottomSheetModalWrapper>
                  <DrawerNavigator />
                </BottomSheetModalWrapper>
              </ModalLike>
            </NavigationContainer>
          </PaperProvider>
        </Provider>
      </MenuProvider>
    </GestureHandlerRootView>
  );
};
