### ISSUE TITLE
Tried to synchoronously call function {dimiss} from a different thread issue:  when I drag the sheet down when keyboard is visible

### ISSUE THREAD

**Issue by mudassir77** [gorhom/react-native-scroll-bottom-sheet#1390]
# Bug

Tried to synchoronously call function {dimiss} from a different thread issue:  when I drag the sheet down when keyboard is visible

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5([url](url))   |
| react-native                    | 0.70.6   |
| react-native-reanimated         | 2.13.0   |
| react-native-gesture-handler    | 2.9.0  |

## Steps To Reproduce

1.When the keyboard is opened and you try to close the bottom sheet by swiping it down it gives this error
 

Describe what you expected to happen:

1. Bottom sheet should close without giving the error.

**Comment by sayan-webskitters** [comment]
https://github.com/gorhom/react-native-bottom-sheet/assets/135309474/3514f3d3-d7bb-41c9-bf14-e083249ddb0c

facing the same issue

**Comment by mozzius** [comment]
Same here: fix is to downgrade the version to v4.4.5

Seems like the latest version fixed a bug for reanimated v3 but introduced a new one for reanimated v2
