### ISSUE TITLE
`onOpen` props

### ISSUE THREAD

**Issue by bryanprimus** [gorhom/react-native-scroll-bottom-sheet#1393]
# Feature Request

i see that we have onClose `props` to detect whether the action for the bottom sheet is closing or not

why don't we have the same one for `open` action?

## Why it is needed

Currently i'm implementing `onOpen` like this
```ts
onChange={(index) => {
  if (index !== -1) {
    onOpen?.();
  }
}}
onAnimate={(fromIndex, toIndex) => {
  if (toIndex !== -1) {
    onOpen?.();
  }
}}
```

which sometimes leads to `onOpen` not being called if user immediately closes the sheet before it is fully open

### Code sample

```ts
<BottomSheet 
   onOpen={() => {
     alert("Sheet opened")
   }} 
   onClose={() => {
     alert("Now we have consistent api")
   }}
/>
```

**Comment by baesumin** [comment]
+1

**Comment by paulo-hortelan** [comment]
I don't believe this is necessary, you can just use `onChange` and check if the `index` parameter is 0:

```jsx
const onChange = (index) => {
  if (index === 0) console.log('sheet opened');
  else if (index === -1) console.log('sheet closed');
};

...
<BottomSheetModal
  ref={sheetRef}
  backdropComponent={BottomSheetBackdrop}
  snapPoints={snapPoints}
  onChange={onChange}
>
  <BottomSheetView style={styles.sheetView}>
    <Content/>
  </BottomSheetView>
</BottomSheetModal>
);
...
```

**Comment by baesumin** [comment]
For specific feature development, if I change animateOnMount to false, onchange will not work.

**Comment by mathieumousnier** [comment]
Be careful with the @paulo-hortelan solution.
If your modal has multiple positions, the `index === 0` can occur several times before the modal is closed.

The onChange callback should look like this : 
```ts
const lastIndexRef = useRef<number>(-1);

const onChange = (index: number) => {
    const hasOpened = lastIndexRef.current === -1 && index === 0;
    const hasClosed = index === -1;

    if (hasOpened) {
        console.log('bottomSheet just opened');
    }
    if (hasClosed) {
        console.log('bottomSheet just closed');
    }
    lastIndexRef.current = index;
};
```
