### ISSUE TITLE
Automatically adjust to content height

### ISSUE THREAD

**Issue by MetaBenji** [gorhom/react-native-scroll-bottom-sheet#1395]
# Feature Request

Automatically adjust the modal to the height of it's children.  

## Why it is needed

Often I want the modal to be the size of the content within it.  Setting a snap point isn't responsive on different size devices

## Possible implementation

react-native-modalize has an implementation for this

**Comment by bryanprimus** [comment]
you need to use this https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints

but it doesn't support `scrollables` out of the box

**Comment by ororsatti** [comment]
> you need to use this https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints
> 
> but it doesn't support `scrollables` out of the box

https://github.com/gorhom/react-native-bottom-sheet/pull/1402
