### ISSUE TITLE
[v4] | [v2] Bottom Sheet not dropping to bottom fully

### ISSUE THREAD

**Issue by Nderim1** [gorhom/react-native-scroll-bottom-sheet#1397]
# Bug

Hi, I am not sure if this is a bug or maybe I am not using the lib correctly.
I copied the exact example code in BottomSheetView documentation page and the result don't seem to be correct.
I am not able to fully close (or at least drop to the bottom) the Bottom Sheet "drawer".

I can manage to set the "drawer" at the bottom by setting a higher padding to the main View, but this hides the text in the main view content (`<Text>Hello there</Text>`).

https://github.com/gorhom/react-native-bottom-sheet/assets/15191094/ab4ef990-9cce-4485-b837-fd6ff3ed820d

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4  |
| react-native                    | 0.71.10   |
| react-native-reanimated         | 3.2.0   |
| react-native-gesture-handler    | 2.11.0   |

## Steps To Reproduce

1. Copy [BottomSheetView Example](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetview) code
2. By default the Bottom Sheet "drawer" is set at the top and there is no way of dragging it down

Describe what you expected to happen:

1. By dragging down Bottom Sheet "drawer", the drawer should close or go to the bottom

## Reproducible sample code

```js
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet, Button } from 'react-native';
import BottomSheet, { BottomSheetView } from '@gorhom/bottom-sheet';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

const App = () => {
  // hooks
  const sheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%', '90%'], []);

  // callbacks
  const handleSheetChange = useCallback(index => {
    console.log('handleSheetChange', index);
  }, []);
  const handleSnapPress = useCallback(index => {
    sheetRef.current?.snapToIndex(index);
  }, []);
  const handleClosePress = useCallback(() => {
    sheetRef.current?.close();
  }, []);

  // render
  return (
    <GestureHandlerRootView>
      <View style={styles.container}>
        <Text>Hello there</Text>
        <BottomSheet
          ref={sheetRef}
          snapPoints={snapPoints}
          onChange={handleSheetChange}>
          <BottomSheetView>
            <Text>Awesome 🔥</Text>
          </BottomSheetView>
        </BottomSheet>
      </View>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 200,
    backgroundColor: '#111',
    color: 'red',
  },
});

export default App;
```

**Comment by wragony** [comment]
Set the same element value in the snapPoints parameter. 
For example：

`const snapPoints = useMemo(() => ['90%' '90%'], []);`
