### ISSUE TITLE
[v4] Weird bug that happens only in iOS 16.x devices

### ISSUE THREAD

**Issue by Vatousiadis** [gorhom/react-native-scroll-bottom-sheet#1407]
First of all thank you gorhom and all contributors for the awesome library

# Bug
Whenever the modal sheet is active and i try to minimize the app (get it to background) the app crashes (i will provide crash log below)
This does not happen if while active the modal has a device keyboard active too.
Note that while my use-case has some other UIs too in the modal, i tried this with a clean modal (only a flex View inside) and the bug still occurs

Crash Log:

Incident Identifier: 197F4045-FE91-4A5C-AAD6-67A1FE45F6DE
CrashReporter Key:   AFAC9E2B-67F8-B2EC-4DC5-14ACE972736F
Hardware Model:      Macmini8,1
Process:             myApp [30530]
Path:                .../myApp.app/myApp
Identifier:          com.myApp.myApp
Version:             1.7.41 (52)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [1097]
Coalition:           com.apple.CoreSimulator.SimDevice.9A1E865F-E79D-43C4-B1E4-C8CEB1CD041C [971]
Responsible Process: SimulatorTrampoline [1050]

Date/Time:           2023-06-19 14:44:55.7056 +0300
Launch Time:         2023-06-19 14:44:41.8532 +0300
OS Version:          macOS 13.2 (22D49)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	    0x7ff80042889b __exceptionPreprocess + 226
1   libobjc.A.dylib               	    0x7ff80004dba3 objc_exception_throw + 48
2   CoreFoundation                	    0x7ff800437ab8 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   CoreFoundation                	    0x7ff80042cd71 ___forwarding___ + 1431
4   CoreFoundation                	    0x7ff80042f068 _CF_forwarding_prep_0 + 120
5   myApp              	       0x10607c571 -[InteractableView gestureRecognizerShouldBegin:] + 65 (InteractableView.m:346)
6   UIKitCore                     	       0x11a4d49cc -[UIGestureRecognizer _shouldBegin] + 241
7   UIKitCore                     	       0x11a4ce4c1 -[UIGestureRecognizer setState:] + 296
8   UIKitCore                     	       0x11a4f843d -[_UISystemGestureGateGestureRecognizer _systemGestureStateChanged:] + 343
9   CoreFoundation                	    0x7ff80035964b __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
10  CoreFoundation                	    0x7ff800359581 ___CFXRegistrationPost_block_invoke + 86
11  CoreFoundation                	    0x7ff800358b60 _CFXRegistrationPost + 541
12  CoreFoundation                	    0x7ff800358469 _CFXNotificationPost + 822
13  Foundation                    	    0x7ff800c09459 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
14  UIKitCore                     	       0x11ab21cb2 -[UIWindow _setSystemGestureRecognitionIsPossible:andTouchesAreCancelled:] + 220
15  UIKitCore                     	       0x11ab8f59d __updateSystemGestureRecognitionIsPossible + 354
16  UIKitCore                     	       0x11ab9132e __dispatchPreprocessedEventFromEventQueue + 3954
17  UIKitCore                     	       0x11ab94f69 __processEventQueue + 8334
18  UIKitCore                     	       0x11ab8b2a1 __eventFetcherSourceCallback + 272
19  CoreFoundation                	    0x7ff800387fe5 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
20  CoreFoundation                	    0x7ff800387f24 __CFRunLoopDoSource0 + 157
21  CoreFoundation                	    0x7ff800387781 __CFRunLoopDoSources0 + 308
22  CoreFoundation                	    0x7ff800381e23 __CFRunLoopRun + 927
23  CoreFoundation                	    0x7ff8003816a7 CFRunLoopRunSpecific + 560
24  GraphicsServices              	    0x7ff809cb128a GSEventRunModal + 139
25  UIKitCore                     	       0x11aac8ad3 -[UIApplication _run] + 994
26  UIKitCore                     	       0x11aacd9ef UIApplicationMain + 123
27  myApp             	       0x105c02f88 main + 104 (main.m:8)
28  dyld_sim                      	       0x10a2182bf start_sim + 10
29  dyld                          	       0x10db6a310 start + 2432

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff83611d22a __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff836175f7b pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff800132fe0 abort + 130
3   libc++abi.dylib               	    0x7ff800258742 abort_message + 241
4   libc++abi.dylib               	    0x7ff80024995d demangling_terminate_handler() + 266
5   libobjc.A.dylib               	    0x7ff800032082 _objc_terminate() + 96
6   libc++abi.dylib               	    0x7ff800257b65 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	    0x7ff80025a3a4 __cxa_rethrow + 99
8   libobjc.A.dylib               	    0x7ff80004dd0d objc_exception_rethrow + 37
9   CoreFoundation                	    0x7ff800381769 CFRunLoopRunSpecific + 754
10  GraphicsServices              	    0x7ff809cb128a GSEventRunModal + 139
11  UIKitCore                     	       0x11aac8ad3 -[UIApplication _run] + 994
12  UIKitCore                     	       0x11aacd9ef UIApplicationMain + 123
13  myApp            	       0x105c02f88 main + 104 (main.m:8)
14  dyld_sim                      	       0x10a2182bf start_sim + 10
15  dyld                          	       0x10db6a310 start + 2432

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff836171c58 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff836171c58 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff836171c58 start_wqthread + 0

Thread 4:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	    0x7ff8361165c2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff836124604 mach_msg2_internal + 82
2   libsystem_kernel.dylib        	    0x7ff83611d635 mach_msg_overwrite + 723
3   libsystem_kernel.dylib        	    0x7ff8361168a8 mach_msg + 19
4   CoreFoundation                	    0x7ff80038788e __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff800381fdf __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff8003816a7 CFRunLoopRunSpecific + 560
7   Foundation                    	    0x7ff800c568b4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
8   Foundation                    	    0x7ff800c56b2d -[NSRunLoop(NSRunLoop) runUntilDate:] + 72
9   UIKitCore                     	       0x11ab9e286 -[UIEventFetcher threadMain] + 535
10  Foundation                    	    0x7ff800c8011b __NSThread__start__ + 1009
11  libsystem_pthread.dylib       	    0x7ff836176259 _pthread_start + 125
12  libsystem_pthread.dylib       	    0x7ff836171c7b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff836171c58 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff836171c58 start_wqthread + 0

Thread 7:: com.facebook.react.JavaScript
0   hermes                        	       0x10ab7c050 0x10ab32000 + 303184
1   hermes                        	       0x10ab79753 0x10ab32000 + 292691
2   hermes                        	       0x10ab59714 0x10ab32000 + 161556
3   hermes                        	       0x10ab58f42 0x10ab32000 + 159554
4   hermes                        	       0x10ab7a580 0x10ab32000 + 296320
5   hermes                        	       0x10ab79753 0x10ab32000 + 292691
6   hermes                        	       0x10ab59714 0x10ab32000 + 161556
7   hermes                        	       0x10ab58f42 0x10ab32000 + 159554
8   hermes                        	       0x10ab7a580 0x10ab32000 + 296320
9   hermes                        	       0x10ab79753 0x10ab32000 + 292691
10  hermes                        	       0x10ab59714 0x10ab32000 + 161556
11  hermes                        	       0x10ab57459 0x10ab32000 + 152665
12  hermes                        	       0x10abfc1cb 0x10ab32000 + 827851
13  hermes                        	       0x10ab5948e 0x10ab32000 + 160910
14  hermes                        	       0x10ab7a55d 0x10ab32000 + 296285
15  hermes                        	       0x10ab79753 0x10ab32000 + 292691
16  hermes                        	       0x10ab59714 0x10ab32000 + 161556
17  hermes                        	       0x10ab57c98 0x10ab32000 + 154776
18  hermes                        	       0x10ac49206 0x10ab32000 + 1143302
19  hermes                        	       0x10ab5948e 0x10ab32000 + 160910
20  hermes                        	       0x10ab7a55d 0x10ab32000 + 296285
21  hermes                        	       0x10ab79753 0x10ab32000 + 292691
22  hermes                        	       0x10ab59714 0x10ab32000 + 161556
23  hermes                        	       0x10ab57c98 0x10ab32000 + 154776
24  hermes                        	       0x10ac49206 0x10ab32000 + 1143302
25  hermes                        	       0x10ab5948e 0x10ab32000 + 160910
26  hermes                        	       0x10ab7a55d 0x10ab32000 + 296285
27  hermes                        	       0x10ab79753 0x10ab32000 + 292691
28  hermes                        	       0x10ab59714 0x10ab32000 + 161556
29  hermes                        	       0x10ab58f42 0x10ab32000 + 159554
30  hermes                        	       0x10ab3bbb3 0x10ab32000 + 39859
31  myApp            	       0x106542dcb facebook::jsi::RuntimeDecorator<facebook::jsi::Runtime

## Environment info

| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.70.5   |
| react-native-reanimated         | 3.0.2   |
| react-native-gesture-handler    | 2.8.0   |
(Note: I have tried various version combinations with RN-reanimated 2.x RN-gesture-handler 2.9.0 and odler/newer versions of your modal-sheet, but no solutions whatsoever)

I understand the issue might not be related directly to bottom-sheet, but it only happens while bottom-sheet modal is active and without an active device keyboard and in iOS 16.x devices, so this is why i decided to ask for your help here

## Steps To Reproduce

While a modal sheet is open in an ios 16.x device and with no device keyboard active, try to minimize the app and drag it to the background

Describe what you expected to happen:

1. Not the app to crash,  as it does not in older iOS versions tahn 16.x

Thanks a lot for your time and taking a look into this.

**Comment by NJHu** [comment]
I also have this problem, 16.x system
