### ISSUE TITLE
[v4] | [v2] snapToIndex doesn't work when BottomSheet index is set to 1

### ISSUE THREAD

**Issue by chrishiguto** [gorhom/react-native-scroll-bottom-sheet#1409]
# Bug

When you have at least two snap points and you pass the index prop to `BottomSheet` component as 1, the `snapToIndex` function doesn't work with parameter 0.

This is happening because `animatedNextPositionIndex` is actually being initialized with 0 and within `snapToIndex` function we're comparing 0 (snapToIndex parameter--where we want the bottom sheet snap to) with 0 (animatedToNextPositionIndex.value) thus early returning and not performing the animate position.

If you're is facing this issue, one workaround would be to set animateOnMount to `true`. This works because `animateOnMount` triggers `animateToPosition` which in turn triggers `animateToPositionCompleted` on complete. `animateToPositionCompleted` then resets `animatedNextPositionIndex.value` to `INITIAL_VALUE` (-Infinity).

I'll create a PR to fix this as soon as possible and I'll update this issue. Thank you!

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6  |
| react-native                    |  0.71.8  |
| react-native-reanimated         | 2.14.4 |
| react-native-gesture-handler    | 2.9.0 |

## Steps To Reproduce

1. Add a BottomSheet component to a screen using two snap points
2. Set index prop of BottomSheet to 1
3. Try calling ref.current.snapToIndex(0)
4. You should not see anything happening in the screen. The animation shouldn't trigger at all.

## Describe what you expected to happen:

1. The animation should trigger after calling snapToIndex(0)

## Reproducible sample code

```
<BottomSheet
    {other props}
    index={1}
/>

```
`ref.current.snapToIndex(0) // this wouldn't work and doesn't change the bottom sheet position.
`

**Comment by CostasCF** [comment]
Having the same issue since updating to the latest version.

Update: The suggested workaround works, however when animateOnMount is set to true, bottomSheet isn't loading at all _sometimes_, I tested on Android build.

Update 2: Apparently you need to use useMemo mentioned in #161 so bottomSheet sometimes not opening is fixed.

**Comment by thaiphan** [comment]
@chrishiguto Did you ever fix this problem?
