### ISSUE TITLE
[v4] Content flexes to the highest snap point

### ISSUE THREAD

**Issue by danieldunderfelt** [gorhom/react-native-scroll-bottom-sheet#1411]
# Bug

I expect the content of the bottom sheet to conform to the available space within the bottom sheet. This only seems to work when the sheet is at the highest snap position, otherwise the content seems to think it has more space than it really does and is hidden under the bottom edge of the screen. It seems like the available space is calculated for the highest snap point and not for the actual current snap point of the sheet.

It feels like a bug or that I am missing something obvious. My content is wrapped with a view with style `flex: 1`, otherwise it works even less.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. Add BottomSheet with two snap points, for example 40% and 80%
2. Add content wrapped with a View with style flex: 1. I have a FlatList with more items than fits in the view at any snap point. I also have stuff under the FlatList.
3. Content flexes according to the space available at the highest snap point. 

Describe what you expected to happen:

1. Content should flex to the available space at any snap point, not only the highest.

## Reproducible sample code

I couldn't get the reproduce snack to work (some weird reanimated error), but here is an image explaining the situation:

![Untitled-2023-06-23-1624](https://github.com/gorhom/react-native-bottom-sheet/assets/3145668/18d757e2-bd26-453e-ad48-bbde26e391e2)

**Comment by calebpanza** [comment]
+1

**Comment by filippobarcellos** [comment]
@danieldunderfelt  Have you managed to fix this? I have the same problem.

**Comment by danieldunderfelt** [comment]
@filippobarcellos No, I haven't. I have to use just one snap point 😂

**Comment by filippobarcellos** [comment]
@danieldunderfelt Managed to get it working with a little bit of hacking. 

AnimatedIndex keeps the updated value while snapping.

 ```
const animatedIndex = useSharedValue(0);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      height: interpolate(animatedIndex.value, [0, 1, 2], [120, 340, 590]),
    };
  });

  return (
    <GestureHandlerRootView style={{ flex: 1, backgroundColor: '#d3d3d3' }}>
      <BottomSheet
        ref={bottomSheetModalRef}
        index={1}
        snapPoints={snapPoints}
        animatedIndex={animatedIndex}
        onChange={handleSheetChanges}
        footerComponent={renderFooter}
      >
        <Animated.View style={[animatedStyle]}>
          <FlatList
            data={data}
            keyExtractor={(i) => i}
            renderItem={renderItem}
          />
        </Animated.View>
      </BottomSheet>
    </GestureHandlerRootView>
)

**Comment by calebpanza** [comment]
Would love to see this as a configurable option in the definition of the Bottom Sheet

**Comment by calebpanza** [comment]
Was finally able to get this working using the [useBottomSheetDynamicSnapPoints](https://gorhom.github.io/react-native-bottom-sheet/hooks#usebottomsheetdynamicsnappoints) hook.

```
const MyComponent = () => {
  const insets = useSafeAreaInsets();

  const bottomSheetRef = useRef();
  const initialSnapPoints = useMemo(() => ['CONTENT_HEIGHT'], []);
  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints);

  useEffect(() => {
    bottomSheetRef?.current?.present();
  }, [bottomSheetRef]);

  return (
    <BottomSheetModalProvider>
      <BottomSheetModal
        ref={bottomSheetRef}
        topInset={insets.top}
        snapPoints={animatedSnapPoints}
        handleHeight={animatedHandleHeight}
        contentHeight={animatedContentHeight}
        enableOverDrag={false}
      >
        <BottomSheetView
          onLayout={handleContentLayout}
          style={{ paddingBottom: insets.bottom + 16 }}
        >
          {/* REST OF YOUR CONTENT */}
        </BottomSheetView>
      </BottomSheetModal>
    </BottomSheetModalProvider>
  );
};
```

**Comment by calebpanza** [comment]
Gonna try to find some time to open up a PR on the docs site to add a guide for "Setting the Sheet height based on content height"

**Comment by UchennaOkafor** [comment]
@calebpanza 

Thanks, worked ✅.

**Comment by filippobarcellos** [comment]
@calebpanza What if the  "rest of your content" is a big flat last and has input, etc... I don't think in this case "CONTENT_HEIGHT" would follow the snap point desired.

**Comment by calebpanza** [comment]
So I _think_ that if the `CONTENT_HEIGHT` exceeds the height of the screen, it'll expand to 100% of the available height. though I'll admit I haven't tested this.

The use case that I was needing for my application was a bottom sheet that didn't include a list, but rather static elements to display.

In your case, are you wanting to use snap points of like `[HEIGHT_OF_TEXT_INPUT, "100%"]`?

**Comment by tastyqbit** [comment]
Any update on this? I am getting a lot of rerenders using the `animatedIndex` approach and the `useBottomSheetDynamicSnapPoints` is deprecated :/

**Comment by lauridskern** [comment]
Can we reopen this issue? Like @tastyqbit said, useBottomSheetDynamicSnapPoints is deprecated

**Comment by ReedVivid** [comment]
This is still an issue. Can this ticket be reopened?

**Comment by ayush-goyal** [comment]
+ 1 to this, having this problem as well

**Comment by n-ii-ma** [comment]
Having this problem as well.

**Comment by vileikis** [comment]
+1  this is still and issue

**Comment by rude-seagull** [comment]
+1 this is still an issue

**Comment by PetriKiviniemi** [comment]
+1 this is still an issue

**Comment by jarrodparkes** [comment]
+1 — not sure if it is fixed, but im trying to find a solution for this exact issue right now
