### ISSUE TITLE
[v4] BottomSheet didn't go back to it's initial position after close the keyboard

### ISSUE THREAD

**Issue by YuryDG** [gorhom/react-native-scroll-bottom-sheet#1417]
# Bug

When interacting with `BottomSheetTextInput` inside the `BottomSheet`, the BottomSheet changes its height when the keyboard is shown but when the keyboard is hidden, the `BottomSheet` didn't go back to its initial position. 

I guess this behavior is not the expected one, I copy-paste the example[ from the documentation](https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling) and it is not working as expected. 

Did I miss something? 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | ~2.14.4  |
| react-native-gesture-handler    | ~2.9.0   |

## Steps To Reproduce

1. Create a new app using `npx create-expo-app@latest --example with-router`
2. Copy the example  from the Documentation [Keyboard handling](https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling)
3. Interact with the `BottomSheetTextInput` 

https://github.com/gorhom/react-native-bottom-sheet/assets/8725796/f68085d2-0b0a-4084-82de-59584ce161d2

Describe what you expected to happen:

1. BottomSheet should go back to its initial position after we close the keyboard

## Reproducible sample code
I took the example from the documentation [Keyboard handling](https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling)

**Comment by YuryDG** [comment]
Hi team, 
Thanks for the awesome Job with this package

I just solved the problem. There is a property missing for the `BottomSheet` on the example  `keyboardBlurBehavior="restore" `. That is why is not working as expected. 

https://github.com/gorhom/react-native-bottom-sheet/assets/8725796/412132ed-0c3b-4751-8857-13e910ef3fb3

@gorhom I'm wondering why the default value of `keyboardBlurBehavior` prop is `none` instead of `restore`.
Is there any reason behind it? 

If it's not possible to change it to `restore`, we could add them to the examples on the documentation.
 I'm open to help 😄 

Thanks in advance

**Comment by bugra-kara** [comment]
> Hi team, Thanks for the awesome Job with this package
> 
> I just solved the problem. There is a property missing for the `BottomSheet` on the example `keyboardBlurBehavior="restore" `. That is why is not working as expected.
> 
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-06-25.at.02.18.37.mp4 
> 
> @gorhom I'm wondering why the default value of `keyboardBlurBehavior` prop is `none` instead of `restore`. Is there any reason behind it?
> 
> If it's not possible to change it to `restore`, we could add them to the examples on the documentation. I'm open to help 😄
> 
> Thanks in advance

thanks my man, it works clearly

**Comment by Ainul-Hossain** [comment]
> Hi team, Thanks for the awesome Job with this package
> 
> I just solved the problem. There is a property missing for the `BottomSheet` on the example `keyboardBlurBehavior="restore" `. That is why is not working as expected.
> 
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-06-25.at.02.18.37.mp4 
> @gorhom I'm wondering why the default value of `keyboardBlurBehavior` prop is `none` instead of `restore`. Is there any reason behind it?
> 
> If it's not possible to change it to `restore`, we could add them to the examples on the documentation. I'm open to help 😄
> 
> Thanks in advance



Great!! Thanks, man. Working fine.

**Comment by thisisomar** [comment]
Curious as to why the default is none as well, should be stated in the documentation, especially when using `keyboardBehavior="interactive"`
