### ISSUE TITLE
[v4] BottomSheetSectionList: Section header has wrong position when bottom sheet is expanded by swipe up

### ISSUE THREAD

**Issue by nihilenz** [gorhom/react-native-scroll-bottom-sheet#1424]
# Bug

Using `BottomSheetSectionList`, we noticed that the section header (maybe only the first section header?) is positioned incorrectly (covering the first line) when the bottom sheet is expanded by swipe up gesture. 
I think it only happens on iOS.

Screenshot: https://share.getcloudapp.com/YEu4QpeE

Screencast: https://share.getcloudapp.com/qGu6lKYv
At the beginning of the video, I expanded the bottom sheet by dragging the handle and the problem doesn't occur.
All the other times I swipe up the bottom sheet and the problem always happens.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.67.5   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 2.4.2   |

## Steps To Reproduce

1. Install and start the example app https://github.com/gorhom/react-native-bottom-sheet/tree/master/example/expo on an iOS device/simulator
2. Open the "SectionList" example
3. Swipe up the bottom sheet to expand it

Describe what you expected to happen:

1. The first section header above the the first section, but instead the first section header is placed further down covering the first row. 

## Reproducible sample code

https://github.com/gorhom/react-native-bottom-sheet/tree/master/example

**Comment by nihilenz** [comment]
not stale

**Comment by nihilenz** [comment]
reopen?

**Comment by vipien** [comment]
Did you manage to solve it?

**Comment by IkeyBenz** [comment]
@nihilenz I ran into this too.

I solved it by setting `stickySectionHeadersEnabled` to true only when the sheet is already opened.

```tsx
const [snapIndex, setSnapIndex] = useState(0); // mine starts out closed
return (
  <BottomSheet onChange={setSnapIndex}>
    <BottomSheetSectionList {...props} stickySectionHeadersEnabled={snapIndex === 1} />
  </BottomSheet>
);
```

In case you or someone is still dealing with this.
