### ISSUE TITLE
[v4] | [v2] Keyboard should not expand BottomSheet beyond a maximum height

### ISSUE THREAD

**Issue by slutske22** [gorhom/react-native-scroll-bottom-sheet#1430]
# Bug

This is perhaps more of a question, but maybe it is indeed a bug.  I need to be able to set a max height on the bottomsheet, especially as it relates to the keyboard.  If any input is pressed, the bottomsheet should expand to make space for the keyboard, *up until a certain max height*.  After that max height, the bottomsheet should no longer expand, but rather should allow the keyboard to slide over it.  Perhaps there is already a way to do this, but I am struggling to find it in the docs.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. Create a bottomsheet with dynamic snappoints
2.  Use a BottomSheetTextInput somewhere in the content.  Cap the content's height using its `style` property
3. Press the text input.  The keyboard will open, and the bottomsheet will open so far that you can no longer see the top

In the following example, you can see the FlatList is quite long, but because its container is capped with a maxHeight, it does not push the BottomSheet open to far, and the user can scroll within the sheet.  However, as soon as the keyboard opens, the BottomSheet opens too far

![Jul-04-2023 06-47-31](https://github.com/gorhom/react-native-bottom-sheet/assets/52637023/8940e222-d6d1-4487-b7b9-af99733be310)

Interestingly, if the size of the content is not fully rendered until the keyboard is already open, the layout is as desired.  I.e., content rendere is initially small, then keyboard opens, then more content renders while keyboard is open - this is the layout, which is the desired result:

<img width="316" alt="Screenshot 2023-07-04 at 6 57 21 AM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/52637023/3aa7fddd-30d9-45ed-a93b-be8c2922f622">

In the above image, if you blur the input (to close the keyboard), then focus it again to reopen the keyboard, the layout does not return to what you see in that image, but rather to the problematic layout shown in the gif.

Describe what you expected to happen:

1. Set a maxHeight somewhere on the bottomsheet or its children
2. Any keyboard-expanding inputs should open the keyboard.  The bottomsheet should expand, but only until it reaches the maximum set height.  Beyond that, the keyboard should slide *over* the content rather than continuous to push it up beyond the top border of the screen

Is there some way to set an "absolute max height regardless of content height. + keyboard height"?

### [Snack demonstrating the issue](https://snack.expo.dev/@slutske22/example-react-native-bottom-sheet__keyboard-issue)

(Note the standard template was throwing errors so I found another one to use)

Some quick reference for the code:

```ts
// App.tsx

import { Content } from './Content';

export default function App() {
  // use 75 as a bare minimum
  const initialSnapPoints = useMemo(() => [75, 'CONTENT_HEIGHT'], []);

  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints);

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
        <SafeAreaView
          style={[StyleSheet.absoluteFill, { backgroundColor: 'beige' }]}>
          <Text>Some content here</Text>

          <BottomSheet
            index={1}
            snapPoints={animatedSnapPoints}
            handleHeight={animatedHandleHeight}
            contentHeight={animatedContentHeight}
            keyboardBlurBehavior="restore">
            <BottomSheetView
              style={styles.container}
              onLayout={handleContentLayout}>
              <Content />
            </BottomSheetView>
          </BottomSheet>
        </SafeAreaView>
      </TouchableWithoutFeedback>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    backgroundColor: 'white',
    maxHeight: Dimensions.get('window').height - 300,  // <--- set max height of content so it won't grow too large
  },
});
```

```ts
// Content.tsx

import { useLazyEffect } from './useLazyEffect';
import data from './data';

export const Content: React.FC = () => {
  const { snapToIndex } = useBottomSheet();

  const [value, setValue] = useState('');
  const [results, setResults] = useState();

  useLazyEffect(
    () => {
      if (value) {
        setResults(data);
      }
    },
    [value],
    1000
  );

  return (
    <View
      style={{ paddingHorizontal: 20, paddingBottom: 50 }}
      onLayout={() => {
        setTimeout(() => {
          snapToIndex(1);
        }, 50);
      }}>
      <Text>Type something to render a list</Text>
      <BottomSheetTextInput
        style={{ borderColor: 'black', borderWidth: 1 }}
        value={value}
        onChangeText={(text) => setValue(text)}
      />
      {data && (
        <>
          <FlatList
            data={data}
            style={{ marginTop: 40 }}
            keyExtractor={(item) => item.id}
            renderItem={(listItem) => (
              <TouchableOpacity
                style={{
                  padding: 20,
                  borderColor: 'lightgrey',
                  borderBottomWidth: 1,
                  borderTopWidth: 1,
                }}>
                <Text>{listItem.item.name}</Text>
              </TouchableOpacity>
            )}
          />
        </>
      )}
    </View>
  );
};

```

**Comment by slutske22** [comment]
not stale

**Comment by gaiaml** [comment]
you have two props on the BottomSheetModal:

keyboardBehavior & keyboardBlurBehavior

by setting keyboardBehavior  to "extend" the sheet will be expanded to its maximum snap point

**Comment by imprisonedmind** [comment]
> you have two props on the BottomSheetModal:
> 
> keyboardBehavior & keyboardBlurBehavior
> 
> by setting keyboardBehavior to "extend" the sheet will be expanded to its maximum snap point

@gaiaml This seems to work but how would ```keyboardBlurBehavior={"restore"}``` go back to the first snap point, it seems to go back to the heighest snap point.

**Comment by slutske22** [comment]
@gaiaml I dont necesarily want the `extend` behavior.  While it works for when the content is taller than the theoretical desired `maxHeight`, it does not work when the content is smaller than that.  If its smaller, the keyboard ends up covering content that should be pushed up, because the dynamic height of the content is still less than the desired 'maxHeight'.  You can try modifying my snack to see that.  The idea is to dynamically check this, and essentially have `keyboardBehavior="extend"` behavior only when the CONTENT_HEIGHT exceeds "maxHeight".  But the transition between `keyboardBehavior="interactive" and `keyboardBehavior="extend"` should be seamless.  Perhaps there is a smart way to code this with existing props?

**Comment by Maksim-creator** [comment]
You can provide `topInset` prop to the `<BottomSheetModal>` using `useSafeAreaInsets()` hook.
I have the same problem that my modal goes under dynamic island of the phone, however I tried to give `topInset={insets.top}` and it works fine!

**Comment by Rhym** [comment]
@Maksim-creator My man!

**Comment by x43n** [comment]
> You can provide `topInset` prop to the `<BottomSheetModal>` using `useSafeAreaInsets()` hook. I have the same problem that my modal goes under dynamic island of the phone, however I tried to give `topInset={insets.top}` and it works fine!

This doesn't help if you want the user to be able to increase the size of the sheet, as you've set a hard top inset for the sheet.

**Comment by Viceclaw13** [comment]
Has anyone got a stable solution?
