### ISSUE TITLE
getRefNativeTag : RN 0.72.1 error new error

### ISSUE THREAD

**Issue by billnbell** [gorhom/react-native-scroll-bottom-sheet#1438]
# Bug

Issue on React Native 0.72.1 when using GetStream and use_framework static - throw new Error happening in `getRefNativeTag`
with `Unexpected nativeTag ...`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.72.1  |
| react-native-reanimated         | 3.3.0  |
| react-native-gesture-handler    | 2.12.0   |
| stream-chat-react-native   | 5.15.2   |

## Steps To Reproduce

1. Load app after installing getstream react native library - stream-chat-react-native v5.15.2
2. Exception is thrown in getRefNativeTag()

Describe what you expected to happen:

1. No exception.

## Reproducible sample code

Happy if you need more examples.

**Comment by dev-fredericfox** [comment]
I have the same error in every scrollable component. BottomSheetView seems to work fine.

**Comment by billnbell** [comment]
True. So I commented that code out and I am good. Throwing an exception when it works without it - maybe it should be a warning?

`@gorhom+bottom-sheet+4.4.5.patch`

```
diff --git a/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts b/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
index d4f3cc4..794a175 100644
--- a/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
+++ b/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
@@ -27,17 +27,17 @@ export function getRefNativeTag(ref: unknown) {
     nativeTag = ref.current._nativeTag;
   }
 
-  if (!nativeTag || typeof nativeTag !== 'number') {
-    throw new Error(
-      `Unexpected nativeTag: ${refType}; nativeTag=${nativeTag} 
+  // if (!nativeTag || typeof nativeTag !== 'number') {
+  //   throw new Error(
+  //     `Unexpected nativeTag: ${refType}; nativeTag=${nativeTag} 
 
-			createBottomSheetScrollableComponent's ScrollableComponent needs to return 
-			a reference that contains a nativeTag to a Native HostComponent.
+	// 		createBottomSheetScrollableComponent's ScrollableComponent needs to return 
+	// 		a reference that contains a nativeTag to a Native HostComponent.
 
-			ref=${ref}
-			`
-    );
-  }
+	// 		ref=${ref}
+	// 		`
+  //   );
+  // }
 
   return nativeTag;
 }
```

**Comment by fgagneten** [comment]
Same issue here. It happens to me with virtualized list an a modal action sheet

**Comment by vhakulinen** [comment]
I encountered this issue when trying out the new architecture.

**Comment by jspizziri** [comment]
@gorhom this seems to be a thing. Please reopen.

**Comment by nartjie101** [comment]
I got the same issue :(

**Comment by mordonez-me** [comment]
This happens with new architecture

**Comment by keithchan-bowtie** [comment]
This happens with new architecture.
Please reopen it!

If I comment the error like @billnbell , the scrollable content won't be shown but I can see the BottomSheet attached on the screen. (using Element Inspector)

**Comment by theyanniss23002** [comment]
react-native version 0.73, bottom-sheet version 4.5.1 and the problem still remains, there is no error when opening, but if inside the bottom-sheet you do an onPress event or something like that, this error appears
<img width="537" alt="Снимок экрана 2023-12-13 в 17 28 29" src="https://github.com/gorhom/react-native-bottom-sheet/assets/57316921/c61e8242-b199-4c5d-966e-3cb4c6dc639a">
<img width="547" alt="Снимок экрана 2023-12-13 в 18 32 45" src="https://github.com/gorhom/react-native-bottom-sheet/assets/57316921/fed57d2e-106e-49eb-aabd-12f93314dfa0">

**Comment by Crhis35** [comment]
I found this partial solution:
https://gorhom.github.io/react-native-bottom-sheet/troubleshooting/#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android

Using `ScrollView` instead of `BottomSheetScrollView`
<img width="849" alt="Screenshot 2023-12-23 at 9 31 00 AM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/49347705/20bfe95f-b689-4284-93c5-19089769bc3e">

**Comment by parkwherever** [comment]
Using `ScrollView` conflicts with the resolution to dynamic sizing: https://github.com/gorhom/react-native-bottom-sheet/issues/1573

**Comment by vishalsaini26** [comment]
> I found this partial solution: https://gorhom.github.io/react-native-bottom-sheet/troubleshooting/#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android
> 
> Using `ScrollView` instead of `BottomSheetScrollView` <img alt="Screenshot 2023-12-23 at 9 31 00 AM" width="849" src="https://private-user-images.githubusercontent.com/49347705/292631110-20bfe95f-b689-4284-93c5-19089769bc3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDUwNzYsIm5iZiI6MTcwOTEwNDc3NiwicGF0aCI6Ii80OTM0NzcwNS8yOTI2MzExMTAtMjBiZmU5NWYtYjY4OS00Mjg0LTkzYzUtMTkwODk3NjliYzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA3MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMGFhZGVjNWY2ZTdlZmRmMGIyOTBmOTQ5NzNmZjM0NjlkMWM3ZmQzNDBlMDY0MTNmYzAxMzUxMjY3MTI0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gcalnbBhyGmOyeWPwSn4q49H8YsP6UoKi5vKtB_yTtQ">

That seems to solves the issue

**Comment by victorneuret** [comment]
Had a similar issue with `BottomSheetFlatList`. Replacing it by `FlatList` fixed it for me

**Comment by khushal87** [comment]
The question is: Is replacing the Flatlist of the bottom sheet with that of the gesture handler a proper solution?

@gorhom

**Comment by Nikhildotasara** [comment]
Not sure if this is correct way but Using Flatlist instead of BottomSheetFlatlist fixed the issue for me!!!
Is this proper way? 
@gorhom

**Comment by lucasahlgrenToxic** [comment]
I am experiencing the same issue with BottomSheetScrollView in the new architecture. @gorhom is there any update on this?

@gorhom/bottom-sheet | 4.6.3
react-native | 0.74.3
react-native-reanimated | 3.14.0
react-native-gesture-handler | 2.17.1

**Comment by tn531** [comment]
I'm experiencing the same problem but with GestureHandlerRootView. Can we reopen this issue?

import { GestureHandlerRootView } from "react-native-gesture-handler";

**Comment by hazemelshaterr** [comment]
ref https://github.com/gorhom/react-native-bottom-sheet/commit/b906f5e67afdb823b7c31a9a929e757fc35222a2
