### ISSUE TITLE
[v4] | [v2] Using BottomSheetFlatList with removeClippedSubviews=true will not render initially off-screen views when expanded

### ISSUE THREAD

**Issue by MichaelDanielTom** [gorhom/react-native-scroll-bottom-sheet#1442]
# Bug

[v4] | [v2] Using `BottomSheetFlatList` with `removeClippedSubviews={true}` will not render initially off-screen views when panned up with a gesture that does not start within the FlatList.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Include a `BottomSheetFlatList` with `removeClippedSubviews={true}` in a `BottomSheet` with at least the screen's height worth of content in the FlatList.
2. Start the BottomSheet out at a snap point that is low (let's say '30%')
3. Put your finger on the handle component (or any component that is not within the FlatList) and pan up.

As you pan up, more of the sheet is shown, but the list items that were not initially shown are not rendered. Note that if you pan up starting within the FlatList, the items are properly rendered as you pan. If you do pan within the FlatList after having reached a higher snap point, the missing items will immediately render. This issue does not seem to occur when `removeClippedSubviews={false}`.

## Reproducible sample code

```
    <BottomSheet
      ref={sheetRef}
      index={0}
      snapPoints={[100, 400]}
    >
        <BottomSheetFlatList
            data={data}
            renderItem={renderItem}
            removeClippedSubviews={true}
        />
    </BottomSheet>

```

**Comment by jade-h-kim** [comment]
same issue for me

**Comment by JuEunSung** [comment]
same issue
