### ISSUE TITLE
App crash with Assertion failed on new architecture in IOS.

### ISSUE THREAD

**Issue by Yagnesh7028** [gorhom/react-native-scroll-bottom-sheet#1448]
# Bug

Facing crash on IOS with below error, It not happens every time but if open and close bottomsheet approx 3 to 4 times then getting crash with below log on xcode output.
react_native_assert failure: yogaChild->getContext() == traitCast<YogaLayoutableShadowNode const *>(child.get())
Assertion failed: (yogaChild->getContext() == traitCast<YogaLayoutableShadowNode const *>(child.get())), function ensureYogaChildrenAlignment, file YogaLayoutableShadowNode.cpp, line 915.
Message from debugger: Terminated due to signal 6

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1.  Open / Close same bottom sheet view multiple times.

## Reproducible sample code

https://snack.expo.dev/tJaNBdm25

![Screenshot 2023-07-18 at 7 22 48 PM](https://github.com/gorhom/react-native-bottom-sheet/assets/17902020/619b0cf2-9a97-4525-b53d-037a35107a6e)

**Comment by cepintos** [comment]
The same is happening to me, however, this seems more related to Reanimated 3.3.0

**Comment by Yagnesh7028** [comment]
@burzacoding , you got anything related to this?

**Comment by meghvarse** [comment]
> @burzacoding , you got anything related to this?

@burzacoding Not yet.
