### ISSUE TITLE
[v4] Scrollview in bottom sheet "lags" if enableContentPanningGesture is false

### ISSUE THREAD

**Issue by fwielstra** [gorhom/react-native-scroll-bottom-sheet#1450]
# Bug

I have a bottom sheet with two snap points, one around 30% of the screen, one fullscreen (up to the title bar). I do not want the user to be able to use the handle to drag the bottom sheet between snap points, so I set `enableContentPanningGesture` and `enableHandlePanningGesture` to false, and hid the handle using `handleIndicatorStyle={{ display: "none" }}` as per [this comment](https://github.com/gorhom/react-native-bottom-sheet/issues/198#issuecomment-1316618390).

Within the bottom sheet I have a `BottomSheetScrollView` (with a sticky header, using the `stickyHeaderIndices` property). The scroll view works fine, but if I "overscroll" down, the user can scroll to another snap point or dismiss it. (dismissing it would be fine by the way).

Disabling the content panning gesture works, but it causes the scroll view to lag; it only scroll AFTER I perform a scrolling gesture, like a rubber band. Here's a screen recording of what that looks like:

https://github.com/gorhom/react-native-bottom-sheet/assets/394435/d4b386c5-6dac-4dc8-9192-1ca420deb075

Versus what it should work like (but this is with content panning gesture enabled):

https://github.com/gorhom/react-native-bottom-sheet/assets/394435/1703fc4d-2a9d-4b87-b9de-ee45b0a7c4f6

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

Example code: https://gist.github.com/fwielstra/cf65dcc838d7b41873bee4c4422d2f49

1. Press the 'long text' button; content panning is ON by default
2. Try scrolling. this works fine.
3. Press the "Toggle content panning" button
4. Try scrolling the content again. The scrolling is now janky

Describe what you expected to happen:

1. For the scrolling to be good if content panning is off.

## Reproducible sample code

https://snack.expo.dev/5igSYDjvJ

https://gist.github.com/fwielstra/cf65dcc838d7b41873bee4c4422d2f49

**Comment by CyborgCodes** [comment]
Thanks! It works for me 🚀

**Comment by garygcchiu** [comment]
Experiencing the same problem, this is not solved, and there is no workaround as far as I'm aware.

**Comment by Danu-rxone** [comment]
Experiencing the same problem

**Comment by sudhanshu-busy** [comment]
Experiencing the same problem

**Comment by sudhanshu-busy** [comment]
Try enableOverDrag={false}
