### ISSUE TITLE
[v4] Bottom sheet moves to top when keyboard opens if multiple snapPoints are set

### ISSUE THREAD

**Issue by simon-day** [gorhom/react-native-scroll-bottom-sheet#1451]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. With an Expo (SDK 48) app, used code from example in the docs and added a second `snapPoint` to the array of values: https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling
2. Run on iPhone emulator or physical iPhone
3. Tap the input.

Describe what you expected to happen:

1. Expect bottom sheet to offset the sheet by the size of the keyboard as this is the expected behaviour of interactive mode, instead it goes much higher and in some cases right to the top of the screen.
2. The keyboard dismiss behaviour also does not seem to work as expected, even when setting `keyboardBlurBehavior` to `restore`

https://github.com/gorhom/react-native-bottom-sheet/assets/46072806/381365a3-334a-4685-9706-825a9d9a8613

**Comment by bent0b0x** [comment]
I've re-opened this via https://github.com/gorhom/react-native-bottom-sheet/issues/1466, which I _think_ follows the issue template. Hopefully that one gets some traction!

**Comment by hotaryuzaki** [comment]
try using keyboardVerticalOffset in Channel props

**Comment by hotaryuzaki** [comment]
just an idea, try using keyboardVerticalOffset from react native KeyboardAvoidingView
