### ISSUE TITLE
[v4] | [v2] Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by oliviercperrier** [gorhom/react-native-scroll-bottom-sheet#1452]
# Bug

Trying to use bottom sheet in my storybook but i get the following error:

<img width="798" alt="Screenshot 2023-07-24 at 11 57 22 PM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/28421005/dec6b6b5-5550-471d-8eb7-a5d8f646e0df">

React native Gesture handler and reanimated are correctly setuped.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
    "@gorhom/bottom-sheet": "^4.4.7",
    "react-native": "^0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",

**Comment by mahshid22** [comment]
i have same problem any solution?
