### ISSUE TITLE
[v4] keyboardBehavior="interactive" does not work on Android

### ISSUE THREAD

**Issue by JayJiangCT** [gorhom/react-native-scroll-bottom-sheet#1453]
# Bug

I copied the [example code](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheettextinput) about BottomSheetTextInput and made a simple test. But I found out that "interactive" doesn't work on Android phones!

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.7   |
| react-native                    | 0.71.6   |
| react-native-reanimated         | ^3.1.0  |
| react-native-gesture-handler    | ^2.10.0 |

## Steps To Reproduce

1. Click the text input, and show the keyboard
2. The bottom sheet expands to fill the top 

https://github.com/gorhom/react-native-bottom-sheet/assets/59813406/4ec81cd3-ca06-45ba-8427-a57a8774b941

## Describe what you expected to happen:

1. I would like to offset only the height of the keyboard after I set keyboardBehavior = "interactive" 

## Reproducible sample code

`import {useCallback, useMemo, useRef} from "react";
import BottomSheet, {BottomSheetTextInput} from "@gorhom/bottom-sheet";
import {StyleSheet, Text, View} from "react-native";

export const BottomSheetScreen = () => {
    const bottomSheetRef = useRef<BottomSheet>(null);

    // variables
    const snapPoints = useMemo(() => ["25%", "30%"], []);

    // callbacks
    const handleSheetChanges = useCallback((index: number) => {
        console.log("handleSheetChanges", index);
    }, []);

    // renders
    return (
        <View style={styles.container}>
            <BottomSheet ref={bottomSheetRef} index={1} snapPoints={snapPoints} keyboardBehavior="interactive" keyboardBlurBehavior="restore" onChange={handleSheetChanges}>
                <BottomSheetTextInput style={styles.input} />
                <View style={styles.contentContainer}>
                    <Text>Awesome 🎉</Text>
                </View>
            </BottomSheet>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
        backgroundColor: "grey",
    },
    contentContainer: {
        flex: 1,
        alignItems: "center",
    },
    input: {
        marginTop: 8,
        marginBottom: 10,
        borderRadius: 10,
        fontSize: 16,
        lineHeight: 20,
        padding: 8,
        backgroundColor: "rgba(151, 151, 151, 0.25)",
    },
});
`

**Comment by HuriHuchi** [comment]
same issue

**Comment by edritech93** [comment]
same issue in the Samsung A14

**Comment by itsdiay** [comment]
Same issue, any updates on this?
