### ISSUE TITLE
[v4] BottomSheetTextInput onChangeText loop with multiline prop on IOS

### ISSUE THREAD

**Issue by Dequas** [gorhom/react-native-scroll-bottom-sheet#1454]
# Bug
When I use BottomSheetTextInput component (or directly TextInput from react-native) with multiline prop, onChangeText is called in a loop with old and new state. Only on IOS

## Environment info

Library | Version
-- | --
@gorhom/bottom-sheet | 4.4.7
react-native | 0.71.8
react-native-reanimated | 2.14.4
react-native-gesture-handler | 2.9.0
expo | 48.0.18

## Steps To Reproduce
1- Open BottomSheet Modal
2- Enter Text

https://github.com/gorhom/react-native-bottom-sheet/assets/24406360/4eac0852-4c30-471c-b380-b78c077e6418

## Describe what you expected to happen
I expect BottomSheetTextInput to work with multiline prop

## Reproducible sample code
```javascript
const [isVisible, setIsVisible] = useState(false);
    const [input, setInput] = useState('');
    const bottomSheetModalRef = useRef(null);

    useEffect(() => {
        if (isVisible) {
            bottomSheetModalRef.current.present();
        } else {
            bottomSheetModalRef.current.dismiss();
        }
    }, [isVisible]);

  return (
    <BottomSheetModalProvider>
        <View style={{justifyContent: 'center', alignItems: 'center'}}>
            <Pressable onPress={setIsVisible}>
                <Text>Open Modal</Text>
            </Pressable>

            <BottomSheetModal
                        ref={bottomSheetModalRef}
                        index={0}
                        snapPoints={['90%']}
                    >
                        <BottomSheetTextInput
                            style={{height: 100}}
                            onChangeText={setInput}
                            value={input}
                            placeholder={"placeholder"}
                            multiline
                        />
            </BottomSheetModal>
        </View>
    </BottomSheetModalProvider>
  );
```

**Comment by minh-dai** [comment]
+1
In my case: function onChangeText is not calling when i select All text and then press on Cut.

**Comment by cristiano-linvix** [comment]
Any solution?

**Comment by cristiano-linvix** [comment]
solution is here:
https://github.com/gorhom/react-native-bottom-sheet/issues/867#issuecomment-1420441709

**Comment by rsomlette** [comment]
The solutions mentioned above does offer a quick patch however it is not fixing the underlying issue.

In my case I needed to be able to control the value (edit+clear), only quick fix available is to use the `BottomSheet` instead of the `BottomSheetModal`.
Ideally it would be nice if this was fixed with a proper patch.

**Comment by pfcodes** [comment]
Bump need this fixed

**Comment by minh-dai** [comment]
use defaultValue is not correct, it must value not defaultValue

**Comment by jokerhp6789** [comment]
still have this issue with BottomSheetModal

**Comment by TaylorFoster-Informulate** [comment]
Not sure why this is closed, this breaks the entire package...

**Comment by Yusuf-Munir** [comment]
I also have this issue, thought I was going crazy and doing something wrong

**Comment by yestoall** [comment]
look like this project is abandoned

**Comment by kospaa** [comment]
Hello i still have this issue with BottomSheetModal also

**Comment by VimukthiShohan** [comment]
Any solution for this instead of using BottomSheet?

**Comment by kospaa** [comment]
@VimukthiShohan using **defaultValue** props instead of **value** on **TextInput** is working, so i did this, ref : https://github.com/gorhom/react-native-bottom-sheet/issues/1454#issuecomment-1698085166

**Comment by kospaa** [comment]
@VimukthiShohan you can apply it also to the `BottomSheetTextInput` like this :

`<BottomSheetTextInput
        defaultValue={comment} // Here use defaultValue instead of value
        multiline
        onChangeText={setComment}
        placeholder={placeholder}
        style={styles.textArea}
      />`

**Comment by HoanNguyen135** [comment]
> [@VimukthiShohan](https://github.com/VimukthiShohan) using **defaultValue** props instead of **value** on **TextInput** is working, so i did this, ref : [#1454 (comment)](https://github.com/gorhom/react-native-bottom-sheet/issues/1454#issuecomment-1698085166)

 Thanks.It work for me

**Comment by afshoang** [comment]
Does anyone have a solution instead of the trick mentioned above?

**Comment by sudhanshu-busy** [comment]
no solution still
