### ISSUE TITLE
[v4] | [v2] App crashing when refreshing because of Bottom Sheet IOS

### ISSUE THREAD

**Issue by maydersonmellops** [gorhom/react-native-scroll-bottom-sheet#1464]
# Bug

App is closing on IOS when doing a full reload, when using **Bottom Sheet**, I tried several versions of Bottom Sheet and Reanimated but I get the same problem, with React Native version `0.71.7` and Reanimated `3.1.0` was working fine, but it no longer works in version `0.72.3` and **newer versions** of Reanimated.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.4.1   |
| react-native-gesture-handler    | 2.12.1   |

## Steps To Reproduce

1. Start a project with RN from scratch
2. Run app
3. Reload app

## Describe what you expected to happen:

1. After fully reloading the app, the app does not crash.
2. Work with new React Native version

## Reproducible sample code

```tsx
import React, {useCallback, useMemo, useRef} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';
import {GestureHandlerRootView} from 'react-native-gesture-handler';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <GestureHandlerRootView style={{flex: 1}}>
      <View style={styles.container}>
        <BottomSheet
          ref={bottomSheetRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}>
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheet>
      </View>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
```

**Comment by maydersonmellops** [comment]
https://github.com/gorhom/react-native-bottom-sheet/assets/129874730/c3775a9a-b836-405f-bd86-5d1c29e320a0

When run app on Xcode and apply fully reload:

![xcode-debug](https://github.com/gorhom/react-native-bottom-sheet/assets/129874730/f092d542-cc65-4f7a-875a-df16290eeb4f)

**Comment by Sup3r-Us3r** [comment]
Same issue

@gorhom is there any solution for this?

**Comment by Gustavohsdp** [comment]
@gorhom same problem here

**Comment by DaniyarJakupov** [comment]
Crash also happens (ios only) when doing a codepush update in the production app since it reloads the app in order to apply a new bundle. Would be great to at least get a workaround or a patch
cc @gorhom

**Comment by leymytel** [comment]
My workaround to the codepush/eas update issue is to unmount the whole React tree while updating. 

I added a provider that wraps the whole app, and when the user taps on the "reload" banner I display the "Updating the app"  screen.

```
    <OverTheAirUpdatesContext.Provider value={providerValue}>
      {isUpdating ? <Loading text="Updating the app" /> : children}
    </OverTheAirUpdatesContext.Provider>
```

**Comment by yashpadiaGEP** [comment]
For Codedpush reload issue, realm was responsible in my case. And the solution mentioned in the below issue, helped me fixed the crash.
https://github.com/microsoft/react-native-code-push/issues/2179

**Comment by csasiyash** [comment]
For Codedpush reload issue, realm was responsible in my case. And the solution mentioned in the below issue, helped me fix the crash. 
microsoft/react-native-code-push#2179

**Comment by maydersonmellops** [comment]
> For Codedpush reload issue, realm was responsible in my case. And the solution mentioned in the below issue, helped me fixed the crash. [microsoft/react-native-code-push#2179](https://github.com/microsoft/react-native-code-push/issues/2179)

Yes, I applied that solution, but it is something temporary, because that treatment is very bad.

**Comment by Saad-Bashar** [comment]
Did anyone find anything? I tried to use https://github.com/software-mansion/react-native-reanimated/issues/4783#issuecomment-1713329472, but it did not work. The only place that I am using reanimated is with the bottom sheet.

**Comment by valeshgopal** [comment]
Facing same issue in android

**Comment by cnlkkrb** [comment]
I'm getting the same error. Is there any solution? When I refresh my application on the first page of the bottom sheet, it crashes.

**Comment by Javakian12** [comment]
Not sure if anyone is still encountering this issue, but it randomly started to happen to me. To get around it, I put the bottom sheet in a temporary state and use that in the return () field to prevent the bottom sheet from re-rendering on every cycle. See the code:

```
import BottomSheet, {
  BottomSheetView,
  BottomSheetBackdropProps,
} from "@gorhom/bottom-sheet";

  ...
  const mainState = useState(Object);
  const [, setState, stateRef] = useState<any>(mainState);
  ...

  useEffect(() => {
    setState((p: any) => ({
      ...p,
      bottomSheet: (
        <BottomNavigation
          sheetRef={bottomSheetRef}
          contentContainerStyle={styles.contentContainer}
          sheetKey={`store-edit-save-bottom-navigation-sheet-${current_user_id || "default"}`}
        >
         ...
        </BottomNavigation>
    }))
  },[])

return (
<View>
  {stateRef.current.bottomSheet}
</View>
)
```

This may be a little messy, but what I observed is that the bottom sheet crashes on refresh because it is rendering too much? Again, I could be completely wrong as I am not too sure how the sheet unmounts, but I noticed a lot more consistent behavior with the component when storing it in a state and preventing unnecessary re-renders.
