### ISSUE TITLE
[v4] | Bottom sheet moves to top when keyboard opens if multiple snapPoints are set

### ISSUE THREAD

**Issue by bent0b0x** [gorhom/react-native-scroll-bottom-sheet#1466]
# Bug

Given a bottom sheet a text input, multiple snap points, and `keyboardBehavior="interactive"`, opening up the keyboard always extends the sheet to the highest snap point, even if there is room to keep the sheet at a lower snap point even with the keyboard visible. 

| Demo |
| --- |
| <img src="https://github.com/gorhom/react-native-bottom-sheet/assets/7697924/5549db8c-e694-4d65-99aa-e7a45d864dab" width="250"> |

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.69.8  |
| react-native-reanimated         | 2.10.0   |
| react-native-gesture-handler    | 2.6.0   |

## Steps To Reproduce

1. press to focus the text input in the bottom sheet so that the keyboard appears

Describe what you expected to happen:

1. the keyboard pushes the bottom sheet upwards, but does not cause the sheet to expand in height and move to the highest snap point

## Reproducible sample code

```tsx
import React, { useMemo } from "react";
import { View, StyleSheet } from "react-native";
import BottomSheet, { BottomSheetTextInput } from "@gorhom/bottom-sheet";

const App = () => {
  // variables
  // adding 100% to the array below is the only change to made to the sample code on the website
  // https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling
  const snapPoints = useMemo(() => ["25%", "100%",], []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet snapPoints={snapPoints}>
        <View style={styles.contentContainer}>
          <BottomSheetTextInput value="Awesome 🎉" style={styles.textInput} />
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: "grey",
  },
  textInput: {
    alignSelf: "stretch",
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "grey",
    color: "white",
    textAlign: "center",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
  },
});

export default App;
```

**Comment by audn** [comment]
Did you find a workaround for this @bent0b0x?

### Edit
Solved it by removing `keyboardBehavior="fillParent"`prop on `<BottomSheetModal>`

**Comment by bent0b0x** [comment]
> Did you find a workaround for this @bent0b0x?
> 
> ### Edit
> Solved it by removing `keyboardBehavior="fillParent"`prop on `<BottomSheetModal>`

I have not yet found a workaround. As for removing that prop, in my example above I am not specifying that keyboard behavior and am instead falling back to the default, which I believe is `interactive`

**Comment by ChristopherBanas** [comment]
+1

**Comment by ChristopherBanas** [comment]
Think these issues are the same https://github.com/gorhom/react-native-bottom-sheet/issues/1430

**Comment by vinters768** [comment]
Experiencing same issue.

**Comment by ChristopherBanas** [comment]
Not stale

**Comment by atdyer** [comment]
I'm having this same issue. The functionality I'm looking for is to have, e.g., three snapPoints and for the current snap index to remain unchanged when the keyboard opens. So if the user is at the first snap point and opens the keyboard, they can still swipe up twice to expand the sheet through two more points. The current behavior of 'interactive' forces the sheet to the highest snap point.

**Comment by ChristopherBanas** [comment]
Bump

**Comment by calebpanza** [comment]
In a similar boat and would love to know if anyone has a solution!

**Comment by ChristopherBanas** [comment]
Not stale

**Comment by gorhom** [comment]
@bent0b0x the `interactive` mode will use the bottom sheet highest point as the height of the bottom sheet, then it will offset the keyboard height from it.

now what you are asking for a new mode which to snap to a custom snap point instead of the highest point, something related to this feature request https://github.com/gorhom/react-native-bottom-sheet/issues/1648

**Comment by nathMoni** [comment]
not stale

**Comment by fgauna12** [comment]
This is happening to me :-(

**Comment by alikhan866** [comment]
not stale

**Comment by Aklile-Yilma** [comment]
not stale

**Comment by ChenBri** [comment]
I found a fix for now,
Set `android_keyboardInputMode`to `adjustResize`.
`android_keyboardInputMode='adjustResize'`

**Comment by leostark221** [comment]
@ChenBri  Chad, I've been at it for hours couldnt find a solution . Thanks buddy this fixed it for me.
