### ISSUE TITLE
[v4] | Style doesn't apply to BottomSheetBackdrop when using  with BottomSheetModal

### ISSUE THREAD

**Issue by Roka20012** [gorhom/react-native-scroll-bottom-sheet#1468]
# Bug
Style doesn't apply to `BottomSheetBackdrop`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

Pass empty style object to `BottomSheetBackdrop` and it will start lagging

```jsx
<BottomSheetModalProvider>
    <AppNavigator />
</BottomSheetModalProvider>

<BottomSheetBackdrop
    appearsOnIndex={0}
    disappearsOnIndex={-1}
    style={{}}
/>
```

1.  Just use `BottomSheetModalProvider` in App.ts to wrap AppNavigator
2. Start using the default library component
3. 

Describe what you expected to happen:

1. Component should apply style such as a background color change

## Reproducible sample code

# How it should be
https://github.com/gorhom/react-native-bottom-sheet/assets/32239452/35978448-8ac6-43cc-b573-115112d9864e

# How it is right now
https://github.com/gorhom/react-native-bottom-sheet/assets/32239452/6e87734e-a6b2-4c61-bd01-7fd5805b35a4

Can't run snack to provide a working example

Similar issue https://github.com/gorhom/react-native-bottom-sheet/issues/1348#issue-1670395880

**Comment by ACHP** [comment]
I managed to bypass this error by providing this style to the `BottomSheetBackdrop`
```tsx
style={{
   position: 'absolute',
   top: 0,
   left: 0,
   width: '100%',
   height: '100%',
   /* ... And anything else you want here */
   backgroundColor: 'red',
}}
```

Not the perfect solution, but it works for now, I'll try to see if I can find the real cause of this and maybe submit a PR

**Comment by Roka20012** [comment]
@ACHP Nope it doesn't help, are you sure you were using it with `BottomSheetModal` ?

**Comment by ACHP** [comment]
Yes I use BottomSheetModal but it might be a totally different problem, do you confirm that removing the `style={{}}` props works ?  

# Before

<img width="505" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/9294168/51e30896-9d30-4a7c-bf5b-a5dbe09c2e9d">

# After

<img width="400" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/9294168/22134cbc-2bf9-406a-aafa-96783a51f7cb">

**Comment by Roka20012** [comment]
@ACHP yes if you remove style property it works as I showed in video

**Comment by Roka20012** [comment]
@ACHP Ohhh I restarted the project I checked your solution again right now, and it works as needed 👍

It's a temporary solution but it works for now

Thanks!
