### ISSUE TITLE
[v4] | Present modal at a specific snap point

### ISSUE THREAD

**Issue by JulesVision** [gorhom/react-native-scroll-bottom-sheet#1469]
# Bug

I currently try to present a BottomSheetModal at its second snap point but I don't find a solution to do that.

I tried to use `present` and `expand` at the same time but it's don't work. 

Did you have any solution to do that ?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.71.8   |
| react-native-reanimated         | ~2.14.4   |
| react-native-gesture-handler    | ~2.9.0   |

**Comment by raif-ar** [comment]
A workaround for this is to wait for the bottom sheet to mount before doing the expand. Here is a sample -

`
    bottomSheetRef.current.present()
    setTimeout(() => {
      bottomSheetRef.current.expand()
    }, 200)
`

This works for me

**Comment by brandedcow** [comment]
Closed issue, but wanted to mention that setting the `index` prop on the `BottomSheetModal` works to solve this issue.
