### ISSUE TITLE
[v4] How to remove tiny line between main section and top handle section containers ?  

### ISSUE THREAD

**Issue by iArchin** [gorhom/react-native-scroll-bottom-sheet#1474]
I used linear gradient inside the main container of the bottom sheet and also i changed the background color of the top section by setting a background color in `handleStyle` prop.  but there is a tiny line between these 2 that I can not get rid of. i tried to set a border bottom color as same as my background color but doesn't work. any work around for these issue ?

here is the image of these line (sorry to hurt your eyes, it's really tiny)
https://ibb.co/JBQyg0Z

**Comment by consuelo-sanna** [comment]
Have you tried setting the border width to 0 or removing it?
In my case the handle component had a border bottom, so setting in the style borderBottomWidth: 0 removed it
