### ISSUE TITLE
[v4] How can I remove this tiny line between main section and top section ? 

### ISSUE THREAD

**Issue by iArchin** [gorhom/react-native-scroll-bottom-sheet#1476]
# Bug

I used linear gradient inside the main container of the bottom sheet and also i changed the background color of the top section by setting a background color in handleStyle prop. but there is a tiny line between these 2 that I can not get rid of. i tried to set a border bottom color as same as my background color but doesn't work. any work around for these issue ?

here is the image of these line (sorry to hurt your eyes, it's really tiny)
https://ibb.co/JBQyg0Z

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0   |
| react-native                    | 0.72.0   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.10.2   |

## Steps To Reproduce

```
<BottomSheetModal
      ref={bottomSheetModalRef}
      index={0}
      snapPoints={snapPoints}
      keyboardBlurBehavior="restore"
      backdropComponent={renderBackdrop}
      enablePanDownToClose={panDownToClose}
      handleIndicatorStyle={{display: 'none'}}
      handleStyle={{
        backgroundColor: '#EFE9EF',
      }}
      style={{
        borderRadius: 30,
        overflow: 'hidden',
      }}>{...}</BottomSheetModal>
```

1. just set background color to component inside the bottom sheet modal and handleStyle.
 

Describe what you expected to happen:

1. I expect to remove the line

## Reproducible sample code

I provide it above

**Comment by samourai** [comment]
hello,

any fix for that?

**Comment by iArchin** [comment]
@samourai no unfortunately it has been closed without anything...

**Comment by soonoo** [comment]
https://github.com/gorhom/react-native-bottom-sheet/issues/159

**Comment by soonoo** [comment]
https://github.com/gorhom/react-native-bottom-sheet/issues/159#issuecomment-755660887
