### ISSUE TITLE
[v4] | [v2] TS Type error with useBottomSheetDynamicSnapPoints

### ISSUE THREAD

**Issue by nicolascavallin** [gorhom/react-native-scroll-bottom-sheet#1478]
# Bug

Jumping from Reanimated v3.3.0 to v.3.4.2 the `animatedSnapPoints` from `useBottomSheetDynamicSnapPoints` is now of type `Readonly (string | number)[]` and is not compatible with the `snapPoints` prop in the `BottomSheet` component.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.72.3  |
| react-native-reanimated         | 3.4.2   |
| react-native-gesture-handler    | 2.12.1  |

## Steps To Reproduce

There are no specific steps, just upgrade the **Reanimated** library to its last version.

Describe what you expected to happen:

Avoid TS error.

## Reproducible sample code

Is not necessary a sample code to reproduce it.

**Comment by mehmetdemiray** [comment]
`snapPoints={animatedSnapPoints as (string | number)[] | SharedValue<(string | number)[]>}`

Just to remove ts error :)

**Comment by Eli-Nathan** [comment]
> snapPoints={animatedSnapPoints as (string | number)[] | SharedValue<(string | number)[]>}

Or even just `snapPoints={animatedSnapPoints as string[]}` if all you want is to remove the TS error until this issue is fixed
