### ISSUE TITLE
[v4] keep modal height when focus input android?

### ISSUE THREAD

**Issue by Shiro1995** [gorhom/react-native-scroll-bottom-sheet#1482]
# Bug

## Describe the bug
Hi, I'm coding comment section like tiktok. I'd like to keep modal height when focus textinput. Is there any solution? 

## Reproduce
![2023-08-16 11 59 52](https://github.com/gorhom/react-native-bottom-sheet/assets/47969555/14a9f0bc-fc3c-4011-a41d-d4d6448c1f87)

## Dependencies

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | v.4.x   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.11.0   |
| react-native-gesture-handler    | 2.12.1   |

**Comment by Emin91** [comment]
I spent 5 hours trying to fix this bug. To do this, you need to install the `rn-android-keyboard-adjust` package. And as soon as the bottom sheet opens, you need to call the `setAdjustPan()`(or another suitable) method and when closing `setAdjustResize()` (or whatever is written in your manifest.xml). 
I hope this helps you.

**Comment by Shiro1995** [comment]
> 

So we have to change the adjust type dynamically? I didn't see anyone can do it.
Other screens in my app need to use adjustSize already. Could you share the solution more clearly?

**Comment by Shiro1995** [comment]
> I spent 5 hours trying to fix this bug. To do this, you need to install the `rn-android-keyboard-adjust` package. And as soon as the bottom sheet opens, you need to call the `setAdjustPan()`(or another suitable) method and when closing `setAdjustResize()` (or whatever is written in your manifest.xml). I hope this helps you.

So we have to change the adjust type dynamically? I didn't see anyone can do it.
Other screens in my app need to use adjustSize already. Could you share the solution more clearly?
