### ISSUE TITLE
[v4.4.5] Updating the <BottomSheetView> causing handleComponent to re-render

### ISSUE THREAD

**Issue by bhupendra1011** [gorhom/react-native-scroll-bottom-sheet#1485]
# Bug

I am overriding the **handleComponent** of Action Sheet to a custom header, but every time <**BottomSheetView**> is getting updated , it's causing the `handleComponent` to re-render which messes up the state of the custom header. I have tried preventing it by wrapping the **handleComponent** inside React.memo, but it's still not working.

 
```
<BottomSheetModalProvider>
<BottomSheetModal
        snapPoints={['100%']}
        ref={transcriptSheetRef}
        name="TranscriptSheet"
        onDismiss={onTranscriptDismiss}
        style={styles.container}
        backgroundStyle={styles.backgroundStyle}
        handleIndicatorStyle={styles.handleIndicatorStyle}
        enableContentPanningGesture={false}
        handleComponent={React.memo(() => (
          <ActionSheetHandle sidePanel={SidePanelType.Transcript} />
        ))}
        stackBehavior="push">
        <BottomSheetView>
          <Transcript showHeader={false} />
        </BottomSheetView>
   </BottomSheetModal>
<BottomSheetModalProvider>
```
```
const ActionSheetHandle = (props: {sidePanel: SidePanelType}) => {
  const Header = null;

  const {sidePanel} = props;
  console.warn('Handle Comp Re-render');
  return (
    <View style={styles.container}>
      <View style={styles.handleIndicatorStyle} />

      {sidePanel === SidePanelType.Participants && <PeopleHeader />}
      {sidePanel === SidePanelType.Chat && <ChatHeader />}
      {sidePanel === SidePanelType.Settings && <SettingsHeader />}
      {sidePanel === SidePanelType.Transcript && <TranscriptHeader />}
    </View>
  );
```

Is there a way to prevent the re-render of handleCompnent.
Thanks.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5 |
| react-native                    | .64  |
| react-native-reanimated         | 2.12.0  |
| react-native-gesture-handler    | 2.8.0   |

## Steps To Reproduce

1.
2.
3. 

Describe what you expected to happen:

1.
2.

**Comment by joakimgy** [comment]
This still seems to be a problem

**Comment by minikN** [comment]
I'm also having this problem. In my case the handle component gets completely unmounted and remounted.
