### ISSUE TITLE
[v4] Bottom sheet doesnt close when route was changed.

### ISSUE THREAD

**Issue by igorbojk** [gorhom/react-native-scroll-bottom-sheet#1489]
# Bug

If you go to another page with an open the bottom sheet and return back, then the bottom sheet remains open.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Open the bottom sheet
2. Change the route (go to another page)
3. Go back
4. Bottom sheet still opened

Describe what you expected to happen:

1. The bottom sheet will be closed after page was changed

## Reproducible sample code
```
import React, { PropsWithChildren, useImperativeHandle, useRef, useState, useEffect } from 'react';
import { Platform } from 'react-native';
import BottomSheet, { BottomSheetProps } from '@gorhom/bottom-sheet';
import styled, { useTheme } from 'styled-components/native';

import { AppButton } from '@/components/AppButton';

import { AppMaybeWebContainer } from './AppLayout/AppMaybeWebContainer';

interface Props extends BottomSheetProps {
  withCloseButton?: boolean;
}

interface Ref {
  open?(): void;
  close?(): void;
}

const SContainer = styled.View`
  padding: 8px 16px 16px;
`;

const SCloseButton = styled(AppButton)`
  margin-top: 8px;
  margin-bottom: 16px;
  background-color: transparent;
  border: none;
`;

export const AppBottomSheet = React.forwardRef<Ref, PropsWithChildren<Props>>(({ withCloseButton, ...props }, ref) => {
  const theme = useTheme();
  const [closed, setClosed] = useState(true);

  const bottomSheetRef = useRef<BottomSheet>(null);

  useImperativeHandle(ref, () => ({
    open: () => {
      bottomSheetRef?.current?.expand();
      setClosed(false);
    },
    close: () => {
      close();
    }
  }));

  const close = () => {
    bottomSheetRef?.current?.close();
    setClosed(true);
  };

  return (
    <BottomSheet
      index={-1}
      enableOverDrag={Platform.OS !== 'web'}
      enablePanDownToClose={Platform.OS !== 'web'}
      onClose={() => {
        setClosed(true);
      }}
      ref={bottomSheetRef}
      handleIndicatorStyle={{ backgroundColor: theme.app.dividerColor, width: 56 }}
      handleStyle={{
        shadowColor: closed ? 'transparent' : '#0A1E330F',
        shadowOffset: { width: 4, height: -4 },
        shadowRadius: 4,
        shadowOpacity: 1,
        borderTopLeftRadius: 24,
        borderTopEndRadius: 24,
        borderTopWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderTopColor: theme.app.tileBorderColor,
        borderLeftColor: theme.app.tileBorderColor,
        borderRightColor: theme.app.tileBorderColor,
        backgroundColor: theme.app.tileBackground
      }}
      backgroundStyle={{ backgroundColor: theme.app.tileBackground }}
      {...props}
    >
      <AppMaybeWebContainer>
        <SContainer>
          {props.children}

          {withCloseButton && <SCloseButton fullwidth icon="x-small" role="secondary-light" onPress={close} />}
        </SContainer>
      </AppMaybeWebContainer>
    </BottomSheet>
  );
});
```

I know about solution with timeout.
```  useFocusEffect(
     useCallback(() => {
       setTimeout(() => {
         bottomSheetRef?.current?.close();
       }, 50);
     }, [])
   );
   ```
 But, maybe we can fix it without this hack?

**Comment by gaiaml** [comment]
facing the same issue:

` const navigateToEditProfile = () => {
        bottomSheetRef.current?.close();
        router.replace("/profile/editProfile")
    }`

**Comment by mskitcompl** [comment]
Have the same issue, did you find any solution to that, especially that my project is with expo and hard to implement some pure RN

**Comment by igorbojk** [comment]
@mskitcompl 
I fixed it in a very interesting way. Just call the component rerender when the route changes;

```

  const navigation = useNavigation();
  const { index } = navigation.getState();

<BottomSheet
      key={index}
      ....
      
```

In this case after route changing you will rerender your bottom sheet and it will be hidden by default

**Comment by mskitcompl** [comment]
@igorbojk  Thank you, unfortunately that not works for me in Expo SDK49

**Comment by mskitcompl** [comment]
Okay, I manage to use TouchableOpacity with a kind of solution from @gaiaml but instead of replacing I did use push from expo router etc.

In this example each time you have to create a const for each link 

`    const navigateToProfile = () => { bottomSheetModalRef.current?.close(); router.push("/page") }`

But it will work with Expo Router V2 will allow with "go back" on the destination page, and will close the bottom sheet

**Comment by rekodehub** [comment]
If you are using expo 49. You can easily clear the modal once a user leaves the screen.
````
import { useNavigation } from "expo-router";
const navigation = useNavigation();
useEffect(() => {
    const unsubscribe = navigation.addListener("blur", (e) => {
      bottomSheetModalRef.current?.close()
    });

    return unsubscribe;
  }, [navigation]);
````

**Comment by mskitcompl** [comment]
@rekodehub Thank you! That did work out!

**Comment by saver711** [comment]
same issue

**Comment by RodrigoAngeloValentini** [comment]
I found this solution:

const isFocused = useIsFocused();

<BottomSheet
      ref={bottomSheetRef}
      key={isFocused}
      {...props}
>
