### ISSUE TITLE
[v4] | [v2] ScrollToIndex doesn't seem to work for Flatlist inside the bottom sheet 

### ISSUE THREAD

**Issue by AntonioA-D-C** [gorhom/react-native-scroll-bottom-sheet#1491]
# Bug

I've been trying to use a flatlist inside Gorhom bottom sheet and it doesn't work as expected, it doesn't automatically scroll to the desired index at all.

I'm using a method that uses scrollToIndex() in a way that it can scroll to the index regardless of the element's height using the scrollToIndex and scrollToIndex flatlist props
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.7  |
| react-native                    | 0.72.3 |
| react-native-reanimated         | ^3.4.1  |
| react-native-gesture-handler    | ^2.12.1 |

## Steps To Reproduce

How to reproduce:
1. Create a bottom sheet inside a container with a  Flatlist component, custom or not
2. Send data to the flatlist so it can render more items
3. When you use a custom or normal flatlist component, pass data to the render method.
4. Implement scrollToIndex and scrollToIndexFailed, this is not the typical way of using scrollToIndex, and instead works with flatlist elements that have variable sizes, but it has worked for me before
5. Use "useEffect" to activate the "scrollToIndex" function

Describe what you expected to happen:

1. I expected the flatlist to work normally and be affected by scroll to Index, sending me to the 20th index, instead, it doesn't work at all
2. I expected the "scrollToIndexFailed" function to be able to resolve this issue, however, only "Failed" gets logged into the console

## Reproducible sample code
```
{
<BottomSheet 
      
      ref={bottomSheetRef}
      index={1}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      
          >
     
 
        <BottomSheetScrollView style={style.bottomSheetView}>
         
          { (data && !isRefetching && !isLoading) ? <FlatcardList data={data} /> : <ActivityIndicator size="large"/>}
           </BottomSheetScrollView>
            
          </BottomSheet>
}
```

```
function FlatcardList({data, userLocation, navigation, onPress, scrollToId}){
 
 navigation = useNavigation()
      const flatListRef = useRef(null);
  

     function scrollToIndex(){
      console.log("Hello")
      flatListRef?.current?.scrollToIndex({ animated: true, index: 20, viewPosition: 0.5})
   }
   
   function scrollToIndexFailed(error){
    console.log("Failed")
      const offset = error.averageItemLength*error.index;
      flatListRef?.current?.scrollToOffset({offset})
      setTimeout(()=>flatListRef?.current?.scrollToIndex({index: error.index}), 100);
   }
     
  

   useEffect(()=>{
      scrollToIndex();
   }, [data])
  
   
    function renderItem(itemData){
     

        return (
        <FlatcardElement onPress={onPress} data= {itemData.item} />
        )
    
      }
   if(data){
    return(
 
     <FlatList style={{flex:1}}
        data={data}
        keyExtractor={(item) => item.id}
        nestedScrollEnabled
        renderItem={renderItem}
        ref={flatListRef}
       scrollToIndex ={scrollToIndex({index:7})} //you can delete scroll to index in this line, I just put it thinking it would help
        onScrollToIndexFailed={scrollToIndexFailed}
      
        />
    
    )
   }
   return <Text style={styles.addressText}>No hay solicitudes actualmente, empieza creando una nueva solicitud!</Text>
  
}

export default FlatcardList
```

**Comment by JamesHemery** [comment]
Works well with [@shopify/flash-list](https://shopify.github.io/flash-list) :)

**Comment by AntonioA-D-C** [comment]
> Works well with [@shopify/flash-list](https://shopify.github.io/flash-list) :)

Doesn't that only work with hard coded width and height values?

**Comment by JamesHemery** [comment]
> > Works well with [@shopify/flash-list](https://shopify.github.io/flash-list) :)
> 
> Doesn't that only work with hard coded width and height values?

What do you mean by hard-coded height/width? You need to define la props estimatedItemSize

**Comment by AntonioA-D-C** [comment]
> > > Works well with [@shopify/flash-list](https://shopify.github.io/flash-list) :)
> > 
> > 
> > Doesn't that only work with hard coded width and height values?
> 
> What do you mean by hard-coded height/width? You need to define la props estimatedItemSize

Hard coded height and width for the flatlist itself not for the items, or to be more specific, the flatlist's container, in my case it's a bottom sheet that only covers half the screen ("50%"), the width also has to be hard coded.

Otherwise I get

`"FlashList's rendered size is not usable. Either the height or width is too small (<2px). Please make sure that the parent view of the list has a valid size. FlashList will match the size of the parent. "`

**Comment by JamesHemery** [comment]
This code works on my side : 

```tsx
import { ScrollView } from 'react-native-gesture-handler';

<BottomSheetModal
        ref={bottomSheetModalRef}
        style={styles.contentContainer}
        index={0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <FlashList
          initialScrollIndex={10}
          renderItem={({ item }: { item }) => {
            return <View style={{ height: 48, backgroundColor: 'red'}}/>;
          }}
          renderScrollComponent={ScrollView}
          keyExtractor={(item) => item.id}
          estimatedItemSize={48}
          data={items}
          contentContainerStyle={tw`pb-4`}
        />
      </BottomSheetModal>
```

⚠️ `renderScrollComponent={ScrollView}`  is needed with Bottom Sheet (ScrollView from `react-native-gesture-handler`)

**Comment by AntonioA-D-C** [comment]
> ```tsx
> <BottomSheetModal
        ref={bottomSheetModalRef}
        style={styles.contentContainer}
        index={0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
> ```

What style do you have on styles.contentContainer?

**Comment by JamesHemery** [comment]
> > ```tsx
> > <BottomSheetModal
> > ```
> 
> ```
>     ref={bottomSheetModalRef}
>     style={styles.contentContainer}
>     index={0}
>     snapPoints={snapPoints}
>     onChange={handleSheetChanges}
>   >
> ```
> 
> > 
> 
> What style do you have on styles.contentContainer?

Nothing important, juste boxShadow for bottom sheet

**Comment by AntonioA-D-C** [comment]
> > > ```tsx
> > > <BottomSheetModal
> > > ```
> > 
> > 
> > ```
> >     ref={bottomSheetModalRef}
> >     style={styles.contentContainer}
> >     index={0}
> >     snapPoints={snapPoints}
> >     onChange={handleSheetChanges}
> >   >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 
> > 
> > 
> > What style do you have on styles.contentContainer?
> 
> Nothing important, juste boxShadow for bottom sheet

Yeah it's working for me now, thank you, I had the Flashlist inside a BottomSheetScrollView, I removed it, that's the reason it wasn't working

As of now it works but I see the flashlist struggles to scroll to elements that are deeper in the list, probably due to the LazyLoad.
