### ISSUE TITLE
[v4] BottomSheetTextInput inside BottomSheetFooter keeps re-rendering, doesn't retain input value

### ISSUE THREAD

**Issue by plindsay** [gorhom/react-native-scroll-bottom-sheet#1494]
# Bug

I am using a `BottomSheetModal` with a `footerComponent` to render a text input at the bottom of the sheet. It seems to render okay but when you add text into the `BottomSheetTextInput` it doesn't retain the input value. It should set the state of the `commentText` but it keeps being erased and the keyboard loses focus on each keystroke. I suspect this is because the component keeps re-rendering but I can't figure out how to resolve this. Are there any guidelines for using this pattern? 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.70.8   |
| react-native-reanimated         | 3.2.0   |
| react-native-gesture-handler    | 2.9.0  |

## Steps To Reproduce

This is my custom footer method which I reference in the `footerComponent` prop on `BottomSheetModal` -

```
const [commentText, setCommentText] = useState('');

const renderActivePostSheetFooter = useCallback(props => (
        <BottomSheetFooter {...props}>
            <View style={styles.footerContainer}>
                <HStack alignItems="center">
                    <BottomSheetTextInput 
                        placeholder="Add your comments" 
                        style={styles.bottomSheetInput}
                        ref={activePostSheetInput}
                        onChangeText={setCommentText}
                        value={commentText}
                    />
                    <Button onPress={addComment}>Post</Button>
                </HStack>
            </View>
        </BottomSheetFooter>
 ), []);

```
Describe what you expected to happen:

1. Typing into the `BottomSheetTextInput` correctly sets the state of `commentText`.

## Reproducible sample code

[](https://snack.expo.dev/2BcvtOebu)

**Comment by erlanz** [comment]
I have the same problem

**Comment by keeslinp** [comment]
I have seen the same thing with having a text input inside of the `handleComponent`

**Comment by omarabualhija** [comment]
same problem ,any update

**Comment by omarabualhija** [comment]
you must add the dependencies to  callback Function to allow the footer to reRender when happen any update  


code :
    let [locationName, setLocationName] = useState<string>("")



    const renderFooter = useCallback(
      (props: any) => (
        <BottomSheetFooter {...props} bottomInset={0}>
 
    <Pressable.     onPress={() => {
                ///updated value
                console.log(locationName);
           />
        </BottomSheetFooter>
      ),
      [locationName],
    );




       <BottomSheet
       ///....your props 
            footerComponent={renderFooter}

          >
              <TextInput 
    
                value={locationInfo}
                placeholder=""
                title="Yourlocation"
                onChangeText={txt => setLocationName(txt)}
              />

          </BottomSheet>

**Comment by plindsay** [comment]
Thanks @omarabualhija though this doesn't seem to work for me - I have a BottomSheetTextInput inside my renderFooter function though, which is different to your example. I need to have the input pinned to the foot of the bottom sheet e.g.

```
const renderActivePostSheetFooter = useCallback((props) => {
        return (
            <BottomSheetFooter {...props} bottomInset={0}>
                <View>
                        <BottomSheetTextInput 
                            placeholder="Add your comments" 
                            onChangeText={setCommentText}
                            value={commentText}
                            ref={bottomSheetInput}
                        />
                </View>
            </BottomSheetFooter>
        );
    }, [commentText]);
```

**Comment by omarabualhija** [comment]
well, try to log the text when change the text and check if u have the updated value ,after that try to pass call backfunction to take the value from the text input 

like this  


 
```
let onChange=(txt)=>{
//must have the updated value
console.log(txt)


 ///Save your text anywhere you like
}

const renderActivePostSheetFooter = useCallback((props) => {
        return (
            <BottomSheetFooter {...props} bottomInset={0}>
                <View>
                        <BottomSheetTextInput 
                            placeholder="Add your comments" 
                            onChangeText={onChange}
                            value={commentText}
                            ref={bottomSheetInput}
                        />
                </View>
            </BottomSheetFooter>
        );
    }, [add ur dep.]);
```
    
    
 then  if this way not works remove the callback  
    
 i hope this solution helps u

**Comment by raphaelssampaio** [comment]
I have a similar problem.. 

Every time I type a letter, the keyboard is dismissed. This happens when I add the dependency to useCallbak

**Comment by phwed** [comment]
I was facing the same problem and realized when you remove the value prop it would stop rerendering. maybe it might help someone. you could also add a ref so you clear the value on submit by using the ref


```
const [inputValue, setInputValue] = React.useState<string>('')
 const inputRef = React.useRef<typeof BottomSheetTextInput>(null)

 const handleSubmit = () => {
  alert(inputValue);
  inputRef.current?.clear();
}

const renderActivePostSheetFooter = React.useCallback((props) => {
        return (
            <BottomSheetFooter {...props} bottomInset={0}>
                <View>
                        <BottomSheetTextInput 
                            placeholder="Add your comments" 
                            onChangeText={(text) => {
                            console.log(text)
                            setInputValue(text)
                            }}
                            ref={inputRef}
                        />
                </View>
            </BottomSheetFooter>
        );
    }, [inputValue]);
```

**Comment by benjamin-luupli** [comment]
did any fix work for this issue currently facing same error

**Comment by vmseba** [comment]
Facing the same issue I was able to get around it by grabbing the text input value from `onSubmitEditing` .

```
const inputRef = useRef<typeof BottomSheetTextInput>(null);

const handleSubmit = useCallback(
    async ({ nativeEvent }) => {
      const { text } = nativeEvent;
      inputRef?.current?.clear();
    },
    [],
  );
const renderActivePostSheetFooter = useCallback((props) => {
        return (
            <BottomSheetFooter {...props} bottomInset={0}>
                <View>
                        <BottomSheetTextInput 
                            ref={inputRef}
                            returnKeyType="done"
                            placeholder="Add your comments" 
                            onSubmitEditing={handleSubmit}
                        />
                </View>
            </BottomSheetFooter>
        );
    }, [inputValue]);
```

**Comment by benjamin-luupli** [comment]
so i have a button that i will hit to submit the comment but from the look
of your code it seems when the user clicks on the return arrow it triggers
the handlesubmit function how can i modify it so that its been triggered
from a separate button, would be glad if you can reach out to me as well
via gmail ***@***.*** because i'm on the verge of finishing it up
buh this seems to block me

**Comment by vmseba** [comment]
@benjamin-luupli for a submit button you could try something like this.

```
const inputRef = useRef<typeof BottomSheetTextInput>(null);

const handleSubmit = useCallback(
    async ({ nativeEvent }) => {
      const { text } = nativeEvent;
      inputRef?.current?.clear();
      // submit comment
    },
    [],
  );
const renderActivePostSheetFooter = useCallback((props) => {
        return (
            <BottomSheetFooter {...props} bottomInset={0}>
                <View>
                        <BottomSheetTextInput 
                            ref={inputRef}
                            placeholder="Add your comments" 
                            onEndEditing={handleSubmit}
                        />
                        <Button
                              onPress={() => {
                                Keyboard.dismiss();
                              }}
                              title="Submit"
                              color="#841584"
                            />
                </View>
            </BottomSheetFooter>
        );
    }, [inputValue]);
```

**Comment by benjamin-luupli** [comment]
this is my current code when i click on the handlecreate that is supposed
to call the endpoint but the handlesubmit only get triggered when i click
on the return button not on the handlecreate function,
 const handleSubmit = useCallback(
    async ({ nativeEvent }) => {
      const { text } = nativeEvent;
      console.log('----text', text);
      inputRef?.current?.clear();
    },
    [],
  );
  const handleCreateComment = (text) => {
    console.log('-CREATE---text', text);

    let data = {
      postId: postId,
      commentText: text,
    };
    console.log("---commentdata",data)
    createComment(data, profileId);
    // setComment('');
  };
  // console.log("Comment sent:", JSON.stringify(comment_data, null, 2));
  const renderFooter = useCallback(
    props => (
      <BottomSheetFooter style={{backgroundColor: 'white'}} {...props}
bottomInset={22}>
          <View style={styles.row}>
            <View style={styles.row2}>
              <Image
                style={styles.avatar}
                source={require('../../assets/img/black-woman.png')}
              />
              {/* <View style={{flex: 1}}> */}
              <BottomSheetTextInput
              //  multiline
              ref={inputRef}
              returnKeyType="done"
              onSubmitEditing={handleSubmit}
              placeholder="Add a comment..."
                  placeholderTextColor="#94969E" style={styles.input} />

              <TouchableOpacity onPress={handleCreateComment}>
                <Image
                  style={styles.send}
                  source={require('../../assets/img/icons/Send.png')}
                />
              </TouchableOpacity>
            </View>

**Comment by bpeck81** [comment]
I'm also having this issue.

**Comment by bpeck81** [comment]
I got it. The key was to use a ref instead of state to hold the text and use "defaultValue" instead of "value" in the textInput. Here's what worked for me:


```

    const inputRef = useRef(null);
    const inputTextRef = useRef('');
    const commentInputState = useState('')
    const footerComponent = useCallback((props) => (
                <BottomSheetFooter {...props}  >
                    <View style={{  paddingHorizontal: 20, }}>
                        <SpacerComponent space='small' />
                        <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                            <BottomSheetTextInput ref={inputRef} 
                                        placeholder='Add a comment...' 
                                        style={{ flex: 1, paddingRight: 5 }} 
                                        onChangeText={(text) => { inputTextRef.current = text; console.log(text) }} 
                                        defaultValue={inputTextRef.current} />
                            <TouchableOpacity
                                onPress={() => {
                                    if (inputTextRef.current !== '') {
                                        putCommentMutation.mutate({ message: inputTextRef.current })
                                        Haptics.impactAsync()
                                        inputTextRef.current = ''
                                        inputRef?.current?.clear();
                                    }
                                }} style={{ flexDirection: 'row' }}>
                                <ComponentVerticalSpacer />
                                <SpacerComponent column space='small' />
                                <IconComponent isLoading={putCommentMutation.isLoading} isTouchable={false} disabled source={require('../../Assets/Icons/Send.png')} />
                                <SpacerComponent column space='small' />
                            </TouchableOpacity>
                        </View>
                        <SpacerComponent />
                    </View>
                </BottomSheetFooter>


            ), [])}
        >
```

**Comment by MrNapcae** [comment]
I have the same problem

**Comment by Nyomasuke** [comment]
I have the same problem.

This works for me. But I want to use state ><
https://github.com/gorhom/react-native-bottom-sheet/issues/1494#issuecomment-1842045628
