### ISSUE TITLE
[v4] [v2] BottomSheetScrollView does not scroll to bottom occasionally. 

### ISSUE THREAD

**Issue by ibraheem88** [gorhom/react-native-scroll-bottom-sheet#1496]
# Bug
BottomSheetScrollView does not scroll to end occasionally. As far as the pattern I observed it does it when you drag it up slowly to the second snapPoint and then to third, then when you scroll it, it doesn't scroll to bottom. But after mount if you drag it quickly, directly to last or third snapPoint it scrolls to bottom just fine.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.72.1   |
| react-native-reanimated         | 3.4.2   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1.A simple BottomSheet with BottomSheetScrollView inside it.
2. With static snapPoints : const snapPoints = useMemo(() => ['60%', '88%', '100%'], []); 
3. Drag the BottomSheet slowly upwards, the BottomSheetScrollView will get stuck at a certain height.

Describe what you expected to happen:

1.BottomSheetScrollView should always scroll to the bottom of the content

```
<BottomSheet
            ref={bottomSheetRef}
            snapPoints={snapPoints}
            index={0}
            handleComponent={() => null}
            onChange={handleSheetChanges}
            backgroundComponent={props => <BottomSheetBackground {...props} />}
            handleIndicatorStyle={{
                backgroundColor: 'rgba(235, 236, 240, 1)',
            }}>
            <BottomSheetScrollView
                    showsVerticalScrollIndicator={false}
                    style={{ zIndex: 1, flex: 1 }}
                >
                    <Pressable>
                        {props.children}
                    </Pressable>
                <BottomSheetScrollView>
</BottomSheet>
```

https://github.com/gorhom/react-native-bottom-sheet/assets/31616730/be9d5c85-fba3-4036-9dd8-779ef9496b98

**Comment by ibraheem88** [comment]
@gorhom Can you please have a look?

**Comment by alagh697** [comment]
I think you should add a padding bottom on the bottomSheetView. A padding bottom that match the size of the "Débloque ton offre" view.

**Comment by ibraheem88** [comment]
@alagh697 no unfortunately that doesn't help. I have tried that already with BottomSheetScrollView. Also this scrollview doesn't scroll to bottom when you drag it up slowly. Dragging up quickly, just like in the video doesn't create the bug. I think this is an issue with a reanimated component. I am not sure though

**Comment by ils-anwarshah** [comment]
I am having the same issues in Android, but it is working perfectly fine on iOS devices. Sometimes bottomSheetScrollView gets stuck and does not allow me to scroll Then I have to reload the whole application again and it works.

**Comment by ibraheem88** [comment]
@ils-anwarshah yeah this bug is only on android. But we don't have to reload the app to make it go. Just go back to the previous screen and its gone.

**Comment by ils-anwarshah** [comment]
> @ils-anwarshah yeah this bug is only on android. But we don't have to reload the app to make it go. Just go back to the previous screen and its gone.

Thanks for the reply. But this is the major bug for Android users I have created the bottom sheet at the homepage of my Application. so there is no previous screen after login to go back. once the user logs In successfully, it will land on the homepage automatically until the user logs out. that is why I need to reload the whole application. please share the solution if you find any.
![Simulator Screenshot - iPhone 13 - 2023-09-02 at 19 04 33](https://github.com/gorhom/react-native-bottom-sheet/assets/127953063/d3b11c34-4581-4801-9ea6-aa2125a075e2)

**Comment by gorhom** [comment]
@ibraheem88 @ils-anwarshah could you provide repo example using this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by ils-anwarshah** [comment]
> @ibraheem88 @ils-anwarshah could you provide repo example using this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

I have uploaded the code into this repo please check

**Comment by fjmorant** [comment]
same thing happened to me with the latest version

**Comment by ibraheem88** [comment]
@fjmorant Sadly i tried even older versions but the error was still there. Hope it gets fixed soon.

**Comment by fjmorant** [comment]
is there any clue of what might cause the issue?

**Comment by ibraheem88** [comment]
Can't seem to figure out what is causing it to get stuck at a certain height, also it is scrollable up but not down. Maybe the libraries like reanimated or gesture handler have been causing the issue.

**Comment by ibraheem88** [comment]
@gorhom can you have a look. Example has been added above.

**Comment by ils-anwarshah** [comment]
@ibraheem88  @gorhom  I think it is working fine after updating the library to the latest version..

**Comment by ibraheem88** [comment]
Issue is fixed in version 4.5.1

**Comment by petertoth-dev** [comment]
@gorhom I am experiencing this with the newest version. What could be wrong?

**Comment by Nader-CS** [comment]
yes still exist

**Comment by mariacheline** [comment]
+1

**Comment by mclrc** [comment]
Same issue, both platforms. Weirdly, a hot reload after changing a prop on the scroll view (like adding/removing flexGrow: 1, doesn't matter which) fixes it until you reopen the sheet. very strange.

**Comment by mclrc** [comment]
For anyone stumbling across this: I fixed it by removing a view with flex: 1 that was the direct descendant of the sheet and the parent of the bottomsheetscrollview, so there is nothing in between the sheet and the scroll view. I don't know what the problem was, but its' working reliably now :)

**Comment by welcometochristown** [comment]
I noticed this same behavior when using ScrollView from react-native-gesture-handler. When using BottomSheetScrollView I noticed that it wouldn't scroll to the bottom unless I disabled enableDynamicSizing and added snap points manually.

**Comment by mohanataraj** [comment]
> I noticed this same behavior when using ScrollView from react-native-gesture-handler. When using BottomSheetScrollView I noticed that it wouldn't scroll to the bottom unless I disabled enableDynamicSizing and added snap points manually.

Scrolls on ios on android sticky and no movement

**Comment by dheerajkumar003** [comment]
> For anyone stumbling across this: I fixed it by removing a view with flex: 1 that was the direct descendant of the sheet and the parent of the bottomsheetscrollview, so there is nothing in between the sheet and the scroll view. I don't know what the problem was, but its' working reliably now :)

@mclrc currently my code structure is like this 
```
<BottomSheet>
  <BottomSheetView style={{flex:1}}>
     <ScrollView>....content....</ScrollView> "from react-native-gesture-handler"
  </BottomSheetView>
</BottomSheet>
```

 If the sheet is opened add I remove the BottomSheetView then sheet scrolls to the bottom very well but when I close the sheet and try opening it again it does not even open.

**Comment by Niltonsf** [comment]
> > For anyone stumbling across this: I fixed it by removing a view with flex: 1 that was the direct descendant of the sheet and the parent of the bottomsheetscrollview, so there is nothing in between the sheet and the scroll view. I don't know what the problem was, but its' working reliably now :)
> 
> [@mclrc](https://github.com/mclrc) currently my code structure is like this
> 
> ```
> <BottomSheet>
>   <BottomSheetView style={{flex:1}}>
>      <ScrollView>....content....</ScrollView> "from react-native-gesture-handler"
>   </BottomSheetView>
> </BottomSheet>
> ```
> 
> If the sheet is opened add I remove the BottomSheetView then sheet scrolls to the bottom very well but when I close the sheet and try opening it again it does not even open.

Currently facing the same issue.
