### ISSUE TITLE
[v4] | [v2] BottomSheetTextInput as footerComponent does not stick to bottom on keyboard focus (Android only)

### ISSUE THREAD

**Issue by esorinas** [gorhom/react-native-scroll-bottom-sheet#1504]
# Bug

I am using a `BottomSheetTextInput` as `footerComponent` in `BottomSheetModal`. When the keyboard, instead of sticking to the bottom while user is typing, the input floats somewhere in the middle of the screen. This happens only in Android, whereas in iOS the footer sticks in the bottom while typing, as expected.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7  |
| react-native                    | 0.72.3  |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.1   |

## Steps To Reproduce

1. Define a `BottomSheetModal` in your app
2. Set the `footerComponent` prop to render a `BottomSheetTextInput` component
3. Tap on the input to focus the keyboard
4. Input component floats in the middle of the screen, far from the focused keyboard

Describe what you expected to happen:

1. Input component sticks to the bottom, right above the focused keyboard

## Reproducible sample code

Reproducible issue: https://github.com/esorinas/playground-app

Main code:

```
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={0}
          snapPoints={snapPoints}
          footerComponent={() => <BottomSheetTextInput style={{backgroundColor: 'grey'}} placeholder="Some text here"/>}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
```

https://github.com/gorhom/react-native-bottom-sheet/assets/43247096/d981c2a2-81c3-4724-b4ef-263c83817a3f

**Comment by omarabualhija** [comment]
same bug in iOS and android

macbook 2019 
VS code


"react-native": "^0.71.8",
@gorhom/bottom-sheet": "^4.4.7"

**Comment by LouisCapelle** [comment]
Try this : 

```
android_keyboardInputMode="adjustResize"
keyboardBehavior={Platform.OS === 'ios' ? 'extend' : 'interactive'}
keyboardBlurBehavior="restore"
```

**Comment by esorinas** [comment]
Hi @LouisCapelle this did fix the issue! Thank you very much!

**Comment by halid96** [comment]
> Try this :
> 
> ```
> android_keyboardInputMode="adjustResize"
> keyboardBehavior={Platform.OS === 'ios' ? 'extend' : 'interactive'}
> keyboardBlurBehavior="restore"
> ```

this fixed the issue. Thank you!

**Comment by vinesh4Real** [comment]
@LouisCapelle thanks for that. But it doesn't completely fix the problem if your action sheet has a bottominset > 0.
As you can see below, I have my bottomInset set to 60. When I open the keyboard, it still respects that bottomInset. 
It should not.

https://github.com/user-attachments/assets/665abf28-5c9e-4243-8a84-eceb8564d519
