### ISSUE TITLE
[v4] [v5] | [v2] ‘BottomSheetModalInternalContext’ cannot be null error in expo-router

### ISSUE THREAD

**Issue by crstnmac** [gorhom/react-native-scroll-bottom-sheet#1506]
# Bug

  We have a open source library which uses the bottomsheet ,when we use the component inside a expo-router project we get  

  ```
  ‘BottomSheetModalInternalContext’ cannot be null 
  
  ```
  even after `BottomSheetModalProvider` is wrapped in the `_layout.tsx` file of the root

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0.alpha-3   |
| react-native                    | 0.72.4   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Install @gorhom/react-native-bottom-sheet in a expo-router project and also add @adaptui/react-native-tailwind@1.0.0-alpha.13
2.Use the select component as described [here](https://github.com/adaptui/react-native-tailwind/blob/main/docs/select.md)
3. Run the app

Describe what you expected to happen:

1.Expected to open a sheet with options

## Reproducible sample code

Reproducable code:- 

https://github.com/crstnmac/remember-me/tree/select-bug

**Comment by sutyum** [comment]
Did this work out? Does Expo Router V3 help?

**Comment by naytun** [comment]
You just need to wrap in `<BottomSheetModalProvider> ` as follow:
```
         <BottomSheetModalProvider>
            <BottomSheetModal
               ref={bottomSheetModalRef}
               index={0}
               snapPoints={snapPoints}
            >
               <ScrollView contentContainerStyle={...}>
                  ...
               </ScrollView>
            </BottomSheetModal>
         </BottomSheetModalProvider>
```
