### ISSUE TITLE
[v4] [v5] | [v3] Bottom sheet height jumps when closing while using reanimated v3 on android

### ISSUE THREAD

**Issue by ldabiralai** [gorhom/react-native-scroll-bottom-sheet#1508]
# Bug

When upgrading to `react-native-reanimated` v3 a flicker can be seen when closing the bottom sheet. This occurs on both v4 and v5 of the library.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7 (also present on latest v5 alpha)  |
| react-native                    | 0.72.4   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

Ideally use a real android device

1. Clone the example repo, checkout `reanimated-v3` branch
2. `npm i && npm run android`
3. Tap the blue closed state
4. Wait for the sheet to open
5. Tap the background to close the bottom sheet 
6. Repeat 3-5
7. Observe that the bottom sheet sometimes jumps up before collapsing

You can see the behaviour in the video below, it's most obvious at around the 11s mark:

https://github.com/gorhom/react-native-bottom-sheet/assets/1711610/0a39d32a-014b-4150-8044-8914005a382b

Describe what you expected to happen:

1. I would expect the bottom sheet to not jump up sometimes before closing, but instead smoothly collapse downwards.

You can see this working as expected on the master branch:

https://github.com/gorhom/react-native-bottom-sheet/assets/1711610/52abd8f4-f292-4db0-b54f-d9f5ef1f15d8

## Reproducible sample code

I've tried to keep the dependencies as close as possible, but with expo it wasn't possible to keep them exactly the same.

`master` branch uses react-native-reanimated v2, no flicker is present.
`reanimated-v3` branch uses react-native-reanimated v3, flicker is sometimes present when closing the bottom sheet.

https://github.com/ldabiralai/bottom-sheet-reanimated-bug

**Comment by ldabiralai** [comment]
Commenting to keep open, I wouldn't consider this stale.

**Comment by ldabiralai** [comment]
Still not stale

**Comment by tommynordli** [comment]
Still an issue using reanimated v3

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.6  |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

https://github.com/gorhom/react-native-bottom-sheet/assets/5970898/b0e39683-09b4-4856-9ce4-c3b682e9e13f

**Comment by ChronoByteCosmonaut** [comment]
I also have the issue on android

**Comment by nixolas1** [comment]
Edit:
Issue is solved when upgrading to react-native-reanimated v3.6.1 and react-native-gesture-handler v2.14.0

**Comment by jeffinhk** [comment]
> Edit: Issue is solved when upgrading to react-native-reanimated v3.6.1 and react-native-gesture-handler v2.14.0

this worked!
