### ISSUE TITLE
Cannot make new prop enableDynamicSizing work

### ISSUE THREAD

**Issue by andruxnet** [gorhom/react-native-scroll-bottom-sheet#1517]
I'm trying to use the new `enableDynamicSizing` prop but can'tmake it work. Maybe I'm missing something?

I'm using `"@gorhom/bottom-sheet": "^4.5.0"`

I have tested the example screen under /[example](https://github.com/gorhom/react-native-bottom-sheet/tree/master/example)/[app](https://github.com/gorhom/react-native-bottom-sheet/tree/master/example/app)/[src](https://github.com/gorhom/react-native-bottom-sheet/tree/master/example/app/src)/[screens](https://github.com/gorhom/react-native-bottom-sheet/tree/master/example/app/src/screens) and it works as it says it should work, so I'm not sure why my case is not working.

I have this custom component I use to make use of the BottomSheetModal, and it works when I add a `snapPoints` prop, but as soon as I add the `enableDynamicSizing` prop the bottom sheet no longer is displayed. I include my custom bottom sheet component like this (this configuration does work):

```
        <SheetModal ref={sheetModalRef} enableDynamicSizing={false} snapPoints={[250]}>
          <View style={styles.modal}>
            <HTMLView
              value={`<p>${current?.description}</p>`}
              onLinkPress={(url) => pressLink(url)}
              stylesheet={htmlViewStyles}
              addLineBreaks={false}
            />
          </View>
        </SheetModal>
```

If I change the props being passed to this:

```
<SheetModal ref={sheetModalRef} enableDynamicSizing={true}>
```

then it no longer works.

This is my custom component:

```import { createRef, forwardRef, useImperativeHandle, useCallback } from 'react'
import { BottomSheetModalProvider, BottomSheetModal, BottomSheetBackdrop } from '@gorhom/bottom-sheet'

const SheetModal = forwardRef(({ children, enableDynamicSizing = false, snapPoints = [] }, ref) => {
	const bottomSheetModalRef = createRef()

	const renderBackdrop = useCallback(
		props => (
			<BottomSheetBackdrop
				{...props}
				enableTouchThrough={true}
				enableFade={true}
				disappearsOnIndex={-1}
				appearsOnIndex={0}
			/>
		),
		[]
	)

	useImperativeHandle(ref, () => ({
		presentModal: () => {
			bottomSheetModalRef.current.present()
		},
		dismissModal: () => {
			bottomSheetModalRef.current.dismiss()
		}
	}))

	return (
		<BottomSheetModalProvider>
			<BottomSheetModal
				ref={bottomSheetModalRef}
				enableDynamicSizing={enableDynamicSizing}
				snapPoints={snapPoints}
				backdropComponent={renderBackdrop}
			>
				{children}
			</BottomSheetModal>
		</BottomSheetModalProvider>
	)
})

export default SheetModal
```

Hopefully someone can see what I'm doing wrong and can help me out.

Thanks

**Comment by gorhom** [comment]
You need to use BottomSheetView instead of View

**Comment by andruxnet** [comment]
Thank you @gorhom , I was just re writing the issue using the template from another issue.

Using BottomSheetView did the trick, it now shows the bottom sheet, thanks! I also had to remove flex styling from the view because it would show the sheet full height.

Thanks again for taking the time to respond. Awesome library and awesome support 🥇
