### ISSUE TITLE
use useAnimatedKeyboard instead of custom implementation

### ISSUE THREAD

**Issue by cah4a** [gorhom/react-native-scroll-bottom-sheet#1519]
# Feature Request

There is a fantastic SharedValue for [keyboard height](https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/hooks/useAnimatedKeyboard/) from react-reanimated library.

## Why it is needed

Instead of wrapping TextInputs and playing around with Durations, Easing (that doesn't work perfectly), and providing `shouldHandleKeyboardEvents` it's possible to use just animated keyboard height.

## Possible implementation

const keyboard = useAnimatedKeyboard();
const animatedKeyboardState = keyboard.state;
const animatedKeyboardHeight = keyboard.height;

### Code sample

not applicable

**Comment by gstcarv** [comment]
I guess this patch can help you. I'm not sure if it works in all cases but I only needed smooth BottomSheetFooter transition on a simple BottomSheet.

```patch
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
index 9d42ef1..829b453 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
@@ -1,6 +1,7 @@
 import React, { memo, useCallback, useMemo, useRef } from 'react';
 import {
   LayoutChangeEvent,
+  Platform,
   StatusBar,
   StyleProp,
   View,
@@ -10,6 +11,7 @@ import { WINDOW_HEIGHT } from '../../constants';
 import { print } from '../../utilities';
 import { styles } from './styles';
 import type { BottomSheetContainerProps } from './types';
+import Animated, { useAnimatedKeyboard, useAnimatedStyle } from 'react-native-reanimated';
 
 function BottomSheetContainerComponent({
   containerHeight,
@@ -21,19 +23,26 @@ function BottomSheetContainerComponent({
   style,
   children,
 }: BottomSheetContainerProps) {
-  const containerRef = useRef<View>(null);
+  const containerRef = useRef<Animated.View>(null);
+
+  const animatedKeyboard = useAnimatedKeyboard()
+
+  const animatedBottom = useAnimatedStyle(() => ({
+    bottom: Platform.OS === 'android' ?  animatedKeyboard.height.value + bottomInset :bottomInset
+  }))
+
   //#region styles
   const containerStyle = useMemo<StyleProp<ViewStyle>>(
     () => [
+      animatedBottom,
       style,
       styles.container,
       {
         top: topInset,
-        bottom: bottomInset,
         overflow: detached ? 'visible' : 'hidden',
       },
     ],
-    [style, detached, topInset, bottomInset]
+    [style, detached, topInset, bottomInset, animatedBottom]
   );
   //#endregion
 
@@ -74,7 +83,7 @@ function BottomSheetContainerComponent({
 
   //#region render
   return (
-    <View
+    <Animated.View
       ref={containerRef}
       pointerEvents="box-none"
       onLayout={shouldCalculateHeight ? handleContainerLayout : undefined}
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
index 0ddd8e0..612eb58 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
@@ -1,8 +1,9 @@
 import React, { memo } from 'react';
-import { useDerivedValue } from 'react-native-reanimated';
+import { useAnimatedKeyboard, useDerivedValue } from 'react-native-reanimated';
 import { useBottomSheetInternal } from '../../hooks';
 import { KEYBOARD_STATE } from '../../constants';
 import type { BottomSheetFooterContainerProps } from './types';
+import { Platform } from 'react-native';
 
 const BottomSheetFooterContainerComponent = ({
   footerComponent: FooterComponent,
@@ -16,17 +17,21 @@ const BottomSheetFooterContainerComponent = ({
     animatedKeyboardState,
     animatedKeyboardHeightInContainer,
   } = useBottomSheetInternal();
+
+  const reanimatedKeyboard = useAnimatedKeyboard()
+
   //#endregion
 
   //#region variables
   const animatedFooterPosition = useDerivedValue(() => {
-    const keyboardHeight = animatedKeyboardHeightInContainer.value;
+    const keyboardHeight = Platform.OS === 'android' ? animatedKeyboardHeightInContainer.value : reanimatedKeyboard.height.value;
+
     let footerTranslateY = Math.max(
       0,
       animatedContainerHeight.value - animatedPosition.value
     );
 
-    if (animatedKeyboardState.value === KEYBOARD_STATE.SHOWN) {
+    if (animatedKeyboardState.value === KEYBOARD_STATE.SHOWN || Platform.OS === 'ios') {
       footerTranslateY = footerTranslateY - keyboardHeight;
     }
 
@@ -37,6 +42,7 @@ const BottomSheetFooterContainerComponent = ({
 
     return footerTranslateY;
   }, [
+    reanimatedKeyboard,
     animatedKeyboardHeightInContainer,
     animatedContainerHeight,
     animatedPosition,

```

**Comment by TowhidKashem** [comment]
> I guess this patch can help you. I'm not sure if it works in all cases but I only needed smooth BottomSheetFooter transition on a simple BottomSheet.
> 
> ```diff
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
> index 9d42ef1..829b453 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContainer/BottomSheetContainer.tsx
> @@ -1,6 +1,7 @@
>  import React, { memo, useCallback, useMemo, useRef } from 'react';
>  import {
>    LayoutChangeEvent,
> +  Platform,
>    StatusBar,
>    StyleProp,
>    View,
> @@ -10,6 +11,7 @@ import { WINDOW_HEIGHT } from '../../constants';
>  import { print } from '../../utilities';
>  import { styles } from './styles';
>  import type { BottomSheetContainerProps } from './types';
> +import Animated, { useAnimatedKeyboard, useAnimatedStyle } from 'react-native-reanimated';
>  
>  function BottomSheetContainerComponent({
>    containerHeight,
> @@ -21,19 +23,26 @@ function BottomSheetContainerComponent({
>    style,
>    children,
>  }: BottomSheetContainerProps) {
> -  const containerRef = useRef<View>(null);
> +  const containerRef = useRef<Animated.View>(null);
> +
> +  const animatedKeyboard = useAnimatedKeyboard()
> +
> +  const animatedBottom = useAnimatedStyle(() => ({
> +    bottom: Platform.OS === 'android' ?  animatedKeyboard.height.value + bottomInset :bottomInset
> +  }))
> +
>    //#region styles
>    const containerStyle = useMemo<StyleProp<ViewStyle>>(
>      () => [
> +      animatedBottom,
>        style,
>        styles.container,
>        {
>          top: topInset,
> -        bottom: bottomInset,
>          overflow: detached ? 'visible' : 'hidden',
>        },
>      ],
> -    [style, detached, topInset, bottomInset]
> +    [style, detached, topInset, bottomInset, animatedBottom]
>    );
>    //#endregion
>  
> @@ -74,7 +83,7 @@ function BottomSheetContainerComponent({
>  
>    //#region render
>    return (
> -    <View
> +    <Animated.View
>        ref={containerRef}
>        pointerEvents="box-none"
>        onLayout={shouldCalculateHeight ? handleContainerLayout : undefined}
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
> index 0ddd8e0..612eb58 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetFooterContainer/BottomSheetFooterContainer.tsx
> @@ -1,8 +1,9 @@
>  import React, { memo } from 'react';
> -import { useDerivedValue } from 'react-native-reanimated';
> +import { useAnimatedKeyboard, useDerivedValue } from 'react-native-reanimated';
>  import { useBottomSheetInternal } from '../../hooks';
>  import { KEYBOARD_STATE } from '../../constants';
>  import type { BottomSheetFooterContainerProps } from './types';
> +import { Platform } from 'react-native';
>  
>  const BottomSheetFooterContainerComponent = ({
>    footerComponent: FooterComponent,
> @@ -16,17 +17,21 @@ const BottomSheetFooterContainerComponent = ({
>      animatedKeyboardState,
>      animatedKeyboardHeightInContainer,
>    } = useBottomSheetInternal();
> +
> +  const reanimatedKeyboard = useAnimatedKeyboard()
> +
>    //#endregion
>  
>    //#region variables
>    const animatedFooterPosition = useDerivedValue(() => {
> -    const keyboardHeight = animatedKeyboardHeightInContainer.value;
> +    const keyboardHeight = Platform.OS === 'android' ? animatedKeyboardHeightInContainer.value : reanimatedKeyboard.height.value;
> +
>      let footerTranslateY = Math.max(
>        0,
>        animatedContainerHeight.value - animatedPosition.value
>      );
>  
> -    if (animatedKeyboardState.value === KEYBOARD_STATE.SHOWN) {
> +    if (animatedKeyboardState.value === KEYBOARD_STATE.SHOWN || Platform.OS === 'ios') {
>        footerTranslateY = footerTranslateY - keyboardHeight;
>      }
>  
> @@ -37,6 +42,7 @@ const BottomSheetFooterContainerComponent = ({
>  
>      return footerTranslateY;
>    }, [
> +    reanimatedKeyboard,
>      animatedKeyboardHeightInContainer,
>      animatedContainerHeight,
>      animatedPosition,
> ```

just what I needed, thanks!
