### ISSUE TITLE
[v4] Scrollable content can result in stuck BottomSheetModal if user interrupts close. [All platforms]

### ISSUE THREAD

**Issue by Eli-Nathan** [gorhom/react-native-scroll-bottom-sheet#1527]
# Bug

If a <BottomSheetModal /> component contains a BottomSheetScrollView, and you close it with either `ref.current.close()` or `ref.current.forceClose()` and "catch" it while it dismisses, interrupting the close. If while you're dragging it back up, you overscroll slightly upwards, the bottomsheet gets stuck and any close actions no longer work.

In the video example, you can see examples of the issue.

Int he example, one of the times I do this, I purposefully don't overscroll and allow it to naturally get back to it's snapPoint. This lets the sheet work as expected.

It seems it could be something Gesture handler related since it's only after an overscroll.

Example taken from a simulator but the bug is far easier to repro on a physical device. If you have a bottomsheet modal with a list of options that each close the sheet, it is repro'd often by tapping fast on various options, especially if any of the taps have even a hint of panning motion.

### Video link
https://www.veed.io/view/1b0763be-a777-4177-b7b3-31aa1b2996cc

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.0 |
| react-native                    | 0.69.4 |
| react-native-reanimated         | 2.9.1 |
| react-native-gesture-handler    | 2.5.0 |

## Steps To Reproduce

Alter the example App's file: `example/app/src/screens/modal/DynamicSnapPointExample.tsx` to use a `BottomSheetScrollView` instead of the `BottomSheetView` and add a close button within the modal.

```ts
// ...
return (
  <View style={styles.container}>
    <Button label="Present" onPress={handlePresentPress} />
    <Button label="Dismiss" onPress={handleDismissPress} />
    <BottomSheetModal
      ref={bottomSheetRef}
      enableDynamicSizing={true}
      enablePanDownToClose={true}
    >
      <BottomSheetScrollView style={contentContainerStyle}>
        <Button label="Close" onPress={handleDismissPress} />
        <Text style={styles.message}>
          Could this sheet modal resize to its content height ?
        </Text>
        <View style={emojiContainerStyle}>
          <Text style={styles.emoji}>😍</Text>
        </View>
        <Button label="Yes" onPress={handleIncreaseContentPress} />
        <Button label="Maybe" onPress={handleDecreaseContentPress} />
      </BottomSheetScrollView>
    </BottomSheetModal>
  </View>
);
```

1. Expand bottom sheet modal a few times with the "Yes" button to ensure it's scrollable
2. Press Close Button
3. While it's closing, quickly grab it on the way down and drag it back up
4. Keep dragging so that you reach the snapPoint and the content begins to overscroll upwards
5. Press Close and nothing will happen
6. If you then drag the handle either up or down even slightly it seems to reset all functionality.
7. It is possible to pan down to close still
8. Pressing Backdrop to close also doesn't work

Describe what you expected to happen:

1. Overscroll shouldn't break anything

## Reproducible sample code

See above using example app from repo

**Comment by Eli-Nathan** [comment]
Related to https://github.com/gorhom/react-native-bottom-sheet/issues/695
But a little different

**Comment by krisgerhard** [comment]
Same issue for me, would love to see it resolved.

**Comment by Eli-Nathan** [comment]
I've actually been able to reproduce this recently on the Instagram app. Not sure if they use this lib but I know they're a react native app. 
Could be related to gesture handler.

This issue becomes a real problem when the bottom sheet contains touchable elements that should close the sheet. On slower devices it is very easy to reproduce.

It'd be great to have this looked at.

**Comment by krisgerhard** [comment]
I use bottom sheet for navigation. So it contains touchable elements which open another page (with stack navigator).
Sometimes bottom sheet closes half way and remains to be displayed in the next page. I worked around it so that first the bottom sheet is closed and then navigation is done but it's a bit slow experience for the users.

**Comment by Eli-Nathan** [comment]
Okay I seem to have fixed this issue for my case.

I had a function exposed to close the bottomSheetModal.
Like this: 

```ts
const hideBottomSheetModal = useCallback(() => {
  bottomSheetModalRef.current?.close()
}, [])
```

Everything worked as expected if I make these changes
```diff
- const hideBottomSheetModal = useCallback(() => {
-  bottomSheetModalRef.current?.close()
- }, [])
+ const hideBottomSheetModal = () => {
+   bottomSheetModalRef.current?.close()
+ }
```

**Comment by krisgerhard** [comment]
From my side it's also resolved. Different solution though.

I reworked my touchable elements inside bottom sheet.
When navigating to a different view (without bottom sheet) I also unmount it so it's not half-way displayed anymore.
