### ISSUE TITLE
index props doesn't working as expected for BottomSheetModal

### ISSUE THREAD

**Issue by vijay-gojiya** [gorhom/react-native-scroll-bottom-sheet#1535]
Hello,
 @gorhom  I noticed that the index prop doesn't seem to be working as expected for opening the BottomSheetModal by default when using,Is there an alternative method to ensure the bottom sheet is always open? 
Thank you!

**Comment by anatoleblanc** [comment]
+1 though, this makes index pretty complex to use :)
