### ISSUE TITLE
[v4] - BottomSheetModal is behind TabBars

### ISSUE THREAD

**Issue by Spxc** [gorhom/react-native-scroll-bottom-sheet#1539]
# Bug
BottomSheetModal is not presented above the TabBars using Wix RNN

![2023-09-20_09-17-55](https://github.com/gorhom/react-native-bottom-sheet/assets/1374923/09b364f7-7691-45f8-8a81-bf248da13af0)

## Environment info
```
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "^2.13.1",
    "react-native-navigation": "^7.37.0-hotfix.1",
    "react-native-reanimated": "^3.5.2",
  },
```
## Steps To Reproduce
1. Install and setup Wix RNN (React Native Navigation)
2. Install and setup BottomSheet
3. Wrap your registeredComponents with `gestureHandlerRootHOC` (according to the docs)
4. Show BottomSheetModal

Describe what you expected to happen:

1. Expect it to be above the TabBar (not anchored to it)

## Reproducible sample code
index.js
```
import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

Navigation.registerComponent('HomeScreen', 
  () => gestureHandlerRootHOC(Home)

/** This produces the same result **/
Navigation.registerComponent('HomeScreen', 
  () => props => (
    <GestureHandlerRootView>
      <BottomSheetModalProvider>
        <Home {...props} />
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  ),
  () => gestureHandlerRootHOC(Home)

Navigation.setRoot({tabStack})
```

Home.js
```
return (
<SafeAreaView style={styles.wrapper(isDarkMode)}>
        <BottomSheetModalProvider>
             <ReceivePayment ref={receiveModalRef} />
        </BottomSheetModalProvider>
</SafeAreaView>
```

ReceivePayments.js
```
return (
        <BottomSheetModal
            ref={bottomSheetModalRef}
            index={0}
            snapPoints={snapPoints}
            onChange={handleSheetChanges}
            backdropComponent={renderBackdrop}
            backgroundStyle={{backgroundColor: isDarkMode ? '#010010' : '#f2f2f7'}}
            handleStyle={{borderTopLeftRadius: 15, borderTopRightRadius: 15, backgroundColor: isDarkMode ? '#010010' : '#f2f2f7'}}
            >
            <View style={styles.contentContainer}>
                <Text>Receive assets 🎉</Text>
            </View>
        </BottomSheetModal>
    )
```

**Comment by Wilightmoment** [comment]
You need to lift BottomSheetModalProvider up to BottomTabNavigator's root.

like: 
`
  <BottomSheetModalProvider>
    <Tab.Navigator>{Screens()}</Tab.Navigator>
  </BottomSheetModalProvider>
`

**Comment by Spxc** [comment]
> You need to lift BottomSheetModalProvider up to BottomTabNavigator's root.
> 
> like: `<BottomSheetModalProvider> <Tab.Navigator>{Screens()}</Tab.Navigator> </BottomSheetModalProvider>`

Yes, however i'm using Wix RNN, so these wrapper/providers dosent work like that. If you have a look at the `index.js`

**Comment by Eli-Nathan** [comment]
Might be one to raise on the [Wix/React-native-navigation](https://github.com/wix/react-native-navigation) repo on their issues or discussions to see how you should wrap the tabs or app

**Comment by Spxc** [comment]
> Might be one to raise on the [Wix/React-native-navigation](https://github.com/wix/react-native-navigation) repo on their issues or discussions to see how you should wrap the tabs or app

As you can see, it's clearly wrapped, and everything else, including the HOC is working. So this is not related to Wix, this is related to this lib. I've also seen a lot people experiencing this as well. Some use `Portal`, but that really should't be necessary tbh

**Comment by Eli-Nathan** [comment]
> As you can see, it's clearly wrapped

It looks like you have a wrapper around your Home component but that won't include the tabs? I haven't used Wix navigation before

It looks like you _also_ have a second wrapper within your home component?

I imagine it will use the closest one to the actual BottomSheet in the tree, any reason for having 2?

**Comment by Spxc** [comment]
> > As you can see, it's clearly wrapped
> 
> It looks like you have a wrapper around your Home component but that won't include the tabs? I haven't used Wix navigation before
> 
> It looks like you _also_ have a second wrapper within your home component?
> 
> I imagine it will use the closest one to the actual BottomSheet in the tree, any reason for having 2?

Purely as a test, and following the docs from the lib, wrapping the components in HOC was they only way. There is no way to wrap the entire TabController on Wix, as that's not the way it's structured.

**Comment by Eli-Nathan** [comment]
Yeah I think that's what I'm getting at. It sounds like a limitation of that library not giving full customisation options for the root component.

There may be a way to use their setRoot method and define a custom component that in-turn renders the bottom tabs https://wix.github.io/react-native-navigation/docs/advanced-navigation

Their example playground app has a global context and some conditional setRoot logic but it's pretty complex https://github.com/wix/react-native-navigation/blob/master/playground/src/context/index.tsx


But like I say, I've not used that library before so maybe not

**Comment by Spxc** [comment]
Thanks, yeah that's exactly what i'm doing. Wrapping the components as the documentation says. But it dosen't seem to affect the tabcontroller, just the single screen themselves.

**Comment by lethienhung** [comment]
Hi @Spxc! I have the same issue and still struggling to deal with it. Have you found any solution to this situation?

**Comment by Spxc** [comment]
> Hi @Spxc! I have the same issue and still struggling to deal with it. Have you found any solution to this situation?

Sadly... no. 

And you?

**Comment by marcshilling** [comment]
Seems like with Wix RNN you need to use an Overlay (`Navigation.showOverlay()`). You can then render the bottom sheet in that overlay component, and dismiss the overlay when the bottom sheet closes:
```
<BottomSheet
  onChange={(index: number) => {
    if (index === -1) {
      Navigation.dismissOverlay(componentId)
    }
  }}
  ...
>
```

**Comment by GeorgeKumoHq** [comment]
Any solution for this issue. im having the same.
