### ISSUE TITLE
Document onClose invoked on initial render when index is -1

### ISSUE THREAD

**Issue by x43n** [gorhom/react-native-scroll-bottom-sheet#1540]
# Feature Request

Add info to the [`index` prop documentation](https://gorhom.github.io/react-native-bottom-sheet/props#index) detailing the behaviour commented [here](https://github.com/gorhom/react-native-bottom-sheet/blob/65b5dc03e673c25b3b41af954e1f13fe7668a339/src/components/bottomSheet/BottomSheet.tsx#L1561), specifically regarding "we fire the `onClose` callback" 

## Why it is needed

It is somewhat counter-intuitive to invoke the `onClose` callback when the desired initial state of the bottomsheet is closed (index -1). The `onChange` callback can be used for tracking a explicit close event, so it's ok, but good for this to be clearly in the docs to avoid confusing over why onClose is being called when the user has no closed anything.

**Comment by ponikar** [comment]
this is weird behaviour, somehow onClose gets invoked initially when trying to open the sheet. After debugging for a hour. 
Came up with this hack. It might be helpful for you. 

```js
 const initial = useRef(true);
    const onClose = () => {
      // avoid trigger onClose initially
      if (initial.current && ref) {
        initial.current = false;
        ref.current.expand();
        return;
      }
      props?.onClose?.();
    };
```

ref has a reference of BottomSheet via `useRef`.
