### ISSUE TITLE
Document onClose invoked on initial render when index is -1

### ISSUE THREAD

**Issue by x43n** [gorhom/react-native-scroll-bottom-sheet#1541]
# Feature Request

Add info to the [index prop documentation](https://gorhom.github.io/react-native-bottom-sheet/props#index) detailing the behaviour commented [here](https://github.com/gorhom/react-native-bottom-sheet/blob/65b5dc03e673c25b3b41af954e1f13fe7668a339/src/components/bottomSheet/BottomSheet.tsx#L1561), specifically regarding "we fire the onClose callback"

## Why it is needed

It is somewhat counter-intuitive to invoke the `onClose` callback when the desired initial state of the bottomsheet is closed (index -1). The `onChange` callback can be used for tracking an explicit closed event, so it's ok, but good for this to be clearly in the docs to avoid confusing over why onClose is being called when the user has not closed anything. 

## Possible implementation

N/A

### Code sample

N/A

**Comment by mkizesov** [comment]
I also think it'd be great to have this in the docs. Can try helping with updating the documentation.
Btw even "onClose" cb itself is not documented https://gorhom.dev/react-native-bottom-sheet/props#onchange
