### ISSUE TITLE
[v4] | [v2] App not starting in android debug mode

### ISSUE THREAD

**Issue by PrajTS** [gorhom/react-native-scroll-bottom-sheet#1542]
# Bug

I need to use react-native-reanimated v2. During android build, I get this warning

WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found. Falling back to AAR for react-native version 71. The react-native JSI interface is not ABI-safe yet, this may result in crashes. Please post a pull request to implement support for react-native version 72 to the reanimated repo. Thanks!.

![image](https://github.com/gorhom/react-native-bottom-sheet/assets/31252757/4ef15b09-d7af-4805-9c3c-46045e5573ed)

When I try to run the app, the get the following error

` ERROR Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook5react19ReadableNativeArrayC1EN5folly7dynamicE" referenced by "/data/app/~~pJKVSOSw9TXUlUfK49FGTA==/com.onecode.gorhomv42-dXfMUFZfXOXDMwjZ0vJo_w==/lib/arm64/libreanimated.so"..., js engine: hermes
ERROR Invariant Violation: "main" has not been registered. This can happen if:

    Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    A module failed to load due to an error and AppRegistry.registerComponent wasn't called., js engine: hermes`
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/31252757/84fa6e87-eeef-4690-b794-daeafa56816b)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.4   |
| react-native-reanimated         | 2.17.0   |
| react-native-gesture-handler    | 2.12.1  |

## Steps To Reproduce

1. create project with expo
2. yarn add @gorhom/bottom-sheet@^4
3. yarn add reanimated@2  react-native-gesture-handler
4. Add plugin of renaimated to babel.config.js
5. Add gesture handler hoc 
6. Add sample code from documentation
7. run npx expo run:android

## Reproducible sample code

https://github.com/PrajTS/reanimated-2-issue

**Comment by sondreluc** [comment]
As the warning states, unfortunately `react-native-reanimated@v2` does not support `react-native@v72`. You either have to update to reanimated@v3, or seek help into getting reanimated@v2 to support in react-native@v72 in the reanimated repo.

**Comment by PrajTS** [comment]
Will react-native-reanimated@v3 work well with @gorhom/bottom-sheet@v4? I am facing some issues while issues keyboard handling when I use gorhom/bottom-sheet@v4 with reanimated@v3
