### ISSUE TITLE
[v4]  Enable FlatList scrolling when BottomSheet has multiple snapPoints

### ISSUE THREAD

**Issue by halid96** [gorhom/react-native-scroll-bottom-sheet#1547]
When the BottomSheet has multiple snapPoints eg: `const snapPoints = useMemo(() => ["60%", "90%"]);` When a BottomSheetFlatList exists. The scrolling prioritizes the snap index of BottomSheet, instead of scrolling the BottomSheetFlatList contents.

I tried to `enableContentPanningGesture={false}` to disable the Snap Index change,  but this also disables the BottomSheetFlatList scrolling.

**Please allow a user to change the Snap Index only from the handler**

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4  |
| react-native                    | 0.72.3   |
| react-native-reanimated         | ~3.3.0   |
| react-native-gesture-handler    | ~2.12.0   |

**Comment by getsadzeg** [comment]
Have you found the workaround of this, by any chance, @halid96 ?

**Comment by vlkpa** [comment]
try to use FlatList from react-native instead of BottomSheetFlatList

**Comment by getsadzeg** [comment]
> try to use FlatList from react-native instead of BottomSheetFlatList

I couldn't scroll FlatList from react-native inside BottomSheet at all.

**Comment by halid96** [comment]
> Have you found the workaround of this, by any chance, @halid96 ?

No solution yet. TikTok also can't do it, the comments section cannot be adjusted by users. Its always 60%.

**Comment by j-elmer123** [comment]
got similar issue here

**Comment by factorycreacom** [comment]
Can anyone find a solution to this problem?
