### ISSUE TITLE
Defaulting the bottom sheet to be closed instead of initially open?

### ISSUE THREAD

**Issue by ahmetskilinc** [gorhom/react-native-scroll-bottom-sheet#1551]
# Feature Request

I can't find any documentation on it but having the bottom sheet default to open isn't the behaviour I am looking for. If it exists how do I default it to closed, if not can it be implemented?

I am currently using a useEffect hook to call the close method on the action sheet which shows the sheet for a second and then closes it.

## Why it is needed

I want to present the bottom sheet only when it is called on and not open by default?

## Possible implementation

It would work by defaulting the action to closed.

### Code sample

It could have a prop when set the action sheet is closed and when the open method is called via a button for example it can be opened.

**Comment by alexpertuz** [comment]
I have this problem too

**Comment by julien9999** [comment]
same here

**Comment by gani419** [comment]
I tried bottomSheetRef?.current?.close() in useEffect. Still not working.

**Comment by ahmetskilinc** [comment]
> I tried bottomSheetRef?.current?.close() in useEffect. Still not working.

@gani419 I had this working, but then it stopped working for some reason. I cannot figure out why.

**Comment by gani419** [comment]
Just checking this. Working when I try  bottomSheetRef?.current?.snapToIndex(-1); in useEffect

**Comment by ahmetskilinc** [comment]
Just built and tested and that doesn't seem to work.

**Comment by megabeehothanhminh** [comment]
index = {-1}

**Comment by Chosen2730** [comment]
> index = {-1}

This seem to fix it.

**Comment by johnny090807** [comment]
The way you could fix this for now is adding a flag before the sheet like this:

```
const bottomSheetRef = useRef<BottomSheet>(null);
const snapPoints = useMemo(() => ['50%', '75%'], []);

{ YourFlag && <BottomSheet 
                snapPoints={snapPoints}
                enablePanDownToClose
                ref={bottomSheetRef}
/>
```

**Comment by NGMIF** [comment]
It's in the doc https://ui.gorhom.dev/components/bottom-sheet/props

---
<img width="771" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/107159533/9727e1aa-6114-4e4a-92b8-d918b5fb0239">

**Comment by eminnovruz** [comment]
Just add "1%" into **snapPoints** and **snapToIndex(-1)** instantly in **useEffect**

```
const snapPoints = ["1%", "60%"]

    useEffect(() => {
      bottomSheetRef?.current?.snapToIndex(0)
    })
```

**Comment by khalidkresus** [comment]
use this 

`
index={-1}
enablePanDownToClose
snapPoints={['60%']}
`

**Comment by ReactJSGuy** [comment]
For anyone with this issue enable an array called snapPoints, snapPoints are the points on the horizaontal axis the bottomSheet jumps to. Then make the first number in this array 0 or something small like 10%. Then on the bottom sheet set the prop index equal to 0 which will be the default point the sheet jumps to on open.

For example
  const snapPoints = useMemo(()=>['10%','50%','80%'], []);
Then inside bottomSheet        <BottomSheet index={0}
This will mean the bottom sheet will open at a default of 10% which is a nice amount, just enough to see the bottom sheet.
Setting the index to -1 will close the bottom sheet completely on launch.

**Comment by omarker09** [comment]
> bottomSheetRef?.current?.snapToIndex(-1);

thats fix it 

`            <BottomSheet
                ref={bottomSheetRef}
                snapPoints={[80, '70%']}
                index={-1}
            >
                <BottomSheetView style={styles.contentContainer}>
                    <Button color={"orange"} title='Close' onPress={() => {
                        CloseSheet()
                    }} />
                    <Text>Awesome 🎉</Text>
                </BottomSheetView>
            </BottomSheet>`

**Comment by omkero** [comment]
<BottomSheet
            ref={bottomSheetRef}
            snapPoints={[80, '70%']}
            index={-1}
        >
            <BottomSheetView style={styles.contentContainer}>
                <Button color={"orange"} title='Close' onPress={() => {
                    bottomSheetRef.current?.close()
                 }} />
                <Text>Awesome 🎉</Text>
            </BottomSheetView>
        </BottomSheet>

**Comment by Hamzaraja314** [comment]
```javascript
<BottomSheet
        ref={bottomSheetRef}
        onChange={handleSheetChanges}
        snapPoints={['25%', '50%']}
        index={-1}
      >
```

**Comment by ffkraemer** [comment]
When I'm initializing with index={-1}, I have to click twice for the Bottom Sheet to open.
It seems that the index is not changing on the first click.

Anyone else having this problem?

`<TouchableOpacity onPress={toggleBottomSheet}>`

**And the toggleBottomSheet func:**

```
  function toggleBottomSheet(): void {
    if (visible) {
      bottomSheetRef?.current?.snapToIndex(0); //addtional workaround tried
      bottomSheetRef?.current?.expand();
    }
    else {
      bottomSheetRef?.current?.close();
    }
    setVisible(!visible);
  }
```

**Comment by martimarkov** [comment]
@ffkraemer I'm having the same issue

**Comment by karimcambridge** [comment]
yeah in the latest version, index={-1} appears to do nothing @gorhom 

The issue seems to only appear when enableDynamicSizing={true} and having dynamic snapPoints (like a useMemo).


```
<BottomSheet
				key='bottom-sheet'
				ref={bottomSheetRef}
				index={-1}
				snapPoints={snapPoints}
				//onAnimate={handleAnimateChanges}
				handleComponent={renderBottomSheetHandle}
				animatedIndex={bottomSheetIndex}
				animatedPosition={bottomSheetPosition}
				enableDynamicSizing={true}
				enableOverDrag={false}
				detached={isShowingSwipeButton ? true : false}
				bottomInset={isShowingSwipeButton ? 80 : 0}
				backgroundStyle={{ borderBottomStartRadius: 0, borderBottomEndRadius: 0 }}
				{...(isShowingProgressHandle ? { backgroundStyle: { borderRadius: 0 } } : undefined)}
			>
				<BottomSheetView
					style={{ flex: 1 }}
				>
					{renderRideDetails()}
				</BottomSheetView>
			</BottomSheet>
```

**Comment by Opus26** [comment]
Be sure not to assign `height: ‘100%’` to the style of the first `<BottomSheetView>{...}</BottomSheetView>` child of your `<BottomSheet />` component. Here is an example to avoid:

```ts
  <BottomSheet index={-1} snapPoints={snapPoints} {...}>
    <BottomSheetView style={{ height: '100%' }}>{...}</BottomSheetView>
  </BottomSheet>;
```

- "@gorhom/bottom-sheet": "^5.1.6"
- Android only
