### ISSUE TITLE
[v4] <BottomSheet /> is immovable on Android

### ISSUE THREAD

**Issue by Lump01** [gorhom/react-native-scroll-bottom-sheet#1552]
# Bug
I am using the <BottomSheet /> component but cannot scroll to increase or decrease the height at all on Android. It starts at the correct snap point, but doesn't respond to any gestures.

<img width="367" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/59035398/3e89c056-2472-43ce-acf0-3ee07f885c08">

I have followed all installation instructions for the correct version of the dependencies listed below (reanimated, gesture-handler).

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1    |
| react-native                                 | 0.72.3 |
| react-native-reanimated            | 2.17.0    |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce
Create a <BottomSheet /> component with the below code

I expect it snap between 25% and 50% height when I swipe up or down, but it doesn't respond at all. It does not trigger the 'onChange' function either.

## Reproducible sample code

`<View
    style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <BottomSheet
        ref={bottomSheetRef}
        onChange={console.log}
        snapPoints={['25%', '50%']}>
        <View style={{flex: 1}}>
          <Paragraph>Some cool content</Paragraph>
        </View>
      </BottomSheet>
    </View>`

**Comment by ssshopyak** [comment]
Try to change snap Points to fixed 50% or 25%. have this issue too(

**Comment by peternoordijk** [comment]
I have the feeling this relates to [this issue](https://github.com/gorhom/react-native-bottom-sheet/issues/1334) and [this one](https://github.com/gorhom/react-native-bottom-sheet/issues/1297#issuecomment-1492863586).
