### ISSUE TITLE
[v4] | [v2] BottomSheetModal failing to present on iOS

### ISSUE THREAD

**Issue by walterholohan** [gorhom/react-native-scroll-bottom-sheet#1559]
# Bug

We just recently updated RN to `0.72.5` and `react-native-reanimated` to `3.5.4` and released it to production over the weekend. And then we started to get reports from our users that the modals were failing to appear. I will attach some videos below but we were unable to reproduce it on a simulator or a real device however we have ~150,000 MAU so after 24 hours we had over 10 users who were affected.

We had users on iOS 16.x and iOS 17.x who were affected

To unblock our users I had to set `animateOnMount` to `false` which makes me believe the issue is with the opening animation of the modal and reanimated

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.7   |
| react-native                    | 0.72.5   |
| react-native-reanimated         | 3.5.4   |
| react-native-gesture-handler    | 2.13.1   |

## Video of bug
- User tries to press on `Link Activity` and you can see the modal briefly flashes
- User tries to press on `Referral Code` and again the modal flashes and closes

https://github.com/gorhom/react-native-bottom-sheet/assets/5293650/dafcd78b-5ac0-46e8-b99d-6973d0466a7d

**Comment by LouisKraemer** [comment]
Having a similar issue (not able to reproduce but some users have bottom sheet that are not opening) for some users on production. iOS 16 and 17 as well.

And I can confirm that disabling the animation fix the issue as well.
