### ISSUE TITLE
[v4] | [v2] | [IOS] Animation bug when close and open modal during navigation transition with dismissAll and native stack

### ISSUE THREAD

**Issue by Navipro70** [gorhom/react-native-scroll-bottom-sheet#1563]
# Bug

Animation bug when close modal with dismissAll, immediately open new screen and opening new modal at the mount moment of new screen for react navigation native stack.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.8  |
| react-native                    | 0.72.4   |
| react-native-reanimated         | 3.5.2   |
| react-native-gesture-handler    | 2.12.1   |
| @react-navigation/native-stack   | 6.9.13   |
| @react-navigation/native  | 6.1.6   |

## Steps To Reproduce

1. Open any screen
2. Open any modal
3. Dismiss modal with dismissAll, then call navigate | push | replace method of navigation with any screen
4. Open modal on new screen mount

Actual behavior: 
In the moment when first modal is fully closed (animation ended), second modal flicker for a moment at the bottom position

Describe what you expected to happen:
New opened modal should be opened without any stucking or flickering

## Reproducible sample code

 
    const MODAL_HEIGHT = 300;
    
    const Modal = () => {
      const { dismissAll } = useBottomSheetModal();
      const modalRef = useRef<BottomSheetModal>(null);
      const styles = useScreenStyles()
      const snapPoints = useMemo(() => [MODAL_HEIGHT + insets.bottom], [insets.bottom]);
      const navigation = useNavigation()
      
      return (
       <BottomSheetModal
            ref={modalRef}
            enablePanDownToClose={false}
            enableTouchOutsideToClose={false}
            snapPoints={snapPoints}
          >
            <BottomSheetView style={styles.container}>
              <View style={styles.row}>
                <Button
                  onPress={() => {
                    dismissAll();
                    navigation.push('NewScreen');
                  }}
                >
                  Close modals with dismissAll and open new screen with modal
                </Button>
              </View>
            </BottomSheetView>
          </BottomSheetModal>
        );
      }

## Demo

I've configured animation duration for 2 seconds, to correctly demonstrate behavior, but bug will be reproduced also without animationConfig

```
    const animconf = useBottomSheetTimingConfigs({ duration: 2000 });
    
    return <Modal animationConfigs={animconf} />
```

https://github.com/gorhom/react-native-bottom-sheet/assets/60893275/a2cf11a6-bd12-4f12-af33-43d66541f82e

**Comment by Navipro70** [comment]
Still actual

**Comment by Navipro70** [comment]
Still actual

**Comment by Navipro70** [comment]
Still actual

**Comment by Navipro70** [comment]
Still actual

**Comment by janodetzel** [comment]
Wait for the Animation to finish

**Comment by milevy1** [comment]
I had a similar issue where I was trying to navigate to another view with a button in the BottomSheetModal and the modal was not dismissing.  Our solution was to use [stack-actions/#replace](https://reactnavigation.org/docs/stack-actions/#replace) instead of `.navigate` or `.push`.  `.replace` seems to properly unmount the component and dismiss the modal automatically.

This may not work for all use cases, but in my case there was no need to keep the component in the navigation stack (user cannot go back to it).
