### ISSUE TITLE
[v4] | [v2] BottomSheetModal with enableDynamicSizing doesn't account for footerComponent height

### ISSUE THREAD

**Issue by okerx** [gorhom/react-native-scroll-bottom-sheet#1565]
# Bug

When using the `BottomSheetModal` component with the `enableDynamicSizing` prop set to `true` and without providing explicit `snapPoints`, the sheet dynamically adjusts its height to fit the content of the scrollable area. However, it does not account for the height of the footer (provided via the `footerComponent` prop). This results in the footer overlapping with some of the content or not being fully visible.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   | 
| react-native                    | 0.72.5   |
| react-native-reanimated         | 3.5.4   |
| react-native-gesture-handler    | 2.13.1   |

## Steps To Reproduce

1. Create a `BottomSheetModal` component.
2. Set the `enableDynamicSizing` prop to `true`.
3. Provide scrollable content and a footer using the `footerComponent` prop.
4. Observe that the height of the sheet does not account for the footer's height, causing overlap or the footer to be partially hidden.

Describe what you expected to happen:

1. The `BottomSheetModal` should dynamically adjust its height to fit both the scrollable content and the footer without any overlap.
2. The footer should be fully visible and not overlap with the content.

## Reproducible sample code

```jsx
const App: React.FC = () => {
  // ...
  return (
    <GestureHandlerRootView style={styles.root}>
      <BottomSheetModalProvider>
        <View style={styles.container}>
          <Button title="Present" onPress={handlePresentPress} />
          <Button title="Dismiss" onPress={handleDismissPress} />
        </View>
        <BottomSheetModal
          ref={bottomSheetRef}
          enableDynamicSizing
          enablePanDownToClose
          backdropComponent={renderBackdrop}
          footerComponent={Footer}
        >
          <BottomSheetScrollView>
            <View style={styles.contentContainer}>
              <View style={{ height: 50, backgroundColor: 'blue' }} />
              <View style={{ height: 50, backgroundColor: 'red' }} />
              <View style={{ height: 50, backgroundColor: 'green' }} />
            </View>
          </BottomSheetScrollView>
        </BottomSheetModal>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

const Footer = () => {
  return (
    <View style={{ height: 50, backgroundColor: 'yellow', justifyContent: 'center' }}>
      <Button title="Dismiss" onPress={() => {}} />
    </View>
  );
};

const styles = StyleSheet.create({
  root: { flex: 1, flexGrow: 1 },
  container: { flex: 1, padding: 24, gap: 12 },
  contentContainer: { padding: 12, backgroundColor: 'white', gap: 8 },
});

```
<img height="400" src="https://github.com/gorhom/react-native-bottom-sheet/assets/24751350/cee569a6-69cd-45ab-8312-ceae85975259" />

expected behavior,
<img height="400" alt="Screenshot 2023-10-05 at 23 20 50" src="https://github.com/gorhom/react-native-bottom-sheet/assets/24751350/8b3a7a0c-a3d2-4e94-b8da-89d14468feb3">

**Comment by sdent-snippr** [comment]
Also having this issue in our app, is there a temporary workaround until a fix is implemented?

**Comment by DenisDov** [comment]
definitely not stale

**Comment by Stenbaek** [comment]
`const App: React.FC = () => {
  const [footerHeight, setFooterHeight] = useState(0);

  const renderFooterComponent = useCallback(() => {
    return (
      <View
        onLayout={(e) => {
          setFooterHeight(e.nativeEvent.layout.height);
        }}
      >
        {Footer}
      </View>
    );
  }, [Footer]);

  return (
    <GestureHandlerRootView style={styles.root}>
      <BottomSheetModalProvider>
        <View style={styles.container}>
          <Button title="Present" onPress={handlePresentPress} />
          <Button title="Dismiss" onPress={handleDismissPress} />
        </View>
        <BottomSheetModal
          ref={bottomSheetRef}
          enableDynamicSizing
          enablePanDownToClose
          backdropComponent={renderBackdrop}
          footerComponent={renderFooterComponent}
        >
          <View style={{ paddingBottom: footerHeight }}>
            <BottomSheetScrollView>
              <View style={styles.contentContainer}>
                <View style={{ height: 50, backgroundColor: "blue" }} />
                <View style={{ height: 50, backgroundColor: "red" }} />
                <View style={{ height: 50, backgroundColor: "green" }} />
              </View>
            </BottomSheetScrollView>
          </View>
        </BottomSheetModal>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

const Footer = () => {
  return (
    <View
      style={{
        height: 50,
        backgroundColor: "yellow",
        justifyContent: "center",
      }}
    >
      <Button title="Dismiss" onPress={() => {}} />
    </View>
  );
};

const styles = StyleSheet.create({
  root: { flex: 1, flexGrow: 1 },
  container: { flex: 1, padding: 24, gap: 12 },
  contentContainer: { padding: 12, backgroundColor: "white", gap: 8 },
});
`

Something like this should work as a workaround

**Comment by Stenbaek** [comment]
```js
const App: React.FC = () => {
  const [footerHeight, setFooterHeight] = useState(0);

  const renderFooterComponent = useCallback(() => {
    return (
      <View
        onLayout={(e) => {
          setFooterHeight(e.nativeEvent.layout.height);
        }}
      >
        {Footer}
      </View>
    );
  }, [Footer]);

  return (
    <GestureHandlerRootView style={styles.root}>
      <BottomSheetModalProvider>
        <View style={styles.container}>
          <Button title="Present" onPress={handlePresentPress} />
          <Button title="Dismiss" onPress={handleDismissPress} />
        </View>
        <BottomSheetModal
          ref={bottomSheetRef}
          enableDynamicSizing
          enablePanDownToClose
          backdropComponent={renderBackdrop}
          footerComponent={renderFooterComponent}
        >
          <View style={{ paddingBottom: footerHeight }}>
            <BottomSheetScrollView>
              <View style={styles.contentContainer}>
                <View style={{ height: 50, backgroundColor: "blue" }} />
                <View style={{ height: 50, backgroundColor: "red" }} />
                <View style={{ height: 50, backgroundColor: "green" }} />
              </View>
            </BottomSheetScrollView>
          </View>
        </BottomSheetModal>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

const Footer = () => {
  return (
    <View
      style={{
        height: 50,
        backgroundColor: "yellow",
        justifyContent: "center",
      }}
    >
      <Button title="Dismiss" onPress={() => {}} />
    </View>
  );
};

const styles = StyleSheet.create({
  root: { flex: 1, flexGrow: 1 },
  container: { flex: 1, padding: 24, gap: 12 },
  contentContainer: { padding: 12, backgroundColor: "white", gap: 8 },
});
```

Something like this I've used as a workaround

**Comment by aymather** [comment]
Is there a clean solution to this yet? I'm having the same problem.

**Comment by abretonc7s** [comment]
the workaround doesnt do the trick for me on beta-11, can we re-open?
