### ISSUE TITLE
App crash in release build when render this library 

### ISSUE THREAD

**Issue by HaseebAbbas6586** [gorhom/react-native-scroll-bottom-sheet#1569]
# Bug

## Environment info

| @gorhom/bottom-sheet            | ^4.5.1  |
| react-native                    |0.72.4  |
| react-native-reanimated         | 3.5.1 |
| react-native-gesture-handler    | 2.12.1  |

## Steps To Reproduce

1.
2.
3. 

Describe what you expected to happen:

1.
2.

**Comment by rajexpleo** [comment]
Hi 
I am also facing same issue. App getting crash on release build not in simulator.

**Comment by rajjerry** [comment]
Hi
@HaseebAbbas6586  Are you able to resolve this issue? As i am also having the same issue.

**Comment by bbialas** [comment]
+1, I have the same. Looks like this library uses an old react-native-reanimated dependency.

**Comment by HaseebAbbas6586** [comment]
> Hi @HaseebAbbas6586 Are you able to resolve this issue? As i am also having the same issue.

i have resolve this error, just add these line of code where you can you bottom sheet 
import {GestureHandlerRootView} from 'react-native-gesture-handler';
and wrap all the component in with 
<GestureHandlerRootView style={{flex: 1}}>
               ...
               ....
               ....
</GestureHandlerRootView>
