### ISSUE TITLE
[v5] Reanimated error on web when use BottomSheetSectionList

### ISSUE THREAD

**Issue by ddx-510** [gorhom/react-native-scroll-bottom-sheet#1571]
# Bug

On the web, when using `BottomSheetSectionList` with a snap points array, once reaches the maximum point, The section list scroll will conflict with the reanimated gesture handler. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^5.0.0-alpha.4 |
| react-native                    | 0.72.4  |
| react-native-reanimated         |~3.3.0   |
| react-native-gesture-handler    | ~2.12.0  |

## Steps To Reproduce

1. Create a modal with `bottomSheetSectionList`, and snap points:  `snapPoints={['60%', "95%"]}`
2. Open up the modal and scroll to the maximum point

Describe what you expected to happen:

1.  **index.js:43 of reanimated** 
```
    Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at index.js:43:12
    at Array.forEach (<anonymous>)
    at _updatePropsJS (index.js:38:11)
    at UpdateProps.js:19:5
    at Set.forEach (<anonymous>)
    at _f (UpdateProps.js:18:9)
    at _f (useAnimatedStyle.js:167:3)
    at Object._f [as worklet] (useAnimatedStyle.js:342:8)
    at mapperRun (mappers.js:83:5)
```
2. The bottom sheet modal after triggering this error, is still scrollable, however, gesture control is gone. Meaning now cannot scroll down nor use `.dismiss()` to dismiss the modal

## Reproducible sample code

On parent view which loads the bottomSheetModal 
```javascript
function renderSectionList() {
    return (
        <BottomSheetModal
            ref={listModalRef}
            index={0}
            snapPoints={['60%', "95%"]}
            style={styles.modalContainer}
            keyboardBehavior="extend"
            backdropComponent={renderBackdrop}
        >
            <MyList modalRef={listModalRef} />
        </BottomSheetModal>
    );
}

```

**BackDrop:**
```javascript
const renderBackdrop = useCallback(
    (props: JSX.IntrinsicAttributes & BottomSheetDefaultBackdropProps) => (
        <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} />
    ),
    []
);

```
**MyList:**

```javascript
<>
    <BottomSheetTextInput
        style={{
            margin: 10,
            borderRadius: 10,
            fontSize: 16,
            lineHeight: 20,
            padding: 8,
            backgroundColor: Colors.grey60,
        }}
        placeholder={'Test search input bar'}
    />
    <BottomSheetSectionList
        style={{ flex: 1, minHeight: WINDOW_HEIGHT }}
        sections={getSections()} // getSections() here could be any valid sections
        keyExtractor={(item) => item.id.toString()}
        renderItem={({ item }) => renderListItem(item)} // renderListItem(item) cld be any valid components
        renderSectionHeader={({ section: { title } }) =>
            <Text style={{ fontSize: 14, fontWeight: 'bold', color: Colors.grey40 }}>{title}</Text>}
    />
</>

```

Commenting out the BottomSheetSectionList will make the issue disappear. Thus the issue should be some conflicts between BottomSheetSectionList scrolling and reanimated gestures.

**Comment by DCarmona18** [comment]
Any updated on this?

I'm facing also this issue on Web

**Comment by vladimirevstratov** [comment]
seems like this library doesnt support web normally at this moment, i am using native modal from react-native for web part now.
