### ISSUE TITLE
[v4] | [v2] Invariant Violation on calling snapToIndex(1) on mount in version 4.5.1

### ISSUE THREAD

**Issue by leymytel** [gorhom/react-native-scroll-bottom-sheet#1572]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.5 |
| react-native-reanimated         |  3.5.4   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Upgrade to version `4.5.1`.
2. Set up a BottomSheet component with at least two snap points.
3. Use a `useEffect` hook to call `snapToIndex(1)` on mount.

```javascript
useEffect(() => {
    bottomSheetRef.current?.snapToIndex(1);
}, []);
```

## Describe what you expected to happen:

- The BottomSheet should attempt to snap to the specified index on mount without throwing an error.
- No Invariant Violation error should occur.

## Reproducible sample code
```javascript
import React, { useEffect, useRef } from 'react';
import BottomSheet from '@gorhom/bottom-sheet';
// ... other imports

const MyComponent = () => {
  const bottomSheetRef = useRef(null);

  useEffect(() => {
      bottomSheetRef.current?.snapToIndex(1);
  }, []);

  return (
    <BottomSheet
      ref={bottomSheetRef}
      snapPoints={[450, 300]}
      // ...other props
    >
      {/* ...children */}
    </BottomSheet>
  );
};

export default MyComponent;
```

**Comment by h3d0** [comment]
I can confirm the bug.

This can be monkey-patched like:

```
setTimeout(() => {
    refToSheet.current?.snapToIndex(1);
}, 100);
```

But obviously one should not resolve it like this as the time may very and the bug may occur. It looks like the instance of the modal is not fully available during `useEffect`. I did not investigate this further as I have no time for it, but I've noticed the are already couple of threads that were open for this and it was not addressed yet.

**Comment by jinsung-kim** [comment]
+1

**Comment by jessicazu** [comment]
+1

**Comment by jessicazu** [comment]
I also needed to execute `snapToIndex` upon mounting. To achieve this, I created a component that wraps the `BottomSheet` and introduced an active variable. By passing the value to the `index` field when `active` is true, I was able to make it snap from the moment of mounting.

```ts
import * as BottomSheetBase from '@gorhom/bottom-sheet';
...
const BottomSheet = ({
  navigator,
  initialSnapPoint,
  active,
}: BottomSheetProps) => {
  const snapPoints = useMemo(() => ['1%', '60%', '90%', '95%'], []);
  const ref = useRef<BottomSheetBase.default>(null);

  ...

  useEffect(() => {
    if (active) {
      ref.current?.snapToIndex(initialSnapPoint);
    } else {
      ref.current?.close();
    }
  }, [active, initialSnapPoint]);

  const styles = createStyle();

  return (
    <BottomSheetBase.default
      ref={ref}
      snapPoints={snapPoints}
      topInset={0}
      index={active ? initialSnapPoint : -1} // Here
      backdropComponent={props => (active ? CustomBackdrop({...props}) : null)}
      onChange={handleSheetChanges}>
      {active && (
        <BottomSheetBase.BottomSheetView style={styles.container}>
          {navigator}
        </BottomSheetBase.BottomSheetView>
      )}
    </BottomSheetBase.default>
  );
};
```
