### ISSUE TITLE
[v4] | Bottom sheet doesn't show in release mode on android 8

### ISSUE THREAD

**Issue by vladimir-vucetic** [gorhom/react-native-scroll-bottom-sheet#1574]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | ~3.3.0  |
| react-native-gesture-handler    | ~2.12.0   |

## Steps To Reproduce

I use expo 49. 
I implemented bottom sheet by code bellow.
I test in debug mode on android 8 and it work fine.
When I build app with `--variant=release` bottom sheet doesn't show up anymore and when I press action to open it I can't press anything else on the screen any more.

Describe what you expected to happen:
To work on android in release mode

## Reproducible sample code
```
import { BottomSheetBackdrop, BottomSheetModal, BottomSheetModalProvider } from "@gorhom/bottom-sheet";


const ProfileSpaceScreen: React.FC<Props> = ({ route }) => {

const bottomSheetRef = useRef<BottomSheetModal>(null);
const snapPoints = useMemo(() => ["80%"], []);

return (
    <BottomSheetModalProvider>
      <AppHeader />
      <View style={[styles.container, styles.content]}>{renderContent()}</View>
      <BottomSheetModal
        backdropComponent={(props) => <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} />}
        ref={bottomSheetRef}
        index={0}
        snapPoints={snapPoints}
      >
        <View>
          <UserReviews />
        </View>
      </BottomSheetModal>
    </BottomSheetModalProvider>
  );
}

export default ProfileSpaceScreen;
```

**Comment by trungledangAxonActive** [comment]
I'm facing this issue too. But the first time installing and launching the app. The bottom sheet will disappear, often happens on Android devices.

**Comment by joacub** [comment]
same here

**Comment by Risina** [comment]
Facing the same issue here

**Comment by nihilenz** [comment]
Also observed on a device running Android 10, I think it's related to https://github.com/gorhom/react-native-bottom-sheet/issues/1560

**Comment by sommcz** [comment]
I have the same problem on Android 13 with reduced animation setting.

"react-native-reanimated": "3.5.4"
"@gorhom/bottom-sheet": "4.5.1"

Fixed with this solution: https://github.com/gorhom/react-native-bottom-sheet/issues/1560#issuecomment-1750466864

**Comment by codeSupreme** [comment]
Anyone solve this yet? We are facing the same thing.

**Comment by tcdw** [comment]
Facing the same issue, except I did not enable reduce animation on my device 😢

```
    "@gorhom/bottom-sheet": "^4.5.1",
    "expo": "~49.0.8",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
```

**Comment by mmkhmk** [comment]
I'm facing the same issue.

**Comment by Marcados** [comment]
Same issue. Very inconsistent behaviour of the bottom-sheet showing only one time out of 5.

**Comment by nihilenz** [comment]
not stale

**Comment by emanusantos** [comment]
Same issue here

**Comment by Andrey123815** [comment]
I also encountered such a problem at react native expo after updating to version 49, and only on Android and only in pro mode (everything works fine in dev via Expo Go). On ios, everything works out as it should

**Comment by anastasesg** [comment]
Same issue here

**Comment by iusama46** [comment]
This worked for me

const reducedMotion = useReducedMotion();

animateOnMount={!reducedMotion}

**Comment by snicro** [comment]
> Facing the same issue, except I did not enable reduce animation on my device 😢
> 
> ```
>     "@gorhom/bottom-sheet": "^4.5.1",
>     "expo": "~49.0.8",
>     "react-native-gesture-handler": "~2.12.0",
>     "react-native-reanimated": "~3.3.0",
> ```

Same for me on Android. No expo. No reduced motion enabled.

**Comment by next6leo** [comment]
same also

**Comment by nihilenz** [comment]
not stale

**Comment by nihilenz** [comment]
not stale

**Comment by geikobogdan** [comment]
facing same issue on Android, on IOS all works good. RN - 0.73.4, expo - 50.0.11

**Comment by The4star** [comment]
I'm having the same issue on android, the bottom sheet won't show at all, works perfectly on ios.
```
"expo": "~51.0.14",
"react-native-gesture-handler": "^2.16.2",
"@gorhom/bottom-sheet": "^4.6.3",
"react-native-reanimated": "~3.10.1",
```

**Comment by nihilenz** [comment]
not stale

**Comment by imraann00** [comment]
anyone have a solution ?

**Comment by The4star** [comment]
My solution was to use the bottom sheet on ios and go with a seperate custom modal on android.

**Comment by Tamimjabr** [comment]
not stale

**Comment by nihilenz** [comment]
not stale

**Comment by Chinedu25** [comment]
any fix on android?
