### ISSUE TITLE
[v4] Bottomsheet closes and then reopens immediately.

### ISSUE THREAD

**Issue by iArchin** [gorhom/react-native-scroll-bottom-sheet#1583]
# Bug

I have the same problem as [this](https://github.com/gorhom/react-native-bottom-sheet/discussions/1160#discussion-4520896) user asked in the discussion with an example video, anyone can help me with it?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4  |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.3.0  |
| react-native-gesture-handler    | 2.10.2   |

## Steps To Reproduce

1.also available [here](https://github.com/gorhom/react-native-bottom-sheet/discussions/1160#discussion-4520896)
2.
3. 

Describe what you expected to happen:

1. bottomsheet close.
2.

## Reproducible sample code

available [here](https://github.com/gorhom/react-native-bottom-sheet/discussions/1160#discussion-4520896)

**Comment by karam1ashqar** [comment]
+1, happens when i change the state in OnChange prop

**Comment by baesumin** [comment]
+1

**Comment by reflash** [comment]
Having the same issue on android only. Happens only with keyboard restore and after keyboard was opened. Using 4.5.1 version of the lib

**Comment by nateguy** [comment]
Yes, I'm having an issue with this on android. Seems Keyboard needs to be dismissed entirely before BottomSheet can be dismissed.

**Comment by fendermany** [comment]
Same problem with keyboard, only can fixed using setTimeout
