### ISSUE TITLE
Android build.gradle crash v4.5.1

### ISSUE THREAD

**Issue by wilav-dev** [gorhom/react-native-scroll-bottom-sheet#1595]
Build file '..../react_native/node_modules/react-native-bottom-sheet/android/build.gradle' line: 38

A problem occurred evaluating project ':react-native-bottom-sheet'.
> Could not find method compile() for arguments [com.android.support:appcompat-v7:23.0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Any idea?

**Comment by roots-ai** [comment]
Any updates here?

**Comment by egecetiner** [comment]
in build.gradle file compile --> implementation will fix the problem.

**Comment by dazza5000** [comment]
Is this something we can fix in this repo?

**Comment by jacoblyles** [comment]
This is still a problem for me

**Comment by devhik0** [comment]
Its still a problem for me with same output
