### ISSUE TITLE
[v4] Cannot read property 'value' of undefined when using BottomSheetBackdrop on BottomSheetModal

### ISSUE THREAD

**Issue by davidlintin** [gorhom/react-native-scroll-bottom-sheet#1606]
# Bug

When using BottomSheetModal I am rendering a simple BottomSheetBackdrop Component and getting the below Render Error

<img width="325" alt="Screenshot 2023-10-31 at 14 25 13" src="https://github.com/gorhom/react-native-bottom-sheet/assets/102983993/3cf4accb-b060-4d79-9876-f4b0334428f1">

I have installed the packages '@gorhom/bottom-sheet', 'react-native-reanimated' & 'react-native-gesture-handler' using npx expo install

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.5.1   |
| react-native                    | 0.72.5   |
| react-native-reanimated         | ~3.3.1   |
| react-native-gesture-handler    | ~2.12.0   |

## Steps To Reproduce

I tried to use the snack link in the instructions however, I had no such luck with generating the snack from the template [here](https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template). So I created a minimal repo creating the issue. Which can be found [here](https://github.com/davidlintin/bottom-sheet-test).

Describe what you expected to happen:

1. The overlay should appear when the modal is presented.
2. The overlay should disappear when the modal is dismissed.

## Reproducible sample code

Github repo [here](https://github.com/davidlintin/bottom-sheet-test).

**Comment by CleverFlare** [comment]
You've probably forgot to pass the props to the `BottomSheetBackdrop` component.
Here is an example snippet:
```JS
const renderBackdrop =
useCallback(props => <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} />, []);
```
I know I'm almost a year late, but I thought this comment might be helpful to someone visiting this issue in the near future.
