### ISSUE TITLE
When is v5 comming?

### ISSUE THREAD

**Issue by valerarusu7** [gorhom/react-native-scroll-bottom-sheet#1611]

**Comment by UrsDeSwardt** [comment]
How is it going with this?

**Comment by lichstam** [comment]
i'm wondering the same!

**Comment by manuthecoder** [comment]
Install the pre-release versions at your own risk (there's bugs)

**Comment by gorhom** [comment]
> Install the pre-release versions at your own risk (there's bugs)

Could you share some of these bugs in tickets and I would be happy fix them :)

**Comment by nileshzype** [comment]
1+

**Comment by Rhym** [comment]
@gorhom Thanks for al your work on this, I see version 5.X gets rid of the `useBottomSheetDynamicSnapPoints` hook. Any guidance on how that will be handled in the new version?

**Comment by gorhom** [comment]
> @gorhom Thanks for al your work on this, I see version 5.X gets rid of the `useBottomSheetDynamicSnapPoints` hook. Any guidance on how that will be handled in the new version?

It should be enabled by default, you could remove all the variables provided from the hook.

I will add this into the documentation!
