### ISSUE TITLE
[v4] Trying to expand bottom sheet modal with present method crashes application

### ISSUE THREAD

**Issue by paulschoen** [gorhom/react-native-scroll-bottom-sheet#1612]
# Bug

I have set my `GestureHandlerRootView` and `BottomSheetModalProvider` at the root of the project.

When calling `bottomSheetRef.current?.present();` app crashes with the following error:

```
ERROR  Error: [Reanimated] Trying to convert a cyclic object to a shareable. This is not supported.

This error is located at:
    in BottomSheet (created by BottomSheet)
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by VehicleList)
    in VehicleList (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by RootStack)
    in RootStack (created by RootNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by RootNavigator)
    in RootNavigator (created by App)
    in ApolloProvider (created by MobileApolloClientProvider)
    in MobileApolloClientProvider (created by App)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in ErrorBoundary (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.4  |
| react-native-reanimated         | 3.5.4   |
| react-native-gesture-handler    | 2.13.4   |

## Steps To Reproduce

1. Attempt to open bottom sheet modal with `bottomSheetRef.current?.present()`

Describe what you expected to happen:

1. Bottom Sheet Modal should slide up.

**Comment by MoritzCooks** [comment]
As mentioned in the [feature list](https://gorhom.github.io/react-native-bottom-sheet/#features) `react-native-bottom-sheet` is only working with reanimated v1 & v2.

Try downgrading reanimated to v2:
`yarn upgrade react-native-reanimated@^2`

Also install pods again (if needed). 
I additionally cleared metro cache by running `yarn start --reset-cache`

**Comment by paulschoen** [comment]
I appreciate your input and the suggestion to downgrade reanimated to v2. I refrained from downgrading reanimated to v2 because I noticed that other users were successfully using reanimated v3 without any problems. It led me to explore other potential solutions, and I found that changing the import to "@gorhom/bottom-sheet/src" addressed the issue in my specific case, which seemed to be related to Metro.

**Comment by matifriaz** [comment]
I am also facing this issue on @gorhom/bottom-sheet@4.4.8. Did we find any solution for this?

**Comment by matifriaz** [comment]
I have also tried upgrading it to alpha version which uses reanimated@3.6. But that also didn't work.

**Comment by MilanJimi** [comment]
Facing this issue in 
```
    "@gorhom/bottom-sheet": "5.0.0-alpha.7",
    "react-native": "0.73.4",
    "react-native-gesture-handler": "2.15.0",
    "react-native-reanimated": "3.7.0",
```
I haven't the slightest what is causing this

**Comment by rorydbain** [comment]
Also hit this issue! Updating the imports as suggested above works, but then running into some problems with typescript errors

**Comment by flo-sch** [comment]
I am facing the issue as well with v5.0.0-alpha.9:

Library | Version
-- | --
@gorhom/bottom-sheet | 5.0.0-alpha.9
react-native | 0.71.16
react-native-reanimated | 3.6.1
react-native-gesture-handler | 2.14.0

**Comment by moniquealtero** [comment]
> I appreciate your input and the suggestion to downgrade reanimated to v2. I refrained from downgrading reanimated to v2 because I noticed that other users were successfully using reanimated v3 without any problems. It led me to explore other potential solutions, and I found that changing the import to "@gorhom/bottom-sheet/src" addressed the issue in my specific case, which seemed to be related to Metro.

This solved my issue, I only changed the import to "@gorhom/bottom-sheet/src"

**Comment by MrCox007** [comment]
Same issue here when using react native storybook

**Comment by ikotsur** [comment]
> I appreciate your input and the suggestion to downgrade reanimated to v2. I refrained from downgrading reanimated to v2 because I noticed that other users were successfully using reanimated v3 without any problems. It led me to explore other potential solutions, and I found that changing the import to "@gorhom/bottom-sheet/src" addressed the issue in my specific case, which seemed to be related to Metro.

Thank you very much!!! ❤️ It works for me now
