### ISSUE TITLE
[v4] | Bottom Sheet isn't rendering in a flexbox

### ISSUE THREAD

**Issue by ishaanbuildsthings** [gorhom/react-native-scroll-bottom-sheet#1618]
# Bug

I'm sure I'm doing something wrong. I'm trying to get my BottomSheet to show up while being inside a div. My bottom sheet doesn't visually display when I place it inside a root div, but it does when I remove that root div. The bottom sheet does render/run though, I just cannot see it.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.6   |
| react-native-reanimated         | 3.5.4   |
| react-native-gesture-handler    | 2.13.4  |

## Steps To Reproduce

1. Render the bottom sheet inside a parent component as such.
2. Use the below bottom sheet sample code.

Describe what you expected to happen:

1. I expect the bottom sheet to visually display as I believe I followed the documentation example.

## Reproducible sample code

```
const Styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
  },
});

export default function PostComments({onCloseComments}: Props) {
  const bottomSheetRef = React.useRef<BottomSheet>(null);

  return (
    <Box style={Styles.root}>
      <BottomSheet
        enablePanDownToClose
        onClose={onCloseComments}
        ref={bottomSheetRef}
        index={0}
        snapPoints={['50%']}
      >
        <BottomSheetScrollView contentContainerStyle={Styles.contentContainer}>
          {myData.map(datum => <MyComponent />}
        </BottomSheetScrollView>
      </BottomSheet>
    </Box>
  );
}
```

**Comment by justin-waves** [comment]
I'm also experiencing this bug:

```
<View style={styles.container}>
  <BottomSheet
      ref={bottomSheetRef}
      index={1}
      snapPoints={snapPoints}
      enablePanDownToClose
      onChange={handleSheetChanges}
      isVisible={showCreateSheet}
  >
      <View style={styles.contentContainer}>
          <Text style={{ color: "white" }}>Awesome 🎉</Text>
      </View>
  </BottomSheet>
</View>

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
        backgroundColor: "grey",
    },
    contentContainer: {
        flex: 1,
        alignItems: "center",
    },
});
```

![Simulator Screenshot - iPhone 14 Pro - 2023-11-17 at 17 32 06](https://github.com/gorhom/react-native-bottom-sheet/assets/136510107/3114229f-cdc0-4067-8d9a-072ca82bb268)

**Comment by carantes** [comment]
I am experiencing the same issue here. The issue is only happening when running it physically on my iOS device. I believe the main issue is the library is not compatible with reanimated 3x

@gorhom/bottom-sheet | 4.4.8
-- | --
react-native | 0.71.7
react-native-reanimated | 3.5.4
react-native-gesture-handler | 2.9.0
