### ISSUE TITLE
[v4] Problem with FlatList

### ISSUE THREAD

**Issue by alejandro-geeksquare** [gorhom/react-native-scroll-bottom-sheet#1621]
I am using FlatList within BottomSheet as the documentation indicates, I am using the "react-native-gesture-handler" package because otherwise it does not allow interaction with the list. But it still works badly like with lag

**Comment by VovaParamonov** [comment]
I guess you should use (BottomSheetFlatList) instead of (BottomSheetView -> FlatList)
