### ISSUE TITLE
[Question] What is the difference between BottomSheet and BottomSheetModal?

### ISSUE THREAD

**Issue by z1haze** [gorhom/react-native-scroll-bottom-sheet#1626]
Hi, I'm pretty new to RN, so apologies, but I've found your package while trying to come up with a solution to present a picker in a bottom sheet when a user clicks a button or something like that. I've been reading your documentation trying to understand the difference between the BottomSheet itself and the BottomSheetModal, but I cannot see the difference? Is the only difference is that it can be "activated" via clicking a button?

**Comment by pastelmind** [comment]
This has been answered here: https://github.com/gorhom/react-native-bottom-sheet/discussions/668
