### ISSUE TITLE
[v4] Function components cannot have string refs

### ISSUE THREAD

**Issue by vaibhavverma9** [gorhom/react-native-scroll-bottom-sheet#1633]
# Bug
I am getting the following bug when I try using Bottom Sheet in an Expo project:

Error: Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref

This error is located at:
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.72.6   |
| react-native-reanimated         | ~3.3.0  |
| react-native-gesture-handler    | ~2.12.0   |

## Steps To Reproduce

1. Create new Expo project
2. Download all the BottomSheet dependencies. Your package.json will look like this:
```
{
  "name": "bottom-sheet-flatlist-testing",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```
3. Run “npx expo start” and open app in Expo Go 
4. Bug happens 

Describe what you expected to happen:

1. Bottom Sheet with FlatList should work as expected in the doc here: https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetflatlist

## Reproducible sample code
https://github.com/vaibhavverma9/bottom-sheet-flatlist-testing

**Comment by famdude** [comment]
what's going on in all github repos issues? why is this being closed without being fixed?

**Comment by GouravAppeneure** [comment]
> # Bug
> I am getting the following bug when I try using Bottom Sheet in an Expo project:
> 
> Error: Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref
> 
> This error is located at: in RCTView (created by View) in View (created by App) in App (created by withDevTools(App)) in withDevTools(App) in RCTView (created by View) in View (created by AppContainer) in RCTView (created by View) in View (created by AppContainer) in AppContainer in main(RootComponent), js engine: hermes
> 
> ## Environment info
> Library	Version
> @gorhom/bottom-sheet	^4
> react-native	0.72.6
> react-native-reanimated	~3.3.0
> react-native-gesture-handler	~2.12.0
> ## Steps To Reproduce
> 1. Create new Expo project
> 2. Download all the BottomSheet dependencies. Your package.json will look like this:
> 
> ```
> {
>   "name": "bottom-sheet-flatlist-testing",
>   "version": "1.0.0",
>   "main": "node_modules/expo/AppEntry.js",
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "web": "expo start --web"
>   },
>   "dependencies": {
>     "@gorhom/bottom-sheet": "^4",
>     "expo": "~49.0.15",
>     "expo-status-bar": "~1.6.0",
>     "react": "18.2.0",
>     "react-native": "0.72.6",
>     "react-native-gesture-handler": "~2.12.0",
>     "react-native-reanimated": "~3.3.0"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.20.0"
>   },
>   "private": true
> }
> ```
> 
> 3. Run “npx expo start” and open app in Expo Go
> 4. Bug happens
> 
> Describe what you expected to happen:
> 
> 1. Bottom Sheet with FlatList should work as expected in the doc here: https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetflatlist
> 
> ## Reproducible sample code
> https://github.com/vaibhavverma9/bottom-sheet-flatlist-testing

for removing the error this is the solution 
you have to wright use ref code like this   const bottomSheetRef = useRef(null);

**Comment by MikePendo** [comment]
Same issue
