### ISSUE TITLE
[v4] [android]  Typing a number as the first character to an input within the Bottom Sheet forces the keyboard back to alpha keyboard

### ISSUE THREAD

**Issue by ziagrosvenor** [gorhom/react-native-scroll-bottom-sheet#1634]
# Bug

NOTE: This issue occurs on Android devices

Typing a number as the first character to an input within the Bottom Sheet forces the keyboard back to alpha keyboard

## Description

On Android devices, When attempting to input a numerical value in an input field within the `@gorham/bottom-sheet` component, if the first character entered is a number, the keyboard switches back to the alpha keyboard automatically. This behavior is unexpected and may cause confusion for users.

https://github.com/gorhom/react-native-bottom-sheet/assets/7994099/3297221d-0b86-4cd2-818b-b5d5ac20ef1e

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.72.6  |
| react-native-reanimated         | ~3.3.0   |
| react-native-gesture-handler    | ~2.12.0   |

## Steps To Reproduce

1. Open the bottom sheet containing an input field
2. Tap on the input field.
3. Attempt to input a number as the first character
4. See it jumps back to alphabet keyboard

Describe what you expected to happen:

1. Open the bottom sheet containing an input field
2. Tap on the input field.
3. Attempt to input a number as the first character
4. Type as many numbers as required. 

## Reproducible sample code

https://github.com/ziagrosvenor/modal-sheet-input-issue-example/blob/main/App.js

**Comment by lathomas64** [comment]
any idea what causes this to be happening?
