### ISSUE TITLE
[v4] How Detect Botom Sheet is Open

### ISSUE THREAD

**Issue by ajiehatajie** [gorhom/react-native-scroll-bottom-sheet#1637]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1  |
| react-native                    | 0.71.12  |
| react-native-reanimated         | 3.4.2  |
| react-native-gesture-handler    | 2.13.4   |

## Steps To Reproduce

1. in Screen I have 2 Bottom Sheet
2. Bottom Sheet A with Codition an open

Describe what you expected to happen:

1. in Screen I have 2 Bottom Sheet
2. Bottom Sheet A with Codition an
3. Press Backhandler  Android or swipe IOS detect bottom Sheet is open then close

**Comment by beqramo** [comment]
Hi,
bottomsheet has its own listener prop => `onChange`
