### ISSUE TITLE
 [v4] When Talkback is enabled and a modal is displayed, the items below the modal sheet are still accessible by tap and the sheet is not focused

### ISSUE THREAD

**Issue by bekatd** [gorhom/react-native-scroll-bottom-sheet#1641]
# Bug

1. When `Talkback` is enabled Modal is not focused when presented
2. Elements below the Modal are accessible
3. When dismissing modal, elements are no longer accessible/focusable (no green marker around them and no announcements)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1 |
| react-native                    | 0.72.3 |
| react-native-reanimated         | 3.5.4 |
| react-native-gesture-handler    | 2.13.4 |

## Steps To Reproduce

1. When `Talkback` is enabled Modal is not focused when presented
2. Elements below the Modal are accessible
3. When dismissing modal, elements are no longer accessible/focusable (no green marker around them and no announcements)

Describe what you expected to happen:

1. When `Talkback` is enabled, if user opens Modal, it should get focus automatically
2. Elements below the Modal should not be accessible by default (some prop needed maybe)
3. After dismissing Modal, elements that were below it should be accessible/focusable again

## Reproducible sample code
NA

**Comment by instesti** [comment]
Yeah so this is still an issue, where the talkback skips children of the bottom-sheet and reads the backdrop instead. Any update on how to solve this? Currently it breaks a lot of accessibility wise

@gorhom

**Comment by hraschan** [comment]
This is still an issue. It is possible to make the content reachable by setting the BottomSheetModal to `accessible={false}` as mentioned in #1764 . But the elements behind the Bottom Sheet are still accessible. Only appears on android.

I'm really looking forward for this getting fixed. Is it possible to reopen this issue? @gorhom

**Comment by Hosam-hsm** [comment]
@hraschan @instesti  Were you able to find a solution to this issue?

**Comment by hraschan** [comment]
Sadly not.

**Comment by stevegreen99** [comment]
This issue occurs if dialogs are not launched using the showModal() method. It's best to implement the dialog using a <dialog> element because it has all the required behaviours built in. The role="dialog" attribute can also be used. If you do anything else, you will need to hide all the content outside the dialog using the "inert" attribute, but the dialog must not be inside an element with that attribute. This is all explained on the MDN website.

**Comment by Tamimjabr** [comment]
Same problem here
