### ISSUE TITLE
 no matches found: @gorhom/bottom-sheet@^4

### ISSUE THREAD

**Issue by dytra** [gorhom/react-native-scroll-bottom-sheet#1645]
# Bug

I want to install this library but it shows an error: `no matches found: @gorhom/bottom-sheet@^4`

## Environment info

mac os 11.6.5
react-native ^0.62.2
"react-native-reanimated": "^1.9.0",
"react-native-gesture-handler": "^1.6.1",

## Steps To Reproduce

executing the command:

`yarn add @gorhom/bottom-sheet@^4`

**Comment by kmagnusj** [comment]
I've had the same issue today. I started up a simple react-native project and, not having added anything else to the project, run `yarn add @gorhom/bottom-sheet@^4` and then get the error `zsh: no matches found: @gorhom/bottom-sheet@^4`

**Comment by DmytroPetryhan** [comment]
Try this:    yarn add "@gorhom/bottom-sheet@^4"
