### ISSUE TITLE
[v4] | [v2] Picker not working on Android

### ISSUE THREAD

**Issue by Georg7** [gorhom/react-native-scroll-bottom-sheet#1646]
# Bug

Using https://github.com/react-native-picker/picker to display a picker in the bottom sheet (works on iOS but not on Android). 

On Android I can see the Picker label but when i click on it it's not opening. The picker library offers 2 modes (dropdown, dialog). Neither of these options work. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1  |
| react-native                    | 0.72.6   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0  |

## Steps To Reproduce

[Test on Android]
1. Open the bottom sheet
2. Click on the Picker item
3. No Picker modal/dropdown showing

Describe what you expected to happen:

1. Picker modal/dropdown should show

## Reproducible sample code
```
import React, { useMemo, useRef, useCallback } from 'react';
import { View, StyleSheet } from 'react-native';
import BottomSheet, { enableLogging } from '@gorhom/bottom-sheet';
import List from './components/List';
import SearchHandle from './components/SearchHandle';
import Button from './components/Button';
import { Picker } from "@react-native-picker/picker";

enableLogging();

const App = () => {
  // refs
  const bottomSheetRef = useRef(null);

  // variables
  const snapPoints = useMemo(() => [200], []);

  // callbacks
  const handleExpandPress = useCallback(() => {
    bottomSheetRef.current?.expand();
  }, []);
  const handleCollapsePress = useCallback(() => {
    bottomSheetRef.current?.collapse();
  }, []);
  const handleClosePress = useCallback(() => {
    bottomSheetRef.current?.close();
  }, []);

  return (
    <View style={styles.container}>
      <Button onPress={handleExpandPress} title="Expand" />
      <Button onPress={handleCollapsePress} title="Collapse" />
      <Button onPress={handleClosePress} title="Close" />
      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        keyboardBehavior="interactive"
        handleComponent={SearchHandle}
        animateOnMount={true}
        android_keyboardInputMode="adjustPan">
        <List type="FlatList" />
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 64,
    justifyContent: 'flex-start',
    backgroundColor: '#222',
  },
});

export default App;
```

**Comment by javaing** [comment]
In my case, Picker inside of BottomSheet is not shown Picker.Item, but BottomSheet to <BottomSheetModalProvider>
      <BottomSheetModal> is work for me.
