### ISSUE TITLE
A bottom sheet opening from the top to the bottom of the screen

### ISSUE THREAD

**Issue by sepsol** [gorhom/react-native-scroll-bottom-sheet#1651]
# Feature Request

Pretty much self-explanatory :)

## Why it is needed

Because there might be occasions where some information is not that necessary and might be better if it's tucked away further out of reach. Therefore, reaching for a handle at the top of the screen (to open a top sheet) might be desired more than reaching for a handle at the bottom of the screen (to open a bottom sheet).

## Possible implementation

I really don't know

### Code sample

I don't know, sorry

**Comment by sepsol** [comment]
bump

**Comment by sepsol** [comment]
bump

**Comment by sepsol** [comment]
bump

**Comment by jurij** [comment]
bump

**Comment by aymather** [comment]
Also looking for this feature <3

**Comment by philemonpeter02** [comment]
Much needed
