### ISSUE TITLE
[v4] TypeError with 'BottomSheetModalProvider' after Upgrading to React Native 0.73

### ISSUE THREAD

**Issue by tmcyrix** [gorhom/react-native-scroll-bottom-sheet#1653]
# Bug

After upgrading my React Native project from version 0.72 to 0.73, I am encountering a TypeError with the **@gorhom/bottom-sheet** library. The error is: **TypeError: Cannot read property 'BottomSheetModalProvider' of undefined**. This issue did not occur in the previous version of React Native. I have tried clearing the cache, reinstalling the node modules, and ensuring the import statements are correct, but the error persists.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.73.0   |
| react-native-reanimated         | 3.6.1   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Upgrade React Native from 0.72 to 0.73.
2. Import and use the BottomSheetModalProvider from @gorhom/bottom-sheet in App.tsx.
3. Run the application.

Describe what you expected to happen:

1. The application should run without encountering the TypeError.
2. BottomSheetModalProvider should be imported correctly as it was in the previous version of React Native.

## Reproducible sample code

```import React from "react";
import { StatusBar } from "react-native";
import { BottomSheetModalProvider } from "@gorhom/bottom-sheet";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const App = () => {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <BottomSheetModalProvider>
        {/* Your navigation component or a simple Text component can go here for testing */}
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

export default App;
```

**Comment by KirillCustom** [comment]
React Native 0.73.1 will fix the problem related to Reanimated. After installing the patch for version 0.73.0, I lost this problem.
[Related issue](https://github.com/software-mansion/react-native-reanimated/issues/5472#issuecomment-1845215549)

**Comment by adityacarnera** [comment]
I am facing the same issue my react-native version is 0.73.6 and  "@gorhom/bottom-sheet": "^4.6.1"

**Comment by katerynakostikova** [comment]
Are there any updates on how to fix the issue?

**Comment by mmplanet** [comment]
Bump, facing the same issue.

**Comment by Evan-Fisher** [comment]
Same here! This is the last bug of so many by upgrading react-native. Anyone know if native is just the better way to build an app?

**Comment by Evan-Fisher** [comment]
I got it working for me. I like an idiot had been gitignoring my package-lock.json so I don't know what my peerDep version was for reanimated when this initially worked. I assumed when I upgraded react-native it upped my version of reanimated which gorhom uses. I [installed reanimated version 3.6.3](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#installation) (from feb when this initially worked) to be used in gorhom. The error went away. I don't have time to look into more right now, but maybe that can help some of you!

ps: Make sure to add `react-native-reanimated/plugin` to your babel.config

@mmplanet @katerynakostikova @adityacarnera @tmcyrix

**Comment by beneditomauro** [comment]
I am still having this issue for a long time trying to fix it. None of the responses here worked

**Comment by thongle12** [comment]
Any updated yet?

**Comment by sourabhpatil365** [comment]
Same issue for me. im using my react-native version is 0.73.5

**Comment by Adhri14** [comment]
Same issue for me, im using on my project react-native version is 0.78.2

**Comment by js-ojha** [comment]
Same issue for me, But if I remove the BottomSheetModalProvider my app works. I am using these versions :
"react-native-reanimated": "^3.17.4",
"react-native": "0.79.0",
"@gorhom/bottom-sheet": "^5.1.2",
"react-native-gesture-handler": "^2.25.0",

**Comment by therbta** [comment]
_Same issue I'm facing._ 

```
"@gorhom/bottom-sheet": "^5.1.6",
"react-native-reanimated": "^3.18.0",
"react-native-gesture-handler": "^2.25.0",
"react-native": "0.79.3",
```

**

> UPDATE:

**
Well, I found out the issue (at least it worked for me). I was having trouble with `AppDelegate.swift`, and I fixed it, so that resolved the problem as well.

**Comment by omar-bear** [comment]
use reanimated version `react-native-reanimated` 3.9.0 and remove the wrapper `wrapWithReanimatedMetroConfig` inside the metro config it works for me
