### ISSUE TITLE
enableDynamicSizing property closing the modal automatically on orientation changes if the content having less

### ISSUE THREAD

**Issue by vinaykumar0339** [gorhom/react-native-scroll-bottom-sheet#1655]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    |  0.72.7  |
| react-native-reanimated         |  3.6.1  |
| react-native-gesture-handler    |  2.12.1   |

## Steps To Reproduce

1. use enableDynamicSizing for dynamic content height.
2. add some less content like 25% of the screen of height
3. now change the orientation to landscape (in iPad)

Describe what you expected to happen:

1. it should not close the bottom sheet it should be at same snap index

## Reproducible sample code

import React, { useCallback, useMemo, useRef } from 'react';
import PropTypes from 'prop-types';
import { View, StyleSheet } from 'react-native';
import { Portal } from '@gorhom/portal';
import BottomSheet,
{ BottomSheetBackdrop, BottomSheetScrollView } from '@gorhom/bottom-sheet';

import Draggable from '../calendar/draggable';
import FormButtons from './form.buttons';
import { keys, strings } from '../resources/strings/translations';

const BottomSheetPortal = ({
    children,
    resetModal,
    draggable,
    showButtons,
    positiveText,
    negativeText,
    onPress,
    swipeDisabled,
    testID,
    onSkip,
    showHandleComponent,
    enableDynamicSizing,
    disableButton,
    hostName,
}) => {
    const bottomSheetRef = useRef(null);
    // if dynamic content is false then render the form 90% of the screen.
    const snapPoints = useMemo(() => ['90%'], []);

    const onClose = useCallback(() => {
        resetModal?.();
        onSkip?.();
        bottomSheetRef.current?.close?.();
    }, [onSkip, resetModal]);

    const renderBackdrop = useCallback(
        props => (
            <BottomSheetBackdrop
                {...props}
                opacity={1}
                disappearsOnIndex={-1}
                pressBehavior={swipeDisabled ? 'none' : 'close'}
                onPress={onClose}
            />
        ),
        [onClose, swipeDisabled]
    );

    return (
        <Portal hostName={hostName}>
            <View testID={testID} style={StyleSheet.absoluteFill}>
                <BottomSheet
                    ref={bottomSheetRef}
                    onClose={onClose}
                    enableDynamicSizing={enableDynamicSizing}
                    snapPoints={enableDynamicSizing ? [] : snapPoints}
                    index={0}
                    handleComponent={draggable && showHandleComponent ? Draggable : null}
                    enablePanDownToClose={draggable}
                    backdropComponent={renderBackdrop}
                    enableHandlePanningGesture={!swipeDisabled}
                >
                    <BottomSheetScrollView>
                        {children}
                    </BottomSheetScrollView>
                    {showButtons ? <FormButtons
                        disabled={disableButton}
                        cancel={onClose}
                        positiveText={positiveText || strings.get(keys.SAVE)}
                        negativeText={negativeText}
                        onPress={() => {
                            if (onPress) onPress();
                            onClose();
                        }}
                    /> : null}
                </BottomSheet>
            </View>
        </Portal>
    );
};

BottomSheetPortal.propTypes = {
    children: PropTypes.node.isRequired,
    resetModal: PropTypes.func.isRequired,
    draggable: PropTypes.bool,
    showButtons: PropTypes.bool,
    positiveText: PropTypes.string,
    negativeText: PropTypes.string,
    onPress: PropTypes.func,
    swipeDisabled: PropTypes.bool,
    testID: PropTypes.any,
    onSkip: PropTypes.func,
    showHandleComponent: PropTypes.bool,
    enableDynamicSizing: PropTypes.bool,
    disableButton: PropTypes.bool,
    hostName: PropTypes.string,
};

BottomSheetPortal.defaultProps = {
    draggable: true,
    showButtons: false,
    positiveText: '',
    negativeText: '',
    onPress: () => {},
    swipeDisabled: false,
    testID: undefined,
    onSkip: () => {},
    showHandleComponent: true,
    enableDynamicSizing: true,
    disableButton: false,
    hostName: undefined,
};

export default BottomSheetPortal;

**Comment by kuldip-simform** [comment]
Facing this issue

**Comment by coffe0wl** [comment]
Still on v4 and v5

**Comment by instesti** [comment]
+1 bump on this, still occurring in v4 and v5

**Comment by alternacrow** [comment]
Why was this issue closed?
I still reproduce it in v5.1.1 .
Is orientation not supported?

**Comment by clancywist** [comment]
+1 bump still occuring in 5.1.2
