### ISSUE TITLE
[v4]  Adding animateOnMount = false prop prevents snapToIndex(0) on first load

### ISSUE THREAD

**Issue by AbhilashAchenkunju** [gorhom/react-native-scroll-bottom-sheet#1656]
# Bug

If  `animateOnMount={false}` is applied to a BottomSheetModal then it won't allow snapToIndex(0) [0 only] on first mount.
Please see the sample code below for more details. Please note that the SnapToIndex-0 button has to be pressed before moving the bottom sheet using gestures.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.72.7  |
| react-native-reanimated         | 3.6.1   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Create a component with BottomSheetModal Provider with `animateOnMount={false}`
2. Add a button in the BottomSheet body with snapToIndex(0) onPress event
 

Describe what you expected to happen:

1.  Pressing the button on the bottom sheet on first mount WILL not do the snapToIndex(0) operation
2. Move the bottom sheet up and down using gestures
3. Now pressing the button will snap it to index 0

## Reproducible sample code
```
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet, Button } from 'react-native';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

const App = () => {
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  // renders
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          animateOnMount={false}
        >
          <View style={styles.contentContainer}>
          <Button title="SnapToIndex-0" onPress={() => bottomSheetModalRef.current?.snapToIndex(0)} />
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
```

**Comment by obernal** [comment]
@AbhilashAchenkunju I'm facing this exact issue. Did you find a solution to it? Thx!

**Comment by AbhilashAchenkunju** [comment]
Yes I was able to find a workaround

Repeat the 0 index snap point in the SnapPoint[] array

```
const snapPoints = useMemo(() => ['25%', '25%', '50%'], []);
```

Then call snapToIndex(1) instead of snapToIndex(0)

Hope that helps @obernal

**Comment by obernal** [comment]
@AbhilashAchenkunju great catch that did the trick thanks a lot!
