### ISSUE TITLE
[v4] Bottomsheet is flickering or just not appearing at all for some users on android and ios

### ISSUE THREAD

**Issue by beqramo** [gorhom/react-native-scroll-bottom-sheet#1659]
# Bug

I have a problem with some users on both, android and ios.
On Android: Bottomsheet is flickering(see video).
On iOS: Bottomsheet isn't opening at all, I assume the flickering part is getting skipped.

I can't find any solution, I can't reproduce it, that is what makes it super hard to find.

Maybe someone can say the potential reason behind it as after my checking of the lib, I didn't find anything suspicious.

Here is a video from Android:
the device in the video is Samsung A13, android version 13.
But it is happening on all kind of devices.

https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/f80e746e-6487-4c40-ac93-ee0962319cfa

First It is flickering, but after some time it is giving up on that too.

on IOS it is happening on all version. but for other user with the same OS it works .

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    |0.71.14   |
| react-native-reanimated         | 3.6.0   |
| react-native-gesture-handler    | 2.12.1  |

## Steps To Reproduce

1. Install lib.
2. configure everything. with Backdrop.
3. open it via ref.

Describe what you expected to happen:

1. It should open the bottomsheet.
2.

## Reproducible sample code

```tsx

export interface IBottomSheetViewPropsType
  extends Partial<BottomSheetModalProps>,
    React.RefAttributes<BottomSheetModalMethods> {
  bg?: string;
}


// this is my component that I'm using for every bottomsheet. 
const BottomSheetView = forwardRef<BottomSheetModal, IBottomSheetViewPropsType>(
  ({ children, bg, enableDynamicSizing, ...rest }, ref) => {
    const { bottom } = useSafeAreaInsets();
    const renderBackdrop = useCallback(
      (props) => <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={1} />,
      [],
    );

    const Wrapper = useCallback(
      ({ children: _children }) => (
        <Column
          as={enableDynamicSizing ? BottomSheetViewGorhom : Column}
          stretch={!enableDynamicSizing}
          pb={bottom > 0 ? `${bottom}px` : 5}
        >
          {_children}
        </Column>
      ),
      [bottom, enableDynamicSizing],
    );

    const childrenCaller = useCallback(
      (props: any) => {
        return (
          <Wrapper>{typeof children === 'function' ? children(props.data) : undefined}</Wrapper>
        );
      },
      [Wrapper, children],
    );

    return useMemo(
      () => (
        <BottomSheetModal
          ref={ref}
          index={enableDynamicSizing ? undefined : 0}
          snapPoints={enableDynamicSizing ? undefined : [CONSTANTS.HEIGHT * 0.6]}
          enablePanDownToClose={true}
          backdropComponent={renderBackdrop}
          backgroundStyle={{ backgroundColor: bg || 'white' }}
          enableDynamicSizing={enableDynamicSizing}
          {...rest}
        >
          {typeof children === 'function' ? childrenCaller : <Wrapper>{children}</Wrapper>}
        </BottomSheetModal>
      ),
      [Wrapper, bg, children, childrenCaller, enableDynamicSizing, ref, renderBackdrop, rest],
    );
  },
);


// The component itself
const EstimatedPayRollInformation = () => {
  const bottomSheetRef = useRef<BottomSheetModal>(null);


  useEffect(() => {
   bottomSheetRef.current?.present();
  }, []);
  
  return (
    <BottomSheetCustom ref={bottomSheetRef} snapPoints={[500]}>
      <Column stretch>
        <Image source={infoIcon} />
        {/* some things*/}
      </Column>
    </BottomSheetCustom>
  );
}

```

**Comment by mozzius** [comment]
A user has reported this happening in my app, but I have not been able to replicate it myself

**Comment by PartypayNL** [comment]
All users ios or android with reduced motion enabled in accessibility are not able to open the modal. Temporary fix below.  

https://github.com/gorhom/react-native-bottom-sheet/issues/1560#issuecomment-1754892716

@gorhom could you look into this.

**Comment by beqramo** [comment]
I can verify that it is working fine above fix. one user confirmed the fix from production.

thanks @PartypayNL

**Comment by hx2ryu** [comment]
I experienced the same issue. But, I solved using these ways.

1. try to change 'android:windowSoftInputMode' value. 
 - If this setting value is 'adjustResize', modify it to 'adjustPan'.


2. change the z-index of bottom-sheet whenever index of bottom-sheet is changed.
```js
const [zIndex, setZindex] = useState(-1);
...
 return (
     <BottomSheet onChange={(index) => setZindex(index)}   containerStyle={{ zIndex }}>
      ...
    </BottomSheet>
);
```
