### ISSUE TITLE
[v4] [BottomSheetModal] [BottomSheetFlatList] Persist last scroll position on the flatlist when reopening the bottom sheet modal again

### ISSUE THREAD

**Issue by badalsaibo** [gorhom/react-native-scroll-bottom-sheet#1667]
Hi,

I have a bottom sheet modal which renders a flatlist inside. A user presses an item on the flatlist and the bottom sheet closes. When the bottom sheet is opened again, the flatlist starts from the top. That is the scroll position is reset. I'd like it to persist such that when a user selects something from the bottom of the flatlist, it remains in the scroll position the next time too.

I tried the props `scrollsToTop={false}` but it isn't working.

```
<BottomSheetModal
      ref={bottomSheetModalRef}
      snapPoints={snapPoints}
      handleIndicatorStyle={{ display: 'none' }}
      backdropComponent={CustomBackdrop}>
      <BottomSheetFlatList
        data={SESSIONS}
        renderItem={renderItem}
        scrollsToTop={false}
      />
    </BottomSheetModal>
```

**Comment by theobouwman** [comment]
I have the same issue. For us, when the user swipes or touches the top of the sheet, the BottomSheetFlatList scroll to top, this is annoying because is you scroll the feed and swipe it down we dont want it to scroll to the top directly.
