### ISSUE TITLE
BottomSheet Issue on Android 14 and iOS 17.1/17.2

### ISSUE THREAD

**Issue by salmaAlouane** [gorhom/react-native-scroll-bottom-sheet#1674]
# Bug

The BottomSheet component of the @gorhom/bottom-sheet plugin is not functioning correctly on Android 14.
on iOS, it works on version 17.0 but does not work on versions 17.1 and 17.2.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.5.1 |
| react-native                    | ^0.72.7 |
| react-native-reanimated         | ^3.6.1 |
| react-native-gesture-handler    | ^2.14.0 |

## Steps To Reproduce

1.Open the app
2.Click on the button designed to display the BottomSheet.
3.The BottomSheet should open as a result of these steps, but it is not functioning as expected on Android 14 and iOS 17.1/17.2.

Describe what you expected to happen:

The BottomSheet should open .

## Reproducible sample code

 https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by ricoh-willog** [comment]
I don't know it is same case with me. I comment additional environment of this bug.
I found this issue only iPhone 14 series and iOS 17.2.1+

**Comment by chamellion** [comment]
Same issue here

**Comment by salmaAlouane** [comment]
@gorhom is there any solution for that please ?

**Comment by fawadmahmoodwashmen** [comment]
We are also facing this issue on some iOS devices with version 17.1 - 17.2, but does anyone know the exact devices affected by this?

**Comment by jdicami** [comment]
experiencing problems as well, any update @gorhom

**Comment by FawadMahmood** [comment]
@jdicami It is related to reanimated with reduced motion, here is a patch that can temporarily fix this issue.  

[@gorhom+bottom-sheet+4.6.0.patch](https://github.com/gorhom/react-native-bottom-sheet/files/13869904/%40gorhom%2Bbottom-sheet%2B4.6.0.patch)

**Comment by jetaix** [comment]
thx @FawadMahmood your patch fix the issue

**Comment by daveosterjr** [comment]
@gorhom can we get this added in to the next release if possible?

**Comment by FawadMahmood** [comment]
@daveosterjr, it needs to be appropriately implemented. I just made a quick patch.

**Comment by tbonebrad** [comment]
This has been causing some major issues for us on both iOS and Android. We love this library and have used it liberally across our app, which in turn made our app unusable for users on the problematic device/os combos.  I applied the patch and its now fixed (Thank you @FawadMahmood!).  Is there anything I can do to help get this fix moved into a release?

**Comment by tbonebrad** [comment]
> @jdicami It is related to reanimated with reduced motion, here is a patch that can temporarily fix this issue.
> 
> [@gorhom+bottom-sheet+4.6.0.patch](https://github.com/gorhom/react-native-bottom-sheet/files/13869904/%40gorhom%2Bbottom-sheet%2B4.6.0.patch)

Quick clarification to others who find this.  Reduce motion is a phone setting...

-  iOS found under Settings -> Accessibility -> Motion -> Reduce Motion
- Android found under Settings -> Accessibility -> Remove Animations

When enabled the bottom sheet does not work

**Comment by uhhhsoyan** [comment]
+1 please and thanks!

> @gorhom can we get this added in to the next release if possible?

**Comment by fobos531** [comment]
I've submitted a PR which should fix this in v5 of the library: https://github.com/gorhom/react-native-bottom-sheet/pull/1743

**Comment by guvenakcoban** [comment]
You can extend the `animationConfigs` with `reduceAnimation` value if you use react-native-reanimated v3.

```
import { ANIMATION_CONFIGS } from '@gorhom/bottom-sheet';
import { ReduceMotion } from 'react-native-reanimated';

<BottomSheet
      animationConfigs={{ ...ANIMATION_CONFIGS, reduceMotion: ReduceMotion.Never }}
```

**Comment by gorhom** [comment]
this should be fixed on `v5`

**Comment by ericpoulinnz** [comment]
@gorhom great to hear! This is a pretty big issue, are you able to give a rough timeline for when v5 is stable?

**Comment by iusama46** [comment]
This worked for me

const reducedMotion = useReducedMotion();

 <BottomSheetModal
                animateOnMount={!reducedMotion}
                ref={bottomSheetRef}
                enableDynamicSizing={true}
                enablePanDownToClose={true}
                style={AppStyles.bottomSheet}>
                <VendorBottomSheet item={selectedItem}  closeBottomSheet={closeBottomSheet} navigation={navigation} vendor={getVendor()} />

    </BottomSheetModal>

**Comment by iusama46** [comment]
This worked for me

 const reducedMotion = useReducedMotion();
 
  animateOnMount={!reducedMotion}

**Comment by singhayush1403** [comment]
On changing the animationConfigs, the bottomSheet is finally starting to show, but I'm facing a new problem now. 3  out of 10 times the bottom sheet doesn't close properly with the close or dismiss function. It goes down and comes back up. Anyone else facing the same issue?

**Comment by gtsadaris** [comment]
> On changing the animationConfigs, the bottomSheet is finally starting to show, but I'm facing a new problem now. 3 out of 10 times the bottom sheet doesn't close properly with the close or dismiss function. It goes down and comes back up. Anyone else facing the same issue?

@singhayush1403  I had the same issue and fixed it by applying the patch @FawadMahmood provided ! I hope it helps.

**Comment by codebycorey** [comment]
> You can extend the `animationConfigs` with `reduceAnimation` value if you use react-native-reanimated v3.
> 
> ```
> import { ANIMATION_CONFIGS } from '@gorhom/bottom-sheet';
> import { ReduceMotion } from 'react-native-reanimated';
> 
> <BottomSheet
>       animationConfigs={{ ...ANIMATION_CONFIGS, reduceMotion: ReduceMotion.Never }}
> ```

This solution appears to break `BottomSheetTextInput`

When we apply this change, the sheet no longer extends to accommodate keyboard. Does anyone know of a solution around that. 

We bumped to the version with the patch built in and the same issue happens. 

<img width="679" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/10536895/ecd0dd71-bbe8-46dc-a9cb-f688f2ae793f">

**Comment by buzunboy** [comment]
> > You can extend the `animationConfigs` with `reduceAnimation` value if you use react-native-reanimated v3.
> > ```
> > import { ANIMATION_CONFIGS } from '@gorhom/bottom-sheet';
> > import { ReduceMotion } from 'react-native-reanimated';
> > 
> > <BottomSheet
> >       animationConfigs={{ ...ANIMATION_CONFIGS, reduceMotion: ReduceMotion.Never }}
> > ```
> 
> This solution appears to break `BottomSheetTextInput`
> 
> When we apply this change, the sheet no longer extends to accommodate keyboard. Does anyone know of a solution around that.
> 
> We bumped to the version with the patch built in and the same issue happens.
> 
> <img alt="image" width="679" src="https://private-user-images.githubusercontent.com/10536895/315312179-ecd0dd71-bbe8-46dc-a9cb-f688f2ae793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODQ0ODAsIm5iZiI6MTcxMTM4NDE4MCwicGF0aCI6Ii8xMDUzNjg5NS8zMTUzMTIxNzktZWNkMGRkNzEtYmJlOC00NmRjLWE5Y2ItZjY4OGYyYWU3OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjU5MzVjZmRiZjEyZjViMDgwNDQzZDExZTNmOTMyNWVkZjYxMzRmNjRmNzJiZDcxYjUyNjA3ODcxNzE3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TuU9PbMiIYjET9-TL2HBVkYHKWP7L-QbMz-gnEYvMTM">

Hi, I'm facing the same issue. Any suggestions?

**Comment by UgurGumushan** [comment]
> this should be fixed on `v5`

Is that a wish, a demand or information on a merged pull request?

**Comment by UgurGumushan** [comment]
bottom sheet not appearing for users that have reduced motion turned on (https://github.com/gorhom/react-native-bottom-sheet/issues/1743)(by [@fobos531](https://github.com/fobos531)) ([9b4ef4d](https://github.com/gorhom/react-native-bottom-sheet/commit/9b4ef4dabb7ce1f846ae90e2bab39fa9354ff125))
https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.0-alpha.8

**Comment by JJSLIoT** [comment]
Checked after upgrading to [v5.0.0-alpha.8](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.0-alpha.8) but the issue seems to persist. The bottom sheet does not open the first time, I need to call `sheetRef.current?.snapToIndex(0);` twice to actually open it. I started facing this issue after upgrading to RN version `0.70.x` from `0.68.x`. 

The issue persists on RN version `71` as well as on `72`. I also tried upgrading reanimated to the latest version: `3.8.1` and tried applying the patch mentioned here: https://github.com/gorhom/react-native-bottom-sheet/issues/1674#issuecomment-1882488777 after downgrading bottom sheet to `4.6.0` but the issue persists.

**Comment by Code-yWilliams** [comment]
> > > You can extend the `animationConfigs` with `reduceAnimation` value if you use react-native-reanimated v3.
> > > ```
> > > import { ANIMATION_CONFIGS } from '@gorhom/bottom-sheet';
> > > import { ReduceMotion } from 'react-native-reanimated';
> > > 
> > > <BottomSheet
> > >       animationConfigs={{ ...ANIMATION_CONFIGS, reduceMotion: ReduceMotion.Never }}
> > > ```
> > 
> > 
> > This solution appears to break `BottomSheetTextInput`
> > When we apply this change, the sheet no longer extends to accommodate keyboard. Does anyone know of a solution around that.
> > We bumped to the version with the patch built in and the same issue happens.
> > <img alt="image" width="679" src="https://private-user-images.githubusercontent.com/10536895/315312179-ecd0dd71-bbe8-46dc-a9cb-f688f2ae793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODQ0ODAsIm5iZiI6MTcxMTM4NDE4MCwicGF0aCI6Ii8xMDUzNjg5NS8zMTUzMTIxNzktZWNkMGRkNzEtYmJlOC00NmRjLWE5Y2ItZjY4OGYyYWU3OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjU5MzVjZmRiZjEyZjViMDgwNDQzZDExZTNmOTMyNWVkZjYxMzRmNjRmNzJiZDcxYjUyNjA3ODcxNzE3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TuU9PbMiIYjET9-TL2HBVkYHKWP7L-QbMz-gnEYvMTM">
> 
> Hi, I'm facing the same issue. Any suggestions?

Same issue here ☹️ Has anyone been able to address this?

**Comment by UgurGumushan** [comment]
This is resolved here: https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.0-alpha.8
But v5 has other issues. Please patch the v4 and close this issue.

**Comment by hirbod** [comment]
> On changing the animationConfigs, the bottomSheet is finally starting to show, but I'm facing a new problem now. 3 out of 10 times the bottom sheet doesn't close properly with the close or dismiss function. It goes down and comes back up. Anyone else facing the same issue?

I have encountered this, and its unrelated to the reduced motion. Whenever you change the animationConfig, this issue starts to arise.

**Comment by iway1** [comment]
"Reduced Motion" breaks a lot of stuff in this library even previous to 17.1.. IE onClose handlers fire instantly... kind of makes it unusable IMO. In my current project we're going to have to swap out BottomSheet for our own bottom sheet component because of these issues

**Comment by sparga** [comment]
> > On changing the animationConfigs, the bottomSheet is finally starting to show, but I'm facing a new problem now. 3 out of 10 times the bottom sheet doesn't close properly with the close or dismiss function. It goes down and comes back up. Anyone else facing the same issue?
> 
> I have encountered this, and its unrelated to the reduced motion. Whenever you change the animationConfig, this issue starts to arise.

I had the same issue and found that it happens when the `animationConfig` is not memoized. If the component containing `<BottomSheet>` re-renders during the close animation [this `useEffect`](https://github.com/gorhom/react-native-bottom-sheet/blob/2b37e067aa027f408b32d50cc2636d4093bcacfc/src/components/bottomSheet/BottomSheet.tsx#L1593) is run and re-opens the bottom sheet.

I actually noticed the same issue when using `useBottomSheetSpringConfigs` as well because [it's not correctly memoized](https://github.com/gorhom/react-native-bottom-sheet/blob/2b37e067aa027f408b32d50cc2636d4093bcacfc/src/hooks/useBottomSheetSpringConfigs.ts#L11). The config object is not "shallow equal", so the `useMemo` has no effect.

I fixed it by declaring the config object outside the component, which keep the same reference between each render.

```typescript
import { ANIMATION_CONFIGS } from '@gorhom/bottom-sheet';
import { ReduceMotion } from 'react-native-reanimated';

// Constants
const bottomSheetAnimationConfig = {...ANIMATION_CONFIGS, reduceMotion: ReduceMotion.Never};

// In Component
<BottomSheet
      animationConfigs={bottomSheetAnimationConfig}
```
