### ISSUE TITLE
handleComponent change with differents opening of the modal

### ISSUE THREAD

**Issue by Wilane01** [gorhom/react-native-scroll-bottom-sheet#1677]
Hi,
Sorry for asking a probably dumb question but I've looked everywhere a way to do as the example in the preview gif (https://github.com/gorhom/react-native-bottom-sheet/blob/master/preview.gif) and couldn't find a way to proceed. I'd like the top handle to be an arrow when the bottomsheet is not opened and a bar if open. How can I achieve that ?

Thanks a lot

**Comment by Wilane01** [comment]
Edit : I've seen the https://gorhom.github.io/react-native-bottom-sheet/custom-handle guide but haven't suceeded to reproduce it

**Comment by gorhom** [comment]
https://github.com/gorhom/react-native-bottom-sheet/blob/v5/example/src/components/customHandle/CustomHandle.tsx
