### ISSUE TITLE
[v4] | [v2] Mock issue for the BottomSheetFlatList

### ISSUE THREAD

**Issue by kmagnusj** [gorhom/react-native-scroll-bottom-sheet#1682]
# Bug
I writing jest integration tests for a react native application and on one screen I am using the BottomSheetFlatList component. However, the mock doesn't seem to work properly. I've now tried with a blank app and it still isn't working. There is no "children" property in the "props" input for the "BottomSheetComponent" mock when used for the BottomSheetFlatList component. This results in the renderItem components inside the BottomSheetFlatList being invisible to the test.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    | 0.73.1   |
| react-native-reanimated         | 3.6.1   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Create basic react native app as per the [react native cli quickstart guide](https://reactnative.dev/docs/environment-setup)
2. Install gorhom bottom sheet
3. Add a simple BottomSheet component with a simple BottomSheetFlatList inside
4. Add a test id within the renderItem component for testing
5. Modify the gorhom bottom sheet mock to log the properties of BottomSheetFlatList (just to see what we are working with)
6. Modify the standard render test to log the "rendered" code (to see what is jest is working with)
7. Run `npm run test` and see that the logs show no test ids from the BottomSheetFlatList show up.

Describe what you expected to happen:

1. There should be a "children" property in the "props" object of the BottomSheetFlatList
2. The test ids should be visible within the jest render

## Reproducible sample code

**App.tsx**

```
import React, {useRef} from 'react';
import {Text, View} from 'react-native';
import 'react-native-gesture-handler';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import BottomSheet, {BottomSheetFlatList} from '@gorhom/bottom-sheet';

function App(): React.JSX.Element {
  const bottomSheetRef = useRef<BottomSheet>(null);

  return (
    <GestureHandlerRootView testID="parentView" style={{flex: 1}}>
      <BottomSheet index={1} ref={bottomSheetRef} snapPoints={['25%', '50%']}>
        <BottomSheetFlatList
          data={[1, 2, 3, 4, 5]}
          keyExtractor={i => i}
          renderItem={item => (
            <View testID={`flatListLine_${item.item}`}>
              <Text>{`This is line ${item.item}`}</Text>
            </View>
          )}
        />
      </BottomSheet>
    </GestureHandlerRootView>
  );
}

export default App;
```

**App.test.tsx**

```
import 'react-native';
import React from 'react';
import App from '../App';

// Note: import explicitly to use the types shipped with jest.
import {it} from '@jest/globals';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

jest.mock('@gorhom/bottom-sheet', () => ({
  __esModule: true,
  ...require('@gorhom/bottom-sheet/mock'),
  BottomSheetFlatList: props => {
    console.log(JSON.stringify(props));
    return props.children;
  },
}));

it('renders correctly', () => {
  const screen = renderer.create(<App />);
  console.log(JSON.stringify(screen));
});
```

**Console logs**
```
console.log
    {"data":[1,2,3,4,5]}

      at log (__tests__/App.test.tsx:15:13)
```

```
console.log
    {"type":"View","props":{"testID":"parentView","style":{"flex":1}},"children":null}

      at Object.log (__tests__/App.test.tsx:22:11)
```

**Comment by Nikhilm2000** [comment]
jest.mock('@gorhom/bottom-sheet', () => {
    const {React, ReactNode} = require('react');
    const {View, FlatList} = require('react-native');

    const BottomSheet = jest.fn(({children, ...otherProps}) => {
        return (
            <View testID="mocked-bottomview" {...otherProps}>
                {children}
            </View>
        );
    });
    const BottomSheetFlatList = ({
        children,
        ...otherProps
    }: {
        children: typeof ReactNode;
        otherProps: any;
    }) => {
        return (
            <FlatList testID="mocked-flatlist" {...otherProps}>
                {children}
            </FlatList>
        );
    };

    return {
        __esModule: true,
        default: BottomSheet,
        BottomSheet,
        BottomSheetFlatList,
    };
});

**Comment by kmagnusj** [comment]
This mock works! Huzzah! Thank you @Nikhilm2000 

Why isn't the mock in the library like this? Should I make a pull request?
