### ISSUE TITLE
[v4] How to use the 'new' accessibility overrides?

### ISSUE THREAD

**Issue by fwielstra** [gorhom/react-native-scroll-bottom-sheet#1687]
# Question

We've been keeping an eye on https://github.com/gorhom/react-native-bottom-sheet/pull/1288 for a while now, I'm glad it was merged.

In our application, we currently use a bottom sheet to show forms and information to the user, like in this screenshot:

![simulator_screenshot_90CCC6C8-E52E-4D4B-903C-44A18CE0F75E](https://github.com/gorhom/react-native-bottom-sheet/assets/394435/0093bcf9-138f-400f-9af1-06ac6c433790)

Before the accessibility overrides PR was merged, using the Accessiblity Inspector, the bottom sheet  didn't seem to work right. It's better now, but we're still not entirely sure how to make the bottom sheet work with a screen reader, at least not in the simulator / iOS Accessibility Inspector. When iterating over the elements on the screen, the bottom sheet shows up as one whole blob of type `slider`, or actually two of them, the next one appearing when you iterate / press the 'next element' button in the inspector:

![image](https://github.com/gorhom/react-native-bottom-sheet/assets/394435/13537cde-ec88-4dd7-9ede-7bbd5ecddce6)
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/394435/b7267198-e9b7-40e6-a69c-18eb007888f9)

Iterating further does not advance the pointer to the elements inside of the bottom sheet, which means that as far as a screen reader is concerned, there is nothing there.

We can probably make it work for bottom sheets showing just text/information, but we're not sure how to make it work for interactive / forms like this.

Setting `accessible={false}` on the bottom sheet or its scroll view does not seem to make a difference.

Our goals, and keep in mind that we're not actually very good at accessibility beyond setting labels:

 - When the bottom sheet opens, the user's screen reader should be signaled / the user should be notified of it being open
 - When the user iterates to the next element, the bottom sheet's contents should be read out, including text and forms.

Asides from that, we're still assessing whether bottom sheets actually work at all for screen readers; if anyone here can share some experiences, that would be great! This is the preferred user experience at the moment for the average user, but I personally believe that it's not ideal for people using the accessibility features, I would just open the information up in a new page.

Any help or insights would be appreciated!

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.72.7   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

**Comment by BethThomas141** [comment]
I'm also keen to hear the answer to this question, see if you can upload again following the issue template 🙏

**Comment by JosueCuberoSanchez** [comment]
> I'm also keen to hear the answer to this question, see if you can upload again following the issue template 🙏

Please

**Comment by ashishneomenta** [comment]
Use 
      <BottomSheetScrollView style={{flex: 1}}> 
      your list or scroll
      </BottomSheetScrollView>
