### ISSUE TITLE
Cannot read property 'BottomSheetModalProvider' of undefined | "react-native": "0.73.2",

### ISSUE THREAD

**Issue by deepbag** [gorhom/react-native-scroll-bottom-sheet#1695]
After upgrading my React Native project from version to 0.73, I am encountering a TypeError with the @gorhom/bottom-sheet library. I have tried clearing the cache, reinstalling the node modules, and ensuring the import statements are correct, but the error persists.

![image](https://github.com/gorhom/react-native-bottom-sheet/assets/43214783/677b87cb-1a99-4217-8b9c-349bfd17d5a4)

"react-native": "0.73.2",
 "react-native-gesture-handler": "^2.14.0",
 "@gorhom/bottom-sheet": "^4.6.0",
 "react-native-reanimated": "^3.6.1",
 "react-native-safe-area-context": "^4.8.2",
 
 I Imported BottomSheetModalProvider from @gorhom/bottom-sheet in App.tsx

**Comment by FritzAxel** [comment]
Hey, did you find any solution? I have the same issue.

Maybe it's because i am using react-native-cli
