### ISSUE TITLE
set bottom sheet to open by default

### ISSUE THREAD

**Issue by mhsfh** [gorhom/react-native-scroll-bottom-sheet#1702]
# Feature Request

## Why it is needed

sometimes we want to redirect the user to a screen and open the bottom sheet directly 

## Possible implementation

it was supposed to use the index prop to achieve this but unfortunately, it didn't work

### Code sample

//

**Comment by jdnichollsc** [comment]
@mhsfh did you try using the expand method? e.g:
```tsx
const bottomSheetRef = useRef<BottomSheet>(null)
// ...
bottomSheetRef.current?.expand()
```

you can have that from an useEffect if you want

**Comment by mhsfh** [comment]
> @mhsfh did you try using the expand method? e.g:
> 
> ```tsx
> const bottomSheetRef = useRef<BottomSheet>(null)
> // ...
> bottomSheetRef.current?.expand()
> ```
> 
> you can have that from an useEffect if you want

that's what I'm doing currently, but i think i will be more efficient if we have prop that we can pass it to achieve this

**Comment by eduance** [comment]
Another way of doing this is by specifying the index, telling the bottom sheet on what snap point to open.
