### ISSUE TITLE
BottomSheetSectionList not scrolling

### ISSUE THREAD

**Issue by tbveloso** [gorhom/react-native-scroll-bottom-sheet#1703]
# Bug

I tested some scrollable components. I would like to use BottomSheetSectionList, but even though it is rendered, it does not have scrolling. BottomSheetFlatList and BottomSheetScrollView worked fine

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.73.2   |
| react-native-reanimated         | 3.6.1   |
| react-native-gesture-handler    | 2.14.0   |

````
    const renderItem = useCallback(
      ({item}: {item: any}) => <Item item={item} />,
      [],
    );

    const renderSectionHeader = useCallback(
      ({section}: {section: any}) => <Category section={section} />,
      [],
    );

  ...

  return (
          <BottomSheetSectionList
            sections={resume.list}
            renderItem={renderItem}
            renderSectionHeader={renderSectionHeader}
            keyExtractor={i => `${i.categoryId}:${i.id}`}
            contentContainerStyle={styles.contentContainer}
          />
  )
````

**Comment by vladimirevstratov** [comment]
same issue

**Comment by YMirzaa** [comment]
Try to wrap component into `<BottomSheet>` , and if container has a style of `flex:1` remove it
