### ISSUE TITLE
[v4] | Getting react-native-gesture-handler error on using BottomSheetTextInput

### ISSUE THREAD

**Issue by jsonpreet** [gorhom/react-native-scroll-bottom-sheet#1709]
# Bug

If I use BottomSheetTextInput I am getting error

```
Argument 1 (NSNumber) of RNGestureHandlerModule.attachGestureHandler must not be null

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
__41-[RCTModuleMethod processMethodSignature]_block_invoke.96
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_root_queue_drain_deferred_wlh
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
```

```
const Sheet = ({ snap, marginX, children, sheetRef }) => {
	const bottomSheetModalRef = useRef(null)

	const snapPoints = useMemo(() => snap ?? ['20%', '60%'], [snap])

	const renderBackdrop = useCallback((props) => <BottomSheetBackdrop {...props} opacity={0.5} disappearsOnIndex={-1} appearsOnIndex={0} />, [])

	return (
		<BottomSheetModal
			index={1}
			enableDynamicSizing
			enablePanDownToClose={true}
			enableOverDrag={false}
			enableContentPanningGesture={true}
			animateOnMount={true}
			ref={sheetRef}
			handleComponent={null}
			backgroundStyle={{
				borderRadius: 10,
				backgroundColor: Colors.white,
				borderColor: Colors.grey,
				borderWidth: 0.5,
			}}
			animationConfigs={{
				duration: 200,
			}}
			style={{
				marginHorizontal: 0,
				marginBottom: 0,
				overflow: 'hidden',
				borderRadius: 10,
				paddingHorizontal: 20,
				paddingVertical: 20,
			}}
			keyboardBehavior="fillParent"
			keyboardBlurBehavior="restore"
			detached={false}
			bottomInset={0}
			snapPoints={snapPoints}
			backdropComponent={renderBackdrop}
		>
			{children}
		</BottomSheetModal>
	)
}

```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0   |
| react-native                    | 0.72.6   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Used a BottomSheetTextInput for Keyboardbehaviour but getting error with react-native-gesture-handler

Describe what you expected to happen:

1. There should not be error on using BottomSheetTextInput

## Reproducible sample code
```

<BottomSheetTextInput
					className="rounded-xl p-3 mb-5"
					style={{ color: Colors.text, backgroundColor: Colors.inputBg }}
					placeholderTextColor={Colors.placehodlerText}
					placeholder="What do you want to do?"
					value={title}
					onChangeText={setTitle}
				/>
```

**Comment by MANIKANDAN1709** [comment]
@jsonpreet can you please add more details if possible please attach snack example

**Comment by ghmendonca** [comment]
This is also happening in `5.0.0-alpha.4`. Not sure if this is related to this library, but the reason is that inside of the `BottomSheetTextInput` component it's using the `TextInput` component from `react-native-gesture-handler` which doesn't work. I don't know why, but if you try to render the `TextInput` component from the `react-native-gesture-handler` anywhere inside your app, it will crash with the same error.

The solution would be to change the `TextInput` from this library to use the `react-native` one. But the main issue is that the `TextInput` from gesture handler is broken

**Comment by ghmendonca** [comment]
@jsonpreet if you managed to fix this in any other way other than changing the `TextInput`, please let me know!
