### ISSUE TITLE
[v5] BottomSheetFlatList -> horizontal="true" breaks dynamic height calculation

### ISSUE THREAD

**Issue by lauridskern** [gorhom/react-native-scroll-bottom-sheet#1717]
# Bug

When using BottomSheetFlatList and enabling horizontal="true" the calculation of dynamic height seems to break. 
See attached video:

https://github.com/gorhom/react-native-bottom-sheet/assets/8788856/93a429ff-c85f-4266-ace6-609afd6ea5a4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.6   |
| react-native                    | 0.72.6   |
| react-native-reanimated         | 3.3.0  |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Use BottomSheet with enableDynamicSizing 
2.use a BottomSheetFlatList as child with the prop horizontal set to true

Describe what you expected to happen:

Working height calculation

## Reproducible sample code

```
<BottomSheet enableDynamicSizing>
  <BottomSheetView>
    <BottomSheetFlatList horizontal>
    </BottomSheetFlatList>
  </BottomSheetView>
</BottomSheet>

```

**Comment by calebpanza** [comment]
Was there any progress made on this as far as a resolution goes?
