### ISSUE TITLE
Bottomsheet fails to show on certain Android devices in production.

### ISSUE THREAD

**Issue by MitarSpasicc** [gorhom/react-native-scroll-bottom-sheet#1721]
## Bug

In 9/10 times, bottomsheet doesn't show up at all on Android, on IOS everything works fine.
It happens only in production, while on eas dev build and in expo works.
I've tried everything, even rendering only bottomsheet inside App.tsx, but nothing helped.

Here is part of the code that renders Bottomsheet

 ```
<BottomSheet
         handleIndicatorStyle={styles(theme).handlerIndicator}
         snapPoints={['5%', '20%', '85%']}
         index={1}
         ref={bottomSheetRef}
         style={styles(theme).container}
         onChange={(idx) => handleSheetChanges(idx)}
         backgroundStyle={styles(theme).sheetBackground}
  >
          <BottomSheetScrollView style={styles(theme).scrollView}>
              <Card1 navigation={navigation} />
              <Card2 navigation={navigation} />
              <Card3 navigation={navigation} />
              <Card4 navigation={navigation} />
         </BottomSheetScrollView>
</BottomSheet>

```
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.6.0  |
| react-native                    | 0.72.6 |
| react-native-reanimated         | ~3.3.0 |
| react-native-gesture-handler    | ~2.12.0 |

**Comment by willian-moura** [comment]
Same issue here :/

**Comment by MitarSpasicc** [comment]
@willian-moura 
I found what was the issue in my case.
I’ve upgraded expo to SDK 50, and reanimated automatically updated to 3.6.2.
Maybe it will work for you also.
Cheers

**Comment by willian-moura** [comment]
@MitarSpasicc Here we get it using the bottom-sheet at 4.6.0 and the reanimated at 3.4.0. The SDK we still using 49.

**Comment by CostasCF** [comment]
It still happening for me mostly on android devices. Did you find any other solution? @willian-moura @MitarSpasicc
