### ISSUE TITLE
BottomSheetFlatList not supported when newArchEnabled=true

### ISSUE THREAD

**Issue by vijaychouhan-rails** [gorhom/react-native-scroll-bottom-sheet#1722]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.73.2   |
| react-native-reanimated         | 3.6.1  |
| react-native-gesture-handler    | 2.14.0  |

## Steps To Reproduce

1. Enable newArchEnabled=true
2. Add BottomSheetFlatList
3. Then open That bottom sheet and will thrown an error 
         

> Unexpected nativeTag: ${refType}; nativeTag=${nativeTag}
>          createBottomSheetScrollableComponent's ScrollableComponent needs to return 
> 	 a reference that contains a nativeTag to a Native HostComponent. ref=${ref}

And its throwing from this code [https://github.com/gorhom/react-native-bottom-sheet/blob/1128dc82e5c35e0846938e6007d0464b6bb35beb/src/utilities/getRefNativeTag.ts#L30](https://github.com/gorhom/react-native-bottom-sheet/blob/1128dc82e5c35e0846938e6007d0464b6bb35beb/src/utilities/getRefNativeTag.ts#L30)

Describe what you expected to happen:

1.  The error should not get and should work smoothly 

## Reproducible sample code

```
<BottomSheet
      ref={whatsappWindowRef}
      snapPoints={snapPoints}
      index={-1}
      enablePanDownToClose={true}
      backdropComponent={renderBackdrop}
      footerComponent={renderFooter}>
      <BottomSheetFlatList
        style={mainStyle.mB80}
        data={filteredData}
        keyExtractor={keyExtractor}
        renderItem={renderItem}
        ListHeaderComponent={title}
        ListEmptyComponent={emptyListComponent}
        ListFooterComponent={<View style={mainStyle.mB80} />}
      />
    </BottomSheet>
```

**Comment by Martin2037** [comment]
same problem
