### ISSUE TITLE
[v4] On Android there is unexpected overlay on top of modal window when keyboard reappears.

### ISSUE THREAD

**Issue by Gruzchick** [gorhom/react-native-scroll-bottom-sheet#1723]
# Bug

The bug is shown in the video

![bottom-sheet_65](https://github.com/gorhom/react-native-bottom-sheet/assets/13402010/6407a03b-50a0-4a9f-88bd-d04e32c6ddc4)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.71.12   |
| react-native-reanimated         | 2.17.0   |
| react-native-gesture-handler    | 2.14.1   |

## Steps To Reproduce

To reproduce the bug:
1. Open a modal window
2. Set focus to the input field so that the keyboard appears
3. Then hide the keyboard
4. Tap on the input field to open the keyboard

Current behavior: modal window content is covered with some kind of white overlay

Expected behavior: modal window content would not be covered with an overlay

## Reproducible sample code

```
import React, { useRef } from 'react';
import { Button, Dimensions, StyleSheet, Text, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
  BottomSheetScrollView,
  BottomSheetTextInput,
} from '@gorhom/bottom-sheet';

const App = () => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const handleOpenPres = () => {
    bottomSheetModalRef.current?.present();
  };

  return (
    <GestureHandlerRootView style={s.gestureHandlerRootView}>
      <BottomSheetModalProvider>
        <View style={s.screen}>
          <View style={s.buttonWrapper}>
            <Button onPress={handleOpenPres} title={'Open'} />
          </View>
        </View>
        <BottomSheetModal
          index={0}
          ref={bottomSheetModalRef}
          enableDynamicSizing
          maxDynamicContentSize={Dimensions.get('window').height - 40}
          enablePanDownToClose
        >
          <BottomSheetScrollView stickyHeaderIndices={[0]}>
            <BottomSheetTextInput style={s.input} />
            {new Array(20).fill(0).map((_, index) => (
              <View style={s.item}>
                <Text>{index}</Text>
              </View>
            ))}
          </BottomSheetScrollView>
        </BottomSheetModal>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
};

export default App;

const s = StyleSheet.create({
  gestureHandlerRootView: { flex: 1, backgroundColor: '#cccccc' },
  screen: {
    flex: 1,
    borderWidth: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonWrapper: {
    width: 100,
  },
  input: {
    borderWidth: 1,
    marginHorizontal: 16,
    backgroundColor: '#ffffff',
    marginBottom: 20,
  },
  item: {
    height: 30,
    marginBottom: 10,
    marginHorizontal: 16,
    backgroundColor: 'red',
  },
});
```

**Comment by Gruzchick** [comment]
I noticed that this happens when I use BottomSheetTextInput, if I use TextInput the overlay does not appear

**Comment by vipien** [comment]
Did you manage to solve it? I have the same problem but it always happens not only when it reappears.

**Comment by harzh307** [comment]
try using android_keyboardInputMode="adjustResize" in the bottomsheet component like this 
```
<BottomSheet
        ref={sheetRef}
        android_keyboardInputMode="adjustResize">

``` 
this worked for  me and if i speak for every developer it will work for everyone,
 and if you're using keyboardBehavior prop then use its "interactive" value

**Comment by Gruzchick** [comment]
@harzh307 the bug remains

**Comment by harzh307** [comment]
> @harzh307 the bug remains

did you use bottomsheettextinput ?

**Comment by harzh307** [comment]
> @harzh307 the bug remains

what does your code looks like ?

**Comment by noahkurz** [comment]
Moving to a normal input fixed it for me

**Comment by jgillick** [comment]
Here's a snack demonstrating the bug:
https://snack.expo.dev/@jeremyplura/android-keyboard-padding-bottom-sheet-v4

Setting `android_keyboardInputMode="adjustResize"` does seem to fix it for me (as @harzh307  suggested)

**Comment by harzh307** [comment]
this is how you should've approached the problem
` <BottomSheetModal
        android_keyboardInputMode="adjustResize"
          ref={bottomSheetRef}
          snapPoints={snapPoints}
          index={0}
          style={styles.modal}
        >
          <BottomSheetView style={styles.scroller}>
            <BottomSheetTextInput style={styles.input} placeholder="Field input" />
          </BottomSheetView>
        </BottomSheetModal>`

**Comment by harzh307** [comment]
> Here's a snack demonstrating the bug: https://snack.expo.dev/@jeremyplura/android-keyboard-padding-bottom-sheet-v4
> 
> Setting `android_keyboardInputMode="adjustResize"` does seem to fix it for me (as @harzh307 suggested)

this is how you should've approached the problem @jgillick 
` <BottomSheetModal
        android_keyboardInputMode="adjustResize"
          ref={bottomSheetRef}
          snapPoints={snapPoints}
          index={0}
          style={styles.modal}
        >
          <BottomSheetView style={styles.scroller}>
            <BottomSheetTextInput style={styles.input} placeholder="Field input" />
          </BottomSheetView>
        </BottomSheetModal>`

**Comment by abdulragib** [comment]
android_keyboardInputMode="adjustResize" working fine in android , but not working fine in ios

**Comment by jgillick** [comment]
Keep it fresh, because I think it's still broken.
