### ISSUE TITLE
[v4] Bottom Sheet not opening (Only Backdrop)

### ISSUE THREAD

**Issue by FabianTrain** [gorhom/react-native-scroll-bottom-sheet#1734]
# Bug

Some of our users (iOS and Android) report issues with the bottom sheet (no error report in sentry). The sheets background view is displayed but not the sheet itself. The error occurs every time these users try to open the sheet. A reinstall did not solve it.
Unfortunately I am unable to reproduce this issue on my own devices. All solutions to a similar bug ([issue](https://github.com/gorhom/react-native-bottom-sheet/issues/1405)) seem not to apply to my code (handleStyle, handleComponent, reanimated version, Android animation settings).
The open keyboard shown in the screenshots is called through the autoFocus of a text input field component inside the sheet => the component gets rendered. 

<img width="200" alt="Bildschirmfoto 2024-02-08 um 12 12 27" src="https://github.com/gorhom/react-native-bottom-sheet/assets/123388349/37e72509-191f-4fd3-9de9-25a8d4528953">
<img width="200" alt="Bildschirmfoto 2024-02-08 um 12 24 37" src="https://github.com/gorhom/react-native-bottom-sheet/assets/123388349/47b7f91a-64c6-4f02-969a-69462116972a">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.73.4   |
| react-native-reanimated         | 3.6.2   |
| react-native-gesture-handler    | 2.15.0   |

## Steps To Reproduce

Code Snippet:
```Javascript
<View style={styles.container}>
  <BottomSheet
        ref={bottomSheetRef}
        index={0}
        snapPoints={['95%']}
        enablePanDownToClose
        onChange={handleSheetChanges}>
        <Header />
        <Navigator screen={initialScreen} />
        <ProgressButton />
  </BottomSheet>
</View>
```

```Javascript
const handleSheetChanges = useCallback(
  (index: number) => {
    if (index === -1) {
      close();
    }
  },
  [close],
);
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
});
```

**Comment by YashaBP** [comment]
check out the issue https://github.com/gorhom/react-native-bottom-sheet/issues/1674 it may be related, I had a similar problem to yours and the solution in this issue helped me

**Comment by FabianTrain** [comment]
> check out the issue #1674 it may be related, I had a similar problem to yours and the solution in this issue helped me

Thanks a lot for your comment. This was exactly the issue! For anybody else facing this error: Its caused by the android or ios accessibility setting "Reduced Motions". The linked issue provides a patch file for patch-package.
