### ISSUE TITLE
[v5] wrong css translateY and overflow value causing Bottom Sheet Modal not to show properly on Web

### ISSUE THREAD

**Issue by tkhg** [gorhom/react-native-scroll-bottom-sheet#1736]
# Bug
Bottom Sheet Modal not showing due to wrong css being applied on the Modal on Web:

1. `overflow: hidden` being applied on a modal wrapper causing child modal not appearing
2. `transform: translateY({{some value}})` being applied on the modal, the offset value is wrong causing the modal not appearing in correct position, bottom sheet could appear if we change the value manually in developer console 
3. when using `containerComponent`, the translateY value needed to make the bottom sheet reappear is different from when not using it

<img width="1584" alt="Screenshot 2024-02-09 at 6 58 02 PM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/28704185/aae084c9-c37b-4012-a7bb-3f03c316a5df">
<img width="1584" alt="Screenshot 2024-02-09 at 6 52 59 PM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/28704185/3bbc00f3-67ec-4e4d-acd7-660365c97bce">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.6   |
| react-native                    | 0.73.2   |
| react-native-reanimated         | ^3.6.2  |
| react-native-gesture-handler    | ~2.14.0   |

## Steps To Reproduce

1. Launch the app in Web
2. click the `show` button to trigger the bottom sheet modal

**Describe what you expected to happen:**

1. bottom sheet modal appear at correct position

**Actual:**

2. bottom sheet modal html is inserted in the DOM, but is hidden

## Reproducible sample code

```typescript
import React, { useCallback, useMemo, useRef, useState } from "react";
import { View, Text, StyleSheet, Button } from "react-native";
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from "@gorhom/bottom-sheet";
import { FullWindowOverlay } from "react-native-screens";

const ContainerComponent = (props: { children?: React.ReactNode }) => {
  return <FullWindowOverlay>{props?.children}</FullWindowOverlay>;
};

const App = ({}) => {
  const [open, setOpen] = useState(false);
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ["25%", "50%"], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    if (open) {
      bottomSheetModalRef.current?.dismiss();
    } else {
      bottomSheetModalRef.current?.present();
    }
    setOpen(!open)
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    console.log("handleSheetChanges", index);
  }, []);

  // renders
  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button onPress={handlePresentModalPress} title="show"></Button>
        <BottomSheetModal
          ref={bottomSheetModalRef}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
          // uncomment to test with containerComponent
          // containerComponent={ContainerComponent}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};
const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
    backgroundColor: "grey",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
  },
});

export default App;
```

**Comment by ibrahim-eshag** [comment]
having the same issue.
it was working fine when using react navigation, but after converting the router to  "react-router-dom": "^6.26.0" it's not working

**Comment by ruizlenato** [comment]
Did you manage to solve it?
