### ISSUE TITLE
[v5] BottomSheet does not work since 5.0.0-alpha.5 if no scrollable component is used

### ISSUE THREAD

**Issue by hoangvvo** [gorhom/react-native-scroll-bottom-sheet#1738]
# Bug

Since https://github.com/gorhom/react-native-bottom-sheet/pull/1513/files, if no "scrollable component" is used inside the bottom sheet, the bottom sheet does not work. After adding console.log in various parts of the lib, I understand the way it works in alpha.5 is that `animatedContentHeight.value` must be set [here](https://github.com/gorhom/react-native-bottom-sheet/blob/1128dc82e5c35e0846938e6007d0464b6bb35beb/src/components/bottomSheetScrollable/createBottomSheetScrollableComponent.tsx#L88) for bottom sheet to work. Otherwise, we always run into an early return [here](https://github.com/gorhom/react-native-bottom-sheet/blob/v5/src/hooks/useNormalizedSnapPoints.ts#L67).

<img width="543" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40987398/a45575b1-c77d-4427-8a28-c14147681d08">
<img width="1044" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40987398/cf821dc8-57d4-4725-a353-7436fb5c4472">

I tested another cases where I used one of the scrollable components (eg. BottomSheetScrollView) and it worked.

It is not clear to me if this is a bug or it is that the new version requires the use of a scrollable component to work properly (if that is the case then the doc needs to be updated)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | x.x.x   |
| react-native                    | x.x.x   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

## Steps To Reproduce

1. Just use the example code from https://ui.gorhom.dev/components/bottom-sheet/usage

Describe what you expected to happen:

1. After expanding the bottom sheet, it should show to bottom sheet. However the bottom sheet is not visible.

## Reproducible sample code

https://ui.gorhom.dev/components/bottom-sheet/usage

**Comment by kimf** [comment]
@hoangvvo for me it was enough to wrap my content with a `<BottomSheetView>` and it started working again.
Not sure I fully understand exactly why but just wanted to let you know.

**Comment by abdullahcmd** [comment]
Inorder to solve the issue you just need to wrap the bottom sheet under Bottom SHeet view and it will be resolved.
