### ISSUE TITLE
[v4] bottomsheettextinput autofocus bugs

### ISSUE THREAD

**Issue by pierroo** [gorhom/react-native-scroll-bottom-sheet#1747]
# Bug

When using a BottomSheetTextInput inside a bottomsheet (not a modal), it has many issue in latest version on RN0.73+

=> if using autofocus, it will "blink" open the sheet / display keyboard / and close itself right away (randomly, 8 times out of 10)
=> when it "works" and open, it won't respect the sheet height (snapPoint) I wanted, 9 times out of 10 and will just open full height
In the first attached video, we can see the second case, first time autofocus open the sheet at its expected height, second it opens it full screen height without caring about my snapPoint

[bottomsheetinput_issue.webm](https://github.com/gorhom/react-native-bottom-sheet/assets/17619412/f1aee00e-352f-447b-8d63-94302ce1244e)

On the other hand, if I remove the autofocus: snapPoints is initially respected, but as soon as I tap the input then the keyboard expanding will blink and close the sheet right away (second video)

https://github.com/gorhom/react-native-bottom-sheet/assets/17619412/f663c73f-b9b6-40fa-9adf-aaf33bd2164f

My code is very basic:

```
<AppBottomSheet
        index={0}
        snapPoints={[300]}
        onClose={closeSheetName}
        >
            <BottomSheetTextInput
                value={newName}
                onChangeText={setNewName}
                isDisabled={isLoading}
                autoFocus
                ...
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.73.4   |
| react-native-reanimated         | 3.6.2  |
| react-native-gesture-handler    | 2.15.0   |

## Steps To Reproduce

1. use BottomSheetTextInput
2. focus on it
3. see the keyboard appear/sheet closing in a blink

Describe what you expected to happen:

1. I want my snapPoint to be respected
2. I dont want the sheet to close itself

## Reproducible sample code

https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by Kavosh-m** [comment]
same problem with BottomSheetModal

**Comment by Leykwan132** [comment]
https://github.com/gorhom/react-native-bottom-sheet/assets/56620672/121cedd8-7c7a-495e-bbf2-9fc866988422

I am facing the textinput would move in slightly.

**Comment by schactue** [comment]
Same problem

**Comment by AounNaqvi173** [comment]
same

**Comment by litinskii** [comment]
same

**Comment by aexomir** [comment]
any updates?

**Comment by RedkoVO** [comment]
Hmm, the autofocus works, but it immediately shows the bottom sheet.

https://github.com/gorhom/react-native-bottom-sheet/assets/10897778/4d3eba01-1ad3-4a1b-83f9-63df88169835

**Comment by Helyios** [comment]
I have the same problem, as soon as I try to focus it, whether it's through a ref.current.focus() in the useEffect or with the autofocus prop, it automatically closes the bottom sheet. 

The only way I found to allow it to work is to set a delay on the focus.

**Comment by pierroo** [comment]
not stale; still happening.

**Comment by ions96** [comment]
same problem

**Comment by Neel2107** [comment]
+1

**Comment by janechodance** [comment]
I'm experience this also on BottomSheetTextInput on IOS

**Comment by kawasakime** [comment]
v5.0.5

If set autofocus={true} to the input, then onAnimate will work twice. Because of this, the backdrop is animated twice and creates a visual flicker (Android). On iOS the backdrop appears normally.

@gorhom please fix it 

https://github.com/user-attachments/assets/56d98106-658b-4c0b-aa70-9734f1b2620a

**Comment by rochajulian** [comment]
any update????

**Comment by LinhLM23496** [comment]
+1

**Comment by Mafelo** [comment]
I had a similar issue and I came to notice that the issue stems from layout recalculations triggered by keyboard appearance and certain flex layout behaviors. Specifically, when using **flexDirection: "row"** in container elements.

I noticed that using **flexWrap: "wrap"** on one of the containers with **flexDirection:  "row"** resoved the issue.

I was noticed that adding minimum heights to containers helps resolve the issue. 

e.g.,

`container: {
  minHeight: hp(15),
},
contentContainer: {
  minHeight: hp(10), 
}`

**Comment by blazejkustra** [comment]
This issue can also be reproduced on the web using the `BottomSheetModal`:

https://github.com/user-attachments/assets/7450f794-e544-46b2-8b5d-e5d42f1ccd5d

Could someone reopen this issue?

**Comment by mcabrams** [comment]
Can this issue be re-opened or is it a duplicate? Still encountering a number of bugs related to autofocus

**Comment by elgunhuseynli** [comment]
Still happening, please reopen the issue

**Comment by kaumac** [comment]
I can confirm this is still happening on expo 53 and 54 and on the latest version of this library.
I started implementing gorhom bottom sheet on my app and I lost days to find out that autofocus on textinput is what was causing so many issues.

If this wont be re-opened then maybe we should create a new one?

**Comment by gabk17** [comment]
Updates?
