### ISSUE TITLE
[v5] Bottom sheet is not longer opening

### ISSUE THREAD

**Issue by Chasty** [gorhom/react-native-scroll-bottom-sheet#1751]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.7  |
| react-native                    | 0.72.10  |
| react-native-reanimated         | 3.3.0  |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. just using this version "@gorhom/bottom-sheet": "4.4.7" it works perfectly.

Describe what you expected to happen:

I expect it to be opened.

## Reproducible sample code

That's the code i have and whenever i want to open the bottom sheet it does not even open it.

```javascript
import { View } from 'react-native'
import { BottomSheetBackdrop, BottomSheetModal } from '@gorhom/bottom-sheet'
import React, { RefObject, useCallback, useMemo } from 'react'
import CheatSheetContent from './CheatSheetContent'
import { styles } from './CheatSheet.styles'

type CheatSheetProps = {
  bottomSheetModalRef: RefObject<BottomSheetModal>
}

const CheatSheet = ({ bottomSheetModalRef }: CheatSheetProps) => {
  const renderBackdrop = useCallback(
    (props: React.ComponentProps<typeof BottomSheetBackdrop>) => (
      <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
    ),
    []
  )

  const snapPoints = useMemo(() => ['85%'], [])

  return (
    <View>
      <BottomSheetModal
        ref={bottomSheetModalRef}
        index={0}
        snapPoints={snapPoints}
        backdropComponent={renderBackdrop}
        detached={false}
        handleStyle={styles.bottomSheetHandleStyle}
        handleIndicatorStyle={styles.bottomSheetIndicatorStyle}
        keyboardBlurBehavior="restore"
      >
        <CheatSheetContent />
      </BottomSheetModal>
    </View>
  )
}
```

And open it like this.

```javascript
 const bottomSheetModalRef = useRef<BottomSheetModal>(null)

  const openBottomModal = useCallback(() => {
    bottomSheetModalRef.current?.present()
  }, [])
  const closeBottomModal = useCallback(() => {
    bottomSheetModalRef.current?.close()
  }, [bottomSheetModalRef])
  
  
<CheatSheet bottomSheetModalRef={bottomSheetModalRef} />
```

**Comment by Chasty** [comment]
UPDATE: this is broken since this version `5.0.0-alpha.5`, even the example from [here](https://ui.gorhom.dev/components/bottom-sheet/modal/usage) does not open.

**Comment by malikzype** [comment]
+1..Works fine in alpha 6 but breaks in 7 and 8

**Comment by Chasty** [comment]
In my case I need to remove the `backdropComponent` prop and it worked again, but now the bottom sheet  opens sometimes. weird. 

it is somehow related to this issue as well.

https://github.com/gorhom/react-native-bottom-sheet/issues/1627

**Comment by TNAJanssen** [comment]
Same issue here

**Comment by JosueCuberoSanchez** [comment]
Same issue here

**Comment by MoOx** [comment]
Getting the same problem with latest version 5.0.0-alpha.9.

**Comment by anton2mihail** [comment]
###  + 1 here, on 5.0.0-alpha.9

There's also a weird Gesture related bug where even if enablePanDownToClose is false you're still able to close the bottom sheet using a 2 finger gesture across the top of the sheet. 

Not sure if it's related but the bug is 100% consistent

**Comment by nileshzype** [comment]
+1
I am also face same issue with 5.0.0-alpha.9

With 5.0.0-alpha.4 its working fine.

**Comment by joarkosberg** [comment]
+1
Experiencing same in `5.0.0-alpha.11`, on scenarios without the `BottomSheetView` or the other wrappers. Like this example: https://ui.gorhom.dev/components/bottom-sheet/detach-modal

**Comment by Monir-Shembesh** [comment]
+1 Experiencing same in 5.0.0-alpha.11 as well.

**Comment by gorhom** [comment]
I have tested this on 5 alpha.11 , and it works 

https://github.com/user-attachments/assets/5f4dadfb-8eaf-4716-9782-f7b68c8ec4cf

**Comment by Monir-Shembesh** [comment]
> I have tested this on 5 alpha.11 , and it works
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.Max.-.2024-10-13.at.14.20.48.mp4

@gorhom  can you please show us code example? Is this the Modal or just the bottom sheet? This is my setup:

```
Custom Bottom Sheet Modal Component

const BottomSheet = forwardRef<BottomSheetModal, BottomSheetModalProps>(
  ({ snapPoints, children, ...rest }, ref) => {
    const renderBackdrop = useCallback(
      (props: BottomSheetBackdropProps) => <Backdrop {...props} />,
      []
    );

    return (
      <BottomSheetModal
        ref={ref}
        snapPoints={snapPoints}
        enablePanDownToClose
        {...rest}
        backdropComponent={renderBackdrop}
      >
        {children}
      </BottomSheetModal>
    );
  }
);
```

Usage in code

```
  return (
    <>
      <BottomSheet ref={bottomSheetModalRef} snapPoints={['80%']}>
        <View style={styles.contentContainer}>
          <Text size="lg" type="primary">
            Present Modal
          </Text>
        </View>
      </BottomSheet>
    </>
  );
```

Like this it doesn't show up but if I use `BottomSheetView` it only displays the modal to the size of your child content.

Edit: I figured that the prop `enableDynamicSizing` must be set to `false` for it to show up @gorhom

**Comment by ice-cap0** [comment]
yes just upgraded to latest v5 and the bottom sheet doesn't open given some permutations of `enableDynamicSizing`,`detached`, `backdropComponent`.

**Comment by gorhom** [comment]
@Monir-Shembesh you need to replace the children of the bottom sheet from `View` to `BottomSheetView`, in order to get it working

**Comment by Monir-Shembesh** [comment]
> @Monir-Shembesh you need to replace the children of the bottom sheet from `View` to `BottomSheetView`, in order to get it working

It is working correctly if I use a normal `View` as a child with `enableDynamicSizing` prop set to `false`. I believe that `BottomSheetView` is mainly used for dynamic resizing correct? @gorhom

**Comment by lcfarias1501** [comment]
When I add enableDynamicSizing={false} it works

**Comment by Steven-zion** [comment]
wrap your BottomSheet children in a `BottomSheetView` instead of `View`

**Comment by mr-volatile** [comment]
> wrap your BottomSheet children in a `BottomSheetView` instead of `View`

Thanks! this worked for me.

**Comment by chintanrparmar** [comment]
Thanks, this works!

**Comment by koppli-kwan** [comment]
> When I add enableDynamicSizing={false} it works

Thanks! This was really helpful ; )

**Comment by glulu4** [comment]
> [@Monir-Shembesh](https://github.com/Monir-Shembesh) you need to replace the children of the bottom sheet from `View` to `BottomSheetView`, in order to get it working

This worked perfectly

**Comment by poysa213** [comment]
> When I add enableDynamicSizing={false} it works

life saver thanks!

**Comment by anantkrsingh** [comment]
> When I add enableDynamicSizing={false} it works

Thank you so much 
Saved my lot of time !

**Comment by designed2code** [comment]
What Worked for me is The Parent Container using the BottomSheet should stretch, so therefore

```
<SafeAreaView style={{ flex: 1 }}>
      <Text>Account Page</Text>
      <Button
        title="Open Bottom Sheet"
        onPress={() => {
          setPictureOpen(true);
        }}
      ></Button>
      {pictureOpen && <DownloadPicture />}
    </SafeAreaView>
```

where DownloadPicture component has the BottomSheet code also not to forget `enableDynamicSizing={false}`

version "@gorhom/bottom-sheet": "^5.1.6",

**Comment by alvinokafor** [comment]
only thing that worked in case was downgrading to version 4.6.4

**Comment by deBilla** [comment]
> When I add enableDynamicSizing={false} it works

thanks a lot
