### ISSUE TITLE
[v4.6.0] Cannot select content within bottom sheet in Maestro Studio

### ISSUE THREAD

**Issue by StefanWallin** [gorhom/react-native-scroll-bottom-sheet#1753]
# Bug
Cannot select content within bottom-sheet in Maestro Studio or find during test run
Related issue: https://github.com/mobile-dev-inc/maestro/issues/1493

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.0   |
| react-native                    | 0.72.9   |
| react-native-reanimated         | 3.6.1   |
| react-native-gesture-handler    | 2.14.0   |
| maestro | 1.36.0 |

## Steps To Reproduce

1. Add text `Awesome Text in Bottom Sheet` into content section of gorhom bottom sheet
2. Run maestro flow that tries to ` - assertVisible: 'Awesome Text in Bottom Sheet'`
3. Maestro cannot find the text

**Describe what you expected to happen:**
I expect maestro to find the text.

## Reproducible sample code
https://github.com/StefanWallin/Maestro-character-bug/pull/1

1. Git checkout branch `maestro-gorhom-bottom-sheet-1493`
2. npm i
3. npx pod-install
4. npm run ios
5. [Install maestro ](https://maestro.mobile.dev/getting-started/installing-maestro): `curl -Ls "https://get.maestro.mobile.dev" | bash`
6. maestro test .maestro/main.yaml

**Comment by vyobukhov** [comment]
There is kind of a solution found in the linked issue (works for me): 
https://github.com/mobile-dev-inc/maestro/issues/1493#issuecomment-1966447805

Thx to @flo-sch

**Comment by thinh-at-phantom** [comment]
> There is kind of a solution found in the linked issue (works for me): [mobile-dev-inc/maestro#1493 (comment)](https://github.com/mobile-dev-inc/maestro/issues/1493#issuecomment-1966447805)
> 
> Thx to @flo-sch

This seems to be a workaround because of defaults in bottom-sheet. I believe this issue needs to be re-opened and taken a look at, as it currently breaks any tests using Maestro without the workaround. 

I'm still running into this with v4.6.4.
