### ISSUE TITLE
[v4] onAnimate doesn't trigger if user swipes before previous animation completes

### ISSUE THREAD

**Issue by eemebarbe** [gorhom/react-native-scroll-bottom-sheet#1754]
# Bug

If I trigger snapToIndex() and then as the bottom sheet is mid-animation, I swipe the sheet back to it's initial position, neither onAnimate or onChange are triggered. I need to be able to receive an event in this instance, as I need to control the state of an open/close button for the bottom sheet. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | "^4.6.1"   |
| react-native                    | "0.73.2"   |
| react-native-reanimated         | "~3.6.2"   |
| react-native-gesture-handler    | "~2.14.0"   |

## Steps To Reproduce

1. Trigger an animation to a new index using snapToIndex()
2. Interrupt the animation by swiping to the original fromIndex of the animation.
3. onChange and onAnimate will not trigger.

Describe what you expected to happen:

1. Receive an event for a gesture which returns the bottom sheet to it's fromIndex even when the animation to the toIndex hasn't completed.

**Comment by arekkubaczkowski** [comment]
@eemebarbe did you manage to fix it? I am having exactly the same issue, onAnimate is not being triggered when opening/closing the BottomSheet very fast. cc @gorhom  can we reopen this?
