### ISSUE TITLE
[v4] | [v2] BottomSheetFlatList not rendering.

### ISSUE THREAD

**Issue by fofa-rgb** [gorhom/react-native-scroll-bottom-sheet#1759]
#BottomSheetFlatList not rendering

 I'm using gorhoms BottomSheetFlatlist inside of my BottomSheetModal, but it seems like its not rendering anything (but works fine when i use a normal FlatList from the 'react-native-gesture-handler'.  i installed the lib using: 
npx expo install react-native-reanimated react-native-gesture-handler   and   npx expo install @gorhom/bottom-sheet@^4

 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | "4 " |
| react-native                    | "0.73.2 " |
| react-native-reanimated         | "~3.6.2"  |
| react-native-gesture-handler    | "~2.14.0"   |

## Steps To Reproduce

 `
import { View, Text } from 'react-native';
import {BottomSheetFlatList, BottomSheetModal} from '@gorhom/bottom-sheet'
import { forwardRef, useMemo, useRef } from 'react';
import { FlatList } from 'react-native-gesture-handler';

const CustomModal = forwardRef(function CustomModal({ondismiss,data},ref) {
    
    const snapPoints= useMemo(()=>['90%'], [])
    console.log(data);
  
    return (
        <BottomSheetModal ref={ref} snapPoints={snapPoints} index={0} onDismiss={ondismiss}  backgroundStyle={{borderRadius:0, backgroundColor:'transparent'}}>
                    <View style={{padding:100}}>
                    <BottomSheetFlatList
                        data={data}
                        renderItem={({ item }) => {
                            return (<Text style={{fontSize: 20}}>{item}</Text>)
                            }}
                        />
                    </View>
        </BottomSheetModal>
    );
});

export default CustomModal;`

  

1. use a BottomSheetModal component from the gorhom lib 
2.Place a BottomSheetFlatList inside of it
3. Use whatever data you like

Describe what you expected to happen:

I expect that i see the list of items to show up on the screen. on both android and iphone 

## Reproducible sample code

https://snack.expo.dev/rhjED5RNFu_K9w24S3EJG

**Comment by Abhishek2250** [comment]
any update on this? I'm also facing same issue
