### ISSUE TITLE
[v4] | [v2]  BottomSheetScrollView & FlatList crashing with newArchEnabled=true

### ISSUE THREAD

**Issue by Martin2037** [gorhom/react-native-scroll-bottom-sheet#1762]
# Bug

app crashing on IOS, when items need to scroll using newArchEnabled=true
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/63692237/54b8b4cc-3c9c-496a-a4a9-566267b253a0)

## Environment info
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 182.92 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.4.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/zhujunyang/.rubies/ruby-3.3.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/zhujunyang/.rubies/ruby-3.3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

| Library                         | Version |
| ------------------------------- | ------- |
"@gorhom/bottom-sheet": "4.6.1",
 "react-native-gesture-handler": "2.15.0",
"react-native-reanimated": "3.6.2",
"react-native": "0.73.5",
 

## Steps To Reproduce
1. install libs using yarn
2. enable new arch
3. create BottomSheet with BottomSheetScrollView
3. try to render data until container need to scroll

Describe what you expected to happen:

1. app not crashing with newArchEnabled=true

## Reproducible sample code
      <BottomSheet
        snapPoints={['50%']}
        index={0}
      >
        <Box bg={'$coolGray200'} flex={1}>
          <BottomSheetFlatList style={{ flex: 1 }} data={[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]} renderItem={({ item }) => (
            <Text>{item}</Text>
          )}/>
        </Box>
      </BottomSheet>

**Comment by RalissonMattias** [comment]
Yeah, I was looking at the recent changes and found a refactor. After reversing the changes, it works fine.

Version: `^5.0.0-alpha.9`
Ref: [The PR](https://github.com/gorhom/react-native-bottom-sheet/commit/1a8928f51cd2b032a2d2d4252e2edcd76f9e32a6)

```patch
diff --git a/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollable.ts b/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollable.ts
index 3963175..4a38f26 100644
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollable.ts
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollable.ts
@@ -1,8 +1,8 @@
 import { useCallback, RefObject, useRef } from 'react';
 import { useSharedValue } from 'react-native-reanimated';
-import { getRefNativeTag } from '../utilities/getRefNativeTag';
 import { SCROLLABLE_STATE, SCROLLABLE_TYPE } from '../constants';
 import type { ScrollableRef, Scrollable } from '../types';
+import { findNodeHandle } from 'react-native';
 
 export const useScrollable = () => {
   // refs
@@ -38,7 +38,7 @@ export const useScrollable = () => {
     // find node handle id
     let id;
     try {
-      id = getRefNativeTag(ref);
+      id = findNodeHandle(ref.current);
     } catch {
       return;
     }
diff --git a/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollableSetter.ts b/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollableSetter.ts
index ea7d3c2..1cae2e2 100644
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollableSetter.ts
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useScrollableSetter.ts
@@ -1,9 +1,9 @@
 import React, { useCallback, useEffect } from 'react';
 import Animated from 'react-native-reanimated';
 import { useBottomSheetInternal } from './useBottomSheetInternal';
-import { getRefNativeTag } from '../utilities/getRefNativeTag';
 import { SCROLLABLE_TYPE } from '../constants';
 import type { Scrollable } from '../types';
+import { findNodeHandle } from 'react-native';
 
 export const useScrollableSetter = (
   ref: React.RefObject<Scrollable>,
@@ -31,7 +31,7 @@ export const useScrollableSetter = (
     isContentHeightFixed.value = false;
 
     // set current scrollable ref
-    const id = getRefNativeTag(ref);
+    const id = findNodeHandle(ref.current);
     if (id) {
       setScrollableRef({
         id: id,
```

**Comment by RalissonMattias** [comment]
Duplicate #1726
