### ISSUE TITLE
[v4] How to decrease the duration of the Bottom Sheet Modal animation?

### ISSUE THREAD

**Issue by Acetyld** [gorhom/react-native-scroll-bottom-sheet#1769]
# Bug / Feature?

Right now the modal takes a bit to show, this is normally fine, but we use it as a dropdown for inputs, and if it is a 100% modal it takes just to long to show and hide.

Hide is biggest problem, because this will cause the items below to not be clickable before the backdrop is hidden

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1  |
| react-native                    | 0.73.4   |
| react-native-reanimated         | 3.6.2   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Create a bottom-sheet modal + a backdrop without touch through
2. Show modal 100% snappoint
3. See the duration

Describe what you expected to happen:

1. Ability/prop to change duration

## Reproducible sample code

Any bottom sheet modal

**Comment by Acetyld** [comment]
Found it =) Animations configs,

Default is:

```js

const ANIMATION_EASING: Animated.EasingFunction = Easing.out(Easing.exp);
const ANIMATION_DURATION = 250;

const ANIMATION_CONFIGS_IOS = {
  damping: 500,
  stiffness: 1000,
  mass: 3,
  overshootClamping: true,
  restDisplacementThreshold: 10,
  restSpeedThreshold: 10,
};

const ANIMATION_CONFIGS_ANDROID = {
  duration: ANIMATION_DURATION,
  easing: ANIMATION_EASING,
};

const ANIMATION_CONFIGS =
  Platform.OS === 'ios' ? ANIMATION_CONFIGS_IOS : ANIMATION_CONFIGS_ANDROID;

```

**Comment by mindcube** [comment]
Where do you apply these settings?

**Comment by AntonioRDev** [comment]
> Where do you apply these settings?

animationConfigs prop
