### ISSUE TITLE
[v4] | [v2] Modal overlap issue when opening a second modal with custom animation configs

### ISSUE THREAD

**Issue by jckyeh** [gorhom/react-native-scroll-bottom-sheet#1771]
# Bug

On iOS, when using the "@gorhom/bottom-sheet" library, an issue arises involving multiple BottomSheetModal components managed by a BottomSheetModalProvider. Specifically, in a scenario where two modals (A and B) are implemented, with modal A having multiple snap points (e.g., ["60%", "80%"]) and modal B having a single snap point (e.g., ["50%"]), an unexpected behavior occurs under the following conditions:

Modal A is opened to its highest snap point (e.g., "80%").
While modal A is open, an attempt is made to open modal B.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.73.5   |
| react-native-reanimated         | 3.6.2   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Implement a screen with two BottomSheetModal components, A and B, where A has multiple snap points and B has a single snap point.
2. Open modal A to its highest snap point.
3. Trigger the opening of modal B while A is still open.

### Expected Behavior:

Upon opening modal B, modal A should dismiss entirely, allowing modal B to be presented solely. This expectation aligns with the typical modal management where only one modal should be active and visible at a time, ensuring a clean and non-overlapping user interface experience.

### Actual Behavior:

Instead of modal A being dismissed as expected, it collapses to its smaller snap point (e.g., "60%"), and modal B opens simultaneously. This results in both modal A and B being presented at the same time, contrary to the expected behavior where only one modal should be visible at a time. This overlap of modals can lead to a confusing user experience and visual clutter.

![RocketSim_Recording_iPhone_15_6 1_2024-03-16_20 51 15](https://github.com/gorhom/react-native-bottom-sheet/assets/6530117/d2e0aeaa-805d-4401-b57c-e1fdb44b02e6)

### Temporary Solution Identified:

A workaround for this issue involves commenting out the animationConfigs={animationConfigs} line on the BottomSheetModal component. However, this negates the ability to customize the modal's animation, presenting a compromise between functionality and aesthetic customization.

This behavior has been observed and is reproducible on iOS, but not tested on other platforms.

## Reproducible sample code

https://github.com/jckyeh/gorhom-bottom-sheet-mre

**Comment by tdammy92** [comment]
@jckyeh sorry is sheet B nested inside sheet A ?

**Comment by jckyeh** [comment]
@tdammy92 No, they are siblings. See file: 

https://github.com/jckyeh/gorhom-bottom-sheet-mre/blob/main/app/(tabs)/index.tsx
