### ISSUE TITLE
ERROR Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes ERROR Invariant Violation: "main" has not been registered. This can happen if:

### ISSUE THREAD

**Issue by ravishukla21** [gorhom/react-native-scroll-bottom-sheet#1774]
when i install this '@gorhom/bottom-sheet';   I got error in my project 
import BottomSheet, { BottomSheetView } from '@gorhom/bottom-sheet'; 

errors are mentioned below=> can anyone suggest me where I am wrong

ERROR  Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes       
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Comment by ravishukla21** [comment]
my dependencies are 
 "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@gorhom/bottom-sheet": "^4.6.1",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "expo": "~50.0.14",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "^3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0"
  },

**Comment by LeonardoSya** [comment]
You may configure your babel.config.js, this is my configuration for reference:

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./src'],
          extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
          alias: {
            tests: ['./tests/'],
            "@components": "./components",
          }
        }
      ],
      'react-native-reanimated/plugin',
    ]
  }
};

```
Remember to add  'react-native-reanimated/plugin'.
Wish this helps you.

**Comment by preAGIcoder** [comment]
Facing similar issue

**Comment by preAGIcoder** [comment]
@ravishukla21 You need to install dependecies as mentioned in documentation react-native-reanimated and react-native-gesture-handler. Also make sure you wrap your components from bottom sheet with react-native-gesture Provider.

**Comment by YaspYa** [comment]
Try to downgrade "react-native-reanimated" to 3.3.0, because "@gorhom/bottom-sheet" has some issues with it.

**Comment by sleekLancelot** [comment]
Looks like the native side of some dependency hasn't been initialised, have you tried rebuilding the app?
