### ISSUE TITLE
[v4] [Android] Sheet doesn't close when the BottomSheetTextInput is focused with the keyboard is open

### ISSUE THREAD

**Issue by sauzy34** [gorhom/react-native-scroll-bottom-sheet#1777]
# Bug
The sheet doesn't close when the `BottomSheetTextInput` is focused with the keyboard in the opened state,  used with the `BottomSheet` & `BottomSheetFlatList` in **ANDROID**

![Issue](https://github.com/gorhom/react-native-bottom-sheet/assets/19049022/f5021694-fe50-41aa-9e82-66decc6624d6)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4  |
| react-native                    | 0.73.2   |
| react-native-reanimated         | ~3.6.2  |
| react-native-gesture-handler    | ~2.14.0  |

## Steps To Reproduce

1. The list is opened & focus is on the input field. 
2. Now try to click on the list option
3. It doesn't close the bottom sheet

Describe what you expected to happen:

1. Bottom sheet should be closed when `bottomSheetRef.current?.close()` is called with `BottomSheetTextInput` is focused

## Reproducible sample code

Here is the Github link https://github.com/sauzy34/bottom-sheet-snack

**Comment by iusama46** [comment]
Instead of close prop use forceClose prop for android

**Comment by sauzy34** [comment]
Found a neat solution IMO
Added `onTouchStart={() => Keyboard.dismiss()}` to dismiss the keyboard even before the bottom sheet does it automatically.
```
 <BottomSheetFlatList
        data={data}
        initialNumToRender={5}
        bounces={true}
        windowSize={10}
        maxToRenderPerBatch={5}
        renderItem={renderFlatListItem}
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
        keyboardShouldPersistTaps="handled"
        keyboardDismissMode="interactive"
        onTouchStart={() => Keyboard.dismiss()} // solution
      />

```
