### ISSUE TITLE
[v4] | [v2] When using BottomSheetTextInput as footer in BottomSheetFlatList, keyboard is dismissed on value change

### ISSUE THREAD

**Issue by esorinas** [gorhom/react-native-scroll-bottom-sheet#1787]
# Bug
Hello! I am working in an Expo managed project and using the latest version of this package, and I have stumbled into this strange behavior when trying to place a BottomSheetTextInput inside the footer of a BottomSheetFlatList. When I type anything on the input, the keyboard is dismissed, making it quite hard to actually write a full sentence.

**Note**: This only happens when the input has a `value` and `onChangeText` props (as in `<BottomSheetTextInput value={value} onChangeText={setValue}/>`). Using an uncontrolled input like `<BottomSheetTextInput />` it does work fine.

https://github.com/gorhom/react-native-bottom-sheet/assets/43247096/adc5d14c-ef93-4868-8117-46ad174fd36b

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.73.6   |
| react-native-reanimated         | ~3.6.2   |
| react-native-gesture-handler    | ~2.14.0   |

## Steps To Reproduce

1. Create a BottomSheet (or a BottomSheetModal) with a BottomSheetFlatList component inside
2. Add a footer (by setting the `ListFooterComponent` prop) containing a BottomSheetTextInput
3. Define the `value` and `onChangeText` props of the BottomSheetTextInput (as the value and set value from `useState`)
4. Try entering text on the input, and see how the keyboard is dismissed after each change.

Describe what you expected to happen:

I expected the keyboard to be dismissed on regular circumstances (user presses outside, return button press, etc)

## Reproducible sample code

To show the bug, I created a clean Expo project, installed this package and copied components and styles from the examples in the documentation (basically from [BottomSheetFlatList](https://ui.gorhom.dev/components/bottom-sheet/components/bottomsheetflatlist) and [BottomSheetTextInput](https://ui.gorhom.dev/components/bottom-sheet/components/bottomsheettextinput) examples). 
Over that base, I just
- Defined a state with `const [value, setValue] = useState('')`
- Defined the footer with
```
const renderFooter = () => <BottomSheetTextInput style={styles.input} value={value} onChangeText={setValue}/>;
// ...
<BottomSheetFlatList
  ListFooterComponent={renderFooter}
  // ...
/>
````

Link to the Github repo that I created to test this bug: https://github.com/esorinas/bug-reproducing-project

**Comment by esorinas** [comment]
After some extra testing, I found another case where this bug occurs. If your `BottomSheetModal` contains a [`TabView`](https://reactnavigation.org/docs/tab-view/) and you render a `BottomSheetTextInput` inside a tab (with controlled state), you will face the same problem. Therefore it is not an issue specific to the BottomSheetFlatList footer, but honestly I have no clue what do these cases have in common.

Any help is appreciated!

**Comment by esorinas** [comment]
Hi again,

I found out the problem, and it is (I think) completely unrelated to this library.

The issue is that, after each state change, when the component re-renders, it re-creates the function `renderFooter`, thus re-creating the footer itself and triggering this strange behavior.

The solution: simply pass the component itself in the props.
Instead of this
```
// Wrong
const renderFooter = () => <BottomSheetTextInput style={styles.input} value={value} onChangeText={setValue}/>; 
// ...
<BottomSheetFlatList
  ListFooterComponent={renderFooter} 
  // ...
/>
```
do this
```
// Right 
<BottomSheetFlatList
  ListFooterComponent={<BottomSheetTextInput style={styles.input} value={value} onChangeText={setValue}/>} 
  // ...
/>
```

**Comment by pesohub** [comment]
I fixed the problem by installing react-native-keyboard-controller and adding keyboardBehavior and keyboardBlurBehavior.

`<BottomSheetModal
  ...
  keyboardBehavior="interactive"
  keyboardBlurBehavior="restore"
>`
