### ISSUE TITLE
Render content (lazy load) only when sheet is opened.

### ISSUE THREAD

**Issue by clicktodev** [gorhom/react-native-scroll-bottom-sheet#1793]
# Feature Request

A way to lazy load the sheet content until it's actually opened would be great.

**Comment by Psycarlo** [comment]
@hichemfantar is this completed?

**Comment by clicktodev** [comment]
i think i closed because the issue was on my end. feel free to test with the latest version and report back

**Comment by Psycarlo** [comment]
@hichemfantar Current version does not have an option for lazy load bottom-sheet (that I am aware)

A good way to do this is to use `lazy` from `react`

```
import React, { JSX, Suspense, lazy } from 'react';

const BottomSheets = lazy(() => import('./BottomSheets'));

const BottomSheetsLazy = (): JSX.Element => {
	return (
		<Suspense fallback={null}>
			<BottomSheets />
		</Suspense>
	);
};

export default BottomSheetsLazy;
```

Note: Example from [bitkit](https://github.com/synonymdev/bitkit/blob/master/src/sheets/BottomSheetsLazy.tsx)

What was your issue and how did you solve it? Would be amazing if you share for other people future reference.

**Comment by clicktodev** [comment]
it was a long time ago, but I think it was just false reporting (i thought some hooks were running before the sheet was opened)

**Comment by clicktodev** [comment]
try having some code that runs on mount and see if it triggers before the sheet is opened
