### ISSUE TITLE
[v4] | [v2] enablePanDownToClose doesn't update dynamically

### ISSUE THREAD

**Issue by dima-vantage** [gorhom/react-native-scroll-bottom-sheet#1803]
# Bug

## Environment info

| Library                                          | Version |
| ------------------------------- | --------|
| @gorhom/bottom-sheet            | ^4.6.1    |
| react-native                                | 0.69.12  |
| react-native-reanimated           | ^2.17.0   |
| react-native-gesture-handler   | ^1.10.3   |

## Steps To Reproduce

When passing enablePanDownToClose as a conditional prop it doesn't work, only remember the initial value.

## Reproducible sample code

```
<BottomSheetModal
        ref={ref}
        index={index}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
        backdropComponent={renderBackdrop}
        enablePanDownToClose={!blocked}
      >
        {children}
      </BottomSheetModal>
```

**Comment by kierancrown** [comment]
Did you ever find a fix to this? I'm also experiencing the same issue
