### ISSUE TITLE
[v4] When enableContentPanningGesture is false on BottomSheetModal, cant scroll on IOS. Android is working fine

### ISSUE THREAD

**Issue by Lelouch65428** [gorhom/react-native-scroll-bottom-sheet#1807]
# Bug

Cannot scroll on iOS when enableContentPanningGesture is set to false. I want to make the modal draggable from the header only but if I put enableContentPanningGesture to false I am not able to scroll. I have tried to use scrollview from react-native-gesture-handler which is working but then I am getting keyboard related issues with this.  

## Environment info
Tested on iOS simulator 15 pro (iOS 17.2)
I am not using expo

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.71.16   |
| react-native-reanimated         | 2.9.1  |
| react-native-gesture-handler    | 2.8.0  |

## Steps To Reproduce

1. Use BottomSheetModal and add content inside the BottomSheetScrollView
2. enableContentPanningGesture should be false
3. Try to scroll

Describe what you expected to happen:

1. Should be able to scroll
2. Since enableContentPanningGesture is false the modal should not be draggable from the content

## Reproducible sample code

https://snack.expo.dev/wV9IrI1fsIU_sjd1OMPIB

**Comment by Lelouch65428** [comment]
@gorhom please help fix this issue

**Comment by sudhanshu-busy** [comment]
Try enableOverDrag={false}
