### ISSUE TITLE
[v4] | [v2] Does BottomSheetView work with nativewind?

### ISSUE THREAD

**Issue by asharrahman02** [gorhom/react-native-scroll-bottom-sheet#1809]
# Bug

When using nativewind, this will work on most components but does not seem to work with BottomSheetViews in my testing. All I do is do className="bg-blue-500" which does not work.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.6.1 |
| react-native                    | 0.73.6 |
| react-native-reanimated         |~3.6.2|
| react-native-gesture-handler    |~2.14.0|

## Steps To Reproduce

1. Create BottomSheetView Component
2. Install and test Native wind to ensure it is working correctly

Describe what you expected to happen:

1. The background color of the component should be bg-black-400
2.

## Reproducible sample code

`		<BottomSheetView style={{padding: 10, height: '100%'}} className={"bg-black-400"}>`

**Comment by XantreDev** [comment]
I have this issue with some BottomSheet components as well. You can use` const BottomSheetView = styled(LibBottomSheetView)`

**Comment by daybreaker** [comment]
Nativewind v4 does not have a `styled()` function anymore. Has anyone got this working in Nativewind v4 yet?

**Comment by XantreDev** [comment]
> Nativewind v4 does not have a `styled()` function anymore. Has anyone got this working in Nativewind v4 yet?

You should you [remapProps](https://www.nativewind.dev/v4/api/remap-props) in this case

**Comment by daybreaker** [comment]
In case anyone from the future stumbles on this, my problem was putting the `<BottomSheetModalProvider>` before my `<Theme>` wrapper in my App.js. So of course it didnt know what nativeWind was. 🤦

Sometimes it's the simple things we miss, in search of the more difficult answers

**Comment by dcalsky** [comment]
In case anyone from the future stumbles on this too, maybe you are missing appending your custom components to the `tailwind.config.js`.

```javascript
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by abdullahCybersoph** [comment]
> In case anyone from the future stumbles on this, my problem was putting the `<BottomSheetModalProvider>` before my `<Theme>` wrapper in my App.js. So of course it didnt know what nativeWind was. 🤦
> 
> Sometimes it's the simple things we miss, in search of the more difficult answers

This worked for me in 2025
