### ISSUE TITLE
[v4] Delay on BottomSheetModal dimiss

### ISSUE THREAD

**Issue by KhimGurung** [gorhom/react-native-scroll-bottom-sheet#1812]
# Bug

I am using BottomSheetModal and BottomSheetFlatList within it. If the list has many item rendered, there is certain delay while dismissing the modal. But when few items are in the list then the dismissing works fine.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1  |
| react-native                    | 0.71.4   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce
1. Setup BottomSheetModal with BottomSheetFlatList within it
2. Populate BottomSheetFlatlist with around 400 items
3. Present the modal and again dismiss it programatically `bottomSheetRef.current?.ref?.dismiss();` 

Describe what you expected to happen:
1. The BottomSheetModal start dismissing right after clicking dismiss

**Comment by gottfriedaniel** [comment]
@KhimGurung have you managed to overcome this issue?
