### ISSUE TITLE
[v4] Backdrop component with opacity appears at the bottom when bottomInset is set to BottomSheetModal

### ISSUE THREAD

**Issue by sofi-algoritcom** [gorhom/react-native-scroll-bottom-sheet#1816]
# Bug
 If I set a backdrop component with opacity and set bottomInset prop to the BottomSheetModal using useSafeAreaInsets hook ('react-native-safe-area-context'), when the BottomSheetModal is presented, the backdrop component appears at the bottom using the bottomInset height.

<img height="800" src="https://github.com/gorhom/react-native-bottom-sheet/assets/160500407/f72cf9fd-625a-46b7-b392-bb07d2892a2e" />

## Environment info

Trying it with the Expo App SDK 50, iPhone 15 Pro (iOS Version 17.4.1)

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.73.6   |
| react-native-reanimated         | 3.6.2   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Present the BottomSheetModal and see the error at the bottom of the screen.

Describe what you expected to happen:

1. The bottomInset space should be filled with the BottomSheetModal background, not the BackdropComponent's one.

## Reproducible sample code

```
import { useMemo, useRef, useCallback } from 'react';
import { View, StyleSheet } from 'react-native';
import { enableLogging, BottomSheetBackdrop,
  BottomSheetBackdropProps, BottomSheetModal } from '@gorhom/bottom-sheet';
import List from './components/List';
import SearchHandle from './components/SearchHandle';
import Button from './components/Button';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

enableLogging();

const App = () => {
  // refs
  const bottomSheetRef = useRef(null);
  const insets = useSafeAreaInsets();

  // variables
  const snapPoints = useMemo(() => [200], []);

  // callbacks
  const handleExpandPress = useCallback(() => {
    bottomSheetRef.current?.expand();
  }, []);
  const handleCollapsePress = useCallback(() => {
    bottomSheetRef.current?.collapse();
  }, []);
  const handleClosePress = useCallback(() => {
    bottomSheetRef.current?.close();
  }, []);

   const backdropComponent = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
        opacity={0.48}
      />
    ),
    []
  );

  return (
    <View style={styles.container}>
      <Button onPress={handleExpandPress} title="Expand" />
      <Button onPress={handleCollapsePress} title="Collapse" />
      <Button onPress={handleClosePress} title="Close" />
      <BottomSheetModal
        backgroundStyle={{ backgroundColor: colors.background }}
        backdropComponent={backdropComponent}
        bottomInset={insets.bottom}
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        keyboardBehavior="interactive"
        handleComponent={SearchHandle}
        animateOnMount={true}
        android_keyboardInputMode="adjustPan">
        <List type="FlatList" />
      </BottomSheetModal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 64,
    justifyContent: 'flex-start',
    backgroundColor: '#222',
  },
});

export default App;
```

**Comment by vinesh4Real** [comment]
@sofi-algoritcom did you find a solution to this?

**Comment by sofi-algoritcom** [comment]
Hey @vinesh4Real! The workaround I applied was to not pass any value to the bottomInset prop, but instead, I added a paddingBottom to the footer component with the insets.bottom value taken from useSafeAreaInsets() ('react-native-safe-area-context').

**Comment by Maximization** [comment]
@sofi-algoritcom @vinesh4Real I used a similar solution. I didn't have a footer component so instead I applied a paddingBottom to BottomSheetView.

**Comment by benjaminharringtonrose** [comment]
I'm having the same issue here :/

**Comment by Nziranziza** [comment]
I am having a similar issue, I can do the workaround but I wonder if there can be an integrated solution

**Comment by zocario** [comment]
I'm also facing the issue, though `paddingBottom` isn't really helpful as it breaks the computation of dynamic sizing with a flash list inside the modal. I'm really curious to know the recommended way to handle this @gorhom ?

**Comment by DaveMonGym** [comment]
Having the same issue!

After some digging I found that the issue stems from the implementation of the bottom inset handling. 
the `overflow: hidden` causes the background to be visible behind the applied bottom value.

My quick fix for now is to render a view with `height: insets.bottom` as the height value on ios.

<img width="1245" height="651" alt="Image" src="https://github.com/user-attachments/assets/bf06174b-fbf6-401f-bc62-76c4b5a27c0a" />

```
<BottomSheet
        backgroundStyle={{
          ...sheetContainerStyle,
          ...dropShadowStyle,
        }}
        bottomInset={insets.bottom}
        handleIndicatorStyle={sheetIndicatorStyle}
        ref={bottomSheetRef}
        snapPoints={snapPoints}
      >
        <BottomSheetView className="gap-4 p-2">
          <WorkoutSessionTimer />
          {hasRestTimer && <WorkoutSessionRestTimer />}
          <Button
            onPress={goToExerciseBank}
            size={"lg"}
          >
            <Icon
              as={Plus}
              className="text-black"
              size={20}
            />
            <Text className="font-bold text-black">Add exercises</Text>
          </Button>
          <Button
            className="border border-destructive bg-muted"
            onPress={cancelWorkout}
            size={"lg"}
          >
            <Text className="font-bold text-destructive">Cancel workout</Text>
          </Button>
        </BottomSheetView>
      </BottomSheet>
      {isIOS && (
        <View
          className="items-center bg-background"
          style={{
            height: insets.bottom,
          }}
        >
          <Text>Generated view</Text>
        </View>
      )} 
```

**Comment by DaveMonGym** [comment]
Could we re-open this issue?
