### ISSUE TITLE
[v4]  Não abre o bottom-sheet em alguns aparelhos xiaomi

### ISSUE THREAD

**Issue by Joaovictor144** [gorhom/react-native-scroll-bottom-sheet#1819]
# Bug

In some XIAOMI devices, the modal doesn't open, but it works on other devices.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.72.6   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

Trying to open it on Xiaomi 11 Lite and some others, only Xiaomi.

Describe what you expected to happen:

1. that it would open

## Reproducible sample code

and the code from the documentation, it works on all devices except some Xiaomi.

**Comment by yurinmk** [comment]
The same thing happens to me, but my app runs on a payment machine and this problem only happens there, it works on other devices.

**Comment by MarchewkaMatthew** [comment]
Our users reported the same issue - two reports from Xiaomi Mi 9T, please let me know If it's a known problem, or maybe we should prepare some more details about this. @Joaovictor144 have you managed to fix the problem in your app?
