### ISSUE TITLE
[v4] | [v2] Bottomsheet is blinked on tab change in android

### ISSUE THREAD

**Issue by amanbansal246** [gorhom/react-native-scroll-bottom-sheet#1830]
# Bug

I have a problem on android.
Bottomsheet is blinking on tab change(see video).
It is working find on IOS.
I can't find any solution, I can't reproduce it, that is what makes it super hard to find.

Maybe someone can say the potential reason behind it as after my checking of the lib, I didn't find anything suspicious.

Here is a video from Android:

https://github.com/gorhom/react-native-bottom-sheet/assets/59927025/d7bc9c9c-a3a2-4b04-8866-a592188a8798

Here is a video from IOS:

https://github.com/gorhom/react-native-bottom-sheet/assets/59927025/c40bba60-065b-4028-813d-528ab61f8da4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.73.7   |
| react-native-reanimated         | 3.8.1   |
| react-native-gesture-handler    | 2.16.0   |

## Steps To Reproduce

1. Install lib.
2. configure everything. with Backdrop.
3. open it via ref.

Describe what you expected to happen:

1. It should not blink on tab change
2.

## Reproducible sample code

	return (
		<>
			<StatusBar backgroundColor='transparent' translucent={true} />
			<SafeAreaView style={{ flex: 1, backgroundColor: '#570E3F' }}>
				<View style={styles.container}>
					<View style={[styles.detail, { paddingTop: inset.top }]}>
						<Text style={styles.heading}>Claims</Text>
						<Text style={styles.description}>File new claims and track the status of existing ones</Text>
					</View>
					<BottomSheet ref={bottomSheetRef} snapPoints={snapPoints} index={0}
						handleIndicatorStyle={{ backgroundColor: 'white' }}
						backgroundStyle={{ backgroundColor: 'white' }}
					>
						<ClaimsSheet />
					</BottomSheet>
				</View>
			</SafeAreaView>
		</>
	);

**Comment by rdnsan** [comment]
same issue

**Comment by eddie-0125** [comment]
Same issue. Did you find a solution?
