### ISSUE TITLE
[v4] | [v2] BottomSheetView doesn't open when Android animations are disabled.

### ISSUE THREAD

**Issue by Yawan-1** [gorhom/react-native-scroll-bottom-sheet#1834]
# Bug
Hi there,

While testing the bottom-sheet feature in my test application, I noticed that my Android animations were disabled, as the "**Remove Animations**" toggle was turned on. After implementing the feature, I attempted to open the `BottomSheetModal, BottomSheetView`, but it appeared for only a brief moment before closing immediately. I realized that the **disabled animations** may have been the cause of this behavior, as the feature supports **react-native-reanimated**. I enabled animations on my phone, and the bottom sheet displayed without any issues.

Is this an issue that is expected due to the dependence on the animation library, which is designed to only function with animations enabled? I believe not, as there are other features in React Native libraries, such as **react-native**'s drawer and Menu, that support animation regardless of the animation settings. Personally, I prefer using my phone with animations disabled, so I believe the functionality should work regardless of the animation settings being enabled or disabled.

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 18.2.0   |
| react-native-reanimated         | 3.6.2   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce
If you are using the Android operating system (I am using Android 10), 

1. Please access your device's settings. 
2. Search for options related to animations, where you can remove or reduce animations. 
3. **Disable animations** completely within this menu. 
4. Once done, return to the Expo app and attempt to open the bottom-sheet using the button. This adjustment may improve the functionality of the bottom-sheet.

I have not conducted testing on **iOS** devices, but there is a function to reduce animations rather than completely disabling them. In this scenario, I believe the bottom sheet may function properly.

Describe what you expected to happen:

1. I expected it work and open the bottom-sheet even when animations are disabled but it didn't

## Reproducible sample code
I am unsure if it is possible to disable the animations for Android section in Expo website. Additionally, I am uncertain if Expo Snap allows for the disablement of animations on websites.

**Comment by deKadir** [comment]
onDismiss fires when animations are disabled

**Comment by Yawan-1** [comment]
Certainly, the current issue is that the bottom is closing immediately when animations are disabled, triggered by the onDismiss event.

**Comment by leahaeussermann** [comment]
having the same issue, as a workaround I did this 

[[https://github.com/gorhom/react-native-bottom-sheet/issues/1560#issuecomment-1750466864](https://github.com/gorhom/react-native-bottom-sheet/issues/1560#issuecomment-1750466864 )]

**Comment by Yawan-1** [comment]
@leahaeussermann Thank you, it was successful. The title of the issue was somewhat misleading as it only mentioned IOS, so I overlooked it initially.
