### ISSUE TITLE
[v4] | [v2] Bottomsheet modal closes unexpectedly when the current location is fetched or location permissions are checked.

### ISSUE THREAD

**Issue by eljornalerodev** [gorhom/react-native-scroll-bottom-sheet#1837]
# Bug

I have a modal that gets the user's location when opened, through expo-location ~17.0.1, sometimes this request is made twice, and it seems that when checking the user's permission to get the location, the modal closes automatically.

When request location, bottom sheet modal is clossed inesperately, sometimes, on open modal, there are a location request on background, an when is called twice, the modal is closed.

seems to only happen on android in all the versions I've tested. 10, 11, 12, 13, 14

## Environment info
    "@gorhom/bottom-sheet": "^4.6.1",
    "expo": "51.0.1",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "3.10.0",
    "react-qr-code": "^2.0.12",

## Steps To Reproduce

1. Get current location with expo-location or check the locations permissións with requestForegroundPermissionsAsync after open the bottomsheet Modal

Describe what you expected to happen:

1. The modal may stay open

## Reproducible sample code

// Get location function example: 

```
import * as Location from 'expo-location'

export async function getCurrentLocation() {
  try {
    let {status} = await Location.requestForegroundPermissionsAsync()
    if (status !== 'granted') {
      return null
    }

    let location = await Location.getCurrentPositionAsync({})
    return location
  } catch (error) {
    console.log('getCurrentLocation -> error', error)
    throw error
  }
}
```

Bottomsheet code: 
in this case I call directly to getCurrentPositionAsync trying to skip the step of checking the location permission, since I ask for it in a step before opening the modal.

```
 async function handleGenerateQr() {
    try {
      if (user) {
        if (Boolean(defaultData?.start) != start) {
          // generate new QR if it's not a defaultData
          setIsLoadingQr(true)
          console.log('executing handleGenerateQr')
          let currentLocation = await getCurrentPositionAsync().catch(err => {
            console.log('getCurrentLocation ->', err)
            showModal({
              title: 'Error',
              message:
                'No se ha podido obtener tu ubicación. asegúrate de tener activado el GPS e inténtalo de nuevo.'
            })
            return
          })
          if (currentLocation) {
            generateQr({currentLocation})
          }
          setIsLoadingQr(false)
        }
      }
    } catch (error) {
      console.log('function handleGenerateQr ->', error)
      throw error
    }
  }

  useEffect(() => {
    handleGenerateQr().then(() => {
      console.log('QR generated')
    })
  }, [])
```

**Comment by zereight** [comment]
Same here.

Does the UI thread get involved and it's gone?

```
// permission code
import { check, openSettings, PERMISSIONS, request, RESULTS } from 'react-native-permissions';

export const requestLocationPermission = async () => {
  const locationPermission =
    Platform.OS === 'android'
      ? PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION
      : PERMISSIONS.IOS.LOCATION_WHEN_IN_USE;
    const granted = await check(locationPermission);
```


```
// bottom sheet code

useEffect(() => {
    requestLocationPermission().then((res) => console.log('res', res));
  }, []);

  return (
    <>
      <BottomSheet
```
