### ISSUE TITLE
[v4] | [v2] 'useBottomSheetInternal' cannot be used out of the BottomSheet!

### ISSUE THREAD

**Issue by shin101004** [gorhom/react-native-scroll-bottom-sheet#1843]
# Bug

The bottom sheet pop-up was used as a long press event on the button, and the above issue is occurring after updating from the existing version 4.5.1 to 4.6.3.

I used BottomSheetScrollView component as children inside BottomSheet .
![스크린샷 2024-05-23 오후 9 02 45](https://github.com/gorhom/react-native-bottom-sheet/assets/61345090/84fbddc8-bda6-47d0-bb62-98857b16f4ce)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.72.8   |
| react-native-reanimated         | 3.11.0   |
| react-native-gesture-handler    | 2.16.2   |

## Steps To Reproduce

1. Use `BottomSheetScrollView` inside `BS`

Describe what you expected to happen:

1. The sheet will show clearly

## Reproducible sample code

https://snack.expo.dev/ulCNOqERGbD9ntBcb8Add

**Comment by sahiljena** [comment]
facing the same issue, did you find any solution?

**Comment by bencripps** [comment]
also running into this; it looks like its related to using latest RN, as using version 0.72 seems to work but 0.77 doesnt

**Comment by bencripps** [comment]
can we reopen this issue?

**Comment by AlixH** [comment]
Up

**Comment by longb1997** [comment]
up

**Comment by cassiBOSSTech** [comment]
having same issue

**Comment by hamonCordova** [comment]
Same problem

**Comment by gigby** [comment]
same problem

**Comment by thanhbtn** [comment]
same problem
