### ISSUE TITLE
[v4] Delay in mounting the bottom sheet on Android devices

### ISSUE THREAD

**Issue by SuhasK3** [gorhom/react-native-scroll-bottom-sheet#1845]
# Bug

On Android bottom sheet mounting takes time. When user lands on the page the component is not visible for some time. The rest of the page is mounted already but the bottom sheet takes around 1 or 2 secs to mount. This issue happens intermittently and only on Android platform. I have already tried passing false to animateOnMount prop but it didn't make any effect.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.4.2   |
| react-native-gesture-handler    | 2.14.0   |

## Steps To Reproduce

1. Wrap the component inside GestureHandlerRootView.
2. Navigate to the page Bottom sheet is used on.

Describe what you expected to happen:

1. There should not be any delay in mounting of bottom sheet. It should be visible immediately when the page this sheet resides on mounts.

## Reproducible sample code

```
<GestureHandlerRootView style={{flex:1}}>
    <View style={{flex:1}}>
        <BottomSheet snapPoints = ['10%', '40%']>
            <BottomSheetView style={{flex:1}}>
            --------
            </BottomSheetView>
        </BottomSheet>
    </View>
</GestureHandlerRootView>
```

**Comment by brunowilliang** [comment]
hey @SuhasK3, did you manage to solve it?

**Comment by aaronfgph** [comment]
I'm seeing this on iOS as well. A screen that has nothing but a bottom sheet with an empty view that has some arbitrary width/height on it. The screen renders and the bottom sheet is not visible for the first 2 seconds or so, then it animates in to the first snap point.
