### ISSUE TITLE
[v4] | [v2] Demo in documentation doesn't work: 'snapPoints' was provided with no points

### ISSUE THREAD

**Issue by vliegelientje** [gorhom/react-native-scroll-bottom-sheet#1847]
# Bug

The demo on https://ui.gorhom.dev/components/bottom-sheet/usage does not work. It seems to be missing some parameters:

Invariant Violation: 'snapPoints' was provided with no points! please provide at least one snap point.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3  |
| react-native                    | 0.74.1   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.2   |

## Steps To Reproduce

1. Installed package
2. Followed the instructions on https://ui.gorhom.dev/components/bottom-sheet/usage

Describe what you expected to happen:

1. See a page with bottom sheet

**Comment by ilfoxo** [comment]
Same for me

**Comment by sebastianbila** [comment]
Guys, just add the **snapPoints**. Don't be stupid, it's easy

**Comment by sebastianbila** [comment]
```js
 <BottomSheet
      ref={bottomRef}
      snapPoints={['30%', '50%']}
      enablePanDownToClose
      onClose={onClose}
    >

**Comment by vliegelientje** [comment]
No need to be rude. There's just so many libraries around that aren't maintained or not working anymore. 
If the demo doesn't work, I don't bother to dive any further in the documentation.

**Comment by ilfoxo** [comment]
Just was reporting the issue in the example... Genius!

**Comment by fubd** [comment]
horrible

**Comment by wangqiJava** [comment]
I also encountered this, using the official demo

**Comment by QandilAFA** [comment]
> Guys, just add the **snapPoints**. Don't be stupid, it's easy

your docs is fakin stupid and you also

**Comment by vliegelientje** [comment]
Just so you know. You can ask ChatGPT to write a Bottom Sheet Select and it will produce working code. Without any third party libraries, so it won't cost you hours to patch after the next RN update. Appreciate the authors efforts but instead of adding the line they rather argue how stupid everyone is while leaving a broken demo on the site. This is what I hate so much about the RN/Expo ecosystem, sorry to say guys.

**Comment by RuyVictor** [comment]
I didn't understand either, just put snapPoints as mandatory (Typescript).

**Comment by SHUHAIB-T** [comment]
the issue still exist. getting error after adding the snapPoint .

**Comment by umer-nazir02** [comment]
I was importing BottomSheetModalProvider like below. 

import BottomSheetModalProvider from '@gorhom/bottom-sheet';

I updated it to this and error went away.

import {BottomSheetModalProvider} from '@gorhom/bottom-sheet';

**Comment by SHUHAIB-T** [comment]
> the issue still exist. getting error after adding the snapPoint .

answering to my own question. issue got resolved after wrapping th app `<GestureHandlerRootView/>.`

[documentation](https://gorhom.dev/react-native-bottom-sheet/)

```ts
   <GestureHandlerRootView style={{ flex: 1 }}>
          <App/>
   </GestureHandlerRootView>
```
