### ISSUE TITLE
Allow Bottom Sheet modal to be added over Expo navigation bottom bar

### ISSUE THREAD

**Issue by lucferrario** [gorhom/react-native-scroll-bottom-sheet#1850]
# Allow bottom sheet modal over expo navigation navigation bar

I am building a react native app with expo navigation, and using bottom sheet modals they stay below the navigation bar.
Like this:
<img width="550" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/72550664/cc7bc658-823b-4497-baba-9289e4185e16">

Reading other discussions on here i noticed people solved the issue on react native navigation through the bottom sheet modal container, which i placed in the root _layout.tsx file:

`return (
    <Provider store={store}>
      <KeyboardProvider>
        <ThemeProvider
          value={colorScheme === "dark" ? DarkTheme : DefaultTheme}
        >
          <BottomSheetModalProvider>
            <Root />
            <BannerError />
          </BottomSheetModalProvider>
        </ThemeProvider>
      </KeyboardProvider>
    </Provider>
  );`

Even after adding it i still can't manage to display the bottom sheet modal over the navigation bar, and I am wondering if it's linked to the fact that instead of react navigation i am using expo navigation.

thanks in advance!

**Comment by GaylordP** [comment]
Hi :)

Have you found a solution?

Thank you so much!

**Comment by lucferrario** [comment]
Hi!

I wish, but i did not. not even with portals or anything.

happy tweaking tho!
