### ISSUE TITLE
[v4] [Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet

### ISSUE THREAD

**Issue by Willham12** [gorhom/react-native-scroll-bottom-sheet#1854]
# Bug

[Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet. See 
https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3   |
| react-native                    | 0.74.1   |
| react-native-reanimated         | 3.12.0   |
| react-native-gesture-handler    | 2.16.2   |

## Steps To Reproduce

Open a Bottomsheet

1.
2.
3. 

Describe what you expected to happen:

1.
2.

## Reproducible sample code

https://github.com/gorhom/react-native-bottom-sheet/blob/4b2a73991d4356ab13904262206abd3e6c8e2869/src/components/bottomSheet/BottomSheet.tsx#L1202

**Comment by fahad86** [comment]
https://github.com/gorhom/react-native-bottom-sheet/pull/1848

**Comment by pixellet14** [comment]
any solution yet?

**Comment by MonishReddyDev** [comment]
ANY SOLUTION

**Comment by paulschreiber** [comment]
@MonishReddyDev @pixellet14 The PR was just approved a few hours ago. Give them time to release a new version.

**Comment by pixellet14** [comment]
> @MonishReddyDev @pixellet14 The PR was just merged a few hours ago. Give them time to release a new version.

The warnings have disappeared now. Looks like it's solved.

**Comment by ebere-hoag** [comment]
Its still showing up for me.

**Comment by duyrk** [comment]
I have the same problem

**Comment by pixellet14** [comment]
how come it has stopped for me??

**Comment by ebere-hoag** [comment]
@paulschreiber because its not showing up for you doesn't mean you should put a thumbs down on others comments.

It happens when i open the bottomsheetmodal

**Comment by paulschreiber** [comment]
@ebere-hoag I am still seeing the problem. I am putting the 👎 because the people are being impatient. The fix has been approved, but not merged or released. Piling on "me too" comments at this point is not helpful.

**Comment by larsmunkholm** [comment]
@paulschreiber Anyone can approve the pull requests, so I'm not sure that really means anything. It hasn't been approved by @gorhom yet :)

**Comment by emrekilavuz** [comment]
if I downgrade to 4.6.1, will this warning be gone?

**Comment by sayan-avantai** [comment]
> if I downgrade to 4.6.1, will this warning be gone?

nothing works till yet.

any update? neither have to use yellowbox/logbox  for now.

**Comment by Nurulloh01** [comment]
did someone resolve it

**Comment by shymaaMohmed** [comment]
I have the same problem

**Comment by mrtawil** [comment]
+1

**Comment by Willham12** [comment]
There is a PR https://github.com/gorhom/react-native-bottom-sheet/pull/1848

**Comment by hdvinhhoang** [comment]
I have the same problem

**Comment by duyrk** [comment]
> #1848
Apply the patch that mentioned in this issue, everything will work just fine.

**Comment by sayan-avantai** [comment]
> There is a PR #1848

thanks. it's working .

**Comment by kashkashio** [comment]
Merging anytime soon?

**Comment by H4mxa** [comment]
+1

**Comment by shuo-hiwintech** [comment]
+1

**Comment by ksevil** [comment]
+1

**Comment by LeandroAlberti** [comment]
+1

**Comment by Zergus-s** [comment]
+1

**Comment by darkartur** [comment]
+1

**Comment by thianphat** [comment]
+1

**Comment by 1mike12** [comment]
another quick workaround without having to fiddle with patches is to set the installation to the proposed PR for now 

```json
{
"dependencies": {
    "@gorhom/bottom-sheet": "pafry7/react-native-bottom-sheet#fix/config-reducerMotion-in-worklet",
    }
}
```

**Comment by tboy44wiz** [comment]
@1mike12 How do I go about with this your suggestion. Which of the app dependencies?

**Comment by bgever** [comment]
Thanks for the tip @1mike12, and thanks for the fix @pafry7!

For yarn, add the following to the root `package.json` (leave your existing dependencies unchanged):

```json
  "resolutions": {
    "@gorhom/bottom-sheet": "github:pafry7/react-native-bottom-sheet#fix/config-reducerMotion-in-worklet"
  },
```

See https://yarnpkg.com/configuration/manifest#resolutions for what it does.

Then run `yarn` from the root package:

```
bart%Barts-MBP2 ~/repos/myapp ➜ yarn                                                                                                                                                                                                                                                                                         
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @gorhom/bottom-sheet@https://github.com/pafry7/react-native-bottom-sheet.git#commit=9c4c6eba41197a92990e79591dc9e6546ab9edbb
➤ YN0085: │ - @gorhom/bottom-sheet@npm:4.6.3
➤ YN0000: └ Completed in 33s 710ms
[...]
``` 

I had to clear the Metro cache before it started to work.

**Comment by LukasMod** [comment]
Any idea why even with this fix I get this warning after modal is opened second time?

First open / close is working fine, but next time when I try to open the same or another BottomSheetModal it shows warning with reduceMotion info. Is it something wrong with implementation here? I use same HOC for all my modals. In children it's usually BottomSheetScrollView. Tried both patch-package and this solution. I can see these code changes in my node_modules so fix is there.



```
const animationConfig: WithSpringConfig | WithTimingConfig = { duration: 400 };

const DrawerModal: React.FC<DrawerModalPropsType> = ({
    visible,
    children,
    onDismiss,
    snapPoints = ['70%'],
    ...rest
}) => {
    const styles = theme();

    const modalRef = useRef<BottomSheetModal>(null);

    if (modalRef) {
        useBottomSheetBack(visible, modalRef, onDismiss);
    }

    useEffect(() => {
        if (visible) {
            InteractionManager.runAfterInteractions(() => {
                modalRef.current?.present();
            });
        } else {
            if (modalRef.current) {
                modalRef.current.close();
            }
        }
    }, [visible]);

    const handleSheetChanges = useCallback((index: number) => {
        if (index === -1) {
            onDismiss?.();
        }
    }, []);

    const renderBackdrop = useCallback(
        (props: BottomSheetBackdropProps) => (
            <BottomSheetBackdrop
                {...props}
                disappearsOnIndex={-1}
                appearsOnIndex={0}
                pressBehavior='close'
            />
        ),
        [],
    );

    return (
        <BottomSheetModal
            ref={modalRef}
            index={0}
            snapPoints={snapPoints}
            onChange={handleSheetChanges}
            animationConfigs={animationConfig}
            enableDismissOnClose
            backdropComponent={renderBackdrop}
            enableContentPanningGesture={false}
            {...rest}>
            {children}
        </BottomSheetModal>
    );
};

export default DrawerModal;
```

**Comment by Willham12** [comment]
fixed with #1848

**Comment by LukasMod** [comment]
@gorhom Can we reopen this issue or should I create a new one? There is still some problem with reopening bottom sheet, same warnings even with 4.6.4. Not only for me https://github.com/gorhom/react-native-bottom-sheet/pull/1848#issuecomment-2282894602

**Comment by sumin0gig** [comment]
I have the same issue

**Comment by bahadiraraz** [comment]
same

**Comment by tushe-tv** [comment]
When `enableDynamicSizing=false`, the warning appears. This is on 5.0.2.

**Comment by Willham12** [comment]
related to: https://github.com/gorhom/react-native-bottom-sheet/issues/1974

**Comment by LukasMod** [comment]
There is no more warnings in my app after upgrading to 5.0.4 (from 4.6.4)

**Comment by mattrltrent** [comment]
No fix yet? Same issue on newest release.
