### ISSUE TITLE
[v4] bugs with prop enableDynamicSizing={true}

### ISSUE THREAD

**Issue by kawasakime** [gorhom/react-native-scroll-bottom-sheet#1859]
# Bug

1. If you set the enableDynamicSizing parameter to true, then the backdrop appears sharply, there is no smoothness, like snapPoints.
2. if the parameter is set to true and if there is an input (BottomSheetTextInput) with autofocus inside the bottom sheet, then the panel does not open - the keyboard appears for a moment, then disappears, while the bottom sheet itself does not appear (only IOS)
3. After it became impossible to work with enableDynamicSizing={true}, I set the value to false and set the size via snapPoints. I discovered a bug that if the panel is less than or equal to 310 pixels, then when you focus on the input, the bottom sheet immediately closes (only Android)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3  |
| react-native                    | 0.72.14   |
| react-native-reanimated         | 3.11.0   |
| react-native-gesture-handler    | 2.16.2   |

## Reproducible sample code

```
  const renderBackdrop = useCallback((backdropProps) => (
    <BottomSheetBackdrop
      {...backdropProps}
      disappearsOnIndex={-1}
      appearsOnIndex={0}
    />
  ), []);
```

```
    <BottomSheet
      ref={bottomSheetRef}
      onClose={onClose}
      topInset={100}
      backgroundStyle={{ backgroundColor: isDark ? colors.backgroundDark : colors.backgroundLight }}
      handleIndicatorStyle={{ backgroundColor: isDark ? colors.backgroundLight : colors.backgroundDark }}
      enablePanDownToClose={true}
      backdropComponent={renderBackdrop}
      enableContentPanningGesture={true}
      enableDynamicSizing={!!props.enableDynamicSizing}
      snapPoints={props.enableDynamicSizing ? null : points}
      keyboardBehavior='interactive'
      keyboardBlurBehavior='restore'
      android_keyboardInputMode='adjustResize'
      {...props}
    >
      {children}
    </BottomSheet>
```

**Comment by cfragkos** [comment]
I can confirm 3. Please look it up

**Comment by kawasakime** [comment]
+1 bug found, if the bottom sheet is open, next then open the modal component and after closing the modal component right away closing the bottom sheet (using method .close() or .forceClose() no difference), and as a result with a high probability bottom sheet will not close (there will be a closing animation, but will immediately open again)

**Comment by ryskin** [comment]
I can confirm too

**Comment by bleszerd** [comment]
I confirm that number 2 is not exclusive to iOS; I am experiencing the same behavior on Android.

**Comment by Simranjit1080** [comment]
I am still facing the issue

**Comment by AlexanderBich** [comment]
+1
