### ISSUE TITLE
[v4] BottomSheetFooter animation does not work with BottomSheetTextInput

### ISSUE THREAD

**Issue by 77zv** [gorhom/react-native-scroll-bottom-sheet#1863]
# Bug

When you use a BottomSheetTextInput inside a BottomSheetFooter, the footer reacts to a keyboard opening by "teleporting" to the correct position without an animation.
The following is a video example.
https://github.com/gorhom/react-native-bottom-sheet/assets/97407806/c9571aba-cf1a-4fd4-9287-2ff32af298a0

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4 |
| react-native                    | 0.74.1  |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.2  |

## Steps To Reproduce

1. Use a BottomSheetTextInput inside a BottomSheetFooter component

Describe what you expected to happen:

1. When focused on the BottomSheetTextInput, the entire footer should move to avoid the keyboard with an animation (animation currently does not work)

## Reproducible sample code
https://staging-snack.expo.dev/jTr3DrUym5MEeeP5NN0g4

**Comment by zcmgyu** [comment]
Not stale. I have the same issue

https://github.com/user-attachments/assets/21eff36d-a3e1-4899-a6ce-6683a7ac89ca

**Comment by brunoegitomob** [comment]
Not stale... i have the same issue

**Comment by michalpawlowski34** [comment]
bump, still same issue
