### ISSUE TITLE
[v4] | [v2] BottomSheetTextInput on focus fires onAnimate like if it was a close animation

### ISSUE THREAD

**Issue by misteeka** [gorhom/react-native-scroll-bottom-sheet#1868]
# Bug

When you focus BottomSheetTextInput it fires onAnimate with fromIndex = 0 and toIndex = -1, like if it was animating from 0 to -1, so if it was a close animation. 
That makes it impossible to blur text input on close animation. I want to do that in onAnimate and not in onChange to make animation of sheet closing and keyboard hiding play at the same time.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.1   |
| react-native                    | 0.74.2   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.1   |

## Steps To Reproduce

1. Open bottom sheet
2. Click on input to focus it
and check console output and see "onAnimate 0 -1"

Describe what you expected to happen:

OnAnimate fromIndex 0 toIndex 0

## Reproducible sample code
https://snack.expo.dev/@maksemen/bottom-sheet-on-animate-with-bottomsheettextinput

**Comment by sudhanshu-busy** [comment]
not stale
