### ISSUE TITLE
[v5] | [v3] createBottomSheetScrollableComponent's ScrollableComponent needs to return a reference that contains a nativeTag to a Native HostComponent.

### ISSUE THREAD

**Issue by wogno** [gorhom/react-native-scroll-bottom-sheet#1871]
# Bug

<img width="483" alt="Capture d’écran 2024-06-28 à 21 29 07" src="https://github.com/gorhom/react-native-bottom-sheet/assets/31076843/76ca882f-9340-455b-a8ce-4b5d356012f3">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |5.0.0-alpha.10  |
| react-native                    | 0.74.2  |
| react-native-reanimated         | ^3.12.1  |
| react-native-gesture-handler    | ^2.17.0   |

## Steps To Reproduce
1. I installed and dependencies(rect native navigation,gesture handler, ....
2. pod install
3. Follow the code one home page

Describe what you expected to happen:

1. Sheet open with his content
2.

## Reproducible sample code
Same with home page

<BottomSheet
        ref={bottomSheetRef}
        onChange={handleSheetChanges}
      >
        <BottomSheetView style={{}}>
          <Text>Awesome 🎉</Text>
        </BottomSheetView>

**Comment by arbaaz-suggaa** [comment]
any update on this?

**Comment by wogno** [comment]
Not official comment but I found at patch that can resolve it, but still have snatpoint not working well. 

path name: @gorhom+bottom-sheet+5.0.0-alpha.10.patch

diff --git a/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts b/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
index d4f3cc4..794a175 100644
--- a/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
+++ b/node_modules/@gorhom/bottom-sheet/src/utilities/getRefNativeTag.ts
@@ -27,17 +27,17 @@ export function getRefNativeTag(ref: unknown) {
     nativeTag = ref.current._nativeTag;
   }
 
-  if (!nativeTag || typeof nativeTag !== 'number') {
-    throw new Error(
-      `Unexpected nativeTag: ${refType}; nativeTag=${nativeTag} 
+  // if (!nativeTag || typeof nativeTag !== 'number') {
+  //   throw new Error(
+  //     `Unexpected nativeTag: ${refType}; nativeTag=${nativeTag} 
 
-			createBottomSheetScrollableComponent's ScrollableComponent needs to return 
-			a reference that contains a nativeTag to a Native HostComponent.
+	// 		createBottomSheetScrollableComponent's ScrollableComponent needs to return 
+	// 		a reference that contains a nativeTag to a Native HostComponent.
 
-			ref=${ref}
-			`
-    );
-  }
+	// 		ref=${ref}
+	// 		`
+  //   );
+  // }
 
   return nativeTag;
 }

**Comment by wogno** [comment]
[@gorhom+bottom-sheet+5.0.0-alpha.10.patch](https://github.com/user-attachments/files/16161693/%40gorhom%2Bbottom-sheet%2B5.0.0-alpha.10.patch)

**Comment by wogno** [comment]
You can use this one waiting the official update.

**Comment by arbaaz-suggaa** [comment]
okay thanks

**Comment by Feridinha** [comment]
> You can use this one waiting the official update.

Thank you

**Comment by piotr-sobczyk** [comment]
I think this has been solved by 4.6.4 version ([link](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v4.6.4)), and more specifically by this part:
> replace getRefNativeTag with findNodeHandle (https://github.com/gorhom/react-native-bottom-sheet/issues/1823)(by @AndreiCalazans) ([b906f5e](https://github.com/gorhom/react-native-bottom-sheet/commit/b906f5e67afdb823b7c31a9a929e757fc35222a2))

In that version the nativeTag error has been fixed but instead there is some console.warn being printed now 😅 (I reported it [here](https://github.com/gorhom/react-native-bottom-sheet/issues/1919))

**Comment by gorhom** [comment]
could you test on alpha11 ?
