### ISSUE TITLE
Reanimated v3

### ISSUE THREAD

**Issue by Sydney-o9** [gorhom/react-native-scroll-bottom-sheet#1874]
# Feature Request

Is there value to upgrade to Reanimated v3? If we spend time to do it @gorhom will you review the PR? There shouldn’t be breaking changes: https://docs.swmansion.com/react-native-reanimated/docs/guides/migration-from-2.x/

## Why it is needed

Upgrading to v3 prevents breaking changes for upcoming reanimated releases.

## Possible implementation

There shouldn’t be breaking changes: https://docs.swmansion.com/react-native-reanimated/docs/guides/migration-from-2.x/

### Code sample

N/A

**Comment by LeonDvlpmnt** [comment]
This already available in V5 alpha https://github.com/gorhom/react-native-bottom-sheet/tree/v5

Install it with `npm install @gorhom/bottom-sheet@5.0.0-alpha.10`
