### ISSUE TITLE
[v4] Can't interact with (click on) the sheet when the keyboard is active

### ISSUE THREAD

**Issue by rami-maalouf** [gorhom/react-native-scroll-bottom-sheet#1877]
# Bug
You can't interact with (click on) the sheet when the keyboard is active when usually other pages allow you to do so

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3   |
| react-native                    | 0.74.2  |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.2   |

## Steps To Reproduce
Create a bottom sheet that has a button and [bottomSheetKeyboard](https://ui.gorhom.dev/components/bottom-sheet/components/bottomsheettextinput). Open the keyboard and try to click on the button. It won't allow you. You need to close the keyboard first before being able to click on the button

1. Create a bottom sheet that has a button and [bottomSheetKeyboard](https://ui.gorhom.dev/components/bottom-sheet/components/bottomsheettextinput).
3. Open the keyboard and try to click on the button. It won't allow you. You need to close the keyboard first before being able to click on the button

Describe what you expected to happen:

1. I want to be able to interact with the bottom sheet even if the keyboard is active, just as typical pages do

## Reproducible sample code

the snack doesn't work properly

**Comment by rami-maalouf** [comment]
Nevermind it's my code that's wrong

**Comment by jwparsons** [comment]
If anyone else runs into this issue, the solution is to set `keyboardShouldPersistTaps` on your scroll view:
```javascript
<BottomSheetScrollView keyboardShouldPersistTaps={true} />
```
