### ISSUE TITLE
iOS + input field not pushing the bottom sheet upwards / out of the way when keyboard is open

### ISSUE THREAD

**Issue by jamesbtlr** [gorhom/react-native-scroll-bottom-sheet#1880]
When using the bottom sheet and an input field within it: 

On iOS the keyboard opening does not push the bottom sheet upwards, so the keyboard loads in over the top of the input field/bottom sheet itself. This means that a user can type into the input field, but can't see the content of what they're typing. Expected behaviour would be that the bottom sheet gets pushed further up the screen, above they keyboard input.

This doesn't seem to be the case on Android, where this works as expected and the keyboard being open pushes the bottom sheet upwards.

 "@gorhom/bottom-sheet": "^4.6.3",
 "react-native": "^0.73.6",

**Comment by sudhanshu-busy** [comment]
same issue
