### ISSUE TITLE
[v5] Incorrect `keyboardBlurBehavior="restore"` Behavior

### ISSUE THREAD

**Issue by cyanChill** [gorhom/react-native-scroll-bottom-sheet#1887]
# Bug

In `v5.0.0-alpha.10`, having `keyboardBlurBehavior="restore"` on `<BottomSheet />` does not restore the sheet position (ie: doesn't position itself back to the bottom of the screen). The expected behavior is displayed in `v5.0.0-alpha.9`.

I used the `detached` prop to make it more visible.

<table>
  <tr>
    <th>v5.0.0-alpha.9</th>
    <th>v5.0.0-alpha.10</th>
  </tr>
  <tr>
    <td>
     <img src="https://raw.githubusercontent.com/cyanChill/gorhom-v5-keyboardBlurBehavior/main/assets/v5-alpha9.gif" alt="Behavior of `keyboardBlurBehavior='restore'` in `@gorhom/bottom-sheet@5.0.0-alpha.9`." >
    </td>
    <td>
     <img src="https://raw.githubusercontent.com/cyanChill/gorhom-v5-keyboardBlurBehavior/main/assets/v5-alpha10.gif" alt="Behavior of `keyboardBlurBehavior='restore'` in `@gorhom/bottom-sheet@5.0.0-alpha.10`." >
    </td>
  </tr>
</table>

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.10   |
| react-native                    | 0.74.3   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.1   |

## Steps To Reproduce

1. Have `keyboardBlurBehavior="restore"` on `<BottomSheet />`.
2. Have a `<BottomSheetTextInput />` and focus on it.
3. Then, close the keyboard (ie: through the "back" gesture on Android).

Describe what you expected to happen:

1. Bottom sheet should restore its position and hug the bottom of the screen when we dismiss the keyboard.

## Reproducible sample code

Here's the repository with 2 identical projects built from `pnpm create expo-app --template blank-typescript`, one using `@gorhom/bottom-sheet@5.0.0-alpha.9` and the other using `@gorhom/bottom-sheet@5.0.0-alpha.10`: https://github.com/cyanChill/gorhom-v5-keyboardBlurBehavior

For simplicity, you can run the examples with Expo Go (ie: run `npm run start`).

**Comment by gorhom** [comment]
Thanks for reporting this, the bug is related to keyboard input mode set to resize.

I'm working on a fix at the moment, it should be fixed on the next release

**Comment by gorhom** [comment]
@cyanChill this should be fixed in `5.0.0-alpha.11`

**Comment by cyanChill** [comment]
Confirmed that it fixed the bug, thanks!

**Comment by uros808** [comment]
Having the same issue in 5.2.6. iOS only

**Comment by lucksp** [comment]
I am also seeing this on iOS again @gorhom 
- (Looks OK on Android)


-  "@gorhom/bottom-sheet": "^5.1.8" > upgraded to `^5.2.6` with same result.
```js
<BottomSheetTextInput
            onChangeText={handleSearchTextChange}
            onPressIn={() => setShowSearch(true)}
            placeholder="Search for a location"
            returnKeyType={'done'} // changing has no impact
            spellCheck={false}
            style={styles.inputContainer}
            value={searchText}
          />
```

https://github.com/user-attachments/assets/393bea96-6f86-49ec-af2b-f55963c56f79

**Comment by lucksp** [comment]
> Having the same issue in 5.2.6. iOS only

@uros808  - any chance you're able to create a new issue, with a repo?

**Comment by uros808** [comment]
Cant do it unfortunately. Btw try downgrading to 5.1.2, it helped me

**Comment by lucksp** [comment]
> Cant do it unfortunately. Btw try downgrading to 5.1.2, it helped me

do you have `keyboardBehavior="extend"` also with the `keyboardBehavior="restore"`?

**Comment by lucksp** [comment]
> Cant do it unfortunately. Btw try downgrading to 5.1.2, it helped me

this did not resolve for me...

**Comment by sefrijn** [comment]
Had the same issue. Managed to solve it by using a normal RN `TextInput` instead of `BottomSheetTextInput`.

I was running into this issue when having a `BottomSheetTextInput` inside a `BottomSheetScrollView` inside a `BottomSheetModal` with `keyboardBehavior="extend"` and `keyboardBlurBehavior="restore"`.

In my solution I use the `onBlur` and `onFocus` methods of the regular `TextInput` to call `snapToIndex` function from the BottomSheetModal. For my project the TextInput is at the top of the Modal, but if it is further down, you could perhaps also call RN ScrollView `ScrollTo` method.
