### ISSUE TITLE
[v5] enableDynamicSizing={false} does not work

### ISSUE THREAD

**Issue by giantslogik** [gorhom/react-native-scroll-bottom-sheet#1888]
# Bug
The bottom sheet does not snap open when using enableDynamicSizing and calling the imperative .expand() api.
[There is also a reduceMotion related reanimated warning.](https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.10   |
| react-native                    | 0.73.6  |
| react-native-reanimated         | 3.13.0   |
| react-native-gesture-handler    | 2.17.1   |

## Steps To Reproduce
    1. Use a bottom sheet with snapPoints = {[75%]} and enableDynamicSizing={false} and index={-1}
    2. call .expand()

Describe what you expected to happen:

1.  Bottom sheet expand.

## Reproducible sample code

```
  <BottomSheet
        animateOnMount={false}
        enableContentPanningGesture={false}
        enablePanDownToClose
        ...
        index={-1}
        ref={bottomSheetRef}
        snapPoints={['75%']}
        enableDynamicSizing={false}
      >
        {children}
      </BottomSheet>
```

**Comment by giantslogik** [comment]
next position is undefined in the logs:
[fun::bound animateToPosition] currentPosition:932 nextPosition:undefined

**Comment by giantslogik** [comment]
Root cause is this sharedValue is initialized with index 0, so BottomSheet already thinks its at the correct index, within expand.
`const animatedNextPositionIndex = useSharedValue(0);`

**Comment by giantslogik** [comment]
Patch to fix enableDynamicSizing={false} and fix reanimated errors.

[@gorhom+bottom-sheet+5.0.0-alpha.10.patch](https://github.com/user-attachments/files/16246933/%40gorhom%2Bbottom-sheet%2B5.0.0-alpha.10.patch)

**Comment by gorhom** [comment]
tested the issue, and it seems working as expected. 

im closing the issue, please re-open it with a reproducible sample code
