### ISSUE TITLE
[v4] | [v2] Scrolling inside BottomSheetModal cause parent NativeStackModal to close on IOS

### ISSUE THREAD

**Issue by GeekJC** [gorhom/react-native-scroll-bottom-sheet#1889]
# Bug

When using BottomSheetModal inside a NativeStack Screen with presentation: "modal", if the component inside BottomSheetModal is scrollable, it will close the parent NativeStackScreen.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.6.3   |
| react-native                    | 0.74.3   |
| react-native-reanimated         | ~3.14.0  |
| react-native-gesture-handler    | ~2.16.1   |
| react-navigation/native    | ^6.0.2   |

## Steps To Reproduce

https://github.com/user-attachments/assets/a51a79f2-b281-4f5e-aac8-45113f2c8567

1. Open a screen with NativeStack, presentation : "modal"
2. Present a BottomSheetModal inside the Screen
3. Add ScrollView inside the modal
4. Scroll down inside the modal
5. Parent NativeStack Close as well

Describe what you expected to happen:

1. Only the BottomSheetModal should be dismissed

## Reproducible sample code

```
const NativeStackModal = () => {
  const previewModalRef = useRef<BottomSheetModal>(null);
  const snapPoints = useMemo(() => ["100%"], []);

  return (
    <BottomSheetModalProvider>
      <View style={styles.temp}>
        <Text
          text="Open BottomSheetModal"
          onPress={() => {
            previewModalRef.current?.present();
          }}
        />
        <BottomSheetModal
          ref={previewModalRef}
          index={0}
          snapPoints={snapPoints}
          enablePanDownToClose={false}
          handleComponent={null}
        >
          <BottomSheetScrollView contentContainerStyle={styles.temp}>
            <Text text="In Modal" />
          </BottomSheetScrollView>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};
```

**Comment by w4sk1** [comment]
I'm experiencing the same issue. I found that disabling the scroll for `BottomSheetScrollView` resolves the problem, but for me, that is not a viable workaround as the content of my bottom sheet needs to be scrollable.

```
...
<BottomSheetScrollView scrollEnabled={false} contentContainerStyle={styles.temp}>
   ...
</BottomSheetScrollView>
...
```

**Comment by GeekJC** [comment]
> I'm experiencing the same issue. I found that disabling the scroll for `BottomSheetScrollView` resolves the problem, but for me, that is not a viable workaround as the content of my bottom sheet needs to be scrollable.
> 
> ```
> ...
> <BottomSheetScrollView scrollEnabled={false} contentContainerStyle={styles.temp}>
>    ...
> </BottomSheetScrollView>
> ...
> ```

This doesn't seem like a good solution... I need the view to be scrolled.
I am currently replacing the bottomsheetmodal with a Stack.Screen but would be the best if we can resolve this issue.

**Comment by first-dev** [comment]
any updates on this?

**Comment by GiorgioBertolotti** [comment]
I found this workaround that seems to work fine for me, but that's not the best solution for sure...

Adding a fake `refreshControl` seems to keep the `BottomSheetScrollView` scrollable and avoid to close the `modal` presented screen:

```
refreshControl={
    Platform.OS === "ios" ? <RefreshControl refreshing={false} style={{ opacity: 0 }} /> : undefined
}
```
