### ISSUE TITLE
Android release mode: App crash when keyboard is open and trying to dismiss the bottom sheet

### ISSUE THREAD

**Issue by liellevi** [gorhom/react-native-scroll-bottom-sheet#1893]
Bug description:
I use BottomSheetTextInput as buttom sheet component with text inputs.
in debug mode it works good
in release mode, when keyboard is open, trying to dismiss the  all the app crash
attached screen record of the bug.

-->

## Environment info
reproduce in Android (S20, Android version 13)

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.6.3  |
| react-native                    | 0.70.8   |
| react-native-reanimated         | ^2.2.4  |
| react-native-gesture-handler    | ^2.8.0   |

## Steps To Reproduce

my component looks like that:

```
      <BottomSheetTextInput
            value={value}
            autoCapitalize="none"
            autoCorrect={false}
            onChangeText={onValueChange || setValue}
            textContentType={isOtp ? 'oneTimeCode' : 'telephoneNumber'}
            keyboardType={keyboardType || 'phone-pad'}
            style={[styles.inputStyle, { marginHorizontal: calculateSize(10) }]}
            maxLength={maxLength}
          />

```

https://github.com/user-attachments/assets/2243933a-5569-4b46-ae86-31d60629cf90

**Comment by aldhyx** [comment]
I'm facing the same problem, do you find a way to solve it?
