### ISSUE TITLE
[v4] keyboardBehavior="extend" and keyboardBlurBehavior="restore" not work together

### ISSUE THREAD

**Issue by zcmgyu** [gorhom/react-native-scroll-bottom-sheet#1894]
# Bug

In version 4 of the `@gorhom/bottom-sheet` library, there appears to be a conflict between the `keyboardBehavior` set to `"extend"` and the `keyboardBlurBehavior` set to `"restore"`. When the `BottomSheetModal` is initially at a `snapPoint` of `"25%"` and the keyboard is activated, the modal correctly extends to `"60%"`. However, upon the keyboard's dismissal, the modal fails to restore back to the `"25%"` snap point as expected.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3   |
| react-native                    | 0.74.3   |
| react-native-reanimated         | ^3.14.0  |
| react-native-gesture-handler    | 4.6.3  |

## Steps To Reproduce

1. Initialize `BottomSheetModal` with `snapPoints` set to `["25%", "60%"]`.
2. Set `keyboardBehavior` to `"extend"` and `keyboardBlurBehavior` to `"restore"`.
3. Set `BottomSheetTextInput` as children component
3. Trigger the keyboard to appear by focusing on TextInput. Observe the modal extending to `"60%"`.
4. Dismiss the keyboard and observe the modal's failure to restore to `"25%"`.

Describe what you expected to happen:

1. When the keyboard is dismissed, the `BottomSheetModal` should restore back to the initial `"25%"` snap point.
2. The modal's behavior should be consistent with the defined properties for keyboard interaction.

## Reproducible sample code

https://github.com/zcmgyu/repoduce-bottom-sheet-issue

**Comment by longnguyen2508** [comment]
Bump

**Comment by sudhanshu-busy** [comment]
any solution?

**Comment by mabdurrafey-afl** [comment]
not stale

**Comment by TadasSipavicius** [comment]
I've found a solution:

BottomSheetModal must have those properties:
```
      keyboardBehavior="interactive"
      keyboardBlurBehavior="restore"
      android_keyboardInputMode="adjustResize"
```

The key point is to make `enableDynamicSizing={true}`
And remove snapPoints.
