### ISSUE TITLE
[v5] | [v2] unable to call `snapToIndex`

### ISSUE THREAD

**Issue by mojjominion** [gorhom/react-native-scroll-bottom-sheet#1900]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.10  |
| react-native                    | 0.74.3  |
| react-native-reanimated         | 3.14.0   |
| react-native-gesture-handler    | 2.17.1   |

## Steps To Reproduce

1. Setup BottomSheet component 
2. Try calling `snapToIndex`

Describe what you expected to happen:

1. It should not throw the error `'index' was provided but out of the provided snap points range! expected value to be between -1, 0`

## Reproducible sample code

https://snack.expo.dev/@mohan1o1/brave-green-milkshake?platform=android

**Comment by gorhom** [comment]
you need to disable the `enableDynamicSizing` , since you did not wrap you bottom sheet content with `BottomSheetView`

**Comment by mojjominion** [comment]
Thanks for letting me know. Making `enableDynamicSizing: false` works fine.

Couldn't get why it's not working without explicitly setting it false though since the default value is false [here](https://ui.gorhom.dev/components/bottom-sheet/props#enabledynamicsizing)

**Comment by yyyyyyounger** [comment]
> Thanks for letting me know. Making `enableDynamicSizing: false` works fine.
> 
> Couldn't get why it's not working without explicitly setting it false though since the default value is false [here](https://ui.gorhom.dev/components/bottom-sheet/props#enabledynamicsizing)

Same issues here. 
It works fine after add `enableDynamicSizing={false}`, but don't understand why the document's `@default false` doesn't work.
