### ISSUE TITLE
BottomSheet flickers on dynamic height changes

### ISSUE THREAD

**Issue by Swikriti0998** [gorhom/react-native-scroll-bottom-sheet#1906]
# Bug
  Bottom sheet flickering when the content inside it changes size.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1  |
| react-native                    | ^0.73.6   |
| react-native-reanimated         | ~3.6.2   |
| react-native-gesture-handler    | ~2.14.1  |

## Steps To Reproduce

1. Open the bottom sheet, start typing in the input field, click button
2. On error it adds a view below the input field, but before that it closes for a fraction of second and then open again

https://github.com/user-attachments/assets/072cfaf8-9f86-41d5-ad91-bcdc38d353e1

 

Describe what you expected to happen:

1. On button click it should not close the bottom sheet rather increase the size of the sheet

## Reproducible sample code
`<BottomSheet ref={passwordRef} enableDynamicSizing>
<BottomSheetView className="w-full px-3" style={{ paddingBottom }}>
<KeyboardAvoidingView className="px-1" behavior="padding">
<BottomSheetView>
<Text className="my-3 font-semibold">
Password
</Text>
<BottomSheetView>
<BottomInput
autoCapitalize="none"
placeholder={"Enter user name"}
onChangeText={onChangeText}
value={username}
/>
{error && (
<AnimatedView layout={LinearTransition}>
<Text className="text-error-300">{error}</Text>
</AnimatedView>
)}
<BottomSheetView className="mt-5">
<Button
label={"Submit}
loading={isLoading}
variant="primary"
onPress={submit}
/>
</BottomSheetView>
</BottomSheetView>
</BottomSheetView>
</KeyboardAvoidingView>
</BottomSheetView>
</BottomSheet>`

**Comment by DaltonPelkey** [comment]
Probably related to https://github.com/gorhom/react-native-bottom-sheet/issues/1763#issuecomment-2237483436

**Comment by Swikriti0998** [comment]
@DaltonPelkey the problem is its closing and then opening again whenever there is any height change which is why it looks like it is flickering.
