### ISSUE TITLE
Optionally pass data to close and make accessible in the onChange 

### ISSUE THREAD

**Issue by ed-sparkes** [gorhom/react-native-scroll-bottom-sheet#1912]
# Feature Request

Sometimes it is useful to have additional context about why a bottom sheet is closed, especially a bottom sheet that is used for an alert. Was the action successful or cancelled for example?

## Why it is needed

It would be useful to be able to provide a types arbitrary payload to `close` and have that accessible in the `onChange` function so that the host of the bottom sheet can make informed decision about how to react in event of a closure depending on this context. 

### Code sample

```typescript

const data = { wasSuccess: true }
sheetRef.current.close(data)

...

<BottomSheet onClose=((index, data) => {
    if (index < 0 ){
        // this is a close 
        if (data.success) {
            // do something
        } else {
            // do something else
        }

    }
}) >
....
```

**Comment by hanwenbo** [comment]
onChange is BUG
