### ISSUE TITLE
[v4] "Couldn't find the scrollable node handle id!" console warning printed from BottomSheetScrollView in tests

### ISSUE THREAD

**Issue by piotr-sobczyk** [gorhom/react-native-scroll-bottom-sheet#1919]
# Bug

After bumping to 4.6.3 to, when the `BottomSheetScrollView` component is rendered in jest environment it now prints the following console.warn(): 
```
Couldn't find the scrollable node handle id!
```

Other than that, everything is fully functional in runtime and test environment.

It's mostly a result of this change: https://github.com/gorhom/react-native-bottom-sheet/pull/1823 (but console.warn is still much better than the `Unexpected nativeTag: object; nativeTag=undefined` error that was thrown before 🙏 🙏 )

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.3   |
| react-native                    | 0.74.5   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.2   |

## Steps To Reproduce

1. Execute a jest tests that is rendering any component tree including `BottomSheetScrollView`
2. "Couldn't find the scrollable node handle id!" warning is printed
3. 

Describe what you expected to happen:

1. I expected no `console.warn`s to be printed.
2.

## Reproducible sample code

Any jest test running the code with BottomSheetScrollView will reproduce the issue.

**Comment by dathuynh-eh** [comment]
@piotr-sobczyk I get the same issue. Do we have any solution for this?

**Comment by MariuzM** [comment]
This with expo 54 started showing as warning `Couldn't find the scrollable node handle id!`

**Comment by raffidahmad** [comment]
Same issue in expo 54

**Comment by prince272** [comment]
Same issue too

**Comment by joshmohrer** [comment]
same here.

**Comment by tylerbecks** [comment]
same here

**Comment by tahayeslbg** [comment]
I'm having the same issue with expo 54.

**Comment by renanmav** [comment]
This seems to be an issue with `useScrollableSetter`, ref is null here:

```ts
  // callbacks
  const handleSettingScrollable = useCallback(() => {
    // set current content offset
    animatedScrollableState.set(state => ({
      ...state,
      contentOffsetY: contentOffsetY.value,
      type,
      refreshable,
    }));

    // set current scrollable ref
    console.log('ref.current', ref.current); // 👈 this is null
    const id = findNodeHandle(ref.current);
    if (id) {
      setScrollableRef({
        id: id,
        node: ref,
      });
    } else {
      console.warn(`Couldn't find the scrollable node handle id!`);
    }
```

Solved temporarily with this patch https://github.com/gorhom/react-native-bottom-sheet/pull/2374#issuecomment-3289580952

**Comment by ko-devHong** [comment]
I downloaded the last version of `nativewind` and solved it.

**Comment by oguzhantufenk** [comment]
I was using 2.28.0 
Updated it to "react-native-gesture-handler": "2.30.0" and it's fixed.
