### ISSUE TITLE
✨ Add support for React 19.

### ISSUE THREAD

**Issue by oviirup** [gorhom/react-native-scroll-bottom-sheet#1921]
# Feature Request

Add Support for React 19, and ref-as-props

## Why it is needed

As of August 2024 React 19 is not directly supported by expo or react-native, but it will in near future (at least hope so). Currently if I use React 19 with expo it will give the following error...

```
Accessing element.ref was removed in React 19. It will be removed from the JSX Element type in a future release.
```

**Comment by eriknyk** [comment]
is this currently fixed?
it cause a litle bit noise.

<img width="546" height="151" alt="Image" src="https://github.com/user-attachments/assets/594761c9-18da-42c5-80e2-1a1ad513de54" />
