### ISSUE TITLE
[v4] build issue with new react-native-reanimated version

### ISSUE THREAD

**Issue by gurbela** [gorhom/react-native-scroll-bottom-sheet#1927]
# Bug
I was built on MacOS Sonoma 14.6.1 with new architect of react native enabled.

Installing a new version of reanimated has a conflict:
Mismatch between JavaScript code version and Reanimated Babel plugin version (3.15.1 vs. 3.15.0)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.4  |
| react-native                    | 0.75.2  |
| react-native-reanimated         | 3.15.0 |
| react-native-gesture-handler    | 2.18.1  |

## Steps To Reproduce

1. install latest react-native-reanimated version

Describe what you expected to happen:

1. I want to install the latest version of reanimated

**Comment by radko93** [comment]
This is not an issue within this library. Restart your packager with clear cache and it will work.
