### ISSUE TITLE
[v4] | [v2] Mapbox MapView is overflowing to backdropComponent when scrolling.

### ISSUE THREAD

**Issue by nabilseid** [gorhom/react-native-scroll-bottom-sheet#1933]
# Bug

BottomSheetScrollView fails to hide Mapbox on backdrop area when scrolling. It hides other elements but Mapview is still visible. I tried z-index, setting overflow to hidden. Nothing worked. The issue is happening on android. I haven't tested it in iOS.

<img src="https://github.com/user-attachments/assets/a83e8717-709e-4b3a-95e5-8868060ec9f4" width="200" height="400" />
<br />
<img src="https://github.com/user-attachments/assets/0087c1de-8356-4254-8665-71db79489cea" width="200" height="400" />

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.6.4   |
| react-native                    | 0.74.2   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.1   |

## Reproducible sample code

```tsx

const renderBackdrop = useCallback(
    (props: any) => (
      <BottomSheetBackdrop
        {...props}
        pressBehavior="collapse"
      />
    ),
    []
  );

const renderMap = useCallback(
    (mapData, index) => (
      <MapCard key={index} mapData={mapData} />
    ),
    []
 );

return (
    <>
      {/* Floating Button */}
      <Animated.View style={[animatedCloseWrapper]}>
        {props.floatingHeader && props.floatingHeader()}
      </Animated.View>

      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        index={1}
        backdropComponent={renderBackdrop}
        enablePanDownToClose={false}
        animatedPosition={bottomSheetPosition}
      >
        <BottomSheetScrollView style={{ padding: 15 }}>
          {data && data.map(renderMap)}
        </BottomSheetScrollView>
      </BottomSheet>
    </>
  );
```

BottomSheetScrollView seems to work fine without MapBox.

**Comment by instesti** [comment]
Any resolution on this? We have the same issue

**Comment by FernandoAOborges** [comment]
I'm rendering a Mapbox map inside a React Native Modal using @rnmapbox/maps. Even though I’ve wrapped it like this:

```
<View style={{ height: containerSize, overflow: 'hidden', borderRadius: 10 }}>
  <AppMapView style={{ flex: 1, borderRadius: 10 }} />
</View>
```
…the map still overflows the container and pushes sibling content downward. It seems like overflow: 'hidden' isn’t working inside the modal.

I found that Mapbox views are native and ignore JS clipping — for example, [issue #2930](https://github.com/rnmapbox/maps/issues/2930) on the rnmapbox/maps GitHub mentions that Android overlays don’t respect overflow: 'hidden'.

Has anyone experienced this issue specifically within a Modal? Are there any known workarounds? I’ve also tried setting borderRadius directly on the map, but it still doesn’t clip correctly and continues to shift the layout.

Any help would be greatly appreciated!
