### ISSUE TITLE
[v4] | [v2] Issue With Swipe down to Close Gesture With FooterComponent

### ISSUE THREAD

**Issue by arinjay-d11** [gorhom/react-native-scroll-bottom-sheet#1937]
# Bug
Integration of Gorhom Bottom Sheet in Our Project:

In our project, we are utilizing the Gorhom Bottom Sheet library to implement a highly customizable and flexible bottom sheet component. The library allows us to efficiently manage sheet content and interactions like gestures, which are crucial for our use case.

Issue with Footer Component:
While integrating the FooterComponent provided by the Gorhom Bottom Sheet, we encountered an issue with the behavior of the footer when used as footerComponent. Specifically, when performing the swipe down gesture to close the bottom sheet, the main content of the bottom sheet dismisses as expected. However, the FooterComponent does not close simultaneously with the rest of the content.

Observed Behavior:
During the swipe down gesture to close the bottom sheet, the content within the sheet closes first.
After the content closes, the FooterComponent remains briefly visible before it finally disappears, resulting in a non-smooth close gesture.
This issue disrupts the expected user experience, as the footer should close together with the rest of the bottom sheet content.
To better illustrate this issue, I have attached a video showcasing the behavior during the swipe-down-to-close gesture.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.3   |
| react-native                    |0.72.5   |
| react-native-reanimated         |3.4.0 |
| react-native-gesture-handler    | 3.3.2  |

## Steps To Reproduce

1.Clone the Repo
2. Run "yarn"
3. Run "yarn android"
4. After successfully install , Tap on "Open bottom sheet"
5. Close it via , Swipe down to close gesture slowly , we can clearly see the content disappear first and then the footer disappears.

Describe what you expected to happen:

1. The footer should close first
2. After the footer content should gets close 

## Reproducible sample code
Attached the Minimal Reproducible Code 
https://github.com/arinjay-d11/gorhom-bottom-sheet-footer-sample
### Reproducible sample video :
https://github.com/user-attachments/assets/8a3091db-6f31-4ca9-813d-a4b775704127

**Comment by ahmedam55** [comment]
Not stale

**Comment by iatomic1** [comment]
> Not stale

Found a fix ?

**Comment by Zakyyy** [comment]
any updates?

**Comment by kunalshivhare-unify** [comment]
I'm facing this issue. 
Can we reopen this thread
