### ISSUE TITLE
React Native New Architecture support

### ISSUE THREAD

**Issue by mrweiss** [gorhom/react-native-scroll-bottom-sheet#1944]
# Feature Request

React Native new architecture compatibility - is this a plan? what are the main reasons the package is not compatible?

## Why it is needed

It's the direction React Native is going forward https://reactnative.dev/docs/the-new-architecture/landing-page

[(https://reactnative.directory/?search=gorhom%2Fbottom-sheet)](https://reactnative.directory/?search=gorhom%2Fbottom-sheet)

![image](https://github.com/user-attachments/assets/fb14a22d-d98d-4c07-a9c2-14f3373f8b90)

## Possible implementation

A technical assessment would have to be done to align with New Architecture requirements

### Code sample

Not possible until technical assessment

**Comment by daves28** [comment]
The New Architecture is for Expo, not for React, but yes I agree a hugely popular library like this should consider becoming compatible.

**Comment by mrweiss** [comment]
> The New Architecture is for Expo, not for React, but yes I agree a hugely popular library like this should consider becoming compatible.

sorry my bad! changed the title to React **Native** New Architecture :) not just Expo, though!

**Comment by iliapnmrv** [comment]
Hey! This library does not have any native part so it does support New Architecture by default. I've just created a new app with new architecture and rn-bottom-sheet works fine for me

**Comment by daves28** [comment]
That makes sense. This site is incorrectly reporting that this library is incompatible then [https://reactnative.directory/?search=bottom-sheet](https://reactnative.directory/?search=bottom-sheet )

**Comment by iliapnmrv** [comment]
https://github.com/react-native-community/directory/pull/1198 this pr set value to `false`
@0xFA11 Hey! Are you sure this library does not support New Architecture?

**Comment by 0xFA11** [comment]
I didn't test recently but I'd say please use this thread for proper testing on v5: https://github.com/gorhom/react-native-bottom-sheet/pull/1823

Attempted fix didn't really fix it for me in the past (I still had issues with Expo51 + Reanimated3 + bottom sheet scrollview).

I'd suggest testing v5 thoroughly with all components, including bottomsheet scrollview etc and potentially using a simple reanimated3 based view with bottomsheet's exposed animIndex somewhere too.

other than that, if everything looks good then let's call it newArch-supported.

**Comment by mateoabrbt** [comment]
I just try it out it seems i little bit buggy even with v5 sometime the modal would just not open i'm gonna try to see what could cause that.

**Comment by qnrjs42** [comment]
> I just try it out it seems i little bit buggy even with v5 sometime the modal would just not open i'm gonna try to see what could cause that.

same.

**Comment by bahadiraraz** [comment]
Based on my testing results, bottom sheets are not functioning correctly in v5 when using React Native's new architecture - they simply don't open. While bottom sheet v4 is still working, it generates multiple console warnings during operation. The issue appears to be specifically related to the bottom sheet animation and mounting behavior in conjunction with the new architecture.

**Comment by mateoabrbt** [comment]
I would add that i create a custom component passing multiple children inside it and it simply didn't open but using a more simple approach works. It wasn't working for me on V4 also. I would suggest to try out the present method for opening the modal on new architecture.

**Comment by gorhom** [comment]
the library been tested on new arch and it is working , feel free to cut a another ticket if you discover new issues

**Comment by the-simian** [comment]
@gorhom I still get
```
The following issues were found when validating your dependencies against React Native Directory:
Unsupported on New Architecture: @gorhom/bottom-sheet
```

with `expo-doctor@latest`,
do we need to update https://reactnative.directory/?search=bottom-sheet to say its compatible now?

edit: I've made a PR to update it https://github.com/react-native-community/directory/pull/1340 so it reflects your testing
