### ISSUE TITLE
Initial BottomSheet Closed State

### ISSUE THREAD

**Issue by pdesign** [gorhom/react-native-scroll-bottom-sheet#1952]
If you set index on BottomSheet to -1 to close it initially... If you only have 1 snapPoint (lets say 50%) it won't work... it does not open the bottomsheet whenever you trigger ref.current.expand

**Comment by eth0izzle** [comment]
I'm also having this issue, but with zero `snapPoints` (dynamic sizing). I'm having to use a separate state to flip the `index`
