### ISSUE TITLE
[v5] `useBottomSheetDynamicSnapPoints` is mentioned in the docs but it's undefined in the code

### ISSUE THREAD

**Issue by msuess** [gorhom/react-native-scroll-bottom-sheet#1957]
# Bug

I tried upgrading this library to the latest 5.0 alpha in order to make it work with `storybook-react-native-web`. The documention mentions a function called `useBottomSheetDynamicSnapPoints`, but it does not seem to exist anymore. What is the suggeted replacement?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.11   |
| react-native                    | 0.74.5   |
| react-native-reanimated         | 3.10.1   |
| react-native-gesture-handler    | 2.16.1   |

## Steps To Reproduce

1. Set up a project using `@gorhom/bottom-sheet` `5.0.0-alpha.11`
2. Try to call the `useBottomSheetDynamicSnapPoints` hook
3. it fails

Describe what you expected to happen:

1. it should succeed, or
2. the documentation should be updated to reflect changes in the library

## Reproducible sample code

```
import {
  useBottomSheetDynamicSnapPoints,
} from '@gorhom/bottom-sheet'

const hook  = useBottomSheetDynamicSnapPoints(initialSnapPoints)
```

**Comment by BurgerZ** [comment]
@msuess it's just documentation issue, this method was deprecated, you should use this instead:
```
<BottomSheet
    enableDynamicSizing={true}
    ....
>
```

**Comment by gorhom** [comment]
thanks @BurgerZ , correct you no longer need to use that hook with v5.

im in the progress of updating the docs for v5

**Comment by sleekLancelot** [comment]
> thanks @BurgerZ , correct you no longer need to use that hook with v5.
> 
> im in the progress of updating the docs for v5

Hi, version 5.0.1 asks to install flashList
`You need to install FlashList first, `yarn install @shopify/flash-list`, js engine: hermes`
