### ISSUE TITLE
[v4] | The getting started documentation link is incorrect?

### ISSUE THREAD

**Issue by markymc** [gorhom/react-native-scroll-bottom-sheet#1958]
# Bug

it seems to navigate to https://ui.gorhom.dev/components/bottom-sheet which shows "page not found".

## Environment info

N/A

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | x.x.x   |
| react-native                    | x.x.x   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

## Steps To Reproduce

1. Click on the link in the readme.
![Screenshot 2024-10-01 at 1 36 14 PM](https://github.com/user-attachments/assets/eb452441-dfa1-45da-a87c-d2d5d1748d87)

Describe what you expected to happen:

1. I see some documentation

## Reproducible sample code

N/A

**Comment by sszabo11** [comment]
I know it's wrong!. I think this is the link though: [https://gorhom.dev/react-native-bottom-sheet/](url)

**Comment by treygilliland** [comment]
The original link is broken and the one above is correct, but hyperlinked incorrectly. Here is the correct link:

https://gorhom.dev/react-native-bottom-sheet/

**Comment by gorhom** [comment]
https://github.com/gorhom/react-native-bottom-sheet/pull/1951 fixed the links in the readme file
