### ISSUE TITLE
hey , i get error to installation, i try to everythink but not work  npm i @gorhom/bottom-sheet npm error code ETARGET npm error notarget No matching version found for @gorhom/bottom-sheet@5. npm error notarget In most cases you or one of your dependencies are requesting npm error notarget a package version that doesn't exist.

### ISSUE THREAD

**Issue by ramprasadchauhan** [gorhom/react-native-scroll-bottom-sheet#1963]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | x.x.x   |
| react-native                    | x.x.x   |
| react-native-reanimated         | x.x.x   |
| react-native-gesture-handler    | x.x.x   |

## Steps To Reproduce

1.
2.
3. 

Describe what you expected to happen:

1.
2.

**Comment by AnilDCoder** [comment]
Did you tried installing without @5

**Comment by ramprasadchauhan** [comment]
Thank you for your email, it work fine without @5, I used @latest then it
install 4.6.4 it work fine. Thank you
