### ISSUE TITLE
[Bug]: FlashList renders all items on mount instead only visible ones

### ISSUE THREAD

**Issue by Nodonisko** [gorhom/react-native-scroll-bottom-sheet#1972]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

If you use new `BottomSheetFlashList` it will render all items when used in `BottomSheetModal` (maybe in classic `BottomSheet` too, but I did not test this variant).

### Reproduction steps

Consider following code:

```tsx
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, Button } from 'react-native';
import { BottomSheetModal, BottomSheetFlashList } from '@gorhom/bottom-sheet';

const SimpleBottomSheetFlashList = () => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // Sample data
  const data = useMemo(
    () =>
      Array(100)
        .fill(0)
        .map((_, index) => `index-${index}`),
    []
  );

  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  const renderItem = useCallback(
    ({ item }: { item: string }) => {
      console.log("rendering item", item)
      return (
        <View style={{ padding: 20, borderBottomWidth: 1, borderBottomColor: '#ccc' }}>
          <Text>{item}</Text>
        </View>
      )
    },
    []
  );

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button title="Present Modal" onPress={handlePresentModalPress} />

      <BottomSheetModal
        ref={bottomSheetModalRef}
        snapPoints={['50%', '75%']}
      >
          <BottomSheetFlashList
            data={data}
            renderItem={renderItem}
            estimatedItemSize={50}
          />
      </BottomSheetModal>
    </View>
  );
};

export default SimpleBottomSheetFlashList;
```

This will print `100` console logs when BottomSheet is displayed but that shoudn't happen because it should print only first few. I was able to hotfix it by wrapping `BottomSheetFlatList` to `View` with specified height.

```tsx
	<View style={{ height: Dimensions.get('window').height * 0.9 }}>
          <BottomSheetFlashList
            data={data}
            renderItem={renderItem}
            estimatedItemSize={50}
          />
   </View>
```

This is probably not best solution and would be nice to have it somehow integrated into library itself.

### Reproduction sample

https://snack.expo.dev/@nodonisko/bottom-sheet---issue-reproduction-template?platform=android

**Comment by gorhom** [comment]
@Nodonisko thanks for reporting this issue, and sorry for the auto close script.

Could you try setting `enableDynamicSizing ` to false, because it will try to calculate your content size and set it as a bottom sheet content height if you do not set `maxDynamicContentSize`

https://gorhom.dev/react-native-bottom-sheet/props#maxdynamiccontentsize

**Comment by Nodonisko** [comment]
Thanks for suggestion it seems that `enableDynamicSizing={false}` fixes issue, even without defined `maxDynamicContentSize` if you have some snap points. For some reason I expected `enableDynamicSizing` is `false` by default.

**Comment by gorhom** [comment]
in v4 it was set to false as to not break the current bottom sheet behaviors, but in v5 i set it to true 

https://gorhom.dev/react-native-bottom-sheet/blog/bottom-sheet-v5#migration

**Comment by Nodonisko** [comment]
Would be nice to mention in BottomSheetFlashList component that this must be to false in order for FlashList to work correctly.
