### ISSUE TITLE
[Bug]: Tried to modify key reduceMotion

### ISSUE THREAD

**Issue by Willham12** [gorhom/react-native-scroll-bottom-sheet#1974]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

warning Tried to modify key `reduceMotion`

### Reproduction steps

- just open a bottom sheet

### Reproduction sample

https://gorhom.dev/react-native-bottom-sheet/components/bottomsheetscrollview

### Relevant log output

```shell
WARN  [Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet. See 
https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable 


BottomSheet:1455:43
```

**Comment by LCseniordev** [comment]
Same happens with @gorhom/bottom-sheet v^4.6.4 after react native update to v0.75.4 and react-native-reanimated v^3.15.5

**Comment by gorhom** [comment]
i tried to repo the issue and i do not see the warning on RN CLI or Expo projects

**Comment by Willham12** [comment]
Sometimes i got no error but mostly this one:
<img src="https://github.com/user-attachments/assets/805496b4-e0c6-454a-af9f-94f368af861d" width="350">

**Comment by Nodonisko** [comment]
Same issue here, it happens randomly. My guess is that it might be happening only in dev builds because of hot reload, but not sure about that.

I will try to debug it when I encounter it again.

**Comment by thanhcuong1990** [comment]
I think it happen when setting the prop`enableDynamicSizing={false}`
In my case, to make `BottomSheetFlatList` work, I had to set `enableDynamicSizing={false}`. However, this change results in a warning.

**Comment by hieuminh1810** [comment]
I have the same issue

**Comment by fobos531** [comment]
Hello @gorhom , I submitted a PR which fixes a similar issue (not a warning, but a full-blown error) and is based on a previous solution: https://github.com/gorhom/react-native-bottom-sheet/pull/1975

> i tried to repo the issue and i do not see the warning on RN CLI or Expo projects

As I mentioned in the above PR, I was unable to repro in this repo's example app either, but I was able to repro in my own production app and confirmed that the changes made fix the issue in my case. The changes in the PR may also help with the issue described in this thread, so that's why I'm bringing it up here.

**Comment by comertcimen** [comment]
> i tried to repo the issue and i do not see the warning on RN CLI or Expo projects

Could it be related to reanimated version? I tried with reanimated v3.15.5 and get this warning but I just tried using the same version as in the example app (3.10.1) and don't get any

(Only happens if enableDynamicSizing is set to false and snapPoints used instead.)

**Comment by gorhom** [comment]
@fobos531 i think i would prefer to expose a prop on `BottomSheet` to enable/disable `reduceMotion`, that would be a proper solution

**Comment by gorhom** [comment]
by default it should respect the customer settings

**Comment by gorhom** [comment]
this issue should be resolved with the next release. 

I have implemented a fix to respect user accessibility setting by default and can be overridden by using the new prop `overrideReduceMotion` .

https://gorhom.dev/react-native-bottom-sheet/props#overridereducemotion
