### ISSUE TITLE
[Bug] [Android]: BottomSheetTextInput are hidden by keyboard when inside a BottomSheetScrollView

### ISSUE THREAD

**Issue by MagnasiePro** [gorhom/react-native-scroll-bottom-sheet#1981]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Android

### What happened?

Hello,

When placing a list of BottomSheetTextInput (or normal TextInput) components inside a BottomSheetScrollView, the last TextInput in the list gets hidden behind the keyboard when trying to interact with it.

I’m experiencing this issue in both V4 and V5.

### Reproduction steps

1.	Create a BottomSheet component and add a BottomSheetScrollView inside it.
2.	Inside the BottomSheetScrollView, render multiple components, such as BottomSheetTextInput elements.

```
Example:

{Array.from({ length: 20 }).map((_, index) => (
  <BottomSheetTextInput
    key={index}
    value={`Awesome ${index + 1} 🎉`}
  />
))}
```

3.	Attempt to scroll and use the last BottomSheetTextInput on the screen, especially with the keyboard active.

Expected Behavior:

•	The BottomSheetScrollView should be scrollable, and the last BottomSheetTextInput should remain visible and editable when the keyboard is active.

Actual Behavior:

•	The BottomSheetScrollView either shows a large grey area at the top, or the BottomSheetTextInput elements are hidden behind the keyboard when attempting to focus on the last few inputs.
	
Additional Information:

•	The behavior seems similar to the issue in #1194, but in this case, it happens inside a ScrollView.

Attempts to Resolve:

•	I’ve tried several solutions, but so far, the only outcome is displaying a large grey element over the scrollable area or the inputs getting hidden behind the keyboard.

### Reproduction sample

https://snack.expo.dev/@camille.maurel/bottom-sheet---issue-reproduction-template

**Comment by PrimulaX** [comment]
This is still issue
