### ISSUE TITLE
[Bug]: enableDynamicSizing does not work with footerComponent and content with a smaller height than the footer

### ISSUE THREAD

**Issue by Brma1048** [gorhom/react-native-scroll-bottom-sheet#1996]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

The dynamic sizing does not work correctly when the content is smaller than the footer component. The content is behind the footerComponent and gets not bumped up with enableFooterMarginAdjustment from the BottomSheetScrollView.
When i add a minHeight to my content thats bigger than the height of the footer it works, but when not the content is behind the sticky footer.

### Reproduction steps

- Add a BottomSheetModal
- Set enableDynamicSizing to true
- Add a footerComponent with `BottomSheetFooter`
- Add  `BottomSheetScrollView` as child with enableFooterMarginAdjustment
- Add some `Text` as child of the `BottomSheetScrollView` (needs to be smaller than the footerComponent)

### Reproduction sample

https://snack.expo.dev/TlvSuYD5PjmqJbeTNPJq2

**Comment by gorhom** [comment]
hi @Brma1048 , i have tested your provided snack and it seemed to be working just fine

https://github.com/user-attachments/assets/c6918ee0-c8e5-4b2d-a03f-47c499bb7a59

**Comment by Brma1048** [comment]
@gorhom I have just edit the expo go: [https://snack.expo.dev/em0pA4u9wKOPnkQqr3YU0](https://snack.expo.dev/kU26ye3pc3EztJ_ysab-_)
and in this example i get following when i don't set a height or minHeight to the inner view of the BottomSheetScrollView: 
<img src="https://github.com/user-attachments/assets/b40bc354-b233-4221-aae9-a617a23a087a" width="250" height="450">

and when i add the height to the inner view of the BottomSheetScrollView it looks like this:
<img src="https://github.com/user-attachments/assets/dc5e83b2-5baa-49ec-96e9-f1bea58d8f83" width="250" height="450">

**Comment by gorhom** [comment]
i see that you are using the alpha version of the library, could you test again on v5.0.5 @Brma1048

**Comment by Brma1048** [comment]
After upgrading to the latest version v5.0.5 it works, thanks a lot.

**Comment by ckromer2** [comment]
Hey @gorhom! I think this may have gotten reintroduced in 5.1.0

**Comment by Zakyyy** [comment]
+1
