### ISSUE TITLE
[Bug]: InputText Multiline prop enabled causes infinite re-renders of state. 

### ISSUE THREAD

**Issue by maticDevelo** [gorhom/react-native-scroll-bottom-sheet#2000]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

When typing in TextInput that has multiline={true} it start infinite loop or re-renders between current and last state. See in video. Same bug appears using BottomSheetTextInput.

https://github.com/user-attachments/assets/ba6a64dc-f6ee-4e00-829f-beec1d81c7c5

### Reproduction steps

- create bottom sheet modal
- create const [text, setText] = useState(")
- create InputText with value={text}, onChangeText={(value)=>setText(value)} and MULTILINE={true}
- open in Expo go iOS and type into TextInput

### Reproduction sample

https://snack.expo.dev/@lukadevelo/bottom-sheet-ios-multiline

**Comment by gorhom** [comment]
Hi @maticDevelo, for this issue you have two ways to fix it:

1. using `defaultValue` prop instead of `value`
2. update your `onChangeText` to wrap it with `requestAnimationFrame`

```
              onChangeText={value =>
                requestAnimationFrame(() => {
                  setText(value);
                })
              }
```

**Comment by sospedra** [comment]
I was getting mad with this! @gorhom this snippet did all the job. Maybe this should be in the `BottomSheetTextInput` docs? 🤔

**Comment by NaudyDev** [comment]
> Hi [@maticDevelo](https://github.com/maticDevelo), for this issue you have two ways to fix it:
> 
> 1. using `defaultValue` prop instead of `value`
> 2. update your `onChangeText` to wrap it with `requestAnimationFrame`
> 
> ```
>               onChangeText={value =>
>                 requestAnimationFrame(() => {
>                   setText(value);
>                 })
>               }
> ```



its not working still, 


i am using it in
RN: 0.73.5
library: 5.1.8
reanimated: 3.16.0
gesture-handler: 2.19.0



function useMaybeBottomSheetInternal(isKeyboardVisible: boolean) {
    try {
        const internal = useBottomSheetInternal()
        return isKeyboardVisible ? null : internal
    } catch {
        return null
    }
}


  const internal = useMaybeBottomSheetInternal(isKeyboardVisible)

    const handleFocus = (args: any) => {
        if (internal) {
            runOnUI(() => {
                internal.shouldHandleKeyboardEvents.value = true
            })()
        }
        onFocus && onFocus(args)
    }
    const handleBlur = (args: any) => {
        if (internal) {
            runOnUI(() => {
                internal.shouldHandleKeyboardEvents.value = false
            })()
        }

        onBlur && onBlur(args)
    }


 <TextInput
               onBlur={handleBlur}
                onFocus={handleFocus}
                label={label}
                disabled={disabled}
                value={value}
                multiline={multiline}
                mode={mode ? mode : 'outlined'}
                onChangeText={text => {
                    requestAnimationFrame(() => {
                     onChangeText(text)
                    })
                }}/>


@gorhom Please help in this.
