### ISSUE TITLE
Add Card Button Not Working in BottomSheetModal on iPhone 14 with @gorhom/bottom-sheet

### ISSUE THREAD

**Issue by mirzahassan-nc** [gorhom/react-native-scroll-bottom-sheet#2003]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

The "Add Card" button inside the BottomSheetModal using @gorhom/bottom-sheet is not responsive on an iPhone 14 running the latest iOS version. Despite the button being visible, pressing it doesn't trigger any action. No console errors or warnings are generated.

### Reproduction steps

- Implement BottomSheetModal in a React Native project using @gorhom/bottom-sheet.
- Add a button (e.g., "Add Card") inside the BottomSheetModal.
- Run the app on an iPhone 14 (or simulator) with the latest iOS version.
- Open the BottomSheetModal and attempt to press the "Add Card" button.

<img width="335" alt="YFTld6ox" src="https://github.com/user-attachments/assets/bc11dd8c-9126-4072-adab-aacba644cb0b">

### Reproduction sample

https://snack.expo.dev/@mirzahassan/26a265

**Comment by gorhom** [comment]
hi @mirzahassan-nc , i can't run the snack provided . could you please update it

**Comment by mirzahassan-nc** [comment]
@gorhom It’s a mobile application with many files, and I'm just sharing the logic behind my codebase.

**Comment by gorhom** [comment]
try to create a reproducible sample so i could investigate the issue, otherwise i won't be able to help
