### ISSUE TITLE
[Bug]: Is possible to upgrade bottom sheet to V5? and Bottomsheet doesnt Open

### ISSUE THREAD

**Issue by inthisar-hamza** [gorhom/react-native-scroll-bottom-sheet#2019]
### Version

v4 (deprecated)

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Android

### What happened?

Hey,

I need to know, is possible to upgrade the bottom sheet from V4 to V5 on React native V72 ? I know that the latest Version Reanimate only supports certain RN versions but My project depends on that RN version (V72).

`
"react-native": "^0.72.7",
"react-native-gesture-handler": "^2.14.0",
"react-native-reanimated": "^3.6.0",
`

### Reproduction steps

- Install the Latest Version of Gorhom Bottom Sheet
- Bottom sheet won't open

### Reproduction sample

https://snack.expo.dev/vzyoxpZc5yzsyBqVLeISU

**Comment by jackrdye** [comment]
Same issue

**Comment by gorhom** [comment]
it should be fixed with the latest release!

**Comment by inthisar-hamza** [comment]
It wasn't fixed yet!

**Comment by nathanfallet** [comment]
I got the issue too upgrading from v4 to v5. I fixed it by adding `enableDynamicSizing={false}`. Please add some error or warning to let people know a parameter is mandatory. We're doing fucking typescript for a reason! (even if I hate js/ts ecosystem)

**Comment by mrweiss** [comment]
still not fixed, have to use enableDynamicSizing={false}
