### ISSUE TITLE
[Bug]: The BottomSheetModal is not even opening at all

### ISSUE THREAD

**Issue by NickeNicrad** [gorhom/react-native-scroll-bottom-sheet#2020]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

After upgrading to Expo 51 with React Native 0.74.5, my BottomSheet component stopped working and it cannot even open. I've reviewed my code and checked the documentation, but I haven't found any errors or issues to indicate what's wrong.

The BottomSheet is essential to my app, and I can't downgrade since it now relies on react-native-reanimated v3, which is also a dependency for many of my other libraries used in the app.

### Reproduction steps

- I was running Expo-50
- Then I upgraded to Expo-51
- Then the BottomSheet stopped working

### Reproduction sample

https://snack.expo.dev/@gorhom/bottom-sheet---issue-reproduction-template?platform=ios

### Relevant log output

```shell
I cannot reproduce anything because it's not showing any kind of error
```

**Comment by jquezada19** [comment]
I'm also having the same issues and I'm also not getting any error messages; Please let me know if any solutions

**Comment by w8ight** [comment]
Same on version 5.0.5. Happens when there is a props combination of `enableDynamicSize` + `BottomSheetScrollView`. but it was working perfectly fine until I updated to react-native 0.76.1
For example this modal shows up:
```
<BottomSheetModal ref={modalRef} enableDynamicSizing={false} snapPoints={[300]}>
        <BottomSheetScrollView>
              <View style={{ width: '100%', height: 500, backgroundColor: 'tomato' }} />
        </BottomSheetScrollView>
 </BottomSheetModal>
```

This one does not:

```
 <BottomSheetModal ref={modalRef} enableDynamicSizing={true} snapPoints={[300]}>
        <BottomSheetScrollView>
              <View style={{ width: '100%', height: 500, backgroundColor: 'tomato' }} />
        </BottomSheetScrollView>
 </BottomSheetModal>
```

This one does not either:
```
 <BottomSheetModal ref={modalRef} enableDynamicSizing={true}>
        <BottomSheetScrollView>
              <View style={{ width: '100%', height: 500, backgroundColor: 'tomato' }} />
        </BottomSheetScrollView>
 </BottomSheetModal>
```

But if we place a BottomSheetView inside of BottomSheetScrollView, it seems to be working:
```
<BottomSheetModal ref={modalRef} enableDynamicSizing={true}>
      <BottomSheetScrollView>
        <BottomSheetView>
          <View style={{ width: '100%', height: 300, backgroundColor: 'tomato' }} />
          <View style={{ width: '100%', height: 300, backgroundColor: 'red' }} />
          <View style={{ width: '100%', height: 300, backgroundColor: 'blue' }} />
          <View style={{ width: '100%', height: 300, backgroundColor: 'aqua' }} />
        </BottomSheetView>
      </BottomSheetScrollView>
 </BottomSheetModal>
```

**Comment by skoolaidl** [comment]
Commenting to track this issue. I am having the same problem with recently upgrading to RN 0.75.4, Expo V51, and bottom sheet 5.0.5

**Comment by skoolaidl** [comment]
Coming back to say I found a workaround similar to @w8ight -- Adding in BottomSheetView OR BottomSheetScrollView seemed to fix the problem depending on the need. However, I used to have a ScrollView inside of my bottom sheet with some static content (header and footer) outside of the scroll view. It seems that either the entire contents of the sheet must be scrollable or only part -- I can't figure out a way to have the in between as it used to be.

**Comment by vorn-dev-ni** [comment]
same issue

**Comment by BRaymond69** [comment]
If you use a Tab.Navigatior browser, try adding this as props
```typescript
    <Tab.Navigator
      initialRouteName={NAVIGATOR.HOME}
      detachInactiveScreens={Platform.OS === "android" ? false : true} <--- this line
      screenOptions={() => ({
        tabBarActiveTintColor: "#144C41",
        tabBarInactiveTintColor: "#C4C4C4",
        headerShown: false,
      })}>
{...}
```

**Comment by kospaa** [comment]
Same issue, adding BottomSheetView as direct child fixes the problem but when you have a BottomsSheetScrollView or BottomSheetFlatList as child also, the modal opens up with the BottomsSheetScrollView/BottomSheetFlatList content height, ignoring the height of the content in BottomSheetView.

```
<BottomSheetView>
  <BottomSheetScrollView>
    {..content}
  </BottomSheetScrollView/>
  <View>
    {Content not taken in account when the modal shows up}
  </View/>
</BottomSheetView>
```

**Comment by kevin-presentpal** [comment]
Just an FYI, [this](https://github.com/gorhom/react-native-bottom-sheet/issues/2015) issue is already assigned to @gorhom , so hopefully we can get a fix soon! 🤞

**Comment by hraschan** [comment]
I can also confirm this issue. We are using just a normal view in the bottom sheet. This also does not work. I made a test component below. For a little more context. We are using the normal react modal when screen reader is active. Therefore the content cant be a BottomSheetView and has to be a view instead. Its crusial that normal components work in the BottomSheet.

```typescript
import { View, Text } from "react-native";
import React, { useCallback, useRef } from "react";
import { AppButton } from "./AppButton";
import { BottomSheetModal, BottomSheetView } from "@gorhom/bottom-sheet";

const TestBottomSheet = () => {
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);
  const bottomSheetModalRefView = useRef<BottomSheetModal>(null);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);
  const handlePresentModalPressView = useCallback(() => {
    bottomSheetModalRefView.current?.present();
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    console.log("handleSheetChanges", index);
  }, []);
  const handleSheetChangesView = useCallback((index: number) => {
    console.log("handleSheetChanges", index);
  }, []);
  return (
    <View>
      <AppButton title="Open Bottom Sheet" onPress={handlePresentModalPress} />
      <BottomSheetModal ref={bottomSheetModalRef} onChange={handleSheetChanges}>
        <BottomSheetView
          style={{
            flex: 1,
            padding: 24,
            justifyContent: "center",
            backgroundColor: "grey"
          }}
        >
          <Text>Awesome 🎉</Text>
        </BottomSheetView>
      </BottomSheetModal>
      <AppButton
        title="Open Bottom Sheet View"
        onPress={handlePresentModalPressView}
      />
      <BottomSheetModal
        ref={bottomSheetModalRefView}
        onChange={handleSheetChangesView}
      >
        <View
          style={{
            flex: 1,
            padding: 24,
            justifyContent: "center",
            backgroundColor: "grey"
          }}
        >
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheetModal>
    </View>
  );
};

export default TestBottomSheet;
```

**Comment by dannyhw** [comment]
What I've seen is that old bottom sheets I had needed me to set dynamicSizing to false so that they would start showing again. Not sure if this is the same thing but it sounds quite similar to what I was experiencing

**Comment by meenakshi-ss** [comment]
For me even in this case it is not opening:

RN - 74.5
Expo - 51 
 
 <BottomSheetModal
        ref={bottomSheetRef}
        enableDynamicSizing={true}
        snapPoints={[300]}
      >
        <BottomSheetScrollView>
          <BottomSheetView>
            <View
              style={{ width: "100%", height: 300, backgroundColor: "tomato" }}
            />
            <View
              style={{ width: "100%", height: 300, backgroundColor: "red" }}
            />
            <View
              style={{ width: "100%", height: 300, backgroundColor: "blue" }}
            />
            <View
              style={{ width: "100%", height: 300, backgroundColor: "aqua" }}
            />
          </BottomSheetView>
        </BottomSheetScrollView>
      </BottomSheetModal>

**Comment by houssemELbahri** [comment]
I have the same issue  with RN:75.4

**Comment by vellov** [comment]
Just had same problem, also after adding BottomSheetView BottomSheetScrollView my snapPoints got messed up, some further investigation and found that setting enableDynamicSizing={false} fixed the issue without the need to add additional wrapper views.

**Comment by fobos531** [comment]
Hello everyone, can you try the following fix to see if it fixes the issue for you?

https://github.com/gorhom/react-native-bottom-sheet/pull/2010#issuecomment-2474832680

**Comment by gorhom** [comment]
it should be fixed in the latest release , thanks for reporting

**Comment by TasseDeCafe** [comment]
> enableDynamicSizing={false}

Oh man, this saved me. Thanks!

**Comment by melihoeztuerk** [comment]
> enableDynamicSizing={false}

Thanks!

**Comment by Zakyyy** [comment]
opening this again

I can't acheive this UI
Header
Scrollable content 

when adding BottomSheetScrollView inside BottomSheetView it breaks the scrolling behavior, the scroll view keeps bouncing back to top

**Comment by vorn-dev-ni** [comment]
Hello Ahmed, Thank you for reaching out regarding the issue with
BottomSheetModal not opening. I understand how frustrating it can be to
encounter such bugs. Could you please provide more details on the steps you
are taking to reproduce this bug, or if you've already tried any specific
workarounds? This would help in understanding the context better. Thank you
for your patience and cooperation. Regards, Siv sovanpanhavorn

**Comment by Zakyyy** [comment]
Sure @vorn-dev-ni 

The BottomSheetModal is opening, and the dynamic resizing is working fine but the scrollView is not working as expected, you can't scroll basically it keeps blocking the scroll 

```JSX
<GorhomBottomSheetModal
      handleComponent={BottomSheetModalHandle}
      backdropComponent={BackdropComponent}
      ref={ref}
      enableDynamicSizing={enableDynamicSizing}
      maxDynamicContentSize={maxDynamicContentSize}
      backgroundStyle={[
        {
          borderTopLeftRadius: theme.radius.lg,
          borderTopRightRadius: theme.radius.lg,
          backgroundColor: theme.colors.background.default,
        },
        backgroundStyle,
      ]}
      {...rest}>
      <GorhomBottomSheetView>
        //Fixed header
        <Header /> 
        <GorhomBottomScrollView>
           {map} of items
        </GorhomBottomScrollView>
      </GorhomBottomSheetView>
    </GorhomBottomSheetModal>
```


https://github.com/user-attachments/assets/a0985c62-9481-4093-adb7-0b77d3ac476f

**Comment by vorn-dev-ni** [comment]
Thank you for reaching out! I appreciate you bringing this issue to my
attention. I'd like to understand more about the specific context and
implementation details of your `BottomSheetModal` to help troubleshoot
effectively. Could you please provide more information about how you are
trying to open the `BottomSheetModal` and any relevant code snippets? Thank
you and welcome! Regards, Siv sovanpanhavorn

**Comment by Zakyyy** [comment]
sure @vorn-dev-ni 
I have this generic modal hook 

```JSX
export const useModalHook = () => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const openModal = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  const closeModal = useCallback(() => {
    bottomSheetModalRef.current?.dismiss();
  }, []);

  return {
    ref: bottomSheetModalRef,
    openModal,
    closeModal,
  };
};
```


I forward the ref to the BottomSheetModal

Here is an example component I am using 

```JSX

export const FloorSelectionModal = React.forwardRef<
  BottomSheetModal,
  FloorSelectionModalProps
>((props, ref) => {
 
  return (
    <BottomSheetModal ref={ref} onDismiss={props.onDismiss}>
      <BottomSheetView>
      <View> /
        <Text type="headingMedium" color="foreground.primary">
          {t('createProperty:address.floor')}
        </Text>
      </View>
      <BottomSheetScrollView
       style={{ marginVertical: 10, paddingHorizontal: 0 }}
      >
        <YStack backgroundColor="white" borderRadius="md">
          {props.options.map(option => {
            return (
              <Row
                key={option.value}
                grouping="single"
                type="compact"
                onPress={() => setSelected(option)}>
                <Row.Center title={title} />
                {isSelected ? (
                  <Row.Right>
                    <Icon name="check" />
                  </Row.Right>
                ) : null}
              </Row>
            );
          })}
        </YStack>
      </BottomSheetScrollView>
      </BottomSheetView>
    </BottomSheetModal>
```

**Comment by vorn-dev-ni** [comment]
Thank you for reporting the issue with the BottomSheetModal not opening in
the React Native Bottom Sheet library. I understand how frustrating this
can be, and I’m here to help. If you are exploring solutions or considering
enhancements, and if Flutter or state management comes into play in your
projects, I’d be happy to share some technical insights on efficient state
management using BLoC or Riverpod. We could arrange a meeting to discuss
this in more detail. Since today is Thursday, I suggest setting up a
meeting tomorrow between 2-5 PM if that works for you. Thank you again for
reaching out. Looking forward to your response! Regards, Siv sovanpanhavorn

**Comment by vorn-dev-ni** [comment]
Hello Ahmed, Thank you for bringing this issue to attention. The problem
with the BottomSheetModal not opening could stem from lifecycle handling or
incorrect modal mounting in the React Native context. Have you checked
whether the modal's visibility state is being properly managed and if any
related animated or gesture handlers are initialized correctly? If you'd
like, we can have a detailed discussion about possible solutions and
debugging strategies. I am available to meet from 2-5 PM tomorrow if that
works for you. Thank you once again for reaching out. I look forward to
helping resolve this issue. Regards, Siv sovanpanhavorn
