### ISSUE TITLE
[Bug]: Incorrect type for `present` in Bottom Sheet Modal methods

### ISSUE THREAD

**Issue by dwnste** [gorhom/react-native-scroll-bottom-sheet#2023]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android, Web

### What happened?

According to the doc, the type should be `any`. But in [this commit](https://github.com/gorhom/react-native-bottom-sheet/commit/a93aed9904192a8508ba3d159c0ea459776415c1#diff-a593493bcf9ad0871ea3f1601097f4eba1d5af063d9b1857f675637dcd6e6d46R31) `any` was changed to `never` everywhere.

Types were not correctly resolved in the snack.

### Reproduction steps

- Pass data of any type to `present` method

### Reproduction sample

https://snack.expo.dev/@dwnste/reproducing-issue

**Comment by omkarmoghe** [comment]
Found this issue because I had the same question! I was looking at the map app example code, and was curious how this worked with type `never`? Also thought it should be `any` so that you can present the modal with arbitrary data, is there another way to achieve this? 

https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/integrations/map/MapExample.tsx#L63

**Comment by maximpostnikov** [comment]
If you don't want to wait for PR #2029, an alternative is to add a custom type to the project and use it as follows:

```typescript
type BottomSheetModalWithData<T = any> = Omit<BottomSheetModal, 'present'> & { present: (data?: T) => void }
```

```typescript
const alertModalPrimaryRef = useRef<BottomSheetModalWithData<AlertModalContentProps>>(null)

const handleUpdatePress = () => {
  alertModalPrimaryRef.current?.present({
      type: 'success',
      test: true,  // Throws error because `test` isn't defined in `AlertModalContentProps`
    })
}
```

**Comment by L-Weisz** [comment]
I also have this issue
I had created a discussion here https://github.com/gorhom/react-native-bottom-sheet/discussions/2005 
I just ignored the error for now

**Comment by gorhom** [comment]
it should be fixed in latest release , thanks to @maximpostnikov PR 🙌
