### ISSUE TITLE
[Bug]: TextInput with multiline property ignores its basic methods 

### ISSUE THREAD

**Issue by gpawlik1** [gorhom/react-native-scroll-bottom-sheet#2032]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

Using TextInput or BottomSheetTextInput with the `multiline` property don't recognise the basic text input methods, eg. `onContentSizeChange`, `onBlur`, `onFocus`, etc.

Without the `multiline` property all the methods are being called without any problem.

### Reproduction steps

- create a bottom sheet component with a TextInput inside
- set `multiline` property and any of `onContentSizeChange`, `onBlur`, `onFocus`
- observe the methods are not triggered

### Reproduction sample

https://snack.expo.dev/@gregpawlik/bottom-sheet---issue-reproduction-template

**Comment by benjaminharringtonrose** [comment]
I'm experiencing this as well on 5.0.6

**Comment by vendramini** [comment]
Any news here? It's literally not possible to use TextInput as multiline because when the keyboard appears it doesn't fit the layout correctly. @gorhom advices to workaround? Thank you :)

**Comment by luciatugui** [comment]
Can confirm it happens on 5.0.6.

**Comment by NaudyDev** [comment]
https://github.com/gorhom/react-native-bottom-sheet/issues/1999
yes this happening in 4.6.4
