### ISSUE TITLE
[Bug]: BottomSheetBackdrop `appearsOnIndex: 0` doesn't work

### ISSUE THREAD

**Issue by sgup** [gorhom/react-native-scroll-bottom-sheet#2036]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android, Web

### What happened?

Can't make BottomSheetBackdrop work for index 0. Trying to make the backdrop always present when bottom sheet is open.

### Reproduction steps

- Add this props to `BottomSheet`:
```tsx
snapPoints={["50%", "80%"]}
backdropComponent={(props) => (
  <BottomSheetBackdrop
	  {...{
		  ...props,
		  appearsOnIndex: 0,
	  }}
  />
)}
```

### Reproduction sample

https://snack.expo.dev/@shridhar/bottom-sheet---issue-reproduction-template

**Comment by sergeymild** [comment]
you have to define `disappearsOnIndex` for example `disappearsOnIndex={-1}` as well to make it working
