### ISSUE TITLE
[Bug]: iOS look up / translation services sheet not appearing above bottom sheet

### ISSUE THREAD

**Issue by radiodario** [gorhom/react-native-scroll-bottom-sheet#2050]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

When placing a text input inside a bottom sheet, selecting some text and tapping on "Look up" or "Translate" on the context menu that appears, the iOS system modal does not appear. Tapping a second time causes `NSInternalInconsistencyException Shouldn't have a lookup session` and crashes the app.

### Reproduction steps

- Add a bottom sheet to your app
- Add a text field inside the bottom sheet
- open the bottom sheet and type some text on the text field
- Select a word, and open the iOS context menu
- tap on Look up or Translate - nothing happens
- repeat the process, tap on look up again (or translate if you tapped it before) 
- App crashes

### Reproduction sample

https://snack.expo.dev/sQA2D6p5YAvexchY4g1U9

### Relevant log output

```shell
NSInternalInconsistencyException: Shouldn't have a lookup session
  CoreFoundation      0x180433c60  __exceptionPreprocess
  libobjc.A           0x197c63ee0  objc_exception_throw
  Foundation          0x181bd8c7c  -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
  UIKitCore           0x18379acf8  -[UITextInputController _define:]
  UIKitCore           0x1837aa1f4  -[UITextView _define:]
  UIKitCore           0x183499478  +[UIPasteboard _performAsDataOwnerForAction:responder:block:]
  UIKitCore           0x1831adfb4  -[UICalloutBar buttonPressed:]
  UIKitCore           0x1831acbc4  -[UICalloutBarButton fadeAndSendActionWithAuthenticationMessage:]
  Foundation          0x181ae8afc  __NSFireDelayedPerform
  CoreFoundation      0x1804481b0  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
  CoreFoundation      0x1803d1a34  __CFRunLoopDoTimer
  CoreFoundation      0x1803cc5e4  __CFRunLoopDoTimers
  CoreFoundation      0x1803ac2b0  __CFRunLoopRun
  CoreFoundation      0x1803bf170  CFRunLoopRunSpecific
  GraphicsServices    0x1a0ede984  GSEventRunModal
  UIKitCore           0x182bc1a84  -[UIApplication _run]
  UIKitCore           0x18295af74  UIApplicationMain
  REDACTED            0x10032051c  main
  0x10253c4d0  <redacted>
```

**Comment by eyupk3** [comment]
Same problem

Iphone 12 IOS 18.1

**Comment by zonemars** [comment]
same problem
iphone 15 pro IOS 18.1
iphone 12  IOS 18.1
