### ISSUE TITLE
[v4] Initial index -1 not working on Android Only

### ISSUE THREAD

**Issue by aimensasi** [gorhom/react-native-scroll-bottom-sheet#642]
# Bug

When using the `-1` index to make sure that the sheet is closed on the initial render, the sheet works fine on IOS but not on android. Instead on android, the sheet renders a small portion at the bottom of the screen, which blocks interaction with contents outside the sheet.

![WhatsApp Image 2021-09-15 at 11 08 55 PM](https://user-images.githubusercontent.com/13252355/133470057-a0a939d3-0f7a-49c3-ab5b-1c2c761cc21a.jpeg)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.63  |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

Nothing big here, a simple example. Just set the index to `-1`.

Describe what you expected to happen:

The sheet should be closed on initial render and only show when a button is pressed

## Reproducible sample code

The snack code with the issue

https://snack.expo.dev/@aimensasi/bottom-sheet-v4-reproducible-issue-template

**Comment by gorhom** [comment]
i can't reproduce the issue, could you please add more details on how to reproduce it

**Comment by aimensasi** [comment]
Sorry I think the reproducible example was missing the index


```
<BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        index={-1} <==== HERE 
        keyboardBehavior="interactive"
        handleComponent={SearchHandle}
        animateOnMount={true}
        android_keyboardInputMode="adjustPan">
        <List type="FlatList" />
      </BottomSheet>
```

I updated the sample code.

Make sure to test on android.

**Comment by gorhom** [comment]
I just tested the latest snack locally, and it works fine @aimensasi 

https://user-images.githubusercontent.com/4061838/133888279-0f036602-b372-474e-8eea-2e3ea90ac400.mov

**Comment by aimensasi** [comment]
Ok, I tested again. It seems that the issue is only in a physical device. On emulator is fine

**Comment by aimensasi** [comment]
![Uploading Screenshot_20210918-203248_Expo Go.jpg…]()

**Comment by aimensasi** [comment]
![Screenshot_20210918-203248_Expo Go](https://user-images.githubusercontent.com/13252355/133888972-bf9e4a0e-a0a7-4f2f-9d6c-7ff643eccd92.jpg)

**Comment by aimensasi** [comment]
@gorhom any updates on this or quick fix you can help with

**Comment by aditya-keri-betterhalf** [comment]
@gorhom - I am experiencing the same issue on a Physical device. Any help is greatly appreciated!

**Comment by gorhom** [comment]
Could you provide the device name and os version ?

**Comment by aditya-keri-betterhalf** [comment]
> Could you provide the device name and os version ?

Sure.

**Device name** : Oneplus 6T
**OS version** : 11

**Comment by aimensasi** [comment]
Device name: Samsung Galaxy A12
OS Version: Android 11

**Comment by gorhom** [comment]
thanks , i will try to reproduce it later today, meanwhile could you provide the statusbar height to `BottomSheet` as `topInset` https://gorhom.github.io/react-native-bottom-sheet/props#topinset

**Comment by aimensasi** [comment]
I am not sure that would help but will try and let you know.

Currently, my workaround is to do the following


```
useEffect(() => {
  	sleep(400).then(() => {
		  sheet.current?.close();
	  });
  }, []);
```
This will cause the sheet to close, but only after a certain amount of mseconds.

**Comment by gorhom** [comment]
Huh? It seems that it was caused by the parent layout got resized on the initial rendering 🧐, you could provide the the container height as the screen height, that would solve the issue for now till I investigate it

**Comment by aimensasi** [comment]
ok will try it out

**Comment by aimensasi** [comment]
https://snack.expo.dev/@aimensasi/bottom-sheet-v4-reproducible-issue-template

Did not help
