### ISSUE TITLE
[v4] animatedIndex passed to backgroundComponent is always -1

### ISSUE THREAD

**Issue by meenie** [gorhom/react-native-scroll-bottom-sheet#647]
# Bug
I'm trying to use the [exact example you provide for `backgroundComponent`](https://github.com/gorhom/react-native-bottom-sheet/blob/a0bb98a77686687e643514d131b74f421b5d4aee/example/src/components/customBackground/CustomBackground.tsx) and it is not animating. If I do a `console.log` on `animatedIndex.value` it always returns `-1`.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. I copy/pasted the full example from the examples folder into my app and tried it and got the described result above.

Describe what you expected to happen:

1. It should animate between colors and it is not.

## Reproducible sample code
https://snack.expo.dev/@codylundquist/bottomsheet-v4-reproducible-for-647

**Comment by gorhom** [comment]
could you please provide reproducible sample code ? the custom background in the example project is working properly

**Comment by meenie** [comment]
@gorhom, I was having issues with your expo snack before but it looks like it's working now.  I've updated the issue with the reproducible code, but here's the link as well: https://snack.expo.dev/@codylundquist/bottomsheet-v4-reproducible-for-647

As you can see, it should animate the background of the sheet from black to white and it is not. This is 99.99% your example code. I've just added in a console log and change the initial background color to make it more apparent that it's not working.

**Comment by gorhom** [comment]
looking at the snack, you have an issue with the interpolator input `[0, 1]`, you have 1 snap point and its position is 0, so when the bottom sheet is close the animated index will be -1.

all you have to do is to change the `[0, 1]` to `[-1, 0]` in the `CustomBackground` component 👍

**Comment by meenie** [comment]
Do you have some documentation around this?

Also, I updated the snack to what you suggested and it crashed the app with an error of "Uncaught Error: Animated node with ID 2 already exists."  I've updated the snack so you can see for yourself.

**Comment by meenie** [comment]
Playing around with the snack more and trying the custom backdrop example, it seems to be working. The error I pointed out seems to be an Expo Go issue. Reloading the app when it happens fixes it.  I'm still pretty confused how this animation stuff works. It would be great if there was some documentation around explaining it more. Thanks!
