### ISSUE TITLE
[Question] Header + ScrollView

### ISSUE THREAD

**Issue by Alaa-Ben** [gorhom/react-native-scroll-bottom-sheet#654]
Hi !
I'd like to put inside the BottomSheet, a header and a scrollView underneath. The problem is, when I do this using a View (or BottomSheetView) for the Header and a BottomSheetScrollView for ScrollView, the sheet can be dragged from the handle and from the ScrollView, but not from the Header. I'd like be able to expand/close the sheet from the header too. Is this possible ?

**Comment by ardyfeb** [comment]
@Alaa-Ben did you get solution for this?
