### ISSUE TITLE
[v4] Theming | Handle color change

### ISSUE THREAD

**Issue by imprakharshukla** [gorhom/react-native-scroll-bottom-sheet#660]
# Bug
Thank you for this library. I am trying to build my app in dark mode by default and got react-native-bottom-sheet up and running without much trouble but the thing I can't wrap my head around is **How to change the color of the bottom sheet handle on the top**.

I have looked through all the issues (opened and closed) and documentation but ended but being confused because of multiple approaches being suggested.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4  |
| react-native                    | Expo (42.0.0)   |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.2   |

## Images

![Preview](https://user-images.githubusercontent.com/39938009/134813897-da805ae5-38fa-444b-beca-02e1a8ff8d73.jpg)

**Comment by imprakharshukla** [comment]
I did follow the template as much as I could.

**Comment by gorhom** [comment]
@imprakharshukla have you looked at the examples ?
https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/CustomThemeExample.tsx

**Comment by teuscm** [comment]
Looks like you're changing backgroundColor of the `handleStyle` prop, not the actual `handleIndicatorStyle`.

**Comment by imprakharshukla** [comment]
@gorhom @teuscm I'll soon update this issue since my builds are failing due to a dependency issue with tailwind. Thank you so much for the help. I'll make sure to read the other examples as well : )

**Comment by imprakharshukla** [comment]
Thank you so much for pointing that out. It fixed it. Thank you for the great work again!

**Comment by brianwachira** [comment]
> @imprakharshukla have you looked at the examples ? https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/CustomThemeExample.tsx

The quoted link doesn't work. Incase anyone wants to find updated link, [https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/app/src/screens/advanced/CustomThemeExample.tsx](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/app/src/screens/advanced/CustomThemeExample.tsx)
