### ISSUE TITLE
[v4] Backdrop press to close and enablePanDownToClose doesn't work on physical Android devices

### ISSUE THREAD

**Issue by lukebars** [gorhom/react-native-scroll-bottom-sheet#661]
# Bug

Backdrop press to close and enablePanDownToClose doesn't work on physical Android devices. 

Children of the bottom sheet are clickable, but backdrop doesn't react to touches, as does the pan down to close.

Tested on all versions of v4. The backdrop press works on v2. 

v4 - both features do work fine on iOS. 

v2 Doesn't allow to swipe down on physical Android devices even with snapPoints set to [-250,250].

## Environment info

Xiaomi Redmi Note 8 Pro

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.0  |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open the screen with bottom sheet included
2. Open the bottom sheet
3. Press on the backdrop (nothing happens)
4. Pan down to close (nothing happens)

Describe what you expected to happen:

1. Press on backdrop should close the bottom sheet.
2. Pan down should close the bottom sheet.

## Reproducible sample code

```
import React, { useCallback } from 'react';
import { Text } from 'react-native';
import BottomSheet, { BottomSheetBackdrop } from '@gorhom/bottom-sheet';

export const RateAppSheet: React.FC =  () => {

    const renderBackdrop = useCallback(
      props => <BottomSheetBackdrop disappearsOnIndex={-1} appearsOnIndex={0} {...props} />,
      [],
    );

    return (
      <BottomSheet
        ref={ref}
        index={-1}
        enablePanDownToClose={true}
        snapPoints={[250]}
        backdropComponent={renderBackdrop}
      >
        <Text>Hello, the backdrop and pan down isn't working on physical android devices on v4</Text>
      </BottomSheet>
    );
  },
);
```

**Comment by siddharthkr** [comment]
Yes same here

**Comment by siddharthkr** [comment]
I think Library is working fine, in my case, I did not followed the complete installation steps for react-native-gesture-handler. 
Everything is working now.🙂

**Comment by lukebars** [comment]
I was missing the [GestureHandlerRootView wrapper in my App](https://docs.swmansion.com/react-native-gesture-handler/docs/#js). Works alright now.

**Comment by gregavola** [comment]
Do you have any example of this @lukebars? I am trying  to use this with a react-native-portal.

**Comment by siddharthkr** [comment]
> Do you have any example of this @lukebars? I am trying to use this with a react-native-portal.

This link might help you:

https://dev.to/jeff_codes/react-native-custom-bottombar-navigation-with-bottomsheet-1ep9

**Comment by gregavola** [comment]
@siddharth-kt Sadly, it does not. I already followed this guide. It doesn't mention anything about `GestureHandlerRootView` in the article, and it doesn't work on Android (i.e you cant swipe down to dismiss)

**Comment by lukebars** [comment]
@gregavola did you add the wrapper to App.tsx / App.js?

**Comment by projodesign** [comment]
> I was missing the [GestureHandlerRootView wrapper in my App](https://docs.swmansion.com/react-native-gesture-handler/docs/#js). Works alright now.

This solved it for me also. For others that see a broken screen - you may need to add style={{flex:1}} to the <GestureHandlerRootView /> tag.

**Comment by gregavola** [comment]
@lukebars I did

```
<PaperProvider>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <AppearanceProvider>
          <StatusBar
            barStyle={scheme === "dark" ? "light-content" : "dark-content"}
          />

          <MyTabs />
        </AppearanceProvider>
      </GestureHandlerRootView>
    </PaperProvider>
```

Is this the correct way?

**Comment by gregavola** [comment]
Then my component:

```
<Portal>
      <BottomSheet
        index={-1}
        ref={reference}
        snapPoints={snapPoints}
        enablePanDownToClose={true}
        backdropComponent={renderBackdrop}
        backgroundStyle={{ backgroundColor: colors.card }}
        handleIndicatorStyle={{ backgroundColor: colors.text }}
      >
      </BottomSheet>
    </Portal>
  
```

**Comment by gouravvaidyastar** [comment]
@gregavola - You just need to add below code in MainActivity.java , Hope it helps
  ```
@Override
   protected ReactActivityDelegate createReactActivityDelegate() {
            return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
                      return new RNGestureHandlerEnabledRootView(MainActivity.this);
                      }
    };
          }
```

**Comment by gourav108** [comment]
@gregavola  - You just need to add below code in you MainActivity.java

```
@Override
 protected ReactActivityDelegate createReactActivityDelegate() {
          return new ReactActivityDelegate(this, getMainComponentName()) {
    @Override
    protected ReactRootView createRootView() {
                    return new RNGestureHandlerEnabledRootView(MainActivity.this);
                    }
  };
 }
```
