### ISSUE TITLE
Ability to disable animations when snap points change / content height changes

### ISSUE THREAD

**Issue by tslater** [gorhom/react-native-scroll-bottom-sheet#663]
# Feature Request

The ability to disable animations when snap points change / content height changes. The bottom sheet would only move in response to gestures.

## Why it is needed

I have my bottom sheet with an offset where a user selects different options and the bottom sheet content changes. It is very jarring to have the sheet animating up and down as the user selects various options.

## Possible implementation

A simple config setting would suffice.

### Code sample

```
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        disableSnapPointAnimations={true}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;

```

**Comment by mogelbrod** [comment]
This would be a great improvement! We use BottomSheet with the layout (and thus content height) changing in response to the viewport/window size. In resizable environments such as Mac OS (catalyst) the animations triggered by changing the snapPoints seem to be queued up and run sequentially which results in a broken layout until all the animations have finished.

Would it be possible to reopen this issue?
