### ISSUE TITLE
[v4] [Need help] BottomSheet shows up for a brief second when dismissing keyboard on chat screen

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [gorhom/react-native-scroll-bottom-sheet#664]
I'm looking for a suggestion with an issue I have. I'm using the latest version (**4.1.0**) of BottomSheet in my project and we are using it in our Chat screen.

In our Chat screen, when we click on the Input box, the Keyboard opens and the entire Chat screen lifts up.
At this point, the BottomSheet (which has an `index` of -1), is right behind the keyboard. 

When we dismiss the Keyboard, the BottomSheet appears for a brief second because it was right behind it.

One solution I could think of was, providing a negative snapPoint, something like -500. This is exactly what we did with our [previous BottomSheet library](https://github.com/osdnk/react-native-reanimated-bottom-sheet) and it allowed us to provide it any negative snapPoint we want. So we didn't face this issue with that library.

When I tried to do the same with this library, it throws an error saying that negative snapPoints aren't allowed. I'm sure this isn't a bug. But I'd greatly appreciate any help or suggestion on this.

Please see the recording here : 
https://user-images.githubusercontent.com/90186621/135208450-01f89b8c-4d28-4aad-b2e4-92019fbfde98.mp4

**Comment by siddharthkr** [comment]
Any Solution ?

**Comment by gorhom** [comment]
duplicated #665

**Comment by Shipu8644** [comment]
It is not fixed for me. I am using the latest version.
