### ISSUE TITLE
[v4] [web] Use of both height and flex: 1 in BottomSheetDraggableView cause incorrect layout 

### ISSUE THREAD

**Issue by hoangvvo** [gorhom/react-native-scroll-bottom-sheet#670]
# Bug

The use of both height and flex: 1 found in `BottomSheetDraggableView`.

https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L1161-L1180
https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetDraggableView/BottomSheetDraggableView.tsx#L61-L71
https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetDraggableView/styles.ts

causes incorrect layout in certain cases. The container does not fill the whole height.

It is actually weird because I cannot reproduce it in all components, but on the one that happens it does consistently.

![Screenshot from 2021-09-29 18-55-11](https://user-images.githubusercontent.com/40987398/135263928-9d39e2ab-6b3e-4dd3-aa17-ae3a6c2451d7.png)

If I remove the flex-1 style, the layout is correct.

![Screenshot from 2021-09-29 19-01-46](https://user-images.githubusercontent.com/40987398/135264695-c05ee438-6de3-4c5b-b076-fb42a1bdd8e4.png)

After all, I don't think flex: 1 should be used together with height/width

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.1.0   |
| react-native-web                    | ^0.17.1  |
| react-native-reanimated         | ^2.3.0-beta.1   |
| react-native-gesture-handler    | ^1.10.3  |

## Steps To Reproduce

I have not yet been able to reproduce it in a minimal component. Perhaps it is css inconsistency in browser or ordering by RNW library or maybe just CSS making us struggling daily.

The above investigation may help. If it is not enough, I will try to create a minimal one later when I am more available. Sorry!

## Reproducible sample code

```tsx
const PlayerViewInner: FC = () => {
  return (
    <BottomSheetModal
      ref={bottomSheetRef}
      handleComponent={() => null}
      backgroundComponent={({ style, pointerEvents }) => (
        <PlayerViewBackground style={style} pointerEvents={pointerEvents} />
      )}
      snapPoints={["100%"]}
      stackBehavior="push"
      enableContentPanningGesture={false}
      onDismiss={onDismiss}
    >
      <SafeAreaView style={styles.root}>
        <PlayerViewHeader onDismiss={dismiss} />
        <PlayerViewInner />
      </SafeAreaView>
    </BottomSheetModal>
  );
};
```

**Comment by rchavik** [comment]
How about changing https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L1175

Does that help?

```diff
-        height: animate({
+        minHeight: animate({
```
