### ISSUE TITLE
[v4] BottomSheetModal content not visible on iOS 15

### ISSUE THREAD

**Issue by Noitham** [gorhom/react-native-scroll-bottom-sheet#673]
# Bug

Noticed that when building my app on an iOS 15 device/simulator, the content of the `BottomSheetModal` becomes not visible.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.0   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Implement `BottomSheetModal` on an iOS 15 device
2. Set `snapPoint` to > ```[`65%`]```
2. Content on the modal won't be shown.

Describe what you expected to happen:

1. Content should be shown.

## Reproducible sample code

A simple implementation of the 

`<BottomSheetModal>` component will be sufficient in order to reproduce the issue.

If running in version < iOS 15.0, it'll work and the content will be shown.
iOS 15 won't display anything.
When dragging the modal on the iOS 15 device, the content becomes shortly visible.

**Comment by Noitham** [comment]
Investigating a bit more...

Tried to replace my `BottomSheetModal` and make use of the `BottomSheet` component instead.
All good, but, wanted to hide the BottomTab whenever the `BottomSheet` is visible.

Using react-navigation v6, so setting ```tabBarStyle: { display: `none` }``` in order to achieve so.

Result? Once again, "trick" seems to work, but on iOS 15, the content on the modal is hidden for some unknown reason.

Anyone experiencing something similar?

--- 
EDIT:

Ok, more curiosities, the content on the `BottomSheetModal` or `BottomSheet` component is only hidden if the snapping point is > ` 65%`.

**Comment by Noitham** [comment]
Ok, more curiosities, the content on the `BottomSheetModal` or `BottomSheet` component is only hidden if the snapping point is > ` 65%`.

**Comment by gorhom** [comment]
i have tested on iOS 15 and it seems working fine 
![image](https://user-images.githubusercontent.com/4061838/135753882-82873ba4-87ba-4d99-939e-c5416822b410.png)

**Comment by gorhom** [comment]
and here is a modal with snap point `80%` 
![image](https://user-images.githubusercontent.com/4061838/135753974-9b143862-f4da-421d-8be1-2280272cb88f.png)

**Comment by Noitham** [comment]
> and here is a modal with snap point `80%`

Is there a BottomTabBar on the screen?
I could make a video of the error occurring on my repo, or try to reproduce it on a clean project.
What would work better for you?

**Comment by gorhom** [comment]
you should use the issue repo template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by Noitham** [comment]
@gorhom issue can be closed, I was applying a shadow style that for some reason _only_ on iOS devices (not simulators) was causing the BottomSheet content not to be visible.
All good now 🙇
