### ISSUE TITLE
[v4] | TextInput inside footerComponent , keyboard is dismiss in each keystroke

### ISSUE THREAD

**Issue by rajeshlousigam** [gorhom/react-native-scroll-bottom-sheet#677]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.0   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Put a TextInput inside BottomSheetFooter and place inside footerComponent in BottomSheetModal
2. Typing inthat TextInput cause keyboard to dismiss each time I type any keys on keyboard

Describe what you expected to happen:

1. Should be able to type properly without keyboard not closing
2.

**Comment by rajeshlousigam** [comment]
@gorhom Hi, can you please check this issue? I am unable to figure out what might cause this.

**Comment by Maximization** [comment]
@rajeshlousigam Did you find out what caused this?
