### ISSUE TITLE
[v4] Backdrop doesn't render when used single snap point

### ISSUE THREAD

**Issue by badalsaibo** [gorhom/react-native-scroll-bottom-sheet#678]
Single snap point doesn't render the backdrop. I'd only like to have a single snap point, however backdrop doesn't render with single snap point.

```js
const snapPoints = useMemo(() => ['60%'], []); // doesn't work
```
```js
const snapPoints = useMemo(() => ['10%', '60%'], []); // works
```

I added `0`, but it says snapPoints `0` is not supported, use `enablePanDownToClose` instead.

```js
...
const renderBackdrop = useCallback(
        (props) => <BottomSheetBackdrop {...props} pressBehavior="close" />,
        [],
    );
...

        <BottomSheet
            ref={bottomSheetRef}
            snapPoints={snapPoints}
            backdropComponent={renderBackdrop}
            index={-1}
            enablePanDownToClose={true}
            handleIndicatorStyle={styles.bottomSheetHandle}
            backgroundStyle={{ backgroundColor: 'red' }}
            {...otherProps}>
            {children(otherProps)}
        </BottomSheet>
```

**Comment by Mooney007** [comment]
Adding disappearsOnIndex={-1} prop on the BottomSheetBackdrop works for me. If that does not work, you could try adding appearsOnIndex={0}

**Comment by badalsaibo** [comment]
@CPhilipse Works!! Thanks a lot!

**Comment by Rc85** [comment]
I am having the same issue, but with custom backdrop and those props do not exist in `Animated.View`. What's the alternative solution for custom backdrops?

Edit - Fixed it by using 3 ranges in interpolate input and output.

```
const containerAnimatedStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      animatedIndex.value,
      [-1. -1, 0],
      [0, 0, 0.75],
      Extrapolate.CLAMP
    ),
  }));
```
