### ISSUE TITLE
[v4] Overdrag only works when dragging on the handle component, not the sheet content

### ISSUE THREAD

**Issue by davidskaarup** [gorhom/react-native-scroll-bottom-sheet#683]
# Bug
Overdrag only works when dragging on the handle component, not the sheet content

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.1   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create a bottom sheet
2. Make sure overdrag is enabled
3. Drag on the sheet handle - overdrag works
4. Drag on the sheet content - overdrag does _not_ work

Describe what you expected to happen:

1. Expected overdrag to work when dragging on sheet content

## Reproducible sample code

https://snack.expo.dev/wZpbbu9OC

**Comment by gorhom** [comment]
use `BottomSheetView` instead of `View` 👍
