### ISSUE TITLE
[v4] | [v2] Horizontal lines and icons are flickering

### ISSUE THREAD

**Issue by hiteshSavkare** [gorhom/react-native-scroll-bottom-sheet#689]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.1   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.2  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

- Explain the steps we need to take to reproduce the issue:
-->
Just created the overlay with BottomSheet sheet and loaded the another component as children inside it (code sample as bellow)

Describe what you expected to happen:

Flickering should not happen for lines and icons 

## Reproducible sample code
  <BottomSheet
      ref={bottomSheetRef}
      activeOffsetY={[-10, 10]}
      style={styles.bottomSheet}
      snapPoints={snapPoints}
      enablePanDownToClose
    >
      {children}
    </BottomSheet>
<!--

 Please use the Bottom Sheet issue snack template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template or provide a minimal runnable repro as explained above so that the bug can be tested in isolation. or use
--

https://user-images.githubusercontent.com/57394770/136665300-1bbf7024-8d44-4d9c-9675-b14b23c04b60.mov

**Comment by gorhom** [comment]
@hiteshSavkare could post the video here ?

**Comment by hiteshSavkare** [comment]
@gorhom  video uploaded for your reference 
https://user-images.githubusercontent.com/57394770/136689280-bd4f2abe-9af9-4362-930a-f1db155046ce.mov

**Comment by gorhom** [comment]
This flickering caused by the simulator scaling, it won’t happen on actual device 👍

**Comment by hiteshSavkare** [comment]
> This flickering caused by the simulator scaling, it won’t happen on actual device 👍

@gorhom this is happening on actual device too, thats a reason i created the issue

**Comment by KiranDave** [comment]
@gorhom , I am also facing the same flickering issue on actual devices.

**Comment by hiteshSavkare** [comment]
@gorhom any update on this?
due to this we are unable to publish production app
