### ISSUE TITLE
[v4]  BottomSheet goes below screen content with elevation on Android

### ISSUE THREAD

**Issue by itsramiel** [gorhom/react-native-scroll-bottom-sheet#692]
# Bug

### Issue
on **Android**
I have a screen that has a component wrapped in a View that has elevation set to 2 in order to create a shadow; however, when I add a BottomSheet component to the same screen, the component with elevation of 2 covers the modal. I am trying to set elevation 3 on the BottomSheet using the style prop, but it is not working

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.1   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Create a Simple Screen
2. Add a component and set its elevation to anything above 0
3. Add the Bottomsheet

Describe what you expected to happen:

1. I want the BottomSheet to go over the content, not under it

## Reproducible sample code

```
import React, { useMemo, useRef, useCallback } from 'react';
import { View, StyleSheet } from 'react-native';
import BottomSheet, { enableLogging } from '@gorhom/bottom-sheet';
import List from './components/List';
import SearchHandle from './components/SearchHandle';
import Button from './components/Button';

enableLogging();

const App = () => {
  // refs
  const bottomSheetRef = useRef(null);

  // variables
  const snapPoints = useMemo(() => ["80%"], []);

  // callbacks
  const handleExpandPress = useCallback(() => {
    bottomSheetRef.current?.expand();
  }, []);
  const handleCollapsePress = useCallback(() => {
    bottomSheetRef.current?.collapse();
  }, []);
  const handleClosePress = useCallback(() => {
    bottomSheetRef.current?.close();
  }, []);

  return (
    <View style={styles.container}>
    <View style={{elevation:1, backgroundColor:'blue'}}>
      <Button onPress={handleExpandPress} title="Expand" />
      <Button onPress={handleCollapsePress} title="Collapse" />
      <Button onPress={handleClosePress} title="Close" />
    </View>
      <BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        keyboardBehavior="interactive"
        handleComponent={SearchHandle}
        animateOnMount={true}
        android_keyboardInputMode="adjustPan">
        <List type="FlatList" />
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingVertical: 64,
    justifyContent: 'flex-start',
    backgroundColor: '#222',
  },
});

export default App;
```

**Comment by ardyfeb** [comment]
Same here, flatlist not rendering

**Comment by rkstar** [comment]
@ramiel1999 did you ever solve this?

**Comment by manan-schmooze** [comment]
Anyone with any solution? This is a very serious problem for our app which is in prod right now
@gorhom
