### ISSUE TITLE
[v4] Flatlist not rendering

### ISSUE THREAD

**Issue by ardyfeb** [gorhom/react-native-scroll-bottom-sheet#694]
# Bug

`BottomSheetFlatList` not rendering. Bottomsheet blocking screen seems like rendering but not content showing up
![Screenshot_2021-10-12-01-06-26-382_com.juabali.front.jpg](https://user-images.githubusercontent.com/30074366/136835330-3e41e75e-21d7-4bb9-9649-060ad06dea3f.jpg)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.66.0   |
| react-native-reanimated         | 2.3.0-beta.2   |
| react-native-gesture-handler    | ^1.10.3   |

## Reproducible sample code
```tsx
const places = [
  {
    "placeId": "ChIJuxex4kK51C8RpWsEw7WMRrg",
    "formatted": {
      "main": "Padang",
      "secondary": "Kota Padang, Sumatera Barat, Indonesia"
    },
    "match": [
      {
        "length": 6,
        "offset": 0
      }
    ]
  }
]

<BottomSheet 
    ref={innerRef}
    index={-1}
    snapPoints={animatedSnapPoints}
    contentHeight={animatedContentHeight}
    handleHeight={animatedHandleHeight}
    footerComponent={renderFooter}
    onChange={snapChangeListener}
    backdropComponent={props => <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1}/>}
    enablePanDownToClose={true}
>
     <BottomSheetFlatList 
          focusHook={useFocusEffect} 
          data={places}
          showsVerticalScrollIndicator: false,
          keyboardShouldPersistTaps: 'always',
          renderItem: renderPlaces,
          keyExtractor: item => `places-${item.placeId}`,
          keyboardDismissMode: 'on-drag',
          contentContainerStyle: {
            paddingTop: 8
         }
     />
</BottomSheet>
```

**Comment by gorhom** [comment]
could you provide a reproducible sample code using this snack https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template
