### ISSUE TITLE
[v4] BottomSheet on Android jumps between snapPoints but works fine on iOS

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [gorhom/react-native-scroll-bottom-sheet#702]
# Bug

I'm seeing an issue with the BottomSheet on android devices only and not on iOS.
Whenever there are dynamic snapPoints being provided (i.e, when snapPoints change in quick succession due to re-rendering of the component), the BottomSheet appears to be jumping in android devices. But on the iOS devices, the BottomSheet renders smoothly, without any jumps. 

I've attached the video samples below.

Correct behaviour on iOS :

https://user-images.githubusercontent.com/90186621/137656152-df636a77-e7e3-4720-b3bf-3e15635742fd.mp4

Incorrect behaviour in Android (see how it jumps):

https://user-images.githubusercontent.com/90186621/137656185-15c34d8e-a374-4fb9-8f36-54b8065f1293.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.2   |
| react-native                    | 0.63.3  |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

As you can see in the above videos, when snapPoints change in quick succession, the BottomSheet in Android jumps but works perfectly in Android.
Also, the older package : `react-native-reanimated-bottom-sheet` works fine too on Android and iOS.
So the way to reproduce this would be to generate snapPoints which quickly change after re-rendering. I've also added console logs in the first video to illustrate how the snapPoints actually change.

Describe what you expected to happen:

The behaviour on Android should be like it's on iOS, i.e, the BottomSheet shouldn't jump.

## Reproducible sample code

NA. Please take a look at the recording.

**Comment by gorhom** [comment]
@aditya-keri-betterhalf thanks for submitting this issue, but I can’t help you without a reproducible snack
