### ISSUE TITLE
[v4] Incorrect BottomSheetModal height when BottomSheetTextInput loses focus

### ISSUE THREAD

**Issue by DanielMarkiel** [gorhom/react-native-scroll-bottom-sheet#703]
# Bug

BottomSheetModal doesn't update its height when BottomSheetTextInput loses focus.
The bug occurs on both: Android and iOS.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.2   |
| react-native                    | 0.66.0   |
| react-native-reanimated         | 2.2.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

Steps for reproducing the bug in snack example:

1. Start the example on either iOS or Android
![image](https://user-images.githubusercontent.com/39768412/137782300-15de6fc5-c800-4080-aac3-c50c4b4f08ac.png)
2. Press the "Present" button to open the bottom sheet modal
![image](https://user-images.githubusercontent.com/39768412/137782405-da5a0b57-2403-4046-aa4e-f0e49fb79039.png)
3. Press the Input component (the keyboard should appear and the bottom sheet modal height should increase to move the input above it)
![image](https://user-images.githubusercontent.com/39768412/137782676-eb9427e8-9904-4e5a-8aa1-b70ebfa9e238.png)
4. Hide the keyboard e.g. press the green Done button on the keyboard
![image](https://user-images.githubusercontent.com/39768412/137783147-931a05f5-3f7b-4fa2-b0a3-43f50cdb1af1.png)

Describe what you expected to happen:

1. BottomSheetModal height returns to its original value (from before input focus)

## Reproducible sample code

https://snack.expo.dev/hD4Sgxlb54

**Comment by gorhom** [comment]
https://gorhom.github.io/react-native-bottom-sheet/props#keyboardblurbehavior

**Comment by DanielMarkiel** [comment]
Hi @gorhom,
Thanks for the link. I don't know how I've missed it... :/ 
Btw. Wouldn't be more intuitive to set the default value of `keyboardBlurBehavior` to `restore` since the default value of `keyboardBehavior` is `interactive` (that's why I thought I've found a bug)? Or maybe there's some other reason for the current default (`none`) that I'm not aware of?

**Comment by peterhuijsen** [comment]
Hey @gorhom. I was doing this exact thing, but using `keyboardBlurBehavior={'restore'}` and multiple snap points. The sheet snapped to the top snap point after restoring from input when the input started on the first snap point.

Is this expected behavior? It seems more logical to me that it restores to the snap point that was used when the input started.

Snack: https://snack.expo.dev/@yawm/bottom-sheet-v4-reproducible-issue

**Comment by YaoHuiJi** [comment]
hi, @Yawmm, I find  the same problem, do you have any new thought? It's very strange to not snap to the last position but the top position

**Comment by YaoHuiJi** [comment]
> Hey @gorhom. I was doing this exact thing, but using `keyboardBlurBehavior={'restore'}` and multiple snap points. The sheet snapped to the top snap point after restoring from input when the input started on the first snap point.
> 
> Is this expected behavior? It seems more logical to me that it restores to the snap point that was used when the input started.
> 
> Snack: https://snack.expo.dev/@yawm/bottom-sheet-v4-reproducible-issue

hi, @gorhom, could you confirm if this is a bug or a deliberate design?  I read some source code, but it was too complicated(I don't use TypeScript) for me to find relevant code
