### ISSUE TITLE
[v4] Custom Footer with Modal covering up items

### ISSUE THREAD

**Issue by DawidVanderhoven-TomTom** [gorhom/react-native-scroll-bottom-sheet#706]
# Bug

In the provided examples, the "Footer Example" there seems to be no way of rendering a solid footer without covering up list items?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.1   |
| react-native                    | 0.66.0   |
| react-native-reanimated         | 2.3.0-beta.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. make the footer a solid bar on the example 'Footer'.
2. see that only 9 items are rendered as the last is covered by the footer

Describe what you expected to happen:

1. content would render above the footer
2. It would not cover items if a solid footer is used with a list.

**Comment by siva-444** [comment]
did you have any solution for this?
use use your own style  instead of build-in footer
like 
```
<BottomSheet
//  footerComponent={renderFooter} --comment this
>
  <Block flex={1}>
    <Block flex={1}>
      <Headeer />
    </Block>
    <Block flex={8}>
      <Content />
    </Block>
    <Block flex={1}>
      <Footer />
    </Block>
  </Block>
</BottomSheet>;

```
its a temporary solution...
but footer position affected by animation some times

**Comment by alexandre-eliot** [comment]
I have been encountering the same issue. Is there a way to fix this ?

**Comment by MaxTheTurtle0** [comment]
> I have been encountering the same issue. Is there a way to fix this ?

Did you find a way to fix it?

**Comment by glopez-askit** [comment]
Same issue, is this library still maintained?
