### ISSUE TITLE
Bottom Sheet Modal is always below the content while it should on top of everything

### ISSUE THREAD

**Issue by informsharique** [gorhom/react-native-scroll-bottom-sheet#707]
# Bug

## Environment info
android 11
react native 0.65

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.x.x   |
| react-native                    | 0.65   |
| react-native-reanimated         | 2.2.x   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open a bottmsheetmodal through a button when scrolling content is present
2. it always renders below the content and not on top

Describe what you expected to happen:

1. It should open on top of everything
2.

**Comment by bryanprimus** [comment]
is there any update on this ?
