### ISSUE TITLE
[v4] | [v2] Typescript ref error when creating ref using createRef

### ISSUE THREAD

**Issue by informsharique** [gorhom/react-native-scroll-bottom-sheet#708]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.x.x   |
| react-native                    | 0.65  |
| react-native-reanimated         | 2.2.x   |
| react-native-gesture-handler    | 1.10.x   |

## Steps To Reproduce

1. create a variable outside component using createRef
2. pass bottomsheet ref as the created variable
3. typescript shows the error "Type 'RefObject<Ref<BottomSheetMethods> | undefined>' is not assignable to type 'Ref<BottomSheetMethods> | undefined'"
4. try to put createRef<RefObject<Ref<BottomSheetMethods> | undefined> and you cannot find BottomSheetMethods exported from the libraray

## Expected Behaviour

1. Library should export BottomSheetMethods to create a ref to be able use it as a reusable component
2. Also closing the modal from different component uses createRef.

## Reproducible sample code
```
export const bottomSheetRef = createRef<React.Ref<BottomSheetMethods> | undefined>();

<BottomSheet
	ref={bottomSheetRef}
	index={-1}
	snapPoints={snapPoints}
	enablePanDownToClose
>
```

**Comment by gchiacchio** [comment]
Issue is still happening... please reopen

**Comment by akinyele** [comment]
still experiencing this bug as well

**Comment by adibkadir** [comment]
I'm getting this error 
`Error: Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref`

When trying to run the app due to this. Is anybody using this component on expo react native app?

**Comment by mansiRadicalRack** [comment]
same error coming with sample code

**Comment by marcshilling** [comment]
Agree `BottomSheetMethods` should be exposed
