### ISSUE TITLE
[v4] BottomSheet is not closed using bottomsheettextinput after keyboard dismissed

### ISSUE THREAD

**Issue by AlexSirenko** [gorhom/react-native-scroll-bottom-sheet#711]
# Bug

    <BottomSheet
      ref={sheetRef}
      index={-1}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}
      backgroundStyle={{
        backgroundColor: colors.bgLayout1,
      }}
      enablePanDownToClose
      onClose={handleOnClose}
    >
<BottomSheetTextInput />
  </BottomSheet>

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.0  |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Add the BottomSheetTextInput inside bottomSheet component.
2. Press on BottomSheet that trigger keyboard opening and bottomSheet opens (becomes bigger)
3. Press done on the keyboard that trigger keyboard dismissing.
4. Bottom sheet not comes to initial position.

Describe what you expected to happen:

1. Bottom sheets comes to initial position

Also the code-snippet from the docs is not working:
https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling

## Reproducible sample code

This template has the same behavior -
https://snack.expo.dev/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by AlexSirenko** [comment]
@gorhom any thoughts? Seems the problem is in the const { shouldHandleKeyboardEvents } = useBottomSheetInternal();
Let me know if you need any help :)

**Comment by AlexSirenko** [comment]
UPDATE: 
Just use keyboard props, and all will work ;)

**Comment by rochajulian** [comment]
> UPDATE: Just use keyboard props, and all will work ;)

how did you fix???

**Comment by metuuu** [comment]
```
<BottomSheetModal
  keyboardBlurBehavior="restore"
```
