### ISSUE TITLE
[v4] BottomSheetModal  restores when keyboard disappears

### ISSUE THREAD

**Issue by davidnum** [gorhom/react-native-scroll-bottom-sheet#715]
# Bug

BottomSheetModal restores when keyboard dismissing and other BottomSheetModal appears (maybe race)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.66.1   |
| react-native-reanimated         | 1.10.3   |
| react-native-gesture-handler    | 2.2.3  |

## Steps To Reproduce

1. Render two BottomSheetModal on the screen
2. First should be with BottomSheetTextInput
3. Present first BottomSheetModal
4. Press on BottomSheetTextInput (keyboard appears)
5. Present second BottomSheetModal
<img src="https://github.com/davidnum/rn-bottomsheet-keyboard-issue/raw/master/gif/showcase.gif" width="300"> 

Describe what you expected to happen:

1. First BottomSheetModal should dismiss

## Reproducible sample code

https://github.com/davidnum/rn-bottomsheet-keyboard-issue

**Comment by davidnum** [comment]
Any news?

**Comment by swikars1** [comment]
https://github.com/gorhom/react-native-bottom-sheet/issues/761 check here

**Comment by swikars1** [comment]
> Any news?

https://github.com/gorhom/react-native-bottom-sheet/issues/761 check here

**Comment by davidnum** [comment]
> > Any news?
> 
> #761 check here

It's not android issue.
