### ISSUE TITLE
[v4] Scrolling within a BottomSheetScrollable causes the card to become unresponsive

### ISSUE THREAD

**Issue by bailycase99** [gorhom/react-native-scroll-bottom-sheet#717]
# Bug

If I have a ScrollableView within the BottomSheet (ex: BottomSheetFlatList) it causes the card to become unresponsive and only allows me to scroll the card if I scroll within the FlatList, sometimes when I scroll to the top of the card, it allows me to scroll the card normally again.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create a BottomSheet or BottomSheetModal
2. Put a BottomSheetFlatList inside of it
3. Scroll within the FlatList
4. Attempt to interact with the BottomSheet outside of the FlatList

Describe what you expected to happen:

1. I can interact with the card outside of the scroll view

## Reproducible sample code

https://snack.expo.dev/HKwm5aK1K

**Comment by bailycase99** [comment]
@gorhom I'd like to know if this is expected behavior.

**Comment by strayiker** [comment]
There is a slightly modified snack to demonstrate the related issue. If I remove the scroll view in the middle of its scroll position, I lose control of the bottom sheet altogether.
https://snack.expo.dev/@sadbox/bottom-sheet-v4-reproducible-issue-template
