### ISSUE TITLE
[v4] [IOS] [Device]  BottomSheetFooter bottomInset is not respected when keyboard open 

### ISSUE THREAD

**Issue by aimensasi** [gorhom/react-native-scroll-bottom-sheet#718]
# Bug

Not a major issue, but the `bottomInset` of the `BottomSheetFooter` is not respected when the keyboard is shown. is this on purpose or is it a bug?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3  |
| react-native                    | 0.65.1  |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

Open the sample code below, expand the sheet and then focus on the input. You will notice that the footer items are right above the keyboard with no margin.

Note, You might need to remove the margin from the buttons inside the footer and you will notice that the inset is not working.

## Reproducible sample code

https://snack.expo.dev/@aimensasi/bottom-sheet-v4-reproducible-issue-template

**Comment by vinesh4Real** [comment]
@aimensasi hey buddy. Did you find a fix for this?
