### ISSUE TITLE
[v4] BottomSheetTextInput not handling keyboard properly when content exceeds snap point

### ISSUE THREAD

**Issue by teuscm** [gorhom/react-native-scroll-bottom-sheet#723]
# Bug

Hello. I'm not sure this is a bug or a feature for that is currently not implemented, but it's worth a shot:

The Keyboard Handling on Bottom Sheet or Bottom Sheet Modal does not seem to be working if the content is larger than the maximum snap point (or dynamic snap points), thus obstructing the BottomSheetTextInput visibility when the Keyboard is shown.

![image](https://user-images.githubusercontent.com/30584910/138899006-8229ee79-fc5e-49de-b816-9b65d638960d.png)
As shown in the video below, having a small number of inputs (making the content smaller than the maximum snap point) does the job on keyboard handling, but as soon as I uncomment the rest of the inputs it seems that the onLayout cannot calculate the view's height properly.

I've tested this by modifying the repo's example file, so this should mean that no other libs in my larger app should be causing the problem.

Am I missing something?

https://user-images.githubusercontent.com/30584910/138902698-c677bffc-ef53-4282-b324-e0b27697dae4.mov

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.3.0-beta.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Clone this repository and modify the keyboard handling example code to have dynamic snap points (not needed but I use it in my main app)
2. Remove the contact list component and add enough BottomSheetInputs to exceed the maximum snap point height.
3. Interact with the inputs.

Describe what you expected to happen:

1. The BottomSheetView or BottomSheetScrollView should offset the content or even scroll to the focused input, making it visible even when the Keyboard is active.

## Reproducible sample code

https://snack.expo.dev/quurG9Utgn

**Comment by MarcoCuel** [comment]
Thank god someone’s aknowledged that! I’m facing the same problems on my app.

**Comment by SamKissee** [comment]
I had this issue, I am getting around this temporarily but using [patch-package](https://github.com/ds300/patch-package#readme) to switch from using RNs ScrollView to KeyboardAwareScrollView from [this library](https://github.com/APSL/react-native-keyboard-aware-scroll-view)

Doing this in this [file](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/BottomSheetScrollView.tsx)

**Comment by A01123748** [comment]
@SamKissee nice approach. Do you happen to test it on Android?

**Comment by A01123748** [comment]
> I had this issue, I am getting around this temporarily but using [patch-package](https://github.com/ds300/patch-package#readme) to switch from using RNs ScrollView to KeyboardAwareScrollView from [this library](https://github.com/APSL/react-native-keyboard-aware-scroll-view)
> 
> Doing this in this [file](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/BottomSheetScrollView.tsx)

@SamKissee nice approach. Do you happen to test it on Android?

**Comment by teuscm** [comment]
Any updates?

**Comment by filippobarcellos** [comment]
Did you find a solution? I'm having the same problem.

**Comment by exzos28** [comment]
I'm having the same problem.

**Comment by Julienblc** [comment]
Same problem here, any solution ?

**Comment by exzos28** [comment]
> Same problem here, any solution ?

You can create your component based on [this file](
https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/BottomSheetScrollView.tsx)
Only use [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view) instead of RNScrollView

**Comment by slutske22** [comment]
Having similar (possibly exactly the same) problem here: [Keyboard should not expand BottomSheet beyond a maximum height](https://github.com/gorhom/react-native-bottom-sheet/issues/1430)

**Comment by Viceclaw13** [comment]
> > Same problem here, any solution ?
> 
> You can create your component based on [this file](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/BottomSheetScrollView.tsx) Only use [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view) instead of RNScrollView

This is not usable for android
