### ISSUE TITLE
[v4] | [v2]  TypeError: undefined is not an object (evaluating 'worklet.__workletHash.toString')

### ISSUE THREAD

**Issue by caopeng000** [gorhom/react-native-scroll-bottom-sheet#732]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.64.2   |
| react-native-reanimated         |^2.3.0-beta.2   |
| react-native-gesture-handler    | ^1.10.3 |

## Steps To Reproduce

1.
2.
3. 

Describe what you expected to happen:

1.
2.

**Comment by caopeng000** [comment]
i use V8 engine

**Comment by caopeng000** [comment]
` ERROR  TypeError: undefined is not an object (evaluating 'worklet.__workletHash.toString')

This error is located at:
    in BottomSheetGestureHandlersProvider (at BottomSheet.tsx:1552)
    in BottomSheet (created by BottomSheet)
    in RCTView (at View.js:34)
    in View (at BasicExamples.tsx:90)
    in Unknown (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:280)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:278)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:557)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:536)
    in PanGestureHandler (at GestureHandlerNative.tsx:14)
    in PanGestureHandler (at Card.tsx:530)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
`

**Comment by tylerpope** [comment]
@caopeng000 were you able to resolve this? I'm having the same issue.

**Comment by guifacci** [comment]
Same issue, can't get it to convert to string.

**Comment by baronha** [comment]
same issue. How to fix this ?

**Comment by gorhom** [comment]
This is a reanimated installation issue, please follow their instructions and try again!

**Comment by ChronSyn** [comment]
**Please see update at bottom of this comment dated 17th August 2022**

This may not actually be a reanimated installation issue. Let me start with the solution:

 - If you're using `@apollo/client`, you likely followed the instructions at https://stackoverflow.com/a/70076278 - essentially modifying your `metro.config.js` file to allow the `cjs` modules it uses to work with RN. **If you've modified your metro config file for any reason, this may be why - the fix is not necessarily due to Apollo specifically**
 - This appears to interfere with a number of RN packages which rely on reanimated, and causes the exact same error as above
  - The solution to this is: `yarn add @apollo/client@3.4.16 graphql@15.7.2`

If you use Apollo tooling to generate Typescript types, you can skip adding the `graphql` package (as this may also cause errors since `apollo/client` already ships with it's own GQL library).

Though this is a slightly lower version than the latest, it allows you to remove `metro.config.js` file entirely while still maintaining compatibility with RN

**How did I discover this**

I spent the past few hours trying to figure out why I couldn't use any packages which relied on reanimated. I tried downgrading to SDK43, using older versions of libraries which I thought were related, I even renewed my long-retired Apple developer account subscription in order to do an EAS build to ensure it wasn't an issue with Expo Go (sure, I could run on a sim, but I was looking to reactivate it soon anyway). I could not replicate this error on a minimal repro (https://snack.expo.dev/@chronsyn/215b75), even after downloading the zip and running it on-device.

I then copied across my files, including my `src` and `assets` folder, as well as my `tsconfig`, `app.json`, `package.json` and all other files needed to get the project running. I forgot to copy my metro config across, and the app complained. I moved that across, and while the app would no longer complain about apollo, it would throw the error mentioned in the original post.

I then went back to that same StackOverflow answer linked above, and looked through other solutions. In there was the suggestion to use slightly earlier versions of the library. Installing these and removing my metro config allowed the app to start correctly. Sure enough, when I got to the screen where I'd added the bottom-sheet, it was showing up and there were no errors.

@gorhom - I'm not sure if this is something to consider, but perhaps adding some of these details to the installation readme would help people who are experiencing issues, as the error doesn't immediately point towards metro config being a problem and many people would overlook it as the cause

**EDIT - 17 August 2022**: To clarify, the issue is **NOT** Apollo specifically. It is caused by metro config. Please stop saying "I'm not using Apollo and it still doesn't work" if you still have a metro config file which is not correctly configured or compatible with reanimated 2.

**Comment by Jrodseth** [comment]
@ChronSyn I ran into this problem running the latest apollo client with the `cjs` workaround. I can confirm this resolved the issue for me. Great job.

**Comment by IIsijola** [comment]
Thanks @ChronSyn  you saved my so much time debugging. It's a shame that apollo/clients recommended solution breaks so many other packages dependent on reanimated.

**Comment by gh0st-work** [comment]
Got the same issue in react-native web, but I didn't have Apollo installed. The problem was with expo 44 and reanimated. Solved by downgrading to expo 43 and reanimated 2.2.3.

Snack:
https://snack.expo.dev/@gh0st_work/bottomsheet-reanimated-error

**Comment by maratfakhreev** [comment]
Still have the same issue in almost clean react native app (don't have apollo installed and don't use typescript). 

If I use 2.2.3 version I get another problem related to installation process, so this solution doesn't work for me as well:
```
​Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

This error is located at:
    in BottomSheet (created by BottomSheet)
    in RCTView (at View.js:32)
    in View (at App.js:151)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at App.js:149)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MayakMobile(RootComponent) (at renderApplication.js:60)
```

If I use 2.3.x I get problem related to `toString`:
```
TypeError: Cannot read properties of undefined (reading 'toString')

This error is located at:
    in BottomSheetGestureHandlersProvider (at BottomSheet.tsx:1553)
    in BottomSheet (created by BottomSheet)
    in RCTView (at View.js:32)
    in View (at App.js:151)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at App.js:149)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MayakMobile(RootComponent) (at renderApplication.js:60)
```

My configuration is:
```
"dependencies": {
    "@gorhom/bottom-sheet": "^4",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-reanimated": "^2.3.1",
    "react-native-webview": "^11.15.0"
  },
```
Additionally for `react-native-reanimated` I've added plugin to `babel.config.js`:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```
And for `react-native-gesture-handler` I've added `import 'react-native-gesture-handler';`
```
import 'react-native-gesture-handler';
import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);
```
So I've now idea what to do. Different combination of versions didn't bring any success

**Comment by dreamer01** [comment]
@maratfakhreev were you able to find any solution?

**Comment by getinnocuous** [comment]
@ChronSyn that is some legendary debugging! I recently updated Apollo and didn't even think it could be that causing the problem. Saved me a massive headache,  cheers!

**Comment by m0nk-lee** [comment]
> This may not actually be a reanimated installation issue. Let me start with the solution:
> 
> * If you're using `@apollo/client`, you likely followed the instructions at https://stackoverflow.com/a/70076278 - essentially modifying your `metro.config.js` file to allow the `cjs` modules it uses to work with RN
> * This appears to interfere with a number of RN packages which rely on reanimated, and causes the exact same error as above
> * The solution to this is: `yarn add @apollo/client@3.4.16 graphql@15.7.2`
> 
> If you use Apollo tooling to generate Typescript types, you can skip adding the `graphql` package (as this may also cause errors since `apollo/client` already ships with it's own GQL library).
> 
> Though this is a slightly lower version than the latest, it allows you to remove `metro.config.js` file entirely while still maintaining compatibility with RN
> 
> **How did I discover this**
> 
> I spent the past few hours trying to figure out why I couldn't use any packages which relied on reanimated. I tried downgrading to SDK43, using older versions of libraries which I thought were related, I even renewed my long-retired Apple developer account subscription in order to do an EAS build to ensure it wasn't an issue with Expo Go (sure, I could run on a sim, but I was looking to reactivate it soon anyway). I could not replicate this error on a minimal repro (https://snack.expo.dev/@chronsyn/215b75), even after downloading the zip and running it on-device.
> 
> I then copied across my files, including my `src` and `assets` folder, as well as my `tsconfig`, `app.json`, `package.json` and all other files needed to get the project running. I forgot to copy my metro config across, and the app complained. I moved that across, and while the app would no longer complain about apollo, it would throw the error mentioned in the original post.
> 
> I then went back to that same StackOverflow answer linked above, and looked through other solutions. In there was the suggestion to use slightly earlier versions of the library. Installing these and removing my metro config allowed the app to start correctly. Sure enough, when I got to the screen where I'd added the bottom-sheet, it was showing up and there were no errors.
> 
> @gorhom - I'm not sure if this is something to consider, but perhaps adding some of these details to the installation readme would help people who are experiencing issues, as the error doesn't immediately point towards metro config being a problem and many people would overlook it as the cause


I didn't change the version and modified the 'metro.config.js' file to the contents of [this link](https://stackoverflow.com/a/70174285), so it worked well.

Thanks to you, the problem was solved well.

**Comment by jahglow** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/3049#issuecomment-1117281665 as your last resort (compiler overhead is minimal)

**Comment by twilczek** [comment]
@ChronSyn thanks a lot man, I couldn't figure it out myself. I have been banging my head over it for the last couple of days 😒

**Comment by hbriese** [comment]
This issue also arises when enabling metro's exotic mode, as it has cjs support

**Comment by magrinj** [comment]
> > This may not actually be a reanimated installation issue. Let me start with the solution:
> > 
> > * If you're using `@apollo/client`, you likely followed the instructions at https://stackoverflow.com/a/70076278 - essentially modifying your `metro.config.js` file to allow the `cjs` modules it uses to work with RN
> > * This appears to interfere with a number of RN packages which rely on reanimated, and causes the exact same error as above
> > * The solution to this is: `yarn add @apollo/client@3.4.16 graphql@15.7.2`
> > 
> > If you use Apollo tooling to generate Typescript types, you can skip adding the `graphql` package (as this may also cause errors since `apollo/client` already ships with it's own GQL library).
> > Though this is a slightly lower version than the latest, it allows you to remove `metro.config.js` file entirely while still maintaining compatibility with RN
> > **How did I discover this**
> > I spent the past few hours trying to figure out why I couldn't use any packages which relied on reanimated. I tried downgrading to SDK43, using older versions of libraries which I thought were related, I even renewed my long-retired Apple developer account subscription in order to do an EAS build to ensure it wasn't an issue with Expo Go (sure, I could run on a sim, but I was looking to reactivate it soon anyway). I could not replicate this error on a minimal repro (https://snack.expo.dev/@chronsyn/215b75), even after downloading the zip and running it on-device.
> > I then copied across my files, including my `src` and `assets` folder, as well as my `tsconfig`, `app.json`, `package.json` and all other files needed to get the project running. I forgot to copy my metro config across, and the app complained. I moved that across, and while the app would no longer complain about apollo, it would throw the error mentioned in the original post.
> > I then went back to that same StackOverflow answer linked above, and looked through other solutions. In there was the suggestion to use slightly earlier versions of the library. Installing these and removing my metro config allowed the app to start correctly. Sure enough, when I got to the screen where I'd added the bottom-sheet, it was showing up and there were no errors.
> > @gorhom - I'm not sure if this is something to consider, but perhaps adding some of these details to the installation readme would help people who are experiencing issues, as the error doesn't immediately point towards metro config being a problem and many people would overlook it as the cause
> 
> I didn't change the version and modified the 'metro.config.js' file to the contents of [this link](https://stackoverflow.com/a/70174285), so it worked well.
> 
> Thanks to you, the problem was solved well.

@ChronSyn Thanks !

@monk-lee Seems that it's just working when you remove spread of `defaultResolver`, nothing else to change.

```javascript
const { getDefaultConfig } = require("metro-config");
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
exports.resolver = {
  // ...defaultResolver, // --> Working when this line is commented
  sourceExts: [
    ...defaultResolver.sourceExts,
    "cjs",
  ],
};
```

Don't really know if it's going to create some side-effect, as we are omitting the default resolver.

**Comment by Sahejmaharjan1** [comment]
I'm facing the same issue.. I've tried all above examples still didn't work. I'm not using @apollo/client package. Here's my package.json
```
    "react-native": "0.68.2",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-reanimated": "^2.8.0",    
```
added ``'react-native-reanimated/plugin'`` in babel.config.js
Here's my metro.config.js
```
const { getDefaultConfig } = require('metro-config');




module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      // babelTransformerPath required for using absoulte paths in imports
      babelTransformerPath: require.resolve("./customTransformer.js"),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: true,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg', 'cjs'],
    },
  }
});
```
Any help would be appreciated. Thanks.

**Comment by ReactNativ** [comment]
Add Reanimated's babel plugin to your babel.config.js:

```javascript
  module.exports = {
      ...
      plugins: [
          ...
          'react-native-reanimated/plugin',
      ],
  };
```

- yarn start --reset-cache

**Comment by MaganAnkur** [comment]
Had same issue, add Reanimated's babel plugin and **dont forget** to restart metro using **npm start --reset-cache**

**Comment by WoyongE** [comment]
This combination of versions worked for me. More [here](https://github.com/software-mansion-labs/reanimated-2-playground/blob/master/package.json).

```
  "react": "18.0.0",
  "react-native": "0.69.1",
  "react-native-gesture-handler": "^1.9.0",
  "react-native-reanimated": "2.3.1",
  "@gorhom/bottom-sheet": "^4.4.2",
```

**Comment by HERRKIN** [comment]
I have this problem, I just installed the module, follow the tutorials and still I have the same problem, I don't have apollo installed.

**Comment by gaelhelle** [comment]
Same problem :(
 
 ```
   "@gorhom/bottom-sheet": "^4.4.3",
   "react-native": "0.69.5",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-reanimated": "^2.9.1",   
```

metro.config.js : 
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    sourceExts: ["jsx", "js", "ts", "tsx", "cjs"],
  },
};

```

babel.config.js: 
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["nativewind/babel", "react-native-reanimated/plugin"],
    env: {
      production: {
        plugins: ["react-native-paper/babel"],
      },
    },
  };
};

```

**Comment by adingeist** [comment]
> Add Reanimated's babel plugin to your babel.config.js:
> 
> ```js
>   module.exports = {
>       ...
>       plugins: [
>           ...
>           'react-native-reanimated/plugin',
>       ],
>   };
> ```
> 
> * yarn start --reset-cache

If you use expo:
npx expo start --clear
