### ISSUE TITLE
Shadow not working on Android

### ISSUE THREAD

**Issue by tungduonghgg123** [gorhom/react-native-scroll-bottom-sheet#734]
# Bug

Trying to follow guide on adding shadow to BottomSheetModal, only iOS seems to work.
![IMG_B258DB887710-1](https://user-images.githubusercontent.com/32666311/140602336-8b7efd7b-bd96-475f-8bd6-3f0da9cca9ab.jpeg)
![Screen Shot 2021-11-06 at 14 49 42](https://user-images.githubusercontent.com/32666311/140602339-37a8f538-3b6e-42e5-a9fe-447a31cc1b8c.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.3   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Just use the code in this link: [https://gorhom.github.io/react-native-bottom-sheet/modal/usage](https://gorhom.github.io/react-native-bottom-sheet/modal/usage )
2. Add the style to BottomSheetModal
```
            shadowColor: 'pink',
            shadowOffset: {
              width: 0,
              height: 12,
            },
            shadowOpacity: 0.58,
            shadowRadius: 16.0,

            elevation: 24,
```
3. See the result

Describe what you expected to happen:

1. Android should show the shadow correctly

## Reproducible sample code

[Snack link](https://snack.expo.dev/@tungduonghgg123/bottom-sheet-v4-reproducible-issue-template
)

**Comment by eddievlagea** [comment]
I'm having the same issue, I follow the guide but the shadow does not appear on Android.

**Comment by GauthierEmilien** [comment]
Hello !
I have the exact same problem too !

**Comment by fiznool** [comment]
The `elevation` property on Android is very inflexible, and so I opted for a custom handle component with a shadow applied using [react-native-shadow-2](https://github.com/SrBrahma/react-native-shadow-2).

``` ts
// SheetHandle.tsx

import React, { FC } from 'react';
import { StyleSheet, View } from 'react-native';
import { Shadow } from 'react-native-shadow-2';

const RADIUS = 24;

const SheetHandle: FC = () => {
  return (
    <Shadow
      sides={['top']}
      corners={['topLeft', 'topRight']}
      radius={RADIUS}
      viewStyle={styles.shadowContainer}>
      <View style={styles.handleContainer}>
        <View style={styles.handle} />
      </View>
    </Shadow>
  );
};

const styles = StyleSheet.create({
  shadowContainer: {
    width: '100%',
  },
  handleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderTopLeftRadius: RADIUS,
    borderTopRightRadius: RADIUS,
  },
  handle: {
    width: 30,
    height: 4,
    backgroundColor: 'gray',
    borderRadius: 4,
  },
});

export default SheetHandle;
```

The `SheetHandle` component is then applied to the `BottomSheet` via the `handleComponent` prop:

``` ts
// App.tsx

import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

import SheetHandle from './SheetHandle';

const App = () => {
  return (
    <View style={styles.container}>
      <BottomSheet
        index={1}
        snapPoints={['25%', '50%']}
        handleComponent={SheetHandle}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'white',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
```

The results:

| iOS | Android |
| - | - |
| ![ios](https://user-images.githubusercontent.com/820863/141381013-4def9824-5070-439d-abf0-0571ea35bc9b.jpeg) | ![android](https://user-images.githubusercontent.com/820863/141381033-b5c376da-d9c2-4611-bc57-bb22d2e6c93a.png) |

**Comment by nkemcels** [comment]
thanks @fiznool

**Comment by tchedev** [comment]
I solved the issue by adding a background colour

```
style={{
        backgroundColor: 'white',  // <==== HERE
        borderRadius: 24,
        shadowColor: '#000000',
        shadowOffset: {
          width: 0,
          height: 8,
        },
        shadowOpacity: 0.1,
        shadowRadius: 24,
        elevation: 10,
      }}
```

**Comment by Irian-Adappty** [comment]
> THANK YOU! I was getting mad a so simple thing wasn't working. And [in the documentation](https://gorhom.github.io/react-native-bottom-sheet/adding-shadow) this is not mentioned.

**Comment by Irian-Adappty** [comment]
> I solved the issue by adding a background colour
> 
> ```
> style={{
>         backgroundColor: 'white',  // <==== HERE
>         borderRadius: 24,
>         shadowColor: '#000000',
>         shadowOffset: {
>           width: 0,
>           height: 8,
>         },
>         shadowOpacity: 0.1,
>         shadowRadius: 24,
>         elevation: 10,
>       }}
> ```

THANK YOU! I was getting mad a so simple thing wasn't working. And [in the documentation](https://gorhom.github.io/react-native-bottom-sheet/adding-shadow) this is not mentioned.

However that removes my rounded corners, to fix it I changed it to ` backgroundColor: 'rgba(255, 255, 255,0)' ` ('transparent' was inconsistent, sometimes the shadow would appear and sometimes wouldn't)

**Comment by faerylay** [comment]
> I solved the issue by adding a background colour
> 
> ```
> style={{
>         backgroundColor: 'white',  // <==== HERE
>         borderRadius: 24,
>         shadowColor: '#000000',
>         shadowOffset: {
>           width: 0,
>           height: 8,
>         },
>         shadowOpacity: 0.1,
>         shadowRadius: 24,
>         elevation: 10,
>       }}
> ```

thannks bro i forget to add background color

**Comment by byteab** [comment]
I always use this website to generate consistent looking shadows
https://ethercreative.github.io/react-native-shadow-generator/

**Comment by arnabdotpy** [comment]
> I solved the issue by adding a background colour
> 
> ```
> style={{
>         backgroundColor: 'white',  // <==== HERE
>         borderRadius: 24,
>         shadowColor: '#000000',
>         shadowOffset: {
>           width: 0,
>           height: 8,
>         },
>         shadowOpacity: 0.1,
>         shadowRadius: 24,
>         elevation: 10,
>       }}
> ```

I guess this is a good workaround to get the job done, but why do we need to do this shit.
