### ISSUE TITLE
[v4] BottomSheetTextInput border bottom not visible on focus on iOS

### ISSUE THREAD

**Issue by AnneKlapwijk** [gorhom/react-native-scroll-bottom-sheet#736]
# Bug

When focussing on an input it moves out of the way of the virtual keyboard so that the input is still visible (not hidden under the keyboard).

https://user-images.githubusercontent.com/3767167/140892510-b9362191-ea7e-4e78-8a37-0544b60939b6.mov

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.1.3   |
| react-native                    | 0.66.1   |
| react-native-reanimated         | ~2.2.0   |
| react-native-gesture-handler    | ~1.10.2   |

## Steps To Reproduce

1. Run the [snack](https://snack.expo.dev/@enrisematchminds/bottomsheettextinput-focus-border) on iOS
2. Press on an input at the bottom of the viewport
3. You should see the input moving out of the way of the virtual keyboard
4. The input is visible, but without the bottom border

Describe what you expected to happen:

1. To see the input including the bottom border

## Reproducible sample code

https://snack.expo.dev/@enrisematchminds/bottomsheettextinput-focus-border

**Comment by teuscm** [comment]
Perhaps related to #723 ?

**Comment by AnneKlapwijk** [comment]
> Perhaps related to #723 ?

Looks like a different issue to me. It does offset the content/scroll to the focused input (see screen recording/Snack), but it looks like the border is not taken into account.
