### ISSUE TITLE
[v4] `BottomSheet` doesn't accept `forwardRef` with TypeScript

### ISSUE THREAD

**Issue by noghartt** [gorhom/react-native-scroll-bottom-sheet#742]
# Bug

If we render `BottomSheet` inside a `forwardRef` component and pass the respective ref to the `BottomSheet`'s ref prop, logs to you a type error with the following message:

<details>
<summary>Typescript error message</summary>
<pre>
</code>
Type 'ForwardedRef<unknown>' is not assignable to type 'Ref<BottomSheetModalMethods> | undefined'.
  Type 'MutableRefObject<unknown>' is not assignable to type 'Ref<BottomSheetModalMethods> | undefined'.
    Type 'MutableRefObject<unknown>' is not assignable to type 'RefObject<BottomSheetModalMethods>'.
      Types of property 'current' are incompatible.
        Type 'unknown' is not assignable to type 'BottomSheetModalMethods | null'.
          Type 'unknown' is not assignable to type 'BottomSheetModalMethods'.ts(2322)
index.d.ts(140, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & BottomSheetModalProps & RefAttributes<BottomSheetModalMethods>'
</code>
</pre>
</details>

## Environment info

| Library                                       | Version |
| ----------------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.0.0  |
| react-native                               | 0.64.3   |
| react-native-reanimated            | ~2.2.0  |
| react-native-gesture-handler    |  ~1.10.2  |

## Steps To Reproduce

1. Create a component that is encapsulated by a `forwardRef` and pass `ref` to `BottomSheet`'s ref prop.
2.
3. 

Describe what you expected to happen:

1. Accepts the ref from  `forwardRef`
2.

## Reproducible sample code

```tsx
import React, { useMemo, useCallback, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const RNBottomSheet = React.forwardRef((_, ref) => {
   // variables
   const snapPoints = useMemo(() => ['25%', '50%'], []);

   // callbacks
   const handleSheetChanges = useCallback((index: number) => {
     console.log('handleSheetChanges', index);
   }, []);

  return (
      <BottomSheet
        ref={ref}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
  );
}

const App = () => {
   // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  return (
    <View style={styles.container}>
      <RNBottomSheet ref={bottomSheetRef} />
    <View />
  );
}
```

**Comment by jvasquez864** [comment]
if you annotate the type of the ref param as `ForwardedRef<BottomSheet>`, it should work

**Comment by noghartt** [comment]
> if you annotate the type of the ref param as `ForwardedRef<BottomSheet>`, it should work

Yep! It's work! If I type my component like this, it's work correctly:

```tsx
const BottomSheet = React.forwardRef<BottomSheet>((props, ref) => (
  // rest of the component....
));
```

Thank you! Closing this issue.

**Comment by damonbauer** [comment]
FWIW, this is my implementation:

```tsx
// CustomBottomSheet.tsx

import React from 'react';
import BottomSheet, { BottomSheetProps } from '@gorhom/bottom-sheet';

const CustomBottomSheet = React.forwardRef<BottomSheet, BottomSheetProps>(
  (props, ref) => {
    const { children, ...other } = props;

    return (
      <BottomSheet
        enablePanDownToClose // other props can go here
        ref={ref}
        {...other}>
        {children}
      </BottomSheet>
    );
  },
);
```
---

```tsx
// Consumer.tsx

const Consumer() => {
  const bottomSheetRef = useRef<BottomSheet>(null);

  return <View>
    <CustomBottomSheet ref={bottomSheetRef} snapPoints={['25%']}>...</CustomBottomSheet>
  </View>
}
```

**Comment by agestaun** [comment]
There is no problem to assign the reference to the bottomSheet. However, I cannot close the child (in this case, the CustomBottomSheet component). I would like to be able to close it from the parent (the creator of the ref) and from the child (the one that receives the ref with forward ref and renders the bottomSheet).

I could solve it using the imperative hook and exposing the methods to the parent the methods I need. Not the perfect solution, but pretty clean.

```typescript
export interface Disposable {
    close: () => void;
}

....

const CustomBottomSheet = forwardRef<Disposable, Props>((props, disposable) => {
    const bottomSheetRef = createRef<BottomSheet>();

    useImperativeHandle(bottomSheetDisposable, () => ({
         close: () => bottomSheetRef.current?.close() 
    }));

    return <BottomSheet ref={bottomSheetRef}>{props.children}</BottomSheet>;
});
```

Hope it can help someone else.
