### ISSUE TITLE
[v4] | [v2] Sheet does not go back to original position after TextInput blur

### ISSUE THREAD

**Issue by Yonom** [gorhom/react-native-scroll-bottom-sheet#752]
# Bug

When the keyboard is dismissed (on Android via the "▼" button in the nav bar; cross platform when you tap on a ScrollView in your bottom sheet), the BottomSheet does not go back to its original position

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.66.2   |
| react-native-reanimated         | 2.2.3   |
| react-native-gesture-handler    | 1.10.3    |

## Steps To Reproduce

1. Copy the code from the keyboard handling guide in wiki (https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling) to a brand new app
2. Open app on Android
3. Focus on the TextInput and press the down arrow in navbar
![image](https://user-images.githubusercontent.com/1394504/141961387-92475c4e-d0ed-4d79-83db-2de8532a71ba.png)

Describe what you expected to happen:

1. The BottomSheet should go back to its original position after the keyboard is dismissed

## Reproducible sample code

https://gorhom.github.io/react-native-bottom-sheet/keyboard-handling

**Comment by 0xknon** [comment]
I have the same issue

**Comment by 0xknon** [comment]
@Yonom  
Just find the solution.
You need to set `keyboardBlurBehavior="restore"` in the `BottomSheet` component. 

See if this helps.

**Comment by Yonom** [comment]
Thanks @knyucross!
