### ISSUE TITLE
[v4] | [v2] delay after bottom modal is closed either via gesture or backdrop press

### ISSUE THREAD

**Issue by Monir-Shembesh** [gorhom/react-native-scroll-bottom-sheet#755]
# Bug

I love this component but there was no enhancement label thus i chose bug. But the issue is that there is a huge delay after closing the modal and makes its usage dull. For example I am trying to change the state and conditionally render a bottom footer but it takes time to take effect actually. Please check the video below

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4  |
| react-native                    | 0.66.0   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. set up a state with a boolean value (false)
2. condition a component to show or hide according to the previous state
3. change the state in the onChange function of the bottom sheet

Describe what you expected to happen:

1. faster on change calls
2. displaying the conditioned component will be as instant as a button press

https://user-images.githubusercontent.com/29189345/142757137-42a02350-662c-4222-a9c8-5539d64d640b.mp4

**Comment by Roka20012** [comment]
@Monir-Shembesh have you managed to fix this issue?
I have the same problem with the bottom sheet it closes a little bit slow

**Comment by Monir-Shembesh** [comment]
@Roka20012  I believe I managed to change the implementation programmatically within the library itself but I do not have access to this repo anymore to check it unfortunately

**Comment by TaimoorHussain45** [comment]
i have same issue.can anyOne tell me the solution

https://github.com/user-attachments/assets/6c0d6148-d801-4008-bba8-90cdfbf6b409
