### ISSUE TITLE
[v4] Pull to Refresh not working on iOS

### ISSUE THREAD

**Issue by darkbasic** [gorhom/react-native-scroll-bottom-sheet#758]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.4   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Follow the instructions on https://gorhom.github.io/react-native-bottom-sheet/pull-to-refresh and provide `refreshing` and `onRefresh` props to `BottomSheetScrollView`.
2. Android: pull to refresh works (albeit only when the bottom sheet is snapped at the topmost position).
3. iOS: pull to refresh doesn't work. 

Describe what you expected to happen:

1. Should work on both iOS and Android.

## Reproducible sample code

https://snack.expo.dev/z1gI0579b

**Comment by darkbasic** [comment]
Comment to avoid closure.

**Comment by han-steve** [comment]
yo this is a real issue

**Comment by litinskii** [comment]
Same

**Comment by Pjexaf** [comment]
I found a solution.

For some reasons it works both on Android and iOS if use like so:

<BottomSheetScrollView
          refreshing={isRefreshing}
          onRefresh={handleRefresh}
          refreshControl={<RefreshControl refreshing={isRefreshing} onRefresh={handleRefresh} />}
>

**Comment by Gogn** [comment]
I found a solution.

For some reasons it works both on Android and iOS if use like so:

```
<BottomSheetScrollView
 refreshing={isRefreshing}
 onRefresh={handleRefresh}
 refreshControl={<RefreshControl refreshing={isRefreshing} onRefresh={handleRefresh} />}
>
```
