### ISSUE TITLE
[v4] `BottomSheet` opens by itself on Android.

### ISSUE THREAD

**Issue by proudust** [gorhom/react-native-scroll-bottom-sheet#761]
# Bug

## Environment info

| Library | Version |
| --- | --- |
| @gorhom/bottom-sheet | 4.1.4 |
| react-native | 0.64.3 |
| react-native-reanimated | 2.2.4 |
| react-native-gesture-handler | 1.10.3 |

## Steps To Reproduce

![react-native-bottom-sheet-v4_1_4-bug-report_1](https://user-images.githubusercontent.com/20186429/143746494-458fd550-ec2d-486a-8dd7-ea50777ccca4.gif)

1. Place a `<TextInput />` and `<BottomSheet index={-1} />`.
2. Tap "TextInput" to open the keyboard and enter the any text.
3. After typing, wait about three seconds and then close the keyboard.
4. BottomSheet will open.

Describe what you expected to happen:

1. Bottom sheet does not open when keyboard is closed.

## Reproducible sample code

https://snack.expo.io/@proudust/react-native-bottom-sheet-v4_1_4-bug-report

**Comment by kdenz** [comment]
Same issue here

**Comment by swikars1** [comment]
This can be fixed my changing `android:windowSoftInputMode` value to `"adjustPan"` in `AndroidManifest.xml`.
Here is a part of my `AndroidManifest.xml`:
```
<activity
  android:name=".MainActivity"
  android:label="@string/app_name"
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
  android:screenOrientation="portrait"
  android:launchMode="singleTask"
  android:windowSoftInputMode="adjustPan">
  <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity>
```

**Comment by kdenz** [comment]
@swikars1 Yes it works but our app's UI/UX is heavily dependent on "adjustResize", is there any alternative?

**Comment by lucaashrq** [comment]
I have the same issue, did you solve it?

**Comment by vanGalilea** [comment]
This is issue is still relevant guys, though couldn't reproduce it on my OnePlus 8 pro device :/

**Comment by jayeshpurohit12** [comment]
> # Bug
> ## Environment info
> Library	Version
> @gorhom/bottom-sheet	4.1.4
> react-native	0.64.3
> react-native-reanimated	2.2.4
> react-native-gesture-handler	1.10.3
> ## Steps To Reproduce
> ![react-native-bottom-sheet-v4_1_4-bug-report_1](https://user-images.githubusercontent.com/20186429/143746494-458fd550-ec2d-486a-8dd7-ea50777ccca4.gif) [ ![react-native-bottom-sheet-v4_1_4-bug-report_1](https://user-images.githubusercontent.com/20186429/143746494-458fd550-ec2d-486a-8dd7-ea50777ccca4.gif) ](https://user-images.githubusercontent.com/20186429/143746494-458fd550-ec2d-486a-8dd7-ea50777ccca4.gif) [ ](https://user-images.githubusercontent.com/20186429/143746494-458fd550-ec2d-486a-8dd7-ea50777ccca4.gif)
> 
> 1. Place a `<TextInput />` and `<BottomSheet index={-1} />`.
> 2. Tap "TextInput" to open the keyboard and enter the any text.
> 3. After typing, wait about three seconds and then close the keyboard.
> 4. BottomSheet will open.
> 
> Describe what you expected to happen:
> 
> 1. Bottom sheet does not open when keyboard is closed.
> 
> ## Reproducible sample code
> https://snack.expo.io/@proudust/react-native-bottom-sheet-v4_1_4-bug-report

@proudust got the same problem have you got the solution of that ??

**Comment by swikars1** [comment]
this issue is very relevant only thing I could do was change in manifest as android:windowSoftInputMode="adjustPan"

**Comment by inthisar-hamza** [comment]
still same bug!
