### ISSUE TITLE
[v4] BottomSheetModal stops showing after user taps item in nested BottomSheetFlatList (caused by gesture-handler dependency update)

### ISSUE THREAD

**Issue by Dimous** [gorhom/react-native-scroll-bottom-sheet#768]
# Bug
There is BottomSheetFlatList inside BottomSheetModal. User requests menu so modal is opened up. Modal closes when user taps menu item. To choose another option, user requests menu again. It was working with "react-native-gesture-handler": "1.10.3" and stopped with "2.0.0". No errors in console.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.4   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 2.0.0   |

## Steps To Reproduce

1. create BottomSheetFlatList inside BottomSheetModal and button which triggers present method on bottom sheet ref
2. tap on the button, then tap list item which must trigger close method on sheet ref
3. tap the button again

Describe what you expected to happen:

1. modal opens up again

**Comment by sergeymild** [comment]
the same issue

**Comment by Dimous** [comment]
It is working again with  "react-native-gesture-handler": "^2.1.0" and "react-native-reanimated": "^2.3.0",
