### ISSUE TITLE
[v4] | [v2] An edge case for multiline input keyboard handling

### ISSUE THREAD

**Issue by tungduonghgg123** [gorhom/react-native-scroll-bottom-sheet#772]
# Bug

First of all, I want to thank you for bringing such a great lib.
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.65.1|
| react-native-reanimated         | "2.2.3"   |
| react-native-gesture-handler    | "^1.10.3"   |

## Steps To Reproduce

1. Snap point set as 100%
2. Add a BottomSheetSectionList, render any content inside, make sure the footer is at bottom-edge
2. In the footer, add a BottomSheetInput, with `isMultiple is true`
3. here is a short video describing it

https://user-images.githubusercontent.com/32666311/145560300-cab612e2-a2be-4497-a549-67a8334e4082.mp4

Describe what you expected to happen:

1. When click on the input, the keyboard should not hide the input

## Reproducible sample code

[Snack Link ](https://snack.expo.dev/@tungduonghgg123/bottomsheet-multiline-edge-case)

**Comment by vitorsilvalima** [comment]
I actually got it working by setting `keyboardBehavior="extend"`

```
 <RNBottomSheet
      ref={ref}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}
      animateOnMount={false}
      onClose={onClose}
      backdropComponent={renderBackdrop}
      backgroundStyle={styles.backgroundStyle}
      handleIndicatorStyle={styles.handleIndicator}
      enablePanDownToClose
      keyboardBehavior="extend"
      keyboardBlurBehavior="restore"
    >
```

**Comment by Zakyyy** [comment]
any update on this?
I am facing the same issue
