### ISSUE TITLE
[v4] `enablePanDownToClose` not working on iOS and Android

### ISSUE THREAD

**Issue by mwegener-com** [gorhom/react-native-scroll-bottom-sheet#775]
# Bug

I nested the bottomSheet in a react-native-modal component and use the modal backdrop for onClose.

The prop `enablePanDownToClose` is not working on my iOS and Android app.

If I wrap my app or component with `GestureHandlerRootView` it doesn't make any differences.

Do you have any idea?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce
1. Add code from below
2. Start your app
3. Try to swipe

Describe what you expected to happen:

1. BottomSheet should slide down

## Reproducible sample code

```js
return (
			<Modal
				isVisible={props.modalVisible}
				useNativeDriver={true}
				backdropOpacity={dimensions.shadowOpacity}
				style={styles.modalCenteredView}
				onBackdropPress={props.onClose}
				onBackButtonPress={props.onClose}
				statusBarTranslucent
				hideModalContentWhileAnimating
			>
				<BottomSheet
					ref={bottomSheetRef}
					index={0}
					snapPoints={props.bottomSheetHeight ? [props.bottomSheetHeight] : [DEFAULT_BOTTOM_SHEET_HEIGHT]}
					enablePanDownToClose
				>
					<BottomSheetView style={styles.bottomContent}>{content}</BottomSheetView>
				</BottomSheet>
			</Modal>
		);
```

https://user-images.githubusercontent.com/64470126/145685607-e03eaea2-97b1-42cb-8744-647ed476433a.mov

**Comment by ololoepepe** [comment]
I' having the same issue, but on Android only. On iOS it works fine. Please, take a look at that.

P.S.: Who the hell has invented that bots silently closing issues? :angry:

**Comment by ahAskari** [comment]
> I' having the same issue, but on Android only. On iOS it works fine. Please, take a look at that.
> 
> P.S.: Who the hell has invented that bots silently closing issues? angry

use GestureHandlerRootView to wrap BottomSheet component and and adjust flex: 1
It works for me

**Comment by ahAskari** [comment]
use GestureHandlerRootView to wrap BottomSheet component and and adjust flex: 1
It works for me

**Comment by Beyazatli** [comment]
> use GestureHandlerRootView to wrap BottomSheet component and and adjust flex: 1 It works for me

this worked for me on:
React Native 0.64.3
Expo 44
React Native Gesture Handler 2.1.0

**Comment by MaganAnkur** [comment]
enablePanDownToClose didn't work on android. Adding GestureHandlerRootView to App.js file resolved the issue for me.

```
<SafeAreaProvider>
              <GestureHandlerRootView style={{flex: 1}}>
                <BottomSheetModalProvider>
                  <NavigationContainer ref={navigationRef}>
                    <MainNavigator />
                  </NavigationContainer>
                </BottomSheetModalProvider>
              </GestureHandlerRootView>
 </SafeAreaProvider>
```

**Comment by JoyCood** [comment]
> enablePanDownToClose didn't work on android. Adding GestureHandlerRootView to App.js file resolved the issue for me.
> 
> ```
> <SafeAreaProvider>
>               <GestureHandlerRootView style={{flex: 1}}>
>                 <BottomSheetModalProvider>
>                   <NavigationContainer ref={navigationRef}>
>                     <MainNavigator />
>                   </NavigationContainer>
>                 </BottomSheetModalProvider>
>               </GestureHandlerRootView>
>  </SafeAreaProvider>
> ```

still not work for me on android, but without **<GestureHandlerRootView style={{flex: 1}}**, it's work great on ios.

**Comment by Vikram-D16** [comment]
I’m encountering the same issue on Android. **<GestureHandlerRootView style={{flex: 1}}>** didn't worked for me..

<Modal>
  <BottomSheet>
    <BottomSheetScrollView>
    </BottomSheetScrollView>
  </BottomSheet>
</Modal>

**Comment by Vikram-D16** [comment]
I’m encountering the same issue on Android. **<GestureHandlerRootView style={{flex: 1}}>** didn't worked for me..
`<Modal>
  <BottomSheet>
    <BottomSheetScrollView>
    </BottomSheetScrollView>
  </BottomSheet>
</Modal>`
