### ISSUE TITLE
[v4.1.5] enablePanDownToClose is defaulted to false on BottomSheet but defaulted to true on BottomSheetModal

### ISSUE THREAD

**Issue by hmust92** [gorhom/react-native-scroll-bottom-sheet#777]
# Bug

enablePanDownToClose is defaulted to false on BottomSheet and the documentation also mentions this. However, enablePanDownToClose is defaulted to true on BottomSheetModal. The documentation doesn't mention this. I was running into an issue where I was expecting this prop to behave similarly for the BottomSheetModal and I had to do debugging and digging into the library's source code to figure out what was going on. Is this done on purpose?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. Render <BottomSheet />. enablePanDownToClose is defaulted to false and the Bottom Sheet does not close when swiping down.
2. Render <BottomSheetModal />. enablePanDownToClose is internally defaulted to true and the Bottom Sheet Modal dismisses when swiping down.

The documentation on BottomSheetModal doesn't mention anything about enablePanDownToClose differently so BottomSheetModal should behave the same way.

**Comment by RomanSytnyk** [comment]
Thank you!
I spent much time on understanding why modal is closing without this param, need to set false by hands, omg
