### ISSUE TITLE
[v4] BottomSheetTextInput not draggable on Android

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-scroll-bottom-sheet#778]
# Bug

@gorhom I can't remember if we ever resolved this issue, but is BottomSheetTextInput not draggable on Android? Could you please remind me if there's a solution?

## Environment info

On snack. Expo SDK43

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |

## Steps To Reproduce

Check out the snack. Try to pull the bottom sheet dragging on the "Search" bar

## Reproducible sample code

https://snack.expo.dev/@kickbk/search-bottomsheet

**Comment by ghost** [comment]
I confirm that the bug is repeated. I was able to repeat on React Native CLI.
"react-native": "0.66.4"
"react-native-reanimated": "^2.3.1",
"@gorhom/bottom-sheet": "^4.1.5",
"react-native-gesture-handler": "^2.1.0",

**Comment by rakshadeveloper** [comment]
Hello 
I'm still having the same issue on Android devices.
I'm using this version  `"^v4.1.5"`
Kindly look into it.

**Comment by WisaniShilumani** [comment]
I'm having the same issue on Android devices. Works okay for iOS. I have tried wrapping my app in the GestureHandlerRootView, but to no success. version: "^4"

**Comment by kickbk** [comment]
This is not an issue with react-native-bottom-sheet but with [PanGestureHandler from react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler/issues/668).
Should be resolved with GH 2.5.0 but in the meantime you can solve it by applying the changes [in this patch](https://github.com/rainbow-me/rainbow/blob/aa70c032693c3c1c3cf0775cb7cb7d6e6a20662a/patches/react-native-gesture-handler%2B1.7.0.patch)

**Comment by zirlman** [comment]
The recent version of `react-native-gesture-handler` has a `TextInput` component that allows gestures.

You can read more here: https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/basics/about-handlers/#using-native-components

**Comment by julian-kingman-lark** [comment]
I'm running into this issue, but with just regular content, no TextInput. It should be draggable right? It only drags if I place a BottomSheetScrollview, and then only drags from the content (not the handle or header I've placed above the scrollview). I take it this is not expected behavior?
