### ISSUE TITLE
[v4] BottomSheetBackdrop - appearsOnIndex of 0 fails to render backdrop (has workaround)

### ISSUE THREAD

**Issue by thecodedrift** [gorhom/react-native-scroll-bottom-sheet#779]
# Bug

* [x] I'm willing to provide a pull request for this issue

As of `4.1.5`, the `BottomSheetBackdrop` does not support a value of `appearsOnIndex={0}`. The root cause seems to be coercion to a default of `1` from a falsey `0` value.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create a bottom sheet with a custom backdrop using the `renderBackdrop` from the example
2. Provide the properties `appearsOnIndex={0}` and `disappearsOnIndex={0}`

Describe what you expected to happen:

1. The backdrop should be visible on index `0`

**Workaround** Providing a `snapIndex` such as `snapIndex={[1, "40%"]}` will work although technically the modal will be visible at the bottom of the screen. Alternatively, you can copy/paste the `BottomSheetBackdrop` into a new component with either new defaults or fixed coercion.

## Reproducible sample code

**Reproducible Snack:** https://snack.expo.dev/@jakobo/bottomsheetbackdrop---appearsonindex-bug

**Comment by thecodedrift** [comment]
In case someone gets to this before I can put a PR together, the issue is [here](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx#L28) and the signature probably needs to be rewritten to something like:

```ts
const BottomSheetBackdropComponent = ({
  animatedIndex,
  opacity,
  appearsOnIndex,
  disappearsOnIndex,
  enableTouchThrough = DEFAULT_ENABLE_TOUCH_THROUGH,
  pressBehavior = DEFAULT_PRESS_BEHAVIOR,
  style,
  children,
}: BottomSheetDefaultBackdropProps) => {
  //#region defaults
  opacity = opacity ?? DEFAULT_OPACITY;
  appearsOnIndex = appearsOnIndex ?? DEFAULT_APPEARS_ON_INDEX;
  disappearsOnIndex = disappearsOnIndex ?? DEFAULT_DISAPPEARS_ON_INDEX;
  //#endregion
```

It's only an issue because the initial value of `0` will get forced to their non-zero defaults. This problem technically exits with setting default opacity as well, but it's more noticeable with `appearsOnIndex` since we're no longer setting our first snap point of `0`. Alternatively, we can use a non `??` operator like either of the below.

```ts
// conditional operator for undefined value
opacity = (typeof opacity !== "undefined") ? opacity : DEFAULT_OPACITY;

// Allow explicit zero, otherwise coerce
opacity = opacity === 0 ? 0 : opacity || DEFAULT_OPACITY;
```

**Comment by pnogier** [comment]
Hi, any update on this issue ? 🙏

**Comment by thecodedrift** [comment]
PR is in #793. Hopefully it gets addressed soon. In the meantime, you can create your own backdrop with the changes, which is what we did.

**Comment by JohnLamHK** [comment]
Add disappearsOnIndex={-1} to your backdrop component!
I had the same problem without adding disappearsOnIndex={0} (since it's default). Seems like an unwanted feature to me though, as I assume many people would want to show backdrop at index 0...  my guess is disappearsOnIndex somehow takes precedence over appearsOnIndex?

**Comment by jakobo** [comment]
!stale

**Comment by IngyuTae** [comment]
You could write a custom backdrop component until the PR merged

```tsx
import { BottomSheetBackdropProps } from '@gorhom/bottom-sheet'
import React, { useMemo } from 'react'
import Animated, {
  Extrapolate,
  interpolate,
  useAnimatedStyle,
} from 'react-native-reanimated'

const CustomBackdrop = ({ animatedIndex, style }: BottomSheetBackdropProps) => {
  const containerAnimatedStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      animatedIndex.value,
      [-1, 0],
      [0, 0.5],
      Extrapolate.CLAMP
    ),
  }))

  const containerStyle = useMemo(
    () => [style, { backgroundColor: '#a8b5eb' }, containerAnimatedStyle],
    [style, containerAnimatedStyle]
  )

  return <Animated.View style={containerStyle} />
}

export default CustomBackdrop
```

**Comment by nico2che** [comment]
Same problem here, but after reading this https://github.com/gorhom/react-native-bottom-sheet/blob/0010008906154f9a545f89d5826ea7af48336610/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx#L84

You need to overwrite `disappearsOnIndex` default value:

```js
const renderBackdrop = useCallback(
  props => (
    <BottomSheetBackdrop
      {...props}
      disappearsOnIndex={-1}
      appearsOnIndex={0}
    />
  ),
  [],
);
```

Works well for me
