### ISSUE TITLE
Prop to disable snap skip

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-scroll-bottom-sheet#783]
# Feature Request

I have following snap points:

`const snapPoints = useMemo(() => ['25%, '50%', '100%'], []);`

If I swipe the bottom sheet "fast enough", the sheet snaps from 25% to 100%. It does not stop at 50%.

It would be great, if there was a prop, that a sheet starting at 25% stops at 50%. Only if the sheet is at 50%, it can swipe to 100% or 25%. But never from 25% directly to 100%.

I already tried to find a solution but couldn't make it...

## Why it is needed

For our app it's important to stop at 50% after the first swipe starting with 25%, that the user can see 50% of the bottom sheet and 50% of the content behind the bottom sheet. Our test users always swiped to fast and had the problem, that the bottom sheet did not stop at 50%. It snapped from 25% to 100% which is a bad UX for our case.

In the bottom sheet, which Airbnb-App uses, you can't swipe from 25% to 100%. If you start at 25% it stops at 50% after the first swipe. Only if you swipe again, the sheet snaps from 50% to 100%.

**Comment by Leoputera2407** [comment]
Hey @felix4321, did you manage to figure out how to do this?

**Comment by ghost** [comment]
@Leoputera2407 Unfortunately not...
