### ISSUE TITLE
[v4]  Gesture not working on Android when using BottomSheetModalProvider

### ISSUE THREAD

**Issue by membleapp** [gorhom/react-native-scroll-bottom-sheet#784]
# Bug

When I use BottomSheetModalProvider in my App.js and my BottomSheetModal in an other screen, everything works on iOS but, on android gestures stop to works. 
I can't scroll down and up on my bottom sheet and when I touch the backdropComponent, the bottom sheet don't close. 

The only fix I found is to add BottomSheetModalProvider in my screen instead than in App.js. But with this solution the bottom sheet appears on the top of my tab bar. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5  |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.3.0  |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1.In you App.js wrap your navigation with the BottomSheetModalProvider component. 

```
        <IntlProvider locale ={locale} onError={() => onError} messages={Lang[locale] ?? Lang['en']} defaultLocale={'en'}>
            <Provider store={store}>
                <PersistGate loading={null} persistor={persist}>
                        <BottomSheetModalProvider> 
                            <Routes initialRoute={initialRoute}/>
                        </BottomSheetModalProvider>
                </PersistGate>
            </Provider>
        </IntlProvider>
```

2. In your screen add the BottomSheet
```
<BottomSheetModal
      enableHandlePanningGesture={true}
      ref={settingsGroupBottomSheetModalRef}
      index={1}          
      snapPoints={snapPoints}
    backdropComponent={renderBackdrop}
  >
    <Content />
 </BottomSheetModal>
 ```

This is working fine on iOS, but on android gestures not works

3. Fix I found 
```
if (Platform.OS === 'ios') {
    return (
      <BottomSheetModal
        enableHandlePanningGesture={true}
        ref={settingsGroupBottomSheetModalRef}
        index={1}
        snapPoints={snapPoints}
        backdropComponent={renderBackdrop}
      >
        <Content />
      </BottomSheetModal>
    );
  } else {
    return (
      <BottomSheetModalProvider>
        <BottomSheetModal
          enableHandlePanningGesture={true}
          ref={settingsGroupBottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          backdropComponent={renderBackdrop}
        >
          <Content />
        </BottomSheetModal>
      </BottomSheetModalProvider>
    )
  }
```

the problem is that my tab bar and top bar is visible because BottomSheetModalProvider don't wrap my navigator. 

Describe what you expected to happen:

1. I would to have the same behavior on iOS and Android

**Comment by niraj-khatiwada** [comment]
Any updates on this. I am having exactly same issue. The gesture does not work in Android.

[UPDATE]: Found Solution: https://github.com/gorhom/react-native-bottom-sheet/issues/596#issuecomment-988501754
