### ISSUE TITLE
[v4] Listen for Animated Index Changes in useBottomSheet hook

### ISSUE THREAD

**Issue by tylercote** [gorhom/react-native-scroll-bottom-sheet#788]
# Feature Request
It would be very useful to be able to "listen" for changes to the current snap point of the modal from any nested component.  This might already be supported by the library, I'm not sure if 

## Why it is needed

When a modal is closed, it's pretty common to perform some "state" cleanup in nested child components. A possible example of this could be scrolling a ScrollView back up to the top.  For this, 

I tried doing the following, but it seems that I am only given the initial value, and it does not pick up on any subsequent changes.

```
const { animatedIndex } = useBottomSheet();

useEffect(() => {
    console.log(animatedIndex.value);
}, [animatedIndex.value]);
```

**Comment by eqlion** [comment]
You can use [`useAnimatedReaction`](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedReaction):

```js
useAnimatedReaction(
    () => animatedIndex.value,
    (v) => {
      console.log(v)
    },
  )
```

**Comment by YaoHuiJi** [comment]
> You can use [`useAnimatedReaction`](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedReaction):
> 
> ```js
> useAnimatedReaction(
>     () => animatedIndex.value,
>     (v) => {
>       console.log(v)
>     },
>   )
> ```

thank you! you save my life, I forgot it was a RN2 shared value, so it's no wonder that useEffect doesn't work😂
