### ISSUE TITLE
Question - How overlap the bottomtab / header navigation?

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-scroll-bottom-sheet#789]
<td class="d-block comment-body markdown-body  js-comment-body">
          <h1 dir="auto">Bug</h1>
<p dir="auto">Hi, i'm using this library to display the bottom sheet modal, but, is not in position absolute, so i see my bottomtab and header, the modal does not fill the entire display.

I tried to use Modal provider and wrap the navigation but there are no difference. 
<h2 dir="auto">Environment info</h2>

<table role="table">
<thead>
<tr>
<th>Library</th>
<th>Version</th>
</tr>
</thead>
<tbody>
<tr>
<td>@gorhom/bottom-sheet</td>
<td>4.1.5</td>
</tr>
<tr>
<td>react-native</td>
<td>0.66.4</td>
</tr>
<tr>
<td>react-native-reanimated</td>
<td>2.3.1</td>
</tr>
<tr>
<td>react-native-gesture-handler</td>
<td>2.1.0</td>
</tr>
</tbody>
</table>
<h2 dir="auto">Steps To Reproduce</h2>
<ol dir="auto">
<li>implement navigations with <code>@react-navigation/native-stack</code></li>
<li>Implement bottom sheet modal</li>
<li>Try to open the modal</li>
</ol>
<p dir="auto">Describe what you expected  happen:</p>
<ol dir="auto">
<li>I Expect the modal fill all screen</li>
</ol>
<h2 dir="auto">Reproducible sample code</h2>
<p dir="auto">Wrapped my navigation in modal provider</p>

`<Provider store={store}>
      <PersistGate persistor={persistor}>
        <StripeProvider publishableKey={Config.REACT_APP_STRIPE_PK}>
          <SafeAreaProvider>
            <ErrorBoundary FallbackComponent={ChefError}>
              <LoadingProvider>
                <ApplicationNavigator />
              </LoadingProvider>
            </ErrorBoundary>
          </SafeAreaProvider>
        </StripeProvider>
      </PersistGate>
    </Provider>`

**Comment by ghost** [comment]
news?

**Comment by Engazan** [comment]
> news?

wrap your app with ```<BottomSheetModalProvider>``` put your ```NavigationContainer``` inside, open your modal ```BottomSheetModal``` all modals should teleport to right place

**Comment by ghost** [comment]
@Engazan Ok, but now im using BottomSheetModal  with forwardef, but no works, the modal remain closed

**Comment by Engazan** [comment]
> @Engazan Ok, but now im using BottomSheetModal with forwardef, but no works, the modal remain closed

yes its correct, you neet "present it" in useEffect or some button

```
modalRef.current?.present();
```

**Comment by ghost** [comment]
> > @Engazan Ok, but now im using BottomSheetModal with forwardef, but no works, the modal remain closed
> 
> yes its correct, you neet "present it" in useEffect or some button
> 
> ```
> modalRef.current?.present();
> ```

Yes ok, but no works with forward ref, the ref remain null!

**Comment by ghost** [comment]
```
`<BottomSheetModalProvider>
                    <ApplicationNavigator />
                  </BottomSheetModalProvider>`

`const FiltersBottomSheetModal = ({navigation, route, snapPoints}, ref) => {`

`export default forwardRef(FiltersBottomSheetModal);
` <BottomSheetModal
      ref={ref}
      onAnimate={(a, b) => setIndex(b)}
      handleIndicatorStyle={{backgroundColor: Colors.lightGrey}}
      index={-1}
      topInset={safeAreaInsets.top}
      bottomInset={safeAreaInsets.bottom}
      backdropComponent={renderBackdrop}
      snapPoints={snapPoints}
      footerComponent={renderFooter}
      enablePanDownToClose>`

`

external:

`  const openFilterBottomSheet = useCallback(()=> {
    sheetRef.current?.present();
  }, []);

  const sheetRef = useRef(null);
  const snapPoints = useMemo(() => ['50%', '100%'], []);`

` <FiltersBottomSheetModal
        ref={sheetRef}
        route={route}
        navigation={navigation}
        snapPoints={snapPoints}
      />`

```

**Comment by Engazan** [comment]
> ```
> 
> `<BottomSheetModalProvider>
> 
>                     <ApplicationNavigator />
> 
>                   </BottomSheetModalProvider>`
> 
> 
> 
> `const FiltersBottomSheetModal = ({navigation, route, snapPoints}, ref) => {`
> 
> 
> 
> `export default forwardRef(FiltersBottomSheetModal);
> 
> ` <BottomSheetModal
> 
>       ref={ref}
> 
>       onAnimate={(a, b) => setIndex(b)}
> 
>       handleIndicatorStyle={{backgroundColor: Colors.lightGrey}}
> 
>       index={-1}
> 
>       topInset={safeAreaInsets.top}
> 
>       bottomInset={safeAreaInsets.bottom}
> 
>       backdropComponent={renderBackdrop}
> 
>       snapPoints={snapPoints}
> 
>       footerComponent={renderFooter}
> 
>       enablePanDownToClose>`
> 
> 
> 
> `
> 
> 
> 
> external:
> 
> 
> 
> `  const openFilterBottomSheet = useCallback(()=> {
> 
>     sheetRef.current?.present();
> 
>   }, []);
> 
> 
> 
>   const sheetRef = useRef(null);
> 
>   const snapPoints = useMemo(() => ['50%', '100%'], []);`
> 
> 
> 
> ` <FiltersBottomSheetModal
> 
>         ref={sheetRef}
> 
>         route={route}
> 
>         navigation={navigation}
> 
>         snapPoints={snapPoints}
> 
>       />`
> 
> 
> 
> ```

Your snap code is bad formatted, but this is Basic React knowlage 

When u want forwar ref you have to  use "forwardRef"

```
const a: React.FC = React. forwardRef((props, forwardedRef) => {
 return null
})

```

More info: https://reactjs.org/docs/forwarding-refs.html

**Comment by ghost** [comment]
``

> export default forwardRef(FiltersBottomSheetModal);

Im using forwardref in export, if i use BottomSheet without provider, it works

`const FiltersBottomSheetModal = ({navigation, route, snapPoints}, ref) =>`

`export default forwardRef(FiltersBottomSheetModal);`

**Comment by alexandrecoura96** [comment]
If you are facing this in expo router to overlap the header, you should wrap your main file, per example, the _layout with the BottomSheetModalProvider and inside your Bottom Sheet component, import the BottomSheetModal instead using that default import and put the index={0}.

So your code will be similar like this:

**Main File**
```
export default function Layout() {

  return (
    <GestureHandlerRootView>
      <BottomSheetModalProvider>
          <SafeAreaProvider>
            <StatusBar style="light" />
            <Stack screenOptions={{ headerShadowVisible: false }}>
              <Stack.Screen
                name={StackRouteNames.Splash}
              />
              <Stack.Screen
                name={StackRouteNames.Login}
              />
            </Stack>
            <ToastContainer />
          </SafeAreaProvider>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
}
```

Your Bottom Sheet:

```
import {
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetModal,
} from "@gorhom/bottom-sheet";

    const renderBackdrop = useCallback(
      (props: BottomSheetBackdropProps) => (
        <BottomSheetBackdrop
          {...props}
          appearsOnIndex={0}
          disappearsOnIndex={-1}
        />
      ),
      []
    );

      <BottomSheetModal
        {...props}
        ref={ref}
        index={0}
        backdropComponent={renderBackdrop}
        enablePanDownToClose>
       {content}
      </BottomSheetModal>
```
