### ISSUE TITLE
[v4] Bottom sheet doesn't dragg up in Android after upgrading to  Expo SDK44

### ISSUE THREAD

**Issue by erliskryeziu** [gorhom/react-native-scroll-bottom-sheet#790]
# Bug

  After upgrading to Expo SDK44, the Bottom Sheet doesn't drag up in Android devices, on the other hand in IOS it works completely fine. I upgraded every package following the guidelines, but still no result. Could you please give any help here?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet          |  1.0.0-alpha.22|
| react-native                  | 0.64.3|
| react-native-reanimated        | 2.3.1|
| react-native-gesture-handler    |2.1.0|

<BottomSheet
                    ref={this.bottomSheetRef}
                    snapPoints={[window.viewHeight - window.bottomSpace, 140]}
                    renderContent={() => <List onVehicleClick={(information) => this.onVehicleClick(information)} />}
                    renderHeader={() => <Header open={open} onClose={() => this.hideBottomSheet()} />}
                    initialSnap={1}
                    onOpenEnd={() => this.setState({open: true})}
                    onCloseEnd={() => this.setState({open: false})}
                    borderRadius={0}
                />

This is the code I am using right now.

Describe what you expected to happen:

What it is expected to happen, is to be able to open bottom sheet by dragging(scrolling) up the bottom sheet in Android devices, because in IOS devices it works perfectly fine.

**Comment by erliskryeziu** [comment]
SOLVED: In the lastest upgrade of Expo SDK 44, there was a change for usage of react-native-gesture-handler, which I didn't do it correctly. In the latest version, you need to wrap your parent component with GestureHandlerRootView, which acts up as an View in this case. This helped me solve this issue.


🏗 Deprecations, renamings, and removals
react-native-gesture-handler now requires a GestureHandlerRootView wrapper. As of v2, you now need to wrap your app with a GestureHandlerRootView component, as described in the related installation documentation.

Documentation for upgrading SDK44: https://blog.expo.dev/expo-sdk-44-4c4b8306584a

**Comment by Chandra-Panta-Chhetri** [comment]
@erliskryeziu Can you share a small snippet of what you mean?

Edit: I have made the following changes and it seems to work, let me know if I am missing something:

1. Added GestureHandlerRootView component as a parent component of NavigationContainer

```
        <GestureHandlerRootView style={containerStyles}>
          <NavigationContainer theme={theme}>
          </NavigationContainer>
        </GestureHandlerRootView>

```

**Comment by paranoia5** [comment]
@erliskryeziu  do you mean we wrap our <App> component with <GestureHandlerRootView > ?

**Comment by paranoia5** [comment]
Thanks @erliskryeziu

@Chandra-Panta-Chhetri Yes as stated in the upgrade docs:

> react-native-gesture-handler now requires a GestureHandlerRootView wrapper. As of v2, you now need to wrap your app with a `<GestureHandlerRootView>`

https://blog.expo.dev/expo-sdk-44-4c4b8306584a

**Comment by Chandra-Panta-Chhetri** [comment]
@paranoia5 
Thanks!

**Comment by RomanSuvorov** [comment]
@gorhom hello,
Could you add this info to "guides" or "usage" sections in READ.ME?

**Comment by IngyuTae** [comment]
Don't forget to add `flex:1`

```jsx
<GestureHandlerRootView style={{ flex: 1 }}>
  <App />
</GestureHandlerRootView>
```
