### ISSUE TITLE
[v4] Padding style property is not applied to bottom padding in BottomSheetView

### ISSUE THREAD

**Issue by wilkuintheair** [gorhom/react-native-scroll-bottom-sheet#791]
# Bug

When using `<BottomSheetView style={{padding: 10}} />` padding gets applied to all sides but bottom. Here's a diff that helped me:
```diff
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetView/BottomSheetView.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetView/BottomSheetView.tsx
index 12a2df6..9e840bc 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetView/BottomSheetView.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetView/BottomSheetView.tsx
@@ -25,7 +25,9 @@ function BottomSheetViewComponent({
     const paddingBottom =
       flattenStyle && 'paddingBottom' in flattenStyle
         ? flattenStyle.paddingBottom
-        : 0;
+        : flattenStyle && 'padding' in flattenStyle
+          ? flattenStyle.padding
+          : 0;
     return typeof paddingBottom === 'number' ? paddingBottom : 0;
   }, [style]);
   const containerAnimatedStyle = useAnimatedStyle(
```

![image](https://user-images.githubusercontent.com/644734/147120526-61f0d1c6-8b4b-4282-adad-e078fa0b0864.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.66.1   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Add a `<BottomSheet />` component to your screen
2. Add a `<BottomSheetView />` component as a child of the `<BottomSheet />`
3. Add `style` property with `{ padding: 20 }` or any other padding larger than 0
4. Observe that padding is not getting applied to bottom side
5. Add `{ paddingBottom: 20 }` style to workaround this

Describe what you expected to happen:

1. padding should be applied to all sides, including the bottom side

## Reproducible sample code

https://snack.expo.dev/@wilku/d2276f

**Comment by JuGit-pk** [comment]
still getting this padding problem while the left right and top are working but not the bottom one
