### ISSUE TITLE
Hide bottom sheet 

### ISSUE THREAD

**Issue by dinhduongson** [gorhom/react-native-scroll-bottom-sheet#794]
# Feature Request

I want to hide the bottom sheet when the screen renders. Now it always opens.

## Why it is needed

Not in every situation that we need bottom sheet open when screen starts

**Comment by 3KINGZ** [comment]
did you find a fix for this?

**Comment by fukemy** [comment]
hi, did u found any solution?

**Comment by dinhduongson** [comment]
<BottomSheet
                index={-1}
...
@fukemy 
@3KINGZ

**Comment by fukemy** [comment]
@dinhduongson  worked, thanks
