### ISSUE TITLE
[v4] | Bottom Sheet Modal content doesn't fill wrapper height on desktop

### ISSUE THREAD

**Issue by mhaagens** [gorhom/react-native-scroll-bottom-sheet#795]
# Bug

This might be an issue with the React Native Web implementation.
The `<Animated.View>` inside `<PanGestureHandler>` in `BottomSheetDraggableView.tsx` only fills its explicit height on iOS.
On desktop it only fills the height of its actual content. So if the height of the Bottom Sheet is 300px it still only takes up the height of the content.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.3.1   |
| react-native-gesture-handler    | 2.1.0   |

## Steps To Reproduce

1. Use example [from docs](https://gorhom.github.io/react-native-bottom-sheet/modal/usage)
2. Test in Chrome on MacOS
3. Test in Chrome on iOS

Describe what you expected to happen:

1. Expected the content of the bottom sheet to fill the height of its container
2. It only fills the height of the container on iOS

Web:
![web_gif](https://user-images.githubusercontent.com/3270517/147209851-96ea713d-0534-4b7c-9a69-08c507e58f5b.gif)

Mobile:
![mobile_gif](https://user-images.githubusercontent.com/3270517/147209877-8780cdb7-c283-4471-b5c5-fce1e6a48990.gif)

## Reproducible sample code

https://snack.expo.dev/@mhaagens/bottom-sheet-modal

**Comment by dullkingsman** [comment]
I have this problem on android. Has anyone found a fix for this?

**Comment by bhupendra1011** [comment]
I am also facing the same issue , in BottomSheetModal, content is not taking full height of the snapped sheet.
```
   <BottomSheetModal
        snapPoints={['50%', '100%']}
        ref={participantsSheetRef}
        name="ParticipantsSheet"
        stackBehavior="push">
        <BottomSheetScrollView contentContainerStyle={{flex:1}}> /* neither flex:1 or height:100% works */
          <ParticipantView
          />
        </BottomSheetScrollView>
      </BottomSheetModal>
```

I also tried BottomSheetView but still not working .

Hi, @mhaagens  did you get a workaround for this issue? many  thanks

**Comment by roberteggl** [comment]
I'm still facing this issue on Android... Any workarounds?

**Comment by kkx64** [comment]
For me, this worked: When it's dynamic sizing let it do its own thing, when it's not set to 100%

```tsx
    <BottomSheetModal
      ref={ref}
      handleIndicatorStyle={styles.handle}
      backgroundStyle={[
        styles.contentContainer,
        { backgroundColor: colors.darkBlue['950'] },
      ]}
      keyboardBehavior="interactive"
      keyboardBlurBehavior="restore"
      android_keyboardInputMode="adjustResize"
      onDismiss={handleDismiss}
      {...rest}
    >
      <BottomSheetView
        style={[
          styles.innerContainer,
          {
            height: rest.enableDynamicSizing ? undefined : '100%',
          },
        ]}
      >
        {children}
      </BottomSheetView>
    </BottomSheetModal>

...

  innerContainer: {
    flex: 1,
  },
```
