### ISSUE TITLE
[v4] [EXPO 44] onDismiss is not called when dismiss() on forwarded ref

### ISSUE THREAD

**Issue by Engazan** [gorhom/react-native-scroll-bottom-sheet#796]
# Bug

Today after upgrading EXPO 43 => EXPO 44 nothing happend when i call "modalRef->dismiss()" or "modalRef->dismiss()" in forwarded ref, btw calling "modalRef->expand()" works, btw "modalRef" is forwarded to child component where i control modal ( no i cant use hoos cuz multiple modals are open )

**when i try it on Expo SDK 43 all works as expected** 

calling it direcltry works

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| expo            |  44   |
| @gorhom/bottom-sheet            |  ^4.1.3   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | ~2.3.1   |
| react-native-gesture-handler    | ~2.1.0   |

Describe what you expected to happen:

1. when calling "modalRef->dismiss()" i expect trigger "onDismiss"

**Comment by jembach** [comment]
Hey @Engazan,
I had the same problem and for me solved upgrading to `v4.1.5` and also updated `@gorhom/portal` to `v1.0.11`. Before I used `@gorhom/bottom-sheet@4.1.4` and `@gorhom/portal@1.0.9` which had the problem you described.

**Comment by Engazan** [comment]
> 

upgrading to "@gorhom/bottom-sheet@4.1.5" fixed it, thanks
