### ISSUE TITLE
Bottom Sheet Modal backdropPress close modal and stack.

### ISSUE THREAD

**Issue by serverlocal017** [gorhom/react-native-scroll-bottom-sheet#799]
Hello,

I opened a Modal. So if I press the Backdrop button, then the Modal goes away (good) but also the navigation stack goes back (bad). So I only want to remove the modal not the stack. What I am doing wrong ?

`       
 const renderBackdrop = React.useCallback(
          props => <BottomSheetBackdrop {...props} pressBehavior="close" />,
          [],
        );

        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          backgroundStyle={{backfaceVisibility: 'visible', backgroundColor: 'green',}}
          backdropComponent={renderBackdrop}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>`

**Comment by rkz98** [comment]
Did u solve it? how?
