### ISSUE TITLE
[v4] BottomSheetModal Hides after parent state changed inside modal

### ISSUE THREAD

**Issue by Engazan** [gorhom/react-native-scroll-bottom-sheet#803]
# Bug
When changing screen state inside "BottomSheetModal" where i pass "React.Dispatch" prop will hide bottom sheet modal content, until i click somewhere then it will show again 

this happends only on Expo 44, Expo 43 works perfect

PS unable to make stack cuz Expo 44 is not yet in Stack ...

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.1.5 |
| react-native                    | 0.64.3   |
| react-native-reanimated         | ~2.3.1 |
| react-native-gesture-handler    | ~2.1.0   |
| expo | ~44.0.0 |

## Video

https://user-images.githubusercontent.com/53254371/148389011-98127d2b-c056-4da1-b556-283ccf7eee1f.mp4

## Steps To Reproduce

1. Change parent state from modal

Describe what you expected to happen:

1. when i change parent / state outside of modal modal should not hidde 

## Reproducible sample code

Parent ( drawer screen )
```ts

const [filter, setFilter] = React.useState({
        dlc: {
            2: true,
            3: true,
            4: false,
            5: true,
            6: true,
        }
    });
const [showFilter, setShowFilter] = React.useState<boolean>(false);

return <BottomSheetModalWrap filter={filter} setFilter={setFilter} visible={showFilter} setVisible={setShowFilter} />
```

BottomSheetWrap component
```ts
interface bottomSheetModalWrapProps {
    visible: boolean
    setVisible: React.Dispatch<boolean>
    filter: any // yup any for example ...
    setFilter: Dispatch<any> // yup any for example ...
}
const BottomSheetModalWrap: React.FC<BottomSheetModalWrapProps> = (props) => {

    const bottomSheetModalRef = useRef<BottomSheetModal>(null);
    
    React.useEffect(() => {

        if (props.visible) {
            bottomSheetModalRef.current?.present();
        } else {
            bottomSheetModalRef.current?.dismiss();
        }

    }, [props.visible]);

    function setNewSwitchValue(dlc: number, switchValue: boolean) {
        let newFilter = JSON.parse(JSON.stringify(props.filter));
        newFilter.dlc[dlc] = switchValue;
        props.setFilter(newFilter);
    }
    
    return (
        <BottomSheetModal
            ref={bottomSheetModalRef}
            snapPoints={['75%']}
            backdropComponent={props => (
                <BottomSheetBackdrop
                    {...props}
                    disappearsOnIndex={-1}
                    appearsOnIndex={0}
                />
            )}
            onDismiss={() => props.setVisible(false)}
        >
            <View>
                <View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}}>
                    <Text>A Realm Reborn</Text>
                    <Switch
                        ios_backgroundColor="#3e3e3e"
                        value={props.filter.dlc[2]}
                        onValueChange={(switchValue) => setNewSwitchValue(2, switchValue)}
                    />
                </View>
            </View>
        </BottomSheetModal>
    )
}
```

**Comment by daavidkllr** [comment]
I could experience the same problem on IOS, also with SDK version 44.
The BottomSheetModal gets automatically hidden if the parent gets re-rendert. In my scenario the re-render was caused by toggling the device theme between dark/light mode.

With SDK version 43 everything works fine.

**Comment by ashish-hiverhq** [comment]
getting the same issue

**Comment by Engazan** [comment]
btw when i EJECTED expo and run app its fixed so it looks like its EXPO dev client problem only but i may be wrong here

**Comment by He1nr1chK** [comment]
I am using SDK 43 but also having this problem

**Comment by He1nr1chK** [comment]
It does, however, only happen in dev mode. When I run the app in release the bug does not appear to be present.

**Comment by gorhom** [comment]
im tracking this issue with the expo team, thanks for testing 
https://github.com/expo/expo/issues/15681

**Comment by josehernandezv** [comment]
I'm getting the same issue and I'm not using expo

**Comment by Engazan** [comment]
> im tracking this issue with the expo team, thanks for testing [expo/expo#15681](https://github.com/expo/expo/issues/15681)

i tried making my own simple Modal to try reproduce it and it seems its REANIMATED 2.3 issue, already posted it as issue in reanimated github, i tried with EXPO and pure RN without expo it seems like "useAnimatedStyle" problem 

https://github.com/software-mansion/react-native-reanimated/issues/2836

**Comment by dortamiguel** [comment]
I get the same issue

**Comment by hirbod** [comment]
Was about to post the issue, cause I also faced this issue when appearance triggers a re-render (context is around BottomSheetModal) which cause my modal to disappear

**Comment by hirbod** [comment]
I was hoping that this PR will fix the issue: https://github.com/software-mansion/react-native-reanimated/pull/2580 but unfortunately, not... As soon as I call a `setState`, my modal just hides out. Same happens when the modal rerenders due to darkmode/lightmode listener changes

@gorhom any chance for you to have a look at this?

**Comment by hirbod** [comment]
As this is a pretty heavy issue I had to come along with a workaround for now, because we can't update a simple state, here some helpful insights how to "workaround" for now.

I've memoized my sheet return with `useMemo()`. This will prevent real time appearance updates while the sheet is open but It will at least prevent a simple disappear.

In order to update states and components, I had to make sure not updating from the parent directly (passing down props).
Instead, I created children components and assigned a ref with `useImperativeHandle` and `forwardRef` and I trigger updates from the parent without re-rendering. As long as only the child updates, nothing bad happens.

This is a pretty bad pattern and some extra work, but I could fix my stuff for now.

**Comment by peterferguson** [comment]
> As this is a pretty heavy issue I had to come along with a workaround for now, because we can't update a simple state, here some helpful insights how to "workaround" for now.
> 
> I've memoized my sheet return with `useMemo()`. This will prevent real time appearance updates while the bottom is open but It will at least prevent a simple disappear.
> 
> In order to update states and components, I had to make sure not updating from the parent directly (passing down props). Instead, I created children components and assigned a ref with `useImperativeHandle` and `forwardRef` and I trigger updates from the parent without re-rendering. As long as only the child updates, nothing bad happens.
> 
> This is a pretty bad pattern and some extra work, but I could fix my stuff for now.

@hirbod Do you have a small snippet of the workaround? 

I am getting a problem where my contexts are not being passed into the modal and if I pass the state as props then my modal except for the backdrop, so I think the two must be related to this problem.

**Comment by hirbod** [comment]
@peterferguson yes they are related. I also had to register my ref outside of the component with `createRef` and import it instead of `useRef` inside of the component. Without this approach, my bottom sheet ref was null/undefined as soon as the bottom sheet re-rendered. (couldn't dismiss()/present())

All of my workarounds are hacky, but I need to move forward and can't wait for a fix, thats why I had to come up with some ugly solutions. Basically, if a child component of mine needs a update, I do it with a `imperativeHandle` instead of  `useState`. So I am not passing down props to the child directly, but I am triggering from the outside to only update the child component. I had to basically split everything up into small components.

https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by ghadeeraqraa1992** [comment]
The same issue we have,
any update on this ?

**Comment by Taher-Dweikat-Mappo** [comment]
I am facing the same problem, but without expo.
Any updates?

**Comment by Engazan** [comment]
> I am facing the same problem, but without expo.
> 
> Any updates?

Pull request was rejected so i think we need wait another weeek or 2 

https://github.com/software-mansion/react-native-reanimated/pull/2580

**Comment by hirbod** [comment]
The PR did not fix the issue either

**Comment by Taher-Dweikat-Mappo** [comment]
It seems that the problem is from react-native-reanimated V2.3. I had react-native-reanimated V2.3 and when I downgraded it to V2.2.0 the problem of the BottomSheetModal has been resolved and now it is working fine.

**Comment by dortamiguel** [comment]
For me V2.2.0 doesn't work, I get this error

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
at node_modules/@gorhom/bottom-sheet/src/components/bottomSheetModal/BottomSheetModal.tsx:166:16 in requestAnimationFrame$argument_0
```

**Comment by dlombardi** [comment]
Dealing with this issue as well.  The bottom sheet is hiding with any state update from the parent.  Would be great if we could get working soon as it's a pretty show-stopping bug. Thank you @gorhom

**Comment by dlombardi** [comment]
Also to note: this is not limited to Expo Go.  I'm also seeing this in the Expo Development Client.  I'm also not seeing that the issue you linked that you were tracking with Expo is representative of what we're discussing in this thread 

> im tracking this issue with the expo team, thanks for testing
expo/expo#15681

**Comment by Engazan** [comment]
so easy fix for me right now is FORCING ```"react-native-reanimated": "2.3.0"``` for now with 2.3.0 it happends 2 time of 100 for me ( acceptable )

**Comment by hirbod** [comment]
@dlombardi it is most likely linked to https://github.com/software-mansion/react-native-reanimated/pull/2580 but I couldn't verify it (I installed that branch and the error persisted for me)

**Comment by hirbod** [comment]
Looks like there is a new draft:
https://github.com/software-mansion/react-native-reanimated/pull/2851

Looks promising and might fix this issue, need to test and verify it.

**Comment by Engazan** [comment]
> Looks like there is a new draft:
> 
> https://github.com/software-mansion/react-native-reanimated/pull/2851
> 
> 
> 
> Looks promising and might fix this issue, need to test and verify it.

Tested for me it works perfect 


If somewant want for now hot fix there is it just Replace your package and then run ```yarn``` then ```expo start --clear```


```"react-native-reanimated": "github:software-mansion/react-native-reanimated#@piaskowyk/initial-style-shared"```

**Comment by hirbod** [comment]
@Engazan this will only work for folks with a custom dev client though. And this will need a `expo prebuild --clean`.

**Comment by gorhom** [comment]
i have tested https://github.com/software-mansion/react-native-reanimated/pull/2851 and it is going to fix this issue

**Comment by blurrypiano** [comment]
An alternative workaround that's working for me is to use [npm patch-package](https://www.npmjs.com/package/patch-package) and here's the patch file https://pastebin.com/SzwLNgbb

**Comment by search654321** [comment]
no news on this?

**Comment by hirbod** [comment]
@search654321 no, the issue has still not being merged and released at react-native-reanimated. Not sure what is holding back..

@blurrypiano patch is working fine though. Just make sure you install react-native-reanimate 2.3.1 and add the patchfile into your patches folder and let yarn do its magic for now. Rebuild your project afterwards (or run expo prebuild --clean when using a custom dev client)

**Comment by Amnesthesia** [comment]
Damn, I've been trying to solve this for months now. I had this issue for a while on 43 but tweaking the versions of `react-native-redash` and `react-native-reanimated` seemed to have fixed it for quite some time.

Making sure absolutely every callback and every object passed to the sheet and anything inside it is memoized with `useMemo` seemed to have been a solution, until I had a sheet with state from redux in it where I would have a step 1 and step 2 kind of form — as soon as that redux state causes the parent to re-render, the sheet closes. **But** it doesn't fire any events for it, so no other component is aware of the sheet being closed and it can't be opened again. :(

**Comment by hirbod** [comment]
Because its not being closed @Amnesthesia, its just the wiped styled that make it appear closed.
Unfortunately, the PR has regressions and won't be merged and we need to wait for a "real solution" fixed on the native side.

**Comment by masiamj** [comment]
@hirbod Thanks for all your work and diligence staying up on this issue. I also saw [your involvement in the root cause bug](https://github.com/software-mansion/react-native-reanimated/pull/2851#issuecomment-1066590058) in `react-native-reanimated`. Do you have thoughts on when the root cause fix will be merged?

Thanks all for your work here 👍

**Comment by hirbod** [comment]
@masiamj soon. The PR is ready, I guess it just needs a final review and some more tests.
You can try it now

```bash
yarn add software-mansion/react-native-reanimated#refs/pull/2851/head
```

You will need to install pods afterwards (in case you're using expo with a custom-dev-client, just run `expo prebuild --clean`)

The PR is based on v2.4.1

**Comment by hirbod** [comment]
At all. It is finally fixed.
You need to upgrade `react-native-reanimated` to v2.5.0.

**Comment by inthisar-hamza** [comment]
Hey, this issue is still present in `react-native-bottom-sheet`, when I call dispatch (redux) it auto closing the bottom sheet. 
Can anyone explain why this happens and give a possible solution?
"@gorhom/bottom-sheet": "4",
"react-native-reanimated": "^2.13.0",

@hirbod react-native-reanimated to v2.5.0 gives gradle build error 
A problem occurred evaluating project ':react-native-reanimated'.
> Could not get unknown property 'rnMinorVersion' for project ':react-native-reanimated' of type org.gradle.api.Project.

**Comment by AndrewLutsenko** [comment]
Still not work guys @hirbod @dortamiguel @gorhom 

"react-native": "0.71.5",
"react-native-reanimated": "^3.0.2"
 "@gorhom/bottom-sheet": "^4.4.5",

**Comment by olegkhorev** [comment]
I have similar issue. I use now - it has similar options
https://ui.gorhom.dev/components/bottom-sheet/usage

`import BottomSheet from '@gorhom/bottom-sheet';`

instead of
```
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';

```
I display bottom sheet always and I don't need to close it. But it can be closed/opened also if you learn manual.

It works very well for me now.
