### ISSUE TITLE
[v2] Cannot able to disable handler

### ISSUE THREAD

**Issue by vinitgundeti** [gorhom/react-native-scroll-bottom-sheet#804]
# Bug

Cannot able to disable handler. I want to disable the handler because it is showing separation between the child component because of background color.
![Screenshot_1641477916](https://user-images.githubusercontent.com/47896506/148398390-55187681-e457-4b06-8e7b-70abe6073ae5.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 2.4.1   |
| react-native                    | 0.62.2  |
| react-native-reanimated         | 1.3.0   |
| react-native-gesture-handler    | 1.5.3   |

**Comment by mostafabrazi** [comment]
Actually it's not a bug, I make it works by adding 

```javacript
handleComponent={null}
```

to the bottomsheet, but you will lose the border radius for the view
