### ISSUE TITLE
BottomSheetTextInput partially hides under the keyboard when at the bottom of the Page

### ISSUE THREAD

**Issue by vlack-coder** [gorhom/react-native-scroll-bottom-sheet#806]
# Bug

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.2  |

## Steps To Reproduce
[Link to Snack](https://snack.expo.dev/@vlack-coder/bottom-sheet-v4-reproducible-issue-template)

**Describe what you expected to happen:**

BottomSheetTextInput should completely be visible and be on top of the keyboard

**Reproducible Code**
[Link to Snack Expo code](https://snack.expo.dev/@vlack-coder/bottom-sheet-v4-reproducible-issue-template)

## Video

https://user-images.githubusercontent.com/56041655/148642055-85a60811-c6dc-4571-b3e4-2fbd0452420c.mp4

**Comment by statnyk** [comment]
@vlack-coder , did you manage to fix the bug? i have same problem in my project on Android devices

**Comment by vlack-coder** [comment]
> Open

@statnyk @jcgertig @likern  @vonovak   No, I was not able to fix it... I tried using keyboard avoiding view but it was not consistent across different android devices so I used another library...
Please if you come across any fix, you can always drop it here, Thanks

**Comment by statnyk** [comment]
@vlack-coder , what library did you use?
