### ISSUE TITLE
[v4]  Adding index={-1} in certain devices blocks the view (Example device: Oneplus 5)

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [gorhom/react-native-scroll-bottom-sheet#807]
# Bug

In certain devices like the [OnePlus 5](https://www.oneplus.in/support/spec/oneplus-5), adding an `index={-1}` is causing the entire screen to be non-functional, i.e, we're unable to click anywhere on the screen. If we remove this prop, then everything seems to be working fine. But of course we need the BottomSheet to be in closed state initially, hence not adding this prop is not a solution.
But this does work fine on other devices we've tested. 

This issue is affecting many users in Production, since we're using BottomSheet in many screens and the Users are unable to use those screens.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.2  |
| react-native-reanimated         | 2.2.4  |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

In certain devices only :
Add an index={-1} in the BottomSheet is causing the entire screen to be non-functional. It is as though there's an overlay on top of the screen which doesn't let us access whatever is currently rendered.

Describe what you expected to happen:

It should not render the screen non-functional.

## Reproducible sample code

```import BottomSheetGorhom, { BottomSheetBackdrop } from '@gorhom/bottom-sheet';
import React, { useCallback } from 'react';
import { StyleSheet, Keyboard } from 'react-native';
import PropTypes from 'prop-types';
import { bottomSheetHeaderHandler } from 'colors';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

const renderBackdrop = props => (
  <BottomSheetBackdrop {...props} disappearsOnIndex={-1} appearsOnIndex={0} />
);

const BottomSheet = React.forwardRef((props, ref) => {
  const { children, onChange, ...restProps } = props;

  const handleChange = useCallback(index => {
    if (index === -1) {
      // When the BottomSheet is closed, dismiss any open Keyboard
      Keyboard.dismiss();
    }
    // Call the actual onChange handler passing in the index
    onChange?.(index);
  }, []);

  return (
    <BottomSheetGorhom
      index={-1}
      enablePanDownToClose
      backdropComponent={renderBackdrop}
      handleIndicatorStyle={styles.handleIndicatorStyle}
      ref={ref}
      onChange={handleChange}
      {...restProps}
    >
      {children}
    </BottomSheetGorhom>
  );
});

const styles = StyleSheet.create({
  handleIndicatorStyle: {
    width: wp('12.6%'),
    height: hp('0.65%'),
    borderRadius: 4,
    backgroundColor: bottomSheetHeaderHandler,
  },
});

BottomSheet.propTypes = {
  children: PropTypes.node,
  onChange: PropTypes.func,
};

export default BottomSheet;

**Comment by vinkim** [comment]
I looked into this issue a bit myself on my Samsung S8+ device that is able to reproduce this issue.

In the **BottomSheetBackDrop** component you have the following code.

```
  //#region effects
  useAnimatedReaction(
    () => animatedIndex.value <= disappearsOnIndex,
    (shouldDisableTouchability, previous) => {
      if (shouldDisableTouchability === previous) {
        return;
      }
      runOnJS(handleContainerTouchability)(shouldDisableTouchability);
    },
    [disappearsOnIndex]
  );
  //#endregion
```

Which will call into **handleContainerTouchability**  and set the **pointerEvents** prop.

```
  const handleContainerTouchability = useCallback(
    (shouldDisableTouchability: boolean) => {
      if (!containerRef.current) {
        return;
      }
      // @ts-ignore
      containerRef.current.setNativeProps({
        pointerEvents: shouldDisableTouchability ? 'none' : 'auto',
      });
    },
    []
  );
```

On my Samsung Galaxy S8+ the **animatedIndex.value** is reported as:
```
 // Samsung
 LOG  [ SM-G955F ] animatedIndex.value:  -1
 LOG  [ SM-G955F ] animatedIndex.value:  -0.9999999548556524
 // Simulator
 LOG  [ Android SDK built for x86 ] animatedIndex.value:  -1
 LOG  [ Android SDK built for x86 ] animatedIndex.value:  -1
```

As seen above, the **animatedIndex.value <= disappearsOnIndex** ( -0.9999999548556524 <= -1 ) will result in **false**, and the pointerEvents will be set to 'none', and the input will be blocked.

**Comment by Vi-dot** [comment]
Based on what @vinkim said,
This patch seems to work, but tested only for one snap point.
```diff
node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
@@ -95,14 +95,14 @@ const BottomSheetBackdropComponent = ({
 
   //#region effects
   useAnimatedReaction(
-    () => animatedIndex.value <= disappearsOnIndex,
+    () => !(animatedIndex.value >= appearsOnIndex),
     (shouldDisableTouchability, previous) => {
       if (shouldDisableTouchability === previous) {
         return;
       }
       runOnJS(handleContainerTouchability)(shouldDisableTouchability);
     },
-    [disappearsOnIndex]
+    [appearsOnIndex]
   );
   //#endregion
 
```

**Comment by omar-diop** [comment]
I encountered the same problem: on some Xiaomi or Samsung device the whole screen becomes freezed.

The only workaround i found is to set index={0} and provide a 0 snap point that has 0 height like the following:

```
const snapPoints = useMemo( () => ( [0, "60%", "80%"] ), [], );
<BottomSheet
      ref={ensureRef}
      index={Platform.OS === "android" ? 0 : -1}
      snapPoints={snapPoints}
      backdropComponent={BottomSheetBackdrop}
      backgroundComponent={() => <View style={styles.background} />}
      onChange={handleSheetChange}>
     {...children}
    </BottomSheet>
```

**Comment by marco2216** [comment]
We also had this issue in production, it's also very tricky to debug. The patch fix seems to work for us. Could this change work @gorhom ?

**Comment by aditya-keri-betterhalf** [comment]
@gorhom - Any update on adding this patch in your next release ?
It's affecting many devices we've tested on.

**Comment by marco2216** [comment]
Still an issue

**Comment by abdelhameedhamdy** [comment]
Still an issue

**Comment by aditya-keri-betterhalf** [comment]
@gorhom - Could you please let me know if this issue is fixed ?
Others have also faced this issue.

**Comment by aditya-keri-betterhalf** [comment]
@gorhom - Posting this again because I'm still not sure if this issue has been fixed in the latest release ?
Like you can see, others have the same issue. So would appreciate your response on this.

**Comment by kirillpuzanov** [comment]
in my case it went like this

```
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
index 2446c1d..778564c 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
@@ -104,7 +104,7 @@ const BottomSheetBackdropComponent = ({
 
   //#region effects
   useAnimatedReaction(
-    () => animatedIndex.value <= disappearsOnIndex,
+    () => Math.floor(animatedIndex.value) <= disappearsOnIndex,
     (shouldDisableTouchability, previous) => {
       if (shouldDisableTouchability === previous) {
         return;
```

**Comment by dhavalbetterhalf** [comment]
i resolved the issue by providing default pointerEvents value 

``` diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
index 69db946..88f974f 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
@@ -117,6 +117,7 @@ const BottomSheetBackdropComponent = ({
         accessibilityHint={`Tap to ${
           typeof pressBehavior === 'string' ? pressBehavior : 'move'
         } the Bottom Sheet`}
+        pointerEvents="none"
       >
         {children}
       </Animated.View>

**Comment by dhavalbetterhalf** [comment]
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> index 2446c1d..778564c 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> @@ -104,7 +104,7 @@ const BottomSheetBackdropComponent = ({
>  
>    //#region effects
>    useAnimatedReaction(
> -    () => animatedIndex.value <= disappearsOnIndex,
> +    () => Math.floor(animatedIndex.value) <= disappearsOnIndex,
>      (shouldDisableTouchability, previous) => {
>        if (shouldDisableTouchability === previous) {
>          return;

its work for me as well 
Thanks

**Comment by RobertSasak** [comment]
This issue seems to occur because of mixing two threads worlds. UI vs JS. Perhaps it can all be done by worklets. I found [useAnimatedProps](https://docs.swmansion.com/react-native-reanimated/docs/next/api/hooks/useAnimatedProps) should be doing exactly this. So I came up with following code. It seems to work on iOS and Android. However it does not work on web.  PointerEvents is not changed at all.

Can any of you with "buggy" phones test this solution?
Do you have any thoughts how to make it work on web?
```ts
  //#region effects

  // Better/simplier implementation
  const animatedProps = useAnimatedProps<{
    pointerEvents: ViewProps['pointerEvents'];
  }>(
    () => ({
      pointerEvents: animatedIndex.value <= disappearsOnIndex ? 'none' : 'auto',
    }),
    [animatedIndex, disappearsOnIndex]
  );

   // Old one for reference
  useAnimatedReaction(
    () => animatedIndex.value <= disappearsOnIndex,
    (shouldDisableTouchability, previous) => {
      if (shouldDisableTouchability === previous) {
        return;
      }
      runOnJS(handleContainerTouchability)(shouldDisableTouchability);
    },
    [disappearsOnIndex]
  );
  //#endregion
```
And it can be use like this
```tsx
<TapGestureHandler onGestureEvent={gestureHandler}>
      <Animated.View
        style={containerStyle}
        animatedProps={animatedProps} <- added this line and removed ref
        accessible={true}
        accessibilityRole="button"
        accessibilityLabel="Bottom Sheet backdrop"
        accessibilityHint={`Tap to ${
          typeof pressBehavior === 'string' ? pressBehavior : 'move'
        } the Bottom Sheet`}
      >
        {children}
      </Animated.View>
    </TapGestureHandler>
```

**Comment by janroures** [comment]
this is still happening on v.4.4.5

**Comment by Alaa-Ben** [comment]
Still an issue !

**Comment by Alaa-Ben** [comment]
> This issue seems to occur because of mixing two threads worlds. UI vs JS. Perhaps it can all be done by worklets. I found [useAnimatedProps](https://docs.swmansion.com/react-native-reanimated/docs/next/api/hooks/useAnimatedProps) should be doing exactly this. So I came up with following code. It seems to work on iOS and Android. However it does not work on web. PointerEvents is not changed at all.
> 
> Can any of you with "buggy" phones test this solution? Do you have any thoughts how to make it work on web?
> 
> ```ts
>   //#region effects
> 
>   // Better/simplier implementation
>   const animatedProps = useAnimatedProps<{
>     pointerEvents: ViewProps['pointerEvents'];
>   }>(
>     () => ({
>       pointerEvents: animatedIndex.value <= disappearsOnIndex ? 'none' : 'auto',
>     }),
>     [animatedIndex, disappearsOnIndex]
>   );
> 
>    // Old one for reference
>   useAnimatedReaction(
>     () => animatedIndex.value <= disappearsOnIndex,
>     (shouldDisableTouchability, previous) => {
>       if (shouldDisableTouchability === previous) {
>         return;
>       }
>       runOnJS(handleContainerTouchability)(shouldDisableTouchability);
>     },
>     [disappearsOnIndex]
>   );
>   //#endregion
> ```
> 
> And it can be use like this
> 
> ```tsx
> <TapGestureHandler onGestureEvent={gestureHandler}>
>       <Animated.View
>         style={containerStyle}
>         animatedProps={animatedProps} <- added this line and removed ref
>         accessible={true}
>         accessibilityRole="button"
>         accessibilityLabel="Bottom Sheet backdrop"
>         accessibilityHint={`Tap to ${
>           typeof pressBehavior === 'string' ? pressBehavior : 'move'
>         } the Bottom Sheet`}
>       >
>         {children}
>       </Animated.View>
>     </TapGestureHandler>
> ```

@RobertSasak  It's a simpler implementation but it doesn't seem to fix the core problem: animatedIndex.value <= disappearsOnIndex
The thing with with this bug is that for example: animatedIndex.value: -0.9999999579116011 and disappearsOnIndex: -1
so the inequality is still true with your implementation 🤔

**Comment by RobertSasak** [comment]
@Alaa-Ben I see the issue. For some reason it does not occur as when it is implemented other way around. 
BTW: I made PR for pointer-events for web and it was released as 4.4.4 and then broked again in 4.4.5.

**Comment by Alaa-Ben** [comment]
@RobertSasak  Thanks ! (i'm not using the web version btw, but thanks for your efforts !)
Do you have some insights about the inequality issue ?
A few workarounds would be flooring values or adding a very small delta (0.00001 for eg), but this doesn't seem very robust.. :/

**Comment by emilhdiaz** [comment]
@gorhom This appears to be affecting other Android devices like Google's flagship Pixel phones (reproducible on the Pixel 5 and Pixel 7 Pro so far). 

@omar-diop's work-around no longer works as the library prohibits the using `0` as a snap point: 

https://github.com/gorhom/react-native-bottom-sheet/blob/991d2141a4f026068737abc098f9b0d2b6968a5f/src/hooks/usePropsValidator.ts#L33

Another temporary work-around is to set the first snap point to a very small number (e.g. `1`), set the BottomSheetBackdrop pressBehavior to `close`, and control the BottomSheet index programmatically to open on the second snap point: 

```
const [isOpen, setIsOpen] = React.useState<boolean>(false)
const snapPoints = useMemo( () => ( [1, "60%", "80%"] ), [], );
return (
  <BottomSheet
      ref={ensureRef}
      index=.isOpen ? 1 : -1}
      snapPoints={snapPoints}
      backdropComponent={(props: BottomSheetBackdropProps) => (
         <BottomSheetBackdrop {...props} pressBehavior="close" />
      )}
     {...children}
  </BottomSheet>
)
```

**Comment by alexandreaugus** [comment]
+1

**Comment by CoSNaYe** [comment]
This issue happens with `"@gorhom/bottom-sheet": "4.4.5"` at Xiaomi s10

@emilhdiaz 's solution works, but could we possibly reopen this issue to properly solve it

**Comment by ctriantaf** [comment]
Any updates on this?

**Comment by whyamsx** [comment]
To everyone who has encountered this problem today, I suggest looking at your version of `react-native-reanimated`, this problem appears on version `react-native-reanimated@^3` and disappears if you use version `react-native-reanimated@^2`

**Comment by emilhdiaz** [comment]
@whyamsx I'm using `react-native-reanimated@~2.12.0` and still experiencing this issue

**Comment by claudiutwin** [comment]
Having same problems, any updates?

**Comment by margreen94** [comment]
I am still seeing an issue on some Android devices (Pixel 9, Android 16) where it appears like the screen "freezes" due to the backdrop component. This is specifically on a simulator device with "Remove Animations" turned on. [This](https://github.com/gorhom/react-native-bottom-sheet/issues/807#issuecomment-1160423008) patch fix worked for me but want to see if anyone had another long term solution? Is anyone else still seeing this? Would a PR be the best path forward? 

`"@gorhom/bottom-sheet": "^5.0.6"`
`"expo": "~52.0.27"`
`"react-native": "^0.77.2"`
`"react-native-reanimated": "^3.17.5"`

**Comment by gorhom** [comment]
could you provide a sample code using this template https://snack.expo.dev/@gorhom/bottom-sheet---issue-reproduction-template

**Comment by margreen94** [comment]
@gorhom  I am seeing an issue with the snack like [this](https://github.com/gorhom/react-native-bottom-sheet/issues/2131). But, the issue I am seeing is the same as these other issues ([807](https://github.com/gorhom/react-native-bottom-sheet/issues/807), [1882](https://github.com/gorhom/react-native-bottom-sheet/issues/1882), [527](https://github.com/gorhom/react-native-bottom-sheet/issues/527), [566](https://github.com/gorhom/react-native-bottom-sheet/issues/566)) and can be recreated with code similar to [below](https://github.com/gorhom/react-native-bottom-sheet/issues/566#issuecomment-924063201):  



```javascript
<BottomSheet
    ref={bottomModalSheetRef}
    index={-1}
    animationConfigs={animationConfigs}
    snapPoints={["55%"]}
    detached={false}
    enablePanDownToClose={true}
    enableContentPanningGesture={true}
    overDragResistanceFactor={4}
    topInset={insets.top}
    backdropComponent={(bdProps) => (
      <BottomSheetBackdrop
          {...bdProps}
          appearsOnIndex={0}
          disappearsOnIndex={-1}
          opacity={0.4}
          enableTouchThrough
      />
    )}
    backgroundStyle={{ backgroundColor: "white" }}
>
  <BottomSheetView style={styles.container}>
    <SortPickerContent
       setSortType={setSortType}
       sortType={sortType}
       handleBottomSheetClose={handleBottomSheetClose}
    />
  </BottomSheetView>
</BottomSheet>


...


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
});
``` 

Also, I am only seeing this on some Android devices with Reduced Animations "on".

**Comment by antek-p** [comment]
Still an issue

**Comment by hehooleehoo** [comment]
For anybody stumbling across this...

I hope you didn't spend days hunting the issue like we did... 

The root of the issue appears to be the useAnimatedReaction hook in the BottomSheetBackdrop.tsx component.

At the time of my writing, there are attempts like [this](https://github.com/gorhom/react-native-bottom-sheet/pull/2342) to fix the issue.

In the meantime you may want to recreate the BottomSheetBackDrop file yourself with a hotfix applied: (credit to [aarontuftss](https://github.com/aarontuftss))

```tsx
// BottomSheetBackDrop.tsx
 const EPSILON = 0.001

  useAnimatedReaction(
    () => animatedIndex.value <= (disappearsOnIndex + EPSILON),
    (shouldDisableTouchability, previous) => {
      if (shouldDisableTouchability === previous) {
        return;
      }
      runOnJS(handleContainerTouchability)(shouldDisableTouchability);
    },
    [disappearsOnIndex]
  );

```

**Comment by calvinkei** [comment]
This is the trickiest bug I have ever seen. only happen on certain devices (Samsung S23 Ultra, some Xiaomi phones). I thought the app freezes because JS thread is overloaded, or expo-router is problematic (issue only happens on certain routes)

Turns out it's the bottom sheet blocking the whole view.

And I believe we should reopen the issue since it's still happening on v5.2.8

Patched this with @hehooleehoo 's suggestion. Thank you so much. you saved my production app and 1000's of users using those devices

**Comment by IanMolldrem** [comment]
@gorhom could we reopen this issue given it's reproducible on the latest version, there are open PRs to fix it, and a [patch](https://github.com/gorhom/react-native-bottom-sheet/issues/807#issuecomment-3462246366) that works for several people?

**Comment by murat0** [comment]
This issue absolutely warrants a formal reopening, as the underlying technical complexities remain unresolved and continue to present a significant hurdle for users. The fact that this bug is consistently reproducible on high-end, flagship hardware like the Samsung Galaxy S23 Ultra elevates it from a minor inconvenience to a critical performance concern that affects a massive segment of the active user base.

**Comment by antek-p** [comment]
I can confirm that this issue is critical as it affects a lot of devices (Pixel 7 for example among all mentioned), patch proposed by community is working & fix the frozen app.

**Comment by margreen94** [comment]
Confirming that this is still a critical issue. Please consider reopening this issue and/or merging this PR https://github.com/gorhom/react-native-bottom-sheet/pull/2342
