### ISSUE TITLE
[v4] | Unable to apply paddingBottom to BottomSheetFlatlist when keyboard is closed

### ISSUE THREAD

**Issue by KROSF** [gorhom/react-native-scroll-bottom-sheet#808]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 6.0.6   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create a BottomSheet view with BottomSheetModal > BottomSheetView > BottomSheetFlatList
2. Try  if paddingBottom works when keyboard is closed

Describe what you expected to happen:

1. the paddingBottom gets applied to BottomSheetFlatList when keyboard is closed add snap point is 75%

## Reproducible sample code

https://snack.expo.dev/@krosf/bottom-sheet-v4-reproducible-issue-template

https://user-images.githubusercontent.com/24454660/148811902-0215f6f8-a6f9-43cc-8fea-15302facfc8e.mp4

**Comment by misfits91** [comment]
@KROSF did you solve this?
