### ISSUE TITLE
[v4] Bottom sheet modal 'keyboardBehavior={'extend'}' with 'keyboardBlurBehavior={'restore'}' causes unexpected blur behavior.

### ISSUE THREAD

**Issue by peterhuijsen** [gorhom/react-native-scroll-bottom-sheet#811]
# Bug

When using multiple snap points and setting 'keyboardBehavior' to 'extend' and 'keyboardBlurBehavior' to 'restore' causes the modal to snap to the highest snap point instead of the snap point that it originally snapped to.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.2.3  |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Create a bottom sheet modal with a TextInput component.
2. Add multiple snappoints. 
3. Set 'keyboardBehavior' to 'extend' and 'keyboardBlurBehavior' to 'restore' in its props.
4. Focus the TextInput and blur it.

## Expected behavior

I would expect the sheet to restore to the snap point that was used before the sheet's focus behavior.

## Reproducible sample code

https://snack.expo.dev/@yawm/bottom-sheet-v4-reproducible-issue

**Comment by filippobarcellos** [comment]
Still happening. Does anyone know how to solve?
