### ISSUE TITLE
How to overlap the backdrop over StatusBar?

### ISSUE THREAD

**Issue by MrPhyaeSoneThwim** [gorhom/react-native-scroll-bottom-sheet#813]
I am now using a BottomSheetModal by wrapping it inside the BottomSheetModalProvider. The Backdrop is working fine but it doesn't overlap the StatusBar. Can you please give me any ideas for that.

![Screenshot_2022-01-16-23-37-05-715_com budgety](https://user-images.githubusercontent.com/83585609/149670271-4ba18bd1-ae4b-41e4-9511-7c7e92234be3.jpg)

```
<BottomSheetModal
      ref={bottomSheetRef}
      enablePanDownToClose={true}
      backdropComponent={renderBackdrop}
      snapPoints={animatedSnapPoints}
      handleHeight={animatedHandleHeight}
      contentHeight={animatedContentHeight}>
      <BottomSheetView
          style={contentContainerStyle}
          onLayout={handleContentLayout}>
          <Text>Hello world</Text>
      </BottomSheetView>
</BottomSheetModal>
```

The above code is how did I implement for bottom sheet. And the following one is the renderBackdrop function.

```
const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        disappearsOnIndex={-1}
        appearsOnIndex={0}
        {...props}
      />
    ),
    [],
);
```

**Comment by ronickg** [comment]
Also have the same issue. Haven't found a way to fix it yet either :/

**Comment by michaelheide** [comment]
I had the Same issue, when i was using the SafeAreaView.

As a workaround u just take a normal View. But now you have to care about your safearea on your own. But the backdrop is now in full height.

**Comment by hizbullaharif** [comment]
also this but not yet solved

**Comment by farellsujanto** [comment]
+1 not yet solved since a long time, not that urgent but aesthetically not that good on the eye

**Comment by anazaim77** [comment]
I'm also facing the same problem

**Comment by agestaun** [comment]
The same +1

**Comment by SamehArmouche** [comment]
Any one has been solved?

**Comment by Saujanmgr** [comment]
@SamehArmouche, have you tried adding a <StatusBar /> component inside the component where BottomSheet is used and make StatusBar to translucent and background to transparent.

`<View style={props.viewState === 'open' ? {flex:1, height:'100%', width:'100%', position:'absolute', top:0, elevation:20} : {}}>
       <StatusBar translucent backgroundColor="transparent"/>
       <BottomSheet
        backdropComponent={renderBackdrop} ref={bottomSheetRef} index={2} snapPoints={snapPoints}
        onChange={handleSheetChange}
        enablePanDownToClose
        onClose={()=>props.handleBottomSheetView('close')} >
         <BottomSheetView>
          <Text>Awesome 🔥</Text>
        </BottomSheetView>
      </BottomSheet>
    </View>`

**Comment by baesumin** [comment]
+1

**Comment by caixingyue** [comment]
use react-native-portalize, can solve your problem

**Comment by ibovegar** [comment]
This is still an issue.

**Comment by ceshm** [comment]
A workaround I did the works decently well is add a StatusBar inside of the BackdropComponent with a backgroundColor that matches the BackdropComponent color:

```typescript
import React, { useMemo } from "react";
import { BottomSheetBackdropProps } from "@gorhom/bottom-sheet";
import Animated, {
  Extrapolation,
  interpolate,
  useAnimatedStyle,
} from "react-native-reanimated";
import { StatusBar } from "react-native";

const CustomBackdrop = ({ animatedIndex, style }: BottomSheetBackdropProps) => {
  // animated variables
  const containerAnimatedStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      animatedIndex.value,
      [-1, 1],
      [0, 1],
      Extrapolation.CLAMP
    ),
  }));

  // styles
  const containerStyle = useMemo(
    () => [
      style,
      {
        backgroundColor: "rgba(0,0,0,.5)",
      },
      containerAnimatedStyle,
    ],
    [style, containerAnimatedStyle]
  );

  return (
    <Animated.View style={containerStyle}>
      <StatusBar backgroundColor="rgba(0,0,0,.24)" animated={true} />
    </Animated.View>
  );
};

export default CustomBackdrop;
```

Note that setting the statusBar prop animated also makes it look nicer

**Comment by idanlevi1** [comment]
@ibovegar  @MrPhyaeSoneThwim 
You can use minimal opacity in the status bar to solve it:
``` 
useEffect(() => {
    props.navigation.setOptions({
      statusBarColor: 'rgba(255,255,255, 0)',
    });
 }, []);
  ```

**Comment by MuazzezA** [comment]
> @SamehArmouche, have you tried adding a component inside the component where BottomSheet is used and make StatusBar to translucent and background to transparent.
> 
> `<View style={props.viewState === 'open' ? {flex:1, height:'100%', width:'100%', position:'absolute', top:0, elevation:20} : {}}> <StatusBar translucent backgroundColor="transparent"/> <BottomSheet backdropComponent={renderBackdrop} ref={bottomSheetRef} index={2} snapPoints={snapPoints} onChange={handleSheetChange} enablePanDownToClose onClose={()=>props.handleBottomSheetView('close')} > <BottomSheetView> <Text>Awesome 🔥</Text> </BottomSheetView> </BottomSheet> </View>`

` <StatusBar translucent backgroundColor="transparent"/>`

Writing this code on the page where I used modal worked.

**Comment by epolat-github** [comment]
Making status bar translucent and transparent works on Android, but screen jumps when switching between non-translucent and translucent tab screens. Has anyone seen this problem? I'm using stack inside tab.

**Comment by ronickg** [comment]
For anyone having issues with this, using the rn edge to edge lib can also fix the problem: https://github.com/zoontek/react-native-edge-to-edge

**Comment by Poojaauma** [comment]
@epolat-github ,

Does it go back to normal statusBar color when the BottomSheet is closed?

**Comment by epolat-github** [comment]
@Poojaauma No, not automatically. I’m setting it manually when opening and closing the bottom sheet using `StatusBar.*`  However, the content and navigation header briefly jump to the very top of the screen before returning to their correct position.

**Comment by Poojaauma** [comment]
@epolat-github 

Can you please share the code here for reference?

**Comment by epolat-github** [comment]
```
StatusBar.setBackgroundColor("transparent", true);
StatusBar.setTranslucent(true);
```

And opposite when closing the sheet. But as I said, it makes the screen jump and at least for me, it's not usable.

**Comment by sayan-avantai** [comment]
In the react native modal a property is introduced which is **statusBarTranslucent**. In bottom sheet we need this property .

**Comment by alainib** [comment]
@sayan-avantai  is was using `react-native-modal` too but it's not updated since 3 years. migrating to gorhom but this is a blocker for me until i found a way to replace statusBarTranslucent

any fix for this ?

**Comment by imalgrab** [comment]
I fixed it by adding`<StatusBar/>` from `expo-status-bar` with `translucent` prop set to `true` to a wrapper displaying `<BottomSheetModal/>`:
```tsx
const CustomBottomSheet = () => {
  return (
    <>
      <StatusBar translucent />
      <BottomSheetModal ref={bsRef} {...props}>
        <BottomSheetView>...</BottomSheetView>
      </BottomSheetModal>
    </>
  );
};
```
And now it's working as expected for me:
```json
"@gorhom/bottom-sheet": "^5.0.6",
"react-native": "0.74.5",
"expo": "~51.0.39",
```

**Comment by Shrabya35** [comment]
For anyone still experiencing the issue, setting statusBarTranslucent={true} inside the Modal worked for me

` <Modal
  transparent
  animationType="fade"
  visible={showDeleteConfirm}
  onRequestClose={() => setShowDeleteConfirm(false)}
  statusBarTranslucent={true}
>
  {/* Modal content */}
</Modal>`

**Comment by Shrabya35** [comment]
For anyone still experiencing the issue, setting statusBarTranslucent={true} inside the Modal worked for me

```
 <Modal
  transparent
  animationType="fade"
  visible={showDeleteConfirm}
  onRequestClose={() => setShowDeleteConfirm(false)}
  statusBarTranslucent={true}
>
  {/* Modal content */}
</Modal>
```
