### ISSUE TITLE
[v4] | gesture-handler old API Warning and bottomsheet doesn't render

### ISSUE THREAD

**Issue by christian-hess-94** [gorhom/react-native-scroll-bottom-sheet#814]
# Bug

When adding a simple bottomsheet to my recently created app I'm greeted with a "using wrong gesture handler api" warning and the bottomsheet doesn't render.

Full warning message:
`[react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!`

This doesn't make sense as I'm following the documentation for both gesture-handler and react-native-bottomsheet and i'm using the latests version of both

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | 17.0.2  |
| react-native-reanimated         | ^2.3.1   |
| react-native-gesture-handler    | ^2.2.0   |

## Steps To Reproduce

1.Simply add and import everything in the "usage" documentation page:
```js
<BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={{ height: 200, backgroundColor: 'red', flex: 1 }}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>`
```

Describe what you expected to happen:

1. The botom sheet should appear at 50%, and no warning should appear

## Reproducible sample code
The code is in this repository and branch: https://github.com/christian-hess-94/keycash_challenge/tree/bottomsheet-bug

**Comment by hirbod** [comment]
This is not a bug, it's not even directly related to this library.
https://github.com/software-mansion/react-native-gesture-handler/pull/1817

Bottom Sheet was developed and released, while RNGH was at version 1.X. 
The new major bump introduced a new api but still supports the old API. Its more like a hint or an developer notification. 
I am sure Mo will migrate to the new API someday but it is not urgent. You can use LogBox to get rid of this warning.

**Comment by Ubaid0z** [comment]
did you find something, I'm facing same issue

**Comment by hirbod** [comment]
@Ubaid0z did you read my message? There is NO issue.

**Comment by christian-hess-94** [comment]
> o

Thanks for the reply @Hirbod, but I don't understand why the bottomsheet doesn't render. I'm following the documentation steps exactly, and I've tried this in two different repos and even with the previous release of react-native-bottomsheet.

The warning itself is pretty explanatory, the actual bug is the bottomsheet not rendering

**Comment by hirbod** [comment]
You could try to downgrade react-native-gesture-handler back to 2.1.1 and check if thats the root cause.

**Comment by billnbell** [comment]
2.2.0 must be missing the fix for 2.1.1

**Comment by billnbell** [comment]
[react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!

**Comment by christian-hess-94** [comment]
> You could try to downgrade react-native-gesture-handler back to 2.1.1 and check if thats the root cause.

I already did that, for some reason the same error appears

**Comment by naishe** [comment]
Ref: https://github.com/software-mansion/react-native-gesture-handler/issues/1831#issuecomment-1025256747

**Comment by mndaipre** [comment]
+1
