### ISSUE TITLE
Feat: passing data to present() and dismiss()

### ISSUE THREAD

**Issue by hirbod** [gorhom/react-native-scroll-bottom-sheet#815]
# Feature Request
I miss the possibility to send and receive data to the BottomSheet. Many modal sheets are not in context with each other and currently I have to work with event emitters. 

## Why it is needed
I use the sheets to show partial screens with settings, or to offer single/multiple choices. The modals are generic and are therefore not a coherent stack. So that I know, for example, after closing, which data has been selected, the passing of data would be very helpful. Currently I use EventListener for this.

## Possible implementation

The library should detect if it has an underlying sheet at all at dismiss and pass through the data if it does. If no further sheet opens after the dismiss, no data must be passed through. Passed data via present() or dismiss() should update the state, maybe using a hook.

### Code sample
```tsx
   bottomSheetRefNew.current.present({ data })
   bottomSheetRef.current.dismiss({ data })
```

**Comment by hirbod** [comment]
Not stale

**Comment by elmcapp** [comment]
Yes we need a method to to open and close BottomSheet from any file without using context. Some times we can not pass props. Maybe integrate a builtin Event listener

**Comment by hirbod** [comment]
Dear annoying Github Bot, its not stale :D

**Comment by hirbod** [comment]
Not stale, but coming soon anyway!

**Comment by khzouroussama** [comment]
this would be awesome +1

**Comment by hirbod** [comment]
It’s already available since 4.2.0

**Comment by mouricef** [comment]
Hi hirod,

Can you please help us with some code sample on how to use it

**Comment by zfanta** [comment]
@mouricef 
```ts
<BottomSheetModal {...yourProps}>
  {props => {
    console.log(props);
    return (
      <View style={styles.contentContainer}>
        <Text>Awesome 🎉</Text>
      </View>
    );
  }}
</BottomSheetModal>
```

**Comment by iraybi** [comment]
@zfanta , do you know how to access this data inside the footerComponent?

**Comment by khzouroussama** [comment]
You can use this approch @iraybi 

```jsx
<BottomSheetModal {...yourProps}>
  {props => {
    console.log(props);
    return (
      <View style={styles.contentContainer}>
          <BottomSheetFooterContainer footerComponent={({ animatedFooterPosition }) => (
              <BottomSheetFooter animatedFooterPosition={animatedFooterPosition} bottomInset={bottom}>
                   ....your footer
              </BottomSheetFooter>
             )}
          />
      </View>
    );
  }}
</BottomSheetModal>

```

**Comment by iraybi** [comment]
> ```js
> animatedFooterPosition
> ```

So I'll have to define the animated footer position manually there? Or is there any way to extract the footer props?

**Comment by iraybi** [comment]
@khzouroussama I'm getting some weird rerendering loop if I extract the prop and return the components from it. Anyway, thanks for the BottomSheetFooterContainer part. That solved some other issues I was having.

**Comment by iraybi** [comment]
@khzouroussama Having another issue with the keyboard of the input form inside the footer. As long as I'm typing or canceling there it's fine. But whenever I'm trying to submit something, the keyboard stucks and the app freezes

**Comment by krishnan-456** [comment]
this method is possible in normal BottomSheet component ?
