### ISSUE TITLE
RecyclerListView Scrollable

### ISSUE THREAD

**Issue by henrymoulton** [gorhom/react-native-scroll-bottom-sheet#821]
# Feature Request

## Why it is needed

[RecyclerListView](https://github.com/Flipkart/recyclerlistview/) seems to be accepted to have better performance in the community than an optimised FlatList/SectionList. I'm just wondering if the maintainers thought about this or played with it in the past, otherwise I'm happy to try and create a PR.

## Possible implementation

Looks like it would have to adapt https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetScrollable/createBottomSheetScrollableComponent.tsx

**Comment by siddharthkr** [comment]
@henrymoulton how did you implemented it?

**Comment by hirbod** [comment]
@henrymoulton would be lovely. Was also thinking about it

**Comment by hirbod** [comment]
not stale

**Comment by hirbod** [comment]
Still not stale

**Comment by henrymoulton** [comment]
Not stale please reopen @gorhom

**Comment by Dani-Boy92** [comment]
Any updates on it?

**Comment by siddharthkr** [comment]
@Dani-Boy92 
What worked for me is using  -> ScrollView from "react-native-gesture-handler" inside extendedScrollView prop from RecyclerListView.

**Comment by hirbod** [comment]
ReyclerListView via FlashList has been added. It's Sponsorware, if you need it, sponsor @gorhom to get access :)

**Comment by Dani-Boy92** [comment]
FlashList is not scrollable out of the box within react native bottom sheet.

**Comment by hirbod** [comment]
As said, there is a new package for sponsors.

**Comment by Dani-Boy92** [comment]
@hirbod  I would like to play with FlashList in the React Native Bottom Sheet. Is there a minimum amount that needs to be sponsored to get access to the integrated version. How do the logistics work once the sponsorship is provided?
