### ISSUE TITLE
Android does not scroll

### ISSUE THREAD

**Issue by mehderilker** [gorhom/react-native-scroll-bottom-sheet#826]
Hi,

Works great on iOS devices when I use it with the @gorhom/react-native-wheely repo. But it does not scroll on Android devices.

IOS Working:

https://user-images.githubusercontent.com/26353461/151627950-7855d5b6-8a77-4e2c-a1e3-58ff56fb1560.mp4

Android Not Working:

https://user-images.githubusercontent.com/26353461/151628009-64e37565-75b8-4540-b166-acd81cba0297.mp4

Example Code:

```
import React, {useCallback,useRef,useMemo) from 'react'
import BottomSheet, {
  BottomSheetView
} from '@gorhom/bottom-sheet';
import WheelPicker from 'react-native-wheely';
const Example = () => {
  const snapPoints = useMemo(() => ['30%', '50%', '60%', '90%'], []);
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        disappearsOnIndex={-1}
        appearsOnIndex={0}
        {...props}
      />
    ),
    [],
  );

  const ref = useRef(null);
const handleSheetChanges = useCallback(index => {
    console.log('handleSheetChange', index);
  }, []);
  const handleSnapPress = useCallback((index, refId) => {
    console.log('handleSnapPress', index, refId);
    ref.current?.snapToIndex(index);
  }, []);
  const handleClosePress = useCallback(refId => {
    ref.current?.close();
  }, []);

return(
<View>
   <BottomSheet
        index={1}
        backdropComponent={backdropComponent}
        animateOnMount={true}
        enablePanDownToClose={true}
        keyboardBehavior="extend"
        handleIndicatorStyle={{
          backgroundColor: '#E4E7EC',
          width: scale(70),
        }}
        handleStyle={{backgroundColor: '#F9FAFB', borderRadius: 10}}
        ref={ref}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
         <BottomSheetView>
  <WheelPicker
          selectedIndex={selectedIndex}
          containerStyle={styles.container}
          selectedIndicatorStyle={styles.selectedIndicator}
          itemTextStyle={styles.itemText}
          itemStyle={styles.item}
          options={options}
          onChange={onChange}
        />
  </BottomSheetView>

    </BottomSheet>
    </View>
)
}
```
Dependency

 ```
"@gorhom/bottom-sheet": "^4.1.5",
    "react-native-reanimated": "^2.3.1",
    "react-native-gesture-handler": "^2.1.1",
    "react-native-wheely": "^0.3.2",
```

**Comment by ftzi** [comment]
Have you solved it?

**Comment by kunal-oxl** [comment]
I am facing the same issue

**Comment by mehderilker** [comment]
No, I couldn't solve it.

> çözdün mü

**Comment by mehderilker** [comment]
> Have you solved it?

No, I couldn't solve it.

**Comment by cresenciof** [comment]
worked for me by wrapping with `gestureHandlerRootHOC` from [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android)

**Comment by balloman** [comment]
> worked for me by wrapping with `gestureHandlerRootHOC` from [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android)

Wrapping what? I tried to do this and now I have a GestureView covering half the screen making this solution unusable.

**Comment by balloman** [comment]
> > worked for me by wrapping with `gestureHandlerRootHOC` from [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android)
> 
> Wrapping what? I tried to do this and now I have a GestureView covering half the screen making this solution unusable.

Ok, I was able to fix this by wrapping the entire screen component in `gestureHandlerRootHOC`

**Comment by cresenciof** [comment]
> > > worked for me by wrapping with `gestureHandlerRootHOC` from [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android)
> > 
> > 
> > Wrapping what? I tried to do this and now I have a GestureView covering half the screen making this solution unusable.
> 
> Ok, I was able to fix this by wrapping the entire screen component in `gestureHandlerRootHOC`

that's it, sorry a bit late, this is how it worked for me:

```
const ExploreScreen = gestureHandlerRootHOC(() => {
    ...
    return (
      <BottomSheet
        enableHandlePanningGesture={true}
        enableContentPanningGesture={true}
        ... 
        >
         <BottomSheetFlatList .... />
      </BottomSheet>
    );
 });
```

**Comment by ftzi** [comment]
Why this solution works?

**Comment by jorgegvallejo** [comment]
> > > worked for me by wrapping with `gestureHandlerRootHOC` from [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#usage-with-modals-on-android)
> > 
> > 
> > Wrapping what? I tried to do this and now I have a GestureView covering half the screen making this solution unusable.
> 
> Ok, I was able to fix this by wrapping the entire screen component in `gestureHandlerRootHOC`

This didnt work for me and neither did using the BottomSheetFlatlist. When I use it the list is blank, though I do see it passing data to each render item.

**Comment by brianlaw033** [comment]
for me, i have to wrapping the entire screen component in `gestureHandlerRootHOC` and setting `enableContentPanningGesture={false}`

**Comment by levanthuanmy** [comment]
I try to wrap the `App` component in `gestureHandlerRootHOC` and it works

**Comment by fukemy** [comment]
gestureHandlerRootHOC = wrap app by GestureHandleRootView though

**Comment by dan-herasymov** [comment]
`enableContentPanningGesture={false}` on BottomSheet worked for me 👍
