### ISSUE TITLE
[v4] | [v2] Using BottomsheetTextInput inside BottomSheetModal

### ISSUE THREAD

**Issue by Zakyyy** [gorhom/react-native-scroll-bottom-sheet#833]
# Bug

  I am using bottomsheetTextInput inside bottomsheetModal and it has multiline prop true, 
a lot of users using the app reported that there is a delay in the input and I was able to repro it

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.66.1   |
| react-native-reanimated         | 2.2.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. add BottomSheetTextInput with multiline prop set to true, with value and onChangeText using useState hook
2. add it inside BottomSheetModal and try to write fast 

Describe what you expected to happen:

1. it should work fine without a lag

## Reproducible sample code

<BottomSheetModal
      ref={sheetRef}
      snapPoints={snapPoints}
      onChange={handleSheetChange}
      index={0}
      enablePanDownToClose={true}
      handleComponent={null}>
      <BottomSheetTextInput
        value={com}
        onChangeText={setCom}
        multiline={true}
      />
</BottomSheetModal>

https://user-images.githubusercontent.com/25394763/152216031-d0dbe256-249c-4997-b442-9c3aad8566b6.mov

**Comment by pranavp10** [comment]
@Zakyyy  try to extract the `BottomSheetTextInput`.

 here is the example [https://github.com/gorhom/react-native-bottom-sheet/issues/867#issuecomment-1184432925](https://github.com/gorhom/react-native-bottom-sheet/issues/867#issuecomment-1184432925)

**Comment by sami-sy** [comment]
I am facing the exact same error, tried both the BottomSheetTextInput and TextInput.

**Comment by pranavp10** [comment]
reproduce the error

**Comment by sami-sy** [comment]
below is my TextInput component which is called inside a BottomSheet
```
const DocumentIdInput = forwardRef(({ t }: { t: TFunction }, inputRef) => {
  const [documentId, setDocumentId] = useState<string>()
  const handleDocumentChange = useCallback(debounce(setDocumentId), [documentId])

  useImperativeHandle(
    inputRef,
    () => ({
      value: documentId,
    }),
    []
  )
  return (
    <BottomSheetTextInput
      placeholder={t("Please enter your text")}
      onChangeText={handleDocumentChange}
      value={documentId}
    />
  )
})
```

and this is my bottomSheet

```
<BottomSheetModal
        ref={ref}
        snapPoints={multiSnap ? (numOfSnaps === 2 ? twoSnapPoints : threeSnapPoints) : singleSnapPoint}
        enablePanDownToClose
        index={0}
        style={styles.SheetWrapper}
        footerComponent={useMemo(() => sheetFooterComponent, [])}
        backdropComponent={(backdropProps) => (
          <BottomSheetBackdrop {...backdropProps} appearsOnIndex={0} disappearsOnIndex={-1} enableTouchThrough={true} />
        )}
      >
        <BottomSheetScrollView>
           <Text style={styles.selectTitle}>{t("Please select a document type")}</Text>
              <CustomPickerComponent
                placeholder={t("Select a document type")}
                labelKeyName="label"
                value={documentType?.label}
                onItemChange={handleDocumentType}
                data={DocumentTypeOptions}
                renderListItem={renderDocumentTypeItem}
              />
        <DocumentIdInput t={t} />
   </BottomSheetScrollView>
   <SafeAreaView edges={["bottom"]} />
</BottomSheetModal>
```

**Comment by pranavp10** [comment]
try removing the below code and try are you facing the issue?
```
const handleDocumentChange = useCallback(debounce(setDocumentId), [documentId])

  useImperativeHandle(
    inputRef,
    () => ({
      value: documentId,
    }),
    []
  )
```

**Comment by romankhymych** [comment]
It may helps: https://github.com/gorhom/react-native-bottom-sheet/issues/867#issuecomment-1420441709
