### ISSUE TITLE
TypeError: _bottomSheetModalRef$3.present is not a function

### ISSUE THREAD

**Issue by rahmanharoon** [gorhom/react-native-scroll-bottom-sheet#840]
# Bug

Throwing error when i call `bottomSheetModalRef.current?.present();` and also modal is opening in the initial time 
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.1.5   |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.3.1  |
| react-native-gesture-handler    | ^1.10.3  |

## Steps To Reproduce

1. Create a new project and add the packages and add a modal
2. Try calling ` bottomSheetModalRef.current?.present();`  to open  modal 
3. it will throw the error

Describe what you expected to happen:

1. Need to open modal when i call ` bottomSheetModalRef.current?.present();`

## Reproducible sample code

```
 // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ['50%', '70%'], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  const onModalDismiss = () => {
    bottomSheetModalRef.current?.close();
  };

<BottomSheetModalProvider>
        <BottomSheet
          index={1}
          ref={bottomSheetModalRef}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}>
          <ChangeProjectModal data={projects} onModalDismiss={onModalDismiss} />
        </BottomSheet>
      </BottomSheetModalProvider>

```

![Simulator Screen Shot - iPhone 12 mini - 2022-02-09 at 13 23 24](https://user-images.githubusercontent.com/67966429/153145899-4bc3a42f-1f1f-4400-939f-3d2b46e24e75.png)

**Comment by fitri612** [comment]
how u fix this problem ?
