### ISSUE TITLE
[v4] | [v2] FooterComponent works wrong on Android

### ISSUE THREAD

**Issue by statnyk** [gorhom/react-native-scroll-bottom-sheet#847]
# Bug

Hi, i'm using BottomSheetModal to create a tasks, on the android devices footer component of the modal is covered by the Android keyboard suggestions, on the iOS platform works correctly. It is possible to fix this problem?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | ^0.66.5   |
| react-native-reanimated         | ^2.2.4   |
| react-native-gesture-handler    | ^1.10.3  |

## Steps To Reproduce

1. Create a BottomSheetModal and add footer component 
2. Open modal on different android devices or emulators and u can see wrong behaviour 
3. Here some examples of the wrong behaviour: https://prnt.sc/26ttrre, https://prnt.sc/26ttrzd

Describe what you expected to happen:

1. Here is the expected behaviour: https://prnt.sc/26ttshp

## Reproducible sample code

```javascript
 render() {
        const snapPoint = windowHeight * .2 + 24;
        return (

            <BottomSheetModal
                ref={this.bsRef}
                snapPoints={[snapPoint]}
                backdropComponent={this.renderBackdrop.bind(this)}
                enablePanDownToClose={true}
                onDismiss={() => this.props.onDismiss()}
                footerComponent={() => this.renderFooterComponent()}
                keyboardBlurBehavior='restore'
            >
                <Box style={styles.bsView}>
                    <BottomSheetView style={styles.topContainer}>
                        <BottomSheetTextInput
                            ref={(input) => this.inputRef = input}
                            value={this.props.taskTitle}
                            placeholder={'New task'}
                            onChangeText={(taskName) => this.props.updateTaskTitle(taskName)}
                            autoCorrect={false}
                            numberOfLines={1}
                            style={styles.inputStyle}
                        />
                        <Box ml={'auto'}  >
                            {this.renderSendButton()}
                        </Box>
                    </BottomSheetView>
                </Box>
            </BottomSheetModal>

        )
    }
```

**Comment by statnyk** [comment]
here you can see the same problem like in this thread: https://github.com/gorhom/react-native-bottom-sheet/issues/806

**Comment by statnyk** [comment]
@gorhom, hi can you explain why on different android devices footer component works wrong

<img width="955" alt="Screenshot 2022-02-16 at 10 30 37" src="https://user-images.githubusercontent.com/98084592/154238010-d06d46b6-7fb9-4085-9673-c66e2db36b54.png">

**Comment by hirbod** [comment]
For me, this was the working "fix":

```tsx
<BottomSheet
        keyboardBlurBehavior={'restore'}
        keyboardBehavior="extend"
        android_keyboardInputMode="adjustResize" />
```

**Comment by statnyk** [comment]
@hirbod, unfortunately this solution doesn't fix my problem, by using android_keyboardInputMode prop, keyboard doesn't push the bottom sheet on the top of the keyboard, keyboard overlay the bottom sheet

**Comment by hirbod** [comment]
I ended up using `react-native-keyboard-accessory` and not using the renderFooter from bottom-sheet, having perfect results on iOS and android.

**Comment by hirbod** [comment]
I totally ditched it and wen't with native behavior on Android and for iOS, I went with:
https://github.com/gorhom/react-native-bottom-sheet/issues/641#issuecomment-1069360466

**Comment by somasekharkakarla** [comment]
i am also expecting same behaviour. Footer should be sticky to bottom. Any update on this?
