### ISSUE TITLE
[v4] Can't pass TextInput ref to BottomSheetTextInput as prop

### ISSUE THREAD

**Issue by jzxchiang1** [gorhom/react-native-scroll-bottom-sheet#850]
# Bug

TypeScript complains when you pass a `TextInput` ref as a prop to `BottomSheetTextInput`.

Error is:
```
Property '$$typeof' is missing in type 'TextInput' but required in type 'ForwardRefExoticComponent<TextInputProps & NativeViewGestureHandlerProps & RefAttributes<ComponentType<any>>>'.ts(2322)
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

See sample code. This is a straightforward bug.

## Reproducible sample code

```
  const textInputRef = useRef<TextInput>(null);
  
  <BottomSheetTextInput
      ref={textInputRef}
      ...
  />
```

**Comment by Julienblc** [comment]
Same problem here. Any idea of the type to give ?

**Comment by jzxchiang1** [comment]
> Same problem here. Any idea of the type to give ?

I had to use `// @ts-ignore ...` unfortunately.

**Comment by sarin59337** [comment]
TextInput should be imported from 'react-native-gesture-handler'

```
import { TextInput } from 'react-native-gesture-handler';

const inputRef = useRef<TextInput>();

<BottomSheetTextInput
  ref={inputRef}
  ...
/>
```
