### ISSUE TITLE
[v4] Backdrop background showing after opening bottomSheetModal

### ISSUE THREAD

**Issue by i8ramin** [gorhom/react-native-scroll-bottom-sheet#857]
# Bug

The Backdrop component shows _after_ the opening and animation of the bottom sheet modal. This is from a fresh/new install of the library on a new Expo project. The expected behavior is that the Backdrop shows either _before_ the modal animates in or at the same time.

![050a52c6-2980-4d02-9eef-93c9d8080760](https://user-images.githubusercontent.com/49030/154809517-bbfb1f34-c961-4a46-96f7-6fb3c591a955.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.3.2   |
| react-native-gesture-handler    | 2.1.2   |

## Steps To Reproduce

1. [Follow instructions from the docs](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop#example) on using `BottomSheetBackdrop`
2. Trigger modal
3. Observe that the backdrop appears _after_ the modal appears

Describe what you expected to happen:

1. Trigger modal
2. Expect that the backdrop appears _before_ (or at the same time) as the modal

## Reproducible sample code

The sample code given in the docs results in the above behaviors:
https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop#example

Here is a snack showing the issue: https://snack.expo.dev/@carrot-ramin/bottom-sheet-v4-reproducible-issue-template

**Comment by i8ramin** [comment]
Ok, so not entirely sure I understand how all the different props like `index`, `appearsOnIndex`, and `animatedIndex` work, but adding the following props seems to have solved my issue:

```jsx
  const renderBackdrop = useCallback(
    (props) => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={1}
        animatedIndex={{
          value: 1,
        }}
      />
    ),
    []
  )

  return (
    <View style={tailwind('absolute flex-1')}>
      <BottomSheetModal
        enablePanDownToClose
        detached
        bottomInset={24}
        ref={ref}
        index={0}
        snapPoints={['40%']}
        backdropComponent={renderBackdrop}
        style={tailwind('mx-4')}
      >
        <View style={tailwind('px-4')}>{props.children}</View>
      </BottomSheetModal>
    </View>
  )
```

**Comment by bsmayer** [comment]
I managed to reproduce this issue. 
So apparently this happens when you have only one value in the `snapPoints` array. 
In my case, having the code below solved the issue:

```
const initialSnapPoints = useMemo(() => [1, "CONTENT_HEIGHT"], []);
```

Keep in mind that I'm using the `useBottomSheetDynamicSnapPoints`  hook. 
That's probably not the best solution, there might be a better way, but that did the job for now.

**Comment by i8ramin** [comment]
So I am no longer using a single snap point, and typically have at least 2 snap points in my code, and the thing I am experiencing is that the Backdrop component doesn't seem to _animate in smoothly_, and just sort of appears and disappears as the modal opens and closes. it doesn't feel very smooth. Here is a video to illustrate:

https://www.loom.com/share/9442a43fd6a2418d8ef96b2fb3ec59fe

Here is my code for loading up the BottomSheetModal along with the BottomSheetBackdrop component:

```jsx
const OptionsModal = forwardRef<BottomSheetModalMethods, BottomSheetProps>(
  ({ children, snapPoints = ['95%'], ...props }, ref) => {
    const tailwind = useTailwind()
    const snapPointsMemo = useMemo(() => snapPoints, [snapPoints])

    const renderBackdrop = useCallback(
      (props) => (
        <BottomSheetBackdrop
          {...props}
          animatedIndex={{
            value: 1,
          }}
        />
      ),
      []
    )

    return (
      <BottomSheetModal
        ref={ref}
        enablePanDownToClose
        snapPoints={snapPointsMemo}
        keyboardBlurBehavior="restore"
        backdropComponent={renderBackdrop}
        backgroundStyle={tailwind('bg-offwhite')}
        {...props}
      >
        {children}
      </BottomSheetModal>
    )
  }
)
```

Not entirely sure if I am doing this right, but when I remove the `animatedIndex` prop, the backdrop doesn't show up at all.

**Comment by anhquan291** [comment]
@i8ramin hi. 
I'm facing the same issue that the backdrop just appears and disappears without animated. It doesn't look smooth at all. Any suggestions please? 
Thanks a lot

**Comment by comur** [comment]
Hi @anhquan291 @i8ramin 

I have the same issue, did you find any solution to this ?

Thx

**Comment by comur** [comment]
Finally found a solution to be able to use backdrop component with only 1 snapPoint and let it animate on show and hide:

I had to put these two props on backdrop component

```
<BottomSheetBackdrop
        {...props}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
```

**Comment by anhquan291** [comment]
@comur 
So glad to hear that. I'm gonna try it out. Thank you so much

**Comment by nippysky** [comment]
Thank you very much you guys for the help. This has been so much very helpful

**Comment by favaztechcurve** [comment]
> Ok, so not entirely sure I understand how all the different props like `index`, `appearsOnIndex`, and `animatedIndex` work, but adding the following props seems to have solved my issue:
> 
> ```js
>   const renderBackdrop = useCallback(
>     (props) => (
>       <BottomSheetBackdrop
>         {...props}
>         appearsOnIndex={1}
>         animatedIndex={{
>           value: 1,
>         }}
>       />
>     ),
>     []
>   )
> 
>   return (
>     <View style={tailwind('absolute flex-1')}>
>       <BottomSheetModal
>         enablePanDownToClose
>         detached
>         bottomInset={24}
>         ref={ref}
>         index={0}
>         snapPoints={['40%']}
>         backdropComponent={renderBackdrop}
>         style={tailwind('mx-4')}
>       >
>         <View style={tailwind('px-4')}>{props.children}</View>
>       </BottomSheetModal>
>     </View>
>   )
> ```

you saved my day

**Comment by SourceCipher** [comment]
How come there is no simple prop like `backdropColor` and we could set as `rgba(0, 0, 0, 0.5)` for example???
