### ISSUE TITLE
BottomSheet closes sporadically when re-rendering children due to prop changes

### ISSUE THREAD

**Issue by Amnesthesia** [gorhom/react-native-scroll-bottom-sheet#866]
I'm having issues with the bottom sheet often glitching, opening and closing, without calls being made to `snapToIndex`, `close` or anything else — this especially happens if child props change state

**Comment by MateuszRostkowski** [comment]
Hi, I have the same issue, did you solve it somehow?

**Comment by pehagg** [comment]
I think I know what's happening. I was having the same issue while providing only the `snapPoints`, but not the `index`. Once I provide both the sheet doesn't close when the children update/re-render. Could have something to do with `BottomSheet`'s `index` property defaulting to zero if it's not provided.
