### ISSUE TITLE
[v4] DynamicSnapPoints add footer height

### ISSUE THREAD

**Issue by elmcapp** [gorhom/react-native-scroll-bottom-sheet#872]
# Bug

DynamicSnapPoints: I am able to set the SnapPoint according to height of the content container. The issue is that the footer is not included. I have the Privacy and Restore button as the footer components using BottomSheetFooter. As you can see in the video where the buttons are cut off

https://user-images.githubusercontent.com/64275658/157093445-767d8850-0971-4d66-902e-e0f2f90e5707.mov

## Environment info
iOS and Android

"@gorhom/bottom-sheet": "^4"
"react": "17.0.2"
 "react-native": "0.67.2"
 "react-native-reanimated": "^2.4.1"
 "react-native-gesture-handler": "^2.2.0"

## Steps To Reproduce
I follow the example on the site for using useBottomSheetDynamicSnapPoints and BottomSheetFooter

Describe what you expected to happen:

1. I am not able to set Dynamic SnapPoints and include footer height.

**Comment by chancesmith** [comment]
was another post made?

**Comment by elmcapp** [comment]
bump

**Comment by elmcapp** [comment]
Not Stale

**Comment by ddikodroid** [comment]
same issue

**Comment by Fredkr** [comment]
same here

**Comment by andrecrimb** [comment]
Any updates about this one?

**Comment by BerkeAras** [comment]
No updates? @gorhom?

**Comment by BernardRadman** [comment]
Any updates on this?
