### ISSUE TITLE
Unable to overlap navigation header

### ISSUE THREAD

**Issue by Nitekurs** [gorhom/react-native-scroll-bottom-sheet#876]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |4.1.5   |
| react-native                    | 0.67.2   |
| react-native-reanimated         | 2.4.1   |
| react-native-gesture-handler    | 2.3.0   |

## Steps To Reproduce

1. Backdrop not cover full screen. If i am wrap root component with BottomSheetModalProvider then its drag and close functionality not working

Describe what you expected to happen:

1. I am expecting that its black overlay cover full screen.

**Comment by 11t518s** [comment]
same as me
did you solved?

**Comment by thiago7almeida** [comment]
Any solution?

**Comment by sergey-king** [comment]
up

**Comment by AronBe** [comment]
You should use `BottomSheetModal` and wrap `NavigationContainer` with `BottomSheetModalProvider`

**Comment by achuka99** [comment]
Wrapping the NavigationContainer with BottomSheetModalProvider allows the backdrop to cover full screen but then my model can't close and it can't even be dragged down to close

**Comment by syahirdev** [comment]
I got the same problem as @achuka99. If `NavigationContainer` is wrapped inside `BottomSheetModalProvider`, clicking outside the modal or dragging the pan gesture down is not working anymore, thus can't close the modal.

**Comment by gmani2urs** [comment]
+1 I got the same problem as @achuka99

**Comment by jeffsmonteiro** [comment]
up

**Comment by Mosericko** [comment]
adding this attribute to your BottomSheetModal solves the problem of clicking outside of the modal.
`backdropComponent={(props) => (
					<BottomSheetBackdrop
						{...props}
						appearsOnIndex={0}
						disappearsOnIndex={-1}
					/>
				)}`

**Comment by jaren82** [comment]
It's good to do what AronBe and  syahirdev says. Thank you
But "expo router" doesn't have a Navigation Container
You need to put that in the app/_layout.tsx file

------

위에서 AronBe 와 syahirdev 가 말한대로 하니까 잘됩니다 감사
그런데 expo router 에서는 NavigationContainer 가 없기 대문에
app/_layout.tsx 파일에서 해당 내용을 넣어줘야해요

**Comment by patrickacioli** [comment]
> You should use `BottomSheetModal` and wrap `NavigationContainer` with `BottomSheetModalProvider`

Solve for me

**Comment by erickreutz** [comment]
This does not work for me on android using `@react-navigation/native-stack`

**Comment by atultiwaree** [comment]
> You should use `BottomSheetModal` and wrap `NavigationContainer` with `BottomSheetModalProvider`

I've replaced BottomSheet with BottomSheetModal the modal is not showing up

**Comment by Helen2hang** [comment]
Got the same issue :( Tried all the solutions but didn't work. Anyone got another fix?

**Comment by princebillygk** [comment]
@atultiwaree  same happend with me

**Comment by alexandrecoura96** [comment]
If you are facing this in expo router, you should wrap your main file, per example, the _layout with the BottomSheetModalProvider and inside your Bottom Sheet component, import the BottomSheetModal instead using that default import and put the index={0}.

So your code will be similar like this:

**Main File**
```
export default function Layout() {

  return (
    <GestureHandlerRootView>
      <BottomSheetModalProvider>
          <SafeAreaProvider>
            <StatusBar style="light" />
            <Stack screenOptions={{ headerShadowVisible: false }}>
              <Stack.Screen
                name={StackRouteNames.Splash}
              />
              <Stack.Screen
                name={StackRouteNames.Login}
              />
            </Stack>
            <ToastContainer />
          </SafeAreaProvider>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
}
```

Your Bottom Sheet:

```
import {
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetModal,
} from "@gorhom/bottom-sheet";

    const renderBackdrop = useCallback(
      (props: BottomSheetBackdropProps) => (
        <BottomSheetBackdrop
          {...props}
          appearsOnIndex={0}
          disappearsOnIndex={-1}
        />
      ),
      []
    );

      <BottomSheetModal
        {...props}
        ref={ref}
        index={0}
        backdropComponent={renderBackdrop}
        enablePanDownToClose>
       {content}
      </BottomSheetModal>
```
