### ISSUE TITLE
enableContentPanningGesture={false} stop scrolling

### ISSUE THREAD

**Issue by Nitekurs** [gorhom/react-native-scroll-bottom-sheet#877]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.67.2   |
| react-native-reanimated         | 2.4.1   |
| react-native-gesture-handler    | 2.3.0   |

## Steps To Reproduce

1. When I give false value to enableContentPanningGesture it stop scrolling content

Describe what you expected to happen:

1. Content should be scrollable if enableContentPanningGesture false.

**Comment by ahmedam55** [comment]
I facing the same issue as well
