### ISSUE TITLE
[v4] | [v2] [iOS] Modal does not close when navigating away and keyboardBlurBehavior is "restore"

### ISSUE THREAD

**Issue by Cavallando** [gorhom/react-native-scroll-bottom-sheet#878]
# Bug

Right now we have a Modal that appears and allows the user to enter text in a `BottomSheetTextInput` there is a Submit button that pushes a new Native Stack Screen `presentation: modal`.

When navigating away from a Bottom Sheet Modal to the new screen, we make use of the `useIsFocused` effect from React Navigation as recommended in [this issue](https://github.com/gorhom/react-native-bottom-sheet/issues/231) on this library.

The problem we encountered is that this fixed worked on Simulator for us however once we went to real devices it didn't work and the modal did not close. After digging further, I realized that it was because the keyboard on the simulator wasn't active, once enabling this I could reproduce the bug.

It wasn't until I changed `keyboardBlurBehavior` from `"restore"` to `"none"`  on the bottom sheet modal that this problem went away. I could very well be misunderstanding the expected functionality of "restore" but to me it felt weird that the modal's visibility could be overridden by the keyboard.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.4.1 and 2.3.0+  |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1.  Render a Bottom Sheet Modal with a BottomSheetTextInput and a Button
2. With the keyboard enabled, type in the TextInput
3. Tap the button which closes the modal and navigates to a new screen
4. Go back from the modal via gesture/button press
5. Modal reappears focused on text input

## Reproducible sample code

https://snack.expo.dev/@michaelcavallaro03/bottom-sheet-v4-reproducible-issue-template

**Comment by Cavallando** [comment]
just bumping so it remains open, if I was misunderstanding the api for this library please let me know and I am happy to close.

**Comment by Cavallando** [comment]
> just bumping so it remains open, if I was misunderstanding the api for this library please let me know and I am happy to close.

**Comment by jzxchiang1** [comment]
I have a similar issue but on Android.

When it's set to "restore" and I dismiss the modal by calling `ref.current?.dismiss()` *with the keyboard open*, the modal will disappear but quickly reappear a second later.

**Comment by khzouroussama** [comment]
having the same issue, @Cavallando have you found any workarounds?

**Comment by Cavallando** [comment]
@khzouroussama the only workaround I was able to find was using `"none"` instead of `"restore"` but that doesnt necessarily count as a workaround since it doesnt let you use restore

**Comment by khzouroussama** [comment]
Thanks @Cavallando, I also ended up doing the same, and added the `keyboardHeight` to the snapPoint in order to imitate the behavior of `restore`
```
const snapPoints = useDerivedValue(() => {
    return [animatedSnapPoints.value[0] + (Platform.OS === 'ios' ? keyboardHeight : 0)];
}, [keyboardHeight]);
```

**Comment by pfcodes** [comment]
Bump, any idea how to fix this?

Edit: Ended up just setting a timeout to close the modal 100ms the keyboard was marked for dismissal. Not ideal due to race conditions but it's a hack that works for now. I think calling the `forceClose` method should override `keyboardBlurBehavior `'s `restore`

**Comment by pfcodes** [comment]
Ended up just setting a timeout to close the modal 20ms the keyboard was marked for dismissal. Not ideal due to race conditions but it's a hack that works for now.
