### ISSUE TITLE
Modal Registry with hook to open modal based on string key.

### ISSUE THREAD

**Issue by izakfilmalter** [gorhom/react-native-scroll-bottom-sheet#879]
# Feature Request

Right now you have to bind toggles and the modal closely together because of the ref relationship. Similar to `react-navigation` where you can navigate to a screen with a string key, it would be awesome to have a context provider or even a direct integration with `react-navigation` so that we can open modals programmatically rather than colocation.  

## Why it is needed

This solves two main problems:

1. No more scattering of the same modal through out your code base.
2. Easier opening of the same modal from several interactions on the same screen.

**Comment by ymakhfi** [comment]
try to find the compatible react-native-reanimation version with your env and re run rpm install

**Comment by izakfilmalter** [comment]
@ymakhfi this has nothing to do with which reanimated version I am using. This is a feature request not an issue / bug.
