### ISSUE TITLE
[v4] Modal disappears on typing in controlled TextInput

### ISSUE THREAD

**Issue by thecoorum** [gorhom/react-native-scroll-bottom-sheet#886]
# Bug
While typing in controlled `BottomSheetTextInput` or native `TextInput` the bottom sheet modal can disappear for no reason. Tried different approaches like simple `useState` and custom implementation with `react-hook-form`. When using uncontrolled input seems to be good

### Preview
![RPReplay_Final1647791857](https://user-images.githubusercontent.com/32096016/159171345-da4eae87-49fc-4e8f-81ae-508da550ba8d.GIF)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.3.1   |
| react-native-gesture-handler    | 2.1.0   |

## Steps To Reproduce

1. Create 2 modals within the provider
2. Call second from the first one
3. Start typing in the second modal text field

Describe what you expected to happen:

The second modal doesn't close itself

## Reproducible sample code

```
const renderSearch = useCallback(
    () => (
      <View style={sx({ backgroundColor: "background" })}>
        <Text
          style={sx({
            color: "white",
            fontSize: 20,
            fontWeight: "700",
            fontFamily: "Manrope",
            mb: "$2",
            px: "$5",
          })}
        >
          Select currency
        </Text>
        <InputField
          placeholder="Search currency"
          name="search"
          form={form}
          style={sx({
            py: "$2",
            px: "$3",
            fontSize: 14,
            color: "white",
            flex: 1,
          })}
          clearStyle={sx({ py: "$1", pr: "$4", pl: "$1" })}
          clearSize={18}
          containerStyle={sx({ mb: "$5", mx: "$5" })}
          component={BottomSheetTextInput}
        />
      </View>
    ),
    []
);

...

<BottomSheetModal
  ...
>
  ...
</BottomSheetModal>
<BottomSheetModal
  ...
>
  <BottomSheetFlatList
	    data={currencies}
	    renderItem={renderCurrency}
	    ListHeaderComponent={renderSearch}
	    stickyHeaderIndices={[0]}
	    keyExtractor={(item) => item.id}
	    getItemLayout={(_, index) => ({ length: 70, offset: 70 * index, index })}
	/>
</BottomSheetModal>
```

**Comment by hirbod** [comment]
This is already fixed. You need to upgrade `react-native-reanimated` to v2.5.0.

**Comment by peterhuijsen** [comment]
> This is already fixed. You need to upgrade `react-native-reanimated` to v2.5.0.

Upgrading to v2.5.0 gives me this error:
"Invariant Violation: "main" has not been registered."

I'm using Expo v44.0.0.
Got any ideas?

**Comment by hirbod** [comment]
@Yawmm you can't just upgrade react-native-reanimated to v2.5.0 using expo, unless you're using a custom-dev-client. If you don't use a custom-dev-client, you'll need to wait for SDK 45, which will most likely be released in 2-3 weeks as far as I know.

And as of right now, upgrading will break on android without some workarounds.
https://github.com/software-mansion/react-native-reanimated/issues/3088

I can just tell everybody: start using custom dev clients. It is awesome and will finally leverage all the benefits of expo while still being able to quickly receive library updates or even add basically every third party native lib that your heart pleases.

**Comment by peterhuijsen** [comment]
Alright awesome, will wait for that then, thanks!

**Comment by flpmko** [comment]
This is happening to me too. Are there any workarounds if I NEED this to work NOW and I'm using expo? Eject from expo?

**Comment by hirbod** [comment]
@flpmko No need to eject from Expo. But if you need it now, you'll need to use a custom dev client.

https://docs.expo.dev/development/getting-started/

**Comment by flpmko** [comment]
Thanks @hirbod ! :)

**Comment by hirbod** [comment]
It is a tiny bit of work for initial setup and you'll need XCode/Android SDKs etc to build your own client, but after that, it is basically what you are already used to.

**Comment by peterhuijsen** [comment]
I set up the custom dev client, do I need to add react-native-reanimated as a plugin in the app.json? 
It still gives me the same error.

**Comment by hirbod** [comment]
After setup, just install it. `yarn add react-native-reanimated`.
Make sure t has installed v.2.5.0.

Than run `expo prebuild --clean`, open XCode and compile your custom dev client onto your device.

Run `expo start --dev-client` and open your dev client (not expo go)

On android, you need to follow this workaround for now:
https://github.com/software-mansion/react-native-reanimated/issues/3088

Building android is the same, despite you don't run XCode, but `expo run:android`

**Comment by peterhuijsen** [comment]
Alright, will try that. Thanks @hirbod!

**Comment by kbrgl** [comment]
Not stale

**Comment by hirbod** [comment]
This is stale, since it’s fixed
