### ISSUE TITLE
Remove the Github actions bot concerning issues

### ISSUE THREAD

**Issue by JohnBerd** [gorhom/react-native-scroll-bottom-sheet#891]
# Feature Request

Hello, thank you for the great job. I see many issues closed by the Github action bot and it is not solved.
This happens for 2 reasons:
- the issue template is not respected 
- the issue thread didn't get new messages for a period of time

In my opinion, both of those reasons are not enough to consider an issue as closed since it is not solved.

2 examples of a problem I am currently facing:
#826 #658 

Those issues are currently closed by the bot but still existing, I can't reopen them so I am thinking about just creating a duplicate of those.

## Why it is needed

It is needed for giving more visibility about issues existing and not have to search for them in closed issues.
Having a real snapshot of real problems concerning this package.

## Possible implementation

Disable the Github action bot

### Code sample

No code to show

**Comment by hirbod** [comment]
I agree. The bot settings are just too sensitive.
