### ISSUE TITLE
[v2] Keyboard above bottom sheet

### ISSUE THREAD

**Issue by mehthabux** [gorhom/react-native-scroll-bottom-sheet#893]
im using bottom sheet with textinput, evey time keyboard comes above the bottom sheet
is there any update on keyboard handling in v2 (Reanimated v1)

**Comment by cepintos** [comment]
Happens the same to me in android, after that it closed by itself, its working perfectly on iOS

**Comment by mak12** [comment]
Any luck with this ?

**Comment by fukemy** [comment]
same issues, any solution?
