### ISSUE TITLE
[v4] Android handler touch scroll does not working

### ISSUE THREAD

**Issue by qnrjs42** [gorhom/react-native-scroll-bottom-sheet#895]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5  |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.4.1   |
| react-native-gesture-handler    | 2.2.0   |

## ios
https://user-images.githubusercontent.com/19409518/160754864-43bf5dc2-b95c-43f6-843e-1a4c7a918780.MP4

## android
One UI version: 4.0
Android version: 12
Device: Galaxy Note 10+ 5G

https://user-images.githubusercontent.com/19409518/160755235-fe31234d-c0a7-4dd6-9d61-4a2392e60268.mp4

Describe what you expected to happen:

1. Handler touch scroll does not work on Android.
2. but, iphone is work well

## Reproducible sample code

https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetview

```
import React, { useCallback, useRef, useMemo } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';
import BottomSheet, { BottomSheetView } from '@gorhom/bottom-sheet';

const App = () => {
  // hooks
  const sheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%', '90%'], []);

  // callbacks
  const handleSheetChange = useCallback(index => {
    console.log('handleSheetChange', index);
  }, []);
  const handleSnapPress = useCallback(index => {
    sheetRef.current?.snapToIndex(index);
  }, []);
  const handleClosePress = useCallback(() => {
    sheetRef.current?.close();
  }, []);

  // render
  return (
    <View style={styles.container}>
      <Button title='Snap To 90%' onPress={() => handleSnapPress(2)} />
      <Button title='Snap To 50%' onPress={() => handleSnapPress(1)} />
      <Button title='Snap To 25%' onPress={() => handleSnapPress(0)} />
      <Button title='Close' onPress={() => handleClosePress()} />
      <BottomSheet ref={sheetRef} snapPoints={snapPoints} onChange={handleSheetChange}>
        <BottomSheetView>
          <Text>Awesome 🔥</Text>
        </BottomSheetView>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 200,
  },
});

export default App;
```

**Comment by M0rfes** [comment]
facing the same issue

**Comment by Yrsafam** [comment]
Faced with a similar problem. In my case, the problem was that I use wix\react-native-navigation, and it needs an additional HOC wrapper. Detailed information [here](https://docs.swmansion.com/react-native-gesture-handler/docs/1.10.3/#with-wixreact-native-navigation)
One of the problems is that this fact is not specified in the RNGH v2+ documentation.
I create [PR](https://github.com/software-mansion/react-native-gesture-handler/pull/1965) for RNGH

**Comment by Yrsafam** [comment]
#issue-1186256850

**Comment by M0rfes** [comment]
wrapping the component with gestureHandlerRootHOC worked for me
 
 example
 ```js
import { gestureHandlerRootHOC } from "react-native-gesture-handler";

const Screen = () => {....}

export default  gestureHandlerRootHOC(Screen)

```

**Comment by qnrjs42** [comment]
@Yrsafam Thank you for your interest in my issue!

I tried `gestureHandlerRootHOC`

1. It works well in react-navigation! (O)
2. not work outside of react-navigation. (X)

```
<>
  <Navigation>...</Navigation>
  <GlobalModal>...</GlobalModal>
</>
```


https://user-images.githubusercontent.com/19409518/160985363-1aa138dd-743d-46d5-989f-4c4e595281c8.mp4


## I have problem
1. created white blank. (with ios)
2. handler touch scroll does not working.


## my code example)
```
import { View, Text } from 'react-native';
import React, { useRef, useMemo, VFC } from 'react';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler';
import BottomSheet, { BottomSheetScrollView } from '@gorhom/bottom-sheet';

import CustomModal from '@components/customs/Modal';


const GlobalModalBookmark: VFC = () => {
  // hooks
  const sheetRef = useRef<BottomSheet>(null);
  const snapPoints = useMemo(() => [77, '50%', '100%'], []);

  return (
    <>
      <CustomModal
        ...
      >
        <BottomSheet
          ref={sheetRef}
          index={0}
          snapPoints={snapPoints}
        >
          <BottomSheetScrollView>
            {Array.from(Array(300).keys()).map(v => (
              <View key={v}>
                <Text>Item {v}</Text>
              </View>
            ))}
          </BottomSheetScrollView>
        </BottomSheet>
      </CustomModal>
    </>
  );
};

export default gestureHandlerRootHOC(GlobalModalBookmark);
```


Can't I use it outside the react-navigation?

**Comment by Yrsafam** [comment]
@qnrjs42 
I think the problem here is something else. The documentation for the [RNGH ](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#usage-with-modals-on-android) states that there will be problems on android when using gestures and `Modal`, which seems to be just your case. To begin with, I would try using [BottomSheetModal](https://gorhom.github.io/react-native-bottom-sheet/modal/usage) from the same package, instead of the usual `Modal`, if this does not help, then you may probably need to wrap the `BottomSheet` in `gestureHandlerRootHOC` as indicated in the [documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#usage-with-modals-on-android), but in this case I am not sure that this will not break the `BottomSheet`

**Comment by M0rfes** [comment]
`gestureHandlerRootHOC` fixes the bottom sheet issue on android but 
`BottomSheetFlatList` and `BottomSheetScrollView` brakes the default  Components  render but don't scroll and the components from BottomSheet don't render the children or renderItem render prop

**Comment by The-Lone-Druid** [comment]
Thanks a lot bro, finally it worked!

**Comment by daihieptn97** [comment]
I add **GestureHandlerRootView** for root project and work for me. 

Below example code :


```js
import { GestureHandlerRootView } from "react-native-gesture-handler";


const Stack = createNativeStackNavigator();

function App() {
    return (
        <GestureHandlerRootView style={{ flex: 1 }}>
            <NavigationContainer>
                <Stack.Navigator screenOptions={{ headerShown: false }}>
                    <Stack.Screen name={NavigationKey.Search} component={CommonScreen} />
                    <Stack.Screen name={NavigationKey.Splash} component={SplashScreen} />
                    <Stack.Screen name={NavigationKey.HomeTab} component={HomeBottom} />
                </Stack.Navigator>
            </NavigationContainer>
        </GestureHandlerRootView>

    );
}
```

And code screen:

```js
import BottomSheet from "@gorhom/bottom-sheet";

const CommonScreen = () => {


    // ref
    const bottomSheetRef = useRef<BottomSheet>(null);

    // variables
    const snapPoints = useMemo(() => ["1%", "25%", "50%"], []);

    // callbacks
    const handleSheetChanges = useCallback((index: number) => {
        console.log("handleSheetChanges", index);
    }, []);


    return <SafeAreaView style={{ flex: 1, backgroundColor: Colors.background }}>
        <BottomSheet
            ref={bottomSheetRef}
            index={1}
            snapPoints={snapPoints}
            onChange={handleSheetChanges}
            enablePanDownToClose={true}
        >
            <View style={{
                flex: 1,
                padding: 24,
                backgroundColor: Colors.blackLayer
            }}>
                <Text>Awesome 🎉</Text>
            </View>
        </BottomSheet>


    </SafeAreaView>;
};
export default CommonScreen;

```


Hope it works for you!

**Comment by ScreamZ** [comment]
Both `GestureHandlerRootView` or `gestureHandlerRootHOC` unlocked the situation. This has to be described in the documentation and marked as required when using React Navigation Native Stack.
