### ISSUE TITLE
Gesture Handler Threshold

### ISSUE THREAD

**Issue by thematheusmello** [gorhom/react-native-scroll-bottom-sheet#899]
# Feature Request
It's my first time using this library so I don't know if it's possible already but I was not able to find this configuration on the documentation, I would like to control the percentage or height to close the BottomSheet. For me, it seems I need to always swipe the entire component from the top to the middle of the screen and I would like to add some kind of threshold of 80% and then from this specific point, automatically send the BottomSheet to the end.

## Why it is needed

The gesture handler forces the user to always swipe the BottomSheet from the top to the middle and I would like to control this value.

## Possible implementation

```ts
  <BottomSheet
      onBackdropPress={close}
      onClose={close}
      bottomSheetRef={bottomSheetRef}
      snapPoints={snapPoints}
      threshold={"80%"}
   >
```

**Comment by branikclimbs** [comment]
Duplicate of #563
