### ISSUE TITLE
[v4] | [v2] Bottomsheet Input onChangeText duplicate data when typing quickly

### ISSUE THREAD

**Issue by mokshmodi96** [gorhom/react-native-scroll-bottom-sheet#902]
# Bug

  I have a form in bottomsheetmodal with bottomsheetmodalinput for keyboard handling as you can see in video the input with normal keyboard seems to reinitialising after every keystroke and if types quickly the text is duplicated. Although the same doesnt happen for keyboard type to numeric.
  
This issue only happens on android.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
|react-native                                 | 67.4   |
|react-native-reanimated            | 2.3.2   |
|react-native-gesture-handler    | 2.6.0   |

https://user-images.githubusercontent.com/32169738/162009065-ac4ccd4a-7602-4d27-ae03-44c52e900c1f.mp4
## Steps To Reproduce

1. Using BottomsheetModalInput along with local useState
2. with keyboard type set to default 
3. try to type text quickly the text duplicates on android 

Describe what you expected to happen:

1.Input text to handle values normally

**Comment by mokshmodi96** [comment]
@gorhom Any Update on the issue?

**Comment by giacomocerquone** [comment]
Any news with the new versions on this? I decided to completely recreate my own bottomsheet due to this issue. Would be nice to know that it's solved

**Comment by giacomocerquone** [comment]
@mokshmodi96 I've solved it. Basically, you just need to avoid triggering a setState due to the input within the same component hosting the BottomSheetModal component.

Therefore instead of having:

```jsx
const MyModal = () => {
  const [description, setDescription] = useState("");

  return (
    <BottomSheetModal ...>
        <TextInput onChangeText={setDescription} value={description} />      
    </BottomSheetModal>
  )
}
```

I solved it doing:

```jsx
const Content = () => {
  const [description, setDescription] = useState("");
  return (
    <>
        <TextInput onChangeText={setDescription} value={description} />      
    </>
}

const MyModal = () => {
  return (
    <BottomSheetModal ...>
      <Content />
    </BottomSheetModal>
  )
}
```

**Comment by mokshmodi96** [comment]
@giacomocerquone Thank you for your solution.

**Comment by Zakyyy** [comment]
@giacomocerquone But why ? do you know the exact reason behind this?

**Comment by giacomocerquone** [comment]
> @giacomocerquone But why ? do you know the exact reason behind this?

Very likely that some memoization of the component should be added there and so rerenderings lead to losing some state somewhere!
Don't have the time to contribute and also the maintainer doesn't seem to want help (see: #995)

**Comment by Odyrac** [comment]
same issue here, but my input and my bottom sheet are already in another component
