### ISSUE TITLE
[v4] | [v2] Exception in HostFunction: Value is undefined, expected an Object

### ISSUE THREAD

**Issue by luisbandeiraitez** [gorhom/react-native-scroll-bottom-sheet#904]
# Bug

Exception in HostFunction: Value is undefined, expected an Object

This error happens only in android, I teste with ios and worked completely well, just on android is not working

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.1.5   |
| react-native                    | 0.64.3   |
| react-native-reanimated         | ~2.3.1  |
| react-native-gesture-handler    | ~2.1.0   |

## Steps To Reproduce

```
`import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
// ref
const bottomSheetRef = useRef(null);

// variables
const snapPoints = useMemo(() => ['25%', '50%'], []);

// callbacks
const handleSheetChanges = useCallback((index: number) => {
console.log('handleSheetChanges', index);
}, []);

// renders
return (



Awesome 🎉



);
};

const styles = StyleSheet.create({
container: {
flex: 1,
padding: 24,
backgroundColor: 'grey',
},
contentContainer: {
flex: 1,
alignItems: 'center',
},
});

export default App;`
```

![Screenshot_1649335081](https://user-images.githubusercontent.com/84722333/162201550-38c22569-1256-4b25-ab02-ef7962dea073.png)

1. Running in ios works
2. Runnig in android does not work
3.

**Comment by PaulOskarSoe** [comment]
Try bumping reanimated version to 2.5.0.

**Comment by ELBEQQAL94** [comment]
I got same issue:

    "react-native-reanimated": "~2.3.1",
    "@gorhom/bottom-sheet": "^4",

**Comment by ELBEQQAL94** [comment]
@luisbandeiraitez I solved issue by running ` expo start --clear ` after `yarn start`

resource: https://docs.expo.dev/versions/latest/sdk/reanimated/

**Comment by luisbandeiraitez** [comment]
gonna try this one
@ELBEQQAL94

**Comment by azevgabriel** [comment]
> @luisbandeiraitez I solved issue by running `expo start --clear` after `yarn start`
> 
> resource: https://docs.expo.dev/versions/latest/sdk/reanimated/

**it worked here too**

```json
"dependencies": {
   "@gorhom/bottom-sheet": "4",
   "react-native-gesture-handler": "~2.1.0",
   "react-native-reanimated": "~2.3.1",
}
```

**Comment by luisbandeiraitez** [comment]
I deleted the node modules and installed it agai and worked!! This one can be closed for a while
