### ISSUE TITLE
[v4] BottomSheet flickers when adding Animated component 

### ISSUE THREAD

**Issue by nastarfan** [gorhom/react-native-scroll-bottom-sheet#908]
# Bug
The BottomSheet is flickering when displayed after animated component has been mounted, specifically the flickering part is the `BottomSheetBackdrop`.

From my observation, the flickering only happens when the BottomSheet has `onChange` prop since removing it while still keeping the animated component dismisses the issue. Tho, keeping the `onChange` prop while removing the animated component also removes the issue. So it seems both cannot present at the same time, otherwise the issue will arise.

The issue exists on both BottomSheet and BottomSheetModal.
![bottomsheetbug](https://user-images.githubusercontent.com/45551937/162555647-b4eb23d5-e2a4-4343-b2c7-68d8ea5bf054.gif)

## Environment info
I have only tested this on Android

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.68.0 (also tested on 0.67.4)   |
| react-native-reanimated         | 2.6.0 (also tested on 2.5.0)   |
| react-native-gesture-handler    | 2.3.2   |

## Steps To Reproduce

1. Add animated components (from reanimated), mounted before the bottom sheet
2. Add bottomsheet with `backdropComponent` and `onChange` props
3. The bottom sheet will flicker when shown

Describe what you expected to happen:

1. The BottomSheet doesn't flicker even we have backdrop, onChange handler, and animated components

## Reproducible sample code
I created [a repo ](https://github.com/nastarfan/bugReport)to reproduce the issue, specifically [in this file](https://github.com/nastarfan/bugReport/blob/main/src/Main.js)

**Comment by kaogire** [comment]
@nastarfan Did you finally resolve this?

**Comment by OlehOutlierlabs** [comment]
why is this closed? this is still an issue!!!! @kaogire  @nastarfan did you fix this?

**Comment by kaogire** [comment]
@OlehOutlierlabs Nah, it's still an issue

**Comment by HGCollier** [comment]
Managed to find a solution here: #208 
Essentially, rather than putting a function directly into the `onChange` prop, create a callback instead:
```
const handleSheetChanges = useCallback((index: number) => {
  console.log('handleSheetChanges', index);
}, []);
```
`onChange={handleSheetChanges}`
