### ISSUE TITLE
[v4] Random crashes with Android due to signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by jzxchiang1** [gorhom/react-native-scroll-bottom-sheet#909]
# Bug

When I open and close the BottomSheetModal in quick succession on Android (both emulator and device), I will almost certainly encounter this error, where the entire app will crash with this error:

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7469636f6c657628
    x0  b400007d0fedad70  x1  0000007ca4cfd338  x2  0000000000000002  x3  0000000000000004
    x4  0000007ca4cfd33a  x5  0000007ca4cfd368  x6  0000000000000001  x7  0000000000000001
    x8  00000000000000b9  x9  1baffed00baffedf  x10 b400007ccff02d70  x11 b400007d0fedad70
    x12 0000000000000001  x13 0000000000000003  x14 000000000004200c  x15 0000000030000000
    x16 0000007c12757dc8  x17 0000007c11e2ea1c  x18 0000007ca0f0c000  x19 7469636f6c657610
    x20 b400007ebfe79040  x21 0000007c127789fc  x22 0000000000000005  x23 0000007ca4d05000
    x24 0000007c13b38e8c  x25 0000007c12778000  x26 0000007b0a646e51  x27 0000007ca4d05000
    x28 b400007ebfe84100  x29 0000007ca4cfd480
    lr  0000007c13b71f54  sp  0000007ca4cfd480  pc  0000007c11e2ea48  pst 00000000a0001000
backtrace:
      #00 pc 0000000000deaa48  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8android.so (v8::internal::GlobalHandles::NodeSpace<v8::internal::GlobalHandles::Node>::Release(v8::internal::GlobalHandles::Node*)+44) (BuildId: d77b0179dd66c987)
      #01 pc 00000000000abf50  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8executor.so (rnv8::V8PointerValue::~V8PointerValue()+104) (BuildId: 4333bd01b6f2f93e121b86fc0b8d8aac4756be49)
      #02 pc 00000000000ac660  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8executor.so (rnv8::V8PointerValue::invalidate()+52) (BuildId: 4333bd01b6f2f93e121b86fc0b8d8aac4756be49)
```

It's very possibly a reanimated [error](https://github.com/software-mansion/react-native-reanimated/issues/2430), but I don't see it happen with other libraries that depend on reanimated... only react-native-bottom-sheet.

There something specifically here that triggers this error, and it's causing a lot of headaches. I'm even using a recent version of RN and reanimated.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.67.4   |
| react-native-reanimated         | 2.5.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

It's not easy for me to produce a code snippet to reproduce, but I'd be happy to provide more information or try any experiments you can think of.

**Comment by jzxchiang1** [comment]
Any idea what could be the cause?

**Comment by valeshgopal** [comment]
Same issue
