### ISSUE TITLE
[v4] Force Close When Using BottomSheetModalProvider

### ISSUE THREAD

**Issue by rifansyah** [gorhom/react-native-scroll-bottom-sheet#913]
# Bug

when i add `BottomSheetModalProvider` in the root file of the app. the app got force close when i close and reopen it.

i tried to use the provider right on the screen that i used the modal, but it still shows this error right after close the screen and open it again.

i'm not sure but i think it's related to this code inside `BottomSheetModalProvider`

```
<BottomSheetContainer
    containerOffset={animatedContainerOffset}
    containerHeight={animatedContainerHeight}
    children={null}
/>
```

![image](https://user-images.githubusercontent.com/31396901/163106057-226b2d1f-52fc-4c9d-800d-d4e3b868e51c.png)

it sometimes says `Cannot add new property 'value'`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.5.0   |
| react-native-gesture-handler    | 2.2.0   |

## Steps To Reproduce

1. add `BottomSheetModalProvider` to root file or 
2. close app using back button
3. reopen the app

or
1. add `BottomSheetModalProvider` to specific screen file
2. navigate to that screen
3. close the screen
4. navigate again to that screen

**Comment by David-Montenegro** [comment]
I have the same error, this error is appearing every time the project must be completely rendered. That is, at the minimum change it is showing again. If anyone has a solution to this, please, I've been dealing with this bug for weeks.

**Comment by sameer-j** [comment]
I am also facing the same. Randomly crashing in production as well, with same error as "Cannot add new property 'value'".
@rifansyah @David-Montenegro did you find any solution or workaround for it?

Any way to reopen this?

**Comment by sregg** [comment]
Has anyone found a fix for this?
This crash has been happening after we migrated our app from RN 0.67 to 0.70.

**Comment by getterhiss** [comment]
We are experiencing the same error `TypeError: Cannot add new property 'value'` on our app. We are seeing this happen in production, but I've also been able to replicate this on a **resizable** Android emulator.

It happens every time when I:
1. Open the app on the Android emulator
2. Switch the emulator to a different size (ex: from regular dimensions to foldable)

We have the provider component in the root of our app, between `<GestureHandlerRootView />` and `<SafeAreaProvider />`

Though, only **some** of the users experiencing this error have a foldable device.
