### ISSUE TITLE
[v4] Ability to present modal with specific animation (or instantly)

### ISSUE THREAD

**Issue by elan** [gorhom/react-native-scroll-bottom-sheet#915]
# Feature Request

When you call `.present` on a `BottomSheetModal` there are no parameters and it slides up using the standard animation.

## Why it is needed

With things like a player modal which you might want to display on startup, the animation is distracting. If it could be displayed instantly it would help give the sense of "restoring" the state of the modal.

## Possible implementation

`.present(instant: boolean = false)` or via animation config.

### Code sample

Per above, being able to pass in either a flag or animation config.

**Comment by gorhom** [comment]
this is possible by providing `animateOnMount` with `false` value, however this prop is not exposed, i will add it on the next release 
```
animateOnMount={false}
```

**Comment by elan** [comment]
oh awesome, thank you!

**Comment by elan** [comment]
Actually, I'm not sure that'll work like I was hoping; basically I want it to render the modal fully presented the first time in some cases. Using `animateOnMount={false}` still renders it invisible and then I trigger the `present` right after which makes it appear, but it still shows the app for a few frames before the full-screen modal.

Any suggestions?
