### ISSUE TITLE
Hiding a component when the sheet is dragged

### ISSUE THREAD

**Issue by ahmadardal** [gorhom/react-native-scroll-bottom-sheet#916]
Hello!

I have a bottom sheet in a map view. The user is able to select a marker, and then a tile will appear when a marker has been selected. But the user is also able to drag up the bottom sheet, at which all items will show in a list view. My problem is that when the user has selected a tile, and then drags the bottom sheet, the tile is overlaid above the bottom sheet. I have used onAnimate method, to catch this event and hide the marker. But the onAnimate event only seems to fire off once the bottom sheet has finished animating to the next snapPoint. But it does not catch when the user is still holding the bottom sheet.

![image](https://user-images.githubusercontent.com/77482900/163483516-7b8ec3bc-adf3-46a3-8880-e41fa947b622.png)

![image](https://user-images.githubusercontent.com/77482900/163483789-6fa0d7c0-4d46-41f1-b8ba-f7d03a125294.png)

So isn't there some way we can handle events when the bottom sheet is actually moving? onAnimate only fires off when the transition has finished, meaning for example that it has finished moving from 10% to 90%.

**Comment by calebpanza** [comment]
Curious if you ever found a solution to this issue??

**Comment by pehagg** [comment]
@calebpanza , the way I worked around this was to listen to both `onAnimate` and `onChange` and set visibility of child component based on the `index` both callbacks return using `React.useState`.

**Comment by calebpanza** [comment]
And did you do that from the parent container? Or from a child within the `BottomSheetProvider`?

**Comment by pehagg** [comment]
> And did you do that from the parent container? Or from a child within the `BottomSheetProvider`?

Child within `BottomSheetProvider`, in a component which encapsulates the `BottomSheet`.

**Comment by calebpanza** [comment]
Oh so it was the wrapper component that held `BottomSheet`?

I would love to be able to do this kind of thing using the `useBottomSheet` hook from a child component within Bottom Sheet and I'm having a hard time getting it to work well...
