### ISSUE TITLE
[v4] | [v2] BottomSheetFooter and FlatList size

### ISSUE THREAD

**Issue by filippobarcellos** [gorhom/react-native-scroll-bottom-sheet#923]
# Bug

Hi. First of all thank you for the lib, it's really awesome. I'm having some problems trying to make the flatlist to respond based on the size of the bottom sheet. When is expanded it's showing all the items but when I collapse and can't scroll to the last item and the same item appears to be under the footer. So I'd imagine it's just how to handle the size of the flatlist.
<img width="424" alt="Screenshot 2022-04-27 at 11 15 55" src="https://user-images.githubusercontent.com/56128203/165497030-9ca5002d-f94a-4a8c-81f2-028673642cf2.png">
<img width="424" alt="Screenshot 2022-04-27 at 11 16 05" src="https://user-images.githubusercontent.com/56128203/165497038-73a27bfd-1968-4293-9086-96ac2babfa31.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4 |
| react-native                    | 0.64.3  |
| react-native-reanimated         |~2.3.1  |
| react-native-gesture-handler    | ~2.1.0   |

## Steps To Reproduce

1. On 50% - flatlist needs to be pushed up the show.

## Reproducible sample code

```
export default function BottomSheet() {
const renderFooter = useCallback(
    (props) => (
      <BottomSheetFooter
        {...props}
        bottomInset={20}
      >
        <View>
          <BottomSheetTextInput
            placeholder="Fixed input"
          />
        </View>
      </BottomSheetFooter>
    ),
    []

return (
<BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={onSheetChange}
        enablePanDownToClose
        style={styles.bottomSheet}
        footerComponent={renderFooter}
        keyboardBehavior="extend"
        keyboardBlueBehaviour={'restore'}
      >
        <View>
          <Text>Fixed Header</Text>
        </View>

        <FlatList
          data={data}
          keyExtractor={(i) => String(i)}
          renderItem={renderItem}
          contentContainerStyle={{
            paddingVertical: 10,
          }}
        />
      </BottomSheet>
    </View>
  );
}

**Comment by filippobarcellos** [comment]
bump

**Comment by ChristopherBanas** [comment]
Running into the same issue

**Comment by ChristopherBanas** [comment]
Bump. Encountering the same even when using `BottomSheetFlatList`

**Comment by Nachox07** [comment]
Same issue here with the latest version while having a BottomSheetFlatList where items are displayed conditionally increasing its height.

As a workaround, I could make it work by setting the `enableOverDrag` prop to false in the `BottomSheet` component.

```typescript
      <BottomSheet
        {...props}
        enableOverDrag={false}>
        {children}
      </BottomSheet>
```

**Comment by nathMoni** [comment]
facing the same issue, anyone found a solution for this? the footer is becoming useless if there is a flatlist or scroll view above it

**Comment by ChristopherBanas** [comment]
@nathMoni I apply a hefty amount of padding to the footer component

```
const Footer = useCallback(
    (props: BottomSheetFooterProps) => (
      <BottomSheetFooter
        {...props}
        style={{
          paddingBottom: 26,
        }}
      >
        {footer}
      </BottomSheetFooter>
    ),
    [props, footer]
  );
```

**Comment by nathMoni** [comment]
@ChristopherBanas I just stopped using the footer, better to just use a custom footer comp

**Comment by pelayomartinez** [comment]
Bump
