### ISSUE TITLE
[v4] useBottomSheetDynamicSnapPoints not updating if initialSnapPoints changed

### ISSUE THREAD

**Issue by Shaninnik** [gorhom/react-native-scroll-bottom-sheet#928]
# Bug

We have a use case where `initialSnapPoints` are calculated and can change during the screen lifetime:

``` 
const initialSnapPoints = useMemo(
    () => [initialHeight(), 'CONTENT_HEIGHT'],
    [initialHeight()],
  );
  const {
    animatedHandleHeight,
    animatedSnapPoints,
    animatedContentHeight,
    handleContentLayout,
  } = useBottomSheetDynamicSnapPoints(initialSnapPoints);
```

The way `useBottomSheetDynamicSnapPoints` is implemented makes it impossible to update `initialSnapPoints` and bottom sheet get's stuck with the first value ever supplied as an argument

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.2.1   |
| react-native                    | 0.66.3   |
| react-native-reanimated         | 2.2.4   |
| react-native-gesture-handler    | 1.10.3   |

## Possible solution

Solution looks very simple to me and I was able to fix it with patch-package by modifying `useBottomSheetDynamicSnapPoints.ts` and adding `initialSnapPoints` as dependency to `useDerivedValue`:
```
diff --git a/node_modules/@gorhom/bottom-sheet/src/hooks/useBottomSheetDynamicSnapPoints.ts b/node_modules/@gorhom/bottom-sheet/src/hooks/useBottomSheetDynamicSnapPoints.ts
index a1c2573..5e66825 100644
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useBottomSheetDynamicSnapPoints.ts
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useBottomSheetDynamicSnapPoints.ts
@@ -37,7 +37,7 @@ export const useBottomSheetDynamicSnapPoints = (
     return initialSnapPoints.map(snapPoint =>
       snapPoint === 'CONTENT_HEIGHT' ? contentWithHandleHeight : snapPoint
     );
-  }, []);
+  }, [initialSnapPoints]);
 
   // callbacks
   const handleContentLayout = useCallback(
   ```
   
I have done limited testing and have not noticed any side effects, I can create pull request if this solution looks good to you

**Comment by Rc85** [comment]
This needs to be addressed. I am also facing the same issue. Basically on initial render, I want to set the initial height to the height of the header inside my bottom sheet and the header height can be dynamic.

Maybe open a pull request with your solution?
