### ISSUE TITLE
Lazy loading BottomSheet that has not been open

### ISSUE THREAD

**Issue by farellsujanto** [gorhom/react-native-scroll-bottom-sheet#930]
# Feature Request
Current implementation of the BS is that it is rendered on component mount.

## Why it is needed
I have a heavy component inside several BS' on a page, I kinda need the functionality of lazy loading to prevent JS fps dropping / performance issue on my app. This could serve as a performance optimization for the library.

## Possible implementation
Maybe we can implement a new prop lazyLoad, if this is tru then there will be lazy loading implemented.
```
<BottomSheet
            ref={innerRef}
            index={-1}
            enablePanDownToClose
            snapPoints={snapPoints}
            style={styles.container}
            backdropComponent={Backdrop}
            handleComponent={HandleComponent}
            onChange={handleSheetChanges}
            lazyLoad >
```

**Comment by hirbod** [comment]
Why don't you just render that BottomSheet whenever you need it with a simple state switch (useState)
Or just delay your children rendering with onChange/onAnimate etc.

**Comment by ser-emejia** [comment]
@hirbod You say something like this?

```
const [is_open, setIsOpen] = useState(false)

{
 is_open && (<BottomSheetComponent sheet_ref={sheet_ref} is_open={is_open} />
}
```

**Comment by hirbod** [comment]
Exactly

**Comment by pierroo** [comment]
Unfortunately playing with state brings some race condition where I have to first activate its state, then trigger the ref.current.snapTo; playing without timeout etc to make sure the bottomsheet ref is not undefined etc.
seems very hacky.

we might also lose the closing animation if we set open to false from the state which will immediately remove the component entirely without caring of it's natural sliding down animation.

I also believe a lazyLoad props would be super helpful.

or am I missing something @hirbod ?
did you manage to make it work smoothly @ser-emejia or @farellsujanto ?
Your help would be very much appreciated for I am facing this issue now as well :)

**Comment by aminedammak** [comment]
You can just use Bottom Sheet Modal instead of Bottom Sheet,  https://gorhom.github.io/react-native-bottom-sheet/modal/usage/ the bottom sheet will render only when it is opened.

**Comment by Wenceslauu** [comment]
What is the best way to do that right now? I believe introducing race conditions with state are not worth it

**Comment by Psycarlo** [comment]
Ping
