### ISSUE TITLE
How to change the style of the top bar

### ISSUE THREAD

**Issue by goxr3plus** [gorhom/react-native-scroll-bottom-sheet#947]
Is there a way to change the style of this top bar ?

![image](https://user-images.githubusercontent.com/20374208/168709568-86fb113a-ffc8-41cf-b027-bb4787ac0785.png)

**Comment by goxr3plus** [comment]
@gorhom It's a simple question , not everything needs a template come on :) 

I am new in this library no clue how that top bar is called.

**Comment by goxr3plus** [comment]
.... :) Can i have some help on the topic please

**Comment by georgibakken** [comment]
@goxr3plus : Did you find a way to style it?

**Comment by Opus26** [comment]
You can try to play with ```handleStyle``` and ```handleIndicatorStyle``` (https://gorhom.github.io/react-native-bottom-sheet/props#handlestyle)
