### ISSUE TITLE
[v4] | [v2] Importing BottomSheet results in undefined is not a function. 

### ISSUE THREAD

**Issue by OrcunGuler1** [gorhom/react-native-scroll-bottom-sheet#951]
# Bug

When importing the BottomSheet component or any other available component from the library @gorhom/bottom-sheet react-native throws error ```undefined is not a function```. I have included my package.json. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.0   |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.4.1   |

## Steps To Reproduce
[package.zip](https://github.com/gorhom/react-native-bottom-sheet/files/8740001/package.zip)

1. Create a react-native app,
2. Import the BottomSheet component

Describe what you expected to happen:

1. Create a react-native app,
2. Import the BottomSheet component,
3. Create a BottomSheet and fill it with children nodes.

**Comment by drplauska** [comment]
It'd be easier if you would provide a snack or repo instead of a zip

**Comment by OrcunGuler1** [comment]
@drplauska I'm aware but the file I've uploaded is a .json file and it does not allow me to upload that file here, so I've included as a zip file. Other than that there is nothing I can provide. I've tried a clean install of everything on my work computer. It just doesn't want to work. so I've decided to use another library. Hoping this would get fixed or I can get some insight on what's wrong. This library is much more flexible than the one I'm currently using and I would appreciate if anyone cold point me in the right direction.

**Comment by AmyrAhmady** [comment]
Getting the same error, not sure why, steps to reproduce?just import it and use the example

**Comment by clemensmol** [comment]
Getting the same error. Workaround: downgrade react-native-gesture-handler to 1.10...

This is weird.
After downgrading react-native-gesture-handler to 1.10 the problem was gone. I upgraded it to 2.2.1 no problem, even upgraded it back to 2.4.2 and the problem stayed away. 😕

**Comment by Vi-dot** [comment]
fixed it with `yarn start --reset-cache`

**Comment by drplauska** [comment]
> fixed it with `yarn start --reset-cache`

fresh start was working for me
