### ISSUE TITLE
[v4] | [v2] BottomSheetModal mounted before present is called

### ISSUE THREAD

**Issue by peeredNL** [gorhom/react-native-scroll-bottom-sheet#955]
# Bug

Documentation reads that the `present()` callback "mounts and presents the modal". However, the modal is mounted before I call the present method, and so data to be shown in the modal is fetched before the modal is presented. 

I don't want this behaviour as I want to re-fetch data as the modal is closed and presented a second time.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.4   |
| react-native                    | 0.66.2   |
| react-native-reanimated         | 2.2.4  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. When the `NewWorkout` page is loaded, the useEffect is immediately 
2. Closing the modal (in `startExercise` method) doesn't unmount the modal 

Describe what you expected to happen:

1. I want the modal to mount when the 'present' method is called.
2. Data should be fetched everytime the modal is presented

## Reproducible sample code

``` 
const NewWorkout: React.FC<PageProps> = ({navigation, route}) => {

  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current!.present();
  }, []);

  const startExercise = (item: Exercise) => {
    bottomSheetModalRef.current!.close();
    navigation.navigate('LogRoutine', {exercise: item});
  };

  return (
    <BottomSheetModalProvider>
      <ExerciseBottomSheet
        startExercise={exercise => startExercise(exercise)}
        createExercise={createExercise}
        ref={bottomSheetModalRef}
      />
   </BottomSheetModalProvider>
});
```

```
const ExerciseBottomSheet: React.FC<BottomSheetProps> = forwardRef(
  (props, ref: Ref<BottomSheetModal>) => {
    const [exercises, setExerciseList] = useState<Exercise[]>([]);

    useEffect(() => {
      console.log('in useEffect of exerciseBottomSheet');
      //fetch from API
      setExerciseList(response.data.results); 
    }, []);

    return (
      <BottomSheetModal
        ref={ref}
        index={1}
        snapPoints={['50%', '95%']}
        handleStyle={{
          backgroundColor: 'rgba(236, 164, 0, 0.050)',
        }}
        handleIndicatorStyle={{
          backgroundColor: EStyleSheet.value('$darkColor'),
        }}>
        // ...
      </BottomSheetModal>
    );
  },
);

**Comment by fa11erX** [comment]
same problem

**Comment by peeredNL** [comment]
@nixmove I found out that i can also achieve my goal to fetch data when reopening the modal by using the `useIsFocused` from `@react-navigation/native`. I'm not sure if this also works if you're not leaving the page that has the bottomSheetModal.
```
useEffect(() => {
  // get workout from database
  if (isFocused) {
    getExercises();
  }
}, [props, isFocused]);
```

**Comment by rommyarb** [comment]
You need to change the `index` value to `-1` to initiate the bottom sheet in closed state, as stated here: [https://gorhom.github.io/react-native-bottom-sheet/props#index](https://gorhom.github.io/react-native-bottom-sheet/props#index)

**Comment by ser-emejia** [comment]
Did you find a solution?

passing index value to -1 does not work for me, my BottomSheetModal still mounted before I called :/
