### ISSUE TITLE
[v4] Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-scroll-bottom-sheet#956]
# Bug
App freezes at white screen when using `BottomSheet` or `BottomSheetModal` component while remote Chrome debugger enabled.
It happens even when the component is absent on current screen.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4   |
| react-native                    | 0.68.1   |
| react-native-reanimated         | ^2.8.0   |
| react-native-gesture-handler    | ^2.1.0   |

## Steps To Reproduce

1. `git clone https://github.com/gorhom/react-native-bottom-sheet.git`
2. `cd example && yarn`
3. `yarn run android`
4. Open debug menu and enable remote debugger

Describe what you expected to happen:

1. When remote Chrome debugger enabled app doesn't freeze on white screen and works as intended

## Reproducible sample code
Code in the `example` folder of this repo

**Comment by RNR1** [comment]
I also experienced the same issue, I will add that this occurs for me on windows, running on Android, with similar dependencies.

**Comment by siva-444** [comment]
+1

**Comment by ronlobo01** [comment]
Any fix ?

**Comment by allanrlima** [comment]
+1

**Comment by renanbronchart** [comment]
+1, but only when I try to launch my debugger, react native debugger.

**Comment by ghost** [comment]
Closing this issue as it's related to react-native-reanimated which is being used under the hood of this library and doesn't support remote debugging. For those who experience this issue consider to use Flipper instead of any other debuggers.
