### ISSUE TITLE
Expose calculated drag value from snapPoint A to snapPoint B

### ISSUE THREAD

**Issue by kunalpan23** [gorhom/react-native-scroll-bottom-sheet#957]
# Feature Request

A method which that gives a calculated value from snapPoint 1 to snapPoint 2 (BI-Directional [Y axis])

`snap_points(["25%", "75%"])` 

This method will give us a calculated value of the user screen drag for the bottom sheet from `snap_point 1` to `snap_point 2` 

## Why it is needed

As i came across an animation which requires a certain value for a transition. 
this will work as the onScroll event call which will help and give the updated value each time when its scrolled to the `snap_point B`  from `snap_point A`

## Possible implementation

```
<BottomSheet 
      onBottomSheetScroll={( e, currentPosition, snapPoints ) =>  console.log(currentPosition, snapPoints) }
>
//  ...Content 
</BottomSheet>
```
 ### Code sample
/

**Comment by kunalpan23** [comment]
@gorhom hey please respond to this thread and let us know the status on this

**Comment by fukemy** [comment]
hmm do you find any solution @kunalpan23 ?
