### ISSUE TITLE
navigating to other "screen" on the same bottomsheet

### ISSUE THREAD

**Issue by ddikodroid** [gorhom/react-native-scroll-bottom-sheet#961]
# Feature Request
is it possible to do navigation to other "screen" on the same bottomsheet?
<img width="612" alt="Screenshot 2022-05-27 at 9 56 48 AM" src="https://user-images.githubusercontent.com/4207774/170626610-63120634-94bb-4452-ba3d-59418c85801f.png">

## Why it is needed
 it can be useful for filter choices on a bottomsheet

## Possible implementation
  i have no idea for this

### Code sample
  this too

**Comment by kunalpan23** [comment]
@ddikodroid why aren't you toggling between the components any specific reason?

**Comment by ddikodroid** [comment]
> @ddikodroid why aren't you toggling between the components any specific reason?

for now, that's what i am doing 😁

**Comment by kunalpan23** [comment]
@ddikodroid as per the docs there is no such feature that can navigate or handle stuffs on routings you can request for this feature cuz its an interesting feature 👍

**Comment by hirbod** [comment]
No offense, but I am not sure how you people read docs... You can fully integrate react-navigation (js-stack AND native-stack) into bottom sheet. I am doing this since months and it is working great.

https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration

https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NavigatorExample.tsx

https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NativeScreensExample.tsx

**Comment by kunalpan23** [comment]
> No offense, but I am not sure how you people read docs... You can fully integrate react-navigation (js-stack AND native-stack) into bottom sheet. I am doing this since months and it is working great.
> 
> 
> 
> https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration
> 
> 
> 
> https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NavigatorExample.tsx
> 
> 
> 
> https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NativeScreensExample.tsx

My bad I missed that

**Comment by ddikodroid** [comment]
> No offense, but I am not sure how you people read docs... You can fully integrate react-navigation (js-stack AND native-stack) into bottom sheet. I am doing this since months and it is working great.
> 
> https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration
> 
> https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NavigatorExample.tsx
> 
> https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/bare/src/screens/integrations/NativeScreensExample.tsx

thank you for pointing that out.

**Comment by ah584d** [comment]
@hirbod 
hi do you know If I can do the same thing with react-native-raw-bottom-sheet?
this is what we use in the app, and I can't navigate to another page from the bottom sheet.
thanks
