### ISSUE TITLE
[v4] keyboardBlurBehavior="restore" causes modal to reappear after being dismissed

### ISSUE THREAD

**Issue by jzxchiang1** [gorhom/react-native-scroll-bottom-sheet#964]
# Bug

On Android, if `keyboardBlurBehavior="restore` is set and the keyboard is open, if you try dismissing the modal by calling `ref.current?.dismiss()` the modal will disappear but quickly reappear. I believe it is due to timing... the keyboard takes time to dismiss but by the time it is counted as blurred, the modal is already gone so it reappears...?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.1   |
| react-native                    | 0.67.4   |
| react-native-reanimated         | 3.0.0-rc0   |
| react-native-gesture-handler    | 2.3.2   |

**Comment by magiskaoskar** [comment]
I have the same issue on iOS. Version `4.4.5`

**Comment by batuhansahan** [comment]
same issue on v5
