### ISSUE TITLE
[v4] | [v2] Backdrop doesn't show on index 0

### ISSUE THREAD

**Issue by OsamaAburabie** [gorhom/react-native-scroll-bottom-sheet#968]
# Bug

When I use the built-in **BottomSheetBackdrop** component. 
I couldn't make it appear on **index 0** it only works with index 1 and higher.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.1   |
| react-native                    | 0.68.2   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.2.1   |

## Steps To Reproduce

1. add a snap points array ["50%"]
2. import BottomSheetBackdrop from the library and add it to the bottom sheet component.
3. set the appearsOnIndex={0} on the BottomSheetBackdrop since I only have 1 snap point ["50%"].
 
Describe what you expected to happen:

1. I expected the backdrop to appear on index 0 or in other word when I open the bottom sheet but it didn't.

## Reproducible sample code
https://snack.expo.dev/@aburabie/bottom-sheet-v4-reproducible-issue-template

**Comment by nickschinestzki** [comment]
This is a very needed change. It appears that the `BottomSheetBackdrop` props `appearsOnIndex` (defaults to 1) is expected to be higher than the `disappearsOnIndex` (defaults to 0). Even if I overwrite the values, it still doesn't work. 

I believe to be a very common use-case to have modal with only one snap point like ["50%"], but, right now, with this configuration it seems more complicated than it needs to be.

**Comment by shop-fluencer** [comment]
same issue

**Comment by bcgilliom** [comment]
```
backdropComponent={(props) => (
          <BottomSheetBackdrop
            {...props}
            appearsOnIndex={0}
            disappearsOnIndex={-1}
          />
        )}
```

seems to work

**Comment by OsamaAburabie** [comment]
@bcgilliom worked thanks dude.

**Comment by Roka20012** [comment]
That happens because the default index to open Backdrop Component is 1

https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetBackdrop/constants.ts#L2

**Comment by Olixfills** [comment]
> ```
> backdropComponent={(props) => (
>           <BottomSheetBackdrop
>             {...props}
>             appearsOnIndex={0}
>             disappearsOnIndex={-1}
>           />
>         )}
> ```
> 
> seems to work

Works like a charm...
