### ISSUE TITLE
[v4] | [v2] Snap Point does not accept 1 value in BottomSheetModal

### ISSUE THREAD

**Issue by ahmetkuslular** [gorhom/react-native-scroll-bottom-sheet#970]
# Bug
snapPoint does not accept 1 value. in the Bottom Sheet Modal. The error message shown is as follows 
`'index' was provided but out of the provided snap points range! expected value to be between -1, 0`

docs page: https://gorhom.github.io/react-native-bottom-sheet/props/#snappoints

**not working**❌
`const snapPoints = useMemo(() => ['90%'], []);`

**working**✅
`const snapPoints = useMemo(() => ['20%' '90%'], []);`

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.1   |
| react-native                    | 0.66.4   |
| react-native-reanimated         | 2.4.0   |
| react-native-gesture-handler    | 2.2.0  |

## Steps To Reproduce
![Simulator Screen Shot - iPhone 11 - 2022-06-05 at 18 18 43](https://user-images.githubusercontent.com/17436691/172057659-5fcd7556-aef9-4984-a703-859e87340c1c.png)

## Reproducible sample code
https://snack.expo.dev/@ahmetkuslular/bottom-sheet-v4-reproducible-issue-template

**Comment by travisobregon** [comment]
You need to set the `index` prop to ` index={0}` on the `BottomSheetModal`.

**Comment by firstpersoncode** [comment]
> You need to set the `index` prop to ` index={0}` on the `BottomSheetModal`.


but what if we want the `BottomSheetModal` to be closed initially?

btw I ended up following your solution and it doesn't fix the error.
<img width="374" alt="Screenshot 2023-12-23 at 17 06 09" src="https://github.com/gorhom/react-native-bottom-sheet/assets/22312608/d39982cb-40de-4aad-9350-e3ff8fa6b945">
that's on IOS

**Comment by firstpersoncode** [comment]
I ended up console log the length of the snapPoints:
```
const snapPoints = useMemo(() => ['1%', '50%', '90%'], []);
console.log("snapPoints length", snapPoints.length);
```

and the outpout is:
```
info Reloading app...
 BUNDLE  ./index.js 

 BUNDLE  ./index.js 

 LOG  Running "CleanExpress" with {"rootTag":31,"initialProps":{}}
 LOG  snapPoints length 3
 LOG  snapPoints length 3
 ERROR  Invariant Violation: 'index' was provided but out of the provided snap points range! expected value to be between -1, 0

```

Somehow this library doesn't receive the actual snapPoints I pass or the error handler is not correct?

**Comment by rameesp** [comment]
`const snapPoints = useMemo(() => ['25%', '50%', '95%'], []);`

In order to keep the bottom sheet closed, initially set the index to -1

Here is my full code, hopes it will be helpful : 

```
<BottomSheet
        ref={someHook.bottomSheetRef}
        index={-1}
        enablePanDownToClose
        bottomInset={32}
        backgroundStyle={someStyle.bottomSheetStyle}
        snapPoints={dataFilterResultHook?.snapPoints}>
              <BottomSheetView style={someStyle.bottomSheetContainerStyle}>
                      ...........
               </BottomSheetView>
      </BottomSheet>
```

**Comment by vlad-datacat** [comment]
I have the same issue, I attempted to use 0, 1 and -1 values as index - no luck, always the same error. I declare snappoints like so const snapPoints = isAndroid() ? [16, 79, 145] : [40, 120, 200]; outside of component and code
 `<BottomSheet
      ref={bottomSheetRef}
      snapPoints={snapPoints}
      index={0}>` - this crash happens only the first time it ran on new device, subsequent runs are all good, unless I set `enableDynamicSizing` to true - adding that prop to the mix makes it crash every single refresh. Now failing all initial device tests in Google play store pre-launch. I've attempted to patch the package searching through validators and checks but had no luck.

**Comment by andrecrimb** [comment]
From my debugging I could notice that the issue is mainly in `useNormalizedSnapPoints`(`gorhom/bottom-sheet/src/hooks/useNormalizedSnapPoints`), where an array with only a **single snappoint** get's returned in some cases (eg. if !isContainerLayoutReady), without considering the number of snap points first informed. 
In my case, I had a BS with 2 snap points and I was trying to snap it proactively using `useEffect` when `isContainerLayoutReady` was still false.

**Comment by AlirezaHadjar** [comment]
I'm also having some sentry crashes with this exact error message but my bottom sheet snap point array always has more than 2 items. I tried to patch `useNormalizedSnapPoints ` to not return a default snap point and workaround it.

[@gorhom+bottom-sheet+4.6.4.patch](https://github.com/user-attachments/files/18649007/%40gorhom%2Bbottom-sheet%2B4.6.4.patch)

**Comment by IsTheJack** [comment]
**Workaround suggestion here:**

I had this issue today and noticed that the reason why it happened to me was because I had conditional rendering inside the `BottomSheet`. So I put this hack as BottomSheet child

```jsx
<BottomSheet
   {...allPropsYouNeedToMakeItWork}
>
  {/* put it somewhere inside BottomSheet */}
  <BottomSheetView children={undefined} />
</BottomSheet>
```

Then the the error didn't happen anymore

**Comment by StevePhuc** [comment]
`because I had conditional rendering inside the BottomSheet`

same with me, after remove the conditional rendering it worked

**Comment by u-Aymane** [comment]
```
<BottomSheet
   {...allPropsYouNeedToMakeItWork}
>
  {/* put it somewhere inside BottomSheet */}
  <BottomSheetView children={undefined} />
</BottomSheet>
```

This works!
