### ISSUE TITLE
[v4] Bottom sheet index changes (hence opens) when navigating back to screen

### ISSUE THREAD

**Issue by bjarn** [gorhom/react-native-scroll-bottom-sheet#972]
# Bug

Since updating from Expo 44 to Expo 45 (including RN 0.68.2 and react-native-gesture-handler 2.2.1) the bottom sheet of one screen opens when you navigate to a different screen using the bottom tab navigator and then back to that previous screen which has the bottom sheet.

When logging the onChange callback, it updates the index to the latest in the array. Even with nothing interacting with the bottom sheet.

Downgrading to 4.2.1 or rngh 2.1.0 does not seem to help. Hence I believe it's related to the react native version.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.1   |
| react-native                    | 0.68.2   |
| react-native-reanimated         | 2.8.0  |
| react-native-gesture-handler    | 2.2.1   |

## Steps To Reproduce

1. Create a simple bottom tab navigator with 2 pages.
2. Add bottom sheet to page 1 like this: 
```jsx 
     <BottomSheet
        // ref={bottomSheetRef}
        index={-1}
        snapPoints={['50%']}
        // onChange={handleSheetChanges}
        backgroundStyle={{
          backgroundColor: theme.backgroundDimmed,
        }}
        enablePanDownToClose
      >
        <View>
          <Text>just some text</Text>
        </View>
      </BottomSheet>
```
3. Navigate to other screen and then navigate back by pressing on the bottom tab
4. Bottom sheet is now open, even though nothing interacts with it.

Describe what you expected to happen:

1. Bottom sheet remains closed like previous versions.

**Comment by bjarn** [comment]
Small update;

I have added `sceneAnimationEnabled` to my stack navigator and it fixed the issue. I was just playing around, though. Do not believe this is a good fix, but might be a step in the direction of finding the bug

<img width="600" alt="CleanShot 2022-06-06 at 17 04 48@2x" src="https://user-images.githubusercontent.com/14638441/172188438-645d63c7-ccbc-4c8a-a974-476abcb945ee.png">
.

**Comment by EdgardoV** [comment]
Hi everyone!, Another better solution?

**Comment by bjarn** [comment]
Still an issue, want to prevent closing this tbf :)

**Comment by ronlobo01** [comment]
+1 @bjarn  This is still an issue, I am facing this on release build. When i `navigate()` from Screen 1 to Screen 2, Then `navigate()` back to Screen 1 as I am pass props, the BottomSheet opens !.

Need some help here!

**Comment by RGdevz** [comment]
+1

**Comment by ronlobo01** [comment]
I kinda fixed it, My scenario was the Screen 2 had Keyboard **open**, on navigating Screen 1, It looks like the keyboard from the previous screen was triggering the BottomSheet to open (I don't know why), Hence, I `dismiss()` the keyboard before navigating, which did the trick. `Keyboard` is a component provided by react-native.

**Comment by OfficialDarkComet** [comment]
It likely is unmounted and then goes back to the default index value that is set for the index prop. I answered another issue and it may have the same solution:

https://github.com/gorhom/react-native-bottom-sheet/issues/204#issuecomment-1214180969

**Comment by german2114** [comment]
As @ronlobo01  said, the issue happens when your Screen 2 has keyboard open or you call dismiss at the same time you go back screen

**Comment by iway1** [comment]
happened to me when I navigated and called `bottomSheet.forceClose()` at the same time. I fixed it by moving the bottom sheet to be outside of the `NavigationContainer` component, rather than being a child of it

**Comment by edwinvrgs** [comment]
This issue is still happening for me, we got a workaround wrapping it inside a `Portal`, but now we need to implement this: https://github.com/gorhom/react-native-bottom-sheet/issues/1389#issuecomment-1608857169, and having the `Portal` just makes the screen froze.

**Comment by Rohit3523** [comment]
Facing the same issue

**Comment by abdymm** [comment]
do you guys find a workaround for this issue?
