### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by shop-fluencer** [gorhom/react-native-scroll-bottom-sheet#982]
# Bug

I get this error message:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

## Environment info

@gorhom 

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4   |
| react-native                    | x.x.x   |
| react-native-reanimated         |  2.6.0  |
| react-native-gesture-handler    | 2.2.1   |

## Steps To Reproduce

this error comes when I use this:
`<NativeViewGestureHandler disallowInterruption={true}>`

If I remove this, it works. Can anyone help me what I am doing wrong ?

## Reproducible sample code

Code:

```
import { StyleSheet, Text, View } from 'react-native'
import React, { forwardRef, useMemo } from 'react'
import { BottomSheetBackdrop, BottomSheetModal } from '@gorhom/bottom-sheet';
import { IModalProductByProps } from './Model';
import { NativeViewGestureHandler } from 'react-native-gesture-handler';
import SelectOptionsRLV from '../../SelectOptionsRLV/SelectOptionsRLV';

const ModalProductBy = forwardRef<BottomSheetModal, IModalProductByProps>(({}, ref) => {
  const snapPoints = useMemo(() => ['25%', '50%'], []);
  return (
    <BottomSheetModal
      ref={ref}         
       index={1}
      snapPoints={snapPoints}
      backdropComponent={BottomSheetBackdrop}
      >
      <NativeViewGestureHandler disallowInterruption={true}>
        <SelectOptionsRLV 
          datas={['s', 'as', 'a', 'r', 't', 'v', 'a', 'r']}
          activeOptions={['s']}
        />
      </NativeViewGestureHandler>
    </BottomSheetModal>
  )
});
```

**Comment by fukemy** [comment]
read document about useImperativeHandle, your code totally wrong

**Comment by marcogravbrot** [comment]
> read document about useImperativeHandle, your code totally wrong

This is exactly what the documentation says to do...

https://gorhom.dev/react-native-bottom-sheet/troubleshooting#my-component-gesture-interaction-gets-conflicted-with-bottom-sheet-interactions-
