### ISSUE TITLE
[v4] BottomSheetScrollView not scrolling full content height

### ISSUE THREAD

**Issue by janroures** [gorhom/react-native-scroll-bottom-sheet#986]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.2   |
| react-native                    | 0.68.1   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.4.1   |

## Steps To Reproduce

1. Create a simple View which takes full screen height
2. Put a simple BottomSheet with a BottomSheetScrollView inside which content is 3000px height
3. Try to scroll to the bottom of BottomSheetScrollView

Describe what you expected to happen:

1. BottomSheetScrollView should scroll to the bottom of the content (the 'green' view provided in the snack below)

## Reproducible sample code
https://snack.expo.dev/QXNcNm7TI

**Comment by janroures** [comment]
I found a solution, it's really important to have the bottom sheet wrapped in a view with flex: 1. I am using the sheet on the top level of the app tree and I fixed it by wrapping the whole <App/> inside a <View style={{flex:1}}/>

**Comment by wkoutre** [comment]
I [made a PR for this](https://github.com/gorhom/react-native-bottom-sheet/pull/853) to add to documentation back in February 😅.

**Comment by ibraheem88** [comment]
@janroures Did you find any solution?
