### ISSUE TITLE
[v4] BottomSheetScrollView does not scroll as expected

### ISSUE THREAD

**Issue by lachenmayer** [gorhom/react-native-scroll-bottom-sheet#989]
# Bug

Hi Mo, sorry for the vague issue title, but I've tried a bunch of platform/version combinations and they produce different behavior.

The [repro](https://snack.expo.dev/@lachenmayer/great-croissant) has the simplest possible setup:

```tsx
<View style={styles.container}>
  <BottomSheet snapPoints={['50%', '80%']}>
    <BottomSheetScrollView style={{ flex: 1, backgroundColor: 'red' }}>
      <View style={{ height: 100, backgroundColor: 'blue' }} />
      <View style={{ height: 100, backgroundColor: 'green' }} />
      // ...etc, these views are repeated a bunch of times
```

I tested this separately on:

1. iOS, Expo 44 & Expo 45 - same behavior
2. Android, Expo 44 - can not scroll at all
3. Android, Expo 45 - crashes with #971

## Environment info

Expo 45:

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.2   |
| react-native                    | (whatever comes with Expo 45)   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.2.1   |

Expo 44:

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.3.2   |
| react-native                    | (whatever comes with Expo 44)   |
| react-native-reanimated         | 2.3.1   |
| react-native-gesture-handler    | 2.1.0   |

### iOS

https://user-images.githubusercontent.com/38614/174055057-ec112ac1-3fe2-4271-b32f-4b6e16a29c23.MP4

In this video, I am doing the following:

1. Swiping up/down on the scroll view - nothing happens. ❌ I expect the bottom sheet to expand when swiping up.
2. Swiping up on the handle view (white bg) - this lets me expand the bottom sheet. ✅
3. Scrolling the scroll view down - this works while expanded. ✅
4. Scrolling the scroll view up. ❌ I expect to not see the red view, but the bottom sheet instead snapping to the smaller snap point.
5. Swiping down on the handle works, this has the same behavior as in state 1.

### Android

https://user-images.githubusercontent.com/38614/174056171-1f56c683-7e3a-4815-a9b4-8aa9a8bf8ba4.mp4

You can see the touches on this, this unfortunately does not work at all.

## Reproducible sample code

https://snack.expo.dev/@lachenmayer/great-croissant

**Comment by grgmgd** [comment]
Facing same issue with SDK 45 on iOS, backdrop presses pass through as well. Probably something related to RNGH

**Comment by IagoR0cha** [comment]
Same problem here on iOS with SDK 45

**Comment by mounirkanane** [comment]
Same problem here, when it's expanded scrolling works fine, but when in "50%" mode the scrolling doesn't work. Any solution?

**Comment by grgmgd** [comment]
I found out it only happens on "Expo Go". Building the app using `eas` and testing on the final version or even a custom dev client resolves the issue for me.

**Comment by danshilm** [comment]
Unstale

**Comment by AndreiCalazans** [comment]
Not sure if directly related to OP but react-native-gesture-handler 2.5.0 seems to have a regression https://github.com/software-mansion/react-native-gesture-handler/issues/2160

**Comment by AndreiCalazans** [comment]
I was having similar issue with @gorhom/bottom-sheet and we just didn't have `GestureHandlerRootView` properly wrapping the root of the app case someone has similar issue. - https://docs.swmansion.com/react-native-gesture-handler/docs/installation/#js

**Comment by naytun** [comment]
Usually the solution is:
```
import { GestureHandlerRootView } from 'react-native-gesture-handler'
...
return (
  <GestureHandlerRootView>
   ... your component here
  </GestureHandlerRootView>
)
```
