### ISSUE TITLE
[v4] Disable close on touch outside

### ISSUE THREAD

**Issue by derekstavis** [gorhom/react-native-scroll-bottom-sheet#992]
# Feature Request

Introduce a property pretty much like `enablePanDownToClose` that can be set to `false` to disable closing with a gesture, but for disabling closing with a touch outside of the bottom sheet.

## Why it is needed

This is relevant when the sheet is performing a busy action and one would not like the user to dismiss the sheet intentionally or unintentionally.

## Possible implementation

Add a property `enableTouchOutsideToClose` that can be set to `false` in such cases.

**Comment by derekstavis** [comment]
Rude! I followed the template but removed the non-relevant parts!

**Comment by tsemerad** [comment]
@derekstavis There is already a way to do this. You need to set custom a `backdropComponent` prop. Pass in the `BottomSheetBackdrop` component, setting the [`pressBehavior` prop](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop#pressbehavior) to `'none'`.

**Comment by nippysky** [comment]
The Press behavior props still dont work for me
