### ISSUE TITLE
[v4] Disable close on touch outside

### ISSUE THREAD

**Issue by derekstavis** [gorhom/react-native-scroll-bottom-sheet#993]
# Feature Request

Introduce a property pretty much like `enablePanDownToClose` that can be set to `false` to disable closing with a gesture, but for disabling closing with a touch outside of the bottom sheet.

## Why it is needed

This is relevant when the sheet is performing a busy action and one would not like the user to dismiss the sheet intentionally or unintentionally.

## Possible implementation

Add a property `enableTouchOutsideToClose` that can be set to `false` in such cases.

### Code sample

```jsx
<BottomSheet
  enablePanDownToClose={false}
  enableTouchOutsideToClose={false}
/>
```

**Comment by freemanUA** [comment]
faced similar issue, you can already do it with BottomSheetBackdrop shipped component, just check example app

**Comment by YuryDG** [comment]
Hi Team, 
Is there any update related to this? 
is this already implemented?

**Comment by andrehadianto** [comment]
up. is there any update on this?

**Comment by thakkur** [comment]
I got the same issue.  i fixed as the following way, 

pass set pressBehavior={'none'} in renderBackdrop


```

  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        {...props}
        pressBehavior={'none'}
        appearsOnIndex={1}
        animatedIndex={{
          value: 1,
        }}
      />
    ),
    [],
  );
```

**Comment by Giasinit** [comment]
This worked for me:
```Javascript
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={1}
        onPress={handleClosePress}
        animatedIndex={{
          value: 1,
        }}
      />
    ),
    [],
  );
```

**Comment by SOHAMPATEL1483** [comment]
> I got the same issue. i fixed as the following way,
> 
> pass set pressBehavior={'none'} in renderBackdrop
> 
> ```
> 
>   const renderBackdrop = useCallback(
>     props => (
>       <BottomSheetBackdrop
>         {...props}
>         pressBehavior={'none'}
>         appearsOnIndex={1}
>         animatedIndex={{
>           value: 1,
>         }}
>       />
>     ),
>     [],
>   );
> ```

Above code works with minor change `pressBehavior={"close"}`
