### ISSUE TITLE
[v4] | [v2] How to disable this modal on initial render

### ISSUE THREAD

**Issue by 3KINGZ** [gorhom/react-native-scroll-bottom-sheet#999]
# Bug

Anyway to disable this modal on initial render?

1. Modal always open on initial render
2.
3. 

Describe what you expected to happen:

1. a prop to disable modal on mount
2.

**Comment by 3KINGZ** [comment]
@gorhom

**Comment by turker0** [comment]
index={-1}
https://gorhom.github.io/react-native-bottom-sheet/props#index

**Comment by fuadrifki** [comment]
hello I'm also experiencing the same issue, when I open it on android, when the initial render will expand bottom-sheet, while on ios it doesn't happen. even when i select text input sometimes bottom-sheet auto expand. I've filled the initial index value is -1, but it doesn't affect it and still expands during initial rendering
cc @gorhom

**Comment by fukemy** [comment]
i am using state to render <BottomSheet> , it's work normally

**Comment by fukemy** [comment]
with index=-1. It's cause some anoying bottom padding problem after first time change index
